"use client"

import { useState } from "react"
import { Check, Copy, ExternalLink } from "lucide-react"
import { EnergyPasswordGuard } from "@/components/energy-password-guard"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { useLanguage } from "@/lib/hooks/use-language"

type Tab="mqtt"|"node-red"|"vrm"|"grafana"
const COPY={
 en:{title:"Integration documentation",description:"Operational guides for Victron data integration",copy:"Copy",copied:"Copied",steps:"Setup steps",topics:"Key topics",endpoints:"Available endpoints",architecture:"Architecture",mqttTitle:"MQTT integration with Cerbo GX",mqttDesc:"Real-time data through the Cerbo GX MQTT service.",mqttSteps:["Enable MQTT on the Cerbo GX / Venus OS installation.","Confirm broker address and port before connecting external consumers.","Subscribe only to the topics required by the monitoring workflow."],nodeTitle:"Node-RED flow for Victron data",nodeDesc:"Low-code processing between MQTT and operational storage or dashboards.",nodeSteps:["Enable Node-RED in Venus OS Large.","Install the MQTT and InfluxDB nodes required by the flow.","Connect the input node to the Cerbo GX broker.","Validate payloads before writing data or creating alerts."],vrmTitle:"Victron VRM JSON REST API",vrmDesc:"Cloud API for authorized system monitoring and historical retrieval.",vrmSteps:["Register and link the installation in VRM.","Generate an API token in the authorized account.","Keep tokens server-side and never expose them in client code.","Validate installation IDs and API responses before persistence."],grafanaTitle:"Grafana with InfluxDB",grafanaDesc:"Visualization stack for telemetry already collected from Victron.",grafanaSteps:["Deploy InfluxDB and Grafana in a controlled environment.","Send validated Victron measurements to InfluxDB.","Create dashboards from stable measurement names and tags.","Define alert thresholds only after validating operational ranges."],security:"Security note",securityText:"Examples use placeholders. Do not commit real tokens, passwords, installation IDs or internal hostnames."},
 es:{title:"Documentación de integraciones",description:"Guías operativas para integrar datos Victron",copy:"Copiar",copied:"Copiado",steps:"Pasos de configuración",topics:"Topics principales",endpoints:"Endpoints disponibles",architecture:"Arquitectura",mqttTitle:"Integración MQTT con Cerbo GX",mqttDesc:"Datos en tiempo real mediante el servicio MQTT de Cerbo GX.",mqttSteps:["Habilita MQTT en la instalación Cerbo GX / Venus OS.","Confirma dirección y puerto del broker antes de conectar consumidores externos.","Suscríbete sólo a los topics requeridos por el flujo de monitoreo."],nodeTitle:"Flujo Node-RED para datos Victron",nodeDesc:"Procesamiento low-code entre MQTT y almacenamiento operativo o dashboards.",nodeSteps:["Habilita Node-RED en Venus OS Large.","Instala los nodos MQTT e InfluxDB necesarios para el flujo.","Conecta el nodo de entrada al broker del Cerbo GX.","Valida los payloads antes de persistir datos o crear alertas."],vrmTitle:"API JSON REST de Victron VRM",vrmDesc:"API cloud para monitoreo autorizado y consulta histórica del sistema.",vrmSteps:["Registra y vincula la instalación en VRM.","Genera un token API en la cuenta autorizada.","Mantén los tokens server-side y nunca los expongas en código cliente.","Valida IDs de instalación y respuestas API antes de persistir."],grafanaTitle:"Grafana con InfluxDB",grafanaDesc:"Stack de visualización para telemetría Victron ya recolectada.",grafanaSteps:["Despliega InfluxDB y Grafana en un entorno controlado.","Envía mediciones Victron validadas a InfluxDB.","Construye dashboards con nombres y tags de medición estables.","Define umbrales de alerta sólo después de validar rangos operativos."],security:"Nota de seguridad",securityText:"Los ejemplos usan placeholders. No guardes tokens, contraseñas, IDs de instalación ni hostnames internos reales en el repositorio."},
 de:{title:"Integrationsdokumentation",description:"Operative Leitfäden zur Integration von Victron-Daten",copy:"Kopieren",copied:"Kopiert",steps:"Einrichtungsschritte",topics:"Wichtige Topics",endpoints:"Verfügbare Endpoints",architecture:"Architektur",mqttTitle:"MQTT-Integration mit Cerbo GX",mqttDesc:"Echtzeitdaten über den MQTT-Dienst des Cerbo GX.",mqttSteps:["MQTT auf der Cerbo-GX-/Venus-OS-Installation aktivieren.","Broker-Adresse und Port vor externen Verbindungen bestätigen.","Nur die für den Monitoring-Workflow benötigten Topics abonnieren."],nodeTitle:"Node-RED-Flow für Victron-Daten",nodeDesc:"Low-Code-Verarbeitung zwischen MQTT und operativem Speicher oder Dashboards.",nodeSteps:["Node-RED in Venus OS Large aktivieren.","Benötigte MQTT- und InfluxDB-Nodes installieren.","Eingangsknoten mit dem Cerbo-GX-Broker verbinden.","Payloads vor Speicherung oder Alarmerstellung validieren."],vrmTitle:"Victron VRM JSON REST API",vrmDesc:"Cloud-API für autorisiertes Monitoring und historische Abfragen.",vrmSteps:["Installation in VRM registrieren und verknüpfen.","API-Token im autorisierten Konto erzeugen.","Tokens serverseitig halten und niemals im Client-Code offenlegen.","Installations-IDs und API-Antworten vor Persistierung validieren."],grafanaTitle:"Grafana mit InfluxDB",grafanaDesc:"Visualisierungsstack für bereits erfasste Victron-Telemetrie.",grafanaSteps:["InfluxDB und Grafana in kontrollierter Umgebung bereitstellen.","Validierte Victron-Messwerte an InfluxDB senden.","Dashboards mit stabilen Messnamen und Tags erstellen.","Alarmgrenzen erst nach Validierung der Betriebsbereiche definieren."],security:"Sicherheitshinweis",securityText:"Die Beispiele verwenden Platzhalter. Keine echten Tokens, Passwörter, Installations-IDs oder internen Hostnamen im Repository speichern."},
} as const
const snippets={mqtt:`# Cerbo GX MQTT\nmosquitto_sub -h <cerbo-ip> -p 1883 -t "N/+/system/#" -v\nmosquitto_sub -h <cerbo-ip> -p 1883 -t "N/+/#" -v`,"node-red":`[{"id":"victron_mqtt_in","type":"mqtt in","topic":"N/+/system/0/Dc/Battery/Soc","qos":"2"},{"id":"parse_soc","type":"json"},{"id":"influx_out","type":"influxdb out","measurement":"battery_soc","database":"victron_energy"}]`,vrm:`const endpoint = "https://vrmapi.victronenergy.com/v2";\nconst installationId = "YOUR_INSTALLATION_ID";\nconst token = "YOUR_API_TOKEN";\nfetch(\`\${endpoint}/installations/\${installationId}/devices\`, { headers: { "X-Authorization": \`Bearer \${token}\` } });`,grafana:`services:\n  influxdb:\n    image: influxdb:2.6\n    ports: ["8086:8086"]\n  grafana:\n    image: grafana/grafana:latest\n    ports: ["3000:3000"]`} satisfies Record<Tab,string>
const topics=["N/+/system/0/Dc/Battery/Soc","N/+/system/0/Dc/Battery/Voltage","N/+/system/0/Dc/Battery/Current","N/+/solar/+/Dc/0/Power","N/+/vebus/+/Ac/ActiveIn/L1/P"]
const endpoints=["GET /installations/{id}/devices","GET /installations/{id}/logdata","GET /sites/{id}"]
export default function IntegrationDocs(){const{language}=useLanguage();const lang=(language in COPY?language:"en") as keyof typeof COPY;const c=COPY[lang];const[tab,setTab]=useState<Tab>("mqtt");const[copied,setCopied]=useState<Tab|null>(null);const meta={mqtt:{title:c.mqttTitle,desc:c.mqttDesc,steps:c.mqttSteps},"node-red":{title:c.nodeTitle,desc:c.nodeDesc,steps:c.nodeSteps},vrm:{title:c.vrmTitle,desc:c.vrmDesc,steps:c.vrmSteps},grafana:{title:c.grafanaTitle,desc:c.grafanaDesc,steps:c.grafanaSteps}}[tab];async function copy(){await navigator.clipboard.writeText(snippets[tab]);setCopied(tab);setTimeout(()=>setCopied(null),1500)}return <EnergyPasswordGuard><AppLayout><div className="space-y-6 p-4 sm:p-6"><PageHeader title={c.title} description={c.description}/><div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-wrap gap-2 border-b">{(["mqtt","node-red","vrm","grafana"] as Tab[]).map(item=><button key={item} onClick={()=>setTab(item)} className={`border-b-2 px-4 py-3 text-sm font-medium uppercase ${tab===item?"border-primary text-primary":"border-transparent text-muted-foreground"}`}>{item==="vrm"?"VRM API":item==="node-red"?"Node-RED":item.toUpperCase()}</button>)}</div><Card><CardHeader><CardTitle>{meta.title}</CardTitle><CardDescription>{meta.desc}</CardDescription></CardHeader><CardContent className="space-y-6"><ol className="list-decimal space-y-2 pl-5 text-sm text-muted-foreground">{meta.steps.map(step=><li key={step}>{step}</li>)}</ol><div className="rounded-lg border bg-accent/30 p-4"><div className="mb-3 flex items-center justify-between"><span className="font-mono text-sm">{tab}</span><button onClick={()=>void copy()} className="flex items-center gap-1 rounded bg-primary px-2 py-1 text-xs text-primary-foreground">{copied===tab?<><Check className="h-3 w-3"/>{c.copied}</>:<><Copy className="h-3 w-3"/>{c.copy}</>}</button></div><pre className="overflow-x-auto rounded bg-background p-3 text-xs">{snippets[tab]}</pre></div>{tab==="mqtt"&&<div className="space-y-2">{topics.map(topic=><code key={topic} className="block rounded bg-muted p-2 text-xs">{topic}</code>)}</div>}{tab==="vrm"&&<div className="space-y-2">{endpoints.map(endpoint=><code key={endpoint} className="block rounded bg-muted p-2 text-xs">{endpoint}</code>)}</div>}{tab==="grafana"&&<p className="text-sm text-muted-foreground">Victron Cerbo GX → Node-RED → InfluxDB → Grafana</p>}{tab==="node-red"&&<p className="flex gap-2 rounded border p-3 text-sm text-muted-foreground"><ExternalLink className="h-4 w-4"/>Venus OS Large · Node-RED: <code>http://&lt;cerbo-ip&gt;:1880</code></p>}</CardContent></Card><Card><CardContent className="pt-6"><p className="font-medium">{c.security}</p><p className="mt-1 text-sm text-muted-foreground">{c.securityText}</p></CardContent></Card></div></div></AppLayout></EnergyPasswordGuard>}
