"use client"

import type React from "react"
import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"
import { ArrowLeft, ClipboardList, Plus } from "lucide-react"

interface ProcurementRequest { id: string; request_number: string | null; title: string; category: string; quantity: number; unit: string; estimated_budget_clp: number | null; priority: "low" | "normal" | "high" | "critical"; status: "draft" | "submitted" | "under_review" | "approved" | "rejected" | "converted"; required_date: string | null; commune: string; created_at: string }
type ProcurementLocation = { id: string; name: string }

const initialForm = { title: "", description: "", business_justification: "", category: "Supplies", quantity: "1", unit: "unidad", estimated_budget_clp: "", priority: "normal", status: "submitted", required_date: "", region: "Los Ríos", commune: "Valdivia", location_id: "", delivery_location: "" }
const LOCALES = { en: "en-US", es: "es-CL", de: "de-DE" } as const
const COPY = {
  en: { title: "Procurement requests", description: "Operational requirements connected to their complete procurement lifecycle", currentOrders: "Current orders", newRequest: "New request", genericError: "Procurement requests could not be loaded or saved.", missingLocation: "Select the property or operational location for the request.", expiredSession: "Your session expired. Sign in again before registering the request.", total: "Total", submitted: "Submitted", underReview: "Under review", approved: "Approved", internalRequirements: "Internal requirements", internalDetail: "Open any request to follow quotation, approval, order, receiving and stock intake from a single object.", number: "Number", request: "Request", category: "Category", quantity: "Quantity", budget: "Budget", commune: "Commune", requiredDate: "Required date", priority: "Priority", state: "Status", loading: "Loading requests…", empty: "No procurement requests registered.", pending: "Pending", newRequestTitle: "New procurement request", fieldTitle: "Title", titlePlaceholder: "E.g. cleaning supplies for monthly operations", fieldDescription: "Description", descriptionPlaceholder: "Specifications, quality and required scope", justification: "Business justification", justificationPlaceholder: "Why it is required and which operation depends on this purchase", equipment: "Equipment", supplies: "Supplies", services: "Services", maintenance: "Maintenance", construction: "Construction", other: "Other", low: "Low", normal: "Normal", high: "High", critical: "Critical", unit: "Unit", budgetClp: "Budget CLP", location: "Property / operational location", locationPlaceholder: "Select a property", deliveryDetail: "Delivery location detail", deliveryPlaceholder: "Warehouse, building, access or instructions", scopeHint: "The selected property defines the operational scope. Delivery detail is only a human instruction and does not replace the canonical location.", cancel: "Cancel", saving: "Saving…", register: "Register request" },
  es: { title: "Solicitudes de compra", description: "Requerimientos operativos conectados a su ciclo completo de compra", currentOrders: "Órdenes actuales", newRequest: "Nueva solicitud", genericError: "No fue posible cargar o guardar las solicitudes de compra.", missingLocation: "Selecciona la propiedad o ubicación operacional de la solicitud.", expiredSession: "La sesión expiró. Vuelve a iniciar sesión antes de registrar la solicitud.", total: "Total", submitted: "Enviadas", underReview: "En revisión", approved: "Aprobadas", internalRequirements: "Requerimientos internos", internalDetail: "Abre cualquier solicitud para seguir cotización, aprobación, orden, recepción e ingreso a stock desde un solo objeto.", number: "Número", request: "Solicitud", category: "Categoría", quantity: "Cantidad", budget: "Presupuesto", commune: "Comuna", requiredDate: "Fecha requerida", priority: "Prioridad", state: "Estado", loading: "Cargando solicitudes…", empty: "No hay solicitudes registradas.", pending: "Pendiente", newRequestTitle: "Nueva solicitud de compra", fieldTitle: "Título", titlePlaceholder: "Ej. Insumos de limpieza para operación mensual", fieldDescription: "Descripción", descriptionPlaceholder: "Especificaciones, calidad y alcance requerido", justification: "Justificación del negocio", justificationPlaceholder: "Por qué se requiere y qué operación depende de esta compra", equipment: "Equipamiento", supplies: "Insumos", services: "Servicios", maintenance: "Mantención", construction: "Construcción", other: "Otro", low: "Baja", normal: "Normal", high: "Alta", critical: "Crítica", unit: "Unidad", budgetClp: "Presupuesto CLP", location: "Propiedad / ubicación operacional", locationPlaceholder: "Selecciona una propiedad", deliveryDetail: "Detalle del lugar de entrega", deliveryPlaceholder: "Bodega, edificio, acceso o instrucciones", scopeHint: "La propiedad seleccionada define el scope operacional. El detalle de entrega es solo una instrucción humana y no reemplaza la ubicación canónica.", cancel: "Cancelar", saving: "Guardando…", register: "Registrar solicitud" },
  de: { title: "Beschaffungsanforderungen", description: "Operative Anforderungen entlang ihres vollständigen Beschaffungszyklus", currentOrders: "Aktuelle Bestellungen", newRequest: "Neue Anforderung", genericError: "Beschaffungsanforderungen konnten nicht geladen oder gespeichert werden.", missingLocation: "Wähle die Immobilie oder den operativen Standort der Anforderung aus.", expiredSession: "Deine Sitzung ist abgelaufen. Melde dich erneut an, bevor du die Anforderung erfasst.", total: "Gesamt", submitted: "Eingereicht", underReview: "In Prüfung", approved: "Freigegeben", internalRequirements: "Interne Anforderungen", internalDetail: "Öffne eine Anforderung, um Angebot, Freigabe, Bestellung, Annahme und Bestandszugang in einem Objekt zu verfolgen.", number: "Nummer", request: "Anforderung", category: "Kategorie", quantity: "Menge", budget: "Budget", commune: "Kommune", requiredDate: "Bedarfsdatum", priority: "Priorität", state: "Status", loading: "Anforderungen werden geladen…", empty: "Keine Anforderungen vorhanden.", pending: "Ausstehend", newRequestTitle: "Neue Beschaffungsanforderung", fieldTitle: "Titel", titlePlaceholder: "Z. B. Reinigungsmittel für den Monatsbetrieb", fieldDescription: "Beschreibung", descriptionPlaceholder: "Spezifikationen, Qualität und erforderlicher Umfang", justification: "Geschäftliche Begründung", justificationPlaceholder: "Warum die Beschaffung erforderlich ist und welcher Betrieb davon abhängt", equipment: "Ausrüstung", supplies: "Verbrauchsmaterial", services: "Dienstleistungen", maintenance: "Instandhaltung", construction: "Bau", other: "Sonstiges", low: "Niedrig", normal: "Normal", high: "Hoch", critical: "Kritisch", unit: "Einheit", budgetClp: "Budget CLP", location: "Immobilie / operativer Standort", locationPlaceholder: "Immobilie auswählen", deliveryDetail: "Details zum Lieferort", deliveryPlaceholder: "Lager, Gebäude, Zugang oder Hinweise", scopeHint: "Die gewählte Immobilie definiert den operativen Scope. Lieferhinweise sind nur menschliche Anweisungen und ersetzen nicht den kanonischen Standort.", cancel: "Abbrechen", saving: "Wird gespeichert…", register: "Anforderung erfassen" },
} as const
const CATEGORY = { Equipment: "equipment", Supplies: "supplies", Services: "services", Maintenance: "maintenance", Construction: "construction", Other: "other" } as const
const STATUS = { en: { draft: "Draft", submitted: "Submitted", under_review: "Under review", approved: "Approved", rejected: "Rejected", converted: "Converted" }, es: { draft: "Borrador", submitted: "Enviada", under_review: "En revisión", approved: "Aprobada", rejected: "Rechazada", converted: "Convertida" }, de: { draft: "Entwurf", submitted: "Eingereicht", under_review: "In Prüfung", approved: "Freigegeben", rejected: "Abgelehnt", converted: "Umgewandelt" } } as const
const PRIORITY = { en: { low: "Low", normal: "Normal", high: "High", critical: "Critical" }, es: { low: "Baja", normal: "Normal", high: "Alta", critical: "Crítica" }, de: { low: "Niedrig", normal: "Normal", high: "Hoch", critical: "Kritisch" } } as const

function statusClass(status: ProcurementRequest["status"]) { switch (status) { case "approved": return "border-green-500/40 text-green-500"; case "rejected": return "border-red-500/40 text-red-500"; case "under_review": return "border-blue-500/40 text-blue-500"; case "converted": return "border-purple-500/40 text-purple-500"; case "submitted": return "border-amber-500/40 text-amber-500"; default: return "" } }

export default function ProcurementRequestsPage() {
  const { language } = useLanguage()
  const lang = (language in COPY ? language : "en") as keyof typeof COPY
  const copy = COPY[lang]
  const locale = LOCALES[lang]
  const [requests, setRequests] = useState<ProcurementRequest[]>([])
  const [locations, setLocations] = useState<ProcurementLocation[]>([])
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [form, setForm] = useState(initialForm)
  const number = useMemo(() => new Intl.NumberFormat(locale), [locale])
  const money = (value: number | null) => value === null ? "-" : new Intl.NumberFormat(locale, { style: "currency", currency: "CLP", maximumFractionDigits: 0 }).format(value)
  const date = (value: string | null) => value ? new Intl.DateTimeFormat(locale, { timeZone: "America/Santiago" }).format(new Date(`${value}T12:00:00`)) : "-"
  const href = (path: string) => `/${lang}${path}`

  const loadRequests = useCallback(async () => {
    setLoading(true); setError(null)
    const supabase = createBrowserClient()
    const [requestsResult, locationsResult] = await Promise.all([
      supabase.from("procurement_requests").select("id, request_number, title, category, quantity, unit, estimated_budget_clp, priority, status, required_date, commune, created_at").order("created_at", { ascending: false }),
      supabase.rpc("get_procurement_location_directory"),
    ])
    if (requestsResult.error) { console.error("procurement requests load failed", requestsResult.error); setError(copy.genericError); setRequests([]) } else setRequests((requestsResult.data ?? []) as ProcurementRequest[])
    if (locationsResult.error) { console.error("procurement location directory load failed", locationsResult.error); setError((current) => current ?? copy.genericError); setLocations([]) } else setLocations((locationsResult.data ?? []) as ProcurementLocation[])
    setLoading(false)
  }, [copy.genericError])

  useEffect(() => { void loadRequests() }, [loadRequests])

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault(); setSubmitting(true); setError(null)
    if (!form.location_id) { setError(copy.missingLocation); setSubmitting(false); return }
    const supabase = createBrowserClient()
    const { data: authData } = await supabase.auth.getUser()
    if (!authData.user) { setError(copy.expiredSession); setSubmitting(false); return }
    const estimatedBudget = form.estimated_budget_clp ? Number.parseFloat(form.estimated_budget_clp) : null
    const { error: insertError } = await supabase.from("procurement_requests").insert({ title: form.title.trim(), description: form.description.trim() || null, business_justification: form.business_justification.trim(), category: form.category, quantity: Number.parseFloat(form.quantity), unit: form.unit.trim() || "unidad", estimated_budget_clp: estimatedBudget, priority: form.priority, status: form.status, required_date: form.required_date || null, region: form.region, commune: form.commune, location_id: form.location_id, delivery_location: form.delivery_location.trim() || null, requested_by: authData.user.id })
    if (insertError) { console.error("procurement request insert failed", insertError); setError(copy.genericError); setSubmitting(false); return }
    setForm(initialForm); setDialogOpen(false); setSubmitting(false); await loadRequests()
  }

  const totals = { all: requests.length, submitted: requests.filter((request) => request.status === "submitted").length, review: requests.filter((request) => request.status === "under_review").length, approved: requests.filter((request) => request.status === "approved").length }
  const statusLabel = (value: ProcurementRequest["status"]) => STATUS[lang][value]
  const priorityLabel = (value: ProcurementRequest["priority"]) => PRIORITY[lang][value]

  return <AppLayout>
    <PageHeader title={copy.title} description={copy.description} actions={<div className="flex gap-2"><Button variant="outline" asChild><Link href={href("/procurement")}><ArrowLeft className="mr-2 h-4 w-4" />{copy.currentOrders}</Link></Button><Button onClick={() => setDialogOpen(true)} disabled={locations.length === 0}><Plus className="mr-2 h-4 w-4" />{copy.newRequest}</Button></div>} />
    <div className="space-y-6 p-4 md:p-6 lg:p-8">
      {error && <Card className="border-red-500/40"><CardContent className="pt-6 text-sm text-red-500">{error}</CardContent></Card>}
      <div className="grid gap-4 md:grid-cols-4">{[[copy.total, totals.all], [copy.submitted, totals.submitted], [copy.underReview, totals.review], [copy.approved, totals.approved]].map(([label, value]) => <Card key={String(label)}><CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground">{label}</CardTitle></CardHeader><CardContent className="text-3xl font-bold">{number.format(Number(value))}</CardContent></Card>)}</div>
      <Card><CardHeader><div className="flex items-center gap-2"><ClipboardList className="h-5 w-5" /><CardTitle>{copy.internalRequirements}</CardTitle></div><CardDescription>{copy.internalDetail}</CardDescription></CardHeader><CardContent><div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>{copy.number}</TableHead><TableHead>{copy.request}</TableHead><TableHead>{copy.category}</TableHead><TableHead>{copy.quantity}</TableHead><TableHead>{copy.budget}</TableHead><TableHead>{copy.commune}</TableHead><TableHead>{copy.requiredDate}</TableHead><TableHead>{copy.priority}</TableHead><TableHead>{copy.state}</TableHead></TableRow></TableHeader><TableBody>
        {loading ? <TableRow><TableCell colSpan={9} className="py-8 text-center text-muted-foreground">{copy.loading}</TableCell></TableRow> : requests.length === 0 ? <TableRow><TableCell colSpan={9} className="py-8 text-center text-muted-foreground">{copy.empty}</TableCell></TableRow> : requests.map((request) => <TableRow key={request.id} className="group"><TableCell className="font-mono text-xs"><Link href={`/procurement/requests/${request.id}`} className="hover:text-primary hover:underline">{request.request_number ?? copy.pending}</Link></TableCell><TableCell className="font-medium"><Link href={`/procurement/requests/${request.id}`} className="group-hover:text-primary hover:underline">{request.title}</Link></TableCell><TableCell>{request.category}</TableCell><TableCell>{number.format(request.quantity)} {request.unit}</TableCell><TableCell>{money(request.estimated_budget_clp)}</TableCell><TableCell>{request.commune}</TableCell><TableCell>{date(request.required_date)}</TableCell><TableCell><Badge variant="outline">{priorityLabel(request.priority)}</Badge></TableCell><TableCell><Badge variant="outline" className={statusClass(request.status)}>{statusLabel(request.status)}</Badge></TableCell></TableRow>)}
      </TableBody></Table></div></CardContent></Card>
    </div>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{copy.newRequestTitle}</DialogTitle></DialogHeader><form onSubmit={handleSubmit} className="space-y-4">
      <div><label className="text-sm font-medium">{copy.fieldTitle}</label><Input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder={copy.titlePlaceholder} className="mt-1" /></div>
      <div><label className="text-sm font-medium">{copy.fieldDescription}</label><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="mt-1 min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder={copy.descriptionPlaceholder} /></div>
      <div><label className="text-sm font-medium">{copy.justification}</label><textarea required value={form.business_justification} onChange={(event) => setForm({ ...form, business_justification: event.target.value })} className="mt-1 min-h-20 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder={copy.justificationPlaceholder} /></div>
      <div className="grid gap-4 md:grid-cols-2"><div><label className="text-sm font-medium">{copy.category}</label><Select value={form.category} onValueChange={(value) => setForm({ ...form, category: value })}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(CATEGORY).map(([value, key]) => <SelectItem key={value} value={value}>{copy[key]}</SelectItem>)}</SelectContent></Select></div><div><label className="text-sm font-medium">{copy.priority}</label><Select value={form.priority} onValueChange={(value) => setForm({ ...form, priority: value })}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent>{(["low", "normal", "high", "critical"] as const).map((value) => <SelectItem key={value} value={value}>{copy[value]}</SelectItem>)}</SelectContent></Select></div></div>
      <div className="grid gap-4 md:grid-cols-3"><div><label className="text-sm font-medium">{copy.quantity}</label><Input required min="0.01" step="0.01" type="number" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} className="mt-1" /></div><div><label className="text-sm font-medium">{copy.unit}</label><Input required value={form.unit} onChange={(event) => setForm({ ...form, unit: event.target.value })} className="mt-1" /></div><div><label className="text-sm font-medium">{copy.budgetClp}</label><Input min="0" step="1" type="number" value={form.estimated_budget_clp} onChange={(event) => setForm({ ...form, estimated_budget_clp: event.target.value })} className="mt-1" /></div></div>
      <div className="grid gap-4 md:grid-cols-2"><div><label className="text-sm font-medium">{copy.location}</label><Select required value={form.location_id} onValueChange={(value) => setForm({ ...form, location_id: value })}><SelectTrigger className="mt-1"><SelectValue placeholder={copy.locationPlaceholder} /></SelectTrigger><SelectContent>{locations.map((location) => <SelectItem key={location.id} value={location.id}>{location.name}</SelectItem>)}</SelectContent></Select></div><div><label className="text-sm font-medium">{copy.requiredDate}</label><Input type="date" value={form.required_date} onChange={(event) => setForm({ ...form, required_date: event.target.value })} className="mt-1" /></div></div>
      <div className="grid gap-4 md:grid-cols-2"><div><label className="text-sm font-medium">{copy.commune}</label><Input required value={form.commune} onChange={(event) => setForm({ ...form, commune: event.target.value })} className="mt-1" /></div><div><label className="text-sm font-medium">{copy.deliveryDetail}</label><Input value={form.delivery_location} onChange={(event) => setForm({ ...form, delivery_location: event.target.value })} placeholder={copy.deliveryPlaceholder} className="mt-1" /></div></div>
      <p className="text-xs text-muted-foreground">{copy.scopeHint}</p>
      <div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={() => setDialogOpen(false)}>{copy.cancel}</Button><Button type="submit" disabled={submitting || !form.location_id}>{submitting ? copy.saving : copy.register}</Button></div>
    </form></DialogContent></Dialog>
  </AppLayout>
}
