"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { AlertCircle, ClipboardList, Filter, Plus, RefreshCw, Wrench } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { MaintenanceWeekView } from "@/components/maintenance-week-view"
import { MaintenanceQuickAddDrawer } from "@/components/maintenance-quick-add-drawer"
import { createClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type MaintenanceTask = { id:string; title:string; description?:string|null; status?:string|null; estado_extendido?:string|null; prioridad?:string|null; priority?:string|null; next_run?:string|null; last_completed?:string|null; assigned_to?:string|null; bloqueado?:boolean|null; assets?:{name?:string|null}|null; employees?:{name?:string|null}|null }
const LOCALES={en:"en-US",es:"es-CL",de:"de-DE"} as const
const COPY={
 en:{title:"Maintenance · Fundo Corcovado",description:"Planning and tracking preventive and corrective work on operational assets and infrastructure in Valdivia.",register:"Register work",context:"Operational context",contextDetail:"This section manages maintenance work. User-reported issues are handled separately and can become tasks when technical execution is required.",loadError:"Maintenance data could not be loaded.",retry:"Retry",registered:"Work registered",completedWeek:"Completed this week",pending:"Pending",overdue:"Overdue",blocked:"Blocked",filters:"Operational filters",state:"Status",allStates:"All statuses",priority:"Priority",allPriorities:"All priorities",unassigned:"Only work without assignee",issues:"View open issues",tasks:"View general tasks",loading:"Loading maintenance work…",empty:"No work matches the selected filters.",emptyHint:"Register work or review open issues.",draft:"Draft",scheduled:"Scheduled",assigned:"Assigned",in_progress:"In progress",completed:"Completed",low:"Low",medium:"Medium",high:"High",critical:"Critical"},
 es:{title:"Mantenimiento · Fundo Corcovado",description:"Planificación y seguimiento de trabajos preventivos y correctivos sobre activos e infraestructura de la operación en Valdivia.",register:"Registrar trabajo",context:"Contexto operativo",contextDetail:"Esta sección administra trabajos de mantenimiento. Las incidencias reportadas por usuarios se gestionan por separado y pueden transformarse en tareas cuando requieren ejecución técnica.",loadError:"No fue posible cargar mantenimiento.",retry:"Reintentar",registered:"Trabajos registrados",completedWeek:"Completados esta semana",pending:"Pendientes",overdue:"Vencidos",blocked:"Bloqueados",filters:"Filtros operativos",state:"Estado",allStates:"Todos los estados",priority:"Prioridad",allPriorities:"Todas las prioridades",unassigned:"Solo trabajos sin responsable",issues:"Ver incidencias abiertas",tasks:"Ver tareas generales",loading:"Cargando trabajos de mantenimiento…",empty:"No hay trabajos para los filtros seleccionados.",emptyHint:"Registra un trabajo o revisa las incidencias abiertas.",draft:"Borrador",scheduled:"Programada",assigned:"Asignada",in_progress:"En ejecución",completed:"Completada",low:"Baja",medium:"Media",high:"Alta",critical:"Crítica"},
 de:{title:"Instandhaltung · Fundo Corcovado",description:"Planung und Nachverfolgung präventiver und korrektiver Arbeiten an Anlagen und Infrastruktur in Valdivia.",register:"Arbeit erfassen",context:"Operativer Kontext",contextDetail:"Dieser Bereich verwaltet Instandhaltungsarbeiten. Von Nutzern gemeldete Vorfälle werden separat behandelt und können bei technischem Ausführungsbedarf zu Aufgaben werden.",loadError:"Instandhaltungsdaten konnten nicht geladen werden.",retry:"Erneut versuchen",registered:"Erfasste Arbeiten",completedWeek:"Diese Woche abgeschlossen",pending:"Ausstehend",overdue:"Überfällig",blocked:"Blockiert",filters:"Operative Filter",state:"Status",allStates:"Alle Status",priority:"Priorität",allPriorities:"Alle Prioritäten",unassigned:"Nur Arbeiten ohne Verantwortliche",issues:"Offene Vorfälle anzeigen",tasks:"Allgemeine Aufgaben anzeigen",loading:"Instandhaltungsarbeiten werden geladen…",empty:"Keine Arbeiten entsprechen den gewählten Filtern.",emptyHint:"Erfasse eine Arbeit oder prüfe offene Vorfälle.",draft:"Entwurf",scheduled:"Geplant",assigned:"Zugewiesen",in_progress:"In Bearbeitung",completed:"Abgeschlossen",low:"Niedrig",medium:"Mittel",high:"Hoch",critical:"Kritisch"},
} as const

export default function MaintenancePage(){
 const {language}=useLanguage(); const lang=(language in COPY?language:"en") as keyof typeof COPY; const copy=COPY[lang]; const locale=LOCALES[lang]
 const supabase=useMemo(()=>createClient(),[]); const [tasks,setTasks]=useState<MaintenanceTask[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const [isDrawerOpen,setIsDrawerOpen]=useState(false); const [filters,setFilters]=useState({state:"all",priority:"all",unassigned:false})
 const fetchTasks=useCallback(async()=>{setLoading(true);setError(false);const {data,error:loadError}=await supabase.from("maintenance_tasks").select("*, assets(name), employees(name)").order("next_run",{ascending:true,nullsFirst:false});if(loadError){console.error("maintenance load failed",loadError);setError(true);setTasks([])}else setTasks(((data??[]) as MaintenanceTask[]).map(task=>({...task,priority:task.prioridad??task.priority??"medium"})));setLoading(false)},[supabase])
 useEffect(()=>{void fetchTasks()},[fetchTasks])
 const filteredTasks=useMemo(()=>tasks.filter(task=>{const taskState=task.estado_extendido??task.status??"draft";const taskPriority=task.prioridad??task.priority??"medium";return (filters.state==="all"||taskState===filters.state)&&(filters.priority==="all"||taskPriority===filters.priority)&&(!filters.unassigned||!task.assigned_to)}),[tasks,filters])
 const now=new Date();const weekStart=new Date(now);weekStart.setHours(0,0,0,0);weekStart.setDate(now.getDate()-now.getDay());const weekEnd=new Date(weekStart);weekEnd.setDate(weekStart.getDate()+7)
 const completedThisWeek=tasks.filter(task=>{if(!task.last_completed)return false;const date=new Date(task.last_completed);return date>=weekStart&&date<weekEnd}).length
 const pending=tasks.filter(task=>!["completed","cancelled"].includes(task.estado_extendido??task.status??"")).length; const overdue=tasks.filter(task=>task.next_run&&new Date(task.next_run)<now&&!["completed","cancelled"].includes(task.estado_extendido??task.status??"")).length; const blocked=tasks.filter(task=>task.bloqueado).length
 const states=(["draft","scheduled","assigned","in_progress","completed"] as const)
 return <AppLayout><PageHeader title={copy.title} description={copy.description} actions={<Button onClick={()=>setIsDrawerOpen(true)}><Plus className="mr-2 h-4 w-4"/>{copy.register}</Button>}/><div className="space-y-6 p-4 md:p-6">
  <Card><CardHeader><CardTitle className="text-base">{copy.context}</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-muted-foreground">{copy.contextDetail}</CardContent></Card>
  {error&&<div className="flex items-center justify-between gap-4 rounded-lg border border-destructive/40 bg-destructive/5 p-4 text-sm text-destructive"><span>{copy.loadError}</span><Button variant="outline" size="sm" onClick={()=>void fetchTasks()}><RefreshCw className="mr-2 h-4 w-4"/>{copy.retry}</Button></div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric title={copy.registered} value={tasks.length} locale={locale}/><Metric title={copy.completedWeek} value={completedThisWeek} locale={locale}/><Metric title={copy.pending} value={pending} locale={locale}/><Metric title={copy.overdue} value={overdue} alert={overdue>0} locale={locale}/><Metric title={copy.blocked} value={blocked} alert={blocked>0} locale={locale}/></div>
  <Card><CardHeader className="pb-3"><div className="flex items-center gap-2"><Filter className="h-4 w-4"/><CardTitle className="text-base">{copy.filters}</CardTitle></div></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">{copy.state}<select value={filters.state} onChange={e=>setFilters(current=>({...current,state:e.target.value}))} className="mt-1 w-full rounded-md border bg-background px-3 py-2 text-sm"><option value="all">{copy.allStates}</option>{states.map(value=><option key={value} value={value}>{copy[value]}</option>)}</select></label><label className="text-sm font-medium">{copy.priority}<select value={filters.priority} onChange={e=>setFilters(current=>({...current,priority:e.target.value}))} className="mt-1 w-full rounded-md border bg-background px-3 py-2 text-sm"><option value="all">{copy.allPriorities}</option>{(["low","medium","high","critical"] as const).map(value=><option key={value} value={value}>{copy[value]}</option>)}</select></label><label className="flex items-end gap-2 pb-2 text-sm font-medium"><input type="checkbox" checked={filters.unassigned} onChange={e=>setFilters(current=>({...current,unassigned:e.target.checked}))}/>{copy.unassigned}</label></CardContent></Card>
  <div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href="/issues"><AlertCircle className="mr-2 h-4 w-4"/>{copy.issues}</Link></Button><Button asChild variant="outline"><Link href="/tasks"><ClipboardList className="mr-2 h-4 w-4"/>{copy.tasks}</Link></Button></div>
  {loading?<Card><CardContent className="py-12 text-center text-sm text-muted-foreground">{copy.loading}</CardContent></Card>:filteredTasks.length===0?<Card><CardContent className="py-12 text-center"><Wrench className="mx-auto mb-3 h-6 w-6 text-muted-foreground"/><p className="font-medium">{copy.empty}</p><p className="mt-1 text-sm text-muted-foreground">{copy.emptyHint}</p></CardContent></Card>:<MaintenanceWeekView tasks={filteredTasks as never[]}/>} 
 </div><MaintenanceQuickAddDrawer isOpen={isDrawerOpen} onClose={()=>setIsDrawerOpen(false)} onTaskCreated={fetchTasks}/></AppLayout>
}
function Metric({title,value,alert=false,locale}:{title:string;value:number;alert?:boolean;locale:string}){return <Card className={alert?"border-amber-300":undefined}><CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">{title}</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{new Intl.NumberFormat(locale).format(value)}</div></CardContent></Card>}
