"use client"

import type { FormEvent } from "react"
import { useCallback, useEffect, useMemo, useState } from "react"
import { BarChart3, Plus, RefreshCw, Trash2 } from "lucide-react"
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Definition={id:string;name:string;dataset:string;metric:string;dimension:string;crop_filter:string|null;variety_filter:string|null;unit_filter:string|null;is_shared:boolean}
type Harvest={crop_succession_id:string|null;sales_channel_id:string|null;harvest_date:string;quantity_harvested:number|null;harvest_unit:string|null;total_market_value:number|null;market_value_per_unit:number|null}
type Care={crop_id:string;activity_date:string;activity_type:string;hours_spent:number|null}
type Health={crop_id:string;observation_date:string;severity_level:string|null;affected_percentage:number|null}
type Nursery={crop_succession_id:string;status:string;seeds_sown:number;transplanted_count:number|null;loss_count:number}
type Target={crop_succession_id:string;sales_channel_id:string|null;planned_quantity:number;planned_revenue:number;unit:string}
type Succession={id:string;crop_cycle_id:string}
type Cycle={id:string;crop_name:string;variety:string|null}
type Crop={id:string;crop_name:string;variety:string|null}
type Channel={id:string;name:string}
const config={harvest:{metrics:["quantity","revenue","passes"],dimensions:["crop","month","channel"]},care:{metrics:["hours","events"],dimensions:["crop","month","activity"]},health:{metrics:["events","affected_pct"],dimensions:["crop","month","severity"]},nursery:{metrics:["seeds","transplanted","losses"],dimensions:["crop","status"]},commercial:{metrics:["planned_revenue","planned_quantity"],dimensions:["crop","channel"]}} as const
type Dataset=keyof typeof config

export default function OrchardChartsPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const es=language==="es"
 const [defs,setDefs]=useState<Definition[]>([]);const [harvests,setHarvests]=useState<Harvest[]>([]);const [care,setCare]=useState<Care[]>([]);const [health,setHealth]=useState<Health[]>([]);const [nursery,setNursery]=useState<Nursery[]>([]);const [targets,setTargets]=useState<Target[]>([]);const [successions,setSuccessions]=useState<Succession[]>([]);const [cycles,setCycles]=useState<Cycle[]>([]);const [crops,setCrops]=useState<Crop[]>([]);const [channels,setChannels]=useState<Channel[]>([]);const [error,setError]=useState<string|null>(null);const [saving,setSaving]=useState(false)
 const [form,setForm]=useState({name:"Harvest by crop",dataset:"harvest" as Dataset,metric:"quantity",dimension:"crop",unit_filter:"kg"})
 const load=useCallback(async()=>{const [d,h,c,p,n,t,s,cy,cr,ch]=await Promise.all([supabase.from("orchard_chart_definitions").select("*").order("updated_at",{ascending:false}),supabase.from("orchard_harvest_records").select("crop_succession_id,sales_channel_id,harvest_date,quantity_harvested,harvest_unit,total_market_value,market_value_per_unit"),supabase.from("orchard_care_logs").select("crop_id,activity_date,activity_type,hours_spent"),supabase.from("orchard_pest_logs").select("crop_id,observation_date,severity_level,affected_percentage"),supabase.from("orchard_nursery_batches").select("crop_succession_id,status,seeds_sown,transplanted_count,loss_count"),supabase.from("orchard_revenue_targets").select("crop_succession_id,sales_channel_id,planned_quantity,planned_revenue,unit"),supabase.from("orchard_crop_successions").select("id,crop_cycle_id"),supabase.from("orchard_crop_cycles").select("id,crop_name,variety"),supabase.from("orchard_crops").select("id,crop_name,variety"),supabase.from("orchard_sales_channels").select("id,name")]);const e=d.error??h.error??c.error??p.error??n.error??t.error??s.error??cy.error??cr.error??ch.error;if(e)setError(e.message);else{setDefs((d.data??[]) as Definition[]);setHarvests((h.data??[]) as Harvest[]);setCare((c.data??[]) as Care[]);setHealth((p.data??[]) as Health[]);setNursery((n.data??[]) as Nursery[]);setTargets((t.data??[]) as Target[]);setSuccessions((s.data??[]) as Succession[]);setCycles((cy.data??[]) as Cycle[]);setCrops((cr.data??[]) as Crop[]);setChannels((ch.data??[]) as Channel[])}},[supabase]);useEffect(()=>{void load()},[load])
 const successionById=useMemo(()=>new Map(successions.map(s=>[s.id,s])),[successions]);const cycleById=useMemo(()=>new Map(cycles.map(c=>[c.id,c])),[cycles]);const cropById=useMemo(()=>new Map(crops.map(c=>[c.id,c])),[crops]);const channelById=useMemo(()=>new Map(channels.map(c=>[c.id,c])),[channels]);const cropForSuccession=(id:string|null)=>{if(!id)return "Unlinked";const s=successionById.get(id);const c=s?cycleById.get(s.crop_cycle_id):null;return c?`${c.crop_name}${c.variety?` · ${c.variety}`:""}`:"Unlinked"};const cropForId=(id:string)=>{const c=cropById.get(id);return c?`${c.crop_name}${c.variety?` · ${c.variety}`:""}`:"Unknown"};const month=(d:string)=>d.slice(0,7)
 function rows(def:{dataset:string;metric:string;dimension:string;unit_filter?:string|null}){const m=new Map<string,number>();const add=(key:string,value:number)=>m.set(key,(m.get(key)??0)+value);if(def.dataset==="harvest")harvests.filter(h=>def.metric!=="quantity"||!def.unit_filter||h.harvest_unit===def.unit_filter).forEach(h=>{const key=def.dimension==="crop"?cropForSuccession(h.crop_succession_id):def.dimension==="month"?month(h.harvest_date):channelById.get(h.sales_channel_id??"")?.name??"Unassigned";const value=def.metric==="quantity"?Number(h.quantity_harvested??0):def.metric==="revenue"?Number(h.total_market_value??((h.quantity_harvested??0)*(h.market_value_per_unit??0))):1;add(key,value)});if(def.dataset==="care")care.forEach(r=>{const key=def.dimension==="crop"?cropForId(r.crop_id):def.dimension==="month"?month(r.activity_date):r.activity_type;add(key,def.metric==="hours"?Number(r.hours_spent??0):1)});if(def.dataset==="health")health.forEach(r=>{const key=def.dimension==="crop"?cropForId(r.crop_id):def.dimension==="month"?month(r.observation_date):r.severity_level??"unknown";add(key,def.metric==="affected_pct"?Number(r.affected_percentage??0):1)});if(def.dataset==="nursery")nursery.forEach(r=>{const key=def.dimension==="crop"?cropForSuccession(r.crop_succession_id):r.status;add(key,def.metric==="seeds"?r.seeds_sown:def.metric==="transplanted"?Number(r.transplanted_count??0):r.loss_count)});if(def.dataset==="commercial")targets.filter(t=>!def.unit_filter||t.unit===def.unit_filter).forEach(r=>{const key=def.dimension==="crop"?cropForSuccession(r.crop_succession_id):channelById.get(r.sales_channel_id??"")?.name??"Unassigned";add(key,def.metric==="planned_revenue"?Number(r.planned_revenue):Number(r.planned_quantity))});return [...m.entries()].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value).slice(0,20)}
 async function save(e:FormEvent){e.preventDefault();if(!form.name.trim())return;setSaving(true);setError(null);const r=await supabase.from("orchard_chart_definitions").insert({name:form.name.trim(),dataset:form.dataset,metric:form.metric,dimension:form.dimension,unit_filter:form.unit_filter.trim()||null});if(r.error)setError(r.error.message);else await load();setSaving(false)}
 async function remove(id:string){const r=await supabase.from("orchard_chart_definitions").delete().eq("id",id);if(r.error)setError(r.error.message);else await load()}
 const preview=rows(form)
 return <AppLayout><PageHeader title={es?"Gráficos Personalizados":"Custom Data Charts"} description={es?"Crea vistas guardadas sobre métricas canónicas sin exponer SQL libre ni duplicar datos.":"Build saved views over canonical metrics without arbitrary SQL or duplicated reporting tables."} actions={<Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>{es?"Actualizar":"Refresh"}</Button>}/><OrchardNavigation/><div className="space-y-6 p-3 pb-24 sm:p-8">{error&&<Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5"/>{es?"Constructor":"Chart builder"}</CardTitle><CardDescription>{es?"Dataset, métrica y dimensión están explícitamente permitidos; los filtros de unidad evitan mezclar kg con unidades incompatibles.":"Dataset, metric and dimension are explicitly whitelisted; unit filters prevent incompatible quantities from being mixed."}</CardDescription></CardHeader><CardContent><form onSubmit={save} className="grid gap-3 md:grid-cols-5"><Field label={es?"Nombre":"Name"}><Input value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></Field><Field label="Dataset"><Select value={form.dataset} onValueChange={v=>{const dataset=v as Dataset;setForm(f=>({...f,dataset,metric:config[dataset].metrics[0],dimension:config[dataset].dimensions[0]}))}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.keys(config).map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Field label={es?"Métrica":"Metric"}><Select value={form.metric} onValueChange={v=>setForm(f=>({...f,metric:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{config[form.dataset].metrics.map(v=><SelectItem key={v} value={v}>{v.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select></Field><Field label={es?"Dimensión":"Dimension"}><Select value={form.dimension} onValueChange={v=>setForm(f=>({...f,dimension:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{config[form.dataset].dimensions.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Field label={es?"Unidad (opcional)":"Unit (optional)"}><Input value={form.unit_filter} onChange={e=>setForm(f=>({...f,unit_filter:e.target.value}))}/></Field><Button className="md:col-span-5" disabled={saving}><Plus className="mr-2 h-4 w-4"/>{es?"Guardar gráfico":"Save chart"}</Button></form></CardContent></Card>
 <Card><CardHeader><CardTitle>{es?"Vista previa":"Preview"}</CardTitle></CardHeader><CardContent className="h-[360px]">{preview.length===0?<div className="grid h-full place-items-center text-sm text-muted-foreground">{es?"No hay datos para esta combinación.":"No data for this combination."}</div>:<ResponsiveContainer width="100%" height="100%"><BarChart data={preview} margin={{top:10,right:10,bottom:50,left:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label" angle={-25} textAnchor="end" interval={0} height={80}/><YAxis/><Tooltip/><Bar dataKey="value"/></BarChart></ResponsiveContainer>}</CardContent></Card>
 <div className="grid gap-4 lg:grid-cols-2">{defs.map(d=><Card key={d.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{d.name}</CardTitle><CardDescription>{d.dataset} · {d.metric.replaceAll("_"," ")} / {d.dimension}{d.unit_filter?` · ${d.unit_filter}`:""}</CardDescription></div><Button size="icon" variant="ghost" onClick={()=>void remove(d.id)}><Trash2 className="h-4 w-4"/></Button></div></CardHeader><CardContent className="h-[260px]">{rows(d).length===0?<div className="grid h-full place-items-center text-sm text-muted-foreground">{es?"Sin datos":"No data"}</div>:<ResponsiveContainer width="100%" height="100%"><BarChart data={rows(d)}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label" hide/><YAxis/><Tooltip/><Bar dataKey="value"/></BarChart></ResponsiveContainer>}</CardContent></Card>)}</div>
 </div></AppLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
