import type { Language } from "@/lib/hooks/use-language"

export const addReservationCopy: Record<Language, Record<string, string>> = {
  en: {
    title: "New bed reservation", noPermissionScope: "You do not have permission to create reservations in this scope.", noPermissionDepartment: "You do not have permission to create reservations in this department or location.", invalidDates: "Check-out date must be after check-in date", conflict: "This bed is no longer available for these dates. It may have been booked by someone else. Refresh and choose another bed or date.", createFailed: "Failed to create reservation", errorCreating: "Error creating reservation", capacityWarning: "Warning: you're adding {guests} guests to a room with capacity {capacity}.", capacityNote: "You can proceed, but make sure the guest is aware of the capacity limit.", filterLocation: "Filter by location", allLocations: "All locations", bed: "Bed", selectBed: "Select bed", perNight: "night", existingGuest: "Existing guest (optional)", selectGuest: "Select guest", guestName: "Guest name", email: "Email", phone: "Phone", numberGuests: "Number of guests", capacityHint: "You can add more guests than room capacity if needed.", selectDates: "Select dates", selectBedHint: "Select a bed above to view availability and pick dates.", totalAmount: "Total amount", status: "Status", confirmed: "Confirmed", pending: "Pending", checkedIn: "Checked in", checkedOut: "Checked out", cancelled: "Cancelled", specialRequests: "Special requests", cancel: "Cancel", creating: "Creating...", create: "Create reservation", multiple: "Multiple",
    confirmTitle: "Confirm reservation", location: "Location", checkIn: "Check-in", checkOut: "Check-out", duration: "Duration", night: "night", nights: "nights", review: "Review the details above before confirming this reservation.", confirming: "Confirming...", confirm: "Confirm reservation",
    available: "Available", booked: "Booked", selected: "Selected", bookedBy: "Booked by {guest}", selectionConfirmed: "Selection confirmed", selectCheckOut: "Select check-out", clearSelection: "Clear selection",
    sun: "Sun", mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat",
  },
  es: {
    title: "Nueva reserva de cama", noPermissionScope: "No tienes permiso para crear reservas en este alcance.", noPermissionDepartment: "No tienes permiso para crear reservas en este departamento o ubicación.", invalidDates: "La fecha de check-out debe ser posterior al check-in", conflict: "Esta cama ya no está disponible para esas fechas. Puede haber sido reservada por otra persona. Actualiza y elige otra cama o fecha.", createFailed: "No fue posible crear la reserva", errorCreating: "Error al crear la reserva", capacityWarning: "Advertencia: estás agregando {guests} huéspedes a una habitación con capacidad para {capacity}.", capacityNote: "Puedes continuar, pero asegúrate de que el huésped conozca el límite de capacidad.", filterLocation: "Filtrar por ubicación", allLocations: "Todas las ubicaciones", bed: "Cama", selectBed: "Seleccionar cama", perNight: "noche", existingGuest: "Huésped existente (opcional)", selectGuest: "Seleccionar huésped", guestName: "Nombre del huésped", email: "Correo electrónico", phone: "Teléfono", numberGuests: "Número de huéspedes", capacityHint: "Puedes agregar más huéspedes que la capacidad de la habitación si es necesario.", selectDates: "Seleccionar fechas", selectBedHint: "Selecciona una cama arriba para ver disponibilidad y elegir fechas.", totalAmount: "Monto total", status: "Estado", confirmed: "Confirmada", pending: "Pendiente", checkedIn: "Check-in realizado", checkedOut: "Check-out realizado", cancelled: "Cancelada", specialRequests: "Solicitudes especiales", cancel: "Cancelar", creating: "Creando...", create: "Crear reserva", multiple: "Múltiples",
    confirmTitle: "Confirmar reserva", location: "Ubicación", checkIn: "Check-in", checkOut: "Check-out", duration: "Duración", night: "noche", nights: "noches", review: "Revisa los datos antes de confirmar esta reserva.", confirming: "Confirmando...", confirm: "Confirmar reserva",
    available: "Disponible", booked: "Reservado", selected: "Seleccionado", bookedBy: "Reservado por {guest}", selectionConfirmed: "Selección confirmada", selectCheckOut: "Seleccionar check-out", clearSelection: "Limpiar selección",
    sun: "Dom", mon: "Lun", tue: "Mar", wed: "Mié", thu: "Jue", fri: "Vie", sat: "Sáb",
  },
  de: {
    title: "Neue Bettreservierung", noPermissionScope: "Du hast keine Berechtigung, in diesem Bereich Reservierungen zu erstellen.", noPermissionDepartment: "Du hast keine Berechtigung, in diesem Bereich oder an diesem Standort Reservierungen zu erstellen.", invalidDates: "Das Check-out-Datum muss nach dem Check-in-Datum liegen", conflict: "Dieses Bett ist für diese Daten nicht mehr verfügbar. Es wurde möglicherweise zwischenzeitlich gebucht. Aktualisiere und wähle ein anderes Bett oder Datum.", createFailed: "Reservierung konnte nicht erstellt werden", errorCreating: "Fehler beim Erstellen der Reservierung", capacityWarning: "Hinweis: Du fügst {guests} Gäste zu einem Zimmer mit einer Kapazität von {capacity} hinzu.", capacityNote: "Du kannst fortfahren, stelle aber sicher, dass der Gast die Kapazitätsgrenze kennt.", filterLocation: "Nach Standort filtern", allLocations: "Alle Standorte", bed: "Bett", selectBed: "Bett auswählen", perNight: "Nacht", existingGuest: "Bestehender Gast (optional)", selectGuest: "Gast auswählen", guestName: "Name des Gastes", email: "E-Mail", phone: "Telefon", numberGuests: "Anzahl Gäste", capacityHint: "Bei Bedarf können mehr Gäste als die Zimmerkapazität eingetragen werden.", selectDates: "Daten auswählen", selectBedHint: "Wähle oben ein Bett aus, um Verfügbarkeit und Daten festzulegen.", totalAmount: "Gesamtbetrag", status: "Status", confirmed: "Bestätigt", pending: "Ausstehend", checkedIn: "Eingecheckt", checkedOut: "Ausgecheckt", cancelled: "Storniert", specialRequests: "Sonderwünsche", cancel: "Abbrechen", creating: "Wird erstellt...", create: "Reservierung erstellen", multiple: "Mehrere",
    confirmTitle: "Reservierung bestätigen", location: "Standort", checkIn: "Check-in", checkOut: "Check-out", duration: "Dauer", night: "Nacht", nights: "Nächte", review: "Prüfe die Angaben, bevor du diese Reservierung bestätigst.", confirming: "Wird bestätigt...", confirm: "Reservierung bestätigen",
    available: "Verfügbar", booked: "Belegt", selected: "Ausgewählt", bookedBy: "Belegt durch {guest}", selectionConfirmed: "Auswahl bestätigt", selectCheckOut: "Check-out auswählen", clearSelection: "Auswahl löschen",
    sun: "So", mon: "Mo", tue: "Di", wed: "Mi", thu: "Do", fri: "Fr", sat: "Sa",
  },
}

export function fillReservationCopy(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), template)
}
