import type { Language } from "@/lib/hooks/use-language"

export type BookingOperationsTargetLocale = Exclude<Language, "es">

export const bookingOperationsExact: Record<BookingOperationsTargetLocale, Record<string, string>> = {
  en: {
    "Reservas y operación de hospitalidad": "Reservations and hospitality operations", "Timeline único por propiedad, habitación y cama para reservas, estado operativo, housekeeping, atención al huésped, pagos y bloqueos.": "Unified timeline by property, room and bed for reservations, operational status, housekeeping, guest service, payments and blocks.",
    "Nueva reserva": "New reservation", "Llegadas hoy": "Today's arrivals", "Salidas hoy": "Today's departures", "Ocupadas hoy": "Occupied today", "Habitaciones no listas": "Rooms not ready", "Limpiezas pendientes": "Pending cleanings", "Solicitudes abiertas": "Open requests", "Hoy": "Today", "Todas las propiedades": "All properties", "Buscar propiedad, habitación, cama o estado": "Search property, room, bed or status", "Propiedad / habitación / cama": "Property / room / bed", "Cargando operación…": "Loading operations…", "No hay habitaciones para los filtros seleccionados.": "No rooms match the selected filters.",
    "Lista": "Ready", "Sucia": "Dirty", "En limpieza": "Cleaning", "Pendiente inspección": "Pending inspection", "Inspeccionada": "Inspected", "Ocupada": "Occupied", "Fuera de servicio": "Out of service", "Fuera de inventario": "Out of inventory", "Pendiente": "Pending", "Confirmada": "Confirmed", "Esperando habitación": "Waiting for room", "Lista para check-in": "Ready for check-in", "Alojado": "Checked in", "Salida registrada": "Checked out", "Cancelada": "Cancelled", "Asignada": "Assigned", "En curso": "In progress", "Completada": "Completed", "Resuelta": "Resolved",
    "Limpieza de salida": "Turnover cleaning", "Preparación de habitación": "Room preparation", "Inspección operativa": "Operational inspection", "Limpieza": "Cleaning", "Limpieza profunda": "Deep cleaning", "Preparación previa a llegada": "Pre-arrival preparation", "Inspección previa a llegada": "Pre-arrival inspection", "Limpieza posterior a salida": "Post-checkout cleaning", "Lavandería posterior a salida": "Post-checkout laundry", "Revisión de daños": "Damage review", "Reposición posterior a salida": "Post-checkout restock", "Liberación de habitación": "Room release",
    "Bloqueo": "Block", "Sin tipo": "No type", "Retroceder siete días": "Previous seven days", "Avanzar siete días": "Next seven days", "Filtrar por propiedad": "Filter by property", "Actualizar calendario": "Refresh calendar", "Solicitudes históricas del huésped": "Guest request history", "No hay solicitudes históricas vinculadas.": "No linked historical requests.", "Sin fecha": "No date", "sin estado": "no status", "Incidencias vinculadas": "Linked issues", "No hay incidencias vinculadas a esta reserva.": "No issues are linked to this reservation.", "Incidencia": "Issue", "prioridad no registrada": "priority not recorded",
    "Housekeeping activo": "Active housekeeping", "No hay tareas abiertas asociadas a esta reserva.": "No open tasks are linked to this reservation.", "Vinculada a reserva": "Linked to reservation", "Histórica por habitación": "Room history", "Iniciar": "Start", "Completar": "Complete", "Solicitudes activas de Hospitality": "Active Hospitality requests", "No hay solicitudes abiertas asociadas a esta reserva.": "No open requests are linked to this reservation.", "Tablet de huésped": "Guest tablet", "Registro interno": "Internal record", "Poner en curso": "Start processing",
    "Reserva y estadía": "Reservation and stay", "Confirmar reserva": "Confirm reservation", "Registrar check-in": "Register check-in", "Registrar llegada y enviar a cola": "Register arrival and queue", "Registrar check-out": "Register check-out", "Marcar pago recibido": "Mark payment received", "Marcar pago pendiente": "Mark payment pending", "Crear Housekeeping": "Create housekeeping", "Generar limpieza de salida": "Create turnover cleaning", "Preparar habitación": "Prepare room", "Crear inspección operativa": "Create operational inspection", "Crear Hospitality": "Create Hospitality", "Solicitud del huésped": "Guest request", "Recepción o traslado": "Reception or transfer", "Amenidad o preparación especial": "Amenity or special preparation", "Sin detalle adicional.": "No additional details.",
    "Estado de reserva actualizado": "Reservation status updated", "Check-in registrado": "Check-in registered", "La habitación aún no está lista. La llegada quedó en cola.": "The room is not ready yet. The arrival was queued.", "Estado operativo actualizado": "Operational status updated", "Tarea de housekeeping creada": "Housekeeping task created", "Tarea completada": "Task completed", "Tarea iniciada": "Task started", "Solicitud de hospitalidad creada": "Hospitality request created", "Solicitud completada": "Request completed", "Solicitud en curso": "Request in progress", "Estado de pago actualizado": "Payment status updated", "No fue posible cargar las operaciones de la reserva": "Could not load reservation operations", "No fue posible cargar las operaciones": "Could not load operations",
    "Control operativo": "Operations control", "Operación en tiempo real": "Real-time operations", "Sin ubicación": "No location", "Sin habitación": "No room", "Sin estado": "No status", "Selecciona una reserva en el calendario para dirigir su operación.": "Select a reservation in the calendar to manage its operation.", "Próxima acción": "Next action", "Ver solo esta estadía": "View this stay only", "Ver toda la operación": "View all operations", "Solicitud especial": "Special request", "Abiertas": "Open", "Sin encargado": "Unassigned", "Toda la operación": "All operations", "Acciones de esta estadía": "Actions for this stay", "No hay acciones operacionales abiertas en este contexto.": "There are no open operational actions in this context.", "Seleccionar encargado": "Select assignee", "Encargado asignado": "Assignee assigned", "Asigna un encargado antes de iniciar o completar esta acción.": "Assign someone before starting or completing this action.", "Acción completada": "Action completed", "Acción iniciada": "Action started", "Llegada procesada": "Arrival processed", "Check-out registrado": "Check-out registered",
    "La acción no puede comenzar sin encargado.": "The action cannot start without an assignee.", "Es la siguiente dependencia operacional de la estadía.": "This is the next operational dependency for the stay.", "La habitación aún no está lista para recibir al huésped.": "The room is not ready to receive the guest yet.", "La habitación está lista y la reserva puede ingresar.": "The room is ready and the reservation can check in.", "Atender estadía": "Manage stay", "Hay acciones abiertas vinculadas al huésped.": "There are open actions linked to the guest.", "No existen excepciones operacionales abiertas.": "There are no open operational exceptions.", "Cerrar operación de salida": "Close departure operation", "Verifique limpieza, consumos y documentación final.": "Verify cleaning, charges and final documentation.", "Revisar reserva": "Review reservation", "La reserva requiere validación de su estado actual.": "The reservation requires validation of its current status.",
    "Fri": "Fri", "Sat": "Sat", "Sun": "Sun", "Mon": "Mon", "Tue": "Tue", "Wed": "Wed", "Thu": "Thu",
  },
  de: {
    "Reservas y operación de hospitalidad": "Reservierungen und Hospitality-Betrieb", "Timeline único por propiedad, habitación y cama para reservas, estado operativo, housekeeping, atención al huésped, pagos y bloqueos.": "Einheitliche Zeitleiste nach Unterkunft, Zimmer und Bett für Reservierungen, Betriebsstatus, Housekeeping, Gästeservice, Zahlungen und Sperren.",
    "Nueva reserva": "Neue Reservierung", "Llegadas hoy": "Heutige Anreisen", "Salidas hoy": "Heutige Abreisen", "Ocupadas hoy": "Heute belegt", "Habitaciones no listas": "Zimmer nicht bereit", "Limpiezas pendientes": "Offene Reinigungen", "Solicitudes abiertas": "Offene Anfragen", "Hoy": "Heute", "Todas las propiedades": "Alle Unterkünfte", "Buscar propiedad, habitación, cama o estado": "Unterkunft, Zimmer, Bett oder Status suchen", "Propiedad / habitación / cama": "Unterkunft / Zimmer / Bett", "Cargando operación…": "Betrieb wird geladen…", "No hay habitaciones para los filtros seleccionados.": "Keine Zimmer entsprechen den gewählten Filtern.",
    "Lista": "Bereit", "Sucia": "Schmutzig", "En limpieza": "In Reinigung", "Pendiente inspección": "Prüfung ausstehend", "Inspeccionada": "Geprüft", "Ocupada": "Belegt", "Fuera de servicio": "Außer Betrieb", "Fuera de inventario": "Nicht im Bestand", "Pendiente": "Ausstehend", "Confirmada": "Bestätigt", "Esperando habitación": "Wartet auf Zimmer", "Lista para check-in": "Bereit zum Check-in", "Alojado": "Eingecheckt", "Salida registrada": "Ausgecheckt", "Cancelada": "Storniert", "Asignada": "Zugewiesen", "En curso": "In Bearbeitung", "Completada": "Abgeschlossen", "Resuelta": "Erledigt",
    "Limpieza de salida": "Abreisereinigung", "Preparación de habitación": "Zimmer vorbereiten", "Inspección operativa": "Betriebsprüfung", "Limpieza": "Reinigung", "Limpieza profunda": "Grundreinigung", "Preparación previa a llegada": "Vorbereitung vor Anreise", "Inspección previa a llegada": "Prüfung vor Anreise", "Limpieza posterior a salida": "Reinigung nach Abreise", "Lavandería posterior a salida": "Wäsche nach Abreise", "Revisión de daños": "Schadensprüfung", "Reposición posterior a salida": "Nachbestückung nach Abreise", "Liberación de habitación": "Zimmer freigeben",
    "Bloqueo": "Sperre", "Sin tipo": "Ohne Typ", "Retroceder siete días": "Sieben Tage zurück", "Avanzar siete días": "Sieben Tage vor", "Filtrar por propiedad": "Nach Unterkunft filtern", "Actualizar calendario": "Kalender aktualisieren", "Solicitudes históricas del huésped": "Frühere Gästeanfragen", "No hay solicitudes históricas vinculadas.": "Keine verknüpften früheren Anfragen.", "Sin fecha": "Kein Datum", "sin estado": "ohne Status", "Incidencias vinculadas": "Verknüpfte Vorfälle", "No hay incidencias vinculadas a esta reserva.": "Mit dieser Reservierung sind keine Vorfälle verknüpft.", "Incidencia": "Vorfall", "prioridad no registrada": "Priorität nicht erfasst",
    "Housekeeping activo": "Aktives Housekeeping", "No hay tareas abiertas asociadas a esta reserva.": "Mit dieser Reservierung sind keine offenen Aufgaben verknüpft.", "Vinculada a reserva": "Mit Reservierung verknüpft", "Histórica por habitación": "Zimmerverlauf", "Iniciar": "Starten", "Completar": "Abschließen", "Solicitudes activas de Hospitality": "Aktive Hospitality-Anfragen", "No hay solicitudes abiertas asociadas a esta reserva.": "Mit dieser Reservierung sind keine offenen Anfragen verknüpft.", "Tablet de huésped": "Gäste-Tablet", "Registro interno": "Interner Eintrag", "Poner en curso": "Bearbeitung starten",
    "Reserva y estadía": "Reservierung und Aufenthalt", "Confirmar reserva": "Reservierung bestätigen", "Registrar check-in": "Check-in erfassen", "Registrar llegada y enviar a cola": "Anreise erfassen und einreihen", "Registrar check-out": "Check-out erfassen", "Marcar pago recibido": "Zahlung als erhalten markieren", "Marcar pago pendiente": "Zahlung als ausstehend markieren", "Crear Housekeeping": "Housekeeping erstellen", "Generar limpieza de salida": "Abreisereinigung erstellen", "Preparar habitación": "Zimmer vorbereiten", "Crear inspección operativa": "Betriebsprüfung erstellen", "Crear Hospitality": "Hospitality erstellen", "Solicitud del huésped": "Gästeanfrage", "Recepción o traslado": "Empfang oder Transfer", "Amenidad o preparación especial": "Ausstattung oder Sondervorbereitung", "Sin detalle adicional.": "Keine zusätzlichen Angaben.",
    "Estado de reserva actualizado": "Reservierungsstatus aktualisiert", "Check-in registrado": "Check-in erfasst", "La habitación aún no está lista. La llegada quedó en cola.": "Das Zimmer ist noch nicht bereit. Die Anreise wurde in die Warteschlange gestellt.", "Estado operativo actualizado": "Betriebsstatus aktualisiert", "Tarea de housekeeping creada": "Housekeeping-Aufgabe erstellt", "Tarea completada": "Aufgabe abgeschlossen", "Tarea iniciada": "Aufgabe gestartet", "Solicitud de hospitalidad creada": "Hospitality-Anfrage erstellt", "Solicitud completada": "Anfrage abgeschlossen", "Solicitud en curso": "Anfrage in Bearbeitung", "Estado de pago actualizado": "Zahlungsstatus aktualisiert", "No fue posible cargar las operaciones de la reserva": "Reservierungsvorgänge konnten nicht geladen werden", "No fue posible cargar las operaciones": "Vorgänge konnten nicht geladen werden",
    "Control operativo": "Betriebssteuerung", "Operación en tiempo real": "Betrieb in Echtzeit", "Sin ubicación": "Kein Standort", "Sin habitación": "Kein Zimmer", "Sin estado": "Kein Status", "Selecciona una reserva en el calendario para dirigir su operación.": "Wähle eine Reservierung im Kalender aus, um den Betrieb zu steuern.", "Próxima acción": "Nächste Aktion", "Ver solo esta estadía": "Nur diesen Aufenthalt anzeigen", "Ver toda la operación": "Gesamten Betrieb anzeigen", "Solicitud especial": "Sonderwunsch", "Abiertas": "Offen", "Sin encargado": "Nicht zugewiesen", "Toda la operación": "Gesamter Betrieb", "Acciones de esta estadía": "Aktionen dieses Aufenthalts", "No hay acciones operacionales abiertas en este contexto.": "In diesem Kontext gibt es keine offenen Betriebsaktionen.", "Seleccionar encargado": "Verantwortlichen auswählen", "Encargado asignado": "Verantwortlicher zugewiesen", "Asigna un encargado antes de iniciar o completar esta acción.": "Weise zuerst einen Verantwortlichen zu, bevor die Aktion gestartet oder abgeschlossen wird.", "Acción completada": "Aktion abgeschlossen", "Acción iniciada": "Aktion gestartet", "Llegada procesada": "Anreise verarbeitet", "Check-out registrado": "Check-out erfasst",
    "La acción no puede comenzar sin encargado.": "Die Aktion kann ohne Verantwortlichen nicht beginnen.", "Es la siguiente dependencia operacional de la estadía.": "Dies ist die nächste betriebliche Abhängigkeit des Aufenthalts.", "La habitación aún no está lista para recibir al huésped.": "Das Zimmer ist noch nicht bereit für den Gast.", "La habitación está lista y la reserva puede ingresar.": "Das Zimmer ist bereit und die Reservierung kann einchecken.", "Atender estadía": "Aufenthalt betreuen", "Hay acciones abiertas vinculadas al huésped.": "Es gibt offene Aktionen für diesen Gast.", "No existen excepciones operacionales abiertas.": "Es gibt keine offenen betrieblichen Ausnahmen.", "Cerrar operación de salida": "Abreisebetrieb abschließen", "Verifique limpieza, consumos y documentación final.": "Reinigung, Verbrauch und Abschlussdokumentation prüfen.", "Revisar reserva": "Reservierung prüfen", "La reserva requiere validación de su estado actual.": "Der aktuelle Reservierungsstatus muss geprüft werden.",
    "Fri": "Fr", "Sat": "Sa", "Sun": "So", "Mon": "Mo", "Tue": "Di", "Wed": "Mi", "Thu": "Do",
  },
}

export const bookingOperationsEsDate: Record<string, string> = { Fri: "Vie", Sat: "Sáb", Sun: "Dom", Mon: "Lun", Tue: "Mar", Wed: "Mié", Thu: "Jue" }

export function translateBookingOperationsValue(value: string, locale: Language) {
  if (locale === "es") return bookingOperationsEsDate[value] ?? value
  const exact = bookingOperationsExact[locale][value]
  if (exact) return exact
  if (locale === "de") {
    return value
      .replace(/^(\d+) habitaciones$/, "$1 Zimmer").replace(/^(\d+) habitación$/, "$1 Zimmer")
      .replace(/^(.*) · (\d+) camas$/, "$1 · $2 Betten").replace(/^(.*) · (\d+) cama$/, "$1 · $2 Bett")
      .replace(/^Cama (.+)$/, "Bett $1").replace(/^Bloqueo · /, "Sperre · ").replace(/^Prioridad (.+)$/, "Priorität $1")
      .replace(/^Asignar (.+)$/, "Zuweisen: $1").replace(/^Iniciar (.+)$/, "Starten: $1").replace(/^Asignar encargado a (.+)$/, "Verantwortlichen für $1 zuweisen")
  }
  return value
    .replace(/^(\d+) habitaciones$/, "$1 rooms").replace(/^(\d+) habitación$/, "$1 room")
    .replace(/^(.*) · (\d+) camas$/, "$1 · $2 beds").replace(/^(.*) · (\d+) cama$/, "$1 · $2 bed")
    .replace(/^Cama (.+)$/, "Bed $1").replace(/^Bloqueo · /, "Block · ").replace(/^Prioridad (.+)$/, "Priority $1")
    .replace(/^Asignar (.+)$/, "Assign $1").replace(/^Iniciar (.+)$/, "Start $1").replace(/^Asignar encargado a (.+)$/, "Assign person to $1")
}
