import type { Language } from "@/lib/hooks/use-language"

export const bookingsCalendarPageCopy: Record<Language, Record<string, string>> = {
  en: {
    eyebrow: "Hospitality · Fundo Corcovado",
    title: "Reservations and availability",
    subtitle: "Operational calendar connected to the availability engine. Drag a reservation to another bed to reassign it. Use Ctrl+click or the selection box to select multiple reservations.",
    manageBlocks: "Manage blocks",
    today: "Today",
    newReservation: "New reservation",
    allStatuses: "All statuses", pending: "Pending", confirmed: "Confirmed", checkedIn: "Checked in", completed: "Completed", days: "days", selected: "selected", all: "All", extend: "Extend", reduce: "Reduce", cancel: "Cancel", delete: "Delete", clear: "Clear", conflicts: "conflicts detected", operationComplete: "Operation completed", undoWindow: "to undo", undo: "Undo", blockTitle: "Room block", reason: "Reason", from: "From", to: "To", notes: "Notes", month:"Month", print:"Print calendar", roomsBeds:"Rooms & beds", search:"Search", refresh:"Refresh", tasksAlerts:"Tasks & alerts", profile:"Profile", searchPlaceholder:"Search guest or room", property:"Property", allProperties:"All properties", shiftDay:"day", confirmAction:"Confirm", checkInAction:"Check-in", networkModifyError:"Network error while modifying reservations", networkDeleteError:"Network error while deleting reservations", networkUndoError:"Network error while undoing", deleteFailed:"Could not delete reservations", undoFailed:"Could not undo operation", modified:"reservations modified", deleted:"reservations deleted", restored:"reservations restored", statusUpdateFailed:"Could not update status", statusNetworkError:"Network error while updating status", moved:"reservations moved", moveFailed:"Could not move reservations", moveNetworkError:"Network error while moving reservations", conflictsDetected:"Conflicts detected", resizeBlockConflict:"New dates conflict with a room block", resizeReservationConflict:"New dates conflict with another reservation", resizeChanged:"Availability changed before the new dates could be confirmed", resizeRejected:"Date change was rejected and the reservation was restored", reservationUpdated:"Reservation updated", maintenance:"Maintenance", ownerUse:"Owner use", outOfService:"Out of service", blocked:"Blocked",
  },
  es: {
    eyebrow: "Hospitalidad · Fundo Corcovado",
    title: "Reservas y disponibilidad",
    subtitle: "Calendario operativo conectado al motor de disponibilidad. Arrastra una reserva hacia otra cama para reasignarla. Usa Ctrl+clic o la casilla de selección para seleccionar varias reservas.",
    manageBlocks: "Gestionar bloqueos",
    today: "Hoy",
    newReservation: "Nueva reserva",
    allStatuses: "Todos los estados", pending: "Pendiente", confirmed: "Confirmada", checkedIn: "Hospedado", completed: "Finalizada", days: "días", selected: "seleccionadas", all: "Todas", extend: "Extender", reduce: "Reducir", cancel: "Cancelar", delete: "Eliminar", clear: "Limpiar", conflicts: "conflictos detectados", operationComplete: "Operación completada", undoWindow: "para deshacer", undo: "Deshacer", blockTitle: "Bloqueo de habitación", reason: "Motivo", from: "Desde", to: "Hasta", notes: "Notas", month:"Mes", print:"Imprimir calendario", roomsBeds:"Habitaciones y camas", search:"Buscar", refresh:"Actualizar", tasksAlerts:"Tareas y alertas", profile:"Perfil", searchPlaceholder:"Buscar huésped o habitación", property:"Propiedad", allProperties:"Todas las propiedades", shiftDay:"día", confirmAction:"Confirmar", checkInAction:"Check-in", networkModifyError:"Error de red al modificar reservas", networkDeleteError:"Error de red al eliminar reservas", networkUndoError:"Error de red al deshacer", deleteFailed:"No fue posible eliminar las reservas", undoFailed:"No fue posible deshacer la operación", modified:"reservas modificadas", deleted:"reservas eliminadas", restored:"reservas restauradas", statusUpdateFailed:"No fue posible actualizar el estado", statusNetworkError:"Error de red al actualizar estado", moved:"reservas movidas", moveFailed:"No fue posible mover las reservas", moveNetworkError:"Error de red al mover reservas", conflictsDetected:"Conflictos detectados", resizeBlockConflict:"Las nuevas fechas chocan con un bloqueo", resizeReservationConflict:"Las nuevas fechas chocan con otra reserva", resizeChanged:"La disponibilidad cambió antes de confirmar las fechas", resizeRejected:"El cambio de fechas fue rechazado y se restauró la reserva", reservationUpdated:"Reserva actualizada", maintenance:"Mantenimiento", ownerUse:"Uso propietario", outOfService:"Fuera de servicio", blocked:"Bloqueada",
  },
  de: {
    eyebrow: "Gastbetrieb · Fundo Corcovado",
    title: "Reservierungen und Verfügbarkeit",
    subtitle: "Betriebskalender mit direkter Anbindung an die Verfügbarkeitssteuerung. Ziehe eine Reservierung auf ein anderes Bett, um sie neu zuzuweisen. Mit Strg+Klick oder dem Auswahlfeld kannst du mehrere Reservierungen auswählen.",
    manageBlocks: "Sperren verwalten",
    today: "Heute",
    newReservation: "Neue Reservierung",
    allStatuses: "Alle Status", pending: "Ausstehend", confirmed: "Bestätigt", checkedIn: "Eingecheckt", completed: "Abgeschlossen", days: "Tage", selected: "ausgewählt", all: "Alle", extend: "Verlängern", reduce: "Verkürzen", cancel: "Stornieren", delete: "Löschen", clear: "Leeren", conflicts: "Konflikte erkannt", operationComplete: "Vorgang abgeschlossen", undoWindow: "zum Rückgängigmachen", undo: "Rückgängig", blockTitle: "Zimmersperre", reason: "Grund", from: "Von", to: "Bis", notes: "Notizen", month:"Monat", print:"Kalender drucken", roomsBeds:"Zimmer & Betten", search:"Suchen", refresh:"Aktualisieren", tasksAlerts:"Aufgaben & Hinweise", profile:"Profil", searchPlaceholder:"Gast oder Zimmer suchen", property:"Unterkunft", allProperties:"Alle Unterkünfte", shiftDay:"Tag", confirmAction:"Bestätigen", checkInAction:"Check-in", networkModifyError:"Netzwerkfehler beim Ändern der Reservierungen", networkDeleteError:"Netzwerkfehler beim Löschen der Reservierungen", networkUndoError:"Netzwerkfehler beim Rückgängigmachen", deleteFailed:"Reservierungen konnten nicht gelöscht werden", undoFailed:"Vorgang konnte nicht rückgängig gemacht werden", modified:"Reservierungen geändert", deleted:"Reservierungen gelöscht", restored:"Reservierungen wiederhergestellt", statusUpdateFailed:"Status konnte nicht aktualisiert werden", statusNetworkError:"Netzwerkfehler beim Aktualisieren des Status", moved:"Reservierungen verschoben", moveFailed:"Reservierungen konnten nicht verschoben werden", moveNetworkError:"Netzwerkfehler beim Verschieben der Reservierungen", conflictsDetected:"Konflikte erkannt", resizeBlockConflict:"Neue Daten kollidieren mit einer Zimmersperre", resizeReservationConflict:"Neue Daten kollidieren mit einer anderen Reservierung", resizeChanged:"Die Verfügbarkeit hat sich vor der Bestätigung geändert", resizeRejected:"Die Datumsänderung wurde abgelehnt und die Reservierung wiederhergestellt", reservationUpdated:"Reservierung aktualisiert", maintenance:"Wartung", ownerUse:"Eigentümernutzung", outOfService:"Außer Betrieb", blocked:"Gesperrt",
  },
}
