import type { Language } from "@/lib/hooks/use-language"

export const documentsCopy: Record<Language, Record<string, string>> = {
  en: {
    validating: "Validating document access...", restricted: "Restricted access", restrictedDesc: "The document repository is available only to Administration and users with approval permissions.", controlled: "Controlled access", title: "Document repository", subtitle: "Preventive documentation for Blackswan Facility Core, Mutual de Seguridad, internal control and Fundo Corcovado operations.", openTechnical: "Open technical repository", controlTitle: "Document control", controlDesc: "Signed binaries and personal evidence must not be published on GitHub. This view is a controlled index; master versions must be stored in a private repository with traceability and authenticated download.", baseVersion: "Base version 2026-08-07 · Controlled draft", owner: "Owner: Administration", pendingReview: "Review pending", administration: "Repository administration", administrationDesc: "The technical index, change history and publication procedures live on GitHub. Signed documents and operational evidence must remain outside the public repository.", viewMutual: "View Mutual index", viewGitHub: "View project on GitHub",
  },
  es: {
    validating: "Validando acceso documental…", restricted: "Acceso restringido", restrictedDesc: "El repositorio documental está disponible únicamente para Administración y usuarios con rol de aprobación.", controlled: "Acceso controlado", title: "Repositorio documental", subtitle: "Documentación preventiva de Blackswan Facility Core para Mutual de Seguridad, control interno y operación del Fundo Corcovado.", openTechnical: "Abrir repositorio técnico", controlTitle: "Control documental", controlDesc: "Los archivos binarios firmados y las evidencias personales no deben publicarse en GitHub. Esta vista funciona como índice controlado; las versiones maestras deben almacenarse en un repositorio privado con trazabilidad y descarga autenticada.", baseVersion: "Versión base 2026-08-07 · Borrador controlado", owner: "Propietario: Administración", pendingReview: "Revisión pendiente", administration: "Administración del repositorio", administrationDesc: "El índice técnico, historial de cambios y procedimientos de publicación viven en GitHub. Los documentos firmados y la evidencia operacional deben permanecer fuera del repositorio público.", viewMutual: "Ver índice Mutual", viewGitHub: "Ver proyecto en GitHub",
  },
  de: {
    validating: "Dokumentzugriff wird geprüft...", restricted: "Eingeschränkter Zugriff", restrictedDesc: "Das Dokumentenarchiv steht nur der Administration und Benutzern mit Freigaberechten zur Verfügung.", controlled: "Kontrollierter Zugriff", title: "Dokumentenarchiv", subtitle: "Präventionsdokumentation für Blackswan Facility Core, Mutual de Seguridad, interne Kontrolle und den Betrieb von Fundo Corcovado.", openTechnical: "Technisches Repository öffnen", controlTitle: "Dokumentenkontrolle", controlDesc: "Signierte Binärdateien und personenbezogene Nachweise dürfen nicht auf GitHub veröffentlicht werden. Diese Ansicht dient als kontrollierter Index; Masterversionen müssen in einem privaten Repository mit Nachverfolgbarkeit und authentifiziertem Download gespeichert werden.", baseVersion: "Basisversion 2026-08-07 · Kontrollierter Entwurf", owner: "Verantwortlich: Administration", pendingReview: "Prüfung ausstehend", administration: "Repository-Verwaltung", administrationDesc: "Technischer Index, Änderungsverlauf und Veröffentlichungsverfahren liegen auf GitHub. Signierte Dokumente und operative Nachweise müssen außerhalb des öffentlichen Repositorys bleiben.", viewMutual: "Mutual-Index anzeigen", viewGitHub: "Projekt auf GitHub anzeigen",
  },
}

export const documentTitles: Record<Language, string[]> = {
  en: ["Mutual presentation folder", "Occupational Health and Safety Policy", "Appointment record for the OHS lead", "Emergency and response plan", "Preventive SOP manual", "Draft Internal Hygiene and Safety Regulations", "OHS forms and records", "Mutual visit checklist", "IPER matrix and preventive program", "Master checklist of pending data", "Consolidated document package"],
  es: ["Carpeta de presentación Mutual", "Política de Seguridad y Salud en el Trabajo", "Acta de designación del Encargado SST", "Plan de emergencia y respuesta", "Manual agrupado de SOP preventivos", "Borrador de Reglamento Interno de Higiene y Seguridad", "Formularios y registros SST", "Checklist de visita Mutual", "Matriz IPER y programa preventivo", "Checklist maestro de datos pendientes", "Paquete documental consolidado"],
  de: ["Mutual-Präsentationsmappe", "Richtlinie für Sicherheit und Gesundheitsschutz am Arbeitsplatz", "Bestellungsprotokoll der Arbeitsschutzverantwortung", "Notfall- und Reaktionsplan", "Präventions-SOP-Handbuch", "Entwurf der internen Hygiene- und Sicherheitsordnung", "Arbeitsschutzformulare und -nachweise", "Checkliste für Mutual-Besuch", "IPER-Matrix und Präventionsprogramm", "Master-Checkliste offener Daten", "Konsolidiertes Dokumentenpaket"],
}
