import type { Language } from "@/lib/hooks/use-language"

export const invoiceEditorCopy: Record<Language, Record<string, string>> = {
  en: {
    loadFailed: "Could not load the invoice", newFromReservation: "New invoices must be opened from a reservation", validateFailed: "Could not validate the invoice", customerRequired: "Customer name or legal name is required", itemRequired: "Add at least one valid line item", notReady: "The reservation is not ready for invoicing", traceability: "New invoices must be generated from a reservation to preserve traceability", generateFailed: "Could not generate the invoice", saveFailed: "Could not save the invoice", saved: "Invoice saved", generated: "Invoice generated from reservation", internalInvoice: "Internal invoice · Valdivia, Chile", print: "Print", close: "Close", invoice: "Invoice", pendingGeneration: "pending generation", internalDocument: "Internal management document. Tax validity depends on issuance through the corresponding authorized system.", issued: "Issued", due: "Due", prevalidation: "Reservation pre-validation", eligible: "Reservation ready for invoicing: {nights} night(s), {room}, expected total {total}.", noRoom: "no room assigned", customer: "Customer", customerName: "Name or legal name *", customerPlaceholder: "Customer name", email: "Email", phone: "Phone", address: "Address", addressPlaceholder: "Address, municipality and region", issueAndStatus: "Issue and status", issueDate: "Issue date", dueDate: "Due date", documentStatus: "Document status", paymentStatus: "Payment status", draft: "Draft", sent: "Issued", paid: "Paid", cancelled: "Cancelled", pending: "Pending", partial: "Partially paid", overdue: "Overdue", detail: "Details", calculated: "Calculated from lodging and extras registered on the reservation.", addItem: "Add item", description: "Description", quantity: "Quantity", unitValue: "Unit price", total: "Total", itemPlaceholder: "Lodging, service or extra", deleteItem: "Delete item", observationsConditions: "Notes and conditions", observations: "Notes", observationsPlaceholder: "Additional information for the customer", terms: "Terms and conditions", termsPlaceholder: "Payment term, accepted methods or other conditions", totalsClp: "Totals in CLP", discountPercent: "Discount (%)", discountAmount: "Discount ($)", taxPercent: "VAT / tax (%)", additionalFeesAmount: "Additional fees ($)", subtotal: "Subtotal", discount: "Discount", tax: "VAT / tax", additionalFees: "Additional fees", cancel: "Cancel", saveChanges: "Save changes", generateFromReservation: "Generate invoice from reservation",
  },
  es: {
    loadFailed: "No se pudo cargar la factura", newFromReservation: "Las facturas nuevas deben abrirse desde una reserva", validateFailed: "No se pudo validar la factura", customerRequired: "El nombre o razón social del cliente es obligatorio", itemRequired: "Agrega al menos un ítem válido", notReady: "La reserva no está lista para facturación", traceability: "Las facturas nuevas deben generarse desde una reserva para mantener trazabilidad", generateFailed: "No se pudo generar la factura", saveFailed: "No se pudo guardar la factura", saved: "Factura guardada", generated: "Factura generada desde la reserva", internalInvoice: "Factura interna · Valdivia, Chile", print: "Imprimir", close: "Cerrar", invoice: "Factura", pendingGeneration: "por generar", internalDocument: "Documento de gestión interna. La validez tributaria depende de la emisión en el sistema autorizado correspondiente.", issued: "Emisión", due: "Vencimiento", prevalidation: "Prevalidación de reserva", eligible: "Reserva apta para facturar: {nights} noche(s), {room}, total previsto {total}.", noRoom: "sin habitación asignada", customer: "Cliente", customerName: "Nombre o razón social *", customerPlaceholder: "Nombre del cliente", email: "Correo", phone: "Teléfono", address: "Dirección", addressPlaceholder: "Dirección, comuna y región", issueAndStatus: "Emisión y estado", issueDate: "Fecha de emisión", dueDate: "Fecha de vencimiento", documentStatus: "Estado del documento", paymentStatus: "Estado de pago", draft: "Borrador", sent: "Emitida", paid: "Pagada", cancelled: "Anulada", pending: "Pendiente", partial: "Pago parcial", overdue: "Vencida", detail: "Detalle", calculated: "Calculado desde alojamiento y extras registrados en la reserva.", addItem: "Agregar ítem", description: "Descripción", quantity: "Cantidad", unitValue: "Valor unitario", total: "Total", itemPlaceholder: "Alojamiento, servicio o extra", deleteItem: "Eliminar ítem", observationsConditions: "Observaciones y condiciones", observations: "Observaciones", observationsPlaceholder: "Información adicional para el cliente", terms: "Términos y condiciones", termsPlaceholder: "Plazo de pago, medios aceptados u otras condiciones", totalsClp: "Totales en CLP", discountPercent: "Descuento (%)", discountAmount: "Descuento ($)", taxPercent: "IVA / impuesto (%)", additionalFeesAmount: "Cargos adicionales ($)", subtotal: "Subtotal", discount: "Descuento", tax: "IVA / impuesto", additionalFees: "Cargos adicionales", cancel: "Cancelar", saveChanges: "Guardar cambios", generateFromReservation: "Generar factura desde reserva",
  },
  de: {
    loadFailed: "Rechnung konnte nicht geladen werden", newFromReservation: "Neue Rechnungen müssen aus einer Reservierung heraus geöffnet werden", validateFailed: "Rechnung konnte nicht validiert werden", customerRequired: "Name oder Firmenname des Kunden ist erforderlich", itemRequired: "Füge mindestens eine gültige Position hinzu", notReady: "Die Reservierung ist noch nicht abrechnungsbereit", traceability: "Neue Rechnungen müssen aus einer Reservierung erstellt werden, damit die Nachverfolgbarkeit erhalten bleibt", generateFailed: "Rechnung konnte nicht erstellt werden", saveFailed: "Rechnung konnte nicht gespeichert werden", saved: "Rechnung gespeichert", generated: "Rechnung aus Reservierung erstellt", internalInvoice: "Interne Rechnung · Valdivia, Chile", print: "Drucken", close: "Schließen", invoice: "Rechnung", pendingGeneration: "noch zu erstellen", internalDocument: "Internes Verwaltungsdokument. Die steuerliche Gültigkeit hängt von der Ausstellung im entsprechend autorisierten System ab.", issued: "Ausstellung", due: "Fälligkeit", prevalidation: "Reservierungsprüfung", eligible: "Reservierung ist abrechnungsbereit: {nights} Nacht/Nächte, {room}, erwarteter Gesamtbetrag {total}.", noRoom: "kein Zimmer zugewiesen", customer: "Kunde", customerName: "Name oder Firmenname *", customerPlaceholder: "Kundenname", email: "E-Mail", phone: "Telefon", address: "Adresse", addressPlaceholder: "Adresse, Gemeinde und Region", issueAndStatus: "Ausstellung und Status", issueDate: "Ausstellungsdatum", dueDate: "Fälligkeitsdatum", documentStatus: "Dokumentstatus", paymentStatus: "Zahlungsstatus", draft: "Entwurf", sent: "Ausgestellt", paid: "Bezahlt", cancelled: "Storniert", pending: "Ausstehend", partial: "Teilbezahlt", overdue: "Überfällig", detail: "Positionen", calculated: "Berechnet aus Unterkunft und den in der Reservierung erfassten Extras.", addItem: "Position hinzufügen", description: "Beschreibung", quantity: "Menge", unitValue: "Einzelpreis", total: "Gesamt", itemPlaceholder: "Unterkunft, Service oder Extra", deleteItem: "Position löschen", observationsConditions: "Hinweise und Bedingungen", observations: "Hinweise", observationsPlaceholder: "Zusätzliche Informationen für den Kunden", terms: "Geschäftsbedingungen", termsPlaceholder: "Zahlungsfrist, akzeptierte Zahlungsmittel oder weitere Bedingungen", totalsClp: "Summen in CLP", discountPercent: "Rabatt (%)", discountAmount: "Rabatt ($)", taxPercent: "MwSt. / Steuer (%)", additionalFeesAmount: "Zusatzgebühren ($)", subtotal: "Zwischensumme", discount: "Rabatt", tax: "MwSt. / Steuer", additionalFees: "Zusatzgebühren", cancel: "Abbrechen", saveChanges: "Änderungen speichern", generateFromReservation: "Rechnung aus Reservierung erstellen",
  },
}

export function fillInvoiceCopy(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), template)
}
