import type { Language } from "@/lib/hooks/use-language"

export const logisticsCopy: Record<Language, Record<string, string>> = {
  en: {
    saved: "Logistics plan saved. The calendar will be recalculated with this configuration.", label: "Reservation logistics", loadingReservation: "Loading reservation", subtitle: "Configure the external service, transport legs and responsible resources.", close: "Close logistics configuration", arrival: "Arrival", departure: "Departure", loading: "Loading logistics plan...", transportMode: "Transport mode", undefined: "To be defined", flight: "Flight", bus: "Bus", privateVehicle: "Private vehicle", other: "Other", arrivalHub: "Arrival point", finalDestination: "Final destination", pichoy: "Pichoy Airport", busTerminal: "Valdivia Bus Terminal", rebellin: "Rebellín", direct: "Direct / private vehicle", arrivalTime: "Flight, bus or external arrival time", departureTime: "Flight, bus or final commitment time", margin: "Lead time before flight or bus (minutes)", marginPlaceholder: "To be defined", boat: "Boat", unassigned: "Unassigned", boatResponsible: "Boat responsible", vehicle: "Vehicle", driver: "Driver", boatDuration: "Boat duration (min)", roadDuration: "Road duration (min)", planStatus: "Plan status", draft: "Draft", planned: "Planned", confirmed: "Confirmed", completed: "Completed", cancelled: "Cancelled", defaultNote: "Fixed legs start at 30 minutes and can be adjusted when real operations require it.", saving: "Saving...", save: "Save logistics",
  },
  es: {
    saved: "Plan logístico guardado. El calendario se recalculará con esta configuración.", label: "Logística de reserva", loadingReservation: "Cargando reserva", subtitle: "Configure el servicio externo, los tramos de transporte y los recursos responsables.", close: "Cerrar configuración logística", arrival: "Llegada", departure: "Salida", loading: "Cargando plan logístico…", transportMode: "Modo de transporte", undefined: "Por definir", flight: "Vuelo", bus: "Bus", privateVehicle: "Vehículo particular", other: "Otro", arrivalHub: "Punto de arribo", finalDestination: "Destino final", pichoy: "Aeropuerto Pichoy", busTerminal: "Terminal de Buses de Valdivia", rebellin: "Rebellín", direct: "Directo / vehículo particular", arrivalTime: "Hora del vuelo, bus o arribo externo", departureTime: "Hora del vuelo, bus o compromiso final", margin: "Margen previo al vuelo o bus (minutos)", marginPlaceholder: "Pendiente de definir", boat: "Bote", unassigned: "Sin asignar", boatResponsible: "Responsable del bote", vehicle: "Vehículo", driver: "Conductor", boatDuration: "Duración bote (min)", roadDuration: "Duración terrestre (min)", planStatus: "Estado del plan", draft: "Borrador", planned: "Planificado", confirmed: "Confirmado", completed: "Completado", cancelled: "Cancelado", defaultNote: "Los tramos fijos parten en 30 minutos y pueden ajustarse cuando la operación real lo requiera.", saving: "Guardando…", save: "Guardar logística",
  },
  de: {
    saved: "Logistikplan gespeichert. Der Kalender wird mit dieser Konfiguration neu berechnet.", label: "Reservierungslogistik", loadingReservation: "Reservierung wird geladen", subtitle: "Externen Service, Transportabschnitte und verantwortliche Ressourcen konfigurieren.", close: "Logistikkonfiguration schließen", arrival: "Anreise", departure: "Abreise", loading: "Logistikplan wird geladen...", transportMode: "Transportart", undefined: "Noch festzulegen", flight: "Flug", bus: "Bus", privateVehicle: "Privatfahrzeug", other: "Andere", arrivalHub: "Ankunftspunkt", finalDestination: "Endziel", pichoy: "Flughafen Pichoy", busTerminal: "Busbahnhof Valdivia", rebellin: "Rebellín", direct: "Direkt / Privatfahrzeug", arrivalTime: "Zeit des Flugs, Busses oder der externen Ankunft", departureTime: "Zeit des Flugs, Busses oder des finalen Termins", margin: "Vorlauf vor Flug oder Bus (Minuten)", marginPlaceholder: "Noch festzulegen", boat: "Boot", unassigned: "Nicht zugewiesen", boatResponsible: "Bootsverantwortlicher", vehicle: "Fahrzeug", driver: "Fahrer", boatDuration: "Bootsdauer (Min.)", roadDuration: "Fahrtdauer Land (Min.)", planStatus: "Planstatus", draft: "Entwurf", planned: "Geplant", confirmed: "Bestätigt", completed: "Abgeschlossen", cancelled: "Storniert", defaultNote: "Feste Abschnitte starten mit 30 Minuten und können an den realen Betrieb angepasst werden.", saving: "Wird gespeichert...", save: "Logistik speichern",
  },
}
