import type { Language } from "@/lib/hooks/use-language"

export const roomDialogTranslations: Record<Language, Record<string, string>> = {
  en: {
    addRoom: "Add new room", editRoom: "Edit room", roomNumber: "Room number", roomType: "Room type", capacity: "Capacity", rate: "Rate/night", status: "Status", floor: "Floor", location: "Location", amenities: "Amenities (comma separated)", notes: "Notes", cancel: "Cancel", createRoom: "Create room", creating: "Creating...", save: "Save changes", saving: "Saving...", available: "Available", occupied: "Occupied", maintenance: "Maintenance", unavailable: "Unavailable", addBedTo: "Add bed to {room}", bedNumber: "Bed number/name", bedType: "Bed type", single: "Single", double: "Double", queen: "Queen", king: "King", bunk: "Bunk", sofaBed: "Sofa bed", bedAvailable: "Bed is available for booking", addBed: "Add bed", adding: "Adding...", roomPlaceholder: "Suite-1, Cabin-3, etc.", typePlaceholder: "Suite, Cabin, Bunk Room, etc.", floorPlaceholder: "1st, Ground, etc.", locationPlaceholder: "Main Building, North Wing, etc.", amenitiesPlaceholder: "WiFi, AC, Private Bath, Ocean View", notesPlaceholder: "Additional information...", bedPlaceholder: "Bed A, Bunk 1 Top, etc.", bedNotesPlaceholder: "Any special notes about this bed...", createError: "Error creating room: {error}" },
  es: {
    addRoom: "Agregar nueva habitación", editRoom: "Editar habitación", roomNumber: "Número de habitación", roomType: "Tipo de habitación", capacity: "Capacidad", rate: "Tarifa/noche", status: "Estado", floor: "Piso", location: "Ubicación", amenities: "Comodidades (separadas por coma)", notes: "Notas", cancel: "Cancelar", createRoom: "Crear habitación", creating: "Creando...", save: "Guardar cambios", saving: "Guardando...", available: "Disponible", occupied: "Ocupada", maintenance: "Mantenimiento", unavailable: "No disponible", addBedTo: "Agregar cama a {room}", bedNumber: "Número/nombre de cama", bedType: "Tipo de cama", single: "Individual", double: "Doble", queen: "Queen", king: "King", bunk: "Litera", sofaBed: "Sofá cama", bedAvailable: "Cama disponible para reserva", addBed: "Agregar cama", adding: "Agregando...", roomPlaceholder: "Suite-1, Cabaña-3, etc.", typePlaceholder: "Suite, Cabaña, Dormitorio, etc.", floorPlaceholder: "1°, Planta baja, etc.", locationPlaceholder: "Edificio principal, ala norte, etc.", amenitiesPlaceholder: "WiFi, AC, baño privado, vista al mar", notesPlaceholder: "Información adicional...", bedPlaceholder: "Cama A, Litera 1 superior, etc.", bedNotesPlaceholder: "Notas especiales sobre esta cama...", createError: "Error al crear la habitación: {error}" },
  de: {
    addRoom: "Neues Zimmer hinzufügen", editRoom: "Zimmer bearbeiten", roomNumber: "Zimmernummer", roomType: "Zimmertyp", capacity: "Kapazität", rate: "Tarif/Nacht", status: "Status", floor: "Etage", location: "Standort", amenities: "Ausstattung (durch Kommas getrennt)", notes: "Notizen", cancel: "Abbrechen", createRoom: "Zimmer erstellen", creating: "Wird erstellt...", save: "Änderungen speichern", saving: "Wird gespeichert...", available: "Verfügbar", occupied: "Belegt", maintenance: "Wartung", unavailable: "Nicht verfügbar", addBedTo: "Bett zu {room} hinzufügen", bedNumber: "Bettnummer/-name", bedType: "Betttyp", single: "Einzelbett", double: "Doppelbett", queen: "Queensize-Bett", king: "Kingsize-Bett", bunk: "Etagenbett", sofaBed: "Schlafsofa", bedAvailable: "Bett ist für Buchungen verfügbar", addBed: "Bett hinzufügen", adding: "Wird hinzugefügt...", roomPlaceholder: "Suite-1, Hütte-3 usw.", typePlaceholder: "Suite, Hütte, Mehrbettzimmer usw.", floorPlaceholder: "1. Etage, Erdgeschoss usw.", locationPlaceholder: "Hauptgebäude, Nordflügel usw.", amenitiesPlaceholder: "WLAN, Klimaanlage, eigenes Bad, Meerblick", notesPlaceholder: "Zusätzliche Informationen...", bedPlaceholder: "Bett A, Etagenbett 1 oben usw.", bedNotesPlaceholder: "Besondere Hinweise zu diesem Bett...", createError: "Fehler beim Erstellen des Zimmers: {error}" },
}
