"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { ExternalLink, MapPinned, Printer, RefreshCw, Route, WandSparkles } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Plot={id:string;name:string}
type Bed={id:string;plot_id:string;name:string;code:string|null;area_sqm:number|null;length_m:number|null;width_m:number|null;status:string;planning_order:number|null}
type Allocation={bed_id:string;crop_succession_id:string;planned_start_date:string;planned_end_date:string;allocated_area_sqm:number|null}
type Succession={id:string;crop_cycle_id:string;sequence_no:number;planned_sow_date:string;planned_transplant_date:string|null;planned_first_harvest_date:string|null;planned_last_harvest_date:string|null;planned_area_sqm:number|null;status:string}
type Cycle={id:string;crop_name:string;variety:string|null}
type PlacementResult={allocation_ids?:string[];allocated_area_sqm?:number;contiguous_beds?:number;rotation_penalty?:number;available_run_area_sqm?:number}
const today=()=>new Date().toISOString().slice(0,10)
const copy={
 en:{title:"Crop Auto-Placement",description:"Place successions into contiguous bed sequences, preserve overlap authority, and penalize repeating the most recent rotation.",print:"Print",gis:"Open GIS",contiguousBeds:"Contiguous beds",allocatedArea:"Allocated area",runArea:"Run area",rotationPenalty:"Rotation penalty",unallocated:"Unallocated",freeBeds:"Free beds",freeArea:"Free area",eligibleRuns:"Eligible contiguous runs",planner:"Contiguous multi-bed planner",plannerHelp:"Each bed has a stable planning order inside its plot. The RPC locks candidates, chooses a sufficient contiguous run and uses recent crop/family history as a penalty; the exclusion constraint remains the final authority.",succession:"Succession",plot:"Plot",start:"Start",end:"End",requiredArea:"Required area m²",placing:"Placing…",place:"Auto-place contiguously",crop:"Crop",required:"Required",totalFree:"Total free",sequence:"Planning adjacency sequence",sequenceHelp:"An occupied bed breaks the run. Total free area can be sufficient while no contiguous run is large enough.",selectPlot:"Select a plot.",free:"Free",occupied:"Occupied"},
 es:{title:"Auto-ubicación de Cultivos",description:"Ubica sucesiones en secuencias contiguas de camas, preserva la autoridad de solapamiento y penaliza repetir la rotación reciente.",print:"Imprimir",gis:"Abrir GIS",contiguousBeds:"Camas contiguas",allocatedArea:"Área asignada",runArea:"Área del bloque",rotationPenalty:"Penalización rotación",unallocated:"Sin ubicar",freeBeds:"Camas libres",freeArea:"Área libre",eligibleRuns:"Bloques contiguos aptos",planner:"Planificador multi-cama contiguo",plannerHelp:"Cada cama tiene un orden estable dentro del sector. El RPC bloquea candidatas, elige un bloque contiguo suficiente y usa la historia reciente del cultivo/familia como penalización; la restricción de exclusión sigue siendo la autoridad final.",succession:"Sucesión",plot:"Sector",start:"Inicio",end:"Fin",requiredArea:"Área requerida m²",placing:"Ubicando…",place:"Auto-ubicar contiguamente",crop:"Cultivo",required:"Requerido",totalFree:"Área libre total",sequence:"Secuencia física de planificación",sequenceHelp:"Una cama ocupada corta el bloque. El área libre total puede ser suficiente y aun así no existir un bloque contiguo apto.",selectPlot:"Selecciona un sector.",free:"Libre",occupied:"Ocupada"},
 de:{title:"Automatische Kulturplatzierung",description:"Ordne Folgen in zusammenhängenden Beetfolgen an, bewahre die Überschneidungsregeln und bestrafe Wiederholungen der jüngsten Fruchtfolge.",print:"Drucken",gis:"GIS öffnen",contiguousBeds:"Zusammenhängende Beete",allocatedArea:"Zugeordnete Fläche",runArea:"Blockfläche",rotationPenalty:"Fruchtfolge-Strafe",unallocated:"Nicht zugeordnet",freeBeds:"Freie Beete",freeArea:"Freie Fläche",eligibleRuns:"Geeignete zusammenhängende Blöcke",planner:"Planer für zusammenhängende Beete",plannerHelp:"Jedes Beet hat eine stabile Planungsreihenfolge innerhalb der Parzelle. Der RPC sperrt Kandidaten, wählt einen ausreichend großen zusammenhängenden Block und verwendet die jüngste Kultur-/Familienhistorie als Strafwert; die Ausschlussregel bleibt die endgültige Autorität.",succession:"Folge",plot:"Parzelle",start:"Start",end:"Ende",requiredArea:"Benötigte Fläche m²",placing:"Wird platziert…",place:"Zusammenhängend automatisch platzieren",crop:"Kultur",required:"Benötigt",totalFree:"Gesamt frei",sequence:"Physische Planungsreihenfolge",sequenceHelp:"Ein belegtes Beet unterbricht den Block. Die gesamte freie Fläche kann ausreichen, obwohl kein zusammenhängender Block groß genug ist.",selectPlot:"Parzelle auswählen.",free:"Frei",occupied:"Belegt"}
} as const

export default function OrchardAutoPlacePage(){
 const supabase=useMemo(()=>createBrowserClient(),[]); const {language}=useLanguage(); const text=copy[language]
 const [plots,setPlots]=useState<Plot[]>([]);const [beds,setBeds]=useState<Bed[]>([]);const [allocations,setAllocations]=useState<Allocation[]>([]);const [successions,setSuccessions]=useState<Succession[]>([]);const [cycles,setCycles]=useState<Cycle[]>([])
 const [form,setForm]=useState({succession_id:"",plot_id:"",start_date:today(),end_date:today(),area:""});const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [result,setResult]=useState<PlacementResult|null>(null)
 const load=useCallback(async()=>{const [p,b,a,s,c]=await Promise.all([supabase.from("orchard_plots").select("id,name").order("name"),supabase.from("orchard_beds").select("id,plot_id,name,code,area_sqm,length_m,width_m,status,planning_order").eq("status","active").order("planning_order"),supabase.from("orchard_bed_allocations").select("bed_id,crop_succession_id,planned_start_date,planned_end_date,allocated_area_sqm"),supabase.from("orchard_crop_successions").select("id,crop_cycle_id,sequence_no,planned_sow_date,planned_transplant_date,planned_first_harvest_date,planned_last_harvest_date,planned_area_sqm,status").neq("status","cancelled").order("planned_sow_date"),supabase.from("orchard_crop_cycles").select("id,crop_name,variety")]);const e=p.error??b.error??a.error??s.error??c.error;if(e)setError(e.message);else{setPlots((p.data??[]) as Plot[]);setBeds((b.data??[]) as Bed[]);setAllocations((a.data??[]) as Allocation[]);setSuccessions((s.data??[]) as Succession[]);setCycles((c.data??[]) as Cycle[]) }},[supabase]);useEffect(()=>{void load()},[load])
 const cycleById=useMemo(()=>new Map(cycles.map(c=>[c.id,c])),[cycles]); const allocatedIds=useMemo(()=>new Set(allocations.map(a=>a.crop_succession_id)),[allocations]); const queue=successions.filter(s=>!allocatedIds.has(s.id))
 const selected=successions.find(s=>s.id===form.succession_id); const plotBeds=beds.filter(b=>b.plot_id===form.plot_id).sort((a,b)=>(a.planning_order??9999)-(b.planning_order??9999)); const area=(b:Bed)=>Number(b.area_sqm??((b.length_m??0)*(b.width_m??0)))
 const isFree=(b:Bed)=>!allocations.some(a=>a.bed_id===b.id&&a.planned_start_date<=form.end_date&&a.planned_end_date>=form.start_date); const freeBeds=plotBeds.filter(isFree); const freeArea=freeBeds.reduce((sum,b)=>sum+area(b),0); const required=Number(form.area||selected?.planned_area_sqm||0)
 const runs=useMemo(()=>{const out:{beds:Bed[];area:number}[]=[];let current:{beds:Bed[];area:number}|null=null;for(const bed of plotBeds){if(!isFree(bed)){current=null;continue}if(!current){current={beds:[],area:0};out.push(current)}current.beds.push(bed);current.area+=area(bed)}return out},[plotBeds,allocations,form.start_date,form.end_date])
 const eligibleRuns=runs.filter(r=>r.area>=required&&required>0)
 function pickSuccession(id:string){const s=successions.find(x=>x.id===id);if(!s)return;setResult(null);setForm(f=>({...f,succession_id:id,start_date:s.planned_transplant_date??s.planned_sow_date,end_date:s.planned_last_harvest_date??s.planned_first_harvest_date??s.planned_transplant_date??s.planned_sow_date,area:s.planned_area_sqm?String(s.planned_area_sqm):""}))}
 async function autoPlace(){if(!form.succession_id||!form.plot_id||!form.start_date||!form.end_date||required<=0)return;setSaving(true);setError(null);setResult(null);const r=await supabase.rpc("orchard_auto_place_succession",{p_succession_id:form.succession_id,p_plot_id:form.plot_id,p_start_date:form.start_date,p_end_date:form.end_date,p_required_area_sqm:required});if(r.error)setError(r.error.message);else{setResult((r.data??{}) as PlacementResult);await load()}setSaving(false)}
 const selectedCycle=selected?cycleById.get(selected.crop_cycle_id):null
 return <AppLayout><PageHeader title={text.title} description={text.description} actions={<div className="flex gap-2"><Button variant="outline" onClick={()=>window.print()}><Printer className="mr-2 h-4 w-4"/>{text.print}</Button><Button variant="outline" asChild><Link href={`/${language}/map`}><MapPinned className="mr-2 h-4 w-4"/>{text.gis}<ExternalLink className="ml-2 h-3 w-3"/></Link></Button><Button variant="outline" onClick={()=>void load()} aria-label={text.title}><RefreshCw className="h-4 w-4"/></Button></div>}/><OrchardNavigation/><div className="space-y-6 p-3 pb-24 sm:p-8">
 {error&&<Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
 {result&&<Card className="border-emerald-500/40"><CardContent className="grid gap-3 p-4 sm:grid-cols-4"><MetricInline label={text.contiguousBeds} value={String(result.contiguous_beds??0)}/><MetricInline label={text.allocatedArea} value={`${Number(result.allocated_area_sqm??0).toFixed(1)} m²`}/><MetricInline label={text.runArea} value={`${Number(result.available_run_area_sqm??0).toFixed(1)} m²`}/><MetricInline label={text.rotationPenalty} value={String(result.rotation_penalty??0)}/></CardContent></Card>}
 <div className="grid gap-4 sm:grid-cols-4"><Metric label={text.unallocated} value={queue.length}/><Metric label={text.freeBeds} value={freeBeds.length}/><Metric label={text.freeArea} value={`${freeArea.toFixed(1)} m²`}/><Metric label={text.eligibleRuns} value={eligibleRuns.length}/></div>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Route className="h-5 w-5"/>{text.planner}</CardTitle><CardDescription>{text.plannerHelp}</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-5"><Field label={text.succession}><Select value={form.succession_id} onValueChange={pickSuccession}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{queue.map(s=>{const c=cycleById.get(s.crop_cycle_id);return <SelectItem key={s.id} value={s.id}>{c?.crop_name??text.crop}{c?.variety?` · ${c.variety}`:""} #{s.sequence_no}</SelectItem>})}</SelectContent></Select></Field><Field label={text.plot}><Select value={form.plot_id} onValueChange={v=>{setResult(null);setForm(f=>({...f,plot_id:v}))}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{plots.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></Field><Field label={text.start}><Input type="date" value={form.start_date} onChange={e=>setForm(f=>({...f,start_date:e.target.value}))}/></Field><Field label={text.end}><Input type="date" value={form.end_date} onChange={e=>setForm(f=>({...f,end_date:e.target.value}))}/></Field><Field label={text.requiredArea}><Input type="number" min="0.1" step="0.1" value={form.area} onChange={e=>setForm(f=>({...f,area:e.target.value}))}/></Field><div className="md:col-span-5 flex flex-wrap items-center gap-3"><Button onClick={()=>void autoPlace()} disabled={saving||!form.succession_id||!form.plot_id||required<=0||eligibleRuns.length===0}><WandSparkles className="mr-2 h-4 w-4"/>{saving?text.placing:text.place}</Button><Badge variant={eligibleRuns.length>0?"default":"destructive"}>{selectedCycle?.crop_name??text.crop} · {text.required}: {required.toFixed(1)} m² · {text.totalFree}: {freeArea.toFixed(1)} m²</Badge></div></CardContent></Card>
 <Card><CardHeader><CardTitle>{text.sequence}</CardTitle><CardDescription>{text.sequenceHelp}</CardDescription></CardHeader><CardContent>{!form.plot_id?<p className="text-sm text-muted-foreground">{text.selectPlot}</p>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{plotBeds.map(b=><div key={b.id} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">#{b.planning_order??"—"} · {b.code?`${b.code} · `:""}{b.name}</p><p className="text-xs text-muted-foreground">{area(b).toFixed(1)} m²</p></div><Badge variant={isFree(b)?"outline":"secondary"}>{isFree(b)?text.free:text.occupied}</Badge></div></div>)}</div>}</CardContent></Card>
 </div></AppLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Metric({label,value}:{label:string;value:number|string}){return <Card><CardContent className="p-4"><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>}
function MetricInline({label,value}:{label:string;value:string}){return <div><p className="text-lg font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>}
