"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { ExternalLink, MapPinned, Printer, RefreshCw, Route, WandSparkles } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Plot={id:string;name:string}
type Bed={id:string;plot_id:string;name:string;code:string|null;area_sqm:number|null;length_m:number|null;width_m:number|null;status:string;planning_order:number|null}
type Allocation={bed_id:string;crop_succession_id:string;planned_start_date:string;planned_end_date:string;allocated_area_sqm:number|null}
type Succession={id:string;crop_cycle_id:string;sequence_no:number;planned_sow_date:string;planned_transplant_date:string|null;planned_first_harvest_date:string|null;planned_last_harvest_date:string|null;planned_area_sqm:number|null;status:string}
type Cycle={id:string;crop_name:string;variety:string|null}
type PlacementResult={allocation_ids?:string[];allocated_area_sqm?:number;contiguous_beds?:number;rotation_penalty?:number;available_run_area_sqm?:number}
const today=()=>new Date().toISOString().slice(0,10)
const BED_CONTEXT_PHOTO="https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&w=1600&q=92"

export default function OrchardAutoPlacePage(){
 const supabase=useMemo(()=>createBrowserClient(),[]); const {language}=useLanguage(); const es=language==="es"
 const [plots,setPlots]=useState<Plot[]>([]);const [beds,setBeds]=useState<Bed[]>([]);const [allocations,setAllocations]=useState<Allocation[]>([]);const [successions,setSuccessions]=useState<Succession[]>([]);const [cycles,setCycles]=useState<Cycle[]>([])
 const [form,setForm]=useState({succession_id:"",plot_id:"",start_date:today(),end_date:today(),area:""});const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [result,setResult]=useState<PlacementResult|null>(null)
 const load=useCallback(async()=>{const [p,b,a,s,c]=await Promise.all([supabase.from("orchard_plots").select("id,name").order("name"),supabase.from("orchard_beds").select("id,plot_id,name,code,area_sqm,length_m,width_m,status,planning_order").eq("status","active").order("planning_order"),supabase.from("orchard_bed_allocations").select("bed_id,crop_succession_id,planned_start_date,planned_end_date,allocated_area_sqm"),supabase.from("orchard_crop_successions").select("id,crop_cycle_id,sequence_no,planned_sow_date,planned_transplant_date,planned_first_harvest_date,planned_last_harvest_date,planned_area_sqm,status").neq("status","cancelled").order("planned_sow_date"),supabase.from("orchard_crop_cycles").select("id,crop_name,variety")]);const e=p.error??b.error??a.error??s.error??c.error;if(e)setError(e.message);else{setPlots((p.data??[]) as Plot[]);setBeds((b.data??[]) as Bed[]);setAllocations((a.data??[]) as Allocation[]);setSuccessions((s.data??[]) as Succession[]);setCycles((c.data??[]) as Cycle[]) }},[supabase]);useEffect(()=>{void load()},[load])
 const cycleById=useMemo(()=>new Map(cycles.map(c=>[c.id,c])),[cycles]); const allocatedIds=useMemo(()=>new Set(allocations.map(a=>a.crop_succession_id)),[allocations]); const queue=successions.filter(s=>!allocatedIds.has(s.id))
 const selected=successions.find(s=>s.id===form.succession_id); const plotBeds=beds.filter(b=>b.plot_id===form.plot_id).sort((a,b)=>(a.planning_order??9999)-(b.planning_order??9999)); const area=(b:Bed)=>Number(b.area_sqm??((b.length_m??0)*(b.width_m??0)))
 const isFree=(b:Bed)=>!allocations.some(a=>a.bed_id===b.id&&a.planned_start_date<=form.end_date&&a.planned_end_date>=form.start_date); const freeBeds=plotBeds.filter(isFree); const freeArea=freeBeds.reduce((sum,b)=>sum+area(b),0); const required=Number(form.area||selected?.planned_area_sqm||0)
 const runs=useMemo(()=>{const out:{beds:Bed[];area:number}[]=[];let current:{beds:Bed[];area:number}|null=null;for(const bed of plotBeds){if(!isFree(bed)){current=null;continue}if(!current){current={beds:[],area:0};out.push(current)}current.beds.push(bed);current.area+=area(bed)}return out},[plotBeds,allocations,form.start_date,form.end_date])
 const eligibleRuns=runs.filter(r=>r.area>=required&&required>0)
 function pickSuccession(id:string){const s=successions.find(x=>x.id===id);if(!s)return;setResult(null);setForm(f=>({...f,succession_id:id,start_date:s.planned_transplant_date??s.planned_sow_date,end_date:s.planned_last_harvest_date??s.planned_first_harvest_date??s.planned_transplant_date??s.planned_sow_date,area:s.planned_area_sqm?String(s.planned_area_sqm):""}))}
 async function autoPlace(){if(!form.succession_id||!form.plot_id||!form.start_date||!form.end_date||required<=0)return;setSaving(true);setError(null);setResult(null);const r=await supabase.rpc("orchard_auto_place_succession",{p_succession_id:form.succession_id,p_plot_id:form.plot_id,p_start_date:form.start_date,p_end_date:form.end_date,p_required_area_sqm:required});if(r.error)setError(r.error.message);else{setResult((r.data??{}) as PlacementResult);await load()}setSaving(false)}
 const selectedCycle=selected?cycleById.get(selected.crop_cycle_id):null
 return <AppLayout><PageHeader title={es?"Auto-ubicación de Cultivos":"Crop Auto-Placement"} description={es?"Ubica sucesiones en secuencias contiguas de camas, preserva la autoridad de solapamiento y penaliza repetir la rotación reciente.":"Place successions into contiguous bed sequences, preserve overlap authority, and penalize repeating the most recent rotation."} actions={<div className="flex gap-2"><Button variant="outline" onClick={()=>window.print()}><Printer className="mr-2 h-4 w-4"/>{es?"Imprimir":"Print"}</Button><Button variant="outline" asChild><Link href={`/${language}/map`}><MapPinned className="mr-2 h-4 w-4"/>{es?"Abrir GIS":"Open GIS"}<ExternalLink className="ml-2 h-3 w-3"/></Link></Button><Button variant="outline" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/></Button></div>}/><OrchardNavigation/><div className="space-y-6 p-3 pb-24 sm:p-8">
 {error&&<Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
 {result&&<Card className="border-emerald-500/40"><CardContent className="grid gap-3 p-4 sm:grid-cols-4"><MetricInline label={es?"Camas contiguas":"Contiguous beds"} value={String(result.contiguous_beds??0)}/><MetricInline label={es?"Área asignada":"Allocated area"} value={`${Number(result.allocated_area_sqm??0).toFixed(1)} m²`}/><MetricInline label={es?"Área del bloque":"Run area"} value={`${Number(result.available_run_area_sqm??0).toFixed(1)} m²`}/><MetricInline label={es?"Penalización rotación":"Rotation penalty"} value={String(result.rotation_penalty??0)}/></CardContent></Card>}
 <div className="relative min-h-[190px] overflow-hidden border"><img src={BED_CONTEXT_PHOTO} alt={es?"Camas de cultivo organizadas para planificación espacial":"Organized crop beds for spatial planning"} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,10,8,.9),rgba(7,10,8,.45))]"/><div className="relative z-10 flex min-h-[190px] max-w-2xl flex-col justify-end p-5 text-white"><p className="text-[10px] uppercase tracking-[.18em] text-white/65">{es?"Contexto físico":"Physical context"}</p><h2 className="mt-2 text-2xl text-white!">{es?"Ubicación basada en camas reales":"Placement based on real beds"}</h2><p className="mt-2 text-sm text-white/70">{es?"La auto-ubicación trabaja sobre secuencias de camas, ocupación y rotación; la fotografía refleja el espacio físico que se está planificando.":"Auto-placement operates on bed sequences, occupancy and rotation; the imagery reflects the physical space being planned."}</p></div></div>
 <div className="grid gap-4 sm:grid-cols-4"><Metric label={es?"Sin ubicar":"Unallocated"} value={queue.length}/><Metric label={es?"Camas libres":"Free beds"} value={freeBeds.length}/><Metric label={es?"Área libre":"Free area"} value={`${freeArea.toFixed(1)} m²`}/><Metric label={es?"Bloques contiguos aptos":"Eligible contiguous runs"} value={eligibleRuns.length}/></div>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Route className="h-5 w-5"/>{es?"Planificador multi-cama contiguo":"Contiguous multi-bed planner"}</CardTitle><CardDescription>{es?"Cada cama tiene un orden estable dentro del sector. El RPC bloquea candidatas, elige un bloque contiguo suficiente y usa la historia reciente del cultivo/familia como penalización; la restricción de exclusión sigue siendo la autoridad final.":"Each bed has a stable planning order inside its plot. The RPC locks candidates, chooses a sufficient contiguous run and uses recent crop/family history as a penalty; the exclusion constraint remains the final authority."}</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-5"><Field label={es?"Sucesión":"Succession"}><Select value={form.succession_id} onValueChange={pickSuccession}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{queue.map(s=>{const c=cycleById.get(s.crop_cycle_id);return <SelectItem key={s.id} value={s.id}>{c?.crop_name??"Crop"}{c?.variety?` · ${c.variety}`:""} #{s.sequence_no}</SelectItem>})}</SelectContent></Select></Field><Field label={es?"Sector":"Plot"}><Select value={form.plot_id} onValueChange={v=>{setResult(null);setForm(f=>({...f,plot_id:v}))}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{plots.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></Field><Field label={es?"Inicio":"Start"}><Input type="date" value={form.start_date} onChange={e=>setForm(f=>({...f,start_date:e.target.value}))}/></Field><Field label={es?"Fin":"End"}><Input type="date" value={form.end_date} onChange={e=>setForm(f=>({...f,end_date:e.target.value}))}/></Field><Field label={es?"Área requerida m²":"Required area m²"}><Input type="number" min="0.1" step="0.1" value={form.area} onChange={e=>setForm(f=>({...f,area:e.target.value}))}/></Field><div className="md:col-span-5 flex flex-wrap items-center gap-3"><Button onClick={()=>void autoPlace()} disabled={saving||!form.succession_id||!form.plot_id||required<=0||eligibleRuns.length===0}><WandSparkles className="mr-2 h-4 w-4"/>{saving?(es?"Ubicando…":"Placing…"):(es?"Auto-ubicar contiguamente":"Auto-place contiguously")}</Button><Badge variant={eligibleRuns.length>0?"default":"destructive"}>{selectedCycle?.crop_name??(es?"Cultivo":"Crop")} · {es?"Requerido":"Required"}: {required.toFixed(1)} m² · {es?"Área libre total":"Total free"}: {freeArea.toFixed(1)} m²</Badge></div></CardContent></Card>
 <Card><CardHeader><CardTitle>{es?"Secuencia física de planificación":"Planning adjacency sequence"}</CardTitle><CardDescription>{es?"Una cama ocupada corta el bloque. El área libre total puede ser suficiente y aun así no existir un bloque contiguo apto.":"An occupied bed breaks the run. Total free area can be sufficient while no contiguous run is large enough."}</CardDescription></CardHeader><CardContent>{!form.plot_id?<p className="text-sm text-muted-foreground">{es?"Selecciona un sector.":"Select a plot."}</p>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{plotBeds.map(b=><div key={b.id} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">#{b.planning_order??"—"} · {b.code?`${b.code} · `:""}{b.name}</p><p className="text-xs text-muted-foreground">{area(b).toFixed(1)} m²</p></div><Badge variant={isFree(b)?"outline":"secondary"}>{isFree(b)?(es?"Libre":"Free"):(es?"Ocupada":"Occupied")}</Badge></div></div>)}</div>}</CardContent></Card>
 </div></AppLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Metric({label,value}:{label:string;value:number|string}){return <Card><CardContent className="p-4"><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>}
function MetricInline({label,value}:{label:string;value:string}){return <div><p className="text-lg font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>}