"use client"

import Link from "next/link"
import { FormEvent, useEffect, useMemo, useState } from "react"
import { ArrowRight, CalendarDays, ChevronLeft, ChevronRight, CircleAlert, FlaskConical, PackageOpen, Search, Sprout } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { cropChipStyle, cropColor } from "@/lib/orchard/crop-identity"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"
import nurseryReference from "@/data/orchard/dietrich-nursery-2026-27.json"
import containerPlan from "@/data/orchard/dietrich-nursery-container-plan-2026-27.json"

type Locale = "en" | "es" | "de"
type Plan = { id:string; season:string|null; status:string }
type Cycle = { id:string; game_plan_id:string; crop_name:string; cycle_type:string }
type Succession = { id:string; crop_cycle_id:string; sequence_no:number; planned_sow_date:string; planned_transplant_date:string|null; planned_plants:number|null; germination_rate_pct:number|null; status:string }
type Allocation = { crop_succession_id:string }
type CropProfile = { crop_name:string; crop_family:string|null }
type NurseryRef = { cycle_name:string; reference_crop:string; tray_cells:string|number; germination_temp:string; days_to_germinate:string|number; days_in_nursery:string|number; seeding_technique:string|null; nursery_notes:string|null }
type ContainerRow = { container:string; max_projected:number; total_usage:number; current_in_use:number }
type FarmSettings = { id:string; nursery_usable_surface_m2:number|string|null }

const copy = {
 en:{eyebrow:"Orchard · Nursery",title:"Nursery",description:"Capacity, projected containers and propagation timing for physically reconciled transplant plantings.",transplantPlantings:"Transplant plantings",seedLots:"Seed lots",batches:"Observed batches",observedGerm:"Observed germination",none:"None yet",space:"Nursery space",spaceHelp:"Enter usable tray surface in square metres. If tables have multiple levels, include the usable surface of every level. This is not the building footprint.",spaceUnknown:"Not confirmed",saveSpace:"Save nursery space",spaceSaved:"Nursery space saved",spaceError:"Could not save nursery space",weeklyUsage:"Weekly nursery space usage",usagePending:"Confirm usable nursery surface to calculate capacity percentage. Container footprint evidence is still required before Black Swan will infer occupied m².",usageReady:"Usable nursery surface is confirmed. Occupied m² remains intentionally uncalculated until canonical container footprint evidence exists.",peakUsage:"Peak nursery usage for the season",projection:"Containers",projectionHelp:"Reconciled planning values from Dietrich's Nursery/Crop Chart. Current use remains evidence-based and is never inferred from planned dates.",search:"Search containers...",container:"Name",maxProjected:"Peak usage",totalUsage:"Total use",currentUse:"Current in use",schedule:"Propagation schedule",crop:"Crop",sow:"Nursery sow",transplant:"Field transplant",plants:"Planned plants",refContainer:"Source container",germDays:"Germination",nurseryDays:"Nursery",technique:"Technique",evidence:"Evidence",unresolved:"Expected germination unresolved",days:"d",advanced:"Open seed & nursery management",methods:"Open sowing methods",source:"Planning projection only. Actual nursery evidence comes from orchard_nursery_batches; actual seed inventory comes from orchard_seed_lots. Nursery surface is operator-confirmed physical capacity.",loadError:"Could not load the reconciled nursery plan."},
 es:{eyebrow:"Huerto · Almácigo",title:"Almácigo",description:"Capacidad, contenedores proyectados y calendario de propagación para trasplantes físicamente reconciliados.",transplantPlantings:"Trasplantes planificados",seedLots:"Lotes de semilla",batches:"Batches observados",observedGerm:"Germinación observada",none:"Aún no existe",space:"Espacio de almácigo",spaceHelp:"Ingresa la superficie útil para bandejas en m². Si las mesas tienen varios niveles, incluye la superficie utilizable de todos los niveles. No es la huella física del edificio.",spaceUnknown:"Sin confirmar",saveSpace:"Guardar espacio",spaceSaved:"Espacio de almácigo guardado",spaceError:"No fue posible guardar el espacio",weeklyUsage:"Uso semanal del espacio de almácigo",usagePending:"Confirma la superficie útil para calcular porcentaje de capacidad. Aún se requiere evidencia canónica del área física de cada contenedor antes de inferir m² ocupados.",usageReady:"La superficie útil está confirmada. Los m² ocupados permanecen sin calcular hasta contar con evidencia canónica del área de cada contenedor.",peakUsage:"Máximo uso de almácigo de la temporada",projection:"Contenedores",projectionHelp:"Valores de planificación reconciliados desde Nursery/Crop Chart de Dietrich. El uso actual se mantiene basado en evidencia y nunca se infiere por fecha planificada.",search:"Buscar contenedores...",container:"Nombre",maxProjected:"Máximo proyectado",totalUsage:"Uso total",currentUse:"En uso ahora",schedule:"Programa de propagación",crop:"Cultivo",sow:"Siembra almácigo",transplant:"Trasplante campo",plants:"Plantas planificadas",refContainer:"Contenedor fuente",germDays:"Germinación",nurseryDays:"Almácigo",technique:"Técnica",evidence:"Evidencia",unresolved:"Germinación esperada sin resolver",days:"d",advanced:"Abrir gestión de semillas y almácigos",methods:"Abrir métodos de siembra",source:"Sólo proyección de planificación. La evidencia real de almácigo viene de orchard_nursery_batches; el inventario real de semillas viene de orchard_seed_lots. La superficie de almácigo es capacidad física confirmada por operador.",loadError:"No fue posible cargar el plan reconciliado de almácigo."},
 de:{eyebrow:"Orchard · Anzucht",title:"Anzucht",description:"Kapazität, projizierte Behälter und Vermehrungsplan für physisch abgeglichene Transplant-Pflanzungen.",transplantPlantings:"Geplante Transplants",seedLots:"Saatgutlose",batches:"Beobachtete Chargen",observedGerm:"Beobachtete Keimung",none:"Noch keine",space:"Anzuchtfläche",spaceHelp:"Nutzbare Stellfläche für Anzuchtbehälter in m² eingeben. Bei mehrstöckigen Tischen die nutzbare Fläche aller Ebenen addieren. Nicht die Gebäudegrundfläche.",spaceUnknown:"Nicht bestätigt",saveSpace:"Anzuchtfläche speichern",spaceSaved:"Anzuchtfläche gespeichert",spaceError:"Anzuchtfläche konnte nicht gespeichert werden",weeklyUsage:"Wöchentliche Nutzung der Anzuchtfläche",usagePending:"Nutzbare Anzuchtfläche bestätigen, um Kapazitätsprozent zu berechnen. Für belegte m² bleibt kanonischer Nachweis der Behälterfläche erforderlich.",usageReady:"Die nutzbare Anzuchtfläche ist bestätigt. Belegte m² werden erst mit kanonischem Nachweis der Behälterfläche berechnet.",peakUsage:"Maximale Anzuchtnutzung der Saison",projection:"Behälter",projectionHelp:"Abgeglichene Planwerte aus Dietrich Nursery/Crop Chart. Aktuelle Nutzung bleibt evidenzbasiert und wird nicht aus Plandaten abgeleitet.",search:"Behälter suchen...",container:"Name",maxProjected:"Spitzennutzung",totalUsage:"Gesamtnutzung",currentUse:"Aktuell in Nutzung",schedule:"Vermehrungsplan",crop:"Kultur",sow:"Aussaat Anzucht",transplant:"Feldpflanzung",plants:"Geplante Pflanzen",refContainer:"Quellbehälter",germDays:"Keimung",nurseryDays:"Anzucht",technique:"Technik",evidence:"Nachweis",unresolved:"Erwartete Keimung ungeklärt",days:"T",advanced:"Saatgut- & Anzuchtverwaltung öffnen",methods:"Aussaatmethoden öffnen",source:"Nur Planprojektion. Reale Anzuchtnachweise stammen aus orchard_nursery_batches; reales Saatgutinventar aus orchard_seed_lots. Anzuchtfläche ist operatorbestätigte physische Kapazität.",loadError:"Der abgeglichene Anzuchtplan konnte nicht geladen werden."}
} as const

const localeMap:Record<Locale,string>={en:"en-US",es:"es-CL",de:"de-DE"}
const dateLabel=(value:string|null,locale:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString(locale,{day:"2-digit",month:"short",year:"numeric"}):"—"
const normalize=(value:string)=>value.trim().toLowerCase()
const dateKey=(value:Date)=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`
const addDays=(value:Date,days:number)=>{const next=new Date(value);next.setDate(next.getDate()+days);return next}
const mondayOf=(value:Date)=>{const next=new Date(value);next.setHours(12,0,0,0);const day=(next.getDay()+6)%7;next.setDate(next.getDate()-day);return next}

export default function NurseryOverviewPage(){
 const supabase=useMemo(()=>createBrowserClient(),[])
 const {language}=useLanguage();const lang:Locale=language;const text=copy[lang];const locale=localeMap[lang]
 const [plans,setPlans]=useState<Plan[]>([]),[cycles,setCycles]=useState<Cycle[]>([]),[successions,setSuccessions]=useState<Succession[]>([]),[allocations,setAllocations]=useState<Allocation[]>([]),[profiles,setProfiles]=useState<CropProfile[]>([])
 const [seedLots,setSeedLots]=useState(0),[batches,setBatches]=useState(0),[farmSettings,setFarmSettings]=useState<FarmSettings|null>(null)
 const [capacityDraft,setCapacityDraft]=useState(""),[capacityMessage,setCapacityMessage]=useState<string|null>(null),[savingCapacity,setSavingCapacity]=useState(false),[containerQuery,setContainerQuery]=useState(""),[weekOffset,setWeekOffset]=useState(0)
 const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)

 useEffect(()=>{let live=true;setLoading(true);setError(null);void Promise.all([
  supabase.from("orchard_game_plans").select("id,season,status").order("start_date",{ascending:false}),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name,cycle_type"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id,sequence_no,planned_sow_date,planned_transplant_date,planned_plants,germination_rate_pct,status").neq("status","cancelled").order("planned_sow_date"),
  supabase.from("orchard_bed_allocations").select("crop_succession_id"),
  supabase.from("orchard_seed_lots").select("id",{count:"exact",head:true}),
  supabase.from("orchard_nursery_batches").select("id",{count:"exact",head:true}),
  supabase.from("orchard_crop_library").select("crop_name,crop_family").eq("is_active",true).eq("classification_scheme","black_swan_canonical").eq("classification_code","fundo_corcovado"),
  supabase.from("orchard_farm_settings").select("id,nursery_usable_surface_m2").eq("farm_key","black_swan_orchard").single(),
 ]).then(([p,c,s,a,l,b,f,fs])=>{if(!live)return;const first=p.error??c.error??s.error??a.error??l.error??b.error??f.error??fs.error;if(first){setError(`${text.loadError} ${first.message}`);setLoading(false);return}setPlans((p.data??[]) as Plan[]);setCycles((c.data??[]) as Cycle[]);setSuccessions((s.data??[]) as Succession[]);setAllocations((a.data??[]) as Allocation[]);setSeedLots(l.count??0);setBatches(b.count??0);setProfiles((f.data??[]) as CropProfile[]);const settings=fs.data as FarmSettings;setFarmSettings(settings);setCapacityDraft(settings.nursery_usable_surface_m2==null?"":String(settings.nursery_usable_surface_m2));setLoading(false)});return()=>{live=false}},[supabase,text.loadError])

 const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null
 const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const familyByCrop=new Map(profiles.map(profile=>[normalize(profile.crop_name),profile.crop_family]));const familyFor=(crop:string)=>familyByCrop.get(normalize(crop))??null
 const cycleById=new Map(cycles.filter(c=>c.game_plan_id===plan?.id).map(c=>[c.id,c]));const allocatedIds=new Set(allocations.map(a=>a.crop_succession_id));const transplantSuccessions=successions.filter(s=>allocatedIds.has(s.id)&&cycleById.get(s.crop_cycle_id)?.cycle_type==="transplant")
 const refByCycle=new Map((nurseryReference as NurseryRef[]).map(r=>[r.cycle_name,r]));const rows=transplantSuccessions.map(s=>({s,cycle:cycleById.get(s.crop_cycle_id)!,ref:refByCycle.get(cycleById.get(s.crop_cycle_id)!.crop_name)??null})).sort((a,b)=>a.s.planned_sow_date.localeCompare(b.s.planned_sow_date))
 const observedGermination=batches>0?"—":text.none;const capacity=farmSettings?.nursery_usable_surface_m2==null?null:Number(farmSettings.nursery_usable_surface_m2)
 const containers=(containerPlan.containers as ContainerRow[]).filter(row=>!containerQuery.trim()||row.container.toLowerCase().includes(containerQuery.trim().toLowerCase()))
 const advancedHref=`/${language}/orchard/nursery${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`;const methodsHref=`/${language}/orchard/game-plan/propagation${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`
 const weekText=lang==="es"?{title:"Esta semana en almácigo",today:"Hoy",planned:"Sólo planificación",sow:"Siembra",transplant:"Trasplante",empty:"Sin movimientos planificados",current:"Semana actual"}:lang==="de"?{title:"Diese Woche in der Anzucht",today:"Heute",planned:"Nur Planung",sow:"Aussaat",transplant:"Pflanzung",empty:"Keine geplanten Vorgänge",current:"Aktuelle Woche"}:{title:"This week in nursery",today:"Today",planned:"Planning only",sow:"Sow",transplant:"Transplant",empty:"No planned moves",current:"Current week"}
 const weekStart=useMemo(()=>addDays(mondayOf(new Date()),weekOffset*7),[weekOffset]);const weekDays=useMemo(()=>Array.from({length:7},(_,index)=>addDays(weekStart,index)),[weekStart]);const today=dateKey(new Date())
 const eventsByDay=weekDays.map(day=>{const key=dateKey(day);const events=rows.flatMap(({s,cycle})=>{const items:{kind:"sow"|"transplant";crop:string;sequence:number}[]=[];if(s.planned_sow_date===key)items.push({kind:"sow",crop:cycle.crop_name,sequence:s.sequence_no});if(s.planned_transplant_date===key)items.push({kind:"transplant",crop:cycle.crop_name,sequence:s.sequence_no});return items});return {day,key,events}})

 async function saveCapacity(event:FormEvent){event.preventDefault();if(!farmSettings)return;const parsed=capacityDraft.trim()===""?null:Number(capacityDraft);if(parsed!=null&&(!Number.isFinite(parsed)||parsed<0))return;setSavingCapacity(true);setCapacityMessage(null);const result=await supabase.from("orchard_farm_settings").update({nursery_usable_surface_m2:parsed}).eq("id",farmSettings.id).select("id,nursery_usable_surface_m2").single();if(result.error)setCapacityMessage(text.spaceError);else{const settings=result.data as FarmSettings;setFarmSettings(settings);setCapacityDraft(settings.nursery_usable_surface_m2==null?"":String(settings.nursery_usable_surface_m2));setCapacityMessage(text.spaceSaved)}setSavingCapacity(false)}

 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1560px] px-4 pb-16 pt-6 sm:px-6 lg:px-8">
  <header className="mb-4 max-w-5xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--orchard-green)]">{text.eyebrow}</p><div className="mt-1.5 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-normal sm:text-4xl">{text.title}</h1>{plan?.season?<Badge variant="secondary">{plan.season}</Badge>:null}</div><p className="mt-2 max-w-4xl text-sm leading-5 text-muted-foreground">{text.description}</p></header>
  {loading?<div className="py-12 text-sm text-muted-foreground">…</div>:error?<div className="border-y border-red-400/30 py-4 text-sm text-red-300">{error}</div>:<>
   <section className="mb-4 grid border-y border-[var(--bs-divider-subtle)] sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Sprout} label={text.transplantPlantings} value={String(rows.length)}/><Metric icon={PackageOpen} label={text.seedLots} value={String(seedLots)}/><Metric icon={FlaskConical} label={text.batches} value={String(batches)}/><Metric icon={CircleAlert} label={text.observedGerm} value={observedGermination}/></section>

   <section className="mb-5 border-y border-[var(--bs-divider-subtle)] py-3"><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[var(--orchard-green)]"/><div><h2 className="text-lg font-normal">{weekText.title}</h2><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">{weekStart.toLocaleDateString(locale,{day:"2-digit",month:"short"})} — {addDays(weekStart,6).toLocaleDateString(locale,{day:"2-digit",month:"short",year:"numeric"})} · {weekText.planned}</p></div></div><div className="flex items-center gap-1"><button type="button" aria-label="Previous week" onClick={()=>setWeekOffset(value=>value-1)} className="flex h-9 w-9 items-center justify-center border border-[var(--bs-divider-subtle)]"><ChevronLeft className="h-4 w-4"/></button><button type="button" onClick={()=>setWeekOffset(0)} className="h-9 border border-[var(--bs-divider-subtle)] px-3 text-xs">{weekText.current}</button><button type="button" aria-label="Next week" onClick={()=>setWeekOffset(value=>value+1)} className="flex h-9 w-9 items-center justify-center border border-[var(--bs-divider-subtle)]"><ChevronRight className="h-4 w-4"/></button></div></div><div className="overflow-x-auto"><div className="grid min-w-[820px] grid-cols-7 gap-px bg-[var(--bs-divider-subtle)]">{eventsByDay.map(({day,key,events})=><div key={key} className={`min-h-28 bg-[var(--bs-surface-primary)] p-2.5 ${key===today?"ring-1 ring-inset ring-[var(--orchard-green)]":""}`}><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">{day.toLocaleDateString(locale,{weekday:"short"})}</p><p className="mt-0.5 text-lg tabular-nums">{day.getDate()}</p></div>{key===today?<span className="text-[9px] uppercase tracking-[.1em] text-[var(--orchard-green)]">{weekText.today}</span>:null}</div><div className="mt-2 space-y-1.5">{events.length===0?<p className="text-[10px] leading-4 text-muted-foreground">{weekText.empty}</p>:events.map((event,index)=>{const family=familyFor(event.crop);const color=cropColor(event.crop,family);return <div key={`${event.kind}-${event.crop}-${event.sequence}-${index}`} className="border-l-2 pl-2" style={{borderColor:color}}><p className="truncate text-[11px] font-medium">{event.crop} #{event.sequence}</p><p className="text-[9px] uppercase tracking-[.08em] text-muted-foreground">{event.kind==="sow"?weekText.sow:weekText.transplant}</p></div>})}</div></div>)}</div></div></section>

   <section className="mb-5 grid gap-4 border-y border-[var(--bs-divider-subtle)] py-4 lg:grid-cols-[1.1fr_.9fr]">
    <div><p className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">{text.weeklyUsage}</p><div className="mt-3 flex min-h-28 items-center justify-center border-b border-l border-[var(--bs-divider-subtle)]"><span className="text-3xl text-muted-foreground">—</span></div><p className="mt-3 text-xs leading-5 text-muted-foreground">{capacity==null?text.usagePending:text.usageReady}</p></div>
    <form onSubmit={saveCapacity} className="border-l-0 border-[var(--bs-divider-subtle)] lg:border-l lg:pl-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">{text.space}</p><p className="mt-2 text-3xl tabular-nums">{capacity==null?text.spaceUnknown:`${capacity.toLocaleString(locale,{maximumFractionDigits:2})} m²`}</p></div><div className="text-right"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">{text.peakUsage}</p><p className="mt-2 text-2xl">—</p></div></div><p className="mt-3 text-xs leading-5 text-muted-foreground">{text.spaceHelp}</p><div className="mt-4 flex gap-2"><div className="flex min-h-10 flex-1 items-center border border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)]"><input type="number" min="0" step="0.01" value={capacityDraft} onChange={e=>setCapacityDraft(e.target.value)} placeholder="m²" className="h-10 min-w-0 flex-1 bg-transparent px-3 text-sm outline-none"/><span className="pr-3 text-xs text-muted-foreground">m²</span></div><button type="submit" disabled={savingCapacity} className="min-h-10 bg-[var(--orchard-green)] px-4 text-sm font-medium text-[#10130f] disabled:opacity-50">{savingCapacity?"…":text.saveSpace}</button></div>{capacityMessage?<p className="mt-2 text-xs text-muted-foreground">{capacityMessage}</p>:null}</form>
   </section>

   <section className="mb-5 border-y border-[var(--bs-divider-subtle)]"><div className="flex flex-col gap-3 py-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-normal">{text.projection}</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-muted-foreground">{text.projectionHelp}</p></div><label className="flex min-h-10 w-full items-center gap-2 border border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)] px-3 sm:w-[280px]"><Search className="h-4 w-4 text-muted-foreground"/><input value={containerQuery} onChange={e=>setContainerQuery(e.target.value)} placeholder={text.search} className="h-8 w-full bg-transparent text-sm outline-none"/></label></div><div className="overflow-x-auto"><div className="min-w-[680px]"><div className="grid grid-cols-[1.5fr_130px_130px_130px] border-b border-[var(--bs-divider-subtle)] py-2 text-[10px] uppercase tracking-[.12em] text-muted-foreground"><span>{text.container}</span><span>{text.maxProjected}</span><span>{text.totalUsage}</span><span>{text.currentUse}</span></div>{containers.map(row=><div key={row.container} className="grid grid-cols-[1.5fr_130px_130px_130px] items-center border-b border-[var(--bs-divider-subtle)] py-2.5 text-sm last:border-b-0"><strong className="font-medium">{row.container}</strong><span className="tabular-nums">{row.max_projected}</span><span className="tabular-nums">{row.total_usage}</span><span className="tabular-nums">{row.current_in_use}</span></div>)}</div></div></section>

   <section className="mb-6"><div className="mb-2 flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.16em] text-muted-foreground">{text.schedule}</p><h2 className="mt-1 text-2xl font-normal">{rows.length} · {plan?.season??"—"}</h2></div></div><div className="overflow-x-auto border-y border-[var(--bs-divider-subtle)]"><div className="min-w-[1200px]"><div className="grid grid-cols-[220px_135px_135px_110px_160px_105px_105px_150px_1fr] border-b border-[var(--bs-divider-subtle)] py-2 text-[10px] uppercase tracking-[.11em] text-muted-foreground"><span>{text.crop}</span><span>{text.sow}</span><span>{text.transplant}</span><span>{text.plants}</span><span>{text.refContainer}</span><span>{text.germDays}</span><span>{text.nurseryDays}</span><span>{text.technique}</span><span>{text.evidence}</span></div>{rows.map(({s,cycle,ref})=>{const family=familyFor(cycle.crop_name);const chip=cropChipStyle(cycle.crop_name,family);const color=cropColor(cycle.crop_name,family);return <div key={s.id} className="grid grid-cols-[220px_135px_135px_110px_160px_105px_105px_150px_1fr] items-center border-b border-[var(--bs-divider-subtle)] py-2.5 text-sm last:border-b-0" style={{boxShadow:`inset 2px 0 0 ${color}`}}><div className="pl-3"><strong className="inline-flex items-center gap-2 font-medium"><i className="h-2 w-2 rounded-full" style={{backgroundColor:color}}/>{cycle.crop_name}</strong><p className="mt-0.5 text-[10px]" style={{color:chip.color}}>#{s.sequence_no}{family?` · ${family}`:""}</p></div><span>{dateLabel(s.planned_sow_date,locale)}</span><span>{dateLabel(s.planned_transplant_date,locale)}</span><span className="tabular-nums">{s.planned_plants?.toLocaleString(locale)??"—"}</span><span>{ref?.tray_cells??"—"}</span><span>{ref?`${ref.days_to_germinate} ${text.days}`:"—"}</span><span>{ref?`${ref.days_in_nursery} ${text.days}`:"—"}</span><span>{ref?.seeding_technique??"—"}</span><span className={s.germination_rate_pct?"":"text-[var(--bs-warm-amber)]"}>{s.germination_rate_pct?`${s.germination_rate_pct}%`:text.unresolved}</span></div>})}</div></div></section>

   <footer className="flex flex-col gap-4 border-t border-[var(--bs-divider-subtle)] pt-4 text-xs leading-5 text-muted-foreground lg:flex-row lg:items-center lg:justify-between"><span className="max-w-4xl">{text.source}</span><div className="flex flex-wrap gap-4"><Link href={methodsHref} className="inline-flex items-center gap-2 text-sm text-foreground">{text.methods}<ArrowRight className="h-4 w-4"/></Link><Link href={advancedHref} className="inline-flex items-center gap-2 text-sm text-foreground">{text.advanced}<ArrowRight className="h-4 w-4"/></Link></div></footer>
  </>}
 </main></AppLayout>
}

function Metric({icon:Icon,label,value}:{icon:typeof Sprout;label:string;value:string}){return <div className="border-r border-[var(--bs-divider-subtle)] px-3 py-3 last:border-r-0"><Icon className="h-3.5 w-3.5 text-muted-foreground"/><p className="mt-2 text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-2xl tabular-nums">{value}</p></div>}
