"use client"

import Link from "next/link"
import { FormEvent, useEffect, useMemo, useState } from "react"
import { ArrowRight, CircleAlert, FlaskConical, PackageOpen, Search, Sprout } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"
import nurseryReference from "@/data/orchard/dietrich-nursery-2026-27.json"
import containerPlan from "@/data/orchard/dietrich-nursery-container-plan-2026-27.json"

type Locale = "en" | "es" | "de"
type Plan = { id:string; season:string|null; status:string }
type Cycle = { id:string; game_plan_id:string; crop_name:string; cycle_type:string }
type Succession = { id:string; crop_cycle_id:string; sequence_no:number; planned_sow_date:string; planned_transplant_date:string|null; planned_plants:number|null; germination_rate_pct:number|null; status:string }
type Allocation = { crop_succession_id:string }
type NurseryRef = { cycle_name:string; tray_cells:string|number; days_to_germinate:string|number; days_in_nursery:string|number; seeding_technique:string|null }
type ContainerRow = { container:string; max_projected:number; total_usage:number; current_in_use:number }
type FarmSettings = { id:string; nursery_usable_surface_m2:number|string|null }
type View = "containers" | "plan"

const copy = {
 en:{title:"Nursery",description:"Capacity and container planning for physically reconciled transplant plantings.",capacityTitle:"Projected weekly Nursery space usage",space:"Nursery space",spaceHelp:"Usable tray surface in square metres. Include all usable table levels; do not use the building footprint.",spaceUnknown:"Not confirmed",saveSpace:"Save nursery space",spaceSaved:"Nursery space saved",spaceError:"Could not save nursery space",capacityPending:"Confirm usable nursery surface to unlock capacity monitoring. Occupied m² stays unresolved until container-footprint evidence exists.",capacityReady:"Usable nursery surface is confirmed. Occupied m² remains unresolved until canonical container-footprint evidence exists.",currentUsage:"Current nursery space usage",containers:"Containers",plan:"Propagation plan",search:"Search containers...",container:"Name",maxProjected:"Projected peak usage",totalUsage:"Total use",currentUse:"Currently in use",crop:"Crop",sow:"Nursery sow",transplant:"Field transplant",plants:"Planned plants",sourceContainer:"Source container",evidence:"Evidence",unresolved:"Expected germination unresolved",seedLots:"Seed lots",batches:"Observed batches",transplants:"Transplant plantings",manage:"Manage seeds & nursery",quickStock:"Add stock",methods:"Sowing methods",source:"Planning values come from the reconciled Dietrich Nursery/Crop Chart. Current nursery use is evidence-based and is never inferred from planned dates.",loadError:"Could not load the reconciled nursery plan.",empty:"No rows match this view."},
 es:{title:"Almácigo",description:"Capacidad y planificación de contenedores para trasplantes físicamente reconciliados.",capacityTitle:"Uso semanal proyectado del espacio de almácigo",space:"Espacio de almácigo",spaceHelp:"Superficie útil para bandejas en m². Incluye todos los niveles utilizables de las mesas; no uses la huella del edificio.",spaceUnknown:"Sin confirmar",saveSpace:"Guardar espacio",spaceSaved:"Espacio de almácigo guardado",spaceError:"No fue posible guardar el espacio",capacityPending:"Confirma la superficie útil para habilitar el monitoreo de capacidad. Los m² ocupados siguen sin resolver hasta contar con evidencia del área de los contenedores.",capacityReady:"La superficie útil está confirmada. Los m² ocupados siguen sin resolver hasta contar con evidencia canónica del área de los contenedores.",currentUsage:"Uso actual del espacio",containers:"Contenedores",plan:"Plan de propagación",search:"Buscar contenedores...",container:"Nombre",maxProjected:"Máximo proyectado",totalUsage:"Uso total",currentUse:"En uso ahora",crop:"Cultivo",sow:"Siembra almácigo",transplant:"Trasplante campo",plants:"Plantas planificadas",sourceContainer:"Contenedor fuente",evidence:"Evidencia",unresolved:"Germinación esperada sin resolver",seedLots:"Lotes de semilla",batches:"Batches observados",transplants:"Trasplantes planificados",manage:"Gestionar semillas y almácigo",quickStock:"Agregar stock",methods:"Métodos de siembra",source:"Los valores de planificación provienen del Nursery/Crop Chart reconciliado de Dietrich. El uso actual del almácigo se basa en evidencia y nunca se infiere por fechas planificadas.",loadError:"No fue posible cargar el plan reconciliado de almácigo.",empty:"No hay filas para esta vista."},
 de:{title:"Anzucht",description:"Kapazität und Behälterplanung für physisch abgeglichene Transplant-Pflanzungen.",capacityTitle:"Projizierte wöchentliche Nutzung der Anzuchtfläche",space:"Anzuchtfläche",spaceHelp:"Nutzbare Stellfläche in m². Alle nutzbaren Tisch-Ebenen einbeziehen; nicht die Gebäudegrundfläche verwenden.",spaceUnknown:"Nicht bestätigt",saveSpace:"Anzuchtfläche speichern",spaceSaved:"Anzuchtfläche gespeichert",spaceError:"Anzuchtfläche konnte nicht gespeichert werden",capacityPending:"Nutzbare Anzuchtfläche bestätigen, um Kapazitätsmonitoring zu aktivieren. Belegte m² bleiben ohne Nachweis der Behälterfläche ungeklärt.",capacityReady:"Nutzbare Anzuchtfläche ist bestätigt. Belegte m² bleiben bis zum kanonischen Nachweis der Behälterfläche ungeklärt.",currentUsage:"Aktuelle Nutzung der Anzuchtfläche",containers:"Behälter",plan:"Vermehrungsplan",search:"Behälter suchen...",container:"Name",maxProjected:"Projizierte Spitzennutzung",totalUsage:"Gesamtnutzung",currentUse:"Aktuell in Nutzung",crop:"Kultur",sow:"Aussaat Anzucht",transplant:"Feldpflanzung",plants:"Geplante Pflanzen",sourceContainer:"Quellbehälter",evidence:"Nachweis",unresolved:"Erwartete Keimung ungeklärt",seedLots:"Saatgutlose",batches:"Beobachtete Chargen",transplants:"Geplante Transplants",manage:"Saatgut & Anzucht verwalten",quickStock:"Bestand hinzufügen",methods:"Aussaatmethoden",source:"Planwerte stammen aus dem abgeglichenen Dietrich Nursery/Crop Chart. Aktuelle Nutzung bleibt evidenzbasiert und wird nie aus Plandaten abgeleitet.",loadError:"Der abgeglichene Anzuchtplan konnte nicht geladen werden.",empty:"Keine Zeilen in dieser Ansicht."}
} as const

const localeMap:Record<Locale,string>={en:"en-US",es:"es-CL",de:"de-DE"}
const dateLabel=(value:string|null,locale:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString(locale,{day:"2-digit",month:"short",year:"numeric"}):"—"

export default function NurseryOverviewPage(){
 const supabase=useMemo(()=>createBrowserClient(),[])
 const {language}=useLanguage();const lang:Locale=language;const text=copy[lang];const locale=localeMap[lang]
 const [plans,setPlans]=useState<Plan[]>([]),[cycles,setCycles]=useState<Cycle[]>([]),[successions,setSuccessions]=useState<Succession[]>([]),[allocations,setAllocations]=useState<Allocation[]>([])
 const [seedLots,setSeedLots]=useState(0),[batches,setBatches]=useState(0),[farmSettings,setFarmSettings]=useState<FarmSettings|null>(null)
 const [capacityDraft,setCapacityDraft]=useState(""),[capacityMessage,setCapacityMessage]=useState<string|null>(null),[savingCapacity,setSavingCapacity]=useState(false),[query,setQuery]=useState(""),[view,setView]=useState<View>("containers")
 const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)

 useEffect(()=>{let live=true;setLoading(true);setError(null);void Promise.all([
  supabase.from("orchard_game_plans").select("id,season,status").order("start_date",{ascending:false}),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name,cycle_type"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id,sequence_no,planned_sow_date,planned_transplant_date,planned_plants,germination_rate_pct,status").neq("status","cancelled").order("planned_sow_date"),
  supabase.from("orchard_bed_allocations").select("crop_succession_id"),
  supabase.from("orchard_seed_lots").select("id",{count:"exact",head:true}),
  supabase.from("orchard_nursery_batches").select("id",{count:"exact",head:true}),
  supabase.from("orchard_farm_settings").select("id,nursery_usable_surface_m2").eq("farm_key","black_swan_orchard").single(),
 ]).then(([p,c,s,a,l,b,fs])=>{if(!live)return;const first=p.error??c.error??s.error??a.error??l.error??b.error??fs.error;if(first){setError(`${text.loadError} ${first.message}`);setLoading(false);return}setPlans((p.data??[]) as Plan[]);setCycles((c.data??[]) as Cycle[]);setSuccessions((s.data??[]) as Succession[]);setAllocations((a.data??[]) as Allocation[]);setSeedLots(l.count??0);setBatches(b.count??0);const settings=fs.data as FarmSettings;setFarmSettings(settings);setCapacityDraft(settings.nursery_usable_surface_m2==null?"":String(settings.nursery_usable_surface_m2));setLoading(false)});return()=>{live=false}},[supabase,text.loadError])

 const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null
 const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const cycleById=new Map(cycles.filter(c=>c.game_plan_id===plan?.id).map(c=>[c.id,c]));const allocatedIds=new Set(allocations.map(a=>a.crop_succession_id));const transplantSuccessions=successions.filter(s=>allocatedIds.has(s.id)&&cycleById.get(s.crop_cycle_id)?.cycle_type==="transplant")
 const refByCycle=new Map((nurseryReference as NurseryRef[]).map(r=>[r.cycle_name,r]));const rows=transplantSuccessions.map(s=>({s,cycle:cycleById.get(s.crop_cycle_id)!,ref:refByCycle.get(cycleById.get(s.crop_cycle_id)!.crop_name)??null})).sort((a,b)=>a.s.planned_sow_date.localeCompare(b.s.planned_sow_date))
 const capacity=farmSettings?.nursery_usable_surface_m2==null?null:Number(farmSettings.nursery_usable_surface_m2)
 const containers=(containerPlan.containers as ContainerRow[]).filter(row=>!query.trim()||row.container.toLowerCase().includes(query.trim().toLowerCase()))
 const planRows=rows.filter(row=>!query.trim()||row.cycle.crop_name.toLowerCase().includes(query.trim().toLowerCase()))
 const advancedHref=`/${language}/orchard/nursery/advanced${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`
 const stockHref=`/${language}/orchard/nursery/quick-stock${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`
 const methodsHref=`/${language}/orchard/game-plan/propagation${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`

 async function saveCapacity(event:FormEvent){event.preventDefault();if(!farmSettings)return;const parsed=capacityDraft.trim()===""?null:Number(capacityDraft);if(parsed!=null&&(!Number.isFinite(parsed)||parsed<0))return;setSavingCapacity(true);setCapacityMessage(null);const result=await supabase.from("orchard_farm_settings").update({nursery_usable_surface_m2:parsed}).eq("id",farmSettings.id).select("id,nursery_usable_surface_m2").single();if(result.error)setCapacityMessage(text.spaceError);else{const settings=result.data as FarmSettings;setFarmSettings(settings);setCapacityDraft(settings.nursery_usable_surface_m2==null?"":String(settings.nursery_usable_surface_m2));setCapacityMessage(text.spaceSaved)}setSavingCapacity(false)}

 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1560px] px-4 pb-16 pt-6 sm:px-6 lg:px-8">
  <header className="mb-6 flex flex-col gap-4 border-b border-[var(--bs-divider-subtle)] pb-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-3"><h1 className="text-3xl font-normal sm:text-4xl">{text.title}</h1>{plan?.season?<Badge variant="secondary">{plan.season}</Badge>:null}</div><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{text.description}</p></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span><strong className="text-foreground">{rows.length}</strong> {text.transplants}</span><span><strong className="text-foreground">{seedLots}</strong> {text.seedLots}</span><span><strong className="text-foreground">{batches}</strong> {text.batches}</span></div></header>
  {loading?<div className="py-12 text-sm text-muted-foreground">…</div>:error?<div className="border-y border-red-400/30 py-4 text-sm text-red-300">{error}</div>:<>
   <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_260px]">
    <div className="min-h-[280px] border border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)] p-5"><p className="text-xs font-medium">{text.capacityTitle}</p><div className="flex min-h-[190px] items-center justify-center"><div className="max-w-xl text-center"><div className="mx-auto flex h-16 w-16 items-end justify-center gap-1.5 border-b border-[var(--bs-divider-subtle)] pb-2"><span className="h-5 w-2 bg-[var(--orchard-green)]/35"/><span className="h-9 w-2 bg-[var(--orchard-green)]/50"/><span className="h-7 w-2 bg-[var(--orchard-green)]/40"/><span className="h-12 w-2 bg-[var(--orchard-green)]/65"/><span className="h-8 w-2 bg-[var(--orchard-green)]/45"/></div><p className="mt-5 text-sm leading-6 text-muted-foreground">{capacity==null?text.capacityPending:text.capacityReady}</p></div></div></div>
    <aside className="border border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)] p-5"><p className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">{text.space}</p><p className="mt-2 text-3xl tabular-nums">{capacity==null?text.spaceUnknown:`${capacity.toLocaleString(locale,{maximumFractionDigits:2})} m²`}</p><div className="my-5 border-t border-[var(--bs-divider-subtle)]"/><p className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">{text.currentUsage}</p><div className="mt-3 flex h-20 w-20 items-center justify-center rounded-full border-4 border-[var(--bs-divider-subtle)] text-lg text-muted-foreground">—</div><form onSubmit={saveCapacity} className="mt-5"><p className="text-xs leading-5 text-muted-foreground">{text.spaceHelp}</p><div className="mt-3 flex items-center border border-[var(--bs-divider-subtle)]"><input type="number" min="0" step="0.01" value={capacityDraft} onChange={e=>setCapacityDraft(e.target.value)} placeholder="m²" className="h-10 min-w-0 flex-1 bg-transparent px-3 text-sm outline-none"/><span className="pr-3 text-xs text-muted-foreground">m²</span></div><button type="submit" disabled={savingCapacity} className="mt-2 h-10 w-full bg-[var(--orchard-green)] px-4 text-sm font-medium text-[#10130f] disabled:opacity-50">{savingCapacity?"…":text.saveSpace}</button>{capacityMessage?<p className="mt-2 text-xs text-muted-foreground">{capacityMessage}</p>:null}</form></aside>
   </section>

   <section className="mt-6 border border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)]">
    <div className="flex flex-col gap-3 border-b border-[var(--bs-divider-subtle)] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-5"><button type="button" onClick={()=>{setView("containers");setQuery("")}} className={`border-b-2 pb-2 text-sm ${view==="containers"?"border-[var(--orchard-green)] text-foreground":"border-transparent text-muted-foreground"}`}>{text.containers}</button><button type="button" onClick={()=>{setView("plan");setQuery("")}} className={`border-b-2 pb-2 text-sm ${view==="plan"?"border-[var(--orchard-green)] text-foreground":"border-transparent text-muted-foreground"}`}>{text.plan}</button></div><label className="flex h-10 w-full items-center gap-2 border border-[var(--bs-divider-subtle)] px-3 sm:w-[280px]"><Search className="h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={view==="containers"?text.search:text.crop} className="w-full bg-transparent text-sm outline-none"/></label></div>
    {view==="containers"?<div className="overflow-x-auto"><div className="min-w-[720px]"><div className="grid grid-cols-[1.5fr_160px_150px_150px] border-b border-[var(--bs-divider-subtle)] px-4 py-2.5 text-[10px] uppercase tracking-[.12em] text-muted-foreground"><span>{text.container}</span><span>{text.maxProjected}</span><span>{text.totalUsage}</span><span>{text.currentUse}</span></div>{containers.length?containers.map(row=><div key={row.container} className="grid grid-cols-[1.5fr_160px_150px_150px] items-center border-b border-[var(--bs-divider-subtle)] px-4 py-3 text-sm last:border-b-0"><strong className="font-medium">{row.container}</strong><span className="tabular-nums">{row.max_projected}</span><span className="tabular-nums">{row.total_usage}</span><span className="tabular-nums">{row.current_in_use}</span></div>):<p className="p-6 text-sm text-muted-foreground">{text.empty}</p>}</div></div>:<div className="overflow-x-auto"><div className="min-w-[900px]"><div className="grid grid-cols-[1.5fr_145px_145px_120px_160px_1fr] border-b border-[var(--bs-divider-subtle)] px-4 py-2.5 text-[10px] uppercase tracking-[.12em] text-muted-foreground"><span>{text.crop}</span><span>{text.sow}</span><span>{text.transplant}</span><span>{text.plants}</span><span>{text.sourceContainer}</span><span>{text.evidence}</span></div>{planRows.length?planRows.map(({s,cycle,ref})=><div key={s.id} className="grid grid-cols-[1.5fr_145px_145px_120px_160px_1fr] items-center border-b border-[var(--bs-divider-subtle)] px-4 py-3 text-sm last:border-b-0"><div><strong className="font-medium">{cycle.crop_name}</strong><p className="mt-0.5 text-[10px] text-muted-foreground">#{s.sequence_no}</p></div><span>{dateLabel(s.planned_sow_date,locale)}</span><span>{dateLabel(s.planned_transplant_date,locale)}</span><span className="tabular-nums">{s.planned_plants?.toLocaleString(locale)??"—"}</span><span>{ref?.tray_cells??"—"}</span><span className={s.germination_rate_pct?"":"text-[var(--bs-warm-amber)]"}>{s.germination_rate_pct?`${s.germination_rate_pct}%`:text.unresolved}</span></div>):<p className="p-6 text-sm text-muted-foreground">{text.empty}</p>}</div></div>}
   </section>

   <footer className="mt-5 flex flex-col gap-4 border-t border-[var(--bs-divider-subtle)] pt-4 text-xs leading-5 text-muted-foreground lg:flex-row lg:items-center lg:justify-between"><span className="max-w-4xl">{text.source}</span><div className="flex flex-wrap gap-4"><Link href={stockHref} className="inline-flex items-center gap-2 text-sm text-foreground hover:text-[var(--orchard-green)]"><PackageOpen className="h-4 w-4"/>{text.quickStock}<ArrowRight className="h-3.5 w-3.5"/></Link><Link href={advancedHref} className="inline-flex items-center gap-2 text-sm text-foreground hover:text-[var(--orchard-green)]"><Sprout className="h-4 w-4"/>{text.manage}<ArrowRight className="h-3.5 w-3.5"/></Link><Link href={methodsHref} className="inline-flex items-center gap-2 text-sm text-foreground hover:text-[var(--orchard-green)]"><FlaskConical className="h-4 w-4"/>{text.methods}<ArrowRight className="h-3.5 w-3.5"/></Link></div></footer>
  </>}
 </main></AppLayout>
}
