import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

test("Heirloom-style Orchard workload exposes list, completed week board and workload graph on canonical tasks", async () => {
  const component = await readFile("components/orchard/orchard-workload-parity.tsx", "utf8")
  const weekBoard = await readFile("components/orchard/orchard-week-board.tsx", "utf8")
  const list = await readFile("app/orchard/work/list/page.tsx", "utf8")
  const week = await readFile("app/orchard/work/week-board/page.tsx", "utf8")
  const graph = await readFile("app/orchard/work/workload-graph/page.tsx", "utf8")

  assert.match(component, /from\("tasks"\)/)
  assert.match(component, /from\("task_assignments"\)/)
  assert.match(component, /from\("employees"\)/)
  assert.match(component, /from\("orchard_plots"\)/)
  assert.match(component, /from\("locations"\)/)
  assert.match(component, /\.in\("operational_area",\["orchard","huerto_vinedo"\]\)/)
  assert.match(component, /rpc\("create_operational_task_atomic"/)
  assert.match(component, /p_operational_area:"orchard"/)
  assert.match(component, /p_employee_ids:\[form\.employeeId\]/)
  assert.match(component, /p_location_id:location\.id/)
  assert.match(component, /form\.employeeId===\"none\"/)
  assert.match(component, /form\.locationId===\"none\"/)
  assert.doesNotMatch(component, /from\("tasks"\)\.insert/)
  assert.match(component, /Recurring tasks are not yet a canonical Core field/)
  assert.match(component, /mode===\"list\"/)
  assert.match(component, /mode===\"workload-graph\"/)
  assert.match(list, /mode="list"/)
  assert.match(graph, /mode="workload-graph"/)

  assert.match(week, /OrchardWeekBoard/)
  assert.match(weekBoard, /from\("tasks"\)/)
  assert.match(weekBoard, /from\("task_assignments"\)/)
  assert.match(weekBoard, /Previous week|Semana anterior/)
  assert.match(weekBoard, /Display options|Opciones de visualización/)
  assert.match(weekBoard, /Export|Exportar/)
  assert.match(weekBoard, /type="date"/)
  assert.match(weekBoard, /new Blob/)
  assert.match(weekBoard, /weatherGap/)
  assert.doesNotMatch(weekBoard, /Math\.random/)
})
