import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

test("Heirloom reconciliation remains explicit, bed-meter based and capacity safe", async () => {
  const migration = await readFile("supabase/migrations/20260901184500_orchard_heirloom_reference_reconciliation.sql", "utf8")
  const placement = await readFile("supabase/migrations/20260901190000_orchard_place_succession_bed_meters.sql", "utf8")
  const optimizedLayout = await readFile("supabase/migrations/20260901194500_orchard_capacity_safe_reference_layout.sql", "utf8")
  const expansion = await readFile("supabase/migrations/20260901195500_orchard_add_farm_area_1_sectors.sql", "utf8")
  const page = await readFile("app/orchard/crop-map/auto-place/page.tsx", "utf8")
  const workPage = await readFile("app/orchard/work/page.tsx", "utf8")
  const gettingStarted = await readFile("app/orchard/getting-started/page.tsx", "utf8")
  const parity = await readFile("lib/orchard/heirloom-parity.ts", "utf8")

  // Preserve the authenticated Heirloom observation as historical evidence.
  assert.match(migration, /BS Orchard — Crop Plan 2026\/27/)
  assert.match(migration, /v_matches <> 32/)
  assert.match(migration, /v_total <> 744/)
  assert.match(migration, /Orchard BlackSwan Campo/)
  assert.match(migration, /generate_series\(1,18\)/)
  assert.match(migration, /Arugula generation 1 -> bed 17 -> 9 bed m/)
  assert.doesNotMatch(migration, /3bdcad00-b8e5-4f73-bb8b-fdea96da9262/)

  assert.match(placement, /orchard_place_succession_bed_meters/)
  assert.match(placement, /for update/)
  assert.match(placement, /allocated_length_m/)
  assert.match(placement, /Insufficient contiguous bed-meter capacity/)
  assert.match(placement, /Planting already has a bed allocation/)

  // Historical intermediate migrations stay immutable for migration history.
  assert.match(optimizedLayout, /maximum-count/)
  assert.match(optimizedLayout, /Storage Potatoes/)
  assert.match(optimizedLayout, /New Potatoes/)
  assert.match(optimizedLayout, /v_assigned_succ <> 30/)
  assert.match(optimizedLayout, /v_assigned_bed_m <> 504/)
  assert.match(optimizedLayout, /v_peak_global > 540/)
  assert.match(optimizedLayout, /b\.name = '18'/)
  assert.doesNotMatch(optimizedLayout, /min\(id\)/)

  assert.match(expansion, /Farm Area 1 reference polygon/)
  assert.match(expansion, /Orchard BlackSwan Campo — Sector 2/)
  assert.match(expansion, /Orchard BlackSwan Campo — Sector 3/)
  assert.match(expansion, /v_assigned <> 32/)
  assert.match(expansion, /v_pending <> 0/)
  assert.match(expansion, /v_allocated_m <> 744/)

  // Current application logic must use the confirmed 8-block physical model.
  assert.match(page, /planned_bed_m/)
  assert.match(page, /allocated_length_m/)
  assert.match(page, /orchard_place_succession_bed_meters/)
  assert.match(page, /\$\{assigned\}\/\$\{scoped\.length\}/)
  assert.match(page, /peakDemand/)
  assert.match(page, /areaCapacity/)
  assert.match(page, /FARM_AREA_BLOCK_NAMES/)
  assert.match(page, /Current 01/)
  assert.match(page, /Current 05/)
  assert.match(page, /Expansion 01/)
  assert.match(page, /Expansion 03/)
  assert.match(page, /80 active beds/)
  assert.match(page, /800 bed-m/)
  assert.doesNotMatch(page, /three logical cultivation sectors/)

  // Workload must not drift back to the unreconciled draft graph or bypass the task guard.
  assert.match(workPage, /allocatedSuccessionIds/)
  assert.match(workPage, /reconciledSuccessionIds/)
  assert.match(workPage, /new Set\(\[\.\.\.graph\.successionIds\]\.filter/)
  assert.match(workPage, /reconciledSuccessions/)
  assert.match(workPage, /orchard_succession_sow/)
  assert.match(workPage, /orchard_succession_transplant/)
  assert.match(workPage, /orchard_succession_harvest/)
  assert.match(workPage, /rpc\("create_operational_task_atomic"/)
  assert.match(workPage, /p_operational_area:\"orchard\"/)
  assert.match(workPage, /p_location_id:location\.locationId/)
  assert.match(workPage, /p_employee_ids:\[form\.employee_id\]/)
  assert.match(workPage, /p_employee_ids:\[bulkEmployeeId\]/)
  assert.match(workPage, /bulkEmployeeId === "none"/)
  assert.doesNotMatch(workPage, /from\("tasks"\)\.insert/)

  // Getting Started must count only accountable Orchard tasks linked to reconciled plantings.
  assert.match(gettingStarted, /\.in\("operational_area",\["orchard","huerto_vinedo"\]\)/)
  assert.match(gettingStarted, /const scopedTasks=/)
  assert.match(gettingStarted, /reconciledIds\.has\(task\.source_id\)/)
  assert.match(gettingStarted, /scopedTasks\.length>0/)
  assert.doesNotMatch(gettingStarted, /\.eq\("operational_area","huerto_vinedo"\)/)

  // Historical Heirloom reference and current Core truth are deliberately separate.
  assert.match(parity, /fieldBlockBeds: 18/)
  assert.match(parity, /fieldBlockBedLengthM: 30/)
  assert.match(parity, /HEIRLOOM_REFERENCE_PLANTINGS/)
  assert.match(parity, /currentBlockCount: 5/)
  assert.match(parity, /expansionBlockCount: 3/)
  assert.match(parity, /blockCount: 8/)
  assert.match(parity, /bedsPerBlock: 10/)
  assert.match(parity, /bedLengthM: 10/)
  assert.match(parity, /totalBeds: 80/)
  assert.match(parity, /totalCapacityBedMeters: 800/)
  assert.match(parity, /totalCultivableAreaSqm: 608/)
  assert.match(parity, /allocatedPlantings: 32/)
  assert.match(parity, /allocatedBedMeters: 744/)
})
