"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { ArrowLeft, PackageSearch, RefreshCw } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { createBrowserClient } from "@/lib/supabase/client"

type Stock={id:string;item_code:string;name:string;category:string|null;unit:string;quantity_on_hand:number;minimum_stock:number;unit_cost:number|null;is_active:boolean;warehouse_location_id:string;cost_center_id:string|null;warehouse_locations?:{name:string;warehouses?:{name:string}|null}|null;cost_centers?:{name:string;code:string|null}|null}
type Movement={id:string;stock_item_id:string;movement_type:string;quantity:number;unit_cost:number|null;balance_after:number;notes:string|null;moved_at:string}
const movementLabel:Record<string,string>={receipt:"Recepción",issue:"Consumo",adjustment:"Ajuste",transfer_in:"Traslado entrada",transfer_out:"Traslado salida",return:"Devolución"}

function firstRelation<T>(value:T|T[]|null|undefined):T|null{return Array.isArray(value)?value[0]??null:value??null}

export default function InventoryStockPage(){const supabase=useMemo(()=>createBrowserClient(),[]);const [stock,setStock]=useState<Stock[]>([]);const [movements,setMovements]=useState<Movement[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);const [a,b]=await Promise.all([supabase.from("inventory_stock_items").select("id,item_code,name,category,unit,quantity_on_hand,minimum_stock,unit_cost,is_active,warehouse_location_id,cost_center_id,warehouse_locations(name,warehouses(name)),cost_centers(name,code)").order("name"),supabase.from("inventory_stock_movements").select("id,stock_item_id,movement_type,quantity,unit_cost,balance_after,notes,moved_at").order("moved_at",{ascending:false}).limit(50)]);const err=a.error||b.error;if(err){setError(err.message);setStock([]);setMovements([])}else{setStock((a.data??[]).map(row=>{const location=firstRelation(row.warehouse_locations);return {...row,warehouse_locations:location?{...location,warehouses:firstRelation(location.warehouses)}:null,cost_centers:firstRelation(row.cost_centers)}}));setMovements((b.data??[]) as Movement[])}setLoading(false)},[supabase]);useEffect(()=>{void load()},[load])
 const filtered=stock.filter(x=>`${x.item_code} ${x.name} ${x.category??""}`.toLowerCase().includes(query.toLowerCase()));const low=stock.filter(x=>x.is_active&&Number(x.quantity_on_hand)<=Number(x.minimum_stock));const stockValue=stock.reduce((s,x)=>s+Number(x.quantity_on_hand)*Number(x.unit_cost??0),0);const names=Object.fromEntries(stock.map(x=>[x.id,x.name]));
 return <AppLayout><PageHeader title="Stock consumible" description="Existencias, mínimos y kardex originados desde compras y movimientos internos." actions={<div className="flex gap-2"><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Actualizar</Button><Button variant="outline" asChild><Link href="/inventory"><ArrowLeft className="mr-2 h-4 w-4"/>Inventario</Link></Button></div>}/><div className="space-y-6 p-4 sm:p-8">
 <div className="grid gap-4 sm:grid-cols-3"><Metric title="Ítems activos" value={stock.filter(x=>x.is_active).length}/><Metric title="Bajo mínimo" value={low.length} alert={low.length>0}/><Metric title="Valor registrado" value={new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(stockValue)} detail="Cantidad por costo unitario registrado"/></div>
 {error&&<Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
 <Card><CardHeader><CardTitle>Existencias</CardTitle><CardDescription>Los mínimos son parámetros operativos y pueden ajustarse en una etapa posterior de administración.</CardDescription></CardHeader><CardContent><Input className="mb-4" placeholder="Buscar por código, nombre o categoría" value={query} onChange={e=>setQuery(e.target.value)}/><div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Código</TableHead><TableHead>Ítem</TableHead><TableHead>Ubicación</TableHead><TableHead>Centro de costo</TableHead><TableHead className="text-right">Existencia</TableHead><TableHead className="text-right">Mínimo</TableHead><TableHead className="text-right">Costo unitario</TableHead><TableHead>Estado</TableHead></TableRow></TableHeader><TableBody>{loading?<TableRow><TableCell colSpan={8} className="py-10 text-center text-muted-foreground">Cargando stock…</TableCell></TableRow>:filtered.length===0?<TableRow><TableCell colSpan={8} className="py-10 text-center"><PackageSearch className="mx-auto mb-3 h-7 w-7 text-muted-foreground"/><p className="font-medium">No hay existencias consumibles registradas.</p></TableCell></TableRow>:filtered.map(x=>{const alert=Number(x.quantity_on_hand)<=Number(x.minimum_stock);return <TableRow key={x.id}><TableCell className="font-mono text-xs">{x.item_code}</TableCell><TableCell><p className="font-medium">{x.name}</p><p className="text-xs text-muted-foreground">{x.category??"Sin categoría"} · {x.unit}</p></TableCell><TableCell>{x.warehouse_locations?.warehouses?.name??"Bodega"} · {x.warehouse_locations?.name??"Sin ubicación"}</TableCell><TableCell>{x.cost_centers?`${x.cost_centers.name}${x.cost_centers.code?` (${x.cost_centers.code})`:""}`:"No asignado"}</TableCell><TableCell className="text-right font-medium">{Number(x.quantity_on_hand).toLocaleString("es-CL")}</TableCell><TableCell className="text-right">{Number(x.minimum_stock).toLocaleString("es-CL")}</TableCell><TableCell className="text-right">{x.unit_cost==null?"Sin costo":new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(x.unit_cost)}</TableCell><TableCell><Badge variant="outline" className={alert?"border-amber-300":""}>{alert?"Reponer":"Disponible"}</Badge></TableCell></TableRow>})}</TableBody></Table></div></CardContent></Card>
 <Card><CardHeader><CardTitle>Kardex reciente</CardTitle><CardDescription>Últimos 50 movimientos registrados.</CardDescription></CardHeader><CardContent className="space-y-2">{movements.length===0?<p className="py-6 text-center text-sm text-muted-foreground">Todavía no hay movimientos de stock.</p>:movements.map(x=><div key={x.id} className="flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{names[x.stock_item_id]??"Ítem de stock"} · {movementLabel[x.movement_type]??x.movement_type}</p><p className="text-xs text-muted-foreground">{new Date(x.moved_at).toLocaleString("es-CL")}{x.notes?` · ${x.notes}`:""}</p></div><div className="text-right"><p className="text-sm font-medium">{Number(x.quantity).toLocaleString("es-CL")}</p><p className="text-xs text-muted-foreground">Saldo {Number(x.balance_after).toLocaleString("es-CL")}</p></div></div>)}</CardContent></Card>
 </div></AppLayout>}
function Metric({title,value,alert=false,detail}:{title:string;value:number|string;alert?:boolean;detail?:string}){return <Card className={alert?"border-amber-300":undefined}><CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground">{title}</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{typeof value==="number"?value.toLocaleString("es-CL"):value}</div>{detail&&<p className="mt-1 text-xs text-muted-foreground">{detail}</p>}</CardContent></Card>}
