"use client"

import type { FormEvent, ReactNode } from "react"
import { useCallback, useEffect, useMemo, useState } from "react"
import { Plus, RefreshCw, Sprout, Trash2 } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type SeedLot = { id: string; crop_name: string; variety: string | null; lot_code: string | null; supplier: string | null; quantity_seeds: number; germination_rate_pct: number | null; received_date: string | null; expiry_date: string | null; storage_location: string | null; notes: string | null }
type Batch = { id: string; crop_succession_id: string; seed_lot_id: string | null; sow_date: string; cells_sown: number | null; seeds_sown: number; emerged_count: number | null; ready_count: number | null; transplanted_count: number | null; expected_ready_date: string | null; actual_ready_date: string | null; transplant_date: string | null; status: "planned" | "sown" | "germinating" | "growing" | "ready" | "transplanted" | "completed" | "failed" | "cancelled"; location: string | null; notes: string | null }
type Succession = { id: string; crop_cycle_id: string; sequence_no: number; planned_sow_date: string; planned_transplant_date: string | null; planned_plants: number | null }
type Cycle = { id: string; crop_name: string; variety: string | null }

const statuses: Batch["status"][] = ["planned", "sown", "germinating", "growing", "ready", "transplanted", "completed", "failed", "cancelled"]
const copy = {
  en: { title: "Seeds & Nursery", description: "Manage seed lots and carry planned successions through sowing, emergence, nursery readiness and transplanting.", refresh: "Refresh", seedLots: "Seed lots", newSeedLot: "New seed lot", crop: "Crop", variety: "Variety", lot: "Lot code", supplier: "Supplier", quantity: "Seeds on hand", germination: "Germination (%)", received: "Received", expiry: "Expiry", storage: "Storage", notes: "Notes", saveLot: "Save seed lot", nursery: "Nursery batches", newBatch: "Start nursery batch", succession: "Succession", seedLot: "Seed lot", sowDate: "Sow date", cells: "Cells sown", seedsSown: "Seeds sown", expectedReady: "Expected ready", location: "Nursery location", startBatch: "Start batch", emerged: "Emerged", ready: "Ready", transplanted: "Transplanted", actualReady: "Actual ready", transplantDate: "Transplant date", saveCounts: "Save progress", emptyLots: "No seed lots recorded yet.", emptyBatches: "No nursery batches yet.", loadError: "Could not load nursery data", saveError: "Could not save changes", deleteLot: "Delete this seed lot?", deleteBatch: "Delete this nursery batch?", available: "available", planned: "planned" },
  es: { title: "Semillas y Almácigos", description: "Gestiona lotes de semillas y lleva las sucesiones planificadas por siembra, emergencia, preparación y trasplante.", refresh: "Actualizar", seedLots: "Lotes de semillas", newSeedLot: "Nuevo lote", crop: "Cultivo", variety: "Variedad", lot: "Código de lote", supplier: "Proveedor", quantity: "Semillas disponibles", germination: "Germinación (%)", received: "Recepción", expiry: "Vencimiento", storage: "Almacenamiento", notes: "Notas", saveLot: "Guardar lote", nursery: "Lotes de almácigo", newBatch: "Iniciar almácigo", succession: "Sucesión", seedLot: "Lote de semillas", sowDate: "Fecha de siembra", cells: "Celdas sembradas", seedsSown: "Semillas sembradas", expectedReady: "Fecha estimada lista", location: "Ubicación", startBatch: "Iniciar lote", emerged: "Emergidas", ready: "Listas", transplanted: "Trasplantadas", actualReady: "Fecha real lista", transplantDate: "Fecha de trasplante", saveCounts: "Guardar avance", emptyLots: "Aún no hay lotes de semillas.", emptyBatches: "Aún no hay lotes de almácigo.", loadError: "No fue posible cargar almácigos", saveError: "No fue posible guardar cambios", deleteLot: "¿Eliminar este lote de semillas?", deleteBatch: "¿Eliminar este lote de almácigo?", available: "disponibles", planned: "planificadas" },
} as const
const titleize = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase())
const dateLabel = (value: string | null, locale: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString(locale) : "—"

export default function OrchardNurseryPage() {
  const supabase = useMemo(() => createBrowserClient(), [])
  const { language } = useLanguage(); const lang = language === "es" ? "es" : "en"; const text = copy[lang]; const locale = lang === "es" ? "es-CL" : "en-US"
  const [seedLots, setSeedLots] = useState<SeedLot[]>([]); const [batches, setBatches] = useState<Batch[]>([]); const [successions, setSuccessions] = useState<Succession[]>([]); const [cycles, setCycles] = useState<Cycle[]>([])
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const [lotForm, setLotForm] = useState({ crop_name: "", variety: "", lot_code: "", supplier: "", quantity_seeds: "", germination_rate_pct: "", received_date: "", expiry_date: "", storage_location: "", notes: "" })
  const [batchForm, setBatchForm] = useState({ crop_succession_id: "", seed_lot_id: "none", sow_date: "", cells_sown: "", seeds_sown: "", expected_ready_date: "", location: "", notes: "" })
  const [progress, setProgress] = useState<Record<string, { emerged_count: string; ready_count: string; transplanted_count: string; actual_ready_date: string; transplant_date: string }>>({})

  const loadData = useCallback(async () => { setLoading(true); setError(null); const [l, b, s, c] = await Promise.all([
    supabase.from("orchard_seed_lots").select("id, crop_name, variety, lot_code, supplier, quantity_seeds, germination_rate_pct, received_date, expiry_date, storage_location, notes").order("crop_name"),
    supabase.from("orchard_nursery_batches").select("id, crop_succession_id, seed_lot_id, sow_date, cells_sown, seeds_sown, emerged_count, ready_count, transplanted_count, expected_ready_date, actual_ready_date, transplant_date, status, location, notes").order("sow_date", { ascending: false }),
    supabase.from("orchard_crop_successions").select("id, crop_cycle_id, sequence_no, planned_sow_date, planned_transplant_date, planned_plants").order("planned_sow_date"),
    supabase.from("orchard_crop_cycles").select("id, crop_name, variety").order("crop_name"),
  ]); const e = l.error ?? b.error ?? s.error ?? c.error; if (e) setError(`${text.loadError}: ${e.message}`); else { setSeedLots((l.data ?? []) as SeedLot[]); const nextBatches = (b.data ?? []) as Batch[]; setBatches(nextBatches); setSuccessions((s.data ?? []) as Succession[]); setCycles((c.data ?? []) as Cycle[]); setProgress(Object.fromEntries(nextBatches.map((item) => [item.id, { emerged_count: item.emerged_count?.toString() ?? "", ready_count: item.ready_count?.toString() ?? "", transplanted_count: item.transplanted_count?.toString() ?? "", actual_ready_date: item.actual_ready_date ?? "", transplant_date: item.transplant_date ?? "" }]))) } setLoading(false) }, [supabase, text.loadError])
  useEffect(() => { void loadData() }, [loadData])
  const cycleById = useMemo(() => new Map(cycles.map((cycle) => [cycle.id, cycle])), [cycles]); const successionById = useMemo(() => new Map(successions.map((item) => [item.id, item])), [successions])
  const usedSuccessionIds = new Set(batches.map((batch) => batch.crop_succession_id)); const availableSuccessions = successions.filter((item) => !usedSuccessionIds.has(item.id))
  const successionLabel = (item: Succession) => { const cycle = cycleById.get(item.crop_cycle_id); return `${cycle?.crop_name ?? "Crop"}${cycle?.variety ? ` · ${cycle.variety}` : ""} #${item.sequence_no}` }

  async function createLot(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!lotForm.crop_name) return; setSaving(true); const { error: e } = await supabase.from("orchard_seed_lots").insert({ crop_name: lotForm.crop_name.trim(), variety: lotForm.variety.trim() || null, lot_code: lotForm.lot_code.trim() || null, supplier: lotForm.supplier.trim() || null, quantity_seeds: Number(lotForm.quantity_seeds || 0), germination_rate_pct: lotForm.germination_rate_pct ? Number(lotForm.germination_rate_pct) : null, received_date: lotForm.received_date || null, expiry_date: lotForm.expiry_date || null, storage_location: lotForm.storage_location.trim() || null, notes: lotForm.notes.trim() || null }); if (e) setError(`${text.saveError}: ${e.message}`); else { setLotForm({ crop_name: "", variety: "", lot_code: "", supplier: "", quantity_seeds: "", germination_rate_pct: "", received_date: "", expiry_date: "", storage_location: "", notes: "" }); await loadData() } setSaving(false) }
  async function createBatch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!batchForm.crop_succession_id || !batchForm.sow_date) return; setSaving(true); const { error: e } = await supabase.from("orchard_nursery_batches").insert({ crop_succession_id: batchForm.crop_succession_id, seed_lot_id: batchForm.seed_lot_id === "none" ? null : batchForm.seed_lot_id, sow_date: batchForm.sow_date, cells_sown: batchForm.cells_sown ? Number(batchForm.cells_sown) : null, seeds_sown: Number(batchForm.seeds_sown || 0), expected_ready_date: batchForm.expected_ready_date || null, location: batchForm.location.trim() || null, notes: batchForm.notes.trim() || null }); if (e) setError(`${text.saveError}: ${e.message}`); else { setBatchForm({ crop_succession_id: "", seed_lot_id: "none", sow_date: "", cells_sown: "", seeds_sown: "", expected_ready_date: "", location: "", notes: "" }); await loadData() } setSaving(false) }
  async function saveProgress(batch: Batch) { const item = progress[batch.id]; if (!item) return; setSaving(true); const numeric = (value: string) => value ? Number(value) : null; const { error: e } = await supabase.from("orchard_nursery_batches").update({ emerged_count: numeric(item.emerged_count), ready_count: numeric(item.ready_count), transplanted_count: numeric(item.transplanted_count), actual_ready_date: item.actual_ready_date || null, transplant_date: item.transplant_date || null, updated_at: new Date().toISOString() }).eq("id", batch.id); if (e) setError(`${text.saveError}: ${e.message}`); else await loadData(); setSaving(false) }
  async function updateStatus(id: string, status: Batch["status"]) { setSaving(true); const { error: e } = await supabase.from("orchard_nursery_batches").update({ status, updated_at: new Date().toISOString() }).eq("id", id); if (e) setError(`${text.saveError}: ${e.message}`); else await loadData(); setSaving(false) }
  async function remove(table: string, id: string, message: string) { if (!window.confirm(message)) return; setSaving(true); const { error: e } = await supabase.from(table).delete().eq("id", id); if (e) setError(`${text.saveError}: ${e.message}`); else await loadData(); setSaving(false) }

  return <AppLayout><PageHeader title={text.title} description={text.description} actions={<Button variant="outline" onClick={() => void loadData()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />{text.refresh}</Button>} /><OrchardNavigation /><div className="space-y-6 p-4 sm:p-8">
    {error && <Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
    <div className="grid gap-6 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>{text.newSeedLot}</CardTitle><CardDescription>{seedLots.length} {text.available}</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={createLot}><Field label={text.crop}><Input value={lotForm.crop_name} onChange={(e) => setLotForm((v) => ({ ...v, crop_name: e.target.value }))} required /></Field><Field label={text.variety}><Input value={lotForm.variety} onChange={(e) => setLotForm((v) => ({ ...v, variety: e.target.value }))} /></Field><Field label={text.lot}><Input value={lotForm.lot_code} onChange={(e) => setLotForm((v) => ({ ...v, lot_code: e.target.value }))} /></Field><Field label={text.supplier}><Input value={lotForm.supplier} onChange={(e) => setLotForm((v) => ({ ...v, supplier: e.target.value }))} /></Field><Field label={text.quantity}><Input type="number" min="0" value={lotForm.quantity_seeds} onChange={(e) => setLotForm((v) => ({ ...v, quantity_seeds: e.target.value }))} /></Field><Field label={text.germination}><Input type="number" min="1" max="100" step="0.1" value={lotForm.germination_rate_pct} onChange={(e) => setLotForm((v) => ({ ...v, germination_rate_pct: e.target.value }))} /></Field><Field label={text.received}><Input type="date" value={lotForm.received_date} onChange={(e) => setLotForm((v) => ({ ...v, received_date: e.target.value }))} /></Field><Field label={text.expiry}><Input type="date" value={lotForm.expiry_date} onChange={(e) => setLotForm((v) => ({ ...v, expiry_date: e.target.value }))} /></Field><Field label={text.storage}><Input value={lotForm.storage_location} onChange={(e) => setLotForm((v) => ({ ...v, storage_location: e.target.value }))} /></Field><div className="md:col-span-2"><Field label={text.notes}><Textarea value={lotForm.notes} onChange={(e) => setLotForm((v) => ({ ...v, notes: e.target.value }))} /></Field></div><div className="md:col-span-2"><Button type="submit" disabled={saving}><Plus className="mr-2 h-4 w-4" />{text.saveLot}</Button></div></form></CardContent></Card>
      <Card><CardHeader><CardTitle>{text.newBatch}</CardTitle><CardDescription>{availableSuccessions.length} {text.planned}</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={createBatch}><Field label={text.succession}><Select value={batchForm.crop_succession_id} onValueChange={(value) => { const item = successionById.get(value); setBatchForm((v) => ({ ...v, crop_succession_id: value, sow_date: item?.planned_sow_date ?? "", expected_ready_date: item?.planned_transplant_date ?? "", cells_sown: item?.planned_plants?.toString() ?? "" })) }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{availableSuccessions.map((item) => <SelectItem key={item.id} value={item.id}>{successionLabel(item)}</SelectItem>)}</SelectContent></Select></Field><Field label={text.seedLot}><Select value={batchForm.seed_lot_id} onValueChange={(value) => setBatchForm((v) => ({ ...v, seed_lot_id: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">—</SelectItem>{seedLots.map((lot) => <SelectItem key={lot.id} value={lot.id}>{lot.crop_name}{lot.variety ? ` · ${lot.variety}` : ""}{lot.lot_code ? ` · ${lot.lot_code}` : ""}</SelectItem>)}</SelectContent></Select></Field><Field label={text.sowDate}><Input type="date" value={batchForm.sow_date} onChange={(e) => setBatchForm((v) => ({ ...v, sow_date: e.target.value }))} required /></Field><Field label={text.expectedReady}><Input type="date" value={batchForm.expected_ready_date} onChange={(e) => setBatchForm((v) => ({ ...v, expected_ready_date: e.target.value }))} /></Field><Field label={text.cells}><Input type="number" min="0" value={batchForm.cells_sown} onChange={(e) => setBatchForm((v) => ({ ...v, cells_sown: e.target.value }))} /></Field><Field label={text.seedsSown}><Input type="number" min="0" value={batchForm.seeds_sown} onChange={(e) => setBatchForm((v) => ({ ...v, seeds_sown: e.target.value }))} /></Field><Field label={text.location}><Input value={batchForm.location} onChange={(e) => setBatchForm((v) => ({ ...v, location: e.target.value }))} /></Field><div className="md:col-span-2"><Field label={text.notes}><Textarea value={batchForm.notes} onChange={(e) => setBatchForm((v) => ({ ...v, notes: e.target.value }))} /></Field></div><div className="md:col-span-2"><Button type="submit" disabled={saving || availableSuccessions.length === 0}><Sprout className="mr-2 h-4 w-4" />{text.startBatch}</Button></div></form></CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>{text.seedLots}</CardTitle></CardHeader><CardContent>{seedLots.length === 0 ? <p className="py-6 text-sm text-muted-foreground">{text.emptyLots}</p> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{seedLots.map((lot) => <div key={lot.id} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{lot.crop_name}{lot.variety ? ` · ${lot.variety}` : ""}</p><p className="text-sm text-muted-foreground">{lot.lot_code || lot.supplier || "—"}</p></div><Button variant="ghost" size="icon" onClick={() => void remove("orchard_seed_lots", lot.id, text.deleteLot)}><Trash2 className="h-4 w-4" /></Button></div><div className="mt-4 flex flex-wrap gap-2"><Badge variant="secondary">{lot.quantity_seeds.toLocaleString(locale)} {text.available}</Badge>{lot.germination_rate_pct && <Badge variant="outline">{lot.germination_rate_pct}%</Badge>}</div><p className="mt-3 text-xs text-muted-foreground">{lot.storage_location || ""}{lot.expiry_date ? ` · ${text.expiry}: ${dateLabel(lot.expiry_date, locale)}` : ""}</p></div>)}</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle>{text.nursery}</CardTitle></CardHeader><CardContent>{loading ? <p className="py-6 text-sm text-muted-foreground">{text.loading}</p> : batches.length === 0 ? <p className="py-6 text-sm text-muted-foreground">{text.emptyBatches}</p> : <div className="space-y-3">{batches.map((batch) => { const succession = successionById.get(batch.crop_succession_id); const item = progress[batch.id] ?? { emerged_count: "", ready_count: "", transplanted_count: "", actual_ready_date: "", transplant_date: "" }; return <div key={batch.id} className="rounded-lg border p-4"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><p className="font-semibold">{succession ? successionLabel(succession) : text.succession}</p><p className="mt-1 text-sm text-muted-foreground">{dateLabel(batch.sow_date, locale)} → {dateLabel(batch.expected_ready_date, locale)}{batch.location ? ` · ${batch.location}` : ""}</p><div className="mt-3 flex flex-wrap gap-2"><Badge variant="outline">{batch.seeds_sown} {text.seedsSown.toLowerCase()}</Badge>{batch.cells_sown != null && <Badge variant="secondary">{batch.cells_sown} {text.cells.toLowerCase()}</Badge>}</div></div><div className="flex gap-2"><Select value={batch.status} onValueChange={(value) => void updateStatus(batch.id, value as Batch["status"])}><SelectTrigger className="w-[155px]"><SelectValue /></SelectTrigger><SelectContent>{statuses.map((status) => <SelectItem key={status} value={status}>{titleize(status)}</SelectItem>)}</SelectContent></Select><Button variant="ghost" size="icon" onClick={() => void remove("orchard_nursery_batches", batch.id, text.deleteBatch)}><Trash2 className="h-4 w-4" /></Button></div></div><div className="mt-4 grid gap-3 border-t pt-4 md:grid-cols-3 xl:grid-cols-5"><Field label={text.emerged}><Input type="number" min="0" value={item.emerged_count} onChange={(e) => setProgress((p) => ({ ...p, [batch.id]: { ...item, emerged_count: e.target.value } }))} /></Field><Field label={text.ready}><Input type="number" min="0" value={item.ready_count} onChange={(e) => setProgress((p) => ({ ...p, [batch.id]: { ...item, ready_count: e.target.value } }))} /></Field><Field label={text.transplanted}><Input type="number" min="0" value={item.transplanted_count} onChange={(e) => setProgress((p) => ({ ...p, [batch.id]: { ...item, transplanted_count: e.target.value } }))} /></Field><Field label={text.actualReady}><Input type="date" value={item.actual_ready_date} onChange={(e) => setProgress((p) => ({ ...p, [batch.id]: { ...item, actual_ready_date: e.target.value } }))} /></Field><Field label={text.transplantDate}><Input type="date" value={item.transplant_date} onChange={(e) => setProgress((p) => ({ ...p, [batch.id]: { ...item, transplant_date: e.target.value } }))} /></Field></div><Button className="mt-4" variant="outline" onClick={() => void saveProgress(batch)} disabled={saving}>{text.saveCounts}</Button></div> })}</div>}</CardContent></Card>
  </div></AppLayout>
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div> }
