"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { Anchor, Loader2, MapPin, Pencil, Plus, Ship, Trash2, Wrench } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { createClient } from "@/lib/supabase/client"
import { useToast } from "@/hooks/use-toast"
import { useLanguage } from "@/lib/hooks/use-language"

type PortBoatType="port"|"boat"; type PortBoatStatus="operational"|"maintenance"|"inactive"
type PortBoat={id:string;name:string;type:PortBoatType;location:string;capacity:string|null;status:PortBoatStatus;description:string|null;last_maintenance:string|null;created_at:string|null;updated_at:string|null}
type PortBoatForm={name:string;type:PortBoatType;location:string;capacity:string;status:PortBoatStatus;description:string;last_maintenance:string}
const EMPTY_FORM:PortBoatForm={name:"",type:"boat",location:"",capacity:"",status:"operational",description:"",last_maintenance:""}
const STATUS_CLASS:Record<PortBoatStatus,string>={operational:"border-emerald-500/30 bg-emerald-500/10 text-emerald-700",maintenance:"border-amber-500/30 bg-amber-500/10 text-amber-700",inactive:"border-slate-500/30 bg-slate-500/10 text-slate-600"}
const COPY={
 en:{title:"Ports and boats",description:"Real operational inventory of docks, ports and fleet linked to Fundo Corcovado.",newRecord:"New record",ports:"Ports",boats:"Boats",operational:"Operational",maintenance:"Maintenance",maritime:"Maritime assets",visible:"visible records · data persisted in ports_boats.",all:"All",loading:"Loading maritime inventory…",empty:"No records match this filter.",capacity:"Capacity / dimensions",lastMaintenance:"Last maintenance",edit:"Edit",delete:"Delete",editRecord:"Edit record",newPortBoat:"New port or boat",dialogDetail:"Fields are saved directly to the canonical maritime inventory.",type:"Type",state:"Status",port:"Port",boat:"Boat",inactive:"Inactive",name:"Name",location:"Location",maintenanceNote:"Last maintenance",maintenancePlaceholder:"Date or operational note",recordDescription:"Description",cancel:"Cancel",saving:"Saving…",save:"Save",loadError:"Ports and boats could not be loaded.",updateError:"The record could not be updated.",createError:"The record could not be created.",updated:"Record updated",created:"Record created",deleteError:"The record could not be deleted.",deleted:"Record deleted",confirmPort:"Delete port",confirmBoat:"Delete boat"},
 es:{title:"Puertos y embarcaciones",description:"Inventario operativo real de muelles, puertos y flota vinculada al Fundo Corcovado.",newRecord:"Nuevo registro",ports:"Puertos",boats:"Embarcaciones",operational:"Operativos",maintenance:"En mantenimiento",maritime:"Activos marítimos",visible:"registros visibles · datos persistidos en ports_boats.",all:"Todos",loading:"Cargando inventario marítimo…",empty:"No hay registros para este filtro.",capacity:"Capacidad / dimensión",lastMaintenance:"Último mantenimiento",edit:"Editar",delete:"Eliminar",editRecord:"Editar registro",newPortBoat:"Nuevo puerto o embarcación",dialogDetail:"Los campos se guardan directamente en el inventario marítimo canónico.",type:"Tipo",state:"Estado",port:"Puerto",boat:"Embarcación",inactive:"Inactivo",name:"Nombre",location:"Ubicación",maintenanceNote:"Último mantenimiento",maintenancePlaceholder:"Fecha o nota operacional",recordDescription:"Descripción",cancel:"Cancelar",saving:"Guardando…",save:"Guardar",loadError:"No fue posible cargar puertos y embarcaciones.",updateError:"No fue posible actualizar el registro.",createError:"No fue posible crear el registro.",updated:"Registro actualizado",created:"Registro creado",deleteError:"No fue posible eliminar el registro.",deleted:"Registro eliminado",confirmPort:"Eliminar el puerto",confirmBoat:"Eliminar la embarcación"},
 de:{title:"Häfen und Boote",description:"Reales operatives Inventar von Stegen, Häfen und Flotte von Fundo Corcovado.",newRecord:"Neuer Eintrag",ports:"Häfen",boats:"Boote",operational:"Betriebsbereit",maintenance:"In Instandhaltung",maritime:"Maritime Anlagen",visible:"sichtbare Einträge · Daten in ports_boats gespeichert.",all:"Alle",loading:"Maritimes Inventar wird geladen…",empty:"Keine Einträge für diesen Filter.",capacity:"Kapazität / Abmessungen",lastMaintenance:"Letzte Instandhaltung",edit:"Bearbeiten",delete:"Löschen",editRecord:"Eintrag bearbeiten",newPortBoat:"Neuer Hafen oder Boot",dialogDetail:"Felder werden direkt im kanonischen maritimen Inventar gespeichert.",type:"Typ",state:"Status",port:"Hafen",boat:"Boot",inactive:"Inaktiv",name:"Name",location:"Standort",maintenanceNote:"Letzte Instandhaltung",maintenancePlaceholder:"Datum oder operative Notiz",recordDescription:"Beschreibung",cancel:"Abbrechen",saving:"Wird gespeichert…",save:"Speichern",loadError:"Häfen und Boote konnten nicht geladen werden.",updateError:"Der Eintrag konnte nicht aktualisiert werden.",createError:"Der Eintrag konnte nicht erstellt werden.",updated:"Eintrag aktualisiert",created:"Eintrag erstellt",deleteError:"Der Eintrag konnte nicht gelöscht werden.",deleted:"Eintrag gelöscht",confirmPort:"Hafen löschen",confirmBoat:"Boot löschen"},
} as const

export default function PortsBoatsPage(){
 const {language}=useLanguage();const lang=(language in COPY?language:"en") as keyof typeof COPY;const copy=COPY[lang];const locale=lang==="es"?"es-CL":lang==="de"?"de-DE":"en-US"
 const supabase=useMemo(()=>createClient(),[]);const {toast}=useToast();const [items,setItems]=useState<PortBoat[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [dialogOpen,setDialogOpen]=useState(false);const [editingId,setEditingId]=useState<string|null>(null);const [filter,setFilter]=useState<"all"|PortBoatType>("all");const [form,setForm]=useState<PortBoatForm>(EMPTY_FORM)
 const statusLabel=(status:PortBoatStatus)=>status==="operational"?copy.operational:status==="maintenance"?copy.maintenance:copy.inactive
 const typeLabel=(type:PortBoatType)=>type==="port"?copy.port:copy.boat
 const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from("ports_boats").select("id,name,type,location,capacity,status,description,last_maintenance,created_at,updated_at").order("type").order("name");if(error){console.error("ports_boats load failed",error);toast({title:copy.loadError,variant:"destructive"});setItems([])}else setItems((data??[]).flatMap(row=>{if((row.type!=="port"&&row.type!=="boat")||!["operational","maintenance","inactive"].includes(row.status))return[];return [{id:row.id,name:row.name,type:row.type as PortBoatType,location:row.location,capacity:row.capacity,status:row.status as PortBoatStatus,description:row.description,last_maintenance:row.last_maintenance,created_at:row.created_at,updated_at:row.updated_at} satisfies PortBoat]}));setLoading(false)},[copy.loadError,supabase,toast])
 useEffect(()=>{void load()},[load]);const visibleItems=useMemo(()=>filter==="all"?items:items.filter(item=>item.type===filter),[filter,items]);const metrics=useMemo(()=>({ports:items.filter(i=>i.type==="port").length,boats:items.filter(i=>i.type==="boat").length,operational:items.filter(i=>i.status==="operational").length,maintenance:items.filter(i=>i.status==="maintenance").length}),[items])
 const openNew=()=>{setEditingId(null);setForm(EMPTY_FORM);setDialogOpen(true)};const openEdit=(item:PortBoat)=>{setEditingId(item.id);setForm({name:item.name,type:item.type,location:item.location,capacity:item.capacity??"",status:item.status,description:item.description??"",last_maintenance:item.last_maintenance??""});setDialogOpen(true)}
 async function save(){if(!form.name.trim()||!form.location.trim()||saving)return;setSaving(true);const payload={name:form.name.trim(),type:form.type,location:form.location.trim(),capacity:form.capacity.trim()||null,status:form.status,description:form.description.trim()||null,last_maintenance:form.last_maintenance.trim()||null,updated_at:new Date().toISOString()};const result=editingId?await supabase.from("ports_boats").update(payload).eq("id",editingId):await supabase.from("ports_boats").insert(payload);setSaving(false);if(result.error){console.error("ports_boats save failed",result.error);toast({title:editingId?copy.updateError:copy.createError,variant:"destructive"});return}toast({title:editingId?copy.updated:copy.created});setDialogOpen(false);await load()}
 async function remove(item:PortBoat){if(!window.confirm(`${item.type==="port"?copy.confirmPort:copy.confirmBoat} “${item.name}”?`))return;const {error}=await supabase.from("ports_boats").delete().eq("id",item.id);if(error){console.error("ports_boats delete failed",error);return toast({title:copy.deleteError,variant:"destructive"})}toast({title:copy.deleted});await load()}
 return <AppLayout><PageHeader title={copy.title} description={copy.description} icon={Anchor} actions={<Button onClick={openNew}><Plus className="mr-2 h-4 w-4"/>{copy.newRecord}</Button>}/><div className="space-y-5 p-4 md:p-8"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Anchor} label={copy.ports} value={metrics.ports} locale={locale}/><Metric icon={Ship} label={copy.boats} value={metrics.boats} locale={locale}/><Metric icon={MapPin} label={copy.operational} value={metrics.operational} locale={locale}/><Metric icon={Wrench} label={copy.maintenance} value={metrics.maintenance} locale={locale}/></div>
 <Card><CardHeader className="gap-3 md:flex-row md:items-center md:justify-between"><div><CardTitle className="text-base">{copy.maritime}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{new Intl.NumberFormat(locale).format(visibleItems.length)} {copy.visible}</p></div><Select value={filter} onValueChange={(value:"all"|PortBoatType)=>setFilter(value)}><SelectTrigger className="w-full md:w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{copy.all}</SelectItem><SelectItem value="port">{copy.ports}</SelectItem><SelectItem value="boat">{copy.boats}</SelectItem></SelectContent></Select></CardHeader><CardContent>{loading?<div className="flex min-h-48 items-center justify-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>{copy.loading}</div>:visibleItems.length===0?<div className="min-h-48 place-content-center text-center text-sm text-muted-foreground">{copy.empty}</div>:<div className="grid gap-3 lg:grid-cols-2">{visibleItems.map(item=>{const Icon=item.type==="port"?Anchor:Ship;return <article key={item.id} className="rounded-lg border bg-card p-4 shadow-sm"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold">{item.name}</h3><Badge variant="outline" className={STATUS_CLASS[item.status]}>{statusLabel(item.status)}</Badge></div><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="h-3.5 w-3.5"/>{item.location}</p>{item.capacity&&<p className="mt-2 text-xs text-muted-foreground">{copy.capacity}: <span className="text-foreground">{item.capacity}</span></p>}{item.description&&<p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{item.description}</p>}{item.last_maintenance&&<p className="mt-2 text-xs text-muted-foreground">{copy.lastMaintenance}: {item.last_maintenance}</p>}</div><div className="flex shrink-0 gap-1"><Button variant="ghost" size="icon" onClick={()=>openEdit(item)} aria-label={`${copy.edit} ${item.name}`}><Pencil className="h-4 w-4"/></Button><Button variant="ghost" size="icon" onClick={()=>void remove(item)} aria-label={`${copy.delete} ${item.name}`}><Trash2 className="h-4 w-4"/></Button></div></div></article>})}</div>}</CardContent></Card></div>
 <Dialog open={dialogOpen} onOpenChange={open=>!saving&&setDialogOpen(open)}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{editingId?copy.editRecord:copy.newPortBoat}</DialogTitle><DialogDescription>{copy.dialogDetail}</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>{copy.type}</Label><Select value={form.type} onValueChange={(value:PortBoatType)=>setForm(current=>({...current,type:value}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="port">{copy.port}</SelectItem><SelectItem value="boat">{copy.boat}</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>{copy.state}</Label><Select value={form.status} onValueChange={(value:PortBoatStatus)=>setForm(current=>({...current,status:value}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="operational">{copy.operational}</SelectItem><SelectItem value="maintenance">{copy.maintenance}</SelectItem><SelectItem value="inactive">{copy.inactive}</SelectItem></SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="port-boat-name">{copy.name}</Label><Input id="port-boat-name" value={form.name} onChange={e=>setForm(current=>({...current,name:e.target.value}))} maxLength={120} required/></div><div className="space-y-2"><Label htmlFor="port-boat-location">{copy.location}</Label><Input id="port-boat-location" value={form.location} onChange={e=>setForm(current=>({...current,location:e.target.value}))} maxLength={160} required/></div><div className="space-y-2"><Label htmlFor="port-boat-capacity">{copy.capacity}</Label><Input id="port-boat-capacity" value={form.capacity} onChange={e=>setForm(current=>({...current,capacity:e.target.value}))} maxLength={120}/></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="port-boat-maintenance">{copy.maintenanceNote}</Label><Input id="port-boat-maintenance" value={form.last_maintenance} onChange={e=>setForm(current=>({...current,last_maintenance:e.target.value}))} maxLength={160} placeholder={copy.maintenancePlaceholder}/></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="port-boat-description">{copy.recordDescription}</Label><Textarea id="port-boat-description" value={form.description} onChange={e=>setForm(current=>({...current,description:e.target.value}))} rows={3} maxLength={600}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setDialogOpen(false)} disabled={saving}>{copy.cancel}</Button><Button onClick={()=>void save()} disabled={saving||!form.name.trim()||!form.location.trim()}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}{saving?copy.saving:copy.save}</Button></DialogFooter></DialogContent></Dialog>
 </AppLayout>
}
function Metric({icon:Icon,label,value,locale}:{icon:typeof Anchor;label:string;value:number;locale:string}){return <Card><CardContent className="flex items-center gap-3 p-4"><Icon className="h-5 w-5 text-muted-foreground"/><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-semibold tracking-tight">{new Intl.NumberFormat(locale).format(value)}</p></div></CardContent></Card>}
