"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { ArrowLeft, Boxes, RefreshCw, ShieldCheck } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useToast } from "@/hooks/use-toast"
import { useLanguage } from "@/lib/hooks/use-language"
import { createBrowserClient } from "@/lib/supabase/client"

type Intake = { id:string; receipt_item_id:string; intake_type:"asset"|"consumable"; status:string; reconciliation_status:string; created_at:string; notes:string|null }
type ReceiptItem = { id:string; request_id:string; received_quantity:number; condition:string; discrepancy_reason:string|null; receipt_id:string }
type Request = { id:string; title:string; category:string; unit:string; quantity:number }
type Receipt = { id:string; receipt_number:string|null; purchase_order_id:string }
type Order = { id:string; order_number:string|null }
type Option = { id:string; name:string; code?:string|null; warehouse_id?:string; warehouses?:{name:string}|null }
type ReplenishmentNeed = { procurement_request_id:string|null; stock_item_id:string; status:string; inventory_stock_items:{ item_code:string; name:string; warehouse_location_id:string; minimum_stock:number; warehouse_locations:{name:string;warehouses:{name:string}|{name:string}[]|null}|{name:string;warehouses:{name:string}|{name:string}[]|null}[]|null }|{ item_code:string; name:string; warehouse_location_id:string; minimum_stock:number; warehouse_locations:{name:string;warehouses:{name:string}|{name:string}[]|null}|{name:string;warehouses:{name:string}|{name:string}[]|null}[]|null }[]|null }

const LOCALES = { en:"en-US", es:"es-CL", de:"de-DE" } as const
const COPY = {
 en:{title:"Inventory intake",description:"Classification and reconciliation of procurement receipts.",inventory:"Inventory",pending:"Pending",processed:"Processed",exceptions:"Exceptions",retry:"Retry",queue:"Pending queue",queueDescription:"Assets require category, cost center, and location. Consumable replenishment preserves the SKU and physical location that originated the purchase.",loading:"Loading queue…",empty:"No receipts are pending inventory intake.",emptyHint:"They will appear here after a receipt is registered for inventory intake.",selectReceipt:"Select receipt",lineage:"Protected replenishment lineage",lineagePrefix:"SKU",lineageSuffix:"This intake can only return to its source location; no parallel SKU is created.",warehouse:"Warehouse",originLocation:"its source location",location:"Location",selectLocation:"Select location",costCenter:"Cost center",keepCurrent:"Keep current / select",assetCategory:"Asset category",selectCategory:"Select category",class:"Class",equipment:"Equipment",tool:"Tool",vehicle:"Vehicle or machinery",infrastructure:"Infrastructure",other:"Other",minimumStock:"Minimum stock",minimumPreserved:"Current minimum is preserved",notes:"Intake notes",processing:"Processing…",applyReplenishment:"Apply replenishment to SKU",process:"Process intake",recent:"Recent reconciliation",asset:"Asset",consumable:"Consumable",loadError:"Inventory intake data could not be loaded.",processError:"The intake could not be processed.",processedTitle:"Intake processed",createdAssets:"asset(s) created.",replenishmentApplied:"Replenishment applied to the source SKU. Stock increased by",stockUpdated:"Stock increased by",order:"PO",receivedItem:"Received item"},
 es:{title:"Ingreso a inventario",description:"Clasificación y conciliación de recepciones de compras.",inventory:"Inventario",pending:"Pendientes",processed:"Procesados",exceptions:"Con excepción",retry:"Reintentar",queue:"Cola pendiente",queueDescription:"Los activos requieren categoría, centro de costo y ubicación. Una reposición consumible conserva el SKU y la ubicación física que originaron la compra.",loading:"Cargando cola…",empty:"No hay recepciones pendientes de ingreso.",emptyHint:"Aparecerán aquí después de registrar una recepción con ingreso a inventario.",selectReceipt:"Seleccionar recepción",lineage:"Reposición con lineage protegido",lineagePrefix:"SKU",lineageSuffix:"Este ingreso sólo puede volver a su ubicación de origen; no se crea un SKU paralelo.",warehouse:"Bodega",originLocation:"su ubicación de origen",location:"Ubicación",selectLocation:"Seleccionar ubicación",costCenter:"Centro de costo",keepCurrent:"Conservar actual / seleccionar",assetCategory:"Categoría de activo",selectCategory:"Seleccionar categoría",class:"Clase",equipment:"Equipo",tool:"Herramienta",vehicle:"Vehículo o maquinaria",infrastructure:"Infraestructura",other:"Otro",minimumStock:"Stock mínimo",minimumPreserved:"Se conserva el mínimo actual",notes:"Notas de ingreso",processing:"Procesando…",applyReplenishment:"Aplicar reposición al SKU",process:"Procesar ingreso",recent:"Conciliación reciente",asset:"Activo",consumable:"Consumible",loadError:"No fue posible cargar los datos de ingreso a inventario.",processError:"No fue posible procesar el ingreso.",processedTitle:"Ingreso procesado",createdAssets:"activo(s) creados.",replenishmentApplied:"Reposición aplicada al SKU de origen. Stock actualizado en",stockUpdated:"Stock actualizado en",order:"OC",receivedItem:"Ítem recibido"},
 de:{title:"Inventareingang",description:"Klassifizierung und Abstimmung von Beschaffungseingängen.",inventory:"Inventar",pending:"Ausstehend",processed:"Verarbeitet",exceptions:"Mit Ausnahme",retry:"Erneut versuchen",queue:"Ausstehende Eingänge",queueDescription:"Anlagen benötigen Kategorie, Kostenstelle und Standort. Verbrauchsmaterial-Nachschub behält SKU und physischen Ausgangsstandort bei.",loading:"Eingänge werden geladen…",empty:"Keine Eingänge warten auf die Inventaraufnahme.",emptyHint:"Sie erscheinen hier nach der Erfassung eines Wareneingangs mit Inventaraufnahme.",selectReceipt:"Wareneingang auswählen",lineage:"Geschützte Nachschub-Linie",lineagePrefix:"SKU",lineageSuffix:"Dieser Eingang kann nur an seinen Ursprungsstandort zurückkehren; es wird kein paralleler SKU erzeugt.",warehouse:"Lager",originLocation:"seinen Ursprungsstandort",location:"Standort",selectLocation:"Standort auswählen",costCenter:"Kostenstelle",keepCurrent:"Aktuell behalten / auswählen",assetCategory:"Anlagenkategorie",selectCategory:"Kategorie auswählen",class:"Klasse",equipment:"Ausrüstung",tool:"Werkzeug",vehicle:"Fahrzeug oder Maschine",infrastructure:"Infrastruktur",other:"Sonstiges",minimumStock:"Mindestbestand",minimumPreserved:"Aktueller Mindestbestand bleibt erhalten",notes:"Eingangsnotizen",processing:"Wird verarbeitet…",applyReplenishment:"Nachschub auf SKU anwenden",process:"Eingang verarbeiten",recent:"Letzte Abstimmung",asset:"Anlage",consumable:"Verbrauchsmaterial",loadError:"Die Inventareingangsdaten konnten nicht geladen werden.",processError:"Der Eingang konnte nicht verarbeitet werden.",processedTitle:"Eingang verarbeitet",createdAssets:"Anlage(n) erstellt.",replenishmentApplied:"Nachschub auf Ursprungs-SKU angewendet. Bestand erhöht um",stockUpdated:"Bestand erhöht um",order:"PO",receivedItem:"Empfangener Artikel"}
} as const

function firstRelation<T>(value:T|T[]|null|undefined):T|null{return Array.isArray(value)?value[0]??null:value??null}

export default function InventoryIntakePage(){
 const {language}=useLanguage(); const copy=COPY[language]; const locale=LOCALES[language]; const number=useMemo(()=>new Intl.NumberFormat(locale),[locale]); const dateTime=useMemo(()=>new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}),[locale]); const localize=(href:string)=>`/${language}${href}`
 const supabase=useMemo(()=>createBrowserClient(),[]); const {toast}=useToast()
 const [intakes,setIntakes]=useState<Intake[]>([]); const [items,setItems]=useState<Record<string,ReceiptItem>>({}); const [requests,setRequests]=useState<Record<string,Request>>({}); const [receipts,setReceipts]=useState<Record<string,Receipt>>({}); const [orders,setOrders]=useState<Record<string,Order>>({}); const [replenishments,setReplenishments]=useState<Record<string,ReplenishmentNeed>>({})
 const [locations,setLocations]=useState<Option[]>([]); const [categories,setCategories]=useState<Option[]>([]); const [costCenters,setCostCenters]=useState<Option[]>([])
 const [selected,setSelected]=useState(""); const [locationId,setLocationId]=useState(""); const [categoryId,setCategoryId]=useState(""); const [costCenterId,setCostCenterId]=useState(""); const [assetClass,setAssetClass]=useState("equipment"); const [minimumStock,setMinimumStock]=useState("0"); const [notes,setNotes]=useState(""); const [loading,setLoading]=useState(true); const [processing,setProcessing]=useState(false); const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);const [a,b,c,d,e,f,g,h,i]=await Promise.all([
  supabase.from("procurement_inventory_intake").select("id,receipt_item_id,intake_type,status,reconciliation_status,created_at,notes").order("created_at",{ascending:false}),
  supabase.from("procurement_receipt_items").select("id,request_id,received_quantity,condition,discrepancy_reason,receipt_id"), supabase.from("procurement_requests").select("id,title,category,unit,quantity"), supabase.from("procurement_receipts").select("id,receipt_number,purchase_order_id"), supabase.from("procurement_purchase_orders").select("id,order_number"), supabase.from("warehouse_locations").select("id,name,code,warehouse_id,warehouses(name)").eq("is_active",true).order("name"), supabase.from("asset_categories").select("id,name,code").eq("is_active",true).order("name"), supabase.from("cost_centers").select("id,name,code").eq("is_active",true).order("name"), supabase.from("inventory_replenishment_needs").select("procurement_request_id,stock_item_id,status,inventory_stock_items(item_code,name,warehouse_location_id,minimum_stock,warehouse_locations(name,warehouses(name)))").in("status",["requested","approved","ordered","receiving"])
 ]); const err=[a,b,c,d,e,f,g,h,i].find(x=>x.error)?.error;if(err){console.error("[inventory-intake] load failed",err);setError(copy.loadError);setLoading(false);return}
 setIntakes((a.data??[]) as Intake[]);setItems(Object.fromEntries(((b.data??[]) as ReceiptItem[]).map(x=>[x.id,x])));setRequests(Object.fromEntries(((c.data??[]) as Request[]).map(x=>[x.id,x])));setReceipts(Object.fromEntries(((d.data??[]) as Receipt[]).map(x=>[x.id,x])));setOrders(Object.fromEntries(((e.data??[]) as Order[]).map(x=>[x.id,x])));setLocations((f.data??[]).map(x=>({...x,warehouses:firstRelation(x.warehouses)})));setCategories((g.data??[]) as Option[]);setCostCenters((h.data??[]) as Option[]);setReplenishments(Object.fromEntries(((i.data??[]) as unknown as ReplenishmentNeed[]).filter(x=>x.procurement_request_id).map(x=>[x.procurement_request_id as string,x])));setLoading(false)},[copy.loadError,supabase])
 useEffect(()=>{void load()},[load]); const current=intakes.find(x=>x.id===selected); const pending=intakes.filter(x=>x.status==="pending"); const currentItem=current?items[current.receipt_item_id]:null; const currentNeed=currentItem?replenishments[currentItem.request_id]??null:null; const currentStock=firstRelation(currentNeed?.inventory_stock_items); const currentStockLocation=firstRelation(currentStock?.warehouse_locations); const currentWarehouse=firstRelation(currentStockLocation?.warehouses)
 useEffect(()=>{if(!current){setLocationId("");return}if(currentNeed&&currentStock){setLocationId(currentStock.warehouse_location_id);setMinimumStock(String(currentStock.minimum_stock??0));return}setLocationId("")},[current,currentNeed,currentStock])
 async function process(){if(!current)return;const destination=currentNeed&&currentStock?currentStock.warehouse_location_id:locationId;if(!destination)return;if(current.intake_type==="asset"&&(!categoryId||!costCenterId))return;setProcessing(true);const {data,error:rpcError}=await supabase.rpc("process_procurement_inventory_intake",{p_intake_id:current.id,p_warehouse_location_id:destination,p_asset_category_id:current.intake_type==="asset"?categoryId:null,p_cost_center_id:costCenterId||null,p_asset_class:assetClass,p_minimum_stock:currentNeed?0:Number(minimumStock||0),p_notes:notes.trim()||null});setProcessing(false);if(rpcError){console.error("[inventory-intake] process failed",rpcError);toast({title:copy.processError,variant:"destructive"});return}toast({title:copy.processedTitle,description:data?.type==="asset"?`${number.format(Number(data.created??0))} ${copy.createdAssets}`:data?.replenishment_lineage?`${copy.replenishmentApplied} ${number.format(Number(data.quantity_added??0))}.`:`${copy.stockUpdated} ${number.format(Number(data.quantity_added??0))}.`});setSelected("");setLocationId("");setCategoryId("");setCostCenterId("");setNotes("");await load()}
 function label(intake:Intake){const item=items[intake.receipt_item_id];const request=item?requests[item.request_id]:null;const receipt=item?receipts[item.receipt_id]:null;const order=receipt?orders[receipt.purchase_order_id]:null;return `${order?.order_number??copy.order} · ${request?.title??copy.receivedItem} · ${number.format(item?.received_quantity??0)} ${request?.unit??""}`}
 return <AppLayout><PageHeader title={copy.title} description={copy.description} actions={<Button variant="outline" asChild><Link href={localize("/inventory")}><ArrowLeft className="mr-2 h-4 w-4"/>{copy.inventory}</Link></Button>}/><div className="space-y-6 p-4 sm:p-8">
  <div className="grid gap-4 sm:grid-cols-3"><Metric title={copy.pending} value={pending.length} locale={locale}/><Metric title={copy.processed} value={intakes.filter(x=>x.status==="processed").length} locale={locale}/><Metric title={copy.exceptions} value={intakes.filter(x=>x.reconciliation_status==="exception").length} alert={intakes.some(x=>x.reconciliation_status==="exception")} locale={locale}/></div>
  {error&&<Card className="border-destructive/60"><CardContent className="flex items-center justify-between p-4"><p className="text-sm text-destructive">{error}</p><Button variant="outline" size="sm" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>{copy.retry}</Button></CardContent></Card>}
  <Card><CardHeader><CardTitle>{copy.queue}</CardTitle><CardDescription>{copy.queueDescription}</CardDescription></CardHeader><CardContent className="space-y-4">
   {loading?<p className="py-8 text-center text-muted-foreground">{copy.loading}</p>:pending.length===0?<div className="py-10 text-center"><Boxes className="mx-auto mb-3 h-7 w-7 text-muted-foreground"/><p className="font-medium">{copy.empty}</p><p className="mt-1 text-sm text-muted-foreground">{copy.emptyHint}</p></div>:<>
    <Select value={selected} onValueChange={setSelected}><SelectTrigger><SelectValue placeholder={copy.selectReceipt}/></SelectTrigger><SelectContent>{pending.map(x=><SelectItem key={x.id} value={x.id}>{label(x)}</SelectItem>)}</SelectContent></Select>
    {currentNeed&&currentStock&&<div className="flex gap-3 rounded-lg border border-emerald-300 bg-emerald-50/50 p-4 text-sm"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-700"/><div><p className="font-medium text-emerald-900">{copy.lineage}</p><p className="mt-1 text-emerald-800">{copy.lineagePrefix} {currentStock.item_code} · {currentStock.name}. {copy.lineageSuffix} {currentWarehouse?.name??copy.warehouse} · {currentStockLocation?.name??copy.originLocation}.</p></div></div>}
    {current&&<div className="grid gap-4 md:grid-cols-2"><Field label={copy.location}><Select value={locationId} onValueChange={setLocationId} disabled={Boolean(currentNeed)}><SelectTrigger><SelectValue placeholder={copy.selectLocation}/></SelectTrigger><SelectContent>{locations.map(x=><SelectItem key={x.id} value={x.id}>{x.warehouses?.name??copy.warehouse} · {x.name}</SelectItem>)}</SelectContent></Select></Field>
     <Field label={copy.costCenter}><Select value={costCenterId} onValueChange={setCostCenterId}><SelectTrigger><SelectValue placeholder={copy.keepCurrent}/></SelectTrigger><SelectContent>{costCenters.map(x=><SelectItem key={x.id} value={x.id}>{x.name}{x.code?` (${x.code})`:""}</SelectItem>)}</SelectContent></Select></Field>
     {current.intake_type==="asset"?<><Field label={copy.assetCategory}><Select value={categoryId} onValueChange={setCategoryId}><SelectTrigger><SelectValue placeholder={copy.selectCategory}/></SelectTrigger><SelectContent>{categories.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select></Field><Field label={copy.class}><Select value={assetClass} onValueChange={setAssetClass}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="equipment">{copy.equipment}</SelectItem><SelectItem value="tool">{copy.tool}</SelectItem><SelectItem value="vehicle">{copy.vehicle}</SelectItem><SelectItem value="infrastructure">{copy.infrastructure}</SelectItem><SelectItem value="other">{copy.other}</SelectItem></SelectContent></Select></Field></>:!currentNeed?<Field label={copy.minimumStock}><Input type="number" min="0" value={minimumStock} onChange={e=>setMinimumStock(e.target.value)}/></Field>:<div><p className="text-sm font-medium">{copy.minimumStock}</p><p className="mt-1 rounded-md border bg-muted/20 px-3 py-2 text-sm">{copy.minimumPreserved}: {number.format(currentStock?.minimum_stock??0)}</p></div>}
     <div className="md:col-span-2"><label className="text-sm font-medium">{copy.notes}</label><textarea className="mt-1 min-h-20 w-full rounded-md border bg-background px-3 py-2 text-sm" value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="md:col-span-2 flex justify-end"><Button onClick={()=>void process()} disabled={processing||!(currentNeed&&currentStock?currentStock.warehouse_location_id:locationId)||(current.intake_type==="asset"&&(!categoryId||!costCenterId))}>{processing?copy.processing:currentNeed?copy.applyReplenishment:copy.process}</Button></div></div>}
   </>}
  </CardContent></Card>
  <Card><CardHeader><CardTitle>{copy.recent}</CardTitle></CardHeader><CardContent className="space-y-2">{intakes.slice(0,12).map(x=><div key={x.id} className="flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{label(x)}</p><p className="text-xs text-muted-foreground">{dateTime.format(new Date(x.created_at))}</p></div><div className="flex gap-2"><Badge variant="outline">{x.intake_type==="asset"?copy.asset:copy.consumable}</Badge><Badge variant="outline">{x.status}</Badge><Badge variant="outline">{x.reconciliation_status}</Badge></div></div>)}</CardContent></Card>
 </div></AppLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="text-sm font-medium">{label}</label><div className="mt-1">{children}</div></div>}
function Metric({title,value,alert=false,locale}:{title:string;value:number;alert?:boolean;locale:string}){return <Card className={alert?"border-amber-300":undefined}><CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground">{title}</CardTitle></CardHeader><CardContent className="text-3xl font-semibold">{new Intl.NumberFormat(locale).format(value)}</CardContent></Card>}
