"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { BarChart3, BookOpenText, ChartNoAxesCombined, FileText, Leaf, RefreshCw, ShieldAlert, Sprout } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage, type Language } from "@/lib/hooks/use-language"
import { ALL_GAME_PLANS, gamePlanScopeLabel, resolveRequestedGamePlanId, resolveSelectedGamePlan, scopeBySuccessionId, scopeGamePlanGraph, syncGamePlanQuery, withGamePlanQuery } from "@/lib/orchard/game-plan-scope"

type GamePlan={id:string;name:string;season:string|null;start_date:string;end_date:string;status:string}
type Cycle={id:string;game_plan_id:string}
type Crop={id:string;crop_succession_id:string|null;status:string}
type Succession={id:string;crop_cycle_id:string;status:string}
type Harvest={id:string;crop_id:string;crop_succession_id:string|null;total_market_value:number|null;quantity_harvested:number|null;market_value_per_unit:number|null}
type Note={id:string;crop_id:string|null;crop_succession_id:string|null;note_type:string}
type Health={id:string;crop_id:string;severity_level:string|null;treatment_effectiveness:string|null}
type ChartDef={id:string;is_shared:boolean}
type Commitment={id:string;crop_succession_id:string|null;status:string}

const localeByLanguage:Record<Language,string>={en:"en-US",es:"es-CL",de:"de-DE"}
const copy:Record<Language,Record<string,string>>={
 en:{allRecords:"All records",seasonSummary:"Season Summary",seasonSummaryText:"Executive closeout bounded by Game Plan: execution, harvest, recorded value, health and learning.",harvestPasses:"harvest passes",traceability:"Traceability",traceabilityText:"Full succession lineage from nursery through harvest.",successionsInScope:"successions in scope",planVsActual:"Plan vs Actual",planVsActualText:"Planned timing and volume compared with real execution.",activeInScope:"active in scope",commercial:"Commercial",commercialText:"Demand, commitments, targets and recorded value.",openCommitments:"open commitments in scope",decisions:"Decisions",decisionsText:"Deterministic, actionable operational exceptions.",highCritical:"high/critical observations",charts:"Custom Charts",chartsText:"Saved views over canonical Orchard data; chart definitions are global, while scope can travel with the view.",sharedGlobal:"global shared",notesInsights:"Notes & Insights",notesInsightsText:"Field journal, signals and operational learning.",notesInScope:"notes in scope",reports:"Reports",selectedDescription:"Executive hub bounded to {scope}. Hub signals use only records connected to that Game Plan.",globalDescription:"Global executive hub. Select a Game Plan so hub signals represent a bounded closeout.",refresh:"Refresh",gamePlanReporting:"Game Plan reporting",reportingLayer:"Orchard reporting layer",narrative:"One narrative from plan to outcome.",formalRange:"Formal plan range: {start} → {end}. Hub KPIs propagate through connected cycles, successions and crops.",globalNarrative:"Every report resolves back to the same operational records used by the team. Harvest value is shown without a currency symbol because harvest records do not store currency.",activeCrops:"Active crops",recordedHarvestValue:"Recorded harvest value",notes:"Notes",savedCharts:"Saved charts",closeout:"Closeout package",selectedPackage:"Package signals are bounded to the selected Game Plan wherever a canonical relationship exists.",globalPackage:"Select a Game Plan to turn global signals into a bounded closeout package.",openReport:"Open report →"},
 es:{allRecords:"Todos los registros",seasonSummary:"Resumen de Temporada",seasonSummaryText:"Cierre ejecutivo acotable por Game Plan: ejecución, cosecha, valor registrado, sanidad y aprendizaje.",harvestPasses:"pases de cosecha",traceability:"Trazabilidad",traceabilityText:"Cadena completa por sucesión desde vivero hasta cosecha.",successionsInScope:"sucesiones en scope",planVsActual:"Plan vs Real",planVsActualText:"Fechas y volumen planificado comparados con ejecución real.",activeInScope:"activas en scope",commercial:"Comercial",commercialText:"Demanda, compromisos, objetivos y valor registrado.",openCommitments:"compromisos abiertos en scope",decisions:"Decisiones",decisionsText:"Excepciones operativas determinísticas y accionables.",highCritical:"observaciones altas/críticas",charts:"Gráficos",chartsText:"Vistas guardadas sobre datos canónicos de Orchard; la definición del gráfico es global, pero el scope puede viajar a la vista.",sharedGlobal:"compartidos globales",notesInsights:"Notas e Insights",notesInsightsText:"Journal de campo, señales y aprendizaje operativo.",notesInScope:"notas en scope",reports:"Reportes",selectedDescription:"Centro ejecutivo acotado a {scope}. Las señales del hub usan solo registros conectados a ese Game Plan.",globalDescription:"Centro ejecutivo global. Selecciona un Game Plan para que las señales del hub representen un cierre acotado.",refresh:"Actualizar",gamePlanReporting:"Reporting por Game Plan",reportingLayer:"Capa de reportes Orchard",narrative:"Una sola narrativa desde el plan hasta el resultado.",formalRange:"Rango formal del plan: {start} → {end}. Los KPIs del hub se propagan por ciclos, sucesiones y cultivos conectados.",globalNarrative:"Cada reporte vuelve a los mismos registros operativos que usa el equipo. El valor de cosecha se muestra sin símbolo monetario porque el registro de cosecha no guarda moneda.",activeCrops:"Cultivos activos",recordedHarvestValue:"Valor cosecha registrado",notes:"Notas",savedCharts:"Vistas guardadas",closeout:"Paquete de cierre",selectedPackage:"Las señales del paquete están acotadas al Game Plan seleccionado cuando existe una relación canónica disponible.",globalPackage:"Selecciona un Game Plan para convertir las señales globales en un paquete de cierre acotado.",openReport:"Abrir reporte →"},
 de:{allRecords:"Alle Datensätze",seasonSummary:"Saisonübersicht",seasonSummaryText:"Executive-Abschluss nach Game Plan: Ausführung, Ernte, erfasster Wert, Pflanzengesundheit und Lernen.",harvestPasses:"Erntedurchgänge",traceability:"Rückverfolgbarkeit",traceabilityText:"Vollständige Folge vom Jungpflanzenbestand bis zur Ernte.",successionsInScope:"Folgen im Bereich",planVsActual:"Plan vs. Ist",planVsActualText:"Geplante Termine und Mengen im Vergleich zur tatsächlichen Ausführung.",activeInScope:"aktiv im Bereich",commercial:"Kommerziell",commercialText:"Nachfrage, Verpflichtungen, Ziele und erfasster Wert.",openCommitments:"offene Verpflichtungen im Bereich",decisions:"Entscheidungen",decisionsText:"Deterministische und umsetzbare operative Ausnahmen.",highCritical:"hohe/kritische Beobachtungen",charts:"Benutzerdefinierte Diagramme",chartsText:"Gespeicherte Ansichten auf kanonischen Orchard-Daten; Diagrammdefinitionen sind global, der Bereich kann jedoch mit der Ansicht reisen.",sharedGlobal:"global geteilt",notesInsights:"Notizen & Erkenntnisse",notesInsightsText:"Feldjournal, Signale und operatives Lernen.",notesInScope:"Notizen im Bereich",reports:"Berichte",selectedDescription:"Executive-Hub begrenzt auf {scope}. Die Signale des Hubs verwenden nur Datensätze, die mit diesem Game Plan verbunden sind.",globalDescription:"Globaler Executive-Hub. Wähle einen Game Plan, damit die Hub-Signale einen klar abgegrenzten Abschluss darstellen.",refresh:"Aktualisieren",gamePlanReporting:"Berichte nach Game Plan",reportingLayer:"Orchard-Berichtsebene",narrative:"Eine durchgängige Geschichte vom Plan bis zum Ergebnis.",formalRange:"Formaler Planzeitraum: {start} → {end}. Die Hub-KPIs werden über verbundene Zyklen, Folgen und Kulturen propagiert.",globalNarrative:"Jeder Bericht greift auf dieselben operativen Datensätze zurück, die das Team verwendet. Der Erntewert wird ohne Währungssymbol angezeigt, da Erntedatensätze keine Währung speichern.",activeCrops:"Aktive Kulturen",recordedHarvestValue:"Erfasster Erntewert",notes:"Notizen",savedCharts:"Gespeicherte Diagramme",closeout:"Abschlusspaket",selectedPackage:"Die Signale des Pakets sind auf den ausgewählten Game Plan begrenzt, sofern eine kanonische Beziehung vorhanden ist.",globalPackage:"Wähle einen Game Plan, um globale Signale in ein klar abgegrenztes Abschlusspaket zu verwandeln.",openReport:"Bericht öffnen →"},
}
const fill=(template:string,values:Record<string,string>)=>Object.entries(values).reduce((out,[key,value])=>out.replaceAll(`{${key}}`,value),template)

export default function OrchardReportsPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const text=copy[language];const number=(value:number)=>new Intl.NumberFormat(localeByLanguage[language],{maximumFractionDigits:2}).format(value)
 const [plans,setPlans]=useState<GamePlan[]>([]);const [selectedPlanId,setSelectedPlanId]=useState<string>(ALL_GAME_PLANS);const [cycles,setCycles]=useState<Cycle[]>([]);const [crops,setCrops]=useState<Crop[]>([]);const [successions,setSuccessions]=useState<Succession[]>([]);const [harvests,setHarvests]=useState<Harvest[]>([]);const [notes,setNotes]=useState<Note[]>([]);const [health,setHealth]=useState<Health[]>([]);const [charts,setCharts]=useState<ChartDef[]>([]);const [commitments,setCommitments]=useState<Commitment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);const [gp,cy,c,s,h,n,he,ch,cm]=await Promise.all([supabase.from("orchard_game_plans").select("id,name,season,start_date,end_date,status").order("start_date",{ascending:false}),supabase.from("orchard_crop_cycles").select("id,game_plan_id"),supabase.from("orchard_crops").select("id,crop_succession_id,status"),supabase.from("orchard_crop_successions").select("id,crop_cycle_id,status"),supabase.from("orchard_harvest_records").select("id,crop_id,crop_succession_id,total_market_value,quantity_harvested,market_value_per_unit"),supabase.from("orchard_notes").select("id,crop_id,crop_succession_id,note_type"),supabase.from("orchard_pest_logs").select("id,crop_id,severity_level,treatment_effectiveness"),supabase.from("orchard_chart_definitions").select("id,is_shared"),supabase.from("orchard_sales_commitments").select("id,crop_succession_id,status")]);const e=gp.error??cy.error??c.error??s.error??h.error??n.error??he.error??ch.error??cm.error;if(e)setError(e.message);else{const planRows=(gp.data??[]) as GamePlan[];setPlans(planRows);setCycles((cy.data??[]) as Cycle[]);setCrops((c.data??[]) as Crop[]);setSuccessions((s.data??[]) as Succession[]);setHarvests((h.data??[]) as Harvest[]);setNotes((n.data??[]) as Note[]);setHealth((he.data??[]) as Health[]);setCharts((ch.data??[]) as ChartDef[]);setCommitments((cm.data??[]) as Commitment[]);if(typeof window!=="undefined")setSelectedPlanId(resolveRequestedGamePlanId(planRows,window.location.search))}setLoading(false)},[supabase]);useEffect(()=>{void load()},[load])
 const selectedPlan=resolveSelectedGamePlan(plans,selectedPlanId);const {scopedSuccessions,successionIds}=useMemo(()=>scopeGamePlanGraph(cycles,successions,selectedPlanId),[cycles,successions,selectedPlanId])
 const scopedCrops=useMemo(()=>scopeBySuccessionId(crops,successionIds,selectedPlanId,c=>c.crop_succession_id),[crops,successionIds,selectedPlanId]);const cropIds=useMemo(()=>new Set(scopedCrops.map(c=>c.id)),[scopedCrops])
 const scopedHarvests=useMemo(()=>selectedPlanId===ALL_GAME_PLANS?harvests:harvests.filter(h=>(h.crop_succession_id&&successionIds.has(h.crop_succession_id))||cropIds.has(h.crop_id)),[harvests,successionIds,cropIds,selectedPlanId]);const scopedNotes=useMemo(()=>selectedPlanId===ALL_GAME_PLANS?notes:notes.filter(n=>(n.crop_id&&cropIds.has(n.crop_id))||(n.crop_succession_id&&successionIds.has(n.crop_succession_id))),[notes,cropIds,successionIds,selectedPlanId]);const scopedHealth=useMemo(()=>selectedPlanId===ALL_GAME_PLANS?health:health.filter(h=>cropIds.has(h.crop_id)),[health,cropIds,selectedPlanId]);const scopedCommitments=useMemo(()=>scopeBySuccessionId(commitments,successionIds,selectedPlanId,c=>c.crop_succession_id),[commitments,successionIds,selectedPlanId])
 const harvestValue=scopedHarvests.reduce((sum,h)=>sum+Number(h.total_market_value??((h.quantity_harvested??0)*(h.market_value_per_unit??0))),0);const highCritical=scopedHealth.filter(h=>["high","critical"].includes((h.severity_level??"").toLowerCase())).length;const activeCrops=scopedCrops.filter(c=>!["harvested","failed","completed"].includes((c.status??"").toLowerCase())).length;const activeSuccessions=scopedSuccessions.filter(s=>!["completed","cancelled"].includes((s.status??"").toLowerCase())).length;const sharedCharts=charts.filter(c=>c.is_shared).length;const openCommitments=scopedCommitments.filter(c=>!["fulfilled","cancelled"].includes((c.status??"").toLowerCase())).length
 const scopeLabel=gamePlanScopeLabel(selectedPlan,text.allRecords);const changePlan=(id:string)=>{setSelectedPlanId(id);syncGamePlanQuery(id)}
 const modules=[{href:withGamePlanQuery("/orchard/season-summary",selectedPlanId),icon:Leaf,title:text.seasonSummary,text:text.seasonSummaryText,signal:`${scopedHarvests.length} ${text.harvestPasses}`},{href:withGamePlanQuery("/orchard/traceability",selectedPlanId),icon:Sprout,title:text.traceability,text:text.traceabilityText,signal:`${scopedSuccessions.length} ${text.successionsInScope}`},{href:withGamePlanQuery("/orchard/performance",selectedPlanId),icon:ChartNoAxesCombined,title:text.planVsActual,text:text.planVsActualText,signal:`${activeSuccessions} ${text.activeInScope}`},{href:withGamePlanQuery("/orchard/commercial",selectedPlanId),icon:FileText,title:text.commercial,text:text.commercialText,signal:`${openCommitments} ${text.openCommitments}`},{href:withGamePlanQuery("/orchard/decisions",selectedPlanId),icon:ShieldAlert,title:text.decisions,text:text.decisionsText,signal:`${highCritical} ${text.highCritical}`},{href:withGamePlanQuery("/orchard/charts",selectedPlanId),icon:BarChart3,title:text.charts,text:text.chartsText,signal:`${sharedCharts}/${charts.length} ${text.sharedGlobal}`},{href:withGamePlanQuery("/orchard/analytics",selectedPlanId),icon:BookOpenText,title:text.notesInsights,text:text.notesInsightsText,signal:`${scopedNotes.length} ${text.notesInScope}`}]
 return <AppLayout><OrchardNavigation/><PageHeader title={text.reports} description={selectedPlan?fill(text.selectedDescription,{scope:scopeLabel}):text.globalDescription} actions={<div className="flex flex-wrap items-center gap-2"><Select value={selectedPlanId} onValueChange={changePlan}><SelectTrigger className="w-[250px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value={ALL_GAME_PLANS}>{text.allRecords}</SelectItem>{plans.map(plan=><SelectItem key={plan.id} value={plan.id}>{plan.name}{plan.season?` · ${plan.season}`:""}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>{text.refresh}</Button></div>}/><div className="space-y-6 p-4 pb-24 sm:p-8">{error&&<Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
 <section className="relative min-h-[300px] overflow-hidden border border-white/10 bg-[#111711] p-6 md:p-8"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,12,9,.97),rgba(8,12,9,.77),rgba(8,12,9,.2)),url('https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=2200&q=92')] bg-cover bg-center [filter:none] [opacity:1]"/><div className="relative z-10 max-w-3xl"><p className="text-xs uppercase tracking-[.2em] text-emerald-200/70">{selectedPlan?text.gamePlanReporting:text.reportingLayer}</p><h2 className="mt-3 text-3xl md:text-5xl">{selectedPlan?scopeLabel:text.narrative}</h2><p className="mt-4 max-w-2xl text-sm text-white/70">{selectedPlan?fill(text.formalRange,{start:selectedPlan.start_date,end:selectedPlan.end_date}):text.globalNarrative}</p><div className="mt-6 grid max-w-2xl grid-cols-2 gap-3 md:grid-cols-4"><HeroMetric label={text.activeCrops} value={String(activeCrops)}/><HeroMetric label={text.recordedHarvestValue} value={number(harvestValue)}/><HeroMetric label={text.notes} value={String(scopedNotes.length)}/><HeroMetric label={text.savedCharts} value={String(charts.length)}/></div></div></section>
 <Card><CardHeader><CardTitle>{text.closeout}</CardTitle><CardDescription>{selectedPlan?text.selectedPackage:text.globalPackage}</CardDescription></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{modules.map(({href,icon:Icon,title,text:moduleText,signal})=><Link key={href} href={`/${language}${href}`} className="group block border border-white/10 bg-[var(--bs-surface-secondary)] p-5 transition hover:bg-[var(--bs-surface-elevated)]"><div className="flex items-center justify-between gap-3"><div className="bg-muted p-2"><Icon className="h-5 w-5"/></div><span className="text-xs text-muted-foreground">{signal}</span></div><p className="mt-5 text-lg font-semibold">{title}</p><p className="mt-2 text-sm text-muted-foreground">{moduleText}</p><p className="mt-5 text-xs uppercase tracking-wider text-foreground/60 group-hover:text-foreground">{text.openReport}</p></Link>)}</div></CardContent></Card>
 </div></AppLayout>}
function HeroMetric({label,value}:{label:string;value:string}){return <div className="border border-white/15 bg-black/20 p-3"><p className="text-[10px] uppercase tracking-wider text-white/50">{label}</p><p className="mt-1 text-lg font-semibold text-white">{value}</p></div>}
