"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { BarChart3, BookOpenText, ChartNoAxesCombined, FileText, Leaf, RefreshCw, ShieldAlert, Sprout } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Crop={id:string;status:string}
type Succession={id:string;status:string}
type Harvest={id:string;total_market_value:number|null;quantity_harvested:number|null;market_value_per_unit:number|null}
type Note={id:string;note_type:string}
type Health={id:string;severity_level:string|null;treatment_effectiveness:string|null}
type ChartDef={id:string;is_shared:boolean}
type Commitment={id:string;status:string}

const number=(value:number)=>new Intl.NumberFormat("es-CL",{maximumFractionDigits:2}).format(value)

export default function OrchardReportsPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const es=language==="es"
 const [crops,setCrops]=useState<Crop[]>([]);const [successions,setSuccessions]=useState<Succession[]>([]);const [harvests,setHarvests]=useState<Harvest[]>([]);const [notes,setNotes]=useState<Note[]>([]);const [health,setHealth]=useState<Health[]>([]);const [charts,setCharts]=useState<ChartDef[]>([]);const [commitments,setCommitments]=useState<Commitment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);const [c,s,h,n,he,ch,cm]=await Promise.all([supabase.from("orchard_crops").select("id,status"),supabase.from("orchard_crop_successions").select("id,status"),supabase.from("orchard_harvest_records").select("id,total_market_value,quantity_harvested,market_value_per_unit"),supabase.from("orchard_notes").select("id,note_type"),supabase.from("orchard_pest_logs").select("id,severity_level,treatment_effectiveness"),supabase.from("orchard_chart_definitions").select("id,is_shared"),supabase.from("orchard_sales_commitments").select("id,status")]);const e=c.error??s.error??h.error??n.error??he.error??ch.error??cm.error;if(e)setError(e.message);else{setCrops((c.data??[]) as Crop[]);setSuccessions((s.data??[]) as Succession[]);setHarvests((h.data??[]) as Harvest[]);setNotes((n.data??[]) as Note[]);setHealth((he.data??[]) as Health[]);setCharts((ch.data??[]) as ChartDef[]);setCommitments((cm.data??[]) as Commitment[])}setLoading(false)},[supabase]);useEffect(()=>{void load()},[load])
 const harvestValue=harvests.reduce((sum,h)=>sum+Number(h.total_market_value??((h.quantity_harvested??0)*(h.market_value_per_unit??0))),0);const openHealth=health.filter(h=>["high","critical"].includes((h.severity_level??"").toLowerCase())&&!['effective','very_effective'].includes((h.treatment_effectiveness??"").toLowerCase())).length;const activeCrops=crops.filter(c=>!["harvested","failed","completed"].includes((c.status??"").toLowerCase())).length;const activeSuccessions=successions.filter(s=>!["completed","cancelled"].includes((s.status??"").toLowerCase())).length;const sharedCharts=charts.filter(c=>c.is_shared).length;const openCommitments=commitments.filter(c=>!["fulfilled","cancelled"].includes((c.status??"").toLowerCase())).length
 const modules=[{href:"/orchard/season-summary",icon:Leaf,title:es?"Resumen de Temporada":"Season Summary",text:es?"Cierre ejecutivo: ejecución, cosecha, valor registrado, incidentes y aprendizaje.":"Executive close: execution, harvest, recorded value, incidents and learning.",signal:`${harvests.length} ${es?"pases de cosecha":"harvest passes"}`},{href:"/orchard/traceability",icon:Sprout,title:es?"Trazabilidad":"Traceability",text:es?"Cadena completa por sucesión desde vivero hasta cosecha.":"Full succession lineage from nursery through harvest.",signal:`${successions.length} ${es?"sucesiones":"successions"}`},{href:"/orchard/performance",icon:ChartNoAxesCombined,title:es?"Plan vs Real":"Plan vs Actual",text:es?"Fechas y volumen planificado comparados con ejecución real.":"Planned timing and volume compared with real execution.",signal:`${activeSuccessions} ${es?"activas":"active"}`},{href:"/orchard/commercial",icon:FileText,title:es?"Comercial":"Commercial",text:es?"Demanda, compromisos, objetivos y valor registrado.":"Demand, commitments, targets and recorded value.",signal:`${openCommitments} ${es?"compromisos abiertos":"open commitments"}`},{href:"/orchard/decisions",icon:ShieldAlert,title:es?"Decisiones":"Decisions",text:es?"Excepciones operativas determinísticas y accionables.":"Deterministic, actionable operational exceptions.",signal:`${openHealth} ${es?"observaciones sanitarias de seguimiento":"health follow-ups"}`},{href:"/orchard/charts",icon:BarChart3,title:es?"Gráficos":"Custom Charts",text:es?"Vistas guardadas sobre datos canónicos de Orchard.":"Saved views over canonical Orchard data.",signal:`${sharedCharts}/${charts.length} ${es?"compartidos":"shared"}`},{href:"/orchard/analytics",icon:BookOpenText,title:es?"Notas e Insights":"Notes & Insights",text:es?"Journal de campo, señales y aprendizaje operativo.":"Field journal, signals and operational learning.",signal:`${notes.length} ${es?"notas":"notes"}`}]
 return <AppLayout><PageHeader title={es?"Reportes":"Reports"} description={es?"Centro ejecutivo para revisar, explicar y cerrar la operación Orchard usando datos canónicos, no reporting duplicado.":"Executive hub to review, explain and close Orchard operations using canonical data, not duplicated reporting tables."} actions={<Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>{es?"Actualizar":"Refresh"}</Button>}/><OrchardNavigation/><div className="space-y-6 p-4 pb-24 sm:p-8">{error&&<Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
 <section className="relative min-h-[300px] overflow-hidden border border-white/10 bg-[#111711] p-6 md:p-8"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,12,9,.97),rgba(8,12,9,.77),rgba(8,12,9,.2)),url('https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=2200&q=92')] bg-cover bg-center [filter:none] [opacity:1]"/><div className="relative z-10 max-w-3xl"><p className="text-xs uppercase tracking-[.2em] text-emerald-200/70">{es?"Orchard reporting layer":"Orchard reporting layer"}</p><h2 className="mt-3 text-3xl md:text-5xl">{es?"Una sola narrativa desde el plan hasta el resultado.":"One narrative from plan to outcome."}</h2><p className="mt-4 max-w-2xl text-sm text-white/70">{es?"Cada reporte vuelve a los mismos registros operativos que usa el equipo. El valor de cosecha se muestra sin símbolo monetario porque el registro de cosecha no guarda moneda.":"Every report resolves back to the same operational records used by the team. Harvest value is shown without a currency symbol because harvest records do not store currency."}</p><div className="mt-6 grid max-w-2xl grid-cols-2 gap-3 md:grid-cols-4"><HeroMetric label={es?"Cultivos activos":"Active crops"} value={String(activeCrops)}/><HeroMetric label={es?"Valor cosecha registrado":"Recorded harvest value"} value={number(harvestValue)}/><HeroMetric label={es?"Notas":"Notes"} value={String(notes.length)}/><HeroMetric label={es?"Vistas guardadas":"Saved charts"} value={String(charts.length)}/></div></div></section>
 <Card><CardHeader><CardTitle>{es?"Paquete de cierre":"Closeout package"}</CardTitle><CardDescription>{es?"Las siete vistas que explican la temporada desde perspectivas complementarias.":"Seven complementary views that explain the season."}</CardDescription></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{modules.map(({href,icon:Icon,title,text,signal})=><Link key={href} href={`/${language}${href}`} className="group block border border-white/10 bg-[var(--bs-surface-secondary)] p-5 transition hover:bg-[var(--bs-surface-elevated)]"><div className="flex items-center justify-between gap-3"><div className="bg-muted p-2"><Icon className="h-5 w-5"/></div><span className="text-xs text-muted-foreground">{signal}</span></div><p className="mt-5 text-lg font-semibold">{title}</p><p className="mt-2 text-sm text-muted-foreground">{text}</p><p className="mt-5 text-xs uppercase tracking-wider text-foreground/60 group-hover:text-foreground">{es?"Abrir reporte →":"Open report →"}</p></Link>)}</div></CardContent></Card>
 </div></AppLayout>}
function HeroMetric({label,value}:{label:string;value:string}){return <div className="border border-white/15 bg-black/20 p-3"><p className="text-[10px] uppercase tracking-wider text-white/50">{label}</p><p className="mt-1 text-lg font-semibold text-white">{value}</p></div>}
