"use client"

import { useEffect, useMemo, useState, type ReactNode } from "react"
import { CalendarRange, ChartNoAxesCombined, Leaf, Target } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Plan={id:string;name:string;season:string|null;start_date:string;end_date:string;status:string}
type Cycle={id:string;game_plan_id:string;crop_name:string;variety:string|null;target_quantity:number|null;target_unit:string|null}
type Succession={id:string;crop_cycle_id:string;sequence_no:number;planned_bed_m:number|null;planned_first_harvest_date:string|null;planned_last_harvest_date:string|null}
type RevenueTarget={crop_succession_id:string;planned_revenue:number|null}
type Window={id:string;crop:string;variety:string|null;sequence:number;bedMeters:number;first:string;last:string;targetQuantity:number|null;targetUnit:string|null;hasRevenueTarget:boolean}

const copy={
 en:{eyebrow:"Production Forecast",title:"Planned availability by harvest window",description:"Operational forecast for the plantings reconciled with Crop Map. Canonical harvest dates and recorded production targets are shown without inventing weekly volumes or revenue.",season:"Season",windows:"Reconciled harvest windows",months:"Months with coverage",crops:"Crops with harvest windows",coverage:"Availability coverage",upcoming:"Planned harvest windows",target:"Season target",noTarget:"No production target recorded",bedMeters:"Bed m",financial:"Financial target",financialMissing:"Not recorded",financialRecorded:"Recorded",empty:"No reconciled harvest windows are recorded for this Game Plan.",method:"Method: only successions with canonical bed-meter requirements are included. A month is covered when at least one reconciled planting has a harvest window overlapping that month.",financialNotice:"Revenue targets are still pending. Production targets exist, but no CLP revenue targets are stored for the reconciled plantings; the forecast therefore does not calculate invented sales values."},
 es:{eyebrow:"Forecast de Producción",title:"Disponibilidad planificada por ventana de cosecha",description:"Forecast operacional de las plantaciones reconciliadas con Crop Map. Se muestran fechas de cosecha y objetivos productivos registrados, sin inventar volúmenes semanales ni ingresos.",season:"Temporada",windows:"Ventanas reconciliadas",months:"Meses con cobertura",crops:"Cultivos con ventana",coverage:"Cobertura de disponibilidad",upcoming:"Ventanas de cosecha planificadas",target:"Objetivo de temporada",noTarget:"Sin objetivo productivo registrado",bedMeters:"m de cama",financial:"Meta financiera",financialMissing:"No registrada",financialRecorded:"Registrada",empty:"No hay ventanas de cosecha reconciliadas para este Plan de Cultivo.",method:"Método: sólo se incluyen sucesiones con requerimiento canónico en metros de cama. Un mes tiene cobertura cuando al menos una plantación reconciliada tiene una ventana de cosecha que se superpone con ese mes.",financialNotice:"Las metas de ingreso siguen pendientes. Existen objetivos productivos, pero no hay metas de ingreso CLP registradas para las plantaciones reconciliadas; por eso el forecast no calcula ventas inventadas."},
 de:{eyebrow:"Produktionsprognose",title:"Geplante Verfügbarkeit nach Erntefenster",description:"Betriebsprognose für die mit Crop Map abgeglichenen Pflanzungen. Kanonische Erntedaten und erfasste Produktionsziele werden ohne erfundene Wochenmengen oder Erlöse gezeigt.",season:"Saison",windows:"Abgeglichene Erntefenster",months:"Monate mit Abdeckung",crops:"Kulturen mit Erntefenster",coverage:"Verfügbarkeitsabdeckung",upcoming:"Geplante Erntefenster",target:"Saisonziel",noTarget:"Kein Produktionsziel erfasst",bedMeters:"Beetmeter",financial:"Finanzziel",financialMissing:"Nicht erfasst",financialRecorded:"Erfasst",empty:"Für diesen Game Plan sind keine abgeglichenen Erntefenster vorhanden.",method:"Methode: Es werden nur Folgen mit kanonischem Beetmeterbedarf berücksichtigt. Ein Monat ist abgedeckt, wenn mindestens eine abgeglichene Pflanzung ein überlappendes Erntefenster hat.",financialNotice:"Umsatzziele stehen noch aus. Produktionsziele sind vorhanden, aber für die abgeglichenen Pflanzungen sind keine CLP-Umsatzziele gespeichert; daher werden keine erfundenen Umsätze berechnet."},
} as const

const locales:Record<Locale,string>={en:"en-US",es:"es-CL",de:"de-DE"}
const dateLabel=(v:string,locale:string)=>new Date(`${v}T12:00:00`).toLocaleDateString(locale,{day:"2-digit",month:"short",year:"numeric"})
const monthKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`
const monthLabel=(key:string,locale:string)=>new Date(`${key}-01T12:00:00`).toLocaleDateString(locale,{month:"short",year:"2-digit"})
function coveredMonths(first:string,last:string){const out:string[]=[];const start=new Date(`${first}T12:00:00`);const end=new Date(`${last}T12:00:00`);const cursor=new Date(start.getFullYear(),start.getMonth(),1,12);while(cursor<=end){out.push(monthKey(cursor));cursor.setMonth(cursor.getMonth()+1)}return out}

export default function OrchardForecastPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const lang:Locale=language;const text=copy[lang];const locale=locales[lang]
 const [plans,setPlans]=useState<Plan[]>([]),[cycles,setCycles]=useState<Cycle[]>([]),[successions,setSuccessions]=useState<Succession[]>([]),[revenueTargets,setRevenueTargets]=useState<RevenueTarget[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 useEffect(()=>{let live=true;void Promise.all([
  supabase.from("orchard_game_plans").select("id,name,season,start_date,end_date,status").order("start_date",{ascending:false}),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name,variety,target_quantity,target_unit"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id,sequence_no,planned_bed_m,planned_first_harvest_date,planned_last_harvest_date").not("planned_bed_m","is",null).neq("status","cancelled"),
  supabase.from("orchard_revenue_targets").select("crop_succession_id,planned_revenue"),
 ]).then(([p,c,s,r])=>{if(!live)return;const first=p.error??c.error??s.error??r.error;if(first){setError(first.message);setLoading(false);return}setPlans((p.data??[]) as Plan[]);setCycles((c.data??[]) as Cycle[]);setSuccessions((s.data??[]) as Succession[]);setRevenueTargets((r.data??[]) as RevenueTarget[]);setLoading(false)});return()=>{live=false}},[supabase])
 const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null
 const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.season==="2026/27")??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const scopedCycles=plan?cycles.filter(c=>c.game_plan_id===plan.id):[];const cycleById=new Map(scopedCycles.map(c=>[c.id,c]));const revenueIds=new Set(revenueTargets.map(r=>r.crop_succession_id));const scoped=successions.filter(s=>cycleById.has(s.crop_cycle_id)&&Number(s.planned_bed_m)>0&&s.planned_first_harvest_date&&s.planned_last_harvest_date)
 const windows:Window[]=scoped.map(s=>{const cycle=cycleById.get(s.crop_cycle_id)!;return{id:s.id,crop:cycle.crop_name,variety:cycle.variety,sequence:s.sequence_no,bedMeters:Number(s.planned_bed_m),first:s.planned_first_harvest_date!,last:s.planned_last_harvest_date!,targetQuantity:cycle.target_quantity,targetUnit:cycle.target_unit,hasRevenueTarget:revenueIds.has(s.id)}}).sort((a,b)=>a.first.localeCompare(b.first))
 const monthMap=new Map<string,Set<string>>();for(const w of windows){for(const month of coveredMonths(w.first,w.last)){const crops=monthMap.get(month)??new Set<string>();crops.add(w.crop);monthMap.set(month,crops)}}
 const months=[...monthMap.entries()].sort(([a],[b])=>a.localeCompare(b));const cropsWithWindows=new Set(windows.map(w=>w.crop)).size;const financialTargets=windows.filter(w=>w.hasRevenueTarget).length
 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1360px] px-4 py-8 sm:px-6 lg:px-8">
  <header className="mb-8 max-w-4xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-[var(--orchard-green)]">{text.eyebrow}</p><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-normal sm:text-4xl">{text.title}</h1>{plan?.season?<Badge variant="secondary">{plan.season}</Badge>:null}</div><p className="mt-3 text-sm leading-6 text-muted-foreground sm:text-base">{text.description}</p></header>
  {loading?<div className="py-12 text-sm text-muted-foreground">…</div>:error?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>:windows.length===0?<div className="py-12 text-sm text-muted-foreground">{text.empty}</div>:<>
   <section className="mb-6 grid overflow-hidden rounded-xl border border-[var(--orchard-line)] bg-white sm:grid-cols-4"><Metric icon={<CalendarRange className="h-4 w-4"/>} label={text.windows} value={String(windows.length)}/><Metric icon={<ChartNoAxesCombined className="h-4 w-4"/>} label={text.months} value={String(months.length)}/><Metric icon={<Leaf className="h-4 w-4"/>} label={text.crops} value={String(cropsWithWindows)}/><Metric icon={<Target className="h-4 w-4"/>} label={text.financial} value={`${financialTargets}/${windows.length}`}/></section>
   {financialTargets===0?<div className="mb-8 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">{text.financialNotice}</div>:null}
   <section className="mb-8 rounded-xl border border-[var(--orchard-line)] bg-white p-5 sm:p-6"><h2 className="text-xl font-normal">{text.coverage}</h2><div className="mt-5 grid gap-px overflow-hidden rounded-lg bg-[var(--orchard-line)] sm:grid-cols-3 lg:grid-cols-6">{months.map(([month,crops])=><div key={month} className="bg-[#fafbf9] p-4"><p className="text-sm font-medium">{monthLabel(month,locale)}</p><p className="mt-1 text-2xl tabular-nums">{crops.size}</p><p className="text-xs text-muted-foreground">{text.crops.toLowerCase()}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-muted-foreground">{text.method}</p></section>
   <section><h2 className="mb-4 text-xl font-normal">{text.upcoming}</h2><div className="space-y-2">{windows.map(w=><article key={w.id} className="grid gap-3 rounded-xl border border-[var(--orchard-line)] bg-white p-4 md:grid-cols-[1.25fr_.55fr_.8fr_.7fr_.85fr_.85fr]"><div><strong className="font-medium">{w.crop}</strong>{w.variety?<span className="ml-2 text-sm text-muted-foreground">{w.variety}</span>:null}<p className="mt-1 text-xs text-muted-foreground">Succession {w.sequence}</p></div><Cell label={text.bedMeters} value={`${w.bedMeters} m`}/><Cell label={text.target} value={w.targetQuantity!=null?`${w.targetQuantity.toLocaleString(locale)} ${w.targetUnit??""}`:text.noTarget}/><Cell label={text.financial} value={w.hasRevenueTarget?text.financialRecorded:text.financialMissing}/><Cell label="Start" value={dateLabel(w.first,locale)}/><Cell label="End" value={dateLabel(w.last,locale)}/></article>)}</div></section>
  </>}
 </main></AppLayout>
}

function Metric({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="p-5">{icon}<p className="mt-4 text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-3xl tabular-nums">{value}</p></div>}
function Cell({label,value}:{label:string;value:string}){return <div><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm">{value}</p></div>}
