"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Circle, CloudSun, Download, Filter, SlidersHorizontal } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Status="nueva"|"en_progreso"|"completada"|"cancelada"
type Task={id:string;title:string;description:string|null;priority:string;status:Status;due_date:string|null;location_name:string|null;task_category:string|null;estimated_minutes:number|null;source_label:string|null}
type Assignment={task_id:string;employee_id:string|null}
type Employee={id:string;name:string}
type ViewDensity="comfortable"|"compact"
type WeatherSettings={latitude:number|null;longitude:number|null;temperature_unit:"celsius"|"fahrenheit";weather_provider:string;weather_timezone:string;weather_enabled:boolean}
type WeatherDay={date:string;code:number;max:number;min:number;pop:number|null}
type OpenMeteoDaily={time?:string[];weather_code?:number[];temperature_2m_max?:number[];temperature_2m_min?:number[];precipitation_probability_max?:(number|null)[]}
type OpenMeteoPayload={daily?:OpenMeteoDaily}

const copy={
 en:{eyebrow:"Orchard · Week Board",title:"Tasks",description:"Canonical Orchard work by week, with source-backed Black Swan weather. Filters, display controls and export operate only on tasks visible under the current Orchard access scope.",today:"Today",prev:"Previous week",next:"Next week",week:"Week",search:"Search tasks…",filters:"Filters",display:"Display options",export:"Export",status:"Status",all:"All",open:"Open",completed:"Completed",owner:"Owner",location:"Location",category:"Category",unassigned:"Unassigned",allOwners:"All owners",allLocations:"All locations",allCategories:"All categories",density:"Density",comfortable:"Comfortable",compact:"Compact",showOwner:"Show owner",showSource:"Show source",empty:"No Orchard tasks match this day.",minutes:"min",loadError:"Could not load Orchard tasks.",weatherError:"Weather unavailable for this date.",weatherSource:"Weather · Open-Meteo",pop:"PoP",csv:"orchard-week-board"},
 es:{eyebrow:"Huerto · Week Board",title:"Tareas",description:"Trabajo canónico de Huerto por semana, con clima de Black Swan respaldado por fuente. Filtros, visualización y exportación operan sólo sobre tareas visibles según el alcance Orchard actual.",today:"Hoy",prev:"Semana anterior",next:"Semana siguiente",week:"Semana",search:"Buscar tareas…",filters:"Filtros",display:"Opciones de visualización",export:"Exportar",status:"Estado",all:"Todos",open:"Abiertas",completed:"Completadas",owner:"Responsable",location:"Ubicación",category:"Categoría",unassigned:"Sin asignar",allOwners:"Todos los responsables",allLocations:"Todas las ubicaciones",allCategories:"Todas las categorías",density:"Densidad",comfortable:"Cómoda",compact:"Compacta",showOwner:"Mostrar responsable",showSource:"Mostrar fuente",empty:"No hay tareas Orchard para este día con los filtros actuales.",minutes:"min",loadError:"No fue posible cargar las tareas Orchard.",weatherError:"Clima no disponible para esta fecha.",weatherSource:"Clima · Open-Meteo",pop:"PoP",csv:"orchard-week-board"},
 de:{eyebrow:"Orchard · Wochenboard",title:"Aufgaben",description:"Kanonische Orchard-Arbeit pro Woche mit quellenbasiertem Black-Swan-Wetter. Filter, Anzeige und Export arbeiten nur mit Aufgaben im aktuellen Orchard-Zugriffsbereich.",today:"Heute",prev:"Vorherige Woche",next:"Nächste Woche",week:"Woche",search:"Aufgaben suchen…",filters:"Filter",display:"Anzeigeoptionen",export:"Export",status:"Status",all:"Alle",open:"Offen",completed:"Abgeschlossen",owner:"Verantwortlich",location:"Ort",category:"Kategorie",unassigned:"Nicht zugewiesen",allOwners:"Alle Verantwortlichen",allLocations:"Alle Orte",allCategories:"Alle Kategorien",density:"Dichte",comfortable:"Komfortabel",compact:"Kompakt",showOwner:"Verantwortliche anzeigen",showSource:"Quelle anzeigen",empty:"Keine Orchard-Aufgaben für diesen Tag mit den aktuellen Filtern.",minutes:"Min",loadError:"Orchard-Aufgaben konnten nicht geladen werden.",weatherError:"Wetter für dieses Datum nicht verfügbar.",weatherSource:"Wetter · Open-Meteo",pop:"PoP",csv:"orchard-week-board"}
} as const
const locales:Record<Locale,string>={en:"en-US",es:"es-CL",de:"de-DE"}
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`
const parseDate=(value:string)=>new Date(`${value}T12:00:00`)
const mondayOf=(date:Date)=>{const d=new Date(date);d.setDate(d.getDate()-((d.getDay()+6)%7));d.setHours(12,0,0,0);return d}
const addDays=(date:Date,days:number)=>{const d=new Date(date);d.setDate(d.getDate()+days);return d}
const csvEscape=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`
const weatherLabel=(code:number,lang:Locale)=>{const labels={en:{clear:"Clear",cloud:"Cloudy",fog:"Fog",rain:"Rain",snow:"Snow",storm:"Storm"},es:{clear:"Despejado",cloud:"Nublado",fog:"Niebla",rain:"Lluvia",snow:"Nieve",storm:"Tormenta"},de:{clear:"Klar",cloud:"Bewölkt",fog:"Nebel",rain:"Regen",snow:"Schnee",storm:"Gewitter"}}[lang];if(code===0)return labels.clear;if(code<=3)return labels.cloud;if(code<=48)return labels.fog;if(code<=67||code>=80&&code<=82)return labels.rain;if(code<=77||code>=85&&code<=86)return labels.snow;if(code>=95)return labels.storm;return labels.cloud}

export function OrchardWeekBoard(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const lang:Locale=language;const text=copy[lang];const locale=locales[lang]
 const [tasks,setTasks]=useState<Task[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[weather,setWeather]=useState<WeatherDay[]>([])
 const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(new Date()))
 const [search,setSearch]=useState(""),[status,setStatus]=useState("all"),[owner,setOwner]=useState("all"),[location,setLocation]=useState("all"),[category,setCategory]=useState("all")
 const [filtersOpen,setFiltersOpen]=useState(false),[displayOpen,setDisplayOpen]=useState(false),[density,setDensity]=useState<ViewDensity>("comfortable"),[showOwner,setShowOwner]=useState(true),[showSource,setShowSource]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError(null);const [t,e,w]=await Promise.all([
  supabase.from("tasks").select("id,title,description,priority,status,due_date,location_name,task_category,estimated_minutes,source_label").in("operational_area",["orchard","huerto_vinedo"]).order("due_date",{ascending:true,nullsFirst:false}),
  supabase.from("employees").select("id,name").eq("is_active",true).order("name"),
  supabase.from("orchard_farm_settings").select("latitude,longitude,temperature_unit,weather_provider,weather_timezone,weather_enabled").eq("farm_key","black_swan_orchard").single(),
 ]);if(t.error||e.error||w.error){setError(`${text.loadError} ${(t.error??e.error??w.error)?.message??""}`);setLoading(false);return}const next=(t.data??[]) as Task[];let a:Assignment[]=[];if(next.length){const ar=await supabase.from("task_assignments").select("task_id,employee_id").in("task_id",next.map(item=>item.id));if(ar.error){setError(`${text.loadError} ${ar.error.message}`);setLoading(false);return}a=(ar.data??[]) as Assignment[]}setTasks(next);setAssignments(a);setEmployees((e.data??[]) as Employee[])
  const config=w.data as WeatherSettings;if(config.weather_enabled&&config.weather_provider==="open_meteo"&&config.latitude!=null&&config.longitude!=null){try{const unit=config.temperature_unit==="fahrenheit"?"fahrenheit":"celsius";const params=new URLSearchParams({latitude:String(config.latitude),longitude:String(config.longitude),daily:"weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max",temperature_unit:unit,timezone:config.weather_timezone||"America/Santiago",past_days:"7",forecast_days:"16"});const response=await fetch(`https://api.open-meteo.com/v1/forecast?${params.toString()}`);if(response.ok){const payload=await response.json() as OpenMeteoPayload;const d=payload.daily;const rows=(d?.time??[]).map((date,i)=>({date,code:d?.weather_code?.[i]??-1,max:d?.temperature_2m_max?.[i]??NaN,min:d?.temperature_2m_min?.[i]??NaN,pop:d?.precipitation_probability_max?.[i]??null}));setWeather(rows)}}catch{setWeather([])}}setLoading(false)},[supabase,text.loadError])
 useEffect(()=>{void load()},[load])
 const employeeById=useMemo(()=>new Map(employees.map(e=>[e.id,e.name])),[employees]);const ownersFor=(id:string)=>assignments.filter(a=>a.task_id===id&&a.employee_id).map(a=>employeeById.get(a.employee_id!)?.name).filter((v):v is string=>Boolean(v));const ownerLabel=(id:string)=>ownersFor(id).join(", ")||text.unassigned
 const weekDays=Array.from({length:7},(_,i)=>addDays(weekStart,i)),weekEnd=weekDays[6]
 const locations=useMemo(()=>[...new Set(tasks.map(t=>t.location_name).filter((v):v is string=>Boolean(v)))].sort(),[tasks]);const categories=useMemo(()=>[...new Set(tasks.map(t=>t.task_category).filter((v):v is string=>Boolean(v)))].sort(),[tasks]);const weatherByDate=useMemo(()=>new Map(weather.map(d=>[d.date,d])),[weather])
 const filtered=tasks.filter(task=>{const hay=[task.title,task.description,task.source_label,task.task_category,task.location_name,ownerLabel(task.id)].filter(Boolean).join(" ").toLowerCase();if(search.trim()&&!hay.includes(search.trim().toLowerCase()))return false;if(status==="open"&&(task.status==="completada"||task.status==="cancelada"))return false;if(status==="completed"&&task.status!=="completada")return false;if(owner!=="all"&&!ownersFor(task.id).includes(owner))return false;if(location!=="all"&&task.location_name!==location)return false;if(category!=="all"&&task.task_category!==category)return false;return true})
 const weekTasks=filtered.filter(t=>t.due_date&&t.due_date>=dateKey(weekStart)&&t.due_date<=dateKey(weekEnd))
 async function toggle(task:Task){const complete=task.status!=="completada";const r=await supabase.from("tasks").update({status:complete?"completada":"nueva",completed_at:complete?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",task.id);if(r.error)setError(r.error.message);else await load()}
 function exportCsv(){const rows=[["date","task","status","minutes","owner","location","category","source"],...weekTasks.map(t=>[t.due_date??"",t.title,t.status,t.estimated_minutes??"",ownerLabel(t.id),t.location_name??"",t.task_category??"",t.source_label??""])];const blob=new Blob([rows.map(row=>row.map(csvEscape).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${text.csv}-${dateKey(weekStart)}.csv`;a.click();URL.revokeObjectURL(url)}
 const weekLabel=`${weekStart.toLocaleDateString(locale,{day:"2-digit",month:"short"})} – ${weekEnd.toLocaleDateString(locale,{day:"2-digit",month:"short"})}`
 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1700px] px-4 pb-16 pt-7 sm:px-6 lg:px-8">
  <header className="border-b border-[var(--orchard-line)] pb-5"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--orchard-green)]">{text.eyebrow}</p><h1 className="mt-2 text-3xl font-normal">{text.title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{text.description}</p></header>
  <div className="mt-5 flex flex-wrap items-center gap-2"><Button variant="outline" onClick={()=>setWeekStart(mondayOf(new Date()))}>{text.today}</Button><Button variant="ghost" size="icon" aria-label={text.prev} onClick={()=>setWeekStart(addDays(weekStart,-7))}><ChevronLeft className="h-4 w-4"/></Button><Button variant="ghost" size="icon" aria-label={text.next} onClick={()=>setWeekStart(addDays(weekStart,7))}><ChevronRight className="h-4 w-4"/></Button><label className="flex items-center gap-2 border border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)] px-3 py-2 text-sm"><CalendarDays className="h-4 w-4 text-muted-foreground"/><span>{text.week}</span><input aria-label={text.week} type="date" value={dateKey(weekStart)} onChange={e=>e.target.value&&setWeekStart(mondayOf(parseDate(e.target.value)))} className="bg-transparent text-foreground outline-none"/></label><strong className="text-sm font-medium">{weekLabel}</strong><div className="ml-auto flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setFiltersOpen(v=>!v)}><Filter className="mr-2 h-4 w-4"/>{text.filters}</Button><Button variant="outline" onClick={()=>setDisplayOpen(v=>!v)}><SlidersHorizontal className="mr-2 h-4 w-4"/>{text.display}</Button><Button variant="outline" onClick={exportCsv} disabled={!weekTasks.length}><Download className="mr-2 h-4 w-4"/>{text.export}</Button></div></div>
  <div className="mt-3 grid gap-3 lg:grid-cols-[minmax(240px,1fr)_auto]"><Input aria-label={text.search} placeholder={text.search} value={search} onChange={e=>setSearch(e.target.value)}/><a href="https://open-meteo.com/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><CloudSun className="h-4 w-4"/>{text.weatherSource}</a></div>
  {filtersOpen&&<section className="mt-3 grid gap-3 border-y border-[var(--bs-divider-subtle)] py-4 sm:grid-cols-2 xl:grid-cols-4"><FilterSelect label={text.status} value={status} onChange={setStatus} options={[["all",text.all],["open",text.open],["completed",text.completed]]}/><FilterSelect label={text.owner} value={owner} onChange={setOwner} options={[["all",text.allOwners],...employees.map(e=>[e.name,e.name] as [string,string])]}/><FilterSelect label={text.location} value={location} onChange={setLocation} options={[["all",text.allLocations],...locations.map(v=>[v,v] as [string,string])]}/><FilterSelect label={text.category} value={category} onChange={setCategory} options={[["all",text.allCategories],...categories.map(v=>[v,v] as [string,string])]}/></section>}
  {displayOpen&&<section className="mt-3 flex flex-wrap items-center gap-6 border-y border-[var(--bs-divider-subtle)] py-4"><FilterSelect label={text.density} value={density} onChange={v=>setDensity(v as ViewDensity)} options={[["comfortable",text.comfortable],["compact",text.compact]]}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={showOwner} onChange={e=>setShowOwner(e.target.checked)}/>{text.showOwner}</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={showSource} onChange={e=>setShowSource(e.target.checked)}/>{text.showSource}</label></section>}
  {error&&<div className="mt-4 border border-red-400/30 p-3 text-sm text-red-300">{error}</div>}
  {loading?<div className="py-16 text-sm text-muted-foreground">…</div>:<section className="mt-5 grid gap-2 xl:grid-cols-7">{weekDays.map(day=>{const key=dateKey(day),dayTasks=weekTasks.filter(t=>t.due_date===key),mins=dayTasks.reduce((sum,t)=>sum+Number(t.estimated_minutes??0),0),wx=weatherByDate.get(key);return <article key={key} className="min-h-72 border border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)]"><div className="border-b border-[var(--bs-divider-subtle)] p-3"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">{day.toLocaleDateString(locale,{weekday:"long"})}</p><p className="mt-1 text-lg">{day.toLocaleDateString(locale,{day:"2-digit",month:"short"})}</p>{wx&&Number.isFinite(wx.max)&&Number.isFinite(wx.min)?<div className="mt-2 border-t border-[var(--bs-divider-subtle)] pt-2"><p className="text-xs font-medium">{weatherLabel(wx.code,lang)}</p><p className="mt-0.5 text-xs text-muted-foreground">{Math.round(wx.min)}° / {Math.round(wx.max)}°{wx.pop!=null?` · ${text.pop} ${wx.pop}%`:""}</p></div>:<p className="mt-2 text-[11px] text-muted-foreground">{text.weatherError}</p>}<p className="mt-2 text-xs text-muted-foreground">{mins} {text.minutes}</p></div><div className={density==="compact"?"space-y-1 p-2":"space-y-2 p-3"}>{dayTasks.length?dayTasks.map(task=><div key={task.id} className={density==="compact"?"border border-[var(--bs-divider-subtle)] p-2":"border border-[var(--bs-divider-subtle)] p-3"}><div className="flex items-start gap-2"><button aria-label={task.status==="completada"?text.completed:text.open} onClick={()=>void toggle(task)} className="mt-0.5 shrink-0 text-[var(--orchard-green)]">{task.status==="completada"?<CheckCircle2 className="h-4 w-4"/>:<Circle className="h-4 w-4"/>}</button><div className="min-w-0"><p className="text-sm font-medium leading-5">{task.title}</p><p className="mt-1 text-xs text-muted-foreground">{task.estimated_minutes?`${task.estimated_minutes} ${text.minutes}`:"—"}{showOwner?` · ${ownerLabel(task.id)}`:""}</p>{task.location_name&&<p className="mt-1 text-[11px] text-muted-foreground">{task.location_name}</p>}{showSource&&task.source_label&&<p className="mt-1 text-[10px] uppercase tracking-wide text-muted-foreground">{task.source_label}</p>}</div></div></div>):<p className="py-5 text-xs text-muted-foreground">{text.empty}</p>}</div></article>})}</section>}
 </main></AppLayout>
}
function FilterSelect({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:[string,string][]}){return <label className="block min-w-44"><span className="mb-1.5 block text-[10px] uppercase tracking-[.12em] text-muted-foreground">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label>}
