"use client"

import { useEffect, useMemo, useState } from "react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Mode="farm-data"|"team"
type Locale="en"|"es"|"de"
type Farm={farm_name:string;farm_address:string|null;farm_city:string|null;farm_state:string|null;country_code:string;measurement_system:string;standard_bed_width_cm:number;standard_bed_length_m:number;standard_path_width_cm:number;weather_timezone:string|null}
type Employee={id:string;name:string;email:string|null;role:string|null;is_active:boolean}
type Profile={employee_id:string;canonical_job_title:string|null;primary_operational_area:string|null;secondary_operational_areas:string[]|null;can_receive_tasks:boolean|null;confidence:string|null;requires_validation:boolean|null}
const copy={
 en:{farmTitle:"Farm data",farmHelp:"Canonical physical and operating data for Black Swan Orchard.",teamTitle:"Team",teamHelp:"People canonically associated with Orchard work. Roles shown here do not grant authorization.",farm:"Farm",address:"Address",country:"Country",units:"Units",timezone:"Timezone",beds:"Beds",plots:"Plots",mapObjects:"Map objects",bedWidth:"Standard bed width",bedLength:"Standard bed length",pathWidth:"Standard path width",name:"Name",role:"Role",area:"Operational area",taskReady:"Task ready",evidence:"Evidence",yes:"Yes",no:"No",validation:"Needs validation",none:"No canonical records available.",unknown:"—"},
 es:{farmTitle:"Datos de granja",farmHelp:"Datos físicos y operativos canónicos de Black Swan Orchard.",teamTitle:"Equipo",teamHelp:"Personas asociadas canónicamente al trabajo de Orchard. Los roles mostrados no otorgan autorización.",farm:"Granja",address:"Dirección",country:"País",units:"Unidades",timezone:"Zona horaria",beds:"Camas",plots:"Parcelas",mapObjects:"Objetos de mapa",bedWidth:"Ancho estándar de cama",bedLength:"Largo estándar de cama",pathWidth:"Ancho estándar de pasillo",name:"Nombre",role:"Rol",area:"Área operativa",taskReady:"Recibe tareas",evidence:"Evidencia",yes:"Sí",no:"No",validation:"Requiere validación",none:"No hay registros canónicos disponibles.",unknown:"—"},
 de:{farmTitle:"Hofdaten",farmHelp:"Kanonische physische und operative Daten für Black Swan Orchard.",teamTitle:"Team",teamHelp:"Personen, die kanonisch mit Orchard-Arbeit verbunden sind. Angezeigte Rollen erteilen keine Berechtigungen.",farm:"Hof",address:"Adresse",country:"Land",units:"Einheiten",timezone:"Zeitzone",beds:"Beete",plots:"Parzellen",mapObjects:"Kartenobjekte",bedWidth:"Standard-Beetbreite",bedLength:"Standard-Beetlänge",pathWidth:"Standard-Wegbreite",name:"Name",role:"Rolle",area:"Betriebsbereich",taskReady:"Aufgabenfähig",evidence:"Evidenz",yes:"Ja",no:"Nein",validation:"Validierung nötig",none:"Keine kanonischen Datensätze verfügbar.",unknown:"—"}
} as const
export function OrchardExactSettings({mode}:{mode:Mode}){
 const {language}=useLanguage();const t=copy[language as Locale];const supabase=useMemo(()=>createBrowserClient(),[]);const [farm,setFarm]=useState<Farm|null>(null);const [counts,setCounts]=useState({beds:0,plots:0,mapObjects:0});const [employees,setEmployees]=useState<Employee[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let live=true;void(async()=>{setLoading(true);setError(null);if(mode==="farm-data"){const [f,b,p,m]=await Promise.all([supabase.from("orchard_farm_settings").select("farm_name,farm_address,farm_city,farm_state,country_code,measurement_system,standard_bed_width_cm,standard_bed_length_m,standard_path_width_cm,weather_timezone").eq("farm_key","black_swan_orchard").single(),supabase.from("orchard_beds").select("id",{count:"exact",head:true}).eq("is_active",true),supabase.from("orchard_plots").select("id",{count:"exact",head:true}),supabase.from("orchard_farm_map_objects").select("id",{count:"exact",head:true})]);if(!live)return;const e=f.error??b.error??p.error??m.error;if(e)setError(e.message);else{setFarm(f.data as Farm);setCounts({beds:b.count??0,plots:p.count??0,mapObjects:m.count??0})}}else{const [e,p]=await Promise.all([supabase.from("employees").select("id,name,email,role,is_active").eq("is_active",true).order("name"),supabase.from("employee_task_profiles").select("employee_id,canonical_job_title,primary_operational_area,secondary_operational_areas,can_receive_tasks,confidence,requires_validation")]);if(!live)return;const x=e.error??p.error;if(x)setError(x.message);else{setEmployees((e.data??[]) as Employee[]);setProfiles((p.data??[]) as Profile[])}}setLoading(false)})();return()=>{live=false}},[mode,supabase])
 const people=useMemo(()=>{const map=new Map(employees.map(e=>[e.id,e]));return profiles.filter(p=>p.primary_operational_area==="orchard"||(p.secondary_operational_areas??[]).includes("orchard")).map(profile=>({profile,employee:map.get(profile.employee_id)})).filter(x=>x.employee)},[employees,profiles]);const title=mode==="farm-data"?t.farmTitle:t.teamTitle;const help=mode==="farm-data"?t.farmHelp:t.teamHelp
 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1180px] px-5 pb-20 pt-6 lg:px-8"><header className="border-b border-[var(--orchard-line)] pb-5"><h1 className="text-[30px] font-normal tracking-[-.03em]">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{help}</p></header>{error?<p className="mt-5 text-sm text-red-300">{error}</p>:null}{mode==="farm-data"&&farm?<div className="mt-7 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><section><h2 className="text-xl font-normal">{t.farm}</h2><div className="mt-4 divide-y divide-[var(--orchard-line-soft)] border-y border-[var(--orchard-line)]"><Info label={t.farm} value={farm.farm_name}/><Info label={t.address} value={[farm.farm_address,farm.farm_city,farm.farm_state].filter(Boolean).join(", ")||t.unknown}/><Info label={t.country} value={farm.country_code}/><Info label={t.units} value={farm.measurement_system}/><Info label={t.timezone} value={farm.weather_timezone||t.unknown}/><Info label={t.bedWidth} value={`${farm.standard_bed_width_cm} cm`}/><Info label={t.bedLength} value={`${farm.standard_bed_length_m} m`}/><Info label={t.pathWidth} value={`${farm.standard_path_width_cm} cm`}/></div></section><section><div className="grid grid-cols-3 gap-px overflow-hidden rounded border border-[var(--orchard-line)] bg-[var(--orchard-line)]"><Metric label={t.beds} value={counts.beds}/><Metric label={t.plots} value={counts.plots}/><Metric label={t.mapObjects} value={counts.mapObjects}/></div></section></div>:null}{mode==="team"?<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr>{[t.name,t.role,t.area,t.taskReady,t.evidence].map(h=><th key={h} className="border-b border-[var(--orchard-line)] px-3 py-3 text-left text-[11px] font-medium uppercase tracking-[.08em] text-muted-foreground">{h}</th>)}</tr></thead><tbody>{people.map(({employee,profile})=><tr key={profile.employee_id}><Td strong>{employee!.name}</Td><Td>{profile.canonical_job_title||employee!.role||t.unknown}</Td><Td>{profile.primary_operational_area||t.unknown}</Td><Td>{profile.requires_validation?t.validation:profile.can_receive_tasks?t.yes:t.no}</Td><Td>{profile.confidence||t.unknown}</Td></tr>)}</tbody></table>{!loading&&!people.length?<p className="py-10 text-center text-sm text-muted-foreground">{t.none}</p>:null}</div>:null}</main></AppLayout>
}
function Info({label,value}:{label:string;value:string}){return <div className="grid grid-cols-[190px_1fr] gap-4 py-3 text-sm"><span className="text-muted-foreground">{label}</span><span>{value}</span></div>};function Metric({label,value}:{label:string;value:number}){return <div className="bg-[#211e1a] p-5 text-center"><p className="text-3xl font-normal">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>};function Td({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <td className={`border-b border-[var(--orchard-line-soft)] px-3 py-3 ${strong?"font-medium text-[#eee9e1]":"text-[#c4bcb1]"}`}>{children}</td>}
