"use client"

import { useEffect, useMemo, useState } from "react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Mode = "collaborators" | "farms" | "sales-channels" | "task-management"
type Locale = "en" | "es" | "de"
type Employee = { id:string; name:string; email:string|null; role:string|null; is_active:boolean }
type Profile = { employee_id:string; canonical_job_title:string|null; primary_operational_area:string|null; secondary_operational_areas:string[]|null; can_receive_tasks:boolean|null; confidence:string|null; requires_validation:boolean|null }
type Farm = { id:string; farm_name:string; farm_address:string|null; farm_city:string|null; farm_state:string|null; country_code:string; measurement_system:string; weather_timezone:string|null }
type Channel = { id:string; name:string; channel_type:string|null; status:string|null; default_price_per_unit:number|null; default_unit:string|null; currency:string|null }
type Task = { task_category:string|null; status:string; estimated_minutes:number|null }

type TaskRow = { category:string; total:number; open:number; avg:number|null }

const copy = {
 en:{collaborators:"Collaborators",collaboratorsHelp:"People canonically associated with Orchard work through task profiles.",farms:"Farms",farmsHelp:"Farm records available to this Orchard implementation.",channels:"Sales Channels",channelsHelp:"Canonical sales channels used by Orchard commercial planning.",tasks:"Task Management",tasksHelp:"Observed task categories and estimates used by Orchard work. This view does not invent recurring templates.",name:"Name",role:"Role",area:"Area",status:"Status",confidence:"Evidence",farm:"Farm",address:"Address",country:"Country",units:"Units",timezone:"Timezone",type:"Type",price:"Default price",currency:"Currency",category:"Task",total:"Tasks",open:"Open",avg:"Avg. estimate",minutes:"min",active:"Active",inactive:"Inactive",ready:"Ready",validation:"Needs validation",none:"No canonical records available.",unclassified:"Unclassified",unknown:"—"},
 es:{collaborators:"Colaboradores",collaboratorsHelp:"Personas asociadas canónicamente al trabajo de Orchard mediante perfiles de tareas.",farms:"Granjas",farmsHelp:"Registros de granja disponibles para esta implementación de Orchard.",channels:"Canales de venta",channelsHelp:"Canales canónicos utilizados por la planificación comercial de Orchard.",tasks:"Gestión de tareas",tasksHelp:"Categorías y estimaciones observadas usadas por el trabajo de Orchard. Esta vista no inventa plantillas recurrentes.",name:"Nombre",role:"Rol",area:"Área",status:"Estado",confidence:"Evidencia",farm:"Granja",address:"Dirección",country:"País",units:"Unidades",timezone:"Zona horaria",type:"Tipo",price:"Precio por defecto",currency:"Moneda",category:"Tarea",total:"Tareas",open:"Abiertas",avg:"Estimación prom.",minutes:"min",active:"Activo",inactive:"Inactivo",ready:"Listo",validation:"Requiere validación",none:"No hay registros canónicos disponibles.",unclassified:"Sin clasificar",unknown:"—"},
 de:{collaborators:"Mitarbeitende",collaboratorsHelp:"Personen, die über Aufgabenprofile kanonisch mit Orchard-Arbeit verbunden sind.",farms:"Höfe",farmsHelp:"Hofdatensätze dieser Orchard-Implementierung.",channels:"Vertriebskanäle",channelsHelp:"Kanonische Vertriebskanäle für die Orchard-Vertriebsplanung.",tasks:"Aufgabenverwaltung",tasksHelp:"Beobachtete Aufgabenkategorien und Schätzwerte. Wiederkehrende Vorlagen werden nicht erfunden.",name:"Name",role:"Rolle",area:"Bereich",status:"Status",confidence:"Evidenz",farm:"Hof",address:"Adresse",country:"Land",units:"Einheiten",timezone:"Zeitzone",type:"Typ",price:"Standardpreis",currency:"Währung",category:"Aufgabe",total:"Aufgaben",open:"Offen",avg:"Ø Schätzung",minutes:"Min",active:"Aktiv",inactive:"Inaktiv",ready:"Bereit",validation:"Validierung nötig",none:"Keine kanonischen Datensätze verfügbar.",unclassified:"Nicht klassifiziert",unknown:"—"}
} as const

export function OrchardSettingsSection({mode}:{mode:Mode}){
 const {language}=useLanguage();const locale:Locale=language;const text=copy[locale];const supabase=useMemo(()=>createBrowserClient(),[])
 const [employees,setEmployees]=useState<Employee[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [farms,setFarms]=useState<Farm[]>([]);const [channels,setChannels]=useState<Channel[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let live=true;void (async()=>{setLoading(true);setError(null);if(mode==="collaborators"){const [e,p]=await Promise.all([supabase.from("employees").select("id,name,email,role,is_active").eq("is_active",true).order("name"),supabase.from("employee_task_profiles").select("employee_id,canonical_job_title,primary_operational_area,secondary_operational_areas,can_receive_tasks,confidence,requires_validation")]);if(!live)return;if(e.error||p.error)setError((e.error??p.error)?.message??"");else{setEmployees((e.data??[]) as Employee[]);setProfiles((p.data??[]) as Profile[])}}else if(mode==="farms"){const r=await supabase.from("orchard_farm_settings").select("id,farm_name,farm_address,farm_city,farm_state,country_code,measurement_system,weather_timezone").order("farm_name");if(!live)return;if(r.error)setError(r.error.message);else setFarms((r.data??[]) as Farm[])}else if(mode==="sales-channels"){const r=await supabase.from("orchard_sales_channels").select("id,name,channel_type,status,default_price_per_unit,default_unit,currency").order("name");if(!live)return;if(r.error)setError(r.error.message);else setChannels((r.data??[]) as Channel[])}else{const r=await supabase.from("tasks").select("task_category,status,estimated_minutes").in("operational_area",["orchard","huerto_vinedo"]);if(!live)return;if(r.error)setError(r.error.message);else setTasks((r.data??[]) as Task[])}setLoading(false)})();return()=>{live=false}},[mode,supabase])
 const orchardPeople=useMemo(()=>{const employeeById=new Map(employees.map(e=>[e.id,e]));return profiles.filter(p=>p.primary_operational_area==="orchard"||(p.secondary_operational_areas??[]).includes("orchard")).map(p=>({profile:p,employee:employeeById.get(p.employee_id)})).filter(row=>row.employee)},[employees,profiles])
 const taskRows=useMemo(()=>{const map=new Map<string,TaskRow>();for(const task of tasks){const category=task.task_category?.trim()||text.unclassified;const row=map.get(category)??{category,total:0,open:0,avg:null};row.total++;if(task.status!=="completada"&&task.status!=="cancelada")row.open++;const mins=tasks.filter(t=>(t.task_category?.trim()||text.unclassified)===category&&t.estimated_minutes!=null).map(t=>Number(t.estimated_minutes));row.avg=mins.length?Math.round(mins.reduce((a,b)=>a+b,0)/mins.length):null;map.set(category,row)}return [...map.values()].sort((a,b)=>b.total-a.total||a.category.localeCompare(b.category))},[tasks,text.unclassified])
 const title=mode==="collaborators"?text.collaborators:mode==="farms"?text.farms:mode==="sales-channels"?text.channels:text.tasks
 const help=mode==="collaborators"?text.collaboratorsHelp:mode==="farms"?text.farmsHelp:mode==="sales-channels"?text.channelsHelp:text.tasksHelp
 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1180px] px-5 pb-20 pt-6 lg:px-8"><header className="border-b border-[var(--orchard-line)] pb-5"><h1 className="text-[30px] font-normal tracking-[-.03em]">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{help}</p></header>{error?<p className="mt-5 text-sm text-red-300">{error}</p>:null}<div className="mt-6 overflow-x-auto">
 {mode==="collaborators"?<table className="w-full min-w-[760px] text-sm"><thead><tr><Th>{text.name}</Th><Th>{text.role}</Th><Th>{text.area}</Th><Th>{text.status}</Th><Th>{text.confidence}</Th></tr></thead><tbody>{orchardPeople.map(({employee,profile})=><tr key={profile.employee_id}><Td strong>{employee!.name}</Td><Td>{profile.canonical_job_title||employee!.role||text.unknown}</Td><Td>{profile.primary_operational_area||text.unknown}</Td><Td>{profile.requires_validation?text.validation:profile.can_receive_tasks?text.ready:text.inactive}</Td><Td>{profile.confidence||text.unknown}</Td></tr>)}</tbody></table>:null}
 {mode==="farms"?<table className="w-full min-w-[780px] text-sm"><thead><tr><Th>{text.farm}</Th><Th>{text.address}</Th><Th>{text.country}</Th><Th>{text.units}</Th><Th>{text.timezone}</Th></tr></thead><tbody>{farms.map(f=><tr key={f.id}><Td strong>{f.farm_name}</Td><Td>{[f.farm_address,f.farm_city,f.farm_state].filter(Boolean).join(", ")||text.unknown}</Td><Td>{f.country_code}</Td><Td>{f.measurement_system}</Td><Td>{f.weather_timezone||text.unknown}</Td></tr>)}</tbody></table>:null}
 {mode==="sales-channels"?<table className="w-full min-w-[760px] text-sm"><thead><tr><Th>{text.name}</Th><Th>{text.type}</Th><Th>{text.status}</Th><Th>{text.price}</Th><Th>{text.currency}</Th></tr></thead><tbody>{channels.map(c=><tr key={c.id}><Td strong>{c.name}</Td><Td>{c.channel_type||text.unknown}</Td><Td>{c.status||text.unknown}</Td><Td>{c.default_price_per_unit==null?text.unknown:`${c.default_price_per_unit} ${c.default_unit??""}`.trim()}</Td><Td>{c.currency||text.unknown}</Td></tr>)}</tbody></table>:null}
 {mode==="task-management"?<table className="w-full min-w-[720px] text-sm"><thead><tr><Th>{text.category}</Th><Th>{text.total}</Th><Th>{text.open}</Th><Th>{text.avg}</Th></tr></thead><tbody>{taskRows.map(r=><tr key={r.category}><Td strong>{r.category}</Td><Td>{r.total}</Td><Td>{r.open}</Td><Td>{r.avg==null?text.unknown:`${r.avg} ${text.minutes}`}</Td></tr>)}</tbody></table>:null}
 {!loading&&((mode==="collaborators"&&!orchardPeople.length)||(mode==="farms"&&!farms.length)||(mode==="sales-channels"&&!channels.length)||(mode==="task-management"&&!taskRows.length))?<p className="py-10 text-center text-sm text-muted-foreground">{text.none}</p>:null}</div></main></AppLayout>
}
function Th({children}:{children:React.ReactNode}){return <th className="border-b border-[var(--orchard-line)] px-3 py-3 text-left text-[11px] font-medium uppercase tracking-[.08em] text-muted-foreground">{children}</th>}
function Td({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <td className={`border-b border-[var(--orchard-line-soft)] px-3 py-3 ${strong?"font-medium text-[#eee9e1]":"text-[#c4bcb1]"}`}>{children}</td>}
