"use client"

import { useEffect, useMemo, useState } from "react"
import { ArrowUpDown, Download, Search, SlidersHorizontal } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Mode="direct-seeding"|"transplantation"|"nursery"|"seeders"|"crop-yield"
type Locale="en"|"es"|"de"
type Crop={id:string;crop_name:string;crop_family:string|null;default_cycle_type:string|null;days_to_maturity:number|null;nursery_days:number|null;plant_spacing_cm:number|null;row_spacing_cm:number|null;germination_rate_pct:number|null;seeds_per_plant:number|null;target_yield_per_sqm:number|null;yield_unit:string|null;provenance_type:string|null;observed_count:number|null}
type Direct={id:string;crop_library_id:string;seeding_method:string|null;seeder_name:string|null;rows_per_bed:number|null;row_spacing_cm:number|null;plant_spacing_cm:number|null;calibration_setting:string|null;demand_value:number|null;demand_unit:string|null;reference_bed_m:number|null;provenance_type:string|null;conflict_status:string|null}
type FarmBed={standard_bed_width_cm:number;standard_bed_length_m:number}
type Cell=string|number

const labels={
 en:{"direct-seeding":["Direct Seeding Chart","Canonical direct-sow references from the Black Swan crop library; unavailable Heirloom-style fields remain blank rather than inferred."],transplantation:["Transplantation Chart","Canonical transplant references from the Black Swan crop library; unavailable Heirloom-style fields remain blank rather than inferred."],nursery:["Nursery Sow Chart","Canonical nursery-sowing references for transplant crops. Container, technique and germination values remain blank unless Black Swan has explicit evidence."],seeders:["Seeders Chart","Direct-sow crop references in the Heirloom seeder-chart grammar. No roller or density setting is inferred without a canonical seeder profile."],"crop-yield":["Crop Yield Chart","Canonical crop yield targets translated to the Black Swan standard bed. Price and revenue remain blank without a crop-level canonical price."],search:"Search crops…",none:"No canonical records available.",crop:"Crop / Cultivar",method:"Method",seeder:"Seeder",rows:"Number of rows",rowSpacing:"Spacing between rows",plantSpacing:"Spacing on the row",rate:"Demand rate",calibration:"Calibration",nurseryDays:"Days in nursery",germination:"Germination",yield:"Target yield / m²",evidence:"Evidence",unknown:"—",records:"records",profiles:"Profiles",family:"Family",harvestWindow:"Harvest window",avgDtm:"Average DTM",climateDtm:"Climate-adjusted DTM",seedMargin:"Seeds safety margin",plantingMethod:"Planting method",container:"Container",seedPerCell:"Seed per cell",seedingTechnique:"Seeding technique",daysToGerminate:"Days to germinate",germTemp:"Optimal germ. temp.",roller:"Roller",density30:"Seeds optimal density / 30m",cultivar:"Cultivar",unit:"Unit",price:"Price per unit",yieldBed:"Yield / standard bed",revenueBed:"Revenue / standard bed",transplant:"Transplant",filters:"Filters",hideEmpty:"Hide rows with no chart values",export:"Export",visible:"visible",sort:"Sort"},
 es:{"direct-seeding":["Tabla de siembra directa","Referencias canónicas de siembra directa desde la biblioteca de cultivos de Black Swan; los campos no observados quedan vacíos en vez de inferirse."],transplantation:["Tabla de trasplante","Referencias canónicas de trasplante desde la biblioteca de cultivos de Black Swan; los campos no observados quedan vacíos en vez de inferirse."],nursery:["Tabla de siembra en vivero","Referencias canónicas de vivero para cultivos de trasplante. Contenedor, técnica y germinación quedan vacíos sin evidencia explícita de Black Swan."],seeders:["Tabla de sembradoras","Referencias de cultivos de siembra directa con la gramática de sembradoras de Heirloom. No se infiere rodillo ni densidad sin perfil canónico."],"crop-yield":["Tabla de rendimiento de cultivos","Objetivos canónicos de rendimiento convertidos a la cama estándar de Black Swan. Precio e ingreso quedan vacíos sin precio canónico a nivel de cultivo."],search:"Buscar cultivos…",none:"No hay registros canónicos disponibles.",crop:"Cultivo / Cultivar",method:"Método",seeder:"Sembradora",rows:"Número de hileras",rowSpacing:"Entre hileras",plantSpacing:"Sobre la hilera",rate:"Dosis",calibration:"Calibración",nurseryDays:"Días en vivero",germination:"Germinación",yield:"Rendimiento objetivo / m²",evidence:"Evidencia",unknown:"—",records:"registros",profiles:"Perfiles",family:"Familia",harvestWindow:"Ventana de cosecha",avgDtm:"DTM promedio",climateDtm:"DTM ajustado por clima",seedMargin:"Margen de seguridad de semillas",plantingMethod:"Método de plantación",container:"Contenedor",seedPerCell:"Semilla por celda",seedingTechnique:"Técnica de siembra",daysToGerminate:"Días para germinar",germTemp:"Temp. óptima de germinación",roller:"Rodillo",density30:"Densidad óptima / 30m",cultivar:"Cultivar",unit:"Unidad",price:"Precio por unidad",yieldBed:"Rendimiento / cama estándar",revenueBed:"Ingreso / cama estándar",transplant:"Trasplante",filters:"Filtros",hideEmpty:"Ocultar filas sin valores de la tabla",export:"Exportar",visible:"visibles",sort:"Ordenar"},
 de:{"direct-seeding":["Direktsaat-Tabelle","Kanonische Direktsaatreferenzen aus der Black-Swan-Kulturbibliothek; nicht beobachtete Felder bleiben leer."],transplantation:["Auspflanz-Tabelle","Kanonische Auspflanzreferenzen aus der Black-Swan-Kulturbibliothek; nicht beobachtete Felder bleiben leer."],nursery:["Anzucht-Aussaat-Tabelle","Kanonische Anzuchtreferenzen für Auspflanzkulturen. Behälter, Technik und Keimwerte bleiben ohne explizite Black-Swan-Evidenz leer."],seeders:["Sägeräte-Tabelle","Direktsaatkulturen in der Heirloom-Sägeräte-Struktur. Walze und Dichte werden ohne kanonisches Profil nicht abgeleitet."],"crop-yield":["Kulturertrags-Tabelle","Kanonische Zielerträge auf das Black-Swan-Standardbeet umgerechnet. Preis und Umsatz bleiben ohne kanonischen Kulturpreis leer."],search:"Kulturen suchen…",none:"Keine kanonischen Datensätze verfügbar.",crop:"Kultur / Sorte",method:"Methode",seeder:"Sägerät",rows:"Anzahl Reihen",rowSpacing:"Abstand zwischen Reihen",plantSpacing:"Abstand in der Reihe",rate:"Bedarf",calibration:"Kalibrierung",nurseryDays:"Tage in Anzucht",germination:"Keimung",yield:"Zielertrag / m²",evidence:"Evidenz",unknown:"—",records:"Einträge",profiles:"Profile",family:"Familie",harvestWindow:"Erntefenster",avgDtm:"Durchschn. DTM",climateDtm:"Klimaangepasstes DTM",seedMargin:"Saatgut-Sicherheitsmarge",plantingMethod:"Pflanzmethode",container:"Behälter",seedPerCell:"Saat pro Zelle",seedingTechnique:"Aussaattechnik",daysToGerminate:"Tage bis Keimung",germTemp:"Optimale Keimtemp.",roller:"Walze",density30:"Optimale Saatdichte / 30m",cultivar:"Sorte",unit:"Einheit",price:"Preis pro Einheit",yieldBed:"Ertrag / Standardbeet",revenueBed:"Umsatz / Standardbeet",transplant:"Auspflanzung",filters:"Filter",hideEmpty:"Zeilen ohne Tabellenwerte ausblenden",export:"Exportieren",visible:"sichtbar",sort:"Sortieren"}
} as const

export function OrchardReferenceChart({mode}:{mode:Mode}){
 const {language}=useLanguage();const locale=language as Locale;const t=labels[locale];const supabase=useMemo(()=>createBrowserClient(),[])
 const [crops,setCrops]=useState<Crop[]>([]);const [direct,setDirect]=useState<Direct[]>([]);const [bed,setBed]=useState<FarmBed|null>(null);const [search,setSearch]=useState("");const [hideEmpty,setHideEmpty]=useState(false);const [filtersOpen,setFiltersOpen]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let live=true;void (async()=>{setLoading(true);setError(null);const cropReq=supabase.from("orchard_crop_library").select("id,crop_name,crop_family,default_cycle_type,days_to_maturity,nursery_days,plant_spacing_cm,row_spacing_cm,germination_rate_pct,seeds_per_plant,target_yield_per_sqm,yield_unit,provenance_type,observed_count").eq("is_active",true).order("crop_name");const directReq=mode==="direct-seeding"||mode==="seeders"?supabase.from("orchard_direct_seeding_profiles").select("id,crop_library_id,seeding_method,seeder_name,rows_per_bed,row_spacing_cm,plant_spacing_cm,calibration_setting,demand_value,demand_unit,reference_bed_m,provenance_type,conflict_status").eq("is_active",true):Promise.resolve({data:[],error:null});const bedReq=mode==="crop-yield"?supabase.from("orchard_farm_settings").select("standard_bed_width_cm,standard_bed_length_m").eq("farm_key","black_swan_orchard").single():Promise.resolve({data:null,error:null});const [cropResult,directResult,bedResult]=await Promise.all([cropReq,directReq,bedReq]);if(!live)return;const failure=cropResult.error??directResult.error??bedResult.error;if(failure)setError(failure.message);setCrops((cropResult.data??[]) as Crop[]);setDirect((directResult.data??[]) as Direct[]);setBed((bedResult.data??null) as FarmBed|null);setLoading(false)})();return()=>{live=false}},[mode,supabase])
 const q=search.trim().toLowerCase();const filteredCrops=useMemo(()=>crops.filter(c=>!q||c.crop_name.toLowerCase().includes(q)||(c.crop_family??"").toLowerCase().includes(q)),[crops,q]);const directByCrop=useMemo(()=>{const map=new Map<string,Direct>();for(const row of direct){if(!map.has(row.crop_library_id))map.set(row.crop_library_id,row)}return map},[direct]);const directSowCrops=useMemo(()=>filteredCrops.filter(c=>c.default_cycle_type==="direct_sow"),[filteredCrops]);const transplantCrops=useMemo(()=>filteredCrops.filter(c=>c.default_cycle_type==="transplant"),[filteredCrops]);const yieldCrops=useMemo(()=>filteredCrops.filter(c=>c.target_yield_per_sqm!=null),[filteredCrops]);const [title,help]=t[mode]
 const bedArea=bed?Number(bed.standard_bed_length_m)*(Number(bed.standard_bed_width_cm)/100):null
 let heads:string[]=[];let tableRows:Cell[][]=[]
 if(mode==="direct-seeding"){heads=[t.crop,t.rows,t.plantSpacing,t.harvestWindow,t.avgDtm,t.climateDtm,t.seedMargin];tableRows=directSowCrops.map(c=>{const profile=directByCrop.get(c.id);return[c.crop_name,profile?.rows_per_bed??t.unknown,(profile?.plant_spacing_cm??c.plant_spacing_cm)==null?t.unknown:`${profile?.plant_spacing_cm??c.plant_spacing_cm} cm`,t.unknown,c.days_to_maturity??t.unknown,t.unknown,t.unknown]})}
 if(mode==="transplantation"){heads=[t.crop,t.rows,t.rowSpacing,t.plantSpacing,t.nurseryDays,t.harvestWindow,t.avgDtm,t.climateDtm];tableRows=transplantCrops.map(c=>[c.crop_name,t.unknown,c.row_spacing_cm==null?t.unknown:`${c.row_spacing_cm} cm`,c.plant_spacing_cm==null?t.unknown:`${c.plant_spacing_cm} cm`,c.nursery_days??t.unknown,t.unknown,c.days_to_maturity??t.unknown,t.unknown])}
 if(mode==="nursery"){heads=[t.crop,t.plantingMethod,t.container,t.seedPerCell,t.seedingTechnique,t.seedMargin,t.daysToGerminate,t.germTemp];tableRows=transplantCrops.map(c=>[c.crop_name,t.transplant,t.unknown,t.unknown,t.unknown,t.unknown,t.unknown,t.unknown])}
 if(mode==="seeders"){heads=[t.crop,t.roller,t.density30];tableRows=directSowCrops.map(c=>[c.crop_name,t.unknown,t.unknown])}
 if(mode==="crop-yield"){heads=[t.crop,t.cultivar,t.unit,t.price,`${t.yieldBed}${bed?` (${bed.standard_bed_length_m}m)`:""}`,t.revenueBed];tableRows=yieldCrops.map(c=>{const target=bedArea==null||c.target_yield_per_sqm==null?t.unknown:`${(Number(c.target_yield_per_sqm)*bedArea).toFixed(2)} ${c.yield_unit??""}`.trim();return[c.crop_name,t.unknown,c.yield_unit??t.unknown,t.unknown,target,t.unknown]})}
 const hasChartValue=(row:Cell[])=>row.slice(1).some(value=>String(value).trim()!==""&&String(value)!==t.unknown)
 const visibleRows=hideEmpty?tableRows.filter(hasChartValue):tableRows
 const downloadCsv=()=>{if(!visibleRows.length)return;const esc=(value:Cell)=>`"${String(value).replaceAll('"','""')}"`;const csv=[heads.map(esc).join(","),...visibleRows.map(row=>row.map(esc).join(","))].join("\n");const blob=new Blob([`\uFEFF${csv}`],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`black-swan-${mode}.csv`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url)}
 return <AppLayout><OrchardNavigation/><main className="mx-auto flex min-h-[calc(100vh-3.5rem)] w-full max-w-[1480px] flex-col px-4 pb-5 pt-4 sm:px-6 lg:px-8">
  <header className="flex flex-col gap-3 border-b border-[var(--orchard-line)] pb-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-[25px] font-normal tracking-[-.03em]">{title}</h1><p className="mt-1 max-w-3xl text-[12px] leading-5 text-muted-foreground">{help}</p></div><p className="shrink-0 text-[10px] uppercase tracking-[.1em] text-muted-foreground">{visibleRows.length} {t.records}</p></header>
  <div className="sticky top-0 z-20 -mx-1 border-b border-[var(--orchard-line-soft)] bg-[var(--orchard-canvas)] px-1 py-3"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><label className="flex h-9 w-full max-w-sm items-center gap-2 border border-[var(--orchard-line)] bg-[#171614] px-3"><Search className="h-4 w-4 text-muted-foreground"/><input aria-label={t.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search} className="min-w-0 flex-1 bg-transparent text-[13px] outline-none"/></label><div className="flex items-center gap-2"><span className="hidden text-[10px] text-muted-foreground md:inline">{visibleRows.length} {t.visible}</span><button type="button" aria-expanded={filtersOpen} onClick={()=>setFiltersOpen(value=>!value)} className="inline-flex h-9 items-center gap-2 border border-[var(--orchard-line)] bg-[#171614] px-3 text-[11px] text-[#d7d0c6] hover:bg-[var(--bs-surface-secondary)]"><SlidersHorizontal className="h-3.5 w-3.5"/>{t.filters}</button><button type="button" onClick={downloadCsv} disabled={!visibleRows.length} className="inline-flex h-9 items-center gap-2 border border-[var(--orchard-line)] bg-[#171614] px-3 text-[11px] text-[#d7d0c6] hover:bg-[var(--bs-surface-secondary)] disabled:cursor-not-allowed disabled:opacity-40"><Download className="h-3.5 w-3.5"/>{t.export}</button></div></div>{filtersOpen?<label className="mt-2 inline-flex min-h-8 items-center gap-2 border border-[var(--orchard-line-soft)] bg-[var(--bs-surface-primary)] px-3 text-[11px] text-muted-foreground"><input type="checkbox" checked={hideEmpty} onChange={event=>setHideEmpty(event.target.checked)} className="accent-[var(--orchard-green)]"/>{t.hideEmpty}</label>:null}</div>
  {error?<p className="mt-4 text-sm text-red-300">{error}</p>:null}
  <div className="min-h-0 flex-1 overflow-auto border-y border-[var(--orchard-line)]">{visibleRows.length?<Table heads={heads} rows={visibleRows} sortLabel={t.sort}/>:!loading?<div className="flex min-h-[300px] items-center justify-center px-6 text-center text-sm text-muted-foreground">{t.none}</div>:null}</div>
 </main></AppLayout>
}
function Table({heads,rows,sortLabel}:{heads:string[];rows:Cell[][];sortLabel:string}){const [sortIndex,setSortIndex]=useState<number|null>(null);const [direction,setDirection]=useState<"asc"|"desc">("asc");const sort=(index:number)=>{if(sortIndex===index){setDirection(current=>current==="asc"?"desc":"asc")}else{setSortIndex(index);setDirection("asc")}};const sorted=useMemo(()=>{if(sortIndex==null)return rows;const result=[...rows];result.sort((a,b)=>compareCells(a[sortIndex],b[sortIndex])* (direction==="asc"?1:-1));return result},[rows,sortIndex,direction]);return <table className="w-full min-w-[900px] border-collapse text-[12px]"><thead className="sticky top-0 z-10 bg-[var(--bs-surface-primary)] shadow-[0_1px_0_var(--orchard-line)]"><tr>{heads.map((h,index)=><th key={h} className="px-3 py-2.5 text-left text-[9px] font-medium uppercase tracking-[.09em] text-muted-foreground"><button type="button" onClick={()=>sort(index)} aria-label={`${sortLabel} ${h}`} className="inline-flex items-center gap-1.5 text-left hover:text-foreground">{h}<ArrowUpDown className="h-3 w-3 opacity-55"/></button></th>)}</tr></thead><tbody>{sorted.map((row,i)=><tr key={`${row[0]}-${i}`} className="transition-colors hover:bg-[var(--bs-surface-secondary)]/55">{row.map((v,j)=><td key={j} className={`border-b border-[var(--orchard-line-soft)] px-3 py-2.5 align-top ${j===0?"font-medium text-[#eee9e1]":"text-[#c4bcb1]"}`}>{v}</td>)}</tr>)}</tbody></table>}
function compareCells(a:Cell,b:Cell){const av=String(a),bv=String(b);if(av==="—"&&bv!=="—")return 1;if(bv==="—"&&av!=="—")return-1;const an=Number.parseFloat(av.replace(",",".")),bn=Number.parseFloat(bv.replace(",","."));if(Number.isFinite(an)&&Number.isFinite(bn))return an-bn;return av.localeCompare(bv,undefined,{numeric:true,sensitivity:"base"})}
