"use client"

import { useEffect, useMemo, useState } from "react"
import { Search } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Mode="direct-seeding"|"transplantation"|"nursery"|"seeders"|"crop-yield"
type Locale="en"|"es"|"de"
type Crop={id:string;crop_name:string;crop_family:string|null;nursery_days:number|null;plant_spacing_cm:number|null;row_spacing_cm:number|null;germination_rate_pct:number|null;target_yield_per_sqm:number|null;yield_unit:string|null;provenance_type:string|null;observed_count:number|null}
type Direct={id:string;crop_library_id:string;seeding_method:string|null;seeder_name:string|null;rows_per_bed:number|null;row_spacing_cm:number|null;plant_spacing_cm:number|null;calibration_setting:string|null;demand_value:number|null;demand_unit:string|null;reference_bed_m:number|null;provenance_type:string|null;conflict_status:string|null}
type Batch={id:string;batch_code:string|null;sow_date:string;expected_ready_date:string|null;actual_ready_date:string|null;transplant_date:string|null;cells_sown:number|null;seeds_sown:number;emerged_count:number|null;ready_count:number|null;transplanted_count:number|null;loss_count:number;status:string;location:string|null}

const labels={
 en:{"direct-seeding":["Direct seeding","Canonical direct-seeding profiles, spacing, demand rates and calibration evidence."],transplantation:["Transplantation","Canonical transplant timing and spacing references by crop."],nursery:["Nursery","Observed nursery batches plus validated nursery-duration references."],seeders:["Seeders","Seeder names and calibration settings observed in canonical direct-seeding profiles."],"crop-yield":["Crop yield","Canonical target yield references. Missing or unvalidated yield remains blank."],search:"Search…",none:"No canonical records available.",crop:"Crop",method:"Method",seeder:"Seeder",rows:"Rows / bed",rowSpacing:"Row spacing",plantSpacing:"Plant spacing",rate:"Demand rate",calibration:"Calibration",nurseryDays:"Nursery days",germination:"Germination",batch:"Batch",sown:"Sown",ready:"Expected ready",status:"Status",cells:"Cells",seeds:"Seeds",emerged:"Emerged",transplanted:"Transplanted",losses:"Losses",yield:"Target yield / m²",evidence:"Evidence",unknown:"—",records:"records",profiles:"Profiles",family:"Family"},
 es:{"direct-seeding":["Siembra directa","Perfiles canónicos de siembra directa, espaciamiento, dosis y calibración."],transplantation:["Trasplante","Referencias canónicas de tiempo y espaciamiento de trasplante por cultivo."],nursery:["Vivero","Lotes observados de vivero y referencias validadas de duración."],seeders:["Sembradoras","Sembradoras y calibraciones observadas en perfiles canónicos de siembra directa."],"crop-yield":["Rendimiento de cultivos","Referencias canónicas de rendimiento objetivo. Lo no validado queda vacío."],search:"Buscar…",none:"No hay registros canónicos disponibles.",crop:"Cultivo",method:"Método",seeder:"Sembradora",rows:"Hileras / cama",rowSpacing:"Entre hileras",plantSpacing:"Entre plantas",rate:"Dosis",calibration:"Calibración",nurseryDays:"Días vivero",germination:"Germinación",batch:"Lote",sown:"Siembra",ready:"Listo esperado",status:"Estado",cells:"Celdas",seeds:"Semillas",emerged:"Emergidas",transplanted:"Trasplantadas",losses:"Pérdidas",yield:"Rendimiento objetivo / m²",evidence:"Evidencia",unknown:"—",records:"registros",profiles:"Perfiles",family:"Familia"},
 de:{"direct-seeding":["Direktsaat","Kanonische Direktsaatprofile, Abstände, Bedarf und Kalibrierung."],transplantation:["Auspflanzung","Kanonische Auspflanzungs- und Abstandsreferenzen nach Kultur."],nursery:["Anzucht","Beobachtete Anzuchtchargen und validierte Anzuchtdauer."],seeders:["Sägeräte","Beobachtete Sägeräte und Kalibrierungen aus Direktsaatprofilen."],"crop-yield":["Kulturertrag","Kanonische Zielertragswerte; nicht validierte Werte bleiben leer."],search:"Suchen…",none:"Keine kanonischen Datensätze verfügbar.",crop:"Kultur",method:"Methode",seeder:"Sägerät",rows:"Reihen / Beet",rowSpacing:"Reihenabstand",plantSpacing:"Pflanzabstand",rate:"Bedarf",calibration:"Kalibrierung",nurseryDays:"Anzuchttage",germination:"Keimung",batch:"Charge",sown:"Aussaat",ready:"Vorauss. bereit",status:"Status",cells:"Zellen",seeds:"Samen",emerged:"Aufgelaufen",transplanted:"Ausgepflanzt",losses:"Verluste",yield:"Zielertrag / m²",evidence:"Evidenz",unknown:"—",records:"Einträge",profiles:"Profile",family:"Familie"}
} as const

export function OrchardReferenceChart({mode}:{mode:Mode}){
 const {language}=useLanguage();const locale=language as Locale;const t=labels[locale];const supabase=useMemo(()=>createBrowserClient(),[])
 const [crops,setCrops]=useState<Crop[]>([]);const [direct,setDirect]=useState<Direct[]>([]);const [batches,setBatches]=useState<Batch[]>([]);const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let live=true;void (async()=>{setLoading(true);setError(null);const cropReq=supabase.from("orchard_crop_library").select("id,crop_name,crop_family,nursery_days,plant_spacing_cm,row_spacing_cm,germination_rate_pct,target_yield_per_sqm,yield_unit,provenance_type,observed_count").eq("is_active",true).order("crop_name");const reqs:[PromiseLike<any>,PromiseLike<any>?,PromiseLike<any>?]=[cropReq];if(mode==="direct-seeding"||mode==="seeders")reqs.push(supabase.from("orchard_direct_seeding_profiles").select("id,crop_library_id,seeding_method,seeder_name,rows_per_bed,row_spacing_cm,plant_spacing_cm,calibration_setting,demand_value,demand_unit,reference_bed_m,provenance_type,conflict_status").eq("is_active",true));if(mode==="nursery")reqs.push(supabase.from("orchard_nursery_batches").select("id,batch_code,sow_date,expected_ready_date,actual_ready_date,transplant_date,cells_sown,seeds_sown,emerged_count,ready_count,transplanted_count,loss_count,status,location").order("sow_date",{ascending:false}));const results=await Promise.all(reqs);if(!live)return;const failure=results.find(r=>r?.error)?.error;if(failure)setError(failure.message);setCrops((results[0]?.data??[]) as Crop[]);let i=1;if(mode==="direct-seeding"||mode==="seeders"){setDirect((results[i]?.data??[]) as Direct[]);i++}if(mode==="nursery")setBatches((results[i]?.data??[]) as Batch[]);setLoading(false)})();return()=>{live=false}},[mode,supabase])
 const cropById=useMemo(()=>new Map(crops.map(c=>[c.id,c.crop_name])),[crops]);const q=search.trim().toLowerCase();const filteredCrops=useMemo(()=>crops.filter(c=>!q||c.crop_name.toLowerCase().includes(q)||(c.crop_family??"").toLowerCase().includes(q)),[crops,q]);const filteredDirect=useMemo(()=>direct.filter(r=>!q||(cropById.get(r.crop_library_id)??"").toLowerCase().includes(q)||(r.seeder_name??"").toLowerCase().includes(q)),[direct,cropById,q]);const seeders=useMemo(()=>{const map=new Map<string,{name:string;profiles:number;calibrations:Set<string>;crops:Set<string>}>();for(const r of direct){if(!r.seeder_name)continue;const x=map.get(r.seeder_name)??{name:r.seeder_name,profiles:0,calibrations:new Set<string>(),crops:new Set<string>()};x.profiles++;if(r.calibration_setting)x.calibrations.add(r.calibration_setting);const crop=cropById.get(r.crop_library_id);if(crop)x.crops.add(crop);map.set(r.seeder_name,x)}return [...map.values()].filter(x=>!q||x.name.toLowerCase().includes(q)||[...x.crops].some(c=>c.toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name))},[direct,cropById,q]);const [title,help]=t[mode]
 const rows=mode==="direct-seeding"?filteredDirect.length:mode==="transplantation"?filteredCrops.filter(c=>c.nursery_days!=null||c.plant_spacing_cm!=null).length:mode==="nursery"?batches.length:mode==="seeders"?seeders.length:filteredCrops.filter(c=>c.target_yield_per_sqm!=null).length
 return <AppLayout><OrchardNavigation/><main className="mx-auto flex min-h-[calc(100vh-3.5rem)] w-full max-w-[1480px] flex-col px-4 pb-5 pt-4 sm:px-6 lg:px-8">
  <header className="flex flex-col gap-3 border-b border-[var(--orchard-line)] pb-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-[25px] font-normal tracking-[-.03em]">{title}</h1><p className="mt-1 max-w-3xl text-[12px] leading-5 text-muted-foreground">{help}</p></div><p className="shrink-0 text-[10px] uppercase tracking-[.1em] text-muted-foreground">{rows} {t.records}</p></header>
  <div className="sticky top-0 z-20 -mx-1 flex items-center border-b border-[var(--orchard-line-soft)] bg-[var(--orchard-canvas)] px-1 py-3"><label className="flex h-9 w-full max-w-sm items-center gap-2 border border-[var(--orchard-line)] bg-[#171614] px-3"><Search className="h-4 w-4 text-muted-foreground"/><input aria-label={t.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search} className="min-w-0 flex-1 bg-transparent text-[13px] outline-none"/></label></div>
  {error?<p className="mt-4 text-sm text-red-300">{error}</p>:null}
  <div className="min-h-0 flex-1 overflow-auto border-y border-[var(--orchard-line)]">
   {mode==="direct-seeding"?<Table heads={[t.crop,t.method,t.seeder,t.rows,t.rowSpacing,t.plantSpacing,t.rate,t.calibration]} rows={filteredDirect.map(r=>[cropById.get(r.crop_library_id)??t.unknown,r.seeding_method??t.unknown,r.seeder_name??t.unknown,r.rows_per_bed??t.unknown,r.row_spacing_cm==null?t.unknown:`${r.row_spacing_cm} cm`,r.plant_spacing_cm==null?t.unknown:`${r.plant_spacing_cm} cm`,r.demand_value==null?t.unknown:`${r.demand_value} ${r.demand_unit??""}`.trim(),r.calibration_setting??t.unknown])}/>:null}
   {mode==="transplantation"?<Table heads={[t.crop,t.nurseryDays,t.plantSpacing,t.rowSpacing,t.germination,t.evidence]} rows={filteredCrops.filter(c=>c.nursery_days!=null||c.plant_spacing_cm!=null).map(c=>[c.crop_name,c.nursery_days??t.unknown,c.plant_spacing_cm==null?t.unknown:`${c.plant_spacing_cm} cm`,c.row_spacing_cm==null?t.unknown:`${c.row_spacing_cm} cm`,c.germination_rate_pct==null?t.unknown:`${c.germination_rate_pct}%`,c.provenance_type??t.unknown])}/>:null}
   {mode==="nursery"?<Table heads={[t.batch,t.sown,t.ready,t.status,t.cells,t.seeds,t.emerged,t.transplanted,t.losses]} rows={batches.map(b=>[b.batch_code??b.id.slice(0,8),b.sow_date,b.actual_ready_date??b.expected_ready_date??t.unknown,b.status,b.cells_sown??t.unknown,b.seeds_sown,b.emerged_count??t.unknown,b.transplanted_count??t.unknown,b.loss_count])}/>:null}
   {mode==="seeders"?<Table heads={[t.seeder,t.profiles,t.crop,t.calibration]} rows={seeders.map(s=>[s.name,s.profiles,[...s.crops].join(", ")||t.unknown,[...s.calibrations].join(", ")||t.unknown])}/>:null}
   {mode==="crop-yield"?<Table heads={[t.crop,t.family,t.yield,t.evidence]} rows={filteredCrops.filter(c=>c.target_yield_per_sqm!=null).map(c=>[c.crop_name,c.crop_family??t.unknown,`${c.target_yield_per_sqm} ${c.yield_unit??""}`.trim(),c.provenance_type??(c.observed_count?String(c.observed_count):t.unknown)])}/>:null}
   {!loading&&rows===0?<div className="flex min-h-[300px] items-center justify-center px-6 text-center text-sm text-muted-foreground">{t.none}</div>:null}
  </div>
 </main></AppLayout>
}
function Table({heads,rows}:{heads:string[];rows:(string|number)[][]}){return <table className="w-full min-w-[900px] border-collapse text-[12px]"><thead className="sticky top-0 z-10 bg-[var(--bs-surface-primary)] shadow-[0_1px_0_var(--orchard-line)]"><tr>{heads.map(h=><th key={h} className="px-3 py-2.5 text-left text-[9px] font-medium uppercase tracking-[.09em] text-muted-foreground">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="transition-colors hover:bg-[var(--bs-surface-secondary)]/55">{row.map((v,j)=><td key={j} className={`border-b border-[var(--orchard-line-soft)] px-3 py-2.5 align-top ${j===0?"font-medium text-[#eee9e1]":"text-[#c4bcb1]"}`}>{v}</td>)}</tr>)}</tbody></table>}
