"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowRight, CircleDollarSign, FileText, Sprout } from "lucide-react"
import { createBrowserClient } from "@/lib/supabase/client"
import { cropColor } from "@/lib/orchard/crop-identity"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Plan={id:string;season:string|null;status:string}
type Cycle={id:string;game_plan_id:string;crop_name:string}
type Succession={id:string;crop_cycle_id:string;planned_bed_m:number|null;planned_first_harvest_date:string|null;planned_last_harvest_date:string|null;knowledge_source_snapshot:Record<string,unknown>|null}
type Allocation={crop_succession_id:string}
type Note={id:string;title:string|null;body:string;note_type:string;observed_at:string}
type Canonical={yield_per_week_10m_bed?:number|string|null;price_per_unit_clp?:number|string|null;yield_unit?:string|null}
type Month={key:string;revenue:number;priced:number;eligible:number}
type Crop={name:string;bedM:number;successions:number}

const copy={
 en:{section:"Season intelligence",description:"Heirloom-style dashboard context, calculated only from the active Black Swan Game Plan and canonical Orchard evidence.",revenue:"Projected revenue by month",revenueHelp:"Only successions with both canonical weekly yield and CLP unit price contribute revenue. Missing prices remain excluded, never estimated.",distribution:"Crop distribution",distributionHelp:"Physical bed meters allocated to the selected Game Plan.",notes:"Latest notes",notesHelp:"Canonical orchard_notes observations visible under the current access policy.",openHarvest:"Open season harvests",openNotes:"Open notes",noRevenue:"No source-backed projected revenue.",noCrops:"No physical crop allocation.",noNotes:"No notes available.",priced:"priced successions",bed:"m bed",plantings:"plantings"},
 es:{section:"Inteligencia de temporada",description:"Contexto de dashboard estilo Heirloom, calculado sólo desde el Game Plan activo de Black Swan y evidencia canónica del Huerto.",revenue:"Ingreso proyectado por mes",revenueHelp:"Sólo aportan ingreso las sucesiones con rendimiento semanal y precio unitario CLP canónicos. Los precios faltantes se excluyen; nunca se estiman.",distribution:"Distribución de cultivos",distributionHelp:"Metros físicos de cama asignados al Game Plan seleccionado.",notes:"Notas recientes",notesHelp:"Observaciones canónicas de orchard_notes visibles bajo la política de acceso actual.",openHarvest:"Abrir cosecha de temporada",openNotes:"Abrir notas",noRevenue:"No hay ingreso proyectado respaldado por fuente.",noCrops:"No hay asignación física de cultivos.",noNotes:"No hay notas disponibles.",priced:"sucesiones con precio",bed:"m cama",plantings:"plantaciones"},
 de:{section:"Saisonintelligenz",description:"Heirloom-artiger Dashboard-Kontext, ausschließlich aus dem aktiven Black-Swan-Game-Plan und kanonischen Orchard-Nachweisen berechnet.",revenue:"Prognostizierter Umsatz pro Monat",revenueHelp:"Nur Folgen mit kanonischem Wochenertrag und CLP-Einheitspreis tragen zum Umsatz bei. Fehlende Preise werden ausgeschlossen, nie geschätzt.",distribution:"Kulturverteilung",distributionHelp:"Physische Beetmeter im ausgewählten Game Plan.",notes:"Neueste Notizen",notesHelp:"Kanonische orchard_notes-Beobachtungen gemäß aktueller Zugriffsrichtlinie.",openHarvest:"Saisonernte öffnen",openNotes:"Notizen öffnen",noRevenue:"Kein quellenbasierter prognostizierter Umsatz.",noCrops:"Keine physische Kulturzuordnung.",noNotes:"Keine Notizen verfügbar.",priced:"Folgen mit Preis",bed:"m Beet",plantings:"Pflanzungen"},
} as const
const localeMap:Record<Locale,string>={en:"en-US",es:"es-CL",de:"de-DE"}
const asFinite=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)?n:null}
const canonicalFor=(snapshot:Record<string,unknown>|null):Canonical=>{if(!snapshot)return{};const value=snapshot["black_swan_canonical"];return value&&typeof value==="object"?value as Canonical:{}}
const addDays=(value:string,days:number)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
const monthStart=(value:string)=>`${value.slice(0,7)}-01`
const nextMonth=(value:string)=>{const d=new Date(`${value}T12:00:00`);d.setMonth(d.getMonth()+1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`}
const monthEnd=(value:string)=>addDays(nextMonth(monthStart(value)),-1)
const overlapDays=(start:string,end:string,periodStart:string,periodEnd:string)=>{const from=start>periodStart?start:periodStart;const to=end<periodEnd?end:periodEnd;if(from>to)return 0;return Math.round((new Date(`${to}T12:00:00`).getTime()-new Date(`${from}T12:00:00`).getTime())/86400000)+1}

export function OrchardDashboardInsights({gamePlanId}:{gamePlanId:string|null}){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const lang:Locale=language;const text=copy[lang];const locale=localeMap[lang]
 const [plans,setPlans]=useState<Plan[]>([]),[cycles,setCycles]=useState<Cycle[]>([]),[successions,setSuccessions]=useState<Succession[]>([]),[allocations,setAllocations]=useState<Allocation[]>([]),[notes,setNotes]=useState<Note[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{let live=true;setLoading(true);void Promise.all([
  supabase.from("orchard_game_plans").select("id,season,status").order("start_date",{ascending:false}),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id,planned_bed_m,planned_first_harvest_date,planned_last_harvest_date,knowledge_source_snapshot").neq("status","cancelled"),
  supabase.from("orchard_bed_allocations").select("crop_succession_id"),
  supabase.from("orchard_notes").select("id,title,body,note_type,observed_at").order("observed_at",{ascending:false}).limit(3),
 ]).then(([p,c,s,a,n])=>{if(!live)return;setPlans((p.data??[]) as Plan[]);setCycles((c.data??[]) as Cycle[]);setSuccessions((s.data??[]) as Succession[]);setAllocations((a.data??[]) as Allocation[]);setNotes((n.data??[]) as Note[]);setLoading(false)});return()=>{live=false}},[supabase])
 const plan=plans.find(p=>p.id===gamePlanId)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const cycleById=new Map(cycles.filter(c=>c.game_plan_id===plan?.id).map(c=>[c.id,c]));const allocatedIds=new Set(allocations.map(a=>a.crop_succession_id));const scoped=successions.filter(s=>cycleById.has(s.crop_cycle_id)&&allocatedIds.has(s.id))
 const cropMap=new Map<string,Crop>();for(const s of scoped){const cycle=cycleById.get(s.crop_cycle_id);if(!cycle)continue;const row=cropMap.get(cycle.crop_name)??{name:cycle.crop_name,bedM:0,successions:0};row.bedM+=Number(s.planned_bed_m??0);row.successions+=1;cropMap.set(cycle.crop_name,row)}const crops=[...cropMap.values()].sort((a,b)=>b.bedM-a.bedM)
 const harvestable=scoped.filter(s=>s.planned_first_harvest_date&&s.planned_last_harvest_date&&Number(s.planned_bed_m)>0);const first=harvestable.map(s=>s.planned_first_harvest_date!).sort()[0]??null;const last=harvestable.map(s=>s.planned_last_harvest_date!).sort().at(-1)??null
 const months:Month[]=[];if(first&&last){let key=monthStart(first);while(key<=last&&months.length<18){months.push({key:key.slice(0,7),revenue:0,priced:0,eligible:0});key=nextMonth(key)}}
 for(const s of harvestable){const canonical=canonicalFor(s.knowledge_source_snapshot);const weeklyYield=asFinite(canonical.yield_per_week_10m_bed);const price=asFinite(canonical.price_per_unit_clp);if(weeklyYield==null||!canonical.yield_unit)continue;const dailyYield=weeklyYield/7*(Number(s.planned_bed_m)/10);for(const month of months){const start=`${month.key}-01`,end=monthEnd(start);const days=overlapDays(s.planned_first_harvest_date!,s.planned_last_harvest_date!,start,end);if(!days)continue;month.eligible+=1;if(price==null)continue;month.priced+=1;month.revenue+=dailyYield*days*price}}
 const maxRevenue=Math.max(...months.map(m=>m.revenue),0);const maxBed=Math.max(...crops.map(c=>c.bedM),0);const money=(value:number)=>new Intl.NumberFormat(locale,{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(value);const planQuery=plan?`?game_plan=${encodeURIComponent(plan.id)}`:""
 if(loading)return <div className="mt-8 py-8 text-sm text-muted-foreground">…</div>
 return <section className="mt-10 border-t border-[var(--orchard-line)] pt-7"><div className="mb-5"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--orchard-green)]">03 · {text.section}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{text.description}</p></div><div className="grid gap-5 xl:grid-cols-2">
  <article className="border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)]"><header className="flex items-start justify-between gap-4 border-b border-[var(--orchard-line)] p-4"><div><div className="flex items-center gap-2"><CircleDollarSign className="h-4 w-4 text-[var(--orchard-green)]"/><h3 className="text-lg font-medium">{text.revenue}</h3></div><p className="mt-1 max-w-xl text-xs leading-5 text-muted-foreground">{text.revenueHelp}</p></div><Link href={`/${language}/orchard/harvest/season${planQuery}`} className="shrink-0 text-xs text-foreground">{text.openHarvest}</Link></header><div className="p-4">{months.some(m=>m.revenue>0)?<div className="space-y-3">{months.filter(m=>m.revenue>0).map(month=><div key={month.key} className="grid grid-cols-[82px_1fr_110px] items-center gap-3"><span className="text-xs capitalize text-muted-foreground">{new Date(`${month.key}-01T12:00:00`).toLocaleDateString(locale,{month:"short",year:"2-digit"})}</span><div className="h-2 bg-[var(--orchard-line)]"><div className="h-full bg-[var(--orchard-green)]" style={{width:`${maxRevenue?Math.max(2,month.revenue/maxRevenue*100):0}%`}}/></div><div className="text-right"><p className="text-xs font-medium">{money(month.revenue)}</p><p className="text-[10px] text-muted-foreground">{month.priced}/{month.eligible} {text.priced}</p></div></div>)}</div>:<p className="py-8 text-sm text-muted-foreground">{text.noRevenue}</p>}</div></article>
  <article className="border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)]"><header className="border-b border-[var(--orchard-line)] p-4"><div className="flex items-center gap-2"><Sprout className="h-4 w-4 text-[var(--orchard-green)]"/><h3 className="text-lg font-medium">{text.distribution}</h3></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{text.distributionHelp}</p></header><div className="p-4">{crops.length?<div className="space-y-2.5">{crops.slice(0,12).map(crop=><div key={crop.name} className="grid grid-cols-[minmax(130px,1fr)_1fr_105px] items-center gap-3"><div className="flex min-w-0 items-center gap-2"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{backgroundColor:cropColor(crop.name,null)}}/><span className="truncate text-xs">{crop.name}</span></div><div className="h-2 bg-[var(--orchard-line)]"><div className="h-full" style={{width:`${maxBed?Math.max(2,crop.bedM/maxBed*100):0}%`,backgroundColor:cropColor(crop.name,null)}}/></div><div className="text-right"><p className="text-xs font-medium">{crop.bedM.toLocaleString(locale,{maximumFractionDigits:1})} {text.bed}</p><p className="text-[10px] text-muted-foreground">{crop.successions} {text.plantings}</p></div></div>)}</div>:<p className="py-8 text-sm text-muted-foreground">{text.noCrops}</p>}</div></article>
  <article className="border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] xl:col-span-2"><header className="flex items-start justify-between gap-4 border-b border-[var(--orchard-line)] p-4"><div><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-[var(--orchard-green)]"/><h3 className="text-lg font-medium">{text.notes}</h3></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{text.notesHelp}</p></div><Link href={`/${language}/orchard/notes${planQuery}`} className="inline-flex shrink-0 items-center gap-1.5 text-xs text-foreground">{text.openNotes}<ArrowRight className="h-3.5 w-3.5"/></Link></header>{notes.length?<div className="grid gap-px bg-[var(--orchard-line)] md:grid-cols-3">{notes.map(note=><Link key={note.id} href={`/${language}/orchard/notes${planQuery}`} className="bg-[var(--bs-surface-primary)] p-4 hover:bg-[var(--bs-surface-secondary)]"><p className="truncate text-sm font-medium">{note.title?.trim()||note.note_type}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{note.body}</p><p className="mt-3 text-[10px] text-muted-foreground">{new Date(note.observed_at).toLocaleDateString(locale,{day:"2-digit",month:"short",year:"numeric",timeZone:"America/Santiago"})}</p></Link>)}</div>:<p className="p-6 text-sm text-muted-foreground">{text.noNotes}</p>}</article>
 </div></section>
}
