"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { ArrowLeft, CheckCircle2, ClipboardList, PackageSearch, RefreshCw, ShoppingCart, Truck } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { useToast } from "@/hooks/use-toast"
import { useEffectiveAccess } from "@/lib/hooks/use-effective-access"
import { useLanguage } from "@/lib/hooks/use-language"
import { createBrowserClient } from "@/lib/supabase/client"

type NeedStatus = "open" | "requested" | "approved" | "ordered" | "receiving" | "fulfilled" | "rejected" | "cancelled"
type StockItem = { id:string; item_code:string; name:string; unit:string; quantity_on_hand:number; minimum_stock:number; reorder_quantity:number; unit_cost:number|null; warehouse_location:{name:string;warehouse:{name:string}|null}|null }
type Need = { id:string; status:NeedStatus; trigger_quantity:number; minimum_stock:number; suggested_quantity:number; requested_quantity:number|null; procurement_request_id:string|null; purchase_order_id:string|null; opened_at:string; requested_at:string|null; approved_at:string|null; ordered_at:string|null; receiving_at:string|null; fulfilled_at:string|null; resolution_reason:string|null; stock_item:StockItem|null; request:{id:string;request_number:string|null;status:string}|null; order:{id:string;order_number:string|null;status:string}|null }
type RawNeed = Omit<Need,"stock_item"|"request"|"order"> & { inventory_stock_items:StockItem|StockItem[]|null; procurement_requests:Need["request"]|Need["request"][]|null; procurement_purchase_orders:Need["order"]|Need["order"][]|null }

const LOCALES={en:"en-US",es:"es-CL",de:"de-DE"} as const
const COPY={
 en:{access:"Checking Inventory access…",title:"Inventory replenishment",shortDescription:"Purchase needs linked to real stock.",noPermission:"Your profile cannot operate Inventory.",description:"From minimum stock through Procurement, order, receiving and intake, preserving a single active need per SKU.",refresh:"Refresh",stock:"Stock",loadError:"Replenishment needs could not be loaded.",quantityError:"Requested quantity must be greater than zero.",requestError:"The procurement request could not be created.",requestSent:"Request sent to Procurement",requestLinked:"The need is linked to requisition",toRequest:"To request",approval:"In approval",orderReceiving:"Order / receiving",fulfilled:"Replenished",chain:"Operational chain",chainDescription:"Purchases are not created by simulation: the cycle starts only when a real SKU reaches or falls below its configured minimum.",stage1:"1. Stock",stage1d:"Detects minimum and suggested quantity.",stage2:"2. Requisition",stage2d:"Inventory sends one idempotent request.",stage3:"3. Procurement",stage3d:"Approval, quotation, and ordering remain in Procurement.",stage4:"4. Receiving",stage4d:"Partial or full receiving preserves traceability.",stage5:"5. Intake",stage5d:"Intake replenishes the same SKU and closes the cycle.",active:"Active",history:"History",requests:"Requests",approvals:"Approvals",receiving:"Receiving",intake:"Intake",loading:"Loading replenishment needs…",emptyActive:"No active replenishment needs.",emptyAll:"No replenishment needs recorded.",emptyHint:"When real consumable stock reaches its configured minimum, the system opens the need automatically. No demo records are created.",needs:"Needs",needsDescription:"One active need per SKU and location.",skuUnavailable:"SKU unavailable",warehouse:"Warehouse",locationUnavailable:"Location unavailable",current:"Current",minimum:"Minimum",suggested:"Suggested",control:"Need control",selectNeed:"Select a need.",selectTrace:"Select a need to review its traceability.",opened:"Opened",triggerQty:"Quantity at trigger",suggestedQty:"Suggested replenishment",requestedQty:"Quantity to request",requiredDate:"Required date",priority:"Priority",low:"Low",normal:"Normal",high:"High",critical:"Critical",sending:"Sending…",createRequest:"Create procurement request",idempotent:"If this need already has a linked request, the RPC returns the same one and does not duplicate the requisition.",request:"Request",order:"Order",requestedAmount:"Requested quantity",lastResult:"Latest result"},
 es:{access:"Verificando acceso a Inventario…",title:"Reposición de inventario",shortDescription:"Necesidades de compra vinculadas a stock real.",noPermission:"Tu perfil no tiene permiso para operar Inventario.",description:"Del stock mínimo a Compras, orden, recepción e ingreso, conservando una sola necesidad activa por SKU.",refresh:"Actualizar",stock:"Stock",loadError:"No fue posible cargar las necesidades de reposición.",quantityError:"La cantidad solicitada debe ser mayor que cero.",requestError:"No fue posible crear la solicitud de compra.",requestSent:"Solicitud enviada a Compras",requestLinked:"La necesidad quedó vinculada a la requisición",toRequest:"Por solicitar",approval:"En aprobación",orderReceiving:"Orden / recepción",fulfilled:"Repuestas",chain:"Cadena operacional",chainDescription:"No se crean compras por simulación: el ciclo nace únicamente cuando un SKU real queda en o bajo su mínimo configurado.",stage1:"1. Stock",stage1d:"Detecta mínimo y cantidad sugerida.",stage2:"2. Requisición",stage2d:"Inventario envía una sola solicitud idempotente.",stage3:"3. Compra",stage3d:"Aprobación, cotización y orden siguen en Procurement.",stage4:"4. Recepción",stage4d:"Recepción parcial/total mantiene trazabilidad.",stage5:"5. Ingreso",stage5d:"El ingreso repone el mismo SKU y cierra el ciclo.",active:"Activas",history:"Historial",requests:"Solicitudes",approvals:"Aprobaciones",receiving:"Recepción",intake:"Ingreso",loading:"Cargando necesidades de reposición…",emptyActive:"No hay necesidades de reposición activas.",emptyAll:"No hay necesidades de reposición registradas.",emptyHint:"Cuando exista stock consumible real y una posición alcance su mínimo configurado, el sistema abrirá la necesidad automáticamente. No se crean registros de demostración.",needs:"Necesidades",needsDescription:"Una necesidad activa por SKU y ubicación.",skuUnavailable:"SKU no disponible",warehouse:"Bodega",locationUnavailable:"Ubicación no disponible",current:"Actual",minimum:"Mínimo",suggested:"Sugerido",control:"Control de la necesidad",selectNeed:"Selecciona una necesidad.",selectTrace:"Selecciona una necesidad para revisar su trazabilidad.",opened:"Abierta",triggerQty:"Cantidad al disparar",suggestedQty:"Reposición sugerida",requestedQty:"Cantidad a solicitar",requiredDate:"Fecha requerida",priority:"Prioridad",low:"Baja",normal:"Normal",high:"Alta",critical:"Crítica",sending:"Enviando…",createRequest:"Crear solicitud de compra",idempotent:"Si esta necesidad ya tiene una solicitud vinculada, el RPC devuelve la misma y no duplica la requisición.",request:"Solicitud",order:"Orden",requestedAmount:"Cantidad solicitada",lastResult:"Último resultado"},
 de:{access:"Inventarzugriff wird geprüft…",title:"Inventarnachschub",shortDescription:"Beschaffungsbedarfe auf Basis realer Bestände.",noPermission:"Dein Profil darf das Inventar nicht operativ bearbeiten.",description:"Vom Mindestbestand über Beschaffung, Bestellung, Wareneingang und Inventaraufnahme – mit genau einem aktiven Bedarf pro SKU.",refresh:"Aktualisieren",stock:"Bestand",loadError:"Die Nachschubbedarfe konnten nicht geladen werden.",quantityError:"Die angeforderte Menge muss größer als null sein.",requestError:"Die Beschaffungsanforderung konnte nicht erstellt werden.",requestSent:"Anforderung an Procurement gesendet",requestLinked:"Der Bedarf ist mit der Anforderung verknüpft",toRequest:"Zu beantragen",approval:"In Genehmigung",orderReceiving:"Bestellung / Wareneingang",fulfilled:"Aufgefüllt",chain:"Betriebskette",chainDescription:"Beschaffungen werden nicht simuliert: Der Zyklus beginnt nur, wenn ein realer SKU seinen konfigurierten Mindestbestand erreicht oder unterschreitet.",stage1:"1. Bestand",stage1d:"Erkennt Mindestbestand und vorgeschlagene Menge.",stage2:"2. Anforderung",stage2d:"Inventar sendet genau eine idempotente Anforderung.",stage3:"3. Beschaffung",stage3d:"Genehmigung, Angebot und Bestellung bleiben in Procurement.",stage4:"4. Wareneingang",stage4d:"Teil- oder Vollwareneingang erhält die Rückverfolgbarkeit.",stage5:"5. Inventaraufnahme",stage5d:"Die Aufnahme füllt denselben SKU auf und schließt den Zyklus.",active:"Aktiv",history:"Verlauf",requests:"Anforderungen",approvals:"Genehmigungen",receiving:"Wareneingang",intake:"Aufnahme",loading:"Nachschubbedarfe werden geladen…",emptyActive:"Keine aktiven Nachschubbedarfe.",emptyAll:"Keine Nachschubbedarfe erfasst.",emptyHint:"Wenn realer Verbrauchsbestand den konfigurierten Mindestbestand erreicht, öffnet das System den Bedarf automatisch. Es werden keine Demodatensätze erzeugt.",needs:"Bedarfe",needsDescription:"Ein aktiver Bedarf pro SKU und Standort.",skuUnavailable:"SKU nicht verfügbar",warehouse:"Lager",locationUnavailable:"Standort nicht verfügbar",current:"Aktuell",minimum:"Minimum",suggested:"Vorgeschlagen",control:"Bedarfssteuerung",selectNeed:"Bedarf auswählen.",selectTrace:"Wähle einen Bedarf aus, um seine Rückverfolgbarkeit zu prüfen.",opened:"Geöffnet",triggerQty:"Menge beim Auslösen",suggestedQty:"Vorgeschlagener Nachschub",requestedQty:"Anzufordernde Menge",requiredDate:"Benötigt am",priority:"Priorität",low:"Niedrig",normal:"Normal",high:"Hoch",critical:"Kritisch",sending:"Wird gesendet…",createRequest:"Beschaffungsanforderung erstellen",idempotent:"Ist dieser Bedarf bereits mit einer Anforderung verknüpft, liefert der RPC dieselbe zurück und erzeugt kein Duplikat.",request:"Anforderung",order:"Bestellung",requestedAmount:"Angeforderte Menge",lastResult:"Letztes Ergebnis"}
} as const
const STATUS={
 en:{open:{label:"Open need",detail:"Stock is below minimum; no procurement request exists yet."},requested:{label:"Request sent",detail:"The requisition is in Procurement and awaits a decision."},approved:{label:"Approved",detail:"Procurement can quote and select a supplier."},ordered:{label:"Ordered",detail:"A linked purchase order exists."},receiving:{label:"Receiving",detail:"The purchase arrived partially or fully and awaits intake closure."},fulfilled:{label:"Replenished",detail:"Intake was applied to the source SKU."},rejected:{label:"Rejected",detail:"The request was rejected; a new need can open if stock remains low."},cancelled:{label:"Cancelled",detail:"The order or cycle was cancelled."}},
 es:{open:{label:"Necesidad abierta",detail:"Stock bajo mínimo; todavía no existe solicitud de compra."},requested:{label:"Solicitud enviada",detail:"La requisición ya está en Compras y espera decisión."},approved:{label:"Aprobada",detail:"Compras puede cotizar y seleccionar proveedor."},ordered:{label:"Ordenada",detail:"Existe una orden de compra vinculada."},receiving:{label:"En recepción",detail:"La compra llegó total o parcialmente y espera cierre de ingreso."},fulfilled:{label:"Repuesta",detail:"El ingreso quedó aplicado al SKU de origen."},rejected:{label:"Rechazada",detail:"La solicitud de compra fue rechazada; una nueva necesidad puede abrirse si el stock sigue bajo."},cancelled:{label:"Cancelada",detail:"La orden o el ciclo fue cancelado."}},
 de:{open:{label:"Offener Bedarf",detail:"Bestand unter Minimum; noch keine Beschaffungsanforderung vorhanden."},requested:{label:"Anforderung gesendet",detail:"Die Anforderung liegt in Procurement und wartet auf Entscheidung."},approved:{label:"Genehmigt",detail:"Procurement kann Angebote einholen und einen Lieferanten auswählen."},ordered:{label:"Bestellt",detail:"Eine verknüpfte Bestellung existiert."},receiving:{label:"Im Wareneingang",detail:"Die Beschaffung ist teilweise oder vollständig eingetroffen und wartet auf Abschluss der Aufnahme."},fulfilled:{label:"Aufgefüllt",detail:"Die Aufnahme wurde auf den Ursprungs-SKU angewendet."},rejected:{label:"Abgelehnt",detail:"Die Anforderung wurde abgelehnt; bei weiterhin niedrigem Bestand kann ein neuer Bedarf entstehen."},cancelled:{label:"Storniert",detail:"Bestellung oder Zyklus wurde storniert."}}
} as const

function firstRelation<T>(value:T|T[]|null|undefined):T|null{return Array.isArray(value)?value[0]??null:value??null}
function asNumber(value:unknown){const parsed=Number(value);return Number.isFinite(parsed)?parsed:0}

export default function InventoryReplenishmentPage(){
 const {language}=useLanguage();const copy=COPY[language];const statusCopy=STATUS[language];const locale=LOCALES[language];const number=useMemo(()=>new Intl.NumberFormat(locale),[locale]);const dateTime=useMemo(()=>new Intl.DateTimeFormat(locale,{dateStyle:"short",timeStyle:"short"}),[locale]);const localize=(href:string)=>`/${language}${href}`
 const supabase=useMemo(()=>createBrowserClient(),[]);const {toast}=useToast();const {loading:accessLoading,can,canAccessDepartment}=useEffectiveAccess();const canOperate=can("inventory.process")&&canAccessDepartment("inventory")
 const [needs,setNeeds]=useState<Need[]>([]);const [selectedId,setSelectedId]=useState("");const [requestedQuantity,setRequestedQuantity]=useState("");const [requiredDate,setRequiredDate]=useState("");const [priority,setPriority]=useState("normal");const [statusFilter,setStatusFilter]=useState<"active"|"all">("active");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{if(accessLoading)return;if(!canOperate){setNeeds([]);setLoading(false);return}setLoading(true);setError(null);const {data,error:loadError}=await supabase.from("inventory_replenishment_needs").select("id,status,trigger_quantity,minimum_stock,suggested_quantity,requested_quantity,procurement_request_id,purchase_order_id,opened_at,requested_at,approved_at,ordered_at,receiving_at,fulfilled_at,resolution_reason,inventory_stock_items(id,item_code,name,unit,quantity_on_hand,minimum_stock,reorder_quantity,unit_cost,warehouse_location:warehouse_locations(name,warehouse:warehouses(name))),procurement_requests(id,request_number,status),procurement_purchase_orders(id,order_number,status)").order("opened_at",{ascending:false}).limit(100)
 if(loadError){console.error("[inventory-replenishment] load failed",loadError);setError(copy.loadError);setNeeds([])}else{const normalized=((data??[]) as unknown as RawNeed[]).map(row=>{const stock=firstRelation(row.inventory_stock_items);return {...row,trigger_quantity:asNumber(row.trigger_quantity),minimum_stock:asNumber(row.minimum_stock),suggested_quantity:asNumber(row.suggested_quantity),requested_quantity:row.requested_quantity==null?null:asNumber(row.requested_quantity),stock_item:stock?{...stock,quantity_on_hand:asNumber(stock.quantity_on_hand),minimum_stock:asNumber(stock.minimum_stock),reorder_quantity:asNumber(stock.reorder_quantity),unit_cost:stock.unit_cost==null?null:asNumber(stock.unit_cost),warehouse_location:firstRelation(stock.warehouse_location as unknown as StockItem["warehouse_location"]|StockItem["warehouse_location"][])}:null,request:firstRelation(row.procurement_requests),order:firstRelation(row.procurement_purchase_orders)} satisfies Need});setNeeds(normalized);setSelectedId(current=>current&&normalized.some(need=>need.id===current)?current:normalized.find(need=>need.status==="open")?.id??normalized[0]?.id??"")}setLoading(false)},[accessLoading,canOperate,copy.loadError,supabase])
 useEffect(()=>{void load()},[load]);const selected=needs.find(need=>need.id===selectedId)??null;useEffect(()=>{if(!selected)return;setRequestedQuantity(String(selected.requested_quantity??selected.suggested_quantity));setRequiredDate("");setPriority(selected.stock_item?.quantity_on_hand===0?"high":"normal")},[selected])
 const activeStatuses:NeedStatus[]=["open","requested","approved","ordered","receiving"];const visibleNeeds=statusFilter==="active"?needs.filter(need=>activeStatuses.includes(need.status)):needs;const metrics={open:needs.filter(n=>n.status==="open").length,requested:needs.filter(n=>["requested","approved"].includes(n.status)).length,ordered:needs.filter(n=>["ordered","receiving"].includes(n.status)).length,fulfilled:needs.filter(n=>n.status==="fulfilled").length}
 async function createRequest(){if(!selected||selected.status!=="open"||saving)return;const quantity=Number(requestedQuantity);if(!Number.isFinite(quantity)||quantity<=0){setError(copy.quantityError);return}setSaving(true);setError(null);const {data,error:rpcError}=await supabase.rpc("create_procurement_request_from_replenishment",{p_need_id:selected.id,p_requested_quantity:quantity,p_required_date:requiredDate||null,p_priority:priority});setSaving(false);if(rpcError){console.error("[inventory-replenishment] request failed",rpcError);setError(copy.requestError);return}toast({title:copy.requestSent,description:`${copy.requestLinked} ${String(data).slice(0,8)}…`});await load()}
 const formatDate=(value:string|null)=>value?dateTime.format(new Date(value)):"—"
 if(accessLoading)return <AppLayout><div className="p-8 text-sm text-muted-foreground">{copy.access}</div></AppLayout>
 if(!canOperate)return <AppLayout><PageHeader title={copy.title} description={copy.shortDescription}/><div className="p-4 sm:p-8"><Card><CardContent className="p-8 text-center text-sm text-muted-foreground">{copy.noPermission}</CardContent></Card></div></AppLayout>
 return <AppLayout><PageHeader title={copy.title} description={copy.description} actions={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>{copy.refresh}</Button><Button variant="outline" asChild><Link href={localize("/inventory/stock")}><ArrowLeft className="mr-2 h-4 w-4"/>{copy.stock}</Link></Button></div>}/><div className="space-y-6 p-4 sm:p-8">
  {error&&<Card className="border-destructive/50"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label={copy.toRequest} value={metrics.open} alert={metrics.open>0} locale={locale}/><Metric label={copy.approval} value={metrics.requested} locale={locale}/><Metric label={copy.orderReceiving} value={metrics.ordered} locale={locale}/><Metric label={copy.fulfilled} value={metrics.fulfilled} locale={locale}/></div>
  <Card><CardHeader><CardTitle className="text-base">{copy.chain}</CardTitle><CardDescription>{copy.chainDescription}</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-5"><Stage icon={PackageSearch} title={copy.stage1} detail={copy.stage1d}/><Stage icon={ClipboardList} title={copy.stage2} detail={copy.stage2d}/><Stage icon={ShoppingCart} title={copy.stage3} detail={copy.stage3d}/><Stage icon={Truck} title={copy.stage4} detail={copy.stage4d}/><Stage icon={CheckCircle2} title={copy.stage5} detail={copy.stage5d}/></CardContent></Card>
  <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><Button size="sm" variant={statusFilter==="active"?"default":"outline"} onClick={()=>setStatusFilter("active")}>{copy.active}</Button><Button size="sm" variant={statusFilter==="all"?"default":"outline"} onClick={()=>setStatusFilter("all")}>{copy.history}</Button></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" asChild><Link href={localize("/procurement/requests")}>{copy.requests}</Link></Button><Button variant="outline" size="sm" asChild><Link href={localize("/procurement/approvals")}>{copy.approvals}</Link></Button><Button variant="outline" size="sm" asChild><Link href={localize("/procurement/receiving")}>{copy.receiving}</Link></Button><Button variant="outline" size="sm" asChild><Link href={localize("/inventory/intake")}>{copy.intake}</Link></Button></div></div>
  {loading?<Card><CardContent className="p-10 text-center text-sm text-muted-foreground">{copy.loading}</CardContent></Card>:visibleNeeds.length===0?<Card><CardContent className="p-10 text-center"><PackageSearch className="mx-auto h-7 w-7 text-muted-foreground"/><p className="mt-3 font-medium">{statusFilter==="active"?copy.emptyActive:copy.emptyAll}</p><p className="mx-auto mt-1 max-w-2xl text-sm text-muted-foreground">{copy.emptyHint}</p></CardContent></Card>:<div className="grid gap-4 xl:grid-cols-[1.15fr_0.85fr]">
   <Card><CardHeader><CardTitle className="text-base">{copy.needs}</CardTitle><CardDescription>{copy.needsDescription}</CardDescription></CardHeader><CardContent className="space-y-2">{visibleNeeds.map(need=>{const stock=need.stock_item;const selectedRow=need.id===selectedId;return <button key={need.id} type="button" onClick={()=>setSelectedId(need.id)} className={`w-full rounded-lg border p-4 text-left transition-colors hover:bg-muted/40 ${selectedRow?"border-primary bg-muted/30":""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{stock?`${stock.item_code} · ${stock.name}`:copy.skuUnavailable}</p><p className="mt-1 text-xs text-muted-foreground">{stock?.warehouse_location?`${stock.warehouse_location.warehouse?.name??copy.warehouse} · ${stock.warehouse_location.name}`:copy.locationUnavailable}</p></div><Badge variant={need.status==="open"?"destructive":"outline"}>{statusCopy[need.status].label}</Badge></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><span>{copy.current}: <strong>{number.format(stock?.quantity_on_hand??need.trigger_quantity)} {stock?.unit??""}</strong></span><span>{copy.minimum}: <strong>{number.format(need.minimum_stock)}</strong></span><span>{copy.suggested}: <strong>{number.format(need.suggested_quantity)}</strong></span></div></button>})}</CardContent></Card>
   <Card><CardHeader><CardTitle className="text-base">{copy.control}</CardTitle><CardDescription>{selected?statusCopy[selected.status].detail:copy.selectNeed}</CardDescription></CardHeader><CardContent className="space-y-4">{!selected?<p className="text-sm text-muted-foreground">{copy.selectTrace}</p>:<><div className="rounded-lg border bg-muted/20 p-4"><p className="font-medium">{selected.stock_item?.name??"SKU"}</p><p className="mt-1 text-sm text-muted-foreground">{copy.opened} {formatDate(selected.opened_at)} · {selected.stock_item?.item_code}</p><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-muted-foreground">{copy.triggerQty}</p><p className="font-medium">{number.format(selected.trigger_quantity)}</p></div><div><p className="text-xs text-muted-foreground">{copy.suggestedQty}</p><p className="font-medium">{number.format(selected.suggested_quantity)} {selected.stock_item?.unit}</p></div></div></div>
    {selected.status==="open"?<div className="space-y-3 rounded-lg border p-4"><div><label className="text-sm font-medium">{copy.requestedQty}</label><Input type="number" min="0.01" step="0.01" value={requestedQuantity} onChange={e=>setRequestedQuantity(e.target.value)}/></div><div className="grid gap-3 sm:grid-cols-2"><div><label className="text-sm font-medium">{copy.requiredDate}</label><Input type="date" value={requiredDate} onChange={e=>setRequiredDate(e.target.value)}/></div><div><label className="text-sm font-medium">{copy.priority}</label><select value={priority} onChange={e=>setPriority(e.target.value)} className="mt-1 w-full rounded-md border bg-background px-3 py-2 text-sm"><option value="low">{copy.low}</option><option value="normal">{copy.normal}</option><option value="high">{copy.high}</option><option value="critical">{copy.critical}</option></select></div></div><Button className="w-full" onClick={()=>void createRequest()} disabled={saving}>{saving?copy.sending:copy.createRequest}</Button><p className="text-xs text-muted-foreground">{copy.idempotent}</p></div>:<div className="space-y-3 rounded-lg border p-4 text-sm"><Trace label={copy.request} value={selected.request?.request_number??selected.procurement_request_id??"—"} state={selected.request?.status}/><Trace label={copy.order} value={selected.order?.order_number??selected.purchase_order_id??"—"} state={selected.order?.status}/><Trace label={copy.requestedAmount} value={selected.requested_quantity==null?"—":`${number.format(selected.requested_quantity)} ${selected.stock_item?.unit??""}`}/><Trace label={copy.lastResult} value={selected.resolution_reason??statusCopy[selected.status].detail}/></div>}</>}</CardContent></Card>
  </div>}
 </div></AppLayout>
}
function Metric({label,value,alert=false,locale}:{label:string;value:number;alert?:boolean;locale:string}){return <Card className={alert?"border-amber-300":undefined}><CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">{label}</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{new Intl.NumberFormat(locale).format(value)}</div></CardContent></Card>}
function Stage({icon:Icon,title,detail}:{icon:typeof PackageSearch;title:string;detail:string}){return <div className="rounded-lg border p-3"><Icon className="h-4 w-4 text-muted-foreground"/><p className="mt-3 text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>}
function Trace({label,value,state}:{label:string;value:string;state?:string}){return <div className="flex items-start justify-between gap-3 border-b pb-2 last:border-0 last:pb-0"><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-0.5 break-all font-medium">{value}</p></div>{state&&<Badge variant="outline">{state}</Badge>}</div>}
