"use client"

import Link from "next/link"
import { ArrowLeft, CheckCircle2, FileClock, ShieldCheck } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { useLanguage } from "@/lib/hooks/use-language"

type Source = { table:string; count:number; failed:boolean }
const META = {
 en:{approver_audit_log:["Procurement approvals","Actions executed by approvers on procurement requests.","Associated approver or admin read; admin and approver insert; no UPDATE, DELETE or TRUNCATE."],procurement_audit_log:["Procurement flow","Changes and actions associated with procurement entities.","Authenticated read; admin and approver insert; no UPDATE, DELETE or TRUNCATE."],audit_actions:["Hospitality actions","Events related to reservations, leads and automations.","Authenticated read and insert only; no UPDATE, DELETE or TRUNCATE."]},
 es:{approver_audit_log:["Aprobaciones de compras","Acciones ejecutadas por aprobadores sobre solicitudes de compra.","Lectura del aprobador asociado o admin; inserción para admin y approver; sin UPDATE, DELETE ni TRUNCATE."],procurement_audit_log:["Flujo de abastecimiento","Cambios y acciones asociados al proceso de compras y sus entidades.","Lectura autenticada; inserción para admin y approver; sin UPDATE, DELETE ni TRUNCATE."],audit_actions:["Acciones de hospitalidad","Eventos vinculados a reservas, leads y automatizaciones.","Solo lectura e inserción autenticada; sin UPDATE, DELETE ni TRUNCATE."]},
 de:{approver_audit_log:["Beschaffungsfreigaben","Aktionen von Freigebenden auf Beschaffungsanforderungen.","Lesen durch zugehörige Freigebende oder Admin; Einfügen für Admin und approver; kein UPDATE, DELETE oder TRUNCATE."],procurement_audit_log:["Beschaffungsablauf","Änderungen und Aktionen im Beschaffungsprozess und seinen Entitäten.","Authentifiziertes Lesen; Einfügen für Admin und approver; kein UPDATE, DELETE oder TRUNCATE."],audit_actions:["Hospitality-Aktionen","Ereignisse zu Reservierungen, Leads und Automatisierungen.","Nur authentifiziertes Lesen und Einfügen; kein UPDATE, DELETE oder TRUNCATE."]},
} as const
const APPEND=[
 ["activity_logs",0,"activity"],["ai_operation_logs",8,"ai"],["asset_logs",0,"assets"],["audit_actions",0,"hospitality"],["multimedia_asset_logs",0,"media"],["reservation_history",0,"reservations"],["task_status_history",0,"tasks"],["approver_audit_log",0,"approvals"],["procurement_audit_log",0,"procurement"],
] as const
const COPY={
 en:{title:"Administrative audit",description:"Verifiable status of traceability sources and production access controls.",back:"Back to Administration",primary:"Primary sources",primaryDetail:"Records available in the three administrative sources.",records:"Records found",protected:"Protected logs",protectedDetail:"Nine sources verified as append-only.",protectedRecords:"8 records, all in ai_operation_logs",integrity:"Integrity control",integrityDetail:"Permissions verified after migrations.",appendOnly:"Append-only logs",integrityText:"Authorized users may query and append events, but cannot modify, delete or truncate existing records.",hardened:"Procurement audit hardened",hardenedDetail:"Migration applied without modifying existing events.",hard1:"approver_audit_log and procurement_audit_log no longer allow anonymous access or event alteration.",hard2:"start_procurement_quotation, build_procurement_comparison and approve_procurement_comparison retain authenticated execution and internal role validation, and are not executable by anon.",hard3:"The actual writers of procurement_audit_log are those three functions. No active writer for approver_audit_log was identified in indexed code or database functions.",adminSources:"Administrative sources",sourceError:"This source could not be queried.",verified:"Query verified",table:"Table",purpose:"Purpose",permissions:"Permissions",selectInsert:"Controlled SELECT + INSERT",scope:"Current scope",scope1:"The view does not expose user names, emails, phone numbers or identifiers.",scope2:"Migrations did not create, modify or delete existing events.",scope3:"Next: register and verify coverage for bulk deletion, permissions, KMZ and financial changes.",activity:"Activity changes",ai:"Agent executions and messages",assets:"Asset history",hospitality:"Hospitality actions",media:"Multimedia asset changes",reservations:"Reservation history",tasks:"Task status changes",approvals:"Procurement approver actions",procurement:"Procurement-flow events"},
 es:{title:"Auditoría administrativa",description:"Estado verificable de las fuentes de trazabilidad y sus controles de acceso en producción.",back:"Volver a Administración",primary:"Fuentes principales",primaryDetail:"Registros disponibles en las tres fuentes administrativas.",records:"Registros encontrados",protected:"Bitácoras protegidas",protectedDetail:"Nueve fuentes verificadas como append-only.",protectedRecords:"8 registros, todos en ai_operation_logs",integrity:"Control de integridad",integrityDetail:"Permisos verificados después de las migraciones.",appendOnly:"Bitácoras append-only",integrityText:"Los usuarios autorizados pueden consultar y agregar eventos, pero no modificar, borrar ni truncar registros existentes.",hardened:"Auditoría de compras endurecida",hardenedDetail:"Migración aplicada sin modificar eventos existentes.",hard1:"approver_audit_log y procurement_audit_log ya no permiten acceso anónimo ni alteración de eventos.",hard2:"start_procurement_quotation, build_procurement_comparison y approve_procurement_comparison conservan ejecución autenticada, mantienen su validación interna de rol y ya no son ejecutables por anon.",hard3:"Los escritores reales de procurement_audit_log son esas tres funciones. No se identificó un escritor activo para approver_audit_log en el código indexado o en funciones de base de datos.",adminSources:"Fuentes administrativas",sourceError:"No fue posible consultar esta fuente.",verified:"Consulta verificada",table:"Tabla",purpose:"Propósito",permissions:"Permisos",selectInsert:"SELECT + INSERT controlado",scope:"Alcance actual",scope1:"La vista no expone nombres, correos, teléfonos ni identificadores de usuarios.",scope2:"Las migraciones no crearon, modificaron ni eliminaron eventos existentes.",scope3:"El siguiente paso es registrar y verificar cobertura para borrados masivos, permisos, KMZ y modificaciones financieras.",activity:"Cambios en actividades",ai:"Ejecuciones y mensajes de agentes",assets:"Historial de activos",hospitality:"Acciones de hospitalidad",media:"Cambios en activos multimedia",reservations:"Historial de reservas",tasks:"Cambios de estado de tareas",approvals:"Acciones de aprobadores de compras",procurement:"Eventos del flujo de abastecimiento"},
 de:{title:"Administrative Prüfung",description:"Prüfbarer Status der Nachvollziehbarkeitsquellen und ihrer Produktionszugriffskontrollen.",back:"Zurück zur Administration",primary:"Primärquellen",primaryDetail:"Datensätze in den drei administrativen Quellen.",records:"Gefundene Datensätze",protected:"Geschützte Protokolle",protectedDetail:"Neun Quellen als append-only verifiziert.",protectedRecords:"8 Datensätze, alle in ai_operation_logs",integrity:"Integritätskontrolle",integrityDetail:"Berechtigungen nach den Migrationen verifiziert.",appendOnly:"Append-only-Protokolle",integrityText:"Autorisierte Nutzer dürfen Ereignisse lesen und hinzufügen, bestehende Datensätze jedoch nicht ändern, löschen oder truncaten.",hardened:"Beschaffungsaudit gehärtet",hardenedDetail:"Migration ohne Änderung bestehender Ereignisse angewendet.",hard1:"approver_audit_log und procurement_audit_log erlauben keinen anonymen Zugriff oder Änderungen an Ereignissen mehr.",hard2:"start_procurement_quotation, build_procurement_comparison und approve_procurement_comparison behalten authentifizierte Ausführung und interne Rollenprüfung und sind für anon nicht ausführbar.",hard3:"Die tatsächlichen Schreiber von procurement_audit_log sind diese drei Funktionen. Für approver_audit_log wurde kein aktiver Schreiber im indexierten Code oder in Datenbankfunktionen gefunden.",adminSources:"Administrative Quellen",sourceError:"Diese Quelle konnte nicht abgefragt werden.",verified:"Abfrage verifiziert",table:"Tabelle",purpose:"Zweck",permissions:"Berechtigungen",selectInsert:"Kontrolliertes SELECT + INSERT",scope:"Aktueller Umfang",scope1:"Die Ansicht zeigt keine Namen, E-Mails, Telefonnummern oder Nutzerkennungen.",scope2:"Die Migrationen haben keine bestehenden Ereignisse erstellt, verändert oder gelöscht.",scope3:"Nächster Schritt: Abdeckung für Massenlöschungen, Berechtigungen, KMZ und finanzielle Änderungen erfassen und prüfen.",activity:"Änderungen an Aktivitäten",ai:"Agentenausführungen und Nachrichten",assets:"Anlagenverlauf",hospitality:"Hospitality-Aktionen",media:"Änderungen an Multimedia-Assets",reservations:"Reservierungsverlauf",tasks:"Änderungen am Aufgabenstatus",approvals:"Aktionen von Beschaffungsfreigebenden",procurement:"Ereignisse des Beschaffungsablaufs"},
} as const

export function AdminAuditView({sources}:{sources:Source[]}){
 const {language}=useLanguage();const lang=(language in COPY?language:"en") as keyof typeof COPY;const copy=COPY[lang];const locale=lang==="es"?"es-CL":lang==="de"?"de-DE":"en-US";const number=new Intl.NumberFormat(locale);const total=sources.reduce((n,s)=>n+s.count,0);const appendTotal=APPEND.reduce((n,s)=>n+s[1],0)
 return <AppLayout><PageHeader title={copy.title} description={copy.description}/><div className="space-y-6 p-4 md:p-8"><Link href="/admin" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4"/>{copy.back}</Link>
 <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2"><FileClock className="h-5 w-5"/>{copy.primary}</CardTitle><CardDescription>{copy.primaryDetail}</CardDescription></CardHeader><CardContent><p className="text-3xl font-semibold">{number.format(total)}</p><p className="mt-2 text-sm text-muted-foreground">{copy.records}</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><FileClock className="h-5 w-5"/>{copy.protected}</CardTitle><CardDescription>{copy.protectedDetail}</CardDescription></CardHeader><CardContent><p className="text-3xl font-semibold">{number.format(appendTotal)}</p><p className="mt-2 text-sm text-muted-foreground">{copy.protectedRecords}</p></CardContent></Card><Card className="border-emerald-500/40"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/>{copy.integrity}</CardTitle><CardDescription>{copy.integrityDetail}</CardDescription></CardHeader><CardContent className="space-y-3"><Badge variant="secondary">{copy.appendOnly}</Badge><p className="text-sm">{copy.integrityText}</p></CardContent></Card></div>
 <Card className="border-emerald-500/40"><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5"/>{copy.hardened}</CardTitle><CardDescription>{copy.hardenedDetail}</CardDescription></CardHeader><CardContent className="space-y-2 text-sm"><p>{copy.hard1}</p><p>{copy.hard2}</p><p className="text-muted-foreground">{copy.hard3}</p></CardContent></Card>
 <section className="space-y-3"><h2 className="text-lg font-semibold">{copy.adminSources}</h2><div className="grid gap-4 lg:grid-cols-3">{sources.map(source=>{const meta=META[lang][source.table as keyof (typeof META)[typeof lang]];return <Card key={source.table}><CardHeader><CardTitle className="text-base">{meta[0]}</CardTitle><CardDescription>{meta[1]}</CardDescription></CardHeader><CardContent className="space-y-3"><p className="text-2xl font-semibold">{number.format(source.count)}</p><p className="font-mono text-xs text-muted-foreground">{source.table}</p><p className="text-xs text-muted-foreground">{meta[2]}</p>{source.failed?<p className="text-xs text-destructive">{copy.sourceError}</p>:<Badge variant="secondary">{copy.verified}</Badge>}</CardContent></Card>})}</div></section>
 <Card><CardHeader><CardTitle>{copy.protected}</CardTitle><CardDescription>{copy.integrityDetail}</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b text-left"><th className="p-3">{copy.table}</th><th className="p-3">{copy.records}</th><th className="p-3">{copy.purpose}</th><th className="p-3">{copy.permissions}</th></tr></thead><tbody>{APPEND.map(([table,records,key])=><tr key={table} className="border-b last:border-0"><td className="p-3 font-mono text-xs">{table}</td><td className="p-3">{number.format(records)}</td><td className="p-3 text-muted-foreground">{copy[key]}</td><td className="p-3">{copy.selectInsert}</td></tr>)}</tbody></table></CardContent></Card>
 <Card><CardHeader><CardTitle>{copy.scope}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-muted-foreground"><p>{copy.scope1}</p><p>{copy.scope2}</p><p>{copy.scope3}</p></CardContent></Card>
 </div></AppLayout>
}
