"use client"

import Link from "next/link"
import { AlertTriangle, ArrowLeft, BedDouble, CalendarDays, ClipboardCheck, ConciergeBell, History, MapPin, PackageSearch, Wrench } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { useLanguage } from "@/lib/hooks/use-language"

export type BookingRoomObjectData={room:{id:string;room_number:string;room_type:string|null;capacity:number|null;status:string|null;operational_status:string|null;location:string|null;floor:string|null;bed_type:string|null;amenities:string[]|null;notes:string|null};state:{reservation_status:string|null;housekeeping_status:string|null;maintenance_status:string|null;availability_status:string|null;current_reservation_id:string|null;guest_name:string|null;check_in:string|null;check_out:string|null}|null;reservations:Array<{id:string;guest_name:string|null;check_in:string;check_out:string;status:string|null;payment_status:string|null;arrival_status:string|null}>;housekeeping:Array<{id:string;task_type:string|null;status:string|null;priority:string|null;service_date:string|null}>;maintenance:Array<{id:string;title:string|null;status:string|null;prioridad:string|null;fecha_objetivo:string|null;bloqueado:boolean|null;asset_id:string|null}>;requests:Array<{id:string;request_type:string|null;category:string|null;description:string|null;status:string|null;priority:string|null;due_at:string|null}>;issues:Array<{id:string;title:string|null;status:string|null;severity:string|null;priority:string|null;created_at:string|null;asset_id:string|null}>;assets:Array<{id:string;name:string;asset_code:string|null;status:string|null;is_critical:boolean|null}>;history:Array<{id:string;previous_status:string|null;new_status:string|null;reason:string|null;source:string|null;created_at:string}>;queryError:boolean}
const COPY={
 en:{back:"Rooms",object:"Object · Room",room:"Room",noState:"no status",floor:"Floor",typeMissing:"Type not recorded",capacity:"Capacity",calendar:"Open calendar",partial:"Part of the related context could not be loaded. The room remains available with data allowed by RLS.",availability:"Availability",reservation:"Reservation",housekeeping:"Housekeeping",maintenance:"Maintenance",noSignal:"no signal",currentReservation:"Current reservation",unknownGuest:"Guest not identified",openReservation:"Open reservation",upcoming:"Upcoming reservations",noUpcoming:"No upcoming reservations visible.",viewAll:"View all",guestMissing:"Reservation without guest",paymentMissing:"payment status missing",openHousekeeping:"Open housekeeping",noHousekeeping:"No open housekeeping.",noDate:"No date",openRequests:"Open requests",noRequests:"No open requests.",request:"Request",noDue:"No due date",openMaintenance:"Open maintenance",noMaintenance:"No open maintenance.",blocked:"Blocked",noTarget:"No target date",assetLinked:"linked asset",openIssues:"Open issues",noIssues:"No open issues.",issue:"Issue",assets:"Related assets",noAssets:"No assets are involved in open work.",noCode:"No code",assetLink:"linked through issue or maintenance",activity:"Room activity",noActivity:"No operational history recorded for this room yet.",system:"system",sheet:"Profile"},
 es:{back:"Habitaciones",object:"Objeto · Habitación",room:"Habitación",noState:"sin estado",floor:"Piso",typeMissing:"Tipo no registrado",capacity:"Capacidad",calendar:"Abrir calendario",partial:"Parte del contexto relacionado no pudo cargarse. La habitación sigue disponible con los datos que sí pasaron RLS.",availability:"Disponibilidad",reservation:"Reserva",housekeeping:"Housekeeping",maintenance:"Mantenimiento",noSignal:"sin señal",currentReservation:"Reserva actual",unknownGuest:"Huésped no identificado",openReservation:"Abrir reserva",upcoming:"Reservas próximas",noUpcoming:"No hay reservas próximas visibles.",viewAll:"Ver todo",guestMissing:"Reserva sin huésped",paymentMissing:"pago sin estado",openHousekeeping:"Housekeeping abierto",noHousekeeping:"Sin housekeeping abierto.",noDate:"Sin fecha",openRequests:"Solicitudes abiertas",noRequests:"Sin solicitudes abiertas.",request:"Solicitud",noDue:"Sin vencimiento",openMaintenance:"Mantenimiento abierto",noMaintenance:"Sin mantenimiento abierto.",blocked:"Bloqueado",noTarget:"Sin fecha objetivo",assetLinked:"activo vinculado",openIssues:"Incidencias abiertas",noIssues:"Sin incidencias abiertas.",issue:"Incidencia",assets:"Activos implicados",noAssets:"No hay activos implicados en trabajo abierto.",noCode:"Sin código",assetLink:"vínculo por incidencia o mantenimiento",activity:"Actividad de la habitación",noActivity:"Todavía no hay historial operacional registrado para esta habitación.",system:"system",sheet:"Ficha"},
 de:{back:"Zimmer",object:"Objekt · Zimmer",room:"Zimmer",noState:"kein Status",floor:"Etage",typeMissing:"Typ nicht erfasst",capacity:"Kapazität",calendar:"Kalender öffnen",partial:"Ein Teil des verknüpften Kontexts konnte nicht geladen werden. Das Zimmer bleibt mit den durch RLS erlaubten Daten verfügbar.",availability:"Verfügbarkeit",reservation:"Reservierung",housekeeping:"Housekeeping",maintenance:"Instandhaltung",noSignal:"kein Signal",currentReservation:"Aktuelle Reservierung",unknownGuest:"Gast nicht identifiziert",openReservation:"Reservierung öffnen",upcoming:"Kommende Reservierungen",noUpcoming:"Keine kommenden Reservierungen sichtbar.",viewAll:"Alle anzeigen",guestMissing:"Reservierung ohne Gast",paymentMissing:"Zahlungsstatus fehlt",openHousekeeping:"Offenes Housekeeping",noHousekeeping:"Kein offenes Housekeeping.",noDate:"Kein Datum",openRequests:"Offene Anfragen",noRequests:"Keine offenen Anfragen.",request:"Anfrage",noDue:"Keine Fälligkeit",openMaintenance:"Offene Instandhaltung",noMaintenance:"Keine offene Instandhaltung.",blocked:"Blockiert",noTarget:"Kein Zieldatum",assetLinked:"Anlage verknüpft",openIssues:"Offene Vorfälle",noIssues:"Keine offenen Vorfälle.",issue:"Vorfall",assets:"Beteiligte Anlagen",noAssets:"Keine Anlagen sind an offenen Arbeiten beteiligt.",noCode:"Kein Code",assetLink:"Verknüpfung über Vorfall oder Instandhaltung",activity:"Zimmeraktivität",noActivity:"Für dieses Zimmer ist noch kein operativer Verlauf erfasst.",system:"system",sheet:"Profil"},
} as const
function statusVariant(value:string|null):"default"|"secondary"|"destructive"|"outline"{const status=value?.toLowerCase()||"";if(["blocked","bloqueado","critical","out_of_service","maintenance"].includes(status))return"destructive";if(["ready","available","completed","resolved","clean"].includes(status))return"secondary";return"outline"}
export function BookingRoomObjectView({data}:{data:BookingRoomObjectData}){
 const{language}=useLanguage();const lang=(language in COPY?language:"en") as keyof typeof COPY;const copy=COPY[lang];const locale=lang==="es"?"es-CL":lang==="de"?"de-DE":"en-US";const number=new Intl.NumberFormat(locale);const date=(value:string|null)=>value?new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeZone:"America/Santiago"}).format(new Date(value.includes("T")?value:`${value}T12:00:00-04:00`)):copy.noDate;const dateTime=(value:string|null)=>value?new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone:"America/Santiago"}).format(new Date(value)):copy.noDate;const{room,state,reservations,housekeeping,maintenance,requests,issues,assets,history,queryError}=data
 return <AppLayout><div className="space-y-6 p-4 md:p-6"><div className="flex flex-col gap-4 border-b pb-5 md:flex-row md:items-end md:justify-between"><div><Link href="/bookings/rooms" className="mb-3 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4"/>{copy.back}</Link><div className="flex flex-wrap items-center gap-3"><div className="flex h-11 w-11 items-center justify-center border border-primary/25 bg-primary/10 text-primary"><BedDouble className="h-5 w-5"/></div><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-primary">{copy.object}</p><h1 className="text-2xl font-semibold">{copy.room} {room.room_number}</h1></div><Badge variant={statusVariant(room.operational_status||room.status)}>{room.operational_status||room.status||copy.noState}</Badge></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-sm text-muted-foreground">{room.location&&<span className="inline-flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5"/>{room.location}</span>}{room.floor&&<span>{copy.floor} {room.floor}</span>}<span>{room.room_type||copy.typeMissing}</span><span>{copy.capacity} {room.capacity==null?"—":number.format(room.capacity)}</span></div></div><Link href="/bookings" className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/90">{copy.calendar}</Link></div>
 {queryError&&<div className="rounded-md border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-amber-700 dark:text-amber-300">{copy.partial}</div>}
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StateCard label={copy.availability} value={state?.availability_status||room.status} empty={copy.noSignal}/><StateCard label={copy.reservation} value={state?.reservation_status} empty={copy.noSignal}/><StateCard label={copy.housekeeping} value={state?.housekeeping_status} empty={copy.noSignal}/><StateCard label={copy.maintenance} value={state?.maintenance_status} empty={copy.noSignal}/></section>
 {state?.current_reservation_id&&<Card className="border-primary/25 bg-primary/5"><CardHeader className="pb-3"><CardTitle className="text-base">{copy.currentReservation}</CardTitle></CardHeader><CardContent className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{state.guest_name||copy.unknownGuest}</p><p className="text-sm text-muted-foreground">{date(state.check_in)} → {date(state.check_out)}</p></div><Link href={`/bookings/reservations/${state.current_reservation_id}`} className="text-sm font-medium text-primary hover:underline">{copy.openReservation}</Link></CardContent></Card>}
 <div className="grid gap-6 xl:grid-cols-2"><ObjectList title={copy.upcoming} icon={<CalendarDays className="h-4 w-4"/>} empty={copy.noUpcoming} href="/bookings" viewAll={copy.viewAll}>{reservations.map(item=><Link key={item.id} href={`/bookings/reservations/${item.id}`} className="flex items-start justify-between gap-3 rounded-md border p-3 hover:bg-muted/40"><div><p className="font-medium">{item.guest_name||copy.guestMissing}</p><p className="mt-1 text-xs text-muted-foreground">{date(item.check_in)} → {date(item.check_out)} · {item.payment_status||copy.paymentMissing}</p></div><Badge variant="outline">{item.arrival_status||item.status||copy.noState}</Badge></Link>)}</ObjectList>
 <ObjectList title={copy.openHousekeeping} icon={<ClipboardCheck className="h-4 w-4"/>} empty={copy.noHousekeeping} href="/bookings/housekeeping" viewAll={copy.viewAll}>{housekeeping.map(item=><CompactRow key={item.id} title={item.task_type||copy.housekeeping} detail={`${item.service_date?date(item.service_date):copy.noDate}${item.priority?` · ${item.priority}`:""}`} status={item.status} empty={copy.noState}/>)}</ObjectList>
 <ObjectList title={copy.openRequests} icon={<ConciergeBell className="h-4 w-4"/>} empty={copy.noRequests} href="/bookings/requests" viewAll={copy.viewAll}>{requests.map(item=><CompactRow key={item.id} title={item.request_type||item.category||copy.request} detail={`${item.due_at?dateTime(item.due_at):copy.noDue}${item.description?` · ${item.description}`:""}`} status={item.priority||item.status} empty={copy.noState}/>)}</ObjectList>
 <ObjectList title={copy.openMaintenance} icon={<Wrench className="h-4 w-4"/>} empty={copy.noMaintenance} href="/maintenance" viewAll={copy.viewAll}>{maintenance.map(item=><CompactRow key={item.id} title={item.title||copy.maintenance} detail={`${item.bloqueado?`${copy.blocked} · `:""}${item.fecha_objetivo?date(item.fecha_objetivo):copy.noTarget}${item.asset_id?` · ${copy.assetLinked}`:""}`} status={item.prioridad||item.status} empty={copy.noState}/>)}</ObjectList>
 <ObjectList title={copy.openIssues} icon={<AlertTriangle className="h-4 w-4"/>} empty={copy.noIssues} href="/issues" viewAll={copy.viewAll}>{issues.map(item=><CompactRow key={item.id} title={item.title||copy.issue} detail={item.created_at?dateTime(item.created_at):copy.noDate} status={item.severity||item.priority||item.status} empty={copy.noState}/>)}</ObjectList>
 <ObjectList title={copy.assets} icon={<PackageSearch className="h-4 w-4"/>} empty={copy.noAssets} href="/assets" viewAll={copy.viewAll}>{assets.map(item=><Link key={item.id} href={`/assets/${item.id}`} className="flex items-start justify-between gap-3 rounded-md border p-3 hover:bg-muted/40"><div><p className="font-medium">{item.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.asset_code||copy.noCode} · {copy.assetLink}</p></div><Badge variant={item.is_critical?"destructive":"outline"}>{item.status||copy.noState}</Badge></Link>)}</ObjectList></div>
 <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><History className="h-4 w-4"/>{copy.activity}</CardTitle></CardHeader><CardContent>{history.length===0?<p className="text-sm text-muted-foreground">{copy.noActivity}</p>:<div className="space-y-3">{history.map(item=><div key={item.id} className="border-l-2 border-border pl-4"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{item.previous_status||"—"} → {item.new_status||"—"}</p><Badge variant="outline">{item.source||copy.system}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{dateTime(item.created_at)}{item.reason?` · ${item.reason}`:""}</p></div>)}</div>}</CardContent></Card>
 {(room.amenities?.length||room.notes)&&<Card><CardHeader><CardTitle className="text-base">{copy.sheet}</CardTitle></CardHeader><CardContent className="space-y-3">{room.amenities?.length?<div className="flex flex-wrap gap-2">{room.amenities.map(item=><Badge key={item} variant="secondary">{item}</Badge>)}</div>:null}{room.notes&&<p className="text-sm text-muted-foreground">{room.notes}</p>}</CardContent></Card>}
 </div></AppLayout>
}
function StateCard({label,value,empty}:{label:string;value:string|null|undefined;empty:string}){return <div className="rounded-lg border p-4"><p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">{label}</p><div className="mt-2"><Badge variant={statusVariant(value||null)}>{value||empty}</Badge></div></div>}
function ObjectList({title,icon,empty,href,children,viewAll}:{title:string;icon:React.ReactNode;empty:string;href:string;children:React.ReactNode;viewAll:string}){const hasChildren=Array.isArray(children)?children.length>0:Boolean(children);return <Card><CardHeader className="pb-3"><div className="flex items-center justify-between gap-3"><CardTitle className="flex items-center gap-2 text-base">{icon}{title}</CardTitle><Link href={href} className="text-xs font-medium text-primary hover:underline">{viewAll}</Link></div></CardHeader><CardContent>{hasChildren?<div className="space-y-2">{children}</div>:<p className="text-sm text-muted-foreground">{empty}</p>}</CardContent></Card>}
function CompactRow({title,detail,status,empty}:{title:string;detail:string;status:string|null;empty:string}){return <div className="flex items-start justify-between gap-3 rounded-md border p-3"><div className="min-w-0"><p className="font-medium">{title}</p><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{detail}</p></div><Badge variant={statusVariant(status)}>{status||empty}</Badge></div>}
