"use client"

import Link from "next/link"
import { AlertTriangle, ArrowLeft, Banknote, BedDouble, ClipboardCheck, FileText, History, MessageSquareText, UserRound, Wrench } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { useLanguage } from "@/lib/hooks/use-language"

export type BookingReservationObjectData = {
  reservation:{id:string;room_id:string|null;guest_id:string|null;guest_name:string|null;guest_email:string|null;guest_phone:string|null;check_in:string;check_out:string;status:string|null;arrival_status:string|null;payment_status:string|null;num_guests:number|null;source:string|null;booking_type:string|null;total_amount:number|string|null;special_requests:string|null;estimated_arrival_time:string|null;estimated_departure_time:string|null;early_check_in_requested:boolean|null;late_check_out_requested:boolean|null}
  room:{id:string;room_number:string;status:string|null;operational_status:string|null;location:string|null}|null
  guest:{id:string;name:string|null;email:string|null;phone:string|null;vip_status:boolean|null;preferred_language:string|null;preferred_contact_channel:string|null;allergies:string|null;mobility_requirements:string|null;housekeeping_preferences:string|null}|null
  payments:Array<{id:string;amount:number|string;payment_method:string|null;payment_status:string|null;paid_at:string|null;created_at:string}>
  invoices:Array<{id:string;invoice_number:string|null;status:string|null;payment_status:string|null;total_amount:number|string|null;balance_due:number|string|null;invoice_date:string|null}>
  housekeeping:Array<{id:string;task_type:string|null;status:string|null;priority:string|null;service_date:string|null;requires_inspection:boolean|null;inspection_status:string|null}>
  maintenance:Array<{id:string;title:string|null;status:string|null;prioridad:string|null;fecha_objetivo:string|null;bloqueado:boolean|null;blocks_room:boolean|null}>
  requests:Array<{id:string;request_type:string|null;category:string|null;description:string|null;priority:string|null;status:string|null;due_at:string|null}>
  exceptions:Array<{source_id:string;domain:string;title:string;status:string;priority:string|null;exception_state:string;blocks_check_in:boolean;blocks_check_out:boolean;detail:string|null}>
  documents:Array<{id:string;document_number:string|null;document_type:string|null;status:string|null;title:string|null;issued_at:string|null}>
  events:Array<{id:string;event_type:string|null;category:string|null;title:string;description:string|null;previous_state:string|null;new_state:string|null;occurred_at:string}>
  queryError:boolean
  paidAmount:number
}

const COPY={
 en:{calendar:"Calendar",object:"Object · Reservation",guestMissing:"Reservation without guest",noState:"no status",guests:"guest(s)",source:"Source",room:"Room",partial:"Part of the related context could not be loaded. The reservation only shows information allowed by RLS.",stay:"Stay",arrival:"Arrival",payment:"Payment",total:"Reservation total",paid:"Recorded payments",attention:"Requires attention",blocksIn:"Blocks check-in",blocksOut:"Blocks check-out",guest:"Guest",unknown:"Not identified",noEmail:"No email",noPhone:"No phone",language:"Language",contact:"Contact",allergies:"Allergies",mobility:"Mobility",housekeepingPref:"Housekeeping",roomStay:"Room and stay",locationMissing:"Location not recorded",openRoom:"Open room object",noRoom:"No room linked.",arrivalEstimate:"Estimated arrival",departureEstimate:"Estimated departure",finance:"Payments and invoices",noFinance:"No financial movements visible.",housekeeping:"Housekeeping",noHousekeeping:"No linked housekeeping.",inspection:"inspection",pending:"pending",maintenance:"Maintenance",noMaintenance:"No linked maintenance.",blocked:"Blocked",blocksRoom:"blocks room",noTarget:"no target date",requests:"Requests",noRequests:"No linked requests.",request:"Request",noDescription:"No description",due:"due",documents:"Documents",noDocuments:"No linked documents.",document:"Document",special:"Special reservation requests",activity:"Reservation activity",noActivity:"No operational events recorded for this reservation yet.",viewAll:"View all",noDate:"No date",balance:"balance",noSignal:"no signal"},
 es:{calendar:"Calendario",object:"Objeto · Reserva",guestMissing:"Reserva sin huésped",noState:"sin estado",guests:"huésped(es)",source:"Fuente",room:"Habitación",partial:"Parte del contexto relacionado no pudo cargarse. La reserva sigue mostrando únicamente la información permitida por RLS.",stay:"Estadía",arrival:"Llegada",payment:"Pago",total:"Total reserva",paid:"Pagos registrados",attention:"Requiere atención",blocksIn:"Bloquea check-in",blocksOut:"Bloquea check-out",guest:"Huésped",unknown:"No identificado",noEmail:"Sin email",noPhone:"Sin teléfono",language:"Idioma",contact:"Contacto",allergies:"Alergias",mobility:"Movilidad",housekeepingPref:"Housekeeping",roomStay:"Habitación y estadía",locationMissing:"Ubicación no registrada",openRoom:"Abrir objeto habitación",noRoom:"No hay habitación vinculada.",arrivalEstimate:"Llegada estimada",departureEstimate:"Salida estimada",finance:"Pagos e invoices",noFinance:"Sin movimientos financieros visibles.",housekeeping:"Housekeeping",noHousekeeping:"Sin housekeeping vinculado.",inspection:"inspección",pending:"pendiente",maintenance:"Mantenimiento",noMaintenance:"Sin mantenimiento vinculado.",blocked:"Bloqueado",blocksRoom:"bloquea habitación",noTarget:"sin fecha objetivo",requests:"Solicitudes",noRequests:"Sin solicitudes vinculadas.",request:"Solicitud",noDescription:"Sin descripción",due:"vence",documents:"Documentos",noDocuments:"Sin documentos vinculados.",document:"Documento",special:"Solicitudes especiales de la reserva",activity:"Actividad de la reserva",noActivity:"Todavía no hay eventos operacionales registrados para esta reserva.",viewAll:"Ver todo",noDate:"Sin fecha",balance:"saldo",noSignal:"sin señal"},
 de:{calendar:"Kalender",object:"Objekt · Reservierung",guestMissing:"Reservierung ohne Gast",noState:"kein Status",guests:"Gast/Gäste",source:"Quelle",room:"Zimmer",partial:"Ein Teil des verknüpften Kontexts konnte nicht geladen werden. Die Reservierung zeigt nur Informationen, die durch RLS erlaubt sind.",stay:"Aufenthalt",arrival:"Ankunft",payment:"Zahlung",total:"Reservierung gesamt",paid:"Erfasste Zahlungen",attention:"Aufmerksamkeit erforderlich",blocksIn:"Blockiert Check-in",blocksOut:"Blockiert Check-out",guest:"Gast",unknown:"Nicht identifiziert",noEmail:"Keine E-Mail",noPhone:"Kein Telefon",language:"Sprache",contact:"Kontakt",allergies:"Allergien",mobility:"Mobilität",housekeepingPref:"Housekeeping",roomStay:"Zimmer und Aufenthalt",locationMissing:"Standort nicht erfasst",openRoom:"Zimmerobjekt öffnen",noRoom:"Kein Zimmer verknüpft.",arrivalEstimate:"Voraussichtliche Ankunft",departureEstimate:"Voraussichtliche Abreise",finance:"Zahlungen und Rechnungen",noFinance:"Keine sichtbaren Finanzbewegungen.",housekeeping:"Housekeeping",noHousekeeping:"Kein Housekeeping verknüpft.",inspection:"Inspektion",pending:"ausstehend",maintenance:"Instandhaltung",noMaintenance:"Keine Instandhaltung verknüpft.",blocked:"Blockiert",blocksRoom:"blockiert Zimmer",noTarget:"kein Zieldatum",requests:"Anfragen",noRequests:"Keine Anfragen verknüpft.",request:"Anfrage",noDescription:"Keine Beschreibung",due:"fällig",documents:"Dokumente",noDocuments:"Keine Dokumente verknüpft.",document:"Dokument",special:"Besondere Reservierungswünsche",activity:"Reservierungsaktivität",noActivity:"Für diese Reservierung sind noch keine operativen Ereignisse erfasst.",viewAll:"Alle anzeigen",noDate:"Kein Datum",balance:"Restbetrag",noSignal:"kein Signal"},
} as const

function statusVariant(value:string|null):"default"|"secondary"|"destructive"|"outline"{const status=value?.toLowerCase()||"";if(["critical","blocked","overdue","failed","unpaid"].includes(status))return"destructive";if(["completed","resolved","paid","ready","checked_in","checked-out","checked_out"].includes(status))return"secondary";return"outline"}

export function BookingReservationObjectView({data}:{data:BookingReservationObjectData}){
 const{language}=useLanguage();const lang=(language in COPY?language:"en") as keyof typeof COPY;const c=COPY[lang];const locale=lang==="es"?"es-CL":lang==="de"?"de-DE":"en-US";const nf=new Intl.NumberFormat(locale);const df=new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeZone:"America/Santiago"});const dtf=new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone:"America/Santiago"});const money=(v:number|string|null)=>{const n=Number(v??0);return Number.isFinite(n)?new Intl.NumberFormat(locale,{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(n):"—"};const date=(v:string|null)=>v?df.format(new Date(v.includes("T")?v:`${v}T12:00:00-04:00`)):c.noDate;const dateTime=(v:string|null)=>v?dtf.format(new Date(v)):c.noDate;const{reservation,room,guest,payments,invoices,housekeeping,maintenance,requests,exceptions,documents,events,queryError,paidAmount}=data
 return <AppLayout><div className="space-y-6 p-4 md:p-6"><div className="flex flex-col gap-4 border-b pb-5 md:flex-row md:items-end md:justify-between"><div><Link href="/bookings" className="mb-3 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4"/>{c.calendar}</Link><div className="flex flex-wrap items-center gap-3"><div className="flex h-11 w-11 items-center justify-center border border-primary/25 bg-primary/10 text-primary"><CalendarIcon/></div><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-primary">{c.object}</p><h1 className="text-2xl font-semibold">{reservation.guest_name||guest?.name||c.guestMissing}</h1></div><Badge variant={statusVariant(reservation.arrival_status||reservation.status)}>{reservation.arrival_status||reservation.status||c.noState}</Badge></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-sm text-muted-foreground"><span>{date(reservation.check_in)} → {date(reservation.check_out)}</span><span>{reservation.num_guests==null?"—":nf.format(reservation.num_guests)} {c.guests}</span>{reservation.source&&<span>{c.source} {reservation.source}</span>}</div></div>{room&&<Link href={`/bookings/rooms/${room.id}`} className="inline-flex h-9 items-center gap-2 rounded-md border px-3 text-sm font-medium hover:bg-muted"><BedDouble className="h-4 w-4"/>{c.room} {room.room_number}</Link>}</div>
 {queryError&&<div className="rounded-md border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-amber-700 dark:text-amber-300">{c.partial}</div>}
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StateCard label={c.stay} value={reservation.status} empty={c.noSignal}/><StateCard label={c.arrival} value={reservation.arrival_status} empty={c.noSignal}/><StateCard label={c.payment} value={reservation.payment_status} empty={c.noSignal}/><div className="rounded-lg border p-4"><p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">{c.total}</p><p className="mt-2 text-lg font-semibold">{money(reservation.total_amount)}</p><p className="mt-1 text-xs text-muted-foreground">{c.paid}: {money(paidAmount)}</p></div></section>
 {exceptions.length>0&&<Card className="border-amber-500/30 bg-amber-500/5"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><AlertTriangle className="h-4 w-4"/>{c.attention}</CardTitle></CardHeader><CardContent className="space-y-2">{exceptions.map(item=><div key={`${item.domain}-${item.source_id}`} className="rounded-md border border-amber-500/20 bg-background/40 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{item.title}</p><Badge variant="destructive">{item.exception_state}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{item.domain}{item.detail?` · ${item.detail}`:""}</p>{(item.blocks_check_in||item.blocks_check_out)&&<p className="mt-2 text-xs font-medium text-amber-700 dark:text-amber-300">{item.blocks_check_in?c.blocksIn:""}{item.blocks_check_in&&item.blocks_check_out?" · ":""}{item.blocks_check_out?c.blocksOut:""}</p>}</div>)}</CardContent></Card>}
 <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UserRound className="h-4 w-4"/>{c.guest}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div><p className="font-medium">{guest?.name||reservation.guest_name||c.unknown}{guest?.vip_status?" · VIP":""}</p><p className="text-muted-foreground">{guest?.email||reservation.guest_email||c.noEmail} · {guest?.phone||reservation.guest_phone||c.noPhone}</p></div>{guest?.preferred_language&&<p><span className="text-muted-foreground">{c.language}:</span> {guest.preferred_language}</p>}{guest?.preferred_contact_channel&&<p><span className="text-muted-foreground">{c.contact}:</span> {guest.preferred_contact_channel}</p>}{guest?.allergies&&<p><span className="text-muted-foreground">{c.allergies}:</span> {guest.allergies}</p>}{guest?.mobility_requirements&&<p><span className="text-muted-foreground">{c.mobility}:</span> {guest.mobility_requirements}</p>}{guest?.housekeeping_preferences&&<p><span className="text-muted-foreground">{c.housekeepingPref}:</span> {guest.housekeeping_preferences}</p>}</CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><BedDouble className="h-4 w-4"/>{c.roomStay}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{room?<><div className="flex items-center justify-between gap-3"><div><p className="font-medium">{c.room} {room.room_number}</p><p className="text-muted-foreground">{room.location||c.locationMissing}</p></div><Badge variant={statusVariant(room.operational_status||room.status)}>{room.operational_status||room.status||c.noState}</Badge></div><Link href={`/bookings/rooms/${room.id}`} className="text-sm font-medium text-primary hover:underline">{c.openRoom}</Link></>:<p className="text-muted-foreground">{c.noRoom}</p>}{reservation.estimated_arrival_time&&<p><span className="text-muted-foreground">{c.arrivalEstimate}:</span> {reservation.estimated_arrival_time}</p>}{reservation.estimated_departure_time&&<p><span className="text-muted-foreground">{c.departureEstimate}:</span> {reservation.estimated_departure_time}</p>}{(reservation.early_check_in_requested||reservation.late_check_out_requested)&&<div className="flex flex-wrap gap-2">{reservation.early_check_in_requested&&<Badge variant="outline">Early check-in</Badge>}{reservation.late_check_out_requested&&<Badge variant="outline">Late check-out</Badge>}</div>}</CardContent></Card>
 <ObjectList title={c.finance} icon={<Banknote className="h-4 w-4"/>} empty={c.noFinance} href="/bookings/charges" viewAll={c.viewAll}>{[...payments.map(item=>({id:`payment-${item.id}`,title:`${money(item.amount)} · ${item.payment_method||c.payment}`,detail:dateTime(item.paid_at||item.created_at),status:item.payment_status})),...invoices.map(item=>({id:`invoice-${item.id}`,title:item.invoice_number?`Invoice ${item.invoice_number}`:"Invoice",detail:`${money(item.total_amount)}${item.balance_due!=null?` · ${c.balance} ${money(item.balance_due)}`:""}`,status:item.payment_status||item.status}))].map(item=><CompactRow key={item.id} title={item.title} detail={item.detail} status={item.status} empty={c.noState}/>)}</ObjectList>
 <ObjectList title={c.housekeeping} icon={<ClipboardCheck className="h-4 w-4"/>} empty={c.noHousekeeping} href="/bookings/housekeeping" viewAll={c.viewAll}>{housekeeping.map(item=><CompactRow key={item.id} title={item.task_type||c.housekeeping} detail={`${item.service_date?date(item.service_date):c.noDate}${item.requires_inspection?` · ${c.inspection} ${item.inspection_status||c.pending}`:""}`} status={item.priority||item.status} empty={c.noState}/>)}</ObjectList>
 <ObjectList title={c.maintenance} icon={<Wrench className="h-4 w-4"/>} empty={c.noMaintenance} href="/maintenance" viewAll={c.viewAll}>{maintenance.map(item=><CompactRow key={item.id} title={item.title||c.maintenance} detail={`${item.bloqueado?`${c.blocked} · `:""}${item.blocks_room?`${c.blocksRoom} · `:""}${item.fecha_objetivo?date(item.fecha_objetivo):c.noTarget}`} status={item.prioridad||item.status} empty={c.noState}/>)}</ObjectList>
 <ObjectList title={c.requests} icon={<MessageSquareText className="h-4 w-4"/>} empty={c.noRequests} href="/bookings/requests" viewAll={c.viewAll}>{requests.map(item=><CompactRow key={item.id} title={item.request_type||item.category||c.request} detail={`${item.description||c.noDescription}${item.due_at?` · ${c.due} ${dateTime(item.due_at)}`:""}`} status={item.priority||item.status} empty={c.noState}/>)}</ObjectList>
 <ObjectList title={c.documents} icon={<FileText className="h-4 w-4"/>} empty={c.noDocuments} href="/bookings/documents" viewAll={c.viewAll}>{documents.map(item=><CompactRow key={item.id} title={item.title||item.document_number||item.document_type||c.document} detail={`${item.document_type||c.document}${item.issued_at?` · ${dateTime(item.issued_at)}`:""}`} status={item.status} empty={c.noState}/>)}</ObjectList></div>
 {reservation.special_requests&&<Card><CardHeader><CardTitle className="text-base">{c.special}</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">{reservation.special_requests}</p></CardContent></Card>}
 <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><History className="h-4 w-4"/>{c.activity}</CardTitle></CardHeader><CardContent>{events.length===0?<p className="text-sm text-muted-foreground">{c.noActivity}</p>:<div className="space-y-3">{events.map(item=><div key={item.id} className="border-l-2 border-border pl-4"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{item.title}</p>{item.category&&<Badge variant="outline">{item.category}</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{dateTime(item.occurred_at)}{item.previous_state||item.new_state?` · ${item.previous_state||"—"} → ${item.new_state||"—"}`:""}</p>{item.description&&<p className="mt-1 text-sm text-muted-foreground">{item.description}</p>}</div>)}</div>}</CardContent></Card></div></AppLayout>
}
function CalendarIcon(){return <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2"><path d="M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2Z"/></svg>}
function StateCard({label,value,empty}:{label:string;value:string|null|undefined;empty:string}){return <div className="rounded-lg border p-4"><p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">{label}</p><div className="mt-2"><Badge variant={statusVariant(value||null)}>{value||empty}</Badge></div></div>}
function ObjectList({title,icon,empty,href,children,viewAll}:{title:string;icon:React.ReactNode;empty:string;href:string;children:React.ReactNode;viewAll:string}){const hasChildren=Array.isArray(children)?children.length>0:Boolean(children);return <Card><CardHeader className="pb-3"><div className="flex items-center justify-between gap-3"><CardTitle className="flex items-center gap-2 text-base">{icon}{title}</CardTitle><Link href={href} className="text-xs font-medium text-primary hover:underline">{viewAll}</Link></div></CardHeader><CardContent>{hasChildren?<div className="space-y-2">{children}</div>:<p className="text-sm text-muted-foreground">{empty}</p>}</CardContent></Card>}
function CompactRow({title,detail,status,empty}:{title:string;detail:string;status:string|null;empty:string}){return <div className="flex items-start justify-between gap-3 rounded-md border p-3"><div className="min-w-0"><p className="font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><Badge variant={statusVariant(status)}>{status||empty}</Badge></div>}
