"use client"

import { AlertTriangle, Mail, Phone, UserCheck, Users } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { AddEmployeeDialog } from "@/components/add-employee-dialog"
import { EmployeeCard } from "@/components/employee-card"
import { useLanguage } from "@/lib/hooks/use-language"
import type { Employee } from "@/lib/types"

const COPY = {
  en: { title: "People and operations", description: "Internal Fundo Corcovado team directory with registered roles, operational availability and contact data.", loadError: "The directory could not be loaded.", review: "Data requiring administrative review", missingRoleOne: "person has no recorded role.", missingRoleMany: "people have no recorded role.", duplicateOne: "duplicate name must be validated before records are consolidated.", duplicateMany: "duplicate names must be validated before records are consolidated.", registered: "People registered", active: "Active", inactive: "Inactive", noEmail: "Active without email", noPhone: "Active without phone", directory: "Operational directory", directoryDetail: "Statuses indicate whether a person is currently active in the system; they do not represent daily attendance or contractual status.", empty: "No people registered.", emptyHint: "Use Add person to start the operational directory." },
  es: { title: "Personas y operaciones", description: "Directorio interno del equipo de Fundo Corcovado, con funciones, disponibilidad operativa y datos de contacto registrados.", loadError: "No fue posible cargar el directorio.", review: "Datos que requieren revisión administrativa", missingRoleOne: "persona sin función registrada.", missingRoleMany: "personas sin función registrada.", duplicateOne: "nombre duplicado que debe validarse antes de consolidar registros.", duplicateMany: "nombres duplicados que deben validarse antes de consolidar registros.", registered: "Personas registradas", active: "Activas", inactive: "Inactivas", noEmail: "Activas sin correo", noPhone: "Activas sin teléfono", directory: "Directorio operativo", directoryDetail: "Los estados indican si una persona está actualmente activa en el sistema; no representan asistencia diaria ni relación contractual.", empty: "No hay personas registradas.", emptyHint: "Utiliza Agregar persona para iniciar el directorio operativo." },
  de: { title: "Personen und Betrieb", description: "Internes Teamverzeichnis von Fundo Corcovado mit erfassten Rollen, operativer Verfügbarkeit und Kontaktdaten.", loadError: "Das Verzeichnis konnte nicht geladen werden.", review: "Daten mit administrativem Prüfbedarf", missingRoleOne: "Person hat keine erfasste Rolle.", missingRoleMany: "Personen haben keine erfasste Rolle.", duplicateOne: "doppelter Name muss vor der Zusammenführung geprüft werden.", duplicateMany: "doppelte Namen müssen vor der Zusammenführung geprüft werden.", registered: "Erfasste Personen", active: "Aktiv", inactive: "Inaktiv", noEmail: "Aktive ohne E-Mail", noPhone: "Aktive ohne Telefon", directory: "Operatives Verzeichnis", directoryDetail: "Status zeigen, ob eine Person derzeit im System aktiv ist; sie stellen weder tägliche Anwesenheit noch Vertragsstatus dar.", empty: "Keine Personen erfasst.", emptyHint: "Verwende Person hinzufügen, um das operative Verzeichnis zu beginnen." },
} as const

export function EmployeesDirectoryView({ employees, loadFailed }: { employees: Employee[]; loadFailed: boolean }) {
  const { language } = useLanguage(); const lang = (language in COPY ? language : "en") as keyof typeof COPY; const copy = COPY[lang]; const locale = lang === "es" ? "es-CL" : lang === "de" ? "de-DE" : "en-US"; const number = new Intl.NumberFormat(locale)
  const active = employees.filter((employee) => employee.is_active).length; const inactive = employees.length - active; const missingRole = employees.filter((employee) => !employee.role?.trim()).length; const missingEmail = employees.filter((employee) => employee.is_active && !employee.email?.trim()).length; const missingPhone = employees.filter((employee) => employee.is_active && !employee.phone?.trim()).length
  const normalizedNames = employees.map((employee) => employee.name.trim().toLocaleLowerCase(locale)); const duplicateNames = new Set(normalizedNames.filter((name, index) => normalizedNames.indexOf(name) !== index)).size
  return <AppLayout><PageHeader title={copy.title} description={copy.description} actions={<AddEmployeeDialog />} /><div className="space-y-6 p-4 sm:p-8">
    {loadFailed && <Card className="border-destructive/60"><CardContent className="p-5"><p className="font-medium text-destructive">{copy.loadError}</p></CardContent></Card>}
    {(missingRole > 0 || duplicateNames > 0) && !loadFailed && <Card className="border-amber-300"><CardContent className="flex gap-3 p-5"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" /><div><p className="font-medium">{copy.review}</p><p className="mt-1 text-sm text-muted-foreground">{missingRole > 0 ? `${number.format(missingRole)} ${missingRole === 1 ? copy.missingRoleOne : copy.missingRoleMany} ` : ""}{duplicateNames > 0 ? `${number.format(duplicateNames)} ${duplicateNames === 1 ? copy.duplicateOne : copy.duplicateMany}` : ""}</p></div></CardContent></Card>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Users} title={copy.registered} value={employees.length} locale={locale} /><Metric icon={UserCheck} title={copy.active} value={active} locale={locale} /><Metric icon={Users} title={copy.inactive} value={inactive} locale={locale} /><Metric icon={Mail} title={copy.noEmail} value={missingEmail} warning={missingEmail > 0} locale={locale} /><Metric icon={Phone} title={copy.noPhone} value={missingPhone} warning={missingPhone > 0} locale={locale} /></div>
    <Card><CardHeader><CardTitle className="text-base">{copy.directory}</CardTitle><p className="text-sm text-muted-foreground">{copy.directoryDetail}</p></CardHeader><CardContent>{employees.length > 0 ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{employees.map((employee) => <EmployeeCard key={employee.id} employee={employee} />)}</div> : <div className="py-12 text-center"><p className="font-medium">{copy.empty}</p><p className="mt-1 text-sm text-muted-foreground">{copy.emptyHint}</p></div>}</CardContent></Card>
  </div></AppLayout>
}
function Metric({ icon: Icon, title, value, warning=false, locale }: { icon:typeof Users; title:string; value:number; warning?:boolean; locale:string }) { return <Card className={warning ? "border-amber-300" : undefined}><CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">{title}</CardTitle><Icon className="h-4 w-4 text-muted-foreground" /></CardHeader><CardContent><div className="text-3xl font-semibold">{new Intl.NumberFormat(locale).format(value)}</div></CardContent></Card> }