'use client'

import Link from 'next/link'
import { ArrowLeft, BadgeEuro, Building2, FileText, History, ReceiptText } from 'lucide-react'
import { AppLayout } from '@/components/app-layout'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { useLanguage } from '@/lib/hooks/use-language'

type FinanceRow = {
  id:string; document_type:string|null; external_source:string|null; external_id:string|null; supplier_name:string|null; supplier_rut:string|null; document_number:string|null; document_date:string|null; due_date:string|null; description:string|null; net_amount:number|string|null; tax_amount:number|string|null; total_amount:number|string|null; currency:string|null; classification_status:string|null; approval_status:string|null; valuation_status:string|null; amount_eur:number|string|null; fx_rate_to_eur:number|string|null; fx_date:string|null; confidence:number|string|null; confidence_label:string|null; classification_reason:string|null; historical_count:number|null; historical_dominance:number|string|null; historical_median:number|string|null; accepted_min:number|string|null; accepted_max:number|string|null; amount_in_range:boolean|null; decision_notes:string|null; division_name:string|null; division_key:string|null; category_name:string|null; category_key:string|null; category_role:string|null; cost_center_name:string|null; cost_center_code:string|null; operational_label:string|null
}
const COPY={
 en:{back:'Back to financial approval',object:'Object · Financial approval',queue:'Open approval queue',supplier:'Supplier',document:'Document',date:'Document date',due:'Due date',status:'Approval status',classification:'Classification',valuation:'Valuation',budget:'Canonical Budget mapping',division:'Division',category:'Category',costCenter:'Cost center',operational:'Operational detail',amounts:'Amounts',net:'Net',tax:'Tax',total:'Total',eur:'EUR value',evidence:'Historical evidence',confidence:'Confidence',history:'Historical observations',median:'Historical median',range:'Accepted range',inRange:'Amount in range',reason:'Classification reason',notes:'Decision notes',notRecorded:'Not recorded',yes:'Yes',no:'No',context:'This is the canonical document evidence used by the approval queue. Approve/reject actions remain in the existing controlled queue.'},
 es:{back:'Volver a aprobación financiera',object:'Objeto · Aprobación financiera',queue:'Abrir cola de aprobación',supplier:'Proveedor',document:'Documento',date:'Fecha documento',due:'Vencimiento',status:'Estado de aprobación',classification:'Clasificación',valuation:'Valorización',budget:'Mapeo al Budget canónico',division:'División',category:'Categoría',costCenter:'Centro de costo',operational:'Detalle operativo',amounts:'Montos',net:'Neto',tax:'Impuesto',total:'Total',eur:'Valor EUR',evidence:'Evidencia histórica',confidence:'Confianza',history:'Observaciones históricas',median:'Mediana histórica',range:'Rango aceptado',inRange:'Monto dentro de rango',reason:'Razón de clasificación',notes:'Notas de decisión',notRecorded:'No registrado',yes:'Sí',no:'No',context:'Esta es la evidencia documental canónica usada por la cola de aprobación. Las acciones de aprobar/rechazar permanecen en la cola controlada existente.'},
 de:{back:'Zurück zur finanziellen Freigabe',object:'Objekt · Finanzielle Freigabe',queue:'Freigabewarteschlange öffnen',supplier:'Lieferant',document:'Dokument',date:'Dokumentdatum',due:'Fälligkeitsdatum',status:'Freigabestatus',classification:'Klassifizierung',valuation:'Bewertung',budget:'Kanonische Budget-Zuordnung',division:'Bereich',category:'Kategorie',costCenter:'Kostenstelle',operational:'Operatives Detail',amounts:'Beträge',net:'Netto',tax:'Steuer',total:'Gesamt',eur:'EUR-Wert',evidence:'Historische Evidenz',confidence:'Konfidenz',history:'Historische Beobachtungen',median:'Historischer Median',range:'Akzeptierter Bereich',inRange:'Betrag im Bereich',reason:'Klassifizierungsgrund',notes:'Entscheidungsnotizen',notRecorded:'Nicht erfasst',yes:'Ja',no:'Nein',context:'Dies ist die kanonische Dokumentevidenz der Freigabewarteschlange. Freigabe- und Ablehnungsaktionen bleiben in der bestehenden kontrollierten Warteschlange.'},
} as const
const LOCALES={en:'en-US',es:'es-CL',de:'de-DE'} as const

export function FinanceApprovalObjectView({row}:{row:FinanceRow}){
 const {language}=useLanguage(); const copy=COPY[language]; const locale=LOCALES[language]
 const date=new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:'America/Santiago'}); const fd=(value:string|null)=>value?date.format(new Date(`${value}T12:00:00-04:00`)):copy.notRecorded
 const money=(value:number|string|null,currency=row.currency||'CLP')=>{const amount=Number(value??0);if(!Number.isFinite(amount))return copy.notRecorded;try{return new Intl.NumberFormat(locale,{style:'currency',currency,maximumFractionDigits:currency==='CLP'?0:2}).format(amount)}catch{return `${amount.toLocaleString(locale)} ${currency}`}}
 const confidence=Number(row.confidence); const confidenceLabel=Number.isFinite(confidence)?new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:0}).format(confidence):row.confidence_label||copy.notRecorded
 return <AppLayout><div className="space-y-6 p-4 md:p-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/budgets/approvals" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4"/>{copy.back}</Link><Badge variant="outline">{copy.object}</Badge></div>
  <Card><CardHeader><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><CardTitle className="text-2xl">{row.operational_label||row.supplier_name||row.document_number||copy.document}</CardTitle><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{row.description||copy.context}</p></div><div className="flex flex-wrap gap-2"><Badge>{row.approval_status||copy.notRecorded}</Badge><Badge variant="secondary">{row.classification_status||copy.notRecorded}</Badge></div></div></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label={copy.supplier} value={row.supplier_name||copy.notRecorded}/><Info label={copy.document} value={[row.document_type,row.document_number].filter(Boolean).join(' · ')||copy.notRecorded}/><Info label={copy.date} value={fd(row.document_date)}/><Info label={copy.due} value={fd(row.due_date)}/></div></CardContent></Card>
  <div className="grid gap-4 lg:grid-cols-3">
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Building2 className="h-4 w-4"/>{copy.budget}</CardTitle></CardHeader><CardContent className="space-y-3"><Info label={copy.division} value={row.division_name||row.division_key||copy.notRecorded}/><Info label={copy.category} value={row.category_name||row.category_key||copy.notRecorded}/><Info label={copy.costCenter} value={[row.cost_center_code,row.cost_center_name].filter(Boolean).join(' · ')||copy.notRecorded}/><Info label={copy.operational} value={row.operational_label||copy.notRecorded}/></CardContent></Card>
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><BadgeEuro className="h-4 w-4"/>{copy.amounts}</CardTitle></CardHeader><CardContent className="space-y-3"><Info label={copy.net} value={money(row.net_amount)}/><Info label={copy.tax} value={money(row.tax_amount)}/><Info label={copy.total} value={money(row.total_amount)}/><Info label={copy.eur} value={row.amount_eur==null?copy.notRecorded:money(row.amount_eur,'EUR')}/></CardContent></Card>
   <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><History className="h-4 w-4"/>{copy.evidence}</CardTitle></CardHeader><CardContent className="space-y-3"><Info label={copy.confidence} value={confidenceLabel}/><Info label={copy.history} value={row.historical_count==null?copy.notRecorded:new Intl.NumberFormat(locale).format(row.historical_count)}/><Info label={copy.median} value={row.historical_median==null?copy.notRecorded:money(row.historical_median)}/><Info label={copy.range} value={row.accepted_min==null&&row.accepted_max==null?copy.notRecorded:`${money(row.accepted_min)} → ${money(row.accepted_max)}`}/><Info label={copy.inRange} value={row.amount_in_range==null?copy.notRecorded:row.amount_in_range?copy.yes:copy.no}/></CardContent></Card>
  </div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FileText className="h-4 w-4"/>{copy.classification}</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Info label={copy.reason} value={row.classification_reason||copy.notRecorded}/><Info label={copy.notes} value={row.decision_notes||copy.notRecorded}/><Info label={copy.status} value={row.approval_status||copy.notRecorded}/><Info label={copy.valuation} value={row.valuation_status||copy.notRecorded}/></CardContent></Card>
  <div className="flex justify-end"><Button asChild><Link href="/budgets/approvals"><ReceiptText className="mr-2 h-4 w-4"/>{copy.queue}</Link></Button></div>
 </div></AppLayout>
}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 break-words font-medium">{value}</p></div>}
