"use client"

import Link from "next/link"
import { AlertCircle, CheckCircle2, Clock3, Plus, Wrench } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { EditIssueDialog } from "@/components/edit-issue-dialog"
import { DeleteIssueButton } from "@/components/delete-issue-button"
import { IssueLabelSelector } from "@/components/issue-labels-selector"
import { IssueTaskLinkDialog } from "@/components/issue-task-link-dialog"
import { useEffectiveAccess } from "@/lib/hooks/use-effective-access"
import { useLanguage } from "@/lib/hooks/use-language"

export type IssueRecord = { id: string; title: string | null; description: string | null; category: string | null; status: string | null; priority: string | null; severity: string | null; created_at: string | null; photo_url: string | null; related_item_type: string | null; assets: { name: string } | null; reporter: { name: string } | null; issue_label_assignments: Array<{ issue_labels: { id: string; name: string; color: string | null } | null }> | null; issue_task_assignments: Array<{ tasks: { id: string; title: string; status: string | null } | null }> | null }
const COPY = {
  en: { title: "Issues · Fundo Corcovado", description: "Register and track operational problems, service requests and derived work in Valdivia.", register: "Report issue", context: "Operational context", contextDetail: "Issues document problems detected by the team. When technical execution is required, link them to a task and manage the work from Maintenance.", loadError: "Issues could not be loaded.", retry: "Retry", open: "Open issues", inProgress: "In progress", resolved: "Resolved", unlinked: "Without linked task", maintenance: "Go to maintenance", empty: "No issues registered.", emptyHint: "Report the first issue to begin operational tracking.", untitled: "Untitled issue", noCategory: "Category not recorded", noDescription: "No description recorded.", reporter: "Reported by", unknownReporter: "Reporter not identified", item: "Asset or item", noItem: "Not associated", tasks: "Linked tasks", derived: "Derived work", noPhoto: "No photographic evidence.", evidenceAlt: "Evidence for", issue: "issue", dateMissing: "Date not recorded", low: "Low", medium: "Medium", high: "High", critical: "Critical", statusOpen: "Open", statusProgress: "In progress", statusResolved: "Resolved", statusClosed: "Closed" },
  es: { title: "Incidencias · Fundo Corcovado", description: "Registro y seguimiento de problemas operativos, solicitudes de servicio y trabajos derivados en Valdivia.", register: "Registrar incidencia", context: "Contexto operativo", contextDetail: "Las incidencias documentan problemas detectados por el equipo. Cuando requieren ejecución técnica, deben vincularse a una tarea y gestionarse desde Mantenimiento.", loadError: "No fue posible cargar las incidencias.", retry: "Reintentar", open: "Incidencias abiertas", inProgress: "En ejecución", resolved: "Resueltas", unlinked: "Sin tarea vinculada", maintenance: "Ir a mantenimiento", empty: "No hay incidencias registradas.", emptyHint: "Registra la primera incidencia para iniciar su seguimiento operativo.", untitled: "Incidencia sin título", noCategory: "Categoría no registrada", noDescription: "Sin descripción registrada.", reporter: "Reportada por", unknownReporter: "Responsable no identificado", item: "Activo o elemento", noItem: "No asociado", tasks: "Tareas vinculadas", derived: "Trabajos derivados", noPhoto: "Sin evidencia fotográfica.", evidenceAlt: "Evidencia de", issue: "incidencia", dateMissing: "Fecha no registrada", low: "Baja", medium: "Media", high: "Alta", critical: "Crítica", statusOpen: "Abierta", statusProgress: "En ejecución", statusResolved: "Resuelta", statusClosed: "Cerrada" },
  de: { title: "Vorfälle · Fundo Corcovado", description: "Erfassung und Nachverfolgung operativer Probleme, Serviceanforderungen und abgeleiteter Arbeiten in Valdivia.", register: "Vorfall erfassen", context: "Operativer Kontext", contextDetail: "Vorfälle dokumentieren vom Team erkannte Probleme. Wenn technische Ausführung erforderlich ist, werden sie mit einer Aufgabe verknüpft und über Instandhaltung gesteuert.", loadError: "Vorfälle konnten nicht geladen werden.", retry: "Erneut versuchen", open: "Offene Vorfälle", inProgress: "In Bearbeitung", resolved: "Gelöst", unlinked: "Ohne verknüpfte Aufgabe", maintenance: "Zur Instandhaltung", empty: "Keine Vorfälle erfasst.", emptyHint: "Erfasse den ersten Vorfall, um die operative Nachverfolgung zu beginnen.", untitled: "Vorfall ohne Titel", noCategory: "Kategorie nicht erfasst", noDescription: "Keine Beschreibung erfasst.", reporter: "Gemeldet von", unknownReporter: "Meldende Person nicht identifiziert", item: "Anlage oder Element", noItem: "Nicht zugeordnet", tasks: "Verknüpfte Aufgaben", derived: "Abgeleitete Arbeiten", noPhoto: "Kein fotografischer Nachweis.", evidenceAlt: "Nachweis für", issue: "Vorfall", dateMissing: "Datum nicht erfasst", low: "Niedrig", medium: "Mittel", high: "Hoch", critical: "Kritisch", statusOpen: "Offen", statusProgress: "In Bearbeitung", statusResolved: "Gelöst", statusClosed: "Geschlossen" },
} as const
function normalizedStatus(value: string | null) { return value?.toLowerCase().replaceAll("_", "-") || "open" }
function isTerminalStatus(value: string | null) { return ["resolved", "closed", "cancelled", "canceled", "cancelada"].includes(normalizedStatus(value)) }
function statusVariant(status: string | null): "default" | "secondary" | "destructive" | "outline" { const value = normalizedStatus(status); if (value === "resolved" || value === "closed") return "secondary"; if (value === "in-progress") return "default"; return "outline" }
function priorityVariant(priority: string): "default" | "secondary" | "destructive" | "outline" { if (priority === "critical") return "destructive"; if (priority === "high") return "default"; if (priority === "low") return "secondary"; return "outline" }

export function IssuesView({ issues, loadFailed }: { issues: IssueRecord[]; loadFailed: boolean }) {
  const { language } = useLanguage(); const lang = (language in COPY ? language : "en") as keyof typeof COPY; const copy = COPY[lang]; const locale = lang === "es" ? "es-CL" : lang === "de" ? "de-DE" : "en-US"; const number = new Intl.NumberFormat(locale)
  const { access, loading: accessLoading, error: accessError, can } = useEffectiveAccess()
  const canMaintain = !accessLoading && !accessError && can("maintenance.operate")
  const canCreateTask = canMaintain && (access.is_admin || access.role === "approver")
  const openCount = issues.filter((issue) => normalizedStatus(issue.status) === "open").length
  const inProgressCount = issues.filter((issue) => normalizedStatus(issue.status) === "in-progress").length
  const resolvedCount = issues.filter((issue) => ["resolved", "closed"].includes(normalizedStatus(issue.status))).length
  const unlinkedCount = issues.filter((issue) => !isTerminalStatus(issue.status) && !(issue.issue_task_assignments ?? []).some((item) => item.tasks)).length
  const date = (value: string | null) => value ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: "America/Santiago" }).format(new Date(value)) : copy.dateMissing
  const statusLabel = (value: string) => ({ open: copy.statusOpen, "in-progress": copy.statusProgress, resolved: copy.statusResolved, closed: copy.statusClosed } as Record<string,string>)[value] ?? value
  const priorityLabel = (value: string) => ({ low: copy.low, medium: copy.medium, high: copy.high, critical: copy.critical } as Record<string,string>)[value] ?? value
  return <AppLayout><PageHeader title={copy.title} description={copy.description} actions={loadFailed ? undefined : <Button asChild><Link href="/issues/report"><Plus className="mr-2 h-4 w-4" />{copy.register}</Link></Button>} />
    <div className="space-y-6 p-4 md:p-6"><Card><CardHeader><CardTitle className="text-base">{copy.context}</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-muted-foreground">{copy.contextDetail}</CardContent></Card>
    {loadFailed && <div className="flex items-center justify-between gap-4 rounded-lg border border-destructive/40 bg-destructive/5 p-4 text-sm text-destructive"><span>{copy.loadError}</span><Button asChild variant="outline" size="sm"><Link href="/issues">{copy.retry}</Link></Button></div>}
    {!loadFailed && <>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title={copy.open} value={openCount} icon={AlertCircle} alert={openCount > 0} locale={locale} /><Metric title={copy.inProgress} value={inProgressCount} icon={Clock3} locale={locale} /><Metric title={copy.resolved} value={resolvedCount} icon={CheckCircle2} locale={locale} /><Metric title={copy.unlinked} value={unlinkedCount} icon={Wrench} alert={unlinkedCount > 0} locale={locale} /></div>
    <Button asChild variant="outline"><Link href="/maintenance"><Wrench className="mr-2 h-4 w-4" />{copy.maintenance}</Link></Button>
    {issues.length === 0 ? <Card><CardContent className="py-12 text-center"><AlertCircle className="mx-auto mb-3 h-6 w-6 text-muted-foreground" /><p className="font-medium">{copy.empty}</p><p className="mt-1 text-sm text-muted-foreground">{copy.emptyHint}</p><Button asChild className="mt-4"><Link href="/issues/report">{copy.register}</Link></Button></CardContent></Card> : <div className="space-y-4">{issues.map((issue) => { const status = normalizedStatus(issue.status); const priority = (issue.severity || issue.priority || "medium").toLowerCase(); const labels = (issue.issue_label_assignments ?? []).flatMap((item) => item.issue_labels ? [item.issue_labels] : []); const linkedTasks = (issue.issue_task_assignments ?? []).flatMap((item) => item.tasks ? [item.tasks] : []); return <Card key={issue.id}><CardHeader className="pb-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><CardTitle className="text-lg">{issue.title || copy.untitled}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{issue.category || copy.noCategory} · {date(issue.created_at)}</p></div><div className="flex flex-wrap gap-2"><Badge variant={priorityVariant(priority)}>{priorityLabel(priority)}</Badge><Badge variant={statusVariant(issue.status)}>{statusLabel(status)}</Badge></div></div></CardHeader><CardContent className="space-y-4">{issue.description ? <p className="text-sm leading-6">{issue.description}</p> : <p className="text-sm text-muted-foreground">{copy.noDescription}</p>}
      <div className="grid gap-3 rounded-lg border bg-muted/20 p-4 text-sm sm:grid-cols-3"><Info label={copy.reporter} value={issue.reporter?.name || copy.unknownReporter} /><Info label={copy.item} value={issue.assets?.name || issue.related_item_type || copy.noItem} /><Info label={copy.tasks} value={number.format(linkedTasks.length)} /></div>
      {labels.length > 0 && <div className="flex flex-wrap gap-2">{labels.map((label) => <Badge key={label.id} variant="outline" style={label.color ? { borderColor: label.color } : undefined}>{label.name}</Badge>)}</div>}
      {linkedTasks.length > 0 && <div className="space-y-2 rounded-lg border p-3"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{copy.derived}</p><div className="flex flex-wrap gap-2">{linkedTasks.map((task) => <Badge key={task.id} variant="secondary">{task.title}{task.status ? ` · ${task.status}` : ""}</Badge>)}</div></div>}
      <div className="flex flex-col gap-3 border-t pt-4 sm:flex-row sm:items-center sm:justify-between">{issue.photo_url ? <img src={issue.photo_url} alt={`${copy.evidenceAlt} ${issue.title || copy.issue}`} className="h-16 w-16 rounded-md border object-cover" /> : <p className="text-xs text-muted-foreground">{copy.noPhoto}</p>}{canMaintain && <div className="flex flex-wrap items-center gap-2"><IssueLabelSelector issueId={issue.id} /><IssueTaskLinkDialog issueId={issue.id} canCreateTask={canCreateTask} /><EditIssueDialog issue={issue} />{access.is_admin && <DeleteIssueButton issueId={issue.id} />}</div>}</div>
    </CardContent></Card> })}</div>}
    </>}
  </div></AppLayout>
}
function Metric({ title, value, icon: Icon, alert=false, locale }: { title:string; value:number; icon:typeof AlertCircle; alert?:boolean; locale:string }) { return <Card className={alert ? "border-amber-300" : undefined}><CardContent className="flex items-start justify-between p-4"><div><p className="text-sm font-medium text-muted-foreground">{title}</p><p className="mt-1 text-3xl font-semibold tabular-nums">{new Intl.NumberFormat(locale).format(value)}</p></div><Icon className="h-5 w-5 text-muted-foreground" /></CardContent></Card> }
function Info({ label, value }: { label:string; value:string }) { return <div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div> }
