"use client"

import Link from "next/link"
import { ArrowLeft, CheckCircle2, ClipboardList, FileCheck2, PackageCheck, ReceiptText, ShoppingCart, Truck } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { useLanguage } from "@/lib/hooks/use-language"

export type ProcurementRequestObjectData = {
  request: { id: string; request_number: string | null; title: string; description: string | null; business_justification: string | null; category: string | null; quantity: number | string | null; unit: string | null; estimated_budget_clp: number | string | null; priority: string | null; status: string | null; required_date: string | null; delivery_location: string | null; location_id: string | null; selected_supplier_id: string | null; approved_for_quotation_at: string | null; final_approved_at: string | null; created_at: string }
  rounds: Array<{ id: string; round_number: number; status: string | null; response_deadline: string | null; minimum_quotes: number | null; sent_at: string | null; closed_at: string | null; created_at: string }>
  quotationRequests: Array<{ id: string; quotation_round_id: string; supplier_id: string; status: string | null; sent_at: string | null; opened_at: string | null; responded_at: string | null }>
  quotes: Array<{ id: string; quotation_request_id: string; supplier_id: string; currency: string | null; total: number | string | null; lead_time_days: number | null; valid_until: string | null; stock_status: string | null; requires_human_review: boolean | null; submitted_at: string | null }>
  comparisons: Array<{ id: string; quotation_round_id: string; recommended_supplier_id: string | null; approved_supplier_id: string | null; approved_at: string | null; recommendation_summary: string | null; risks: unknown }>
  orders: Array<{ id: string; order_number: string; request_id: string; supplier_id: string; status: string | null; currency: string | null; total: number | string | null; expected_delivery: string | null; payment_terms: string | null; issued_at: string | null }>
  receipts: Array<{ id: string; purchase_order_id: string; receipt_number: string; status: string | null; received_at: string | null; delivery_document: string | null; notes: string | null }>
  receiptItems: Array<{ id: string; receipt_id: string; request_id: string; ordered_quantity: number | string | null; received_quantity: number | string | null; rejected_quantity: number | string | null; condition: string | null; discrepancy_reason: string | null; inventory_intake_required: boolean | null }>
  intakes: Array<{ id: string; receipt_item_id: string; intake_type: string | null; status: string | null; linked_asset_id: string | null; linked_stock_item_id: string | null; processed_quantity: number | string | null; reconciliation_status: string | null; processed_at: string | null }>
  replenishment: Array<{ id: string; stock_item_id: string; status: string; trigger_quantity: number | string | null; suggested_quantity: number | string | null; requested_quantity: number | string | null; purchase_order_id: string | null; fulfilled_at: string | null; last_event_at: string | null }>
  approvals: Array<{ id: string; decision: string; request_amount_clp: number | string | null; approver_limit_clp: number | string | null; notes: string | null; created_at: string }>
  audit: Array<{ id: string; entity_type: string; action: string; actor_type: string; metadata: unknown; created_at: string }>
  suppliers: Record<string, string>
  location: { id: string; name: string } | null
  queryError: boolean
}

const LOCALES = { en: "en-US", es: "es-CL", de: "de-DE" } as const
const COPY = {
  en: { back: "Requests", object: "Object · Procurement", noStatus: "no status", pendingNumber: "Number pending", unit: "unit", noLocation: "Location not recorded", order: "Order", partialContext: "Part of the related context could not be loaded. This procurement object is showing only information allowed by RLS.", buy: "Request", requestFallback: "Requirement", quote: "Quote", enabled: "enabled", pending: "pending", approve: "Approve", approved: "approved", inTransit: "In transit", noOrder: "no order", receive: "Receive", stockReady: "Stock ready", ready: "ready", budget: "Budget", supplier: "Supplier", selected: "Selected", noSupplier: "Not selected", received: "Received", requirement: "Requirement", justification: "Justification", category: "Category", priority: "Priority", requiredDate: "Required date", approvals: "Approvals", noApprovals: "No approval decisions are visible.", quotations: "Quotations", noQuotes: "No received quotations are visible.", humanReview: "requires review", purchaseOrders: "Purchase orders", noPurchaseOrders: "No purchase order exists yet.", receiving: "Receiving", noReceipts: "No receipts are registered.", inventoryIntake: "Inventory intake", noIntakes: "No associated Inventory intake yet.", intake: "Intake", processed: "processed", activity: "Procurement activity", noActivity: "No auditable activity is visible for this procurement object.", days: "days", noDate: "No date" },
  es: { back: "Solicitudes", object: "Objeto · Compra", noStatus: "sin estado", pendingNumber: "Número pendiente", unit: "unidad", noLocation: "Ubicación sin registrar", order: "Orden", partialContext: "Parte del contexto relacionado no pudo cargarse. La compra sigue mostrando únicamente la información permitida por RLS.", buy: "Comprar", requestFallback: "Requerimiento", quote: "Cotizar", enabled: "habilitado", pending: "pendiente", approve: "Aprobar", approved: "aprobado", inTransit: "En camino", noOrder: "sin orden", receive: "Recibir", stockReady: "Stock listo", ready: "listo", budget: "Presupuesto", supplier: "Proveedor", selected: "Seleccionado", noSupplier: "Sin seleccionar", received: "Recibido", requirement: "Requerimiento", justification: "Justificación", category: "Categoría", priority: "Prioridad", requiredDate: "Fecha requerida", approvals: "Aprobaciones", noApprovals: "No hay decisiones de aprobación visibles.", quotations: "Cotizaciones", noQuotes: "No hay cotizaciones recibidas visibles.", humanReview: "requiere revisión", purchaseOrders: "Órdenes de compra", noPurchaseOrders: "Todavía no existe una orden de compra.", receiving: "Recepción", noReceipts: "No hay recepciones registradas.", inventoryIntake: "Ingreso a inventario", noIntakes: "Aún no hay ingreso de inventario asociado.", intake: "Ingreso", processed: "procesado", activity: "Actividad de la compra", noActivity: "No hay actividad auditable visible para esta compra.", days: "días", noDate: "Sin fecha" },
  de: { back: "Anforderungen", object: "Objekt · Beschaffung", noStatus: "kein Status", pendingNumber: "Nummer ausstehend", unit: "Einheit", noLocation: "Standort nicht erfasst", order: "Bestellung", partialContext: "Ein Teil des verknüpften Kontexts konnte nicht geladen werden. Das Beschaffungsobjekt zeigt nur die durch RLS erlaubten Informationen.", buy: "Anfordern", requestFallback: "Anforderung", quote: "Angebot", enabled: "freigegeben", pending: "ausstehend", approve: "Freigeben", approved: "freigegeben", inTransit: "Unterwegs", noOrder: "keine Bestellung", receive: "Annehmen", stockReady: "Bestand bereit", ready: "bereit", budget: "Budget", supplier: "Lieferant", selected: "Ausgewählt", noSupplier: "Nicht ausgewählt", received: "Angenommen", requirement: "Anforderung", justification: "Begründung", category: "Kategorie", priority: "Priorität", requiredDate: "Bedarfsdatum", approvals: "Freigaben", noApprovals: "Keine Freigabeentscheidungen sichtbar.", quotations: "Angebote", noQuotes: "Keine eingegangenen Angebote sichtbar.", humanReview: "Prüfung erforderlich", purchaseOrders: "Bestellungen", noPurchaseOrders: "Noch keine Bestellung vorhanden.", receiving: "Annahme", noReceipts: "Keine Annahmen erfasst.", inventoryIntake: "Inventarzugang", noIntakes: "Noch kein zugehöriger Inventarzugang.", intake: "Zugang", processed: "verarbeitet", activity: "Beschaffungsaktivität", noActivity: "Keine prüfbare Aktivität für dieses Beschaffungsobjekt sichtbar.", days: "Tage", noDate: "Kein Datum" },
} as const
const STATUS = {
  en: { draft: "Draft", submitted: "Submitted", under_review: "Under review", approved: "Approved", approved_for_quotation: "Approved for quotation", final_approved: "Final approved", rejected: "Rejected", converted: "Converted", ready_to_issue: "Ready to issue", issued: "Issued", acknowledged: "Acknowledged", confirmed: "Confirmed", partially_received: "Partially received", received: "Received", fulfilled: "Fulfilled", completed: "Completed", closed: "Closed", processed: "Processed", pending: "Pending" },
  es: { draft: "Borrador", submitted: "Enviada", under_review: "En revisión", approved: "Aprobada", approved_for_quotation: "Aprobada para cotizar", final_approved: "Aprobación final", rejected: "Rechazada", converted: "Convertida", ready_to_issue: "Lista para emitir", issued: "Emitida", acknowledged: "Acusada", confirmed: "Confirmada", partially_received: "Recepción parcial", received: "Recibida", fulfilled: "Cumplida", completed: "Completada", closed: "Cerrada", processed: "Procesado", pending: "Pendiente" },
  de: { draft: "Entwurf", submitted: "Eingereicht", under_review: "In Prüfung", approved: "Freigegeben", approved_for_quotation: "Für Angebot freigegeben", final_approved: "Endfreigabe", rejected: "Abgelehnt", converted: "Umgewandelt", ready_to_issue: "Ausgabebereit", issued: "Ausgestellt", acknowledged: "Bestätigt erhalten", confirmed: "Bestätigt", partially_received: "Teilweise angenommen", received: "Angenommen", fulfilled: "Erfüllt", completed: "Abgeschlossen", closed: "Geschlossen", processed: "Verarbeitet", pending: "Ausstehend" },
} as const

function statusVariant(value: string | null): "default" | "secondary" | "destructive" | "outline" {
  const status = value?.toLowerCase() || ""
  if (["rejected", "cancelled", "canceled", "failed", "exception", "blocked"].includes(status)) return "destructive"
  if (["approved", "ordered", "received", "fulfilled", "completed", "closed", "processed"].includes(status)) return "secondary"
  return "outline"
}

export function ProcurementRequestObjectView({ data }: { data: ProcurementRequestObjectData }) {
  const { language } = useLanguage()
  const lang = (language in COPY ? language : "en") as keyof typeof COPY
  const copy = COPY[lang]
  const locale = LOCALES[lang]
  const { request, rounds, quotes, orders, receipts, receiptItems, intakes, replenishment, approvals, audit, suppliers, location, queryError } = data
  const currentOrder = orders[0] ?? null
  const latestRound = rounds[0] ?? null
  const receivedQuantity = receiptItems.reduce((sum, item) => sum + Number(item.received_quantity ?? 0), 0)
  const stockReady = replenishment.some((item) => item.status === "fulfilled") || intakes.some((item) => ["processed", "completed"].includes(item.status?.toLowerCase() ?? ""))
  const money = (value: number | string | null, currency = "CLP") => { const amount = Number(value ?? 0); return Number.isFinite(amount) ? new Intl.NumberFormat(locale, { style: "currency", currency, maximumFractionDigits: currency === "CLP" ? 0 : 2 }).format(amount) : "—" }
  const number = new Intl.NumberFormat(locale, { maximumFractionDigits: 2 })
  const date = (value: string | null) => value ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeZone: "America/Santiago" }).format(new Date(value.includes("T") ? value : `${value}T12:00:00-04:00`)) : copy.noDate
  const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: "America/Santiago" }).format(new Date(value)) : copy.noDate
  const status = (value: string | null) => value ? (STATUS[lang][value as keyof (typeof STATUS)[typeof lang]] ?? value) : copy.noStatus
  const flow = [
    { label: copy.buy, detail: request.request_number ?? copy.requestFallback, complete: true },
    { label: copy.quote, detail: latestRound?.status ? status(latestRound.status) : request.approved_for_quotation_at ? copy.enabled : copy.pending, complete: Boolean(latestRound || request.approved_for_quotation_at) },
    { label: copy.approve, detail: request.final_approved_at ? copy.approved : status(approvals[0]?.decision ?? "pending"), complete: Boolean(request.final_approved_at || approvals.some((item) => item.decision === "approved")) },
    { label: copy.inTransit, detail: currentOrder?.order_number ?? copy.noOrder, complete: Boolean(currentOrder) },
    { label: copy.receive, detail: receipts[0]?.status ? status(receipts[0].status) : copy.pending, complete: receipts.length > 0 },
    { label: copy.stockReady, detail: stockReady ? copy.ready : copy.pending, complete: stockReady },
  ]

  return <AppLayout><div className="space-y-6 p-4 md:p-6">
    <div className="flex flex-col gap-4 border-b pb-5 md:flex-row md:items-end md:justify-between"><div>
      <Link href="/procurement/requests" className="mb-3 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />{copy.back}</Link>
      <div className="flex flex-wrap items-center gap-3"><div className="flex h-11 w-11 items-center justify-center border border-primary/25 bg-primary/10 text-primary"><ShoppingCart className="h-5 w-5" /></div><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-primary">{copy.object}</p><h1 className="text-2xl font-semibold">{request.title}</h1></div><Badge variant={statusVariant(request.status)}>{status(request.status)}</Badge></div>
      <div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-sm text-muted-foreground"><span>{request.request_number ?? copy.pendingNumber}</span><span>{request.quantity == null ? "—" : number.format(Number(request.quantity))} {request.unit ?? copy.unit}</span><span>{location?.name ?? request.delivery_location ?? copy.noLocation}</span></div>
    </div>{currentOrder && <Badge variant="outline" className="w-fit">{copy.order} {currentOrder.order_number}</Badge>}</div>
    {queryError && <div className="rounded-md border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-amber-700 dark:text-amber-300">{copy.partialContext}</div>}
    <section className="grid gap-2 sm:grid-cols-3 xl:grid-cols-6">{flow.map((step, index) => <div key={step.label} className={step.complete ? "rounded-lg border border-primary/30 bg-primary/5 p-3" : "rounded-lg border p-3"}><div className="flex items-center gap-2"><span className={step.complete ? "flex h-6 w-6 items-center justify-center rounded-full bg-primary text-primary-foreground" : "flex h-6 w-6 items-center justify-center rounded-full border text-xs text-muted-foreground"}>{step.complete ? <CheckCircle2 className="h-3.5 w-3.5" /> : index + 1}</span><p className="text-sm font-medium">{step.label}</p></div><p className="mt-2 truncate text-xs text-muted-foreground">{step.detail}</p></div>)}</section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StateCard label={copy.budget} value={money(request.estimated_budget_clp)} /><StateCard label={copy.supplier} value={request.selected_supplier_id ? suppliers[request.selected_supplier_id] ?? copy.selected : copy.noSupplier} /><StateCard label={copy.order} value={currentOrder ? money(currentOrder.total, currentOrder.currency ?? "CLP") : copy.noOrder} /><StateCard label={copy.received} value={`${number.format(receivedQuantity)} ${request.unit ?? copy.unit}`} /></section>
    <div className="grid gap-6 xl:grid-cols-2">
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ClipboardList className="h-4 w-4" />{copy.requirement}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="font-medium">{request.title}</p>{request.description && <p className="text-muted-foreground">{request.description}</p>}{request.business_justification && <p><span className="text-muted-foreground">{copy.justification}:</span> {request.business_justification}</p>}<p><span className="text-muted-foreground">{copy.category}:</span> {request.category ?? "—"}</p><p><span className="text-muted-foreground">{copy.priority}:</span> {request.priority ?? "—"}</p><p><span className="text-muted-foreground">{copy.requiredDate}:</span> {date(request.required_date)}</p></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FileCheck2 className="h-4 w-4" />{copy.approvals}</CardTitle></CardHeader><CardContent className="space-y-2">{approvals.length === 0 ? <Empty text={copy.noApprovals} /> : approvals.map((item) => <CompactRow key={item.id} title={status(item.decision)} detail={`${money(item.request_amount_clp)} · ${dateTime(item.created_at)}`} rawStatus={item.notes} statusLabel={item.notes} />)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ReceiptText className="h-4 w-4" />{copy.quotations}</CardTitle></CardHeader><CardContent className="space-y-2">{quotes.length === 0 ? <Empty text={copy.noQuotes} /> : quotes.map((quote) => <CompactRow key={quote.id} title={suppliers[quote.supplier_id] ?? copy.supplier} detail={`${money(quote.total, quote.currency ?? "CLP")}${quote.lead_time_days != null ? ` · ${number.format(quote.lead_time_days)} ${copy.days}` : ""}`} rawStatus={quote.requires_human_review ? "under_review" : quote.stock_status} statusLabel={quote.requires_human_review ? copy.humanReview : quote.stock_status} />)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShoppingCart className="h-4 w-4" />{copy.purchaseOrders}</CardTitle></CardHeader><CardContent className="space-y-2">{orders.length === 0 ? <Empty text={copy.noPurchaseOrders} /> : orders.map((order) => <CompactRow key={order.id} title={order.order_number} detail={`${suppliers[order.supplier_id] ?? copy.supplier} · ${money(order.total, order.currency ?? "CLP")}`} rawStatus={order.status} statusLabel={status(order.status)} />)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Truck className="h-4 w-4" />{copy.receiving}</CardTitle></CardHeader><CardContent className="space-y-2">{receipts.length === 0 ? <Empty text={copy.noReceipts} /> : receipts.map((receipt) => <CompactRow key={receipt.id} title={receipt.receipt_number} detail={dateTime(receipt.received_at)} rawStatus={receipt.status} statusLabel={status(receipt.status)} />)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><PackageCheck className="h-4 w-4" />{copy.inventoryIntake}</CardTitle></CardHeader><CardContent className="space-y-2">{intakes.length === 0 ? <Empty text={copy.noIntakes} /> : intakes.map((intake) => <CompactRow key={intake.id} title={intake.intake_type ?? copy.intake} detail={`${intake.processed_quantity == null ? "—" : number.format(Number(intake.processed_quantity))} ${copy.processed} · ${dateTime(intake.processed_at)}`} rawStatus={intake.reconciliation_status ?? intake.status} statusLabel={status(intake.reconciliation_status ?? intake.status)} />)}</CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle className="text-base">{copy.activity}</CardTitle></CardHeader><CardContent className="space-y-2">{audit.length === 0 ? <Empty text={copy.noActivity} /> : audit.map((event) => <div key={event.id} className="rounded-md border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{event.action}</p><time className="text-xs text-muted-foreground">{dateTime(event.created_at)}</time></div><p className="mt-1 text-xs text-muted-foreground">{event.entity_type} · {event.actor_type}</p></div>)}</CardContent></Card>
  </div></AppLayout>
}

function StateCard({ label, value }: { label: string; value: string }) { return <Card className="p-4"><p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p></Card> }
function Empty({ text }: { text: string }) { return <p className="rounded-md border border-dashed p-3 text-sm text-muted-foreground">{text}</p> }
function CompactRow({ title, detail, rawStatus, statusLabel }: { title: string; detail: string; rawStatus: string | null; statusLabel: string | null }) { return <div className="rounded-md border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{title}</p>{statusLabel && <Badge variant={statusVariant(rawStatus)}>{statusLabel}</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div> }
