"use client"

import Link from "next/link"
import { ArrowLeft, BookOpen, CheckSquare, Clock3, Plus, ShieldCheck } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { useLanguage } from "@/lib/hooks/use-language"

export type SopProcedureSummary = { id: string; code: string; title: string; domain: string; owner_role: string | null; status: string; risk_level: string; next_review_date: string | null; updated_at: string; sop_versions?: Array<{ id: string; version_number: number; status: string; estimated_minutes: number | null }> }
export type SopProcedureDetail = { id: string; code: string; title: string; domain: string; owner_role: string | null; description: string | null; status: string; risk_level: string; sop_versions: Array<{ id: string; version_number: number; status: string; objective: string | null; scope: string | null; acceptance_criteria: string | null; estimated_minutes: number | null; sop_steps: Array<{ id: string; step_number: number; title: string; instruction: string; is_required: boolean; requires_evidence: boolean; evidence_type: string | null; requires_approval: boolean; expected_minutes: number | null; safety_notes: string | null }> }> }

const COPY = {
  en: { libraryTitle: "Operational procedures", libraryDescription: "Compact library of master SOPs for current portal processes. Generic procedures remain drafts until operational review.", new: "New procedure", summaryAria: "Procedure summary", registered: "Registered procedures", active: "Active", drafts: "Drafts to validate", loadError: "Procedures could not be loaded", loadErrorDetail: "Check access to the SOP library and try again.", emptyTitle: "The SOP library is still empty", emptyDetail: "Create a master procedure or apply the base-library migration to load grouped generic drafts.", create: "Create procedure", libraryAria: "SOP library", code: "Code", procedure: "Procedure", area: "Area", state: "Status", duration: "Duration", owner: "Owner", ownerPending: "Owner pending", undefined: "Not defined", draft: "Draft", archived: "Obsolete", library: "SOP library", version: "Version", noVersion: "No version", responsible: "Owner", pending: "Pending", estimated: "Estimated time", minutes: "minutes", objective: "Objective", objectivePending: "Objective pending documentation.", scope: "Scope", scopePending: "Scope pending documentation.", acceptance: "Acceptance criteria", acceptancePending: "Acceptance criteria pending documentation.", steps: "Procedure steps", stepsDetail: "Executable sequence that will later be copied to each SOP task.", addStep: "Add step", addStepTitle: "Step editor is the next implementation block", noSteps: "No steps registered yet", noStepsDetail: "The procedure will remain a draft until its operational sequence is defined.", required: "Required", evidence: "Evidence", approval: "Approval", safety: "Safety" },
  es: { libraryTitle: "Procedimientos operacionales", libraryDescription: "Biblioteca compacta de SOP maestros para los procesos actuales del portal. Los procedimientos genéricos permanecen en borrador hasta su revisión operativa.", new: "Nuevo procedimiento", summaryAria: "Resumen de procedimientos", registered: "Procedimientos registrados", active: "Vigentes", drafts: "Borradores por validar", loadError: "No fue posible cargar los procedimientos", loadErrorDetail: "Revise el acceso a la biblioteca SOP y vuelva a intentar.", emptyTitle: "La biblioteca SOP todavía está vacía", emptyDetail: "Cree un procedimiento maestro o aplique la migración de biblioteca base para cargar los borradores genéricos agrupados.", create: "Crear procedimiento", libraryAria: "Biblioteca SOP", code: "Código", procedure: "Procedimiento", area: "Área", state: "Estado", duration: "Duración", owner: "Responsable", ownerPending: "Responsable pendiente", undefined: "Sin definir", draft: "Borrador", archived: "Obsoleto", library: "Biblioteca SOP", version: "Versión", noVersion: "Sin versión", responsible: "Responsable", pending: "Pendiente", estimated: "Tiempo estimado", minutes: "minutos", objective: "Objetivo", objectivePending: "Objetivo pendiente de documentar.", scope: "Alcance", scopePending: "Alcance pendiente de documentar.", acceptance: "Criterio de aceptación", acceptancePending: "Criterio pendiente de documentar.", steps: "Pasos del procedimiento", stepsDetail: "Secuencia ejecutable que luego se copiará a cada tarea SOP.", addStep: "Agregar paso", addStepTitle: "El editor de pasos será el siguiente bloque de implementación", noSteps: "Todavía no hay pasos registrados", noStepsDetail: "El procedimiento seguirá en borrador hasta definir su secuencia operacional.", required: "Obligatorio", evidence: "Evidencia", approval: "Aprobación", safety: "Seguridad" },
  de: { libraryTitle: "Betriebsverfahren", libraryDescription: "Kompakte Bibliothek von Master-SOPs für aktuelle Portalprozesse. Generische Verfahren bleiben bis zur operativen Prüfung Entwürfe.", new: "Neues Verfahren", summaryAria: "Verfahrensübersicht", registered: "Erfasste Verfahren", active: "Aktiv", drafts: "Zu prüfende Entwürfe", loadError: "Verfahren konnten nicht geladen werden", loadErrorDetail: "Prüfe den Zugriff auf die SOP-Bibliothek und versuche es erneut.", emptyTitle: "Die SOP-Bibliothek ist noch leer", emptyDetail: "Erstelle ein Masterverfahren oder wende die Basismigration an, um gruppierte generische Entwürfe zu laden.", create: "Verfahren erstellen", libraryAria: "SOP-Bibliothek", code: "Code", procedure: "Verfahren", area: "Bereich", state: "Status", duration: "Dauer", owner: "Verantwortung", ownerPending: "Verantwortung ausstehend", undefined: "Nicht definiert", draft: "Entwurf", archived: "Veraltet", library: "SOP-Bibliothek", version: "Version", noVersion: "Keine Version", responsible: "Verantwortung", pending: "Ausstehend", estimated: "Geschätzte Zeit", minutes: "Minuten", objective: "Ziel", objectivePending: "Ziel noch nicht dokumentiert.", scope: "Geltungsbereich", scopePending: "Geltungsbereich noch nicht dokumentiert.", acceptance: "Abnahmekriterium", acceptancePending: "Abnahmekriterium noch nicht dokumentiert.", steps: "Verfahrensschritte", stepsDetail: "Ausführbare Sequenz, die später in jede SOP-Aufgabe kopiert wird.", addStep: "Schritt hinzufügen", addStepTitle: "Der Schritteditor ist der nächste Implementierungsblock", noSteps: "Noch keine Schritte erfasst", noStepsDetail: "Das Verfahren bleibt Entwurf, bis die operative Sequenz definiert ist.", required: "Pflicht", evidence: "Nachweis", approval: "Freigabe", safety: "Sicherheit" },
} as const
const STATUS = { en: { draft: "Draft", active: "Active", archived: "Obsolete" }, es: { draft: "Borrador", active: "Vigente", archived: "Obsoleto" }, de: { draft: "Entwurf", active: "Aktiv", archived: "Veraltet" } } as const
const statusClass: Record<string, string> = { draft: "bg-[#fdd32c]/14 text-[#fdd32c]", active: "bg-[#8bcba8]/14 text-[#8bcba8]", archived: "bg-[#847c72]/16 text-[#b9b0a4]" }

export function SopLibraryView({ procedures, loadFailed }: { procedures: SopProcedureSummary[]; loadFailed: boolean }) {
  const { language } = useLanguage(); const lang = (language in COPY ? language : "en") as keyof typeof COPY; const copy = COPY[lang]; const number = new Intl.NumberFormat(lang === "es" ? "es-CL" : lang === "de" ? "de-DE" : "en-US")
  const activeCount = procedures.filter((p) => p.status === "active").length; const draftCount = procedures.filter((p) => p.status === "draft").length
  return <AppLayout><PageHeader title={copy.libraryTitle} description={copy.libraryDescription} actions={<Button asChild><Link href="/sop/new"><Plus className="h-4 w-4" />{copy.new}</Link></Button>} />
    <div className="mx-auto w-full max-w-[1440px] space-y-8 px-4 py-6 md:px-8 md:py-8">
      <section className="grid gap-3 sm:grid-cols-3" aria-label={copy.summaryAria}>{[[copy.registered, procedures.length], [copy.active, activeCount], [copy.drafts, draftCount]].map(([label,value]) => <div key={String(label)} className="bg-card p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="bs-heading mt-2 text-2xl text-foreground">{number.format(Number(value))}</p></div>)}</section>
      {loadFailed ? <section className="bg-card p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-destructive" /><div><h2 className="text-lg">{copy.loadError}</h2><p className="mt-2 text-sm text-muted-foreground">{copy.loadErrorDetail}</p></div></div></section> : procedures.length === 0 ? <section className="bg-card px-6 py-12 md:px-10"><div className="max-w-2xl"><BookOpen className="h-7 w-7 text-[#8bcba8]" /><h2 className="mt-5 text-2xl">{copy.emptyTitle}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy.emptyDetail}</p><Button asChild className="mt-6"><Link href="/sop/new"><Plus className="h-4 w-4" />{copy.create}</Link></Button></div></section> : <section className="bg-card" aria-label={copy.libraryAria}><div className="hidden grid-cols-[minmax(120px,0.7fr)_minmax(240px,2fr)_minmax(140px,1fr)_minmax(120px,0.8fr)_minmax(100px,0.7fr)] gap-4 bg-secondary px-5 py-3 text-xs font-medium text-muted-foreground md:grid"><span>{copy.code}</span><span>{copy.procedure}</span><span>{copy.area}</span><span>{copy.state}</span><span>{copy.duration}</span></div><div className="divide-y divide-[var(--bs-divider-subtle)]">{procedures.map((procedure) => { const latest = [...(procedure.sop_versions ?? [])].sort((a,b)=>b.version_number-a.version_number)[0]; const status = STATUS[lang][procedure.status as keyof (typeof STATUS)[typeof lang]] ?? procedure.status; return <Link key={procedure.id} href={`/sop/${procedure.id}`} className="grid gap-3 px-5 py-4 text-sm transition-colors hover:bg-[#5d554a] md:grid-cols-[minmax(120px,0.7fr)_minmax(240px,2fr)_minmax(140px,1fr)_minmax(120px,0.8fr)_minmax(100px,0.7fr)] md:gap-4"><span className="font-medium">{procedure.code}</span><span><span className="block">{procedure.title}</span><span className="mt-1 block text-xs text-muted-foreground">{procedure.owner_role ? `${copy.owner}: ${procedure.owner_role}` : copy.ownerPending}</span></span><span className="text-muted-foreground">{procedure.domain}</span><span><Badge className={statusClass[procedure.status] ?? statusClass.archived}>{status}</Badge></span><span className="flex items-center gap-2 text-muted-foreground"><Clock3 className="h-4 w-4" />{latest?.estimated_minutes ? `${number.format(latest.estimated_minutes)} min` : copy.undefined}</span></Link> })}</div></section>}
    </div></AppLayout>
}

export function SopDetailView({ procedure }: { procedure: SopProcedureDetail }) {
  const { language } = useLanguage(); const lang = (language in COPY ? language : "en") as keyof typeof COPY; const copy = COPY[lang]; const locale = lang === "es" ? "es-CL" : lang === "de" ? "de-DE" : "en-US"; const number = new Intl.NumberFormat(locale)
  const version = [...(procedure.sop_versions ?? [])].sort((a,b)=>b.version_number-a.version_number)[0]; const steps = [...(version?.sop_steps ?? [])].sort((a,b)=>a.step_number-b.step_number); const status = STATUS[lang][procedure.status as keyof (typeof STATUS)[typeof lang]] ?? procedure.status
  return <AppLayout><PageHeader title={procedure.title} description={`${procedure.code} · ${procedure.domain}`} actions={<Button asChild variant="secondary"><Link href="/sop"><ArrowLeft className="h-4 w-4" />{copy.library}</Link></Button>} />
    <div className="mx-auto w-full max-w-[1200px] space-y-8 px-4 py-6 md:px-8 md:py-8">
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label={copy.state} value={status} /><Info label={copy.version} value={version ? `v${number.format(version.version_number)}` : copy.noVersion} /><Info label={copy.responsible} value={procedure.owner_role || copy.pending} /><Info label={copy.estimated} value={version?.estimated_minutes ? `${number.format(version.estimated_minutes)} ${copy.minutes}` : copy.undefined} icon /></section>
      <section className="grid gap-6 bg-card p-5 md:grid-cols-2 md:p-6"><TextBlock title={copy.objective} value={version?.objective || copy.objectivePending} /><TextBlock title={copy.scope} value={version?.scope || copy.scopePending} /><div className="md:col-span-2"><TextBlock title={copy.acceptance} value={version?.acceptance_criteria || copy.acceptancePending} /></div></section>
      <section className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl">{copy.steps}</h2><p className="mt-2 text-sm text-muted-foreground">{copy.stepsDetail}</p></div><Button disabled title={copy.addStepTitle}><Plus className="h-4 w-4" />{copy.addStep}</Button></div>
      {steps.length === 0 ? <div className="bg-card p-6 md:p-8"><CheckSquare className="h-6 w-6 text-[#8bcba8]" /><h3 className="mt-4 text-xl">{copy.noSteps}</h3><p className="mt-2 text-sm text-muted-foreground">{copy.noStepsDetail}</p></div> : <div className="space-y-2">{steps.map((step) => <article key={step.id} className="grid gap-4 bg-card p-5 md:grid-cols-[48px_1fr_auto] md:items-start"><span className="bs-heading text-2xl text-[#8bcba8]">{String(step.step_number).padStart(2,"0")}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg">{step.title}</h3>{step.is_required && <Badge className="bg-[#fdd32c]/14 text-[#fdd32c]">{copy.required}</Badge>}{step.requires_evidence && <Badge className="bg-[#4679ae]/22 text-[#36b6f8]">{copy.evidence}</Badge>}{step.requires_approval && <Badge className="bg-[#8bcba8]/14 text-[#8bcba8]">{copy.approval}</Badge>}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{step.instruction}</p>{step.safety_notes && <p className="mt-3 text-xs text-[#ffa114]">{copy.safety}: {step.safety_notes}</p>}</div><span className="text-xs text-muted-foreground">{step.expected_minutes ? `${number.format(step.expected_minutes)} min` : "—"}</span></article>)}</div>}</section>
    </div></AppLayout>
}

function Info({ label, value, icon=false }: { label:string; value:string; icon?:boolean }) { return <div className="bg-card p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 flex items-center gap-2 text-sm text-foreground">{icon && <Clock3 className="h-4 w-4 text-[#8bcba8]" />}{value}</p></div> }
function TextBlock({ title, value }: { title:string; value:string }) { return <div><h2 className="text-xl">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{value}</p></div> }
