"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { AlertTriangle, ArrowRight, Map, Rows3 } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Plan={id:string;season:string|null;status:string}
type Plot={id:string;name:string;size_sqm:number|null;status:string|null}
type Bed={id:string;plot_id:string;name:string;area_sqm:number|null;status:string|null}
type Allocation={id:string;bed_id:string;crop_succession_id:string;allocated_area_sqm:number|null;planned_plants:number|null}

const copy={
 en:{eyebrow:"Dietrich · Beds & Capacity",title:"Physical capacity only where it is verified",description:"Dietrich's workbook includes Garden map and capacity sheets. Black Swan will not turn those drawings into precise bed assignments until the physical identity of each bed is canonical.",plots:"Physical plots",beds:"Canonical beds",allocations:"Plan allocations",area:"Recorded plot area",warning:"The current database does not yet contain enough verified bed geometry/identity to reproduce Dietrich's Garden map faithfully. Keep using the workbook map as reference until beds are reconciled in the field.",what:"What is safe today",safe1:"Use plot-level infrastructure already registered in Black Swan.",safe2:"Use crop and succession quantities from the Game Plan.",safe3:"Do not infer bed placement or occupancy from historical spreadsheet containers.",advanced:"Open advanced crop-map workspace",source:"Source model: Garden map + Espacio ocupado x semana · physical ownership: Supabase after field verification",noData:"No physical plots are registered."},
 es:{eyebrow:"Dietrich · Camas y Capacidad",title:"Capacidad física sólo donde está verificada",description:"El Excel de Dietrich incluye Garden map y hojas de capacidad. Black Swan no convertirá esos dibujos en asignaciones precisas hasta que la identidad física de cada cama sea canónica.",plots:"Sectores físicos",beds:"Camas canónicas",allocations:"Asignaciones del plan",area:"Superficie registrada",warning:"La base actual todavía no contiene suficiente geometría/identidad verificada de camas para reproducir fielmente el Garden map de Dietrich. El mapa del Excel sigue siendo referencia hasta reconciliar las camas en terreno.",what:"Qué es seguro hoy",safe1:"Usar la infraestructura a nivel de sector ya registrada en Black Swan.",safe2:"Usar cantidades de cultivos y sucesiones del Game Plan.",safe3:"No inferir ubicación u ocupación de camas desde contenedores históricos del Excel.",advanced:"Abrir workspace avanzado de Crop Map",source:"Modelo fuente: Garden map + Espacio ocupado x semana · ownership físico: Supabase después de verificación en terreno",noData:"No hay sectores físicos registrados."},
 de:{eyebrow:"Dietrich · Beete & Kapazität",title:"Physische Kapazität nur bei verifizierten Daten",description:"Dietrichs Workbook enthält Garden map und Kapazitätsblätter. Black Swan erzeugt daraus keine präzisen Beetzuordnungen, bevor die physische Identität jedes Beets kanonisch ist.",plots:"Physische Flächen",beds:"Kanonische Beete",allocations:"Planzuordnungen",area:"Erfasste Fläche",warning:"Die aktuelle Datenbank enthält noch nicht genügend verifizierte Beetgeometrie/-identität, um Dietrichs Garden map zuverlässig abzubilden. Bis zur Feldabstimmung bleibt die Workbook-Karte Referenz.",what:"Was heute sicher ist",safe1:"Bereits registrierte Infrastruktur auf Flächenebene verwenden.",safe2:"Kultur- und Folgemengen aus dem Game Plan verwenden.",safe3:"Keine Beetposition oder Belegung aus historischen Spreadsheet-Containern ableiten.",advanced:"Erweiterten Crop-Map-Arbeitsbereich öffnen",source:"Quellmodell: Garden map + Espacio ocupado x semana · physischer Owner: Supabase nach Feldprüfung",noData:"Keine physischen Flächen erfasst."},
} as const

export default function DietrichCapacityPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const lang:Locale=language;const text=copy[lang]
 const [plans,setPlans]=useState<Plan[]>([]),[plots,setPlots]=useState<Plot[]>([]),[beds,setBeds]=useState<Bed[]>([]),[allocations,setAllocations]=useState<Allocation[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{let live=true;void Promise.all([
  supabase.from("orchard_game_plans").select("id,season,status").order("start_date",{ascending:false}),
  supabase.from("orchard_plots").select("id,name,size_sqm,status").order("name"),
  supabase.from("orchard_beds").select("id,plot_id,name,area_sqm,status").order("name"),
  supabase.from("orchard_bed_allocations").select("id,bed_id,crop_succession_id,allocated_area_sqm,planned_plants"),
 ]).then(([p,pl,b,a])=>{if(!live)return;setPlans((p.data??[]) as Plan[]);setPlots((pl.data??[]) as Plot[]);setBeds((b.data??[]) as Bed[]);setAllocations((a.data??[]) as Allocation[]);setLoading(false)});return()=>{live=false}},[supabase])
 const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null;const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const area=plots.reduce((sum,p)=>sum+Number(p.size_sqm??0),0);const advancedHref=`/${language}/orchard/crop-map${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`
 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1280px] px-4 py-8 sm:px-6 lg:px-8">
  <header className="mb-8 max-w-4xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">{text.eyebrow}</p><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-normal sm:text-4xl">{text.title}</h1>{plan?.season?<Badge variant="secondary">{plan.season}</Badge>:null}</div><p className="mt-3 text-sm leading-6 text-muted-foreground sm:text-base">{text.description}</p></header>
  {loading?<div className="py-12 text-sm text-muted-foreground">…</div>:<>
   <section className="mb-6 grid gap-px bg-[var(--bs-divider-subtle)] sm:grid-cols-4"><div className="bg-[var(--bs-surface-primary)] p-5"><Map className="h-4 w-4 text-muted-foreground"/><p className="mt-4 text-xs uppercase tracking-wide text-muted-foreground">{text.plots}</p><p className="mt-2 text-3xl tabular-nums">{plots.length}</p></div><div className="bg-[var(--bs-surface-primary)] p-5"><Rows3 className="h-4 w-4 text-muted-foreground"/><p className="mt-4 text-xs uppercase tracking-wide text-muted-foreground">{text.beds}</p><p className="mt-2 text-3xl tabular-nums">{beds.length}</p></div><div className="bg-[var(--bs-surface-primary)] p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{text.allocations}</p><p className="mt-2 text-3xl tabular-nums">{allocations.length}</p></div><div className="bg-[var(--bs-surface-primary)] p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{text.area}</p><p className="mt-2 text-3xl tabular-nums">{area.toLocaleString("es-CL",{maximumFractionDigits:0})}<span className="ml-1 text-sm text-muted-foreground">m²</span></p></div></section>
   <section className="mb-6 bg-[var(--bs-surface-primary)] p-5 sm:p-6"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-[var(--bs-warm-amber)]"/><p className="text-sm leading-6 text-muted-foreground">{text.warning}</p></div></section>
   <section className="bg-[var(--bs-surface-primary)] p-5 sm:p-6"><h2 className="text-xl font-normal">{text.what}</h2><div className="mt-5 grid gap-px bg-[var(--bs-divider-subtle)] md:grid-cols-3">{[text.safe1,text.safe2,text.safe3].map((item,index)=><div key={item} className="bg-[var(--bs-surface-secondary)] p-5"><span className="text-xs font-semibold text-muted-foreground">0{index+1}</span><p className="mt-3 text-sm leading-6">{item}</p></div>)}</div>{plots.length?<div className="mt-6 space-y-px">{plots.map(p=><div key={p.id} className="flex items-center justify-between gap-4 bg-[var(--bs-surface-secondary)] px-4 py-3"><span className="text-sm">{p.name}</span><span className="text-xs text-muted-foreground">{p.size_sqm!=null?`${Number(p.size_sqm).toLocaleString("es-CL")} m²`:"—"}</span></div>)}</div>:<p className="mt-5 text-sm text-muted-foreground">{text.noData}</p>}</section>
   <div className="mt-6 flex flex-col gap-3 border-t border-[var(--bs-divider-subtle)] pt-5 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span>{text.source}</span><Link href={advancedHref} className="inline-flex items-center gap-2 text-sm text-foreground">{text.advanced}<ArrowRight className="h-4 w-4"/></Link></div>
  </>}
 </main></AppLayout>
}
