export type Language = 'en' | 'es'

export const translations = {
  en: {
    // Core Operations
    'nav.core_operations': 'Core Operations',
    'nav.core_operations_desc': 'Manage bookings and business',
    'nav.dashboard': 'Dashboard',
    'nav.dashboard_tip': 'View main dashboard',
    'nav.bookings': 'Bookings',
    'nav.bookings_tip': 'Manage property bookings',
    'nav.invoices': 'Invoices',
    'nav.invoices_tip': 'Manage invoices',
    'nav.tasks': 'Tasks',
    'nav.tasks_tip': 'Track tasks and activities',
    
    // Sovereignty
    'nav.sovereignty': 'Sovereignty',
    'nav.sovereignty_desc': 'Personal development',
    'nav.sovereignty_dashboard': 'Sovereignty',
    'nav.sovereignty_dashboard_tip': 'Personal coaching dashboard',
    'nav.coach': 'Coach',
    'nav.coach_tip': 'Personal development coach',
    'nav.layers': 'Layers',
    'nav.layers_tip': 'Development layers',
    
    // Cattle Operations
    'nav.cattle_operations': 'Cattle Operations',
    'nav.cattle_operations_desc': 'Livestock management',
    'nav.cattle_health': 'Health',
    'nav.cattle_health_tip': 'Monitor cattle health',
    'nav.expert_coach': 'Expert Coach',
    'nav.expert_coach_tip': 'AI-powered expert guidance',
    'nav.business_plan': 'Business Plan',
    'nav.business_plan_tip': 'Business planning tools',
    'nav.pricing_costs': 'Costs',
    'nav.pricing_costs_tip': 'Pricing and costs analysis',
    
    // Property Management
    'nav.property_management': 'Property Management',
    'nav.property_management_desc': 'Assets and inventory',
    'nav.assets': 'Assets',
    'nav.assets_tip': 'Manage property assets',
    'nav.inventory': 'Inventory',
    'nav.inventory_tip': 'Track inventory',
    'nav.all_assets': 'All Assets',
    'nav.by_category': 'By Category',
    'nav.by_cost_center': 'By Cost Center',
    'nav.categories': 'Categories',
    'nav.cost_centers': 'Cost Centers',
    'nav.audit_logs': 'Audit Logs',
    'nav.operations': 'Operations',
    'nav.operations_tip': 'Operational management',
    'nav.fuel_consumption': 'Fuel',
    'nav.fuel_consumption_tip': 'Track fuel consumption',
    'nav.maintenance': 'Maintenance',
    'nav.maintenance_tip': 'Track maintenance',
    'nav.gis_map': 'GIS Map',
    'nav.gis_map_tip': 'Geographic information',
    'nav.kmz_viewer': 'KMZ Viewer',
    'nav.kmz_viewer_tip': 'View KMZ files',
    
    // Off-Grid Energy
    'nav.off_grid_energy': 'Off-Grid Energy',
    'nav.off_grid_energy_desc': 'Energy management',
    'nav.management': 'Management',
    'nav.management_tip': 'Energy management',
    'nav.energy_dashboard': 'Dashboard',
    'nav.energy_dashboard_tip': 'Energy analytics',
    'nav.reports': 'Reports',
    'nav.reports_tip': 'Energy reports',
    'nav.victron_setup': 'Victron Setup',
    'nav.victron_setup_tip': 'Victron system setup',
    'nav.integration_docs': 'Integration',
    'nav.integration_docs_tip': 'Integration documentation',
    
    // Orchard Farm
    'nav.orchard_farm': 'Orchard Farm',
    'nav.orchard_farm_desc': 'Fruit production',
    'nav.orchard_dashboard': 'Orchard',
    'nav.orchard_dashboard_tip': 'Orchard overview',
    'nav.orchard_crops': 'Crops',
    'nav.orchard_crops_tip': 'Manage orchard crops',
    'nav.orchard_care': 'Care',
    'nav.orchard_care_tip': 'Care activities',
    'nav.orchard_harvest': 'Harvest',
    'nav.orchard_harvest_tip': 'Harvest tracking',
    'nav.orchard_pests': 'Pests',
    'nav.orchard_pests_tip': 'Pest management',
    'nav.orchard_soil': 'Soil',
    'nav.orchard_soil_tip': 'Soil management',
    'nav.orchard_equipment': 'Equipment',
    'nav.orchard_equipment_tip': 'Equipment tracking',
    'nav.orchard_analytics': 'Analytics',
    'nav.orchard_analytics_tip': 'Production analytics',
    
    // Vineyard
    'nav.vineyard': 'Vineyard',
    'nav.vineyard_desc': 'Grape and wine production',
    'nav.vineyard_dashboard': 'Vineyard',
    'nav.vineyard_dashboard_tip': 'Vineyard overview',
    'nav.vineyard_vines': 'Vines',
    'nav.vineyard_vines_tip': 'Manage vineyard vines',
    'nav.vineyard_care': 'Care',
    'nav.vineyard_care_tip': 'Vine care activities',
    'nav.vineyard_harvest': 'Harvest',
    'nav.vineyard_harvest_tip': 'Grape harvest tracking',
    'nav.vineyard_pests': 'Pests',
    'nav.vineyard_pests_tip': 'Disease management',
    'nav.vineyard_soil': 'Soil',
    'nav.vineyard_soil_tip': 'Soil amendments',
    'nav.vineyard_equipment': 'Equipment',
    'nav.vineyard_equipment_tip': 'Equipment tracking',
    'nav.vineyard_analytics': 'Analytics',
    'nav.vineyard_analytics_tip': 'Yield and quality analytics',
    
    // Supply Chain
    'nav.supply_chain': 'Supply Chain',
    'nav.supply_chain_desc': 'Procurement',
    'nav.procurement': 'Procurement',
    'nav.procurement_tip': 'Procurement management',
    'nav.suppliers': 'Suppliers',
    'nav.suppliers_tip': 'Supplier management',
    'nav.analytics': 'Analytics',
    'nav.analytics_tip': 'Procurement analytics',
    
    // People Operations
    'nav.people_operations': 'People Operations',
    'nav.people_operations_desc': 'Team management',
    'nav.employees': 'Employees',
    'nav.employees_tip': 'Manage employees',
    'nav.volunteers': 'Volunteers',
    'nav.volunteers_tip': 'Volunteer management',
    'nav.activities': 'Activities',
    'nav.activities_tip': 'Activities calendar',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Concierge services',
    'nav.guest_requests': 'Guest Requests',
    'nav.guest_requests_tip': 'Handle guest requests',
    'nav.kitchen': 'Kitchen',
    'nav.kitchen_tip': 'Kitchen management',
    'nav.checklists': 'Checklists',
    'nav.checklists_tip': 'Task checklists',
    
    // Advanced
    'nav.advanced': 'Advanced',
    'nav.advanced_desc': 'System tools',
    'nav.facility_requests': 'Requests',
    'nav.facility_requests_tip': 'Facility requests',
    'nav.ai_ops': 'AI Ops',
    'nav.ai_ops_tip': 'AI operations',
    'nav.admin': 'Admin',
    'nav.admin_tip': 'System administration',
  },
  es: {
    // Core Operations
    'nav.core_operations': 'Operaciones Principales',
    'nav.core_operations_desc': 'Gestionar reservas y negocios',
    'nav.dashboard': 'Panel',
    'nav.dashboard_tip': 'Ver panel principal',
    'nav.bookings': 'Reservas',
    'nav.bookings_tip': 'Gestionar reservas de propiedades',
    'nav.invoices': 'Facturas',
    'nav.invoices_tip': 'Gestionar facturas',
    'nav.tasks': 'Tareas',
    'nav.tasks_tip': 'Rastrear tareas y actividades',
    
    // Sovereignty
    'nav.sovereignty': 'Soberanía',
    'nav.sovereignty_desc': 'Desarrollo personal',
    'nav.sovereignty_dashboard': 'Soberanía',
    'nav.sovereignty_dashboard_tip': 'Panel de coaching personal',
    'nav.coach': 'Entrenador',
    'nav.coach_tip': 'Entrenador de desarrollo personal',
    'nav.layers': 'Capas',
    'nav.layers_tip': 'Capas de desarrollo',
    
    // Cattle Operations
    'nav.cattle_operations': 'Operaciones Ganaderas',
    'nav.cattle_operations_desc': 'Gestión de ganado',
    'nav.cattle_health': 'Salud',
    'nav.cattle_health_tip': 'Monitorear salud del ganado',
    'nav.expert_coach': 'Entrenador Experto',
    'nav.expert_coach_tip': 'Orientación experta con IA',
    'nav.business_plan': 'Plan de Negocio',
    'nav.business_plan_tip': 'Herramientas de planificación',
    'nav.pricing_costs': 'Costos',
    'nav.pricing_costs_tip': 'Análisis de precios y costos',
    
    // Property Management
    'nav.property_management': 'Gestión de Propiedades',
    'nav.property_management_desc': 'Activos e inventario',
    'nav.assets': 'Activos',
    'nav.assets_tip': 'Gestionar activos de propiedades',
    'nav.inventory': 'Inventario',
    'nav.inventory_tip': 'Rastrear inventario',
    'nav.all_assets': 'Todos los Activos',
    'nav.by_category': 'Por Categoría',
    'nav.by_cost_center': 'Por Centro de Costos',
    'nav.categories': 'Categorías',
    'nav.cost_centers': 'Centros de Costos',
    'nav.audit_logs': 'Registros de Auditoría',
    'nav.operations': 'Operaciones',
    'nav.operations_tip': 'Gestión de operaciones',
    'nav.fuel_consumption': 'Combustible',
    'nav.fuel_consumption_tip': 'Rastrear consumo de combustible',
    'nav.maintenance': 'Mantenimiento',
    'nav.maintenance_tip': 'Rastrear mantenimiento',
    'nav.gis_map': 'Mapa GIS',
    'nav.gis_map_tip': 'Información geográfica',
    'nav.kmz_viewer': 'Visor KMZ',
    'nav.kmz_viewer_tip': 'Ver archivos KMZ',
    
    // Off-Grid Energy
    'nav.off_grid_energy': 'Energía Fuera de Red',
    'nav.off_grid_energy_desc': 'Gestión de energía',
    'nav.management': 'Gestión',
    'nav.management_tip': 'Gestión de energía',
    'nav.energy_dashboard': 'Panel',
    'nav.energy_dashboard_tip': 'Analítica de energía',
    'nav.reports': 'Reportes',
    'nav.reports_tip': 'Reportes de energía',
    'nav.victron_setup': 'Configuración Victron',
    'nav.victron_setup_tip': 'Configuración del sistema Victron',
    'nav.integration_docs': 'Integración',
    'nav.integration_docs_tip': 'Documentación de integración',
    
    // Orchard Farm
    'nav.orchard_farm': 'Huerto',
    'nav.orchard_farm_desc': 'Producción de frutas',
    'nav.orchard_dashboard': 'Huerto',
    'nav.orchard_dashboard_tip': 'Resumen del huerto',
    'nav.orchard_crops': 'Cultivos',
    'nav.orchard_crops_tip': 'Gestionar cultivos del huerto',
    'nav.orchard_care': 'Cuidado',
    'nav.orchard_care_tip': 'Actividades de cuidado',
    'nav.orchard_harvest': 'Cosecha',
    'nav.orchard_harvest_tip': 'Rastreo de cosecha',
    'nav.orchard_pests': 'Plagas',
    'nav.orchard_pests_tip': 'Gestión de plagas',
    'nav.orchard_soil': 'Suelo',
    'nav.orchard_soil_tip': 'Gestión del suelo',
    'nav.orchard_equipment': 'Equipos',
    'nav.orchard_equipment_tip': 'Rastreo de equipos',
    'nav.orchard_analytics': 'Analítica',
    'nav.orchard_analytics_tip': 'Analítica de producción',
    
    // Vineyard
    'nav.vineyard': 'Viña',
    'nav.vineyard_desc': 'Producción de uvas y vino',
    'nav.vineyard_dashboard': 'Viña',
    'nav.vineyard_dashboard_tip': 'Resumen de la viña',
    'nav.vineyard_vines': 'Vides',
    'nav.vineyard_vines_tip': 'Gestionar vides del viñedo',
    'nav.vineyard_care': 'Cuidado',
    'nav.vineyard_care_tip': 'Actividades de cuidado de vides',
    'nav.vineyard_harvest': 'Vendimia',
    'nav.vineyard_harvest_tip': 'Rastreo de vendimia',
    'nav.vineyard_pests': 'Enfermedades',
    'nav.vineyard_pests_tip': 'Gestión de enfermedades',
    'nav.vineyard_soil': 'Suelo',
    'nav.vineyard_soil_tip': 'Enmiendas del suelo',
    'nav.vineyard_equipment': 'Equipos',
    'nav.vineyard_equipment_tip': 'Rastreo de equipos',
    'nav.vineyard_analytics': 'Analítica',
    'nav.vineyard_analytics_tip': 'Analítica de rendimiento y calidad',
    
    // Supply Chain
    'nav.supply_chain': 'Cadena de Suministro',
    'nav.supply_chain_desc': 'Adquisiciones',
    'nav.procurement': 'Adquisiciones',
    'nav.procurement_tip': 'Gestión de adquisiciones',
    'nav.suppliers': 'Proveedores',
    'nav.suppliers_tip': 'Gestión de proveedores',
    'nav.analytics': 'Analítica',
    'nav.analytics_tip': 'Analítica de adquisiciones',
    
    // People Operations
    'nav.people_operations': 'Operaciones de Personal',
    'nav.people_operations_desc': 'Gestión de equipo',
    'nav.employees': 'Empleados',
    'nav.employees_tip': 'Gestionar empleados',
    'nav.volunteers': 'Voluntarios',
    'nav.volunteers_tip': 'Gestión de voluntarios',
    'nav.activities': 'Actividades',
    'nav.activities_tip': 'Calendario de actividades',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Servicios de concierge',
    'nav.guest_requests': 'Solicitudes de Huéspedes',
    'nav.guest_requests_tip': 'Atender solicitudes de huéspedes',
    'nav.kitchen': 'Cocina',
    'nav.kitchen_tip': 'Gestión de cocina',
    'nav.checklists': 'Listas de Verificación',
    'nav.checklists_tip': 'Listas de verificación de tareas',
    
    // Advanced
    'nav.advanced': 'Avanzado',
    'nav.advanced_desc': 'Herramientas del sistema',
    'nav.facility_requests': 'Solicitudes',
    'nav.facility_requests_tip': 'Solicitudes de instalaciones',
    'nav.ai_ops': 'Operaciones de IA',
    'nav.ai_ops_tip': 'Operaciones de IA',
    'nav.admin': 'Administrador',
    'nav.admin_tip': 'Administración del sistema',
  },
}
