export type Language = 'en' | 'es'

export const translations = {
  en: {
    // NEW: Operations Center
    'nav.operations_center': 'Operations Center',
    'nav.operations_center_desc': 'Core dashboards and management',
    
    // NEW: Infrastructure
    'nav.infrastructure': 'Infrastructure',
    'nav.infrastructure_desc': 'Properties, assets, and inventory',
    
    // NEW: Production
    'nav.production': 'Production',
    'nav.production_desc': 'Agriculture, livestock, and energy',
    
    // NEW: System
    'nav.system': 'System',
    'nav.system_desc': 'Administration and AI operations',
    
    // NEW: Additional Navigation Items
    'nav.issues': 'Issues & Requests',
    'nav.facility_requests_tip': 'Handle facility requests and issues',
    'nav.energy': 'Energy Management',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Concierge services and guest support',
    'nav.ai_ops': 'AI Operations',
    'nav.ai_ops_tip': 'AI-powered operational insights',
    'nav.admin': 'Admin',
    'nav.admin_tip': 'System administration',
    'nav.cattle_dashboard': 'Cattle',
    'nav.cattle_dashboard_tip': 'Livestock management dashboard',
    'nav.vineyard_dashboard': 'Vineyard',
    'nav.vineyard_dashboard_tip': 'Vineyard management and operations',
    'nav.vineyard_overview': 'Overview',
    'nav.vineyard_photos': 'Photos',
    'nav.vineyard_crops': 'Vines',
    'nav.vineyard_harvest': 'Harvest',
    'nav.vineyard_health': 'Health & Pests',
    
    // Core Operations
    'nav.core_operations': 'Core Operations',
    'nav.core_operations_desc': 'Manage bookings and business',
    'nav.dashboard': 'Dashboard',
    'nav.dashboard_tip': 'View main dashboard',
    'nav.bookings': 'Bookings',
    'nav.bookings_tip': 'Manage property bookings',
    'nav.invoices': 'Invoices',
    'nav.invoices_tip': 'Manage invoices',
    'nav.tasks': 'Tasks',
    'nav.tasks_tip': 'Track tasks and activities',
    
    // Sovereignty
    'nav.sovereignty': 'Sovereignty',
    'nav.sovereignty_desc': 'Personal development',
    'nav.sovereignty_dashboard': 'Sovereignty',
    'nav.sovereignty_dashboard_tip': 'Personal coaching dashboard',
    'nav.coach': 'Coach',
    'nav.coach_tip': 'Personal development coach',
    'nav.layers': 'Layers',
    'nav.layers_tip': 'Development layers',
    
    // Cattle Operations
    'nav.cattle_operations': 'Cattle Operations',
    'nav.cattle_operations_desc': 'Livestock management',
    'nav.cattle_health': 'Health',
    'nav.cattle_health_tip': 'Monitor cattle health',
    'nav.expert_coach': 'Expert Coach',
    'nav.expert_coach_tip': 'AI-powered expert guidance',
    'nav.business_plan': 'Business Plan',
    'nav.business_plan_tip': 'Business planning tools',
    'nav.pricing_costs': 'Costs',
    'nav.pricing_costs_tip': 'Pricing and costs analysis',
    
    // Property Management
    'nav.property_management': 'Property Management',
    'nav.property_management_desc': 'Assets and inventory',
    'nav.assets': 'Assets',
    'nav.assets_tip': 'Manage property assets',
    'nav.inventory': 'Inventory',
    'nav.inventory_tip': 'Track inventory',
    'nav.all_assets': 'All Assets',
    'nav.by_category': 'By Category',
    'nav.by_cost_center': 'By Cost Center',
    'nav.categories': 'Categories',
    'nav.cost_centers': 'Cost Centers',
    'nav.audit_logs': 'Audit Logs',
    'nav.operations': 'Operations',
    'nav.operations_tip': 'Operational management',
    'nav.fuel_consumption': 'Fuel',
    'nav.fuel_consumption_tip': 'Track fuel consumption',
    'nav.maintenance': 'Maintenance',
    'nav.maintenance_tip': 'Track maintenance',
    'nav.gis_map': 'GIS Map',
    'nav.gis_map_tip': 'Geographic information',
    'nav.kmz_viewer': 'KMZ Viewer',
    'nav.kmz_viewer_tip': 'View KMZ files',
    
    // Off-Grid Energy
    'nav.off_grid_energy': 'Off-Grid Energy',
    'nav.off_grid_energy_desc': 'Energy management',
    'nav.combustibles': 'Fuel Consumption',
    'nav.combustibles_tip': 'Track fuel consumption and detect anomalies',
    'nav.management': 'Management',
    'nav.management_tip': 'Energy management',
    'nav.energy_dashboard': 'Dashboard',
    'nav.energy_dashboard_tip': 'Energy analytics',
    'nav.reports': 'Reports',
    'nav.reports_tip': 'Energy reports',
    'nav.victron_setup': 'Victron Setup',
    'nav.victron_setup_tip': 'Victron system setup',
    'nav.integration_docs': 'Integration',
    'nav.integration_docs_tip': 'Integration documentation',
    
    // Orchard Farm
    'nav.orchard_farm': 'Orchard Farm',
    'nav.orchard_farm_desc': 'Fruit production',
    'nav.orchard_dashboard': 'Orchard',
    'nav.orchard_dashboard_tip': 'Orchard overview',
    'nav.orchard_crops': 'Crops',
    'nav.orchard_crops_tip': 'Manage orchard crops',
    'nav.orchard_care': 'Care',
    'nav.orchard_care_tip': 'Care activities',
    'nav.orchard_harvest': 'Harvest',
    'nav.orchard_harvest_tip': 'Harvest tracking',
    'nav.orchard_pests': 'Pests',
    'nav.orchard_pests_tip': 'Pest management',
    'nav.orchard_soil': 'Soil',
    'nav.orchard_soil_tip': 'Soil management',
    'nav.orchard_equipment': 'Equipment',
    'nav.orchard_equipment_tip': 'Equipment tracking',
    'nav.orchard_analytics': 'Analytics',
    'nav.orchard_analytics_tip': 'Production analytics',
    
    // Vineyard
    'nav.vineyard': 'Vineyard',
    'nav.vineyard_desc': 'Grape and wine production',
    'nav.vineyard_dashboard': 'Vineyard',
    'nav.vineyard_dashboard_tip': 'Vineyard overview',
    'nav.vineyard_photos': 'Photos',
    'nav.vineyard_photos_tip': 'Vine photos and gallery',
    'nav.vineyard_vines': 'Vines',
    'nav.vineyard_vines_tip': 'Manage vineyard vines',
    'nav.vineyard_care': 'Care',
    'nav.vineyard_care_tip': 'Vine care activities',
    'nav.vineyard_harvest': 'Harvest',
    'nav.vineyard_harvest_tip': 'Grape harvest tracking',
    'nav.vineyard_pests': 'Pests',
    'nav.vineyard_pests_tip': 'Disease management',
    'nav.vineyard_soil': 'Soil',
    'nav.vineyard_soil_tip': 'Soil amendments',
    'nav.vineyard_equipment': 'Equipment',
    'nav.vineyard_equipment_tip': 'Equipment tracking',
    'nav.vineyard_analytics': 'Analytics',
    'nav.vineyard_analytics_tip': 'Yield and quality analytics',
    
    // Supply Chain
    'nav.supply_chain': 'Supply Chain',
    'nav.supply_chain_desc': 'Procurement',
    'nav.procurement': 'Procurement',
    'nav.procurement_tip': 'Procurement management',
    'nav.suppliers': 'Suppliers',
    'nav.suppliers_tip': 'Supplier management',
    'nav.analytics': 'Analytics',
    'nav.analytics_tip': 'Procurement analytics',
    
    // People Operations
    'nav.people_operations': 'People Operations',
    'nav.people_operations_desc': 'Team management',
    'nav.employees': 'Employees',
    'nav.employees_tip': 'Manage employees',
    'nav.volunteers': 'Volunteers',
    'nav.volunteers_tip': 'Volunteer management',
    'nav.activities': 'Activities',
    'nav.activities_tip': 'Activities calendar',
    
    // Maintenance
    'nav.maintenance_requests': 'Maintenance',
    'nav.maintenance_requests_desc': 'Track maintenance and issues',
    'nav.maintenance': 'Maintenance',
    'nav.maintenance_tip': 'Track maintenance',
    'nav.facility_requests': 'Facility Requests',
    'nav.facility_requests_tip': 'Handle facility requests',
    'nav.checklists': 'Checklists',
    'nav.checklists_tip': 'Task checklists',
    
    // Tracking (Maps & KMZ)
    'nav.tracking': 'Maps & Tracking',
    'nav.tracking_desc': 'Geographic and operational tracking',
    'nav.gis_map': 'GIS Map',
    'nav.gis_map_tip': 'Geographic information',
    'nav.kmz_viewer': 'KMZ Viewer',
    'nav.kmz_viewer_tip': 'View KMZ files',
    'nav.operations': 'Operations',
    'nav.operations_tip': 'Operational management',
    
    // Hospitality
    'nav.hospitality': 'Hospitality',
    'nav.hospitality_desc': 'Guest and concierge services',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Concierge services',
    'nav.guest_requests': 'Guest Requests',
    'nav.guest_requests_tip': 'Handle guest requests',
    'nav.kitchen': 'Kitchen',
    'nav.kitchen_tip': 'Kitchen management',
    
    // Vineyard Pages
    'vineyard.loading': 'Loading...',
    'vineyard.title': 'Vineyard Management',
    'vineyard.description': 'Manage your vineyard plots, vines, and harvest records',
    'vineyard.care_logs': 'Care Logs',
    'vineyard.add_plot': 'Add Plot',
    'vineyard.total_plots': 'Total Plots',
    'vineyard.total_area': 'Total Area',
    'vineyard.active_plots': 'Active',
    'vineyard.avg_density': 'Avg Density',
    'vineyard.plots': 'Vineyard Plots',
    'vineyard.plots_description': 'View and manage all vineyard sections',
    'vineyard.no_plots': 'No vineyard plots yet',
    'vineyard.vines': 'Vine Management',
    'vineyard.vines_description': 'Track and manage individual vines and their health',
    'vineyard.add_vine': 'Add Vine',
    'vineyard.total_vines': 'Total Vines',
    'vineyard.search': 'Search vines...',
    'vineyard.care': 'Vineyard Care',
    'vineyard.care_description': 'Track pruning, fertilizing, and irrigation activities',
    'vineyard.log_activity': 'Log Activity',
    'vineyard.total_activities': 'Activities',
    'vineyard.total_cost': 'Total Cost',
    'vineyard.labor_hours': 'Labor Hours',
    'vineyard.fertilizer': 'Fertilizer',
    'vineyard.care_activities': 'Care Activities',
    'vineyard.care_activities_description': 'All pruning, fertilizing, and maintenance logs',
    'vineyard.no_care_logs': 'No care activities logged yet',
    'vineyard.harvest': 'Harvest Management',
    'vineyard.harvest_description': 'Record and track grape harvest with quality metrics',
    'vineyard.record_harvest': 'Record Harvest',
    'vineyard.total_yield': 'Total Yield',
    'vineyard.harvests_count': 'Harvest Records',
    'vineyard.avg_brix': 'Average Brix',
    'vineyard.avg_quality': 'Average Quality',
    'vineyard.harvest_records': 'Harvest Records',
    'vineyard.harvest_records_description': 'View all recorded harvests with quality analysis',
    'vineyard.no_harvests': 'No harvest records yet',
    'vineyard.pests': 'Pest & Disease Management',
    'vineyard.pests_description': 'Track pest and disease occurrences and treatments',
    'vineyard.log_pest': 'Log Issue',
    'vineyard.total_incidents': 'Incidents',
    'vineyard.active_issues': 'Active Issues',
    'vineyard.treatment_cost': 'Treatment Cost',
    'vineyard.critical': 'Critical',
    'vineyard.pest_records': 'Pest & Disease Records',
    'vineyard.pest_records_description': 'View all recorded pests and treatments',
    'vineyard.no_pest_records': 'No pest records yet',
    'vineyard.soil': 'Soil Management',
    'vineyard.soil_description': 'Track soil amendments and nutrient management',
    'vineyard.add_amendment': 'Add Amendment',
    'vineyard.amendments': 'Amendments',
    'vineyard.total_amount': 'Total Amount',
    'vineyard.amendment_cost': 'Cost',
    'vineyard.nitrogen': 'Nitrogen Added',
    'vineyard.amendments_log': 'Soil Amendments',
    'vineyard.amendments_log_description': 'View all soil amendments and nutrient applications',
    'vineyard.no_amendments': 'No soil amendments recorded yet',
    'vineyard.equipment': 'Equipment Management',
    'vineyard.equipment_description': 'Track vineyard equipment, maintenance schedules, and storage',
    'vineyard.add_equipment': 'Add Equipment',
    'vineyard.total_equipment': 'Total Equipment',
    'vineyard.equipment_list': 'Equipment',
    'vineyard.equipment_list_description': 'All vineyard equipment and maintenance tracking',
    'vineyard.no_equipment': 'No equipment recorded yet',
    'vineyard.analytics': 'Vineyard Analytics',
    'vineyard.analytics_description': 'Comprehensive analytics for yield, quality, and vineyard performance',
    'vineyard.total_production': 'Total Production',
    'vineyard.production_metrics': 'Production Metrics',
    'vineyard.analytics_dashboard': 'Analytics Dashboard',
    'vineyard.analytics_description_long': 'View detailed analytics and performance metrics',
    
    // Orchard Pages
    'orchard.loading': 'Loading...',
    'orchard.title': 'Orchard Management',
    'orchard.description': 'Manage your orchard plots and harvest records',
    'orchard.care_logs': 'Care Logs',
    'orchard.add_plot': 'Add Plot',
    'orchard.add_care_log': 'Add Care Log',
    'orchard.total_plots': 'Total Plots',
    'orchard.plots': 'Plots',
    'orchard.active': 'Active',
    'orchard.total_yield': 'Total Yield',
    'orchard.vegetable_garden': 'Vegetable Garden',
    'orchard.herb_garden': 'Herb Garden',
    'orchard.fruit_garden': 'Fruit Garden',
    'orchard.ph_level': 'pH Level',
    'orchard.sunlight_hours': 'Sunlight Hours',
    'orchard.irrigation': 'Irrigation',
    'orchard.plot_size': 'Plot Size',
    'orchard.crops': 'Crops',
    'orchard.add_crop': 'Add Crop',
    'orchard.crop_name': 'Search crops...',
    'orchard.equipment': 'Equipment',
    'orchard.equipment_name': 'Equipment Name',
    'orchard.harvest_records': 'Harvest Records',
    'orchard.harvest_quantity': 'Harvest Quantity',
    'orchard.pest_logs': 'Pest Logs',
    'orchard.pest_type': 'Pest Type',
    'orchard.soil_amendments': 'Soil Amendments',
    'orchard.amendment_type': 'Amendment Type',
    'orchard.yield_analytics': 'Yield Analytics',
    'orchard.status_active': 'Active',
    'orchard.status_inactive': 'Inactive',
    'orchard.status_paused': 'Paused',
    'orchard.irrigation_drip': 'Drip Irrigation',
    'orchard.irrigation_sprinkler': 'Sprinkler',
    'orchard.irrigation_flood': 'Flood Irrigation',
    'orchard.unit_kg': 'kg',
    'orchard.filter_by_status': 'Filter by status',
    'orchard.filter_by_plot': 'Filter by plot',
    'orchard.all_status': 'All Status',
    'orchard.all_plots': 'All Plots',
    'orchard.add': 'Add',
    'orchard.edit': 'Edit',
    'orchard.delete': 'Delete',
    'orchard.cancel': 'Cancel',
    'orchard.save': 'Save',
    'orchard.search': 'Search',
    'orchard.no_data': 'No data found',
    'orchard.confirm_delete': 'Are you sure you want to delete this?',
    'orchard.severity_low': 'Low',
    'orchard.severity_medium': 'Medium',
    'orchard.severity_high': 'High',
    'orchard.condition_excellent': 'Excellent',
    'orchard.condition_good': 'Good',
    'orchard.condition_fair': 'Fair',
    'orchard.condition_poor': 'Poor',
    'orchard.needs_maintenance': 'Needs Maintenance',
    'orchard.unknown': 'Unknown',
    'orchard.loading': 'Loading...',
    'orchard.total_crops': 'Total Crops',
    'orchard.active': 'active',
    'orchard.total_yield': 'Total Yield',
    'orchard.market_value': 'Market Value',
    'orchard.avg_quality': 'Avg Quality',
    'orchard.no_analytics_data': 'No analytics data available',
    'orchard.comprehensive_analysis': 'Comprehensive performance analysis and metrics',
    'orchard.total_equipment': 'Total Equipment',
    'orchard.equipment_active': 'Active',
    'orchard.needs_maintenance_count': 'Needs Maintenance',
    'orchard.equipment_types': 'Equipment Types',
    'orchard.equipment_description': 'Manage tools and equipment inventory',
    'orchard.no_equipment': 'No equipment records found',
    'orchard.garden_tools': 'Garden tools and equipment inventory',
    'orchard.total_incidents': 'Total Incidents',
    'orchard.high_severity': 'High Severity',
    'orchard.treated': 'Treated',
    'orchard.avg_effectiveness': 'Avg Effectiveness',
    'orchard.pest_description': 'Monitor and track pests and diseases affecting your crops',
    'orchard.no_pests': 'No pest records found',
    'orchard.total_amendments': 'Total Amendments',
    'orchard.total_applied': 'Total Applied',
    'orchard.amendment_types': 'Amendment Types',
    'orchard.soil_description': 'Manage soil health and amendments',
    'orchard.no_amendments': 'No soil amendments recorded',
    'orchard.soil_enhancement': 'Soil enhancement and fertilizer applications',
    'orchard.never': 'Never',
    
    // Assets Pages
    'assets.title': 'Asset Management',
    'assets.description': 'Manage and track property assets',
    'assets.add_asset': 'Add Asset',
    'assets.export': 'Export',
    'assets.search_placeholder': 'Search assets...',
    'assets.filter_by_type': 'Filter by type',
    'assets.all_types': 'All Types',
    'assets.filter_critical': 'Filter critical',
    'assets.all_critical': 'All Critical',
    'assets.critical_only': 'Critical Only',
    'assets.non_critical': 'Non-Critical',
    'assets.sort_by': 'Sort by',
    'assets.name': 'Name',
    'assets.type': 'Type',
    'assets.location': 'Location',
    'assets.last_audit': 'Last Audit',
    'assets.last_audit_date': 'Last Audit Date',
    'assets.description': 'Description',
    'assets.critical': 'Critical',
    'assets.critical_yes': 'Yes',
    'assets.critical_no': 'No',
    'assets.never_audited': 'Never Audited',
    'assets.analytics_title': 'Asset Analytics',
    'assets.analytics_description': 'Asset overview and analytics',
    'assets.total_assets': 'Total Assets',
    'assets.active_facilities': 'Active Facilities',
    'assets.critical_assets': 'Critical Assets',
    'assets.of_total': 'of total',
    'assets.audits_overdue': 'Audits Overdue',
    'assets.overdue_assets': 'overdue assets',
    'assets.maintenance_due': 'Maintenance Due',
    'assets.pending_tasks': 'Pending Tasks',
    'assets.by_type': 'Assets by Type',
    'assets.type_distribution': 'Distribution by type',
    'assets.add_log': 'Add Log',
    'assets.view_manual': 'View Manual',
    
    // Bookings Pages
    'bookings.management': 'Booking Management',
    'bookings.manage_reservations': 'Manage property reservations and bookings',
    'bookings.single_property': 'Single Property',
    'bookings.all_properties': 'All Properties',
    'bookings.properties': 'Properties',
    'bookings.no_properties': 'No properties found',
    'bookings.total_beds': 'Total Beds',
    'bookings.active_bookings': 'Active Bookings',
    'bookings.occupancy': 'Occupancy',
    'bookings.revenue': 'Revenue',
    'bookings.calendar': 'Calendar',
    'bookings.facilities': 'Facilities',
    'bookings.rooms': 'Rooms',
    'bookings.guests': 'Guests',
    'bookings.reports': 'Reports',
    
    // Invoices Pages
    'invoices.management': 'Invoice Management',
    'invoices.create_edit_manage': 'Create, edit, and manage invoices',
    'invoices.new_invoice': 'New Invoice',
    'invoices.search_invoices': 'Search Invoices',
    'invoices.search_placeholder': 'Search by invoice number or client...',
    'invoices.all_invoices': 'All Invoices',
    'invoices.loading': 'Loading invoices...',
    'invoices.no_invoices': 'No invoices found',
    'invoices.delete_confirmation': 'Are you sure you want to delete this invoice?',
    
    // Dashboard Pages
    'dashboard.title': 'Dashboard',
    'dashboard.description': 'Welcome back! Here\'s your property overview',
    'dashboard.total_rooms': 'Total Rooms',
    'dashboard.total_rooms_desc': 'All available rooms',
    'dashboard.total_beds': 'Total Beds',
    'dashboard.total_beds_desc': 'Across all rooms',
    'dashboard.occupancy_rate': 'Occupancy Rate',
    'dashboard.occupancy_rate_desc': 'Current occupancy',
    'dashboard.active_reservations': 'Active Reservations',
    'dashboard.active_reservations_desc': 'Ongoing bookings',
    'dashboard.todays_checkins': 'Today\'s Check-ins',
    'dashboard.todays_checkins_desc': 'Expected arrivals',
    'dashboard.todays_checkouts': 'Today\'s Check-outs',
    'dashboard.todays_checkouts_desc': 'Expected departures',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.booking_calendar': 'Booking Calendar',
    'dashboard.booking_calendar_desc': 'View and manage reservations',
    'dashboard.property_management': 'Property Management',
    'dashboard.property_management_desc': 'Manage properties and facilities',
    'dashboard.maintenance': 'Maintenance',
    'dashboard.maintenance_desc': 'Track maintenance tasks',
    'dashboard.analytics': 'Analytics',
    'dashboard.analytics_desc': 'View detailed analytics',
    
    // Tasks Pages
    'tasks.title': 'Tasks',
    'tasks.description': 'Task coordination system',
    'tasks.new_today': 'New Today',
    'tasks.pending': 'Pending',
    'tasks.completed_week': 'Completed (Week)',
    'tasks.users': 'Users',
    'tasks.add_task': 'Add Task',
    'tasks.new': 'New',
    'tasks.in_progress': 'In Progress',
    'tasks.completed': 'Completed',
    'tasks.cancelled': 'Cancelled',
    'tasks.low': 'Low',
    'tasks.medium': 'Medium',
    'tasks.high': 'High',
    'tasks.urgent': 'Urgent',
    'tasks.select_task': 'Select a task to view details',
    'tasks.no_tasks': 'No tasks found',
    
    // Sovereignty Pages
    'sovereignty.title': 'Sovereignty Management',
    'sovereignty.description': 'Track and improve your operational self-sufficiency across all systems',
    'sovereignty.self_sufficiency': 'Self Sufficiency',
    'sovereignty.dependencies': 'Critical Dependencies',
    'sovereignty.high': 'high risk',
    'sovereignty.categories_tracked': 'Categories Tracked',
    'sovereignty.energy': 'Energy',
    'sovereignty.food': 'Food',
    'sovereignty.water': 'Water',
    'sovereignty.people': 'People',
    'sovereignty.software': 'Software',
    'sovereignty.assets': 'Assets',
    'sovereignty.by_category': 'by Category',
    'sovereignty.compare_systems': 'Compare self-sufficiency across different operational areas',
    'sovereignty.metrics': 'Sovereignty Metrics',
    'sovereignty.all_categories': 'All Categories',
    'sovereignty.critical_dependencies': 'Critical Dependencies',
    'sovereignty.high_risk_external': 'High-risk external dependencies affecting operations',
    'sovereignty.timeline': 'Independence Timeline',
    'sovereignty.timeline_description': 'Track progress toward independence goals',
    'sovereignty.no_timeline_events': 'No timeline events yet',
    'sovereignty.improve_sovereignty': 'Ways to Improve Sovereignty',
    'sovereignty.energy_independence': 'Energy Independence',
    'sovereignty.build_team_skills': 'Build Team Skills',
    'sovereignty.manage_assets': 'Manage Assets',
    'sovereignty.view_reports': 'View Reports',
    'sovereignty.achievement_roadmap': 'Achievement Roadmap',
    'sovereignty.guidance_higher_levels': 'Guidance toward higher sovereignty levels',
    'sovereignty.step1_title': 'Assess Current State',
    'sovereignty.step1_desc': 'Identify all external dependencies and critical systems',
    'sovereignty.step2_title': 'Prioritize Dependencies',
    'sovereignty.step2_desc': 'Focus on highest-risk external dependencies first',
    'sovereignty.step3_title': 'Build Capabilities',
    'sovereignty.step3_desc': 'Develop internal capacity for critical functions',
    'sovereignty.step4_title': 'Implement Solutions',
    'sovereignty.step4_desc': 'Deploy systems for independence in priority areas',
    'sovereignty.step5_title': 'Test Resilience',
    'sovereignty.step5_desc': 'Verify systems work during disruptions',
    'sovereignty.step6_title': 'Optimize & Scale',
    'sovereignty.step6_desc': 'Improve efficiency and expand to other areas',
    'sovereignty.layers_title': 'Sovereignty Layers',
    'sovereignty.layers_description': 'Build independence through progressive self-sufficiency',
    'sovereignty.overall_progress': 'Overall Progress',
    'sovereignty.layer': 'Layer',
    'sovereignty.related_modules': 'Related Modules',
    'sovereignty.key_objectives': 'Key Objectives',
    'sovereignty.target': 'Target',
    'sovereignty.no_objectives': 'No objectives set for this layer',
    'sovereignty.dependencies_to_eliminate': 'Dependencies to Eliminate',
    'sovereignty.coach_title': 'Sovereignty Coach',
    'sovereignty.coach_subtitle': 'AI-powered guidance for achieving independence',
    'sovereignty.coach_header': 'Ask for Guidance',
    'sovereignty.coach_guidance': 'Get personalized recommendations for improving sovereignty',
    'sovereignty.coach_prompt': 'Ask me about improving your sovereignty...',
    
    // Cattle Operations Pages
    'cattle.title': 'Cattle Operations',
    'cattle.description': 'Manage cattle areas, health, production, and breeding programs',
    'cattle.add_area': 'Add Cattle Area',
    'cattle.areas': 'Cattle Areas',
    'cattle.areas_description': 'Manage livestock production areas and pastures',
    'cattle.total_areas': 'Total Areas',
    'cattle.total_capacity': 'Total Capacity',
    'cattle.total_cattle': 'Total Cattle',
    'cattle.active_areas': 'Active Areas',
    'cattle.area_name': 'Area Name',
    'cattle.description': 'Description',
    'cattle.status': 'Status',
    'cattle.hectares': 'Hectares',
    'cattle.capacity': 'Capacity',
    'cattle.grass_type': 'Grass Type',
    'cattle.breeding_type': 'Breeding Type',
    'cattle.business_unit': 'Business Unit',
    'cattle.notes': 'Notes',
    'cattle.loading': 'Loading cattle areas...',
    'cattle.no_areas': 'No cattle areas found',
    'cattle.delete_confirmation': 'Are you sure you want to delete this cattle area?',
    'cattle.health': 'Health Management',
    'cattle.health_description': 'Monitor cattle health, vaccinations, and medical records',
    'cattle.breeding': 'Breeding Program',
    'cattle.breeding_description': 'Track breeding records and genetic programs',
    'cattle.production': 'Production Tracking',
    'cattle.production_description': 'Monitor milk, meat, and other production metrics',
    'cattle.feed_management': 'Feed Management',
    'cattle.feed_management_description': 'Plan and manage feed nutrition',
    'cattle.expert_agent': 'Cattle Expert Agent',
    'cattle.expert_subtitle': 'AI-powered expert for cattle operations',
    'cattle.expert_guidance': 'Get expert recommendations for herd management',
    'cattle.expert_prompt': 'Ask me about cattle operations, breeding, health, or production...',
    'cattle.expert_placeholder': 'Ask about disease prevention, breeding strategies, feed planning, etc.',
    'cattle.business_plan': 'Business Plan',
    'cattle.business_plan_description': 'Financial projections and business planning',
    'cattle.profit_loss': 'Profit/Loss Analysis',
    'cattle.profit_loss_description': 'View financial performance by period',
    'cattle.year': 'Year',
    'cattle.month': 'Month',
    'cattle.profit': 'Profit',
    'cattle.loss': 'Loss',
    'cattle.revenue': 'Revenue',
    'cattle.expenses': 'Expenses',
    'cattle.net_income': 'Net Income',
    'cattle.forecast': 'Forecast',
    'cattle.forecast_description': 'Financial projections for future periods',
    'cattle.export': 'Export Report',
    'cattle.download_report': 'Download Report',
    'cattle.pricing_costs': 'Pricing & Costs',
    'cattle.pricing_costs_description': 'Manage animal pricing and operational costs',
    'cattle.pricing': 'Animal Pricing',
    'cattle.pricing_description': 'Current market prices for different animal types',
    'cattle.animal_type': 'Animal Type',
    'cattle.price': 'Price',
    'cattle.unit': 'Unit',
    'cattle.category': 'Category',
    'cattle.edit_price': 'Edit Price',
    'cattle.costs': 'Operational Costs',
    'cattle.costs_description': 'Track and manage operational expenses',
    'cattle.cost_type': 'Cost Type',
    'cattle.amount': 'Amount',
    'cattle.edit_cost': 'Edit Cost',
    'cattle.cost_analysis': 'Cost Analysis',
    'cattle.cost_breakdown': 'Cost Breakdown by Category',
    'cattle.total_costs': 'Total Costs',
    
    // Maintenance Pages
    'maintenance.title': 'Maintenance Tasks',
    'maintenance.description': 'Schedule and track maintenance activities',
    'maintenance.add_task': 'Add Task',
    'maintenance.total_tasks': 'Total Tasks',
    'maintenance.completed': 'Completed',
    'maintenance.overdue': 'Overdue',
    'maintenance.full_year_schedule': 'Full Year Schedule',
    'maintenance.view_maintenance_tasks': 'View maintenance tasks across all days',
    'maintenance.previous_year': 'Previous Year',
    'maintenance.current_year': 'Current Year',
    'maintenance.next_year': 'Next Year',
    'maintenance.calendar_legend': 'Calendar Legend',
    'maintenance.pending': 'Pending',
    'maintenance.task_scheduled': 'Task scheduled',
    'maintenance.task_finished': 'Task finished',
    'maintenance.task_past_due': 'Task past due date',
    
    // Advanced
    'nav.advanced': 'Advanced',
    'nav.advanced_desc': 'System tools',
    'nav.facility_requests': 'Requests',
    'nav.facility_requests_tip': 'Facility requests',
    'nav.ai_ops': 'AI Ops',
    'nav.ai_ops_tip': 'AI operations',
    'nav.admin': 'Admin',
    'nav.admin_tip': 'System administration',
  },
  es: {
    // NEW: Operations Center
    'nav.operations_center': 'Centro de Operaciones',
    'nav.operations_center_desc': 'Paneles centrales y gestión',
    
    // NEW: Infrastructure
    'nav.infrastructure': 'Infraestructura',
    'nav.infrastructure_desc': 'Propiedades, activos e inventario',
    
    // NEW: Production
    'nav.production': 'Producción',
    'nav.production_desc': 'Agricultura, ganadería y energía',
    
    // NEW: System
    'nav.system': 'Sistema',
    'nav.system_desc': 'Administración y operaciones de IA',
    
    // NEW: Additional Navigation Items
    'nav.issues': 'Problemas y Solicitudes',
    'nav.facility_requests_tip': 'Gestionar solicitudes e problemas de instalaciones',
    'nav.energy': 'Gestión de Energía',
    'nav.concierge': 'Conserje',
    'nav.concierge_tip': 'Servicios de conserjería y soporte',
    'nav.ai_ops': 'Operaciones de IA',
    'nav.ai_ops_tip': 'Información operacional impulsada por IA',
    'nav.admin': 'Administración',
    'nav.admin_tip': 'Administración del sistema',
    'nav.cattle_dashboard': 'Ganado',
    'nav.cattle_dashboard_tip': 'Panel de gestión de ganado',
    'nav.vineyard_dashboard': 'Viña',
    'nav.vineyard_dashboard_tip': 'Gestión y operaciones de viña',
    'nav.vineyard_overview': 'Vista General',
    'nav.vineyard_photos': 'Fotos',
    'nav.vineyard_crops': 'Cepas',
    'nav.vineyard_harvest': 'Cosecha',
    'nav.vineyard_health': 'Salud y Plagas',
    
    // Core Operations
    'nav.core_operations': 'Operaciones Principales',
    'nav.core_operations_desc': 'Gestionar reservas y negocios',
    'nav.dashboard': 'Panel',
    'nav.dashboard_tip': 'Ver panel principal',
    'nav.bookings': 'Reservas',
    'nav.bookings_tip': 'Gestionar reservas de propiedades',
    'nav.invoices': 'Facturas',
    'nav.invoices_tip': 'Gestionar facturas',
    'nav.tasks': 'Tareas',
    'nav.tasks_tip': 'Rastrear tareas y actividades',
    
    // Sovereignty
    'nav.sovereignty': 'Soberanía',
    'nav.sovereignty_desc': 'Desarrollo personal',
    'nav.sovereignty_dashboard': 'Soberanía',
    'nav.sovereignty_dashboard_tip': 'Panel de coaching personal',
    'nav.coach': 'Entrenador',
    'nav.coach_tip': 'Entrenador de desarrollo personal',
    'nav.layers': 'Capas',
    'nav.layers_tip': 'Capas de desarrollo',
    
    // Cattle Operations
    'nav.cattle_operations': 'Operaciones Ganaderas',
    'nav.cattle_operations_desc': 'Gestión de ganado',
    'nav.cattle_health': 'Salud',
    'nav.cattle_health_tip': 'Monitorear salud del ganado',
    'nav.expert_coach': 'Entrenador Experto',
    'nav.expert_coach_tip': 'Orientación experta con IA',
    'nav.business_plan': 'Plan de Negocio',
    'nav.business_plan_tip': 'Herramientas de planificación',
    'nav.pricing_costs': 'Costos',
    'nav.pricing_costs_tip': 'Análisis de precios y costos',
    
    // Property Management
    'nav.property_management': 'Gestión de Propiedades',
    'nav.property_management_desc': 'Activos e inventario',
    'nav.assets': 'Activos',
    'nav.assets_tip': 'Gestionar activos de propiedades',
    'nav.inventory': 'Inventario',
    'nav.inventory_tip': 'Rastrear inventario',
    'nav.all_assets': 'Todos los Activos',
    'nav.by_category': 'Por Categoría',
    'nav.by_cost_center': 'Por Centro de Costos',
    'nav.categories': 'Categorías',
    'nav.cost_centers': 'Centros de Costos',
    'nav.audit_logs': 'Registros de Auditoría',
    'nav.operations': 'Operaciones',
    'nav.operations_tip': 'Gestión de operaciones',
    'nav.fuel_consumption': 'Combustible',
    'nav.fuel_consumption_tip': 'Rastrear consumo de combustible',
    'nav.maintenance': 'Mantenimiento',
    'nav.maintenance_tip': 'Rastrear mantenimiento',
    'nav.gis_map': 'Mapa GIS',
    'nav.gis_map_tip': 'Información geográfica',
    'nav.kmz_viewer': 'Visor KMZ',
    'nav.kmz_viewer_tip': 'Ver archivos KMZ',
    
    // Off-Grid Energy
    'nav.off_grid_energy': 'Energía Fuera de Red',
    'nav.off_grid_energy_desc': 'Gestión de energía',
    'nav.combustibles': 'Consumo de Combustible',
    'nav.combustibles_tip': 'Rastrear consumo de combustible y detectar anomalías',
    'nav.management': 'Gestión',
    'nav.management_tip': 'Gestión de energía',
    'nav.energy_dashboard': 'Panel',
    'nav.energy_dashboard_tip': 'Analítica de energía',
    'nav.reports': 'Reportes',
    'nav.reports_tip': 'Reportes de energía',
    'nav.victron_setup': 'Configuración Victron',
    'nav.victron_setup_tip': 'Configuración del sistema Victron',
    'nav.integration_docs': 'Integración',
    'nav.integration_docs_tip': 'Documentación de integración',
    
    // Orchard Farm
    'nav.orchard_farm': 'Huerto',
    'nav.orchard_farm_desc': 'Producción de frutas',
    'nav.orchard_dashboard': 'Huerto',
    'nav.orchard_dashboard_tip': 'Panel de gestión de huerto',
    'nav.orchard_overview': 'Vista General',
    'nav.orchard_crops': 'Cultivos',
    'nav.orchard_care': 'Cuidado',
    'nav.orchard_health': 'Salud y Plagas',
    'nav.orchard_harvest': 'Cosecha',
    'nav.orchard_soil': 'Suelo',
    'nav.orchard_equipment': 'Equipo',
    'nav.orchard_analytics': 'Analítica',
    'nav.orchard_analytics_tip': 'Analítica de producción',
    
    // Vineyard
    'nav.vineyard': 'Viña',
    'nav.vineyard_desc': 'Producción de uvas y vino',
    'nav.vineyard_dashboard': 'Viña',
    'nav.vineyard_dashboard_tip': 'Resumen de la viña',
    'nav.vineyard_photos': 'Fotos',
    'nav.vineyard_photos_tip': 'Fotos de vides y galería',
    'nav.vineyard_vines': 'Vides',
    'nav.vineyard_vines_tip': 'Gestionar vides del viñedo',
    'nav.vineyard_care': 'Cuidado',
    'nav.vineyard_care_tip': 'Actividades de cuidado de vides',
    'nav.vineyard_harvest': 'Vendimia',
    'nav.vineyard_harvest_tip': 'Rastreo de vendimia',
    'nav.vineyard_pests': 'Enfermedades',
    'nav.vineyard_pests_tip': 'Gestión de enfermedades',
    'nav.vineyard_soil': 'Suelo',
    'nav.vineyard_soil_tip': 'Enmiendas del suelo',
    'nav.vineyard_equipment': 'Equipos',
    'nav.vineyard_equipment_tip': 'Rastreo de equipos',
    'nav.vineyard_analytics': 'Analítica',
    'nav.vineyard_analytics_tip': 'Analítica de rendimiento y calidad',
    
    // Supply Chain
    'nav.supply_chain': 'Cadena de Suministro',
    'nav.supply_chain_desc': 'Adquisiciones',
    'nav.procurement': 'Adquisiciones',
    'nav.procurement_tip': 'Gestión de adquisiciones',
    'nav.suppliers': 'Proveedores',
    'nav.suppliers_tip': 'Gestión de proveedores',
    'nav.analytics': 'Analítica',
    'nav.analytics_tip': 'Analítica de adquisiciones',
    
    // People Operations
    'nav.people_operations': 'Operaciones de Personal',
    'nav.people_operations_desc': 'Gestión de equipo',
    'nav.employees': 'Empleados',
    'nav.employees_tip': 'Gestionar empleados',
    'nav.volunteers': 'Voluntarios',
    'nav.volunteers_tip': 'Gestión de voluntarios',
    'nav.activities': 'Actividades',
    'nav.activities_tip': 'Calendario de actividades',
    
    // Maintenance
    'nav.maintenance_requests': 'Mantenimiento',
    'nav.maintenance_requests_desc': 'Rastrear mantenimiento y problemas',
    'nav.maintenance': 'Mantenimiento',
    'nav.maintenance_tip': 'Rastrear mantenimiento',
    'nav.facility_requests': 'Solicitudes de Instalación',
    'nav.facility_requests_tip': 'Atender solicitudes de instalación',
    'nav.checklists': 'Listas de Verificación',
    'nav.checklists_tip': 'Listas de verificación de tareas',
    
    // Tracking (Maps & KMZ)
    'nav.tracking': 'Mapas y Rastreo',
    'nav.tracking_desc': 'Rastreo geográfico y operacional',
    'nav.gis_map': 'Mapa SIG',
    'nav.gis_map_tip': 'Información geográfica',
    'nav.kmz_viewer': 'Visor KMZ',
    'nav.kmz_viewer_tip': 'Ver archivos KMZ',
    'nav.operations': 'Operaciones',
    'nav.operations_tip': 'Gestión operacional',
    
    // Hospitality
    'nav.hospitality': 'Hospitalidad',
    'nav.hospitality_desc': 'Servicios de huéspedes y concierge',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Servicios de concierge',
    'nav.guest_requests': 'Solicitudes de Huéspedes',
    'nav.guest_requests_tip': 'Atender solicitudes de huéspedes',
    'nav.kitchen': 'Cocina',
    'nav.kitchen_tip': 'Gestión de cocina',
    
    // Vineyard Pages
    'vineyard.loading': 'Cargando...',
    'vineyard.title': 'Gestión del Viñedo',
    'vineyard.description': 'Gestiona tus parcelas de viñedo, vides y registros de cosecha',
    'vineyard.care_logs': 'Registros de Cuidado',
    'vineyard.add_plot': 'Añadir Parcela',
    'vineyard.total_plots': 'Parcelas Totales',
    'vineyard.total_area': 'Área Total',
    'vineyard.active_plots': 'Activas',
    'vineyard.avg_density': 'Densidad Promedio',
    'vineyard.plots': 'Parcelas del Viñedo',
    'vineyard.plots_description': 'Ver y gestionar todas las secciones del viñedo',
    'vineyard.no_plots': 'Sin parcelas de viñedo aún',
    'vineyard.vines': 'Gestión de Vides',
    'vineyard.vines_description': 'Rastrear y gestionar vides individuales y su salud',
    'vineyard.add_vine': 'Añadir Vid',
    'vineyard.total_vines': 'Vides Totales',
    'vineyard.search': 'Buscar vides...',
    'vineyard.care': 'Cuidado del Viñedo',
    'vineyard.care_description': 'Rastrear actividades de poda, fertilización e irrigación',
    'vineyard.log_activity': 'Registrar Actividad',
    'vineyard.total_activities': 'Actividades',
    'vineyard.total_cost': 'Costo Total',
    'vineyard.labor_hours': 'Horas de Trabajo',
    'vineyard.fertilizer': 'Fertilizante',
    'vineyard.care_activities': 'Actividades de Cuidado',
    'vineyard.care_activities_description': 'Todos los registros de poda, fertilización y mantenimiento',
    'vineyard.no_care_logs': 'Sin actividades de cuidado registradas aún',
    'vineyard.harvest': 'Gestión de Vendimia',
    'vineyard.harvest_description': 'Registra y rastrea la cosecha de uva con métricas de calidad',
    'vineyard.record_harvest': 'Registrar Vendimia',
    'vineyard.total_yield': 'Rendimiento Total',
    'vineyard.harvests_count': 'Registros de Vendimia',
    'vineyard.avg_brix': 'Brix Promedio',
    'vineyard.avg_quality': 'Calidad Promedio',
    'vineyard.harvest_records': 'Registros de Vendimia',
    'vineyard.harvest_records_description': 'Ver todas las vendimias registradas con análisis de calidad',
    'vineyard.no_harvests': 'Sin registros de vendimia aún',
    'vineyard.pests': 'Gestión de Plagas y Enfermedades',
    'vineyard.pests_description': 'Rastrear ocurrencias de plagas y enfermedades y tratamientos',
    'vineyard.log_pest': 'Registrar Problema',
    'vineyard.total_incidents': 'Incidentes',
    'vineyard.active_issues': 'Problemas Activos',
    'vineyard.treatment_cost': 'Costo de Tratamiento',
    'vineyard.critical': 'Crítico',
    'vineyard.pest_records': 'Registros de Plagas y Enfermedades',
    'vineyard.pest_records_description': 'Ver todos los registros de plagas y tratamientos',
    'vineyard.no_pest_records': 'Sin registros de plagas aún',
    'vineyard.soil': 'Gestión del Suelo',
    'vineyard.soil_description': 'Rastrear enmiendas del suelo y gestión de nutrientes',
    'vineyard.add_amendment': 'Añadir Enmienda',
    'vineyard.amendments': 'Enmiendas',
    'vineyard.total_amount': 'Cantidad Total',
    'vineyard.amendment_cost': 'Costo',
    'vineyard.nitrogen': 'Nitrógeno Añadido',
    'vineyard.amendments_log': 'Enmiendas del Suelo',
    'vineyard.amendments_log_description': 'Ver todas las enmiendas del suelo y aplicaciones de nutrientes',
    'vineyard.no_amendments': 'Sin enmiendas del suelo registradas aún',
    'vineyard.equipment': 'Gestión de Equipos',
    'vineyard.equipment_description': 'Rastrear equipos del viñedo, horarios de mantenimiento y almacenamiento',
    'vineyard.add_equipment': 'Añadir Equipo',
    'vineyard.total_equipment': 'Equipos Totales',
    'vineyard.equipment_list': 'Equipos',
    'vineyard.equipment_list_description': 'Todos los equipos del viñedo y rastreo de mantenimiento',
    'vineyard.no_equipment': 'Sin equipos registrados aún',
    'vineyard.analytics': 'Analítica del Viñedo',
    'vineyard.analytics_description': 'Analítica completa para rendimiento, calidad y desempeño del viñedo',
    'vineyard.total_production': 'Producción Total',
    'vineyard.production_metrics': 'Métricas de Producción',
    'vineyard.analytics_dashboard': 'Panel de Analítica',
    'vineyard.analytics_description_long': 'Ver analítica detallada y métricas de desempeño',
    
    // Orchard Pages
    'orchard.loading': 'Cargando...',
    'orchard.title': 'Gestión del Huerto',
    'orchard.description': 'Gestiona tus parcelas del huerto y registros de cosecha',
    'orchard.care_logs': 'Registros de Cuidado',
    'orchard.add_plot': 'Añadir Parcela',
    'orchard.add_care_log': 'Añadir Registro de Cuidado',
    'orchard.total_plots': 'Parcelas Totales',
    'orchard.plots': 'Parcelas',
    'orchard.active': 'Activas',
    'orchard.total_yield': 'Rendimiento Total',
    'orchard.vegetable_garden': 'Huerto de Verduras',
    'orchard.herb_garden': 'Huerto de Hierbas',
    'orchard.fruit_garden': 'Huerto de Frutas',
    'orchard.ph_level': 'Nivel de pH',
    'orchard.sunlight_hours': 'Horas de Luz Solar',
    'orchard.irrigation': 'Irrigación',
    'orchard.plot_size': 'Tamaño de Parcela',
    'orchard.crops': 'Cultivos',
    'orchard.add_crop': 'Añadir Cultivo',
    'orchard.crop_name': 'Buscar cultivos...',
    'orchard.equipment': 'Equipos',
    'orchard.equipment_name': 'Nombre de Equipo',
    'orchard.harvest_records': 'Registros de Cosecha',
    'orchard.harvest_quantity': 'Cantidad de Cosecha',
    'orchard.pest_logs': 'Registros de Plagas',
    'orchard.pest_type': 'Tipo de Plaga',
    'orchard.soil_amendments': 'Enmiendas del Suelo',
    'orchard.amendment_type': 'Tipo de Enmienda',
    'orchard.yield_analytics': 'Analítica de Rendimiento',
    'orchard.status_active': 'Activa',
    'orchard.status_inactive': 'Inactiva',
    'orchard.status_paused': 'Pausada',
    'orchard.irrigation_drip': 'Riego por Goteo',
    'orchard.irrigation_sprinkler': 'Aspersor',
    'orchard.irrigation_flood': 'Riego por Inundación',
    'orchard.unit_kg': 'kg',
    'orchard.filter_by_status': 'Filtrar por estado',
    'orchard.filter_by_plot': 'Filtrar por parcela',
    'orchard.all_status': 'Todos los Estados',
    'orchard.all_plots': 'Todas las Parcelas',
    'orchard.add': 'Añadir',
    'orchard.edit': 'Editar',
    'orchard.delete': 'Eliminar',
    'orchard.cancel': 'Cancelar',
    'orchard.save': 'Guardar',
    'orchard.search': 'Buscar',
    'orchard.no_data': 'No se encontraron datos',
    'orchard.confirm_delete': '¿Estás seguro de que deseas eliminar esto?',
    'orchard.severity_low': 'Bajo',
    'orchard.severity_medium': 'Medio',
    'orchard.severity_high': 'Alto',
    'orchard.condition_excellent': 'Excelente',
    'orchard.condition_good': 'Bueno',
    'orchard.condition_fair': 'Regular',
    'orchard.condition_poor': 'Deficiente',
    'orchard.needs_maintenance': 'Necesita Mantenimiento',
    'orchard.unknown': 'Desconocido',
    'orchard.loading': 'Cargando...',
    'orchard.total_crops': 'Cultivos Totales',
    'orchard.active': 'activos',
    'orchard.total_yield': 'Rendimiento Total',
    'orchard.market_value': 'Valor de Mercado',
    'orchard.avg_quality': 'Calidad Promedio',
    'orchard.no_analytics_data': 'No hay datos de análisis disponibles',
    'orchard.comprehensive_analysis': 'Análisis completo de rendimiento y métricas',
    'orchard.total_equipment': 'Equipo Total',
    'orchard.equipment_active': 'Activo',
    'orchard.needs_maintenance_count': 'Necesita Mantenimiento',
    'orchard.equipment_types': 'Tipos de Equipos',
    'orchard.equipment_description': 'Gestionar inventario de herramientas y equipos',
    'orchard.no_equipment': 'No se encontraron registros de equipos',
    'orchard.garden_tools': 'Inventario de herramientas y equipos de jardín',
    'orchard.total_incidents': 'Incidentes Totales',
    'orchard.high_severity': 'Alta Gravedad',
    'orchard.treated': 'Tratados',
    'orchard.avg_effectiveness': 'Efectividad Promedio',
    'orchard.pest_description': 'Monitorear y rastrear plagas y enfermedades que afectan tus cultivos',
    'orchard.no_pests': 'No se encontraron registros de plagas',
    'orchard.total_amendments': 'Enmiendas Totales',
    'orchard.total_applied': 'Total Aplicado',
    'orchard.amendment_types': 'Tipos de Enmiendas',
    'orchard.soil_description': 'Gestionar la salud del suelo y enmiendas',
    'orchard.no_amendments': 'No se registraron enmiendas del suelo',
    'orchard.soil_enhancement': 'Aplicaciones de mejora del suelo y fertilizantes',
    'orchard.never': 'Nunca',
    
    // Assets Pages
    'assets.title': 'Gestión de Activos',
    'assets.description': 'Gestionar y rastrear activos de propiedades',
    'assets.add_asset': 'Añadir Activo',
    'assets.export': 'Exportar',
    'assets.search_placeholder': 'Buscar activos...',
    'assets.filter_by_type': 'Filtrar por tipo',
    'assets.all_types': 'Todos los Tipos',
    'assets.filter_critical': 'Filtrar críticos',
    'assets.all_critical': 'Todos los Críticos',
    'assets.critical_only': 'Solo Críticos',
    'assets.non_critical': 'No Críticos',
    'assets.sort_by': 'Ordenar por',
    'assets.name': 'Nombre',
    'assets.type': 'Tipo',
    'assets.location': 'Ubicación',
    'assets.last_audit': 'Última Auditoría',
    'assets.last_audit_date': 'Fecha Última Auditoría',
    'assets.description': 'Descripción',
    'assets.critical': 'Crítico',
    'assets.critical_yes': 'Sí',
    'assets.critical_no': 'No',
    'assets.never_audited': 'Nunca Auditado',
    'assets.analytics_title': 'Analítica de Activos',
    'assets.analytics_description': 'Descripción general y analítica de activos',
    'assets.total_assets': 'Activos Totales',
    'assets.active_facilities': 'Instalaciones Activas',
    'assets.critical_assets': 'Activos Críticos',
    'assets.of_total': 'del total',
    'assets.audits_overdue': 'Auditorías Vencidas',
    'assets.overdue_assets': 'activos vencidos',
    'assets.maintenance_due': 'Mantenimiento Debido',
    'assets.pending_tasks': 'Tareas Pendientes',
    'assets.by_type': 'Activos por Tipo',
    'assets.type_distribution': 'Distribución por tipo',
    'assets.add_log': 'Añadir Registro',
    'assets.view_manual': 'Ver Manual',
    
    // Bookings Pages
    'bookings.management': 'Gestión de Reservas',
    'bookings.manage_reservations': 'Gestionar reservas y reservaciones de propiedades',
    'bookings.single_property': 'Propiedad Única',
    'bookings.all_properties': 'Todas las Propiedades',
    'bookings.properties': 'Propiedades',
    'bookings.no_properties': 'No se encontraron propiedades',
    'bookings.total_beds': 'Camas Totales',
    'bookings.active_bookings': 'Reservas Activas',
    'bookings.occupancy': 'Ocupación',
    'bookings.revenue': 'Ingresos',
    'bookings.calendar': 'Calendario',
    'bookings.facilities': 'Instalaciones',
    'bookings.rooms': 'Habitaciones',
    'bookings.guests': 'Huéspedes',
    'bookings.reports': 'Reportes',
    
    // Invoices Pages
    'invoices.management': 'Gestión de Facturas',
    'invoices.create_edit_manage': 'Crear, editar y gestionar facturas',
    'invoices.new_invoice': 'Nueva Factura',
    'invoices.search_invoices': 'Buscar Facturas',
    'invoices.search_placeholder': 'Buscar por número de factura o cliente...',
    'invoices.all_invoices': 'Todas las Facturas',
    'invoices.loading': 'Cargando facturas...',
    'invoices.no_invoices': 'No se encontraron facturas',
    'invoices.delete_confirmation': '¿Estás seguro de que deseas eliminar esta factura?',
    
    // Dashboard Pages
    'dashboard.title': 'Panel de Control',
    'dashboard.description': '¡Bienvenido de vuelta! Aquí está tu descripción general de propiedades',
    'dashboard.total_rooms': 'Habitaciones Totales',
    'dashboard.total_rooms_desc': 'Todas las habitaciones disponibles',
    'dashboard.total_beds': 'Camas Totales',
    'dashboard.total_beds_desc': 'En todas las habitaciones',
    'dashboard.occupancy_rate': 'Tasa de Ocupación',
    'dashboard.occupancy_rate_desc': 'Ocupación actual',
    'dashboard.active_reservations': 'Reservas Activas',
    'dashboard.active_reservations_desc': 'Reservaciones en curso',
    'dashboard.todays_checkins': 'Check-ins de Hoy',
    'dashboard.todays_checkins_desc': 'Llegadas esperadas',
    'dashboard.todays_checkouts': 'Check-outs de Hoy',
    'dashboard.todays_checkouts_desc': 'Salidas esperadas',
    'dashboard.quick_actions': 'Acciones Rápidas',
    'dashboard.booking_calendar': 'Calendario de Reservas',
    'dashboard.booking_calendar_desc': 'Ver y gestionar reservaciones',
    'dashboard.property_management': 'Gestión de Propiedades',
    'dashboard.property_management_desc': 'Gestionar propiedades e instalaciones',
    'dashboard.maintenance': 'Mantenimiento',
    'dashboard.maintenance_desc': 'Rastrear tareas de mantenimiento',
    'dashboard.analytics': 'Analítica',
    'dashboard.analytics_desc': 'Ver analítica detallada',
    
    // Tasks Pages
    'tasks.title': 'Tareas',
    'tasks.description': 'Sistema de coordinación de tareas',
    'tasks.new_today': 'Nuevas Hoy',
    'tasks.pending': 'Pendientes',
    'tasks.completed_week': 'Completadas (Semana)',
    'tasks.users': 'Usuarios',
    'tasks.add_task': 'Añadir Tarea',
    'tasks.new': 'Nuevas',
    'tasks.in_progress': 'En Progreso',
    'tasks.completed': 'Completadas',
    'tasks.cancelled': 'Canceladas',
    'tasks.low': 'Baja',
    'tasks.medium': 'Media',
    'tasks.high': 'Alta',
    'tasks.urgent': 'Urgente',
    'tasks.select_task': 'Selecciona una tarea para ver detalles',
    'tasks.no_tasks': 'No se encontraron tareas',
    
    // Sovereignty Pages
    'sovereignty.title': 'Gestión de Soberanía',
    'sovereignty.description': 'Rastrear y mejorar tu autosuficiencia operacional en todos los sistemas',
    'sovereignty.self_sufficiency': 'Autosuficiencia',
    'sovereignty.dependencies': 'Dependencias Críticas',
    'sovereignty.high': 'riesgo alto',
    'sovereignty.categories_tracked': 'Categorías Rastreadas',
    'sovereignty.energy': 'Energía',
    'sovereignty.food': 'Alimentos',
    'sovereignty.water': 'Agua',
    'sovereignty.people': 'Personas',
    'sovereignty.software': 'Software',
    'sovereignty.assets': 'Activos',
    'sovereignty.by_category': 'por Categoría',
    'sovereignty.compare_systems': 'Comparar autosuficiencia en diferentes áreas operacionales',
    'sovereignty.metrics': 'Métricas de Soberanía',
    'sovereignty.all_categories': 'Todas las Categorías',
    'sovereignty.critical_dependencies': 'Dependencias Críticas',
    'sovereignty.high_risk_external': 'Dependencias externas de alto riesgo que afectan operaciones',
    'sovereignty.timeline': 'Cronograma de Independencia',
    'sovereignty.timeline_description': 'Rastrear progreso hacia objetivos de independencia',
    'sovereignty.no_timeline_events': 'Sin eventos en cronograma aún',
    'sovereignty.improve_sovereignty': 'Formas de Mejorar Soberanía',
    'sovereignty.energy_independence': 'Independencia Energética',
    'sovereignty.build_team_skills': 'Construir Habilidades del Equipo',
    'sovereignty.manage_assets': 'Gestionar Activos',
    'sovereignty.view_reports': 'Ver Reportes',
    'sovereignty.achievement_roadmap': 'Mapa de Logros',
    'sovereignty.guidance_higher_levels': 'Orientación hacia niveles más altos de soberanía',
    'sovereignty.step1_title': 'Evaluar Estado Actual',
    'sovereignty.step1_desc': 'Identificar todas las dependencias externas y sistemas críticos',
    'sovereignty.step2_title': 'Priorizar Dependencias',
    'sovereignty.step2_desc': 'Enfocarse primero en dependencias externas de mayor riesgo',
    'sovereignty.step3_title': 'Construir Capacidades',
    'sovereignty.step3_desc': 'Desarrollar capacidad interna para funciones críticas',
    'sovereignty.step4_title': 'Implementar Soluciones',
    'sovereignty.step4_desc': 'Desplegar sistemas para independencia en áreas prioritarias',
    'sovereignty.step5_title': 'Probar Resiliencia',
    'sovereignty.step5_desc': 'Verificar que sistemas funcionen durante disrupciones',
    'sovereignty.step6_title': 'Optimizar y Escalar',
    'sovereignty.step6_desc': 'Mejorar eficiencia y expandir a otras áreas',
    'sovereignty.layers_title': 'Capas de Soberanía',
    'sovereignty.layers_description': 'Construir independencia mediante autosuficiencia progresiva',
    'sovereignty.overall_progress': 'Progreso General',
    'sovereignty.layer': 'Capa',
    'sovereignty.related_modules': 'Módulos Relacionados',
    'sovereignty.key_objectives': 'Objetivos Clave',
    'sovereignty.target': 'Objetivo',
    'sovereignty.no_objectives': 'Sin objetivos establecidos para esta capa',
    'sovereignty.dependencies_to_eliminate': 'Dependencias a Eliminar',
    'sovereignty.coach_title': 'Entrenador de Soberanía',
    'sovereignty.coach_subtitle': 'Orientación con IA para lograr independencia',
    'sovereignty.coach_header': 'Pedir Orientación',
    'sovereignty.coach_guidance': 'Obtén recomendaciones personalizadas para mejorar soberanía',
    'sovereignty.coach_prompt': 'Pregúntame sobre mejorar tu soberanía...',
    
    // Cattle Operations Pages
    'cattle.title': 'Operaciones Ganaderas',
    'cattle.description': 'Gestionar áreas ganaderas, salud, producción y programas de cría',
    'cattle.add_area': 'Añadir Área Ganadera',
    'cattle.areas': 'Áreas Ganaderas',
    'cattle.areas_description': 'Gestionar áreas de producción ganadera y pastos',
    'cattle.total_areas': 'Áreas Totales',
    'cattle.total_capacity': 'Capacidad Total',
    'cattle.total_cattle': 'Ganado Total',
    'cattle.active_areas': 'Áreas Activas',
    'cattle.area_name': 'Nombre del Área',
    'cattle.description': 'Descripción',
    'cattle.status': 'Estado',
    'cattle.hectares': 'Hectáreas',
    'cattle.capacity': 'Capacidad',
    'cattle.grass_type': 'Tipo de Pasto',
    'cattle.breeding_type': 'Tipo de Cría',
    'cattle.business_unit': 'Unidad de Negocio',
    'cattle.notes': 'Notas',
    'cattle.loading': 'Cargando áreas ganaderas...',
    'cattle.no_areas': 'No se encontraron áreas ganaderas',
    'cattle.delete_confirmation': '¿Estás seguro de que deseas eliminar esta área ganadera?',
    'cattle.health': 'Gestión de Salud',
    'cattle.health_description': 'Monitorear salud del ganado, vacunaciones y registros médicos',
    'cattle.breeding': 'Programa de Cría',
    'cattle.breeding_description': 'Rastrear registros de cría y programas genéticos',
    'cattle.production': 'Rastreo de Producción',
    'cattle.production_description': 'Monitorear métricas de producción de leche, carne y otros',
    'cattle.feed_management': 'Gestión de Alimentación',
    'cattle.feed_management_description': 'Planificar y gestionar nutrición del ganado',
    'cattle.expert_agent': 'Experto Ganadero',
    'cattle.expert_subtitle': 'Experto con IA para operaciones ganaderas',
    'cattle.expert_guidance': 'Obtén recomendaciones expertas para gestión de hato',
    'cattle.expert_prompt': 'Pregúntame sobre operaciones ganaderas, cría, salud o producción...',
    'cattle.expert_placeholder': 'Pregunta sobre prevención de enfermedades, estrategias de cría, planificación de alimentos, etc.',
    'cattle.business_plan': 'Plan de Negocio',
    'cattle.business_plan_description': 'Proyecciones financieras y planificación empresarial',
    'cattle.profit_loss': 'Análisis de Ganancias/Pérdidas',
    'cattle.profit_loss_description': 'Ver desempeño financiero por período',
    'cattle.year': 'Año',
    'cattle.month': 'Mes',
    'cattle.profit': 'Ganancia',
    'cattle.loss': 'Pérdida',
    'cattle.revenue': 'Ingresos',
    'cattle.expenses': 'Gastos',
    'cattle.net_income': 'Ingreso Neto',
    'cattle.forecast': 'Proyección',
    'cattle.forecast_description': 'Proyecciones financieras para períodos futuros',
    'cattle.export': 'Exportar Reporte',
    'cattle.download_report': 'Descargar Reporte',
    'cattle.pricing_costs': 'Precios y Costos',
    'cattle.pricing_costs_description': 'Gestionar precios de animales y costos operacionales',
    'cattle.pricing': 'Precios de Animales',
    'cattle.pricing_description': 'Precios de mercado actual para diferentes tipos de animales',
    'cattle.animal_type': 'Tipo de Animal',
    'cattle.price': 'Precio',
    'cattle.unit': 'Unidad',
    'cattle.category': 'Categoría',
    'cattle.edit_price': 'Editar Precio',
    'cattle.costs': 'Costos Operacionales',
    'cattle.costs_description': 'Rastrear y gestionar gastos operacionales',
    'cattle.cost_type': 'Tipo de Costo',
    'cattle.amount': 'Cantidad',
    'cattle.edit_cost': 'Editar Costo',
    'cattle.cost_analysis': 'Análisis de Costos',
    'cattle.cost_breakdown': 'Desglose de Costos por Categoría',
    'cattle.total_costs': 'Costos Totales',
    
    // Maintenance Pages
    'maintenance.title': 'Tareas de Mantenimiento',
    'maintenance.description': 'Programar y rastrear actividades de mantenimiento',
    'maintenance.add_task': 'Añadir Tarea',
    'maintenance.total_tasks': 'Tareas Totales',
    'maintenance.completed': 'Completadas',
    'maintenance.overdue': 'Vencidas',
    'maintenance.full_year_schedule': 'Cronograma Completo del Año',
    'maintenance.view_maintenance_tasks': 'Ver tareas de mantenimiento en todos los días',
    'maintenance.previous_year': 'Año Anterior',
    'maintenance.current_year': 'Año Actual',
    'maintenance.next_year': 'Próximo Año',
    'maintenance.calendar_legend': 'Leyenda del Calendario',
    'maintenance.pending': 'Pendiente',
    'maintenance.task_scheduled': 'Tarea programada',
    'maintenance.task_finished': 'Tarea completada',
    'maintenance.task_past_due': 'Tarea vencida',
    
    // Advanced
    'nav.advanced': 'Avanzado',
    'nav.advanced_desc': 'Herramientas del sistema',
    'nav.facility_requests': 'Solicitudes',
    'nav.facility_requests_tip': 'Solicitudes de instalaciones',
    'nav.ai_ops': 'Operaciones de IA',
    'nav.ai_ops_tip': 'Operaciones de IA',
    'nav.admin': 'Administrador',
    'nav.admin_tip': 'Administración del sistema',
  },
}
