'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    'common.language': 'Language',
    'common.english': 'English',
    'common.spanish': 'Español',
    'nav.core_operations': 'Core Operations',
    'nav.core_operations_desc': 'Manage your property bookings and reservations',
    'nav.dashboard': 'Dashboard',
    'nav.dashboard_tip': 'Overview of your property',
    'nav.bookings': 'Bookings',
    'nav.bookings_tip': 'Manage reservations and availability',
    'nav.invoices': 'Invoices',
    'nav.invoices_tip': 'Manage invoices and payments',
    'nav.tasks': 'Tasks',
    'nav.tasks_tip': 'Daily management tasks',
    'nav.sovereignty': 'Sovereignty',
    'nav.sovereignty_desc': 'Track facility independence and self-sufficiency',
    'nav.sovereignty_dashboard': 'Dashboard',
    'nav.sovereignty_dashboard_tip': 'Track facility autonomy and independence',
    'nav.coach': 'Coach',
    'nav.coach_tip': 'AI advisor for achieving independence',
    'nav.layers': 'Layers',
    'nav.layers_tip': 'View 5-layer sovereignty pyramid',
    'nav.cattle_operations': 'Cattle Operations',
    'nav.cattle_operations_desc': 'Livestock management and breeding operations',
    'nav.cattle_health': 'Health Monitoring',
    'nav.cattle_health_tip': 'Biometric analysis, alerts, and veterinary tracking',
    'nav.expert_coach': 'Expert Coach',
    'nav.expert_coach_tip': 'AI advisor for cattle business',
    'nav.business_plan': 'Business Plan',
    'nav.business_plan_tip': 'Financial projections',
    'nav.pricing_costs': 'Pricing & Costs',
    'nav.pricing_costs_tip': 'Cost analysis and pricing',
    'nav.property_management': 'Property Management',
    'nav.property_management_desc': 'Configure and maintain your facility',
    'nav.assets': 'Assets',
    'nav.assets_tip': 'Inventory and equipment',
    'nav.inventory': 'Inventory',
    'nav.inventory_tip': 'Multimedia inventory tracking and QR codes',
    'nav.all_assets': 'All Assets',
    'nav.by_category': 'By Category',
    'nav.by_cost_center': 'By Cost Center',
    'nav.categories': 'Categories',
    'nav.cost_centers': 'Cost Centers',
    'nav.audit_logs': 'Audit Logs',
    'nav.operations': 'Operations',
    'nav.operations_tip': 'Monthly operations and vehicle trips with KMZ tracking',
    'nav.fuel_consumption': 'Fuel Consumption',
    'nav.fuel_consumption_tip': 'Track field fuel consumption and costs',
    'nav.maintenance': 'Maintenance',
    'nav.maintenance_tip': 'Schedule and track repairs',
    'nav.gis_map': 'GIS Map',
    'nav.gis_map_tip': 'Property location and layout',
    'nav.kmz_viewer': 'KMZ Viewer',
    'nav.kmz_viewer_tip': 'Upload and view KMZ overlays',
    'nav.off_grid_energy': 'Off Grid Energy',
    'nav.off_grid_energy_desc': 'Solar panels, batteries, and Victron monitoring',
    'nav.management': 'Management',
    'nav.management_tip': 'Solar panels and electricity consumption',
    'nav.energy_dashboard': 'Dashboard',
    'nav.energy_dashboard_tip': 'Real-time energy monitoring',
    'nav.reports': 'Reports',
    'nav.reports_tip': 'Historical reports and analytics',
    'nav.victron_setup': 'Victron Setup',
    'nav.victron_setup_tip': 'Victron integration guide',
    'nav.integration_docs': 'Integration Docs',
    'nav.integration_docs_tip': 'MQTT, Node-RED, and VRM API documentation',
    'nav.supply_chain': 'Supply Chain',
    'nav.supply_chain_desc': 'Procurement, suppliers, and acquisitions',
    'nav.procurement': 'Procurement',
    'nav.procurement_tip': 'Purchase orders and acquisitions',
    'nav.suppliers': 'Suppliers',
    'nav.suppliers_tip': 'Manage supplier contacts and relationships',
    'nav.analytics': 'Analytics',
    'nav.people_operations': 'People & Operations',
    'nav.people_operations_desc': 'Staff management and guest services',
    'nav.employees': 'Employees',
    'nav.employees_tip': 'Team management',
    'nav.volunteers': 'Volunteers',
    'nav.volunteers_tip': 'Volunteer coordination and tracking',
    'nav.activities': 'Activities Calendar',
    'nav.activities_tip': 'Plan and manage facility activities, events, and entertainment',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Guest communication',
    'nav.guest_requests': 'Guest Requests',
    'nav.guest_requests_tip': 'Tablet interface for hospitality requests',
    'nav.kitchen': 'Kitchen',
    'nav.kitchen_tip': 'Kitchen and food preparation facilities',
    'nav.checklists': 'Checklists',
    'nav.checklists_tip': 'Operational checklists',
    'nav.advanced': 'Advanced',
    'nav.advanced_desc': 'Analytics and system settings',
    'nav.facility_requests': 'Facility Requests',
    'nav.facility_requests_tip': 'Track facility requests and service tickets',
    'nav.ai_ops': 'AI Operations',
    'nav.ai_ops_tip': 'AI-powered insights',
    'nav.admin': 'Admin',
    'nav.admin_tip': 'System configuration',
    // Core Operations - Dashboard
    'dashboard.title': 'Blackswan Facility Core System',
    'dashboard.description': 'Professional facility management and booking system for your luxury vacation rental. Manage reservations, track availability, and optimize occupancy rates.',
    'dashboard.total_rooms': 'Total Rooms',
    'dashboard.total_rooms_desc': 'Registered properties',
    'dashboard.total_beds': 'Total Beds',
    'dashboard.total_beds_desc': 'Available inventory',
    'dashboard.occupancy_rate': 'Occupancy Rate',
    'dashboard.occupancy_rate_desc': 'Current utilization',
    'dashboard.active_reservations': 'Active Reservations',
    'dashboard.active_reservations_desc': 'Current bookings',
    'dashboard.todays_checkins': 'Today\'s Check-ins',
    'dashboard.todays_checkins_desc': 'Guests arriving today',
    'dashboard.todays_checkouts': 'Today\'s Check-outs',
    'dashboard.todays_checkouts_desc': 'Guests departing today',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.booking_calendar': 'Booking Calendar',
    'dashboard.booking_calendar_desc': 'View and manage all reservations',
    'dashboard.property_management': 'Property Management',
    'dashboard.property_management_desc': 'Configure rooms and amenities',
    'dashboard.maintenance': 'Maintenance',
    'dashboard.maintenance_desc': 'Schedule and track maintenance',
    'dashboard.analytics': 'Analytics',
    'dashboard.analytics_desc': 'View booking trends and insights',
    // Core Operations - Bookings
    'bookings.title': 'Bookings',
    'bookings.add_reservation': 'Add Reservation',
    'bookings.facilities': 'Facilities',
    'bookings.guests': 'Guests',
    'bookings.rooms': 'Rooms',
    'bookings.invoices': 'Invoices',
    'bookings.reports': 'Reports',
    // Core Operations - Tasks
    'tasks.title': 'Tasks',
    'tasks.add_task': 'Add Task',
    'tasks.low': 'Low',
    'tasks.medium': 'Medium',
    'tasks.high': 'High',
    'tasks.urgent': 'Urgent',
    'tasks.new': 'New',
    'tasks.in_progress': 'In Progress',
    'tasks.completed': 'Completed',
    'tasks.cancelled': 'Cancelled',
  },
  es: {
    'common.language': 'Idioma',
    'common.english': 'English',
    'common.spanish': 'Español',
    'nav.core_operations': 'Operaciones Principales',
    'nav.core_operations_desc': 'Administra tus reservas y reservaciones',
    'nav.dashboard': 'Panel',
    'nav.dashboard_tip': 'Resumen de tu propiedad',
    'nav.bookings': 'Reservas',
    'nav.bookings_tip': 'Gestiona reservas y disponibilidad',
    'nav.invoices': 'Facturas',
    'nav.invoices_tip': 'Administra facturas y pagos',
    'nav.tasks': 'Tareas',
    'nav.tasks_tip': 'Tareas de gestión diaria',
    'nav.sovereignty': 'Soberanía',
    'nav.sovereignty_desc': 'Monitorea la independencia y autosuficiencia de la instalación',
    'nav.sovereignty_dashboard': 'Panel',
    'nav.sovereignty_dashboard_tip': 'Monitorea la autonomía e independencia de la instalación',
    'nav.coach': 'Entrenador',
    'nav.coach_tip': 'Asesor de IA para lograr independencia',
    'nav.layers': 'Capas',
    'nav.layers_tip': 'Ver pirámide de soberanía de 5 capas',
    'nav.cattle_operations': 'Operaciones de Ganado',
    'nav.cattle_operations_desc': 'Gestión de ganadería y operaciones de reproducción',
    'nav.cattle_health': 'Monitoreo de Salud',
    'nav.cattle_health_tip': 'Análisis biométrico, alertas y seguimiento veterinario',
    'nav.expert_coach': 'Entrenador Experto',
    'nav.expert_coach_tip': 'Asesor de IA para negocios ganaderos',
    'nav.business_plan': 'Plan de Negocios',
    'nav.business_plan_tip': 'Proyecciones financieras',
    'nav.pricing_costs': 'Precios y Costos',
    'nav.pricing_costs_tip': 'Análisis de costos y precios',
    'nav.property_management': 'Gestión de Propiedades',
    'nav.property_management_desc': 'Configura y mantén tu instalación',
    'nav.assets': 'Activos',
    'nav.assets_tip': 'Inventario y equipo',
    'nav.inventory': 'Inventario',
    'nav.inventory_tip': 'Seguimiento de inventario multimedia y códigos QR',
    'nav.all_assets': 'Todos los Activos',
    'nav.by_category': 'Por Categoría',
    'nav.by_cost_center': 'Por Centro de Costo',
    'nav.categories': 'Categorías',
    'nav.cost_centers': 'Centros de Costo',
    'nav.audit_logs': 'Registros de Auditoría',
    'nav.operations': 'Operaciones',
    'nav.operations_tip': 'Operaciones mensuales y viajes de vehículos con seguimiento KMZ',
    'nav.fuel_consumption': 'Consumo de Combustible',
    'nav.fuel_consumption_tip': 'Monitorea el consumo de combustible y costos de campo',
    'nav.maintenance': 'Mantenimiento',
    'nav.maintenance_tip': 'Programa y monitorea reparaciones',
    'nav.gis_map': 'Mapa GIS',
    'nav.gis_map_tip': 'Ubicación y diseño de propiedad',
    'nav.kmz_viewer': 'Visor KMZ',
    'nav.kmz_viewer_tip': 'Carga y ve superposiciones KMZ',
    'nav.off_grid_energy': 'Energía Fuera de Red',
    'nav.off_grid_energy_desc': 'Paneles solares, baterías y monitoreo Victron',
    'nav.management': 'Gestión',
    'nav.management_tip': 'Paneles solares y consumo de electricidad',
    'nav.energy_dashboard': 'Panel',
    'nav.energy_dashboard_tip': 'Monitoreo de energía en tiempo real',
    'nav.reports': 'Reportes',
    'nav.reports_tip': 'Reportes e informes históricos',
    'nav.victron_setup': 'Configuración Victron',
    'nav.victron_setup_tip': 'Guía de integración Victron',
    'nav.integration_docs': 'Documentos de Integración',
    'nav.integration_docs_tip': 'Documentación de MQTT, Node-RED y VRM API',
    'nav.supply_chain': 'Cadena de Suministro',
    'nav.supply_chain_desc': 'Adquisición, proveedores y suministros',
    'nav.procurement': 'Adquisiciones',
    'nav.procurement_tip': 'Órdenes de compra y suministros',
    'nav.suppliers': 'Proveedores',
    'nav.suppliers_tip': 'Gestiona contactos y relaciones de proveedores',
    'nav.analytics': 'Análisis',
    'nav.analytics_tip': 'Análisis de gastos y desempeño de proveedores',
    'nav.people_operations': 'Personas y Operaciones',
    'nav.people_operations_desc': 'Gestión de personal y servicios de huéspedes',
    'nav.employees': 'Empleados',
    'nav.employees_tip': 'Gestión de equipo',
    'nav.volunteers': 'Voluntarios',
    'nav.volunteers_tip': 'Coordinación y seguimiento de voluntarios',
    'nav.activities': 'Calendario de Actividades',
    'nav.activities_tip': 'Planifica y administra actividades, eventos y entretenimiento de la instalación',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Comunicación con huéspedes',
    'nav.guest_requests': 'Solicitudes de Huéspedes',
    'nav.guest_requests_tip': 'Interfaz de tableta para solicitudes de hospitalidad',
    'nav.kitchen': 'Cocina',
    'nav.kitchen_tip': 'Instalaciones de cocina y preparación de alimentos',
    'nav.checklists': 'Listas de Verificación',
    'nav.checklists_tip': 'Listas de verificación operacionales',
    'nav.advanced': 'Avanzado',
    'nav.advanced_desc': 'Análisis y configuración del sistema',
    'nav.facility_requests': 'Solicitudes de Instalación',
    'nav.facility_requests_tip': 'Monitorea solicitudes de instalación y boletos de servicio',
    'nav.ai_ops': 'Operaciones de IA',
    'nav.ai_ops_tip': 'Información impulsada por IA',
    'nav.admin': 'Administración',
    'nav.admin_tip': 'Configuración del sistema',
    'nav.need_help': '¿Necesitas Ayuda?',
    'nav.press_cmd': 'Presiona ⌘K para buscar',
    'nav.version': 'BFCS v1.0',
    // Core Operations - Dashboard
    'dashboard.title': 'Sistema Central de Instalaciones Blackswan',
    'dashboard.description': 'Sistema profesional de gestión de instalaciones y reservas para tu alquiler vacacional de lujo. Administra reservas, monitorea disponibilidad y optimiza tasas de ocupación.',
    'dashboard.total_rooms': 'Habitaciones Totales',
    'dashboard.total_rooms_desc': 'Propiedades registradas',
    'dashboard.total_beds': 'Camas Totales',
    'dashboard.total_beds_desc': 'Inventario disponible',
    'dashboard.occupancy_rate': 'Tasa de Ocupación',
    'dashboard.occupancy_rate_desc': 'Utilización actual',
    'dashboard.active_reservations': 'Reservas Activas',
    'dashboard.active_reservations_desc': 'Reservas actuales',
    'dashboard.todays_checkins': 'Check-ins de Hoy',
    'dashboard.todays_checkins_desc': 'Huéspedes llegando hoy',
    'dashboard.todays_checkouts': 'Check-outs de Hoy',
    'dashboard.todays_checkouts_desc': 'Huéspedes partiendo hoy',
    'dashboard.quick_actions': 'Acciones Rápidas',
    'dashboard.booking_calendar': 'Calendario de Reservas',
    'dashboard.booking_calendar_desc': 'Ver y gestionar todas las reservas',
    'dashboard.property_management': 'Gestión de Propiedades',
    'dashboard.property_management_desc': 'Configura habitaciones y servicios',
    'dashboard.maintenance': 'Mantenimiento',
    'dashboard.maintenance_desc': 'Programa y monitorea mantenimiento',
    'dashboard.analytics': 'Análisis',
    'dashboard.analytics_desc': 'Ver tendencias e información de reservas',
    // Core Operations - Bookings
    'bookings.title': 'Reservas',
    'bookings.add_reservation': 'Agregar Reserva',
    'bookings.facilities': 'Instalaciones',
    'bookings.guests': 'Huéspedes',
    'bookings.rooms': 'Habitaciones',
    'bookings.invoices': 'Facturas',
    'bookings.reports': 'Reportes',
    // Core Operations - Tasks
    'tasks.title': 'Tareas',
    'tasks.add_task': 'Agregar Tarea',
    'tasks.low': 'Baja',
    'tasks.medium': 'Media',
    'tasks.high': 'Alta',
    'tasks.urgent': 'Urgente',
    'tasks.new': 'Nueva',
    'tasks.in_progress': 'En Progreso',
    'tasks.completed': 'Completada',
    'tasks.cancelled': 'Cancelada',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')
  const [isMounted, setIsMounted] = useState(false)

  useEffect(() => {
    setIsMounted(true)
    const saved = localStorage.getItem('language') as Language | null
    if (saved) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
