export type Language = 'en' | 'es'

export const translations = {
  en: {
    // Core Operations
    'nav.core_operations': 'Core Operations',
    'nav.core_operations_desc': 'Manage bookings and business',
    'nav.dashboard': 'Dashboard',
    'nav.dashboard_tip': 'View main dashboard',
    'nav.bookings': 'Bookings',
    'nav.bookings_tip': 'Manage property bookings',
    'nav.invoices': 'Invoices',
    'nav.invoices_tip': 'Manage invoices',
    'nav.tasks': 'Tasks',
    'nav.tasks_tip': 'Track tasks and activities',
    
    // Sovereignty
    'nav.sovereignty': 'Sovereignty',
    'nav.sovereignty_desc': 'Personal development',
    'nav.sovereignty_dashboard': 'Sovereignty',
    'nav.sovereignty_dashboard_tip': 'Personal coaching dashboard',
    'nav.coach': 'Coach',
    'nav.coach_tip': 'Personal development coach',
    'nav.layers': 'Layers',
    'nav.layers_tip': 'Development layers',
    
    // Cattle Operations
    'nav.cattle_operations': 'Cattle Operations',
    'nav.cattle_operations_desc': 'Livestock management',
    'nav.cattle_health': 'Health',
    'nav.cattle_health_tip': 'Monitor cattle health',
    'nav.expert_coach': 'Expert Coach',
    'nav.expert_coach_tip': 'AI-powered expert guidance',
    'nav.business_plan': 'Business Plan',
    'nav.business_plan_tip': 'Business planning tools',
    'nav.pricing_costs': 'Costs',
    'nav.pricing_costs_tip': 'Pricing and costs analysis',
    
    // Property Management
    'nav.property_management': 'Property Management',
    'nav.property_management_desc': 'Assets and inventory',
    'nav.assets': 'Assets',
    'nav.assets_tip': 'Manage property assets',
    'nav.inventory': 'Inventory',
    'nav.inventory_tip': 'Track inventory',
    'nav.all_assets': 'All Assets',
    'nav.by_category': 'By Category',
    'nav.by_cost_center': 'By Cost Center',
    'nav.categories': 'Categories',
    'nav.cost_centers': 'Cost Centers',
    'nav.audit_logs': 'Audit Logs',
    'nav.operations': 'Operations',
    'nav.operations_tip': 'Operational management',
    'nav.fuel_consumption': 'Fuel',
    'nav.fuel_consumption_tip': 'Track fuel consumption',
    'nav.maintenance': 'Maintenance',
    'nav.maintenance_tip': 'Track maintenance',
    'nav.gis_map': 'GIS Map',
    'nav.gis_map_tip': 'Geographic information',
    'nav.kmz_viewer': 'KMZ Viewer',
    'nav.kmz_viewer_tip': 'View KMZ files',
    
    // Off-Grid Energy
    'nav.off_grid_energy': 'Off-Grid Energy',
    'nav.off_grid_energy_desc': 'Energy management',
    'nav.management': 'Management',
    'nav.management_tip': 'Energy management',
    'nav.energy_dashboard': 'Dashboard',
    'nav.energy_dashboard_tip': 'Energy analytics',
    'nav.reports': 'Reports',
    'nav.reports_tip': 'Energy reports',
    'nav.victron_setup': 'Victron Setup',
    'nav.victron_setup_tip': 'Victron system setup',
    'nav.integration_docs': 'Integration',
    'nav.integration_docs_tip': 'Integration documentation',
    
    // Orchard Farm
    'nav.orchard_farm': 'Orchard Farm',
    'nav.orchard_farm_desc': 'Fruit production',
    'nav.orchard_dashboard': 'Orchard',
    'nav.orchard_dashboard_tip': 'Orchard overview',
    'nav.orchard_crops': 'Crops',
    'nav.orchard_crops_tip': 'Manage orchard crops',
    'nav.orchard_care': 'Care',
    'nav.orchard_care_tip': 'Care activities',
    'nav.orchard_harvest': 'Harvest',
    'nav.orchard_harvest_tip': 'Harvest tracking',
    'nav.orchard_pests': 'Pests',
    'nav.orchard_pests_tip': 'Pest management',
    'nav.orchard_soil': 'Soil',
    'nav.orchard_soil_tip': 'Soil management',
    'nav.orchard_equipment': 'Equipment',
    'nav.orchard_equipment_tip': 'Equipment tracking',
    'nav.orchard_analytics': 'Analytics',
    'nav.orchard_analytics_tip': 'Production analytics',
    
    // Vineyard
    'nav.vineyard': 'Vineyard',
    'nav.vineyard_desc': 'Grape and wine production',
    'nav.vineyard_dashboard': 'Vineyard',
    'nav.vineyard_dashboard_tip': 'Vineyard overview',
    'nav.vineyard_vines': 'Vines',
    'nav.vineyard_vines_tip': 'Manage vineyard vines',
    'nav.vineyard_care': 'Care',
    'nav.vineyard_care_tip': 'Vine care activities',
    'nav.vineyard_harvest': 'Harvest',
    'nav.vineyard_harvest_tip': 'Grape harvest tracking',
    'nav.vineyard_pests': 'Pests',
    'nav.vineyard_pests_tip': 'Disease management',
    'nav.vineyard_soil': 'Soil',
    'nav.vineyard_soil_tip': 'Soil amendments',
    'nav.vineyard_equipment': 'Equipment',
    'nav.vineyard_equipment_tip': 'Equipment tracking',
    'nav.vineyard_analytics': 'Analytics',
    'nav.vineyard_analytics_tip': 'Yield and quality analytics',
    
    // Supply Chain
    'nav.supply_chain': 'Supply Chain',
    'nav.supply_chain_desc': 'Procurement',
    'nav.procurement': 'Procurement',
    'nav.procurement_tip': 'Procurement management',
    'nav.suppliers': 'Suppliers',
    'nav.suppliers_tip': 'Supplier management',
    'nav.analytics': 'Analytics',
    'nav.analytics_tip': 'Procurement analytics',
    
    // People Operations
    'nav.people_operations': 'People Operations',
    'nav.people_operations_desc': 'Team management',
    'nav.employees': 'Employees',
    'nav.employees_tip': 'Manage employees',
    'nav.volunteers': 'Volunteers',
    'nav.volunteers_tip': 'Volunteer management',
    'nav.activities': 'Activities',
    'nav.activities_tip': 'Activities calendar',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Concierge services',
    'nav.guest_requests': 'Guest Requests',
    'nav.guest_requests_tip': 'Handle guest requests',
    'nav.kitchen': 'Kitchen',
    'nav.kitchen_tip': 'Kitchen management',
    'nav.checklists': 'Checklists',
    'nav.checklists_tip': 'Task checklists',
    
    // Vineyard Pages
    'vineyard.loading': 'Loading...',
    'vineyard.title': 'Vineyard Management',
    'vineyard.description': 'Manage your vineyard plots, vines, and harvest records',
    'vineyard.care_logs': 'Care Logs',
    'vineyard.add_plot': 'Add Plot',
    'vineyard.total_plots': 'Total Plots',
    'vineyard.total_area': 'Total Area',
    'vineyard.active_plots': 'Active',
    'vineyard.avg_density': 'Avg Density',
    'vineyard.plots': 'Vineyard Plots',
    'vineyard.plots_description': 'View and manage all vineyard sections',
    'vineyard.no_plots': 'No vineyard plots yet',
    'vineyard.vines': 'Vine Management',
    'vineyard.vines_description': 'Track and manage individual vines and their health',
    'vineyard.add_vine': 'Add Vine',
    'vineyard.total_vines': 'Total Vines',
    'vineyard.search': 'Search vines...',
    'vineyard.care': 'Vineyard Care',
    'vineyard.care_description': 'Track pruning, fertilizing, and irrigation activities',
    'vineyard.log_activity': 'Log Activity',
    'vineyard.total_activities': 'Activities',
    'vineyard.total_cost': 'Total Cost',
    'vineyard.labor_hours': 'Labor Hours',
    'vineyard.fertilizer': 'Fertilizer',
    'vineyard.care_activities': 'Care Activities',
    'vineyard.care_activities_description': 'All pruning, fertilizing, and maintenance logs',
    'vineyard.no_care_logs': 'No care activities logged yet',
    'vineyard.harvest': 'Harvest Management',
    'vineyard.harvest_description': 'Record and track grape harvest with quality metrics',
    'vineyard.record_harvest': 'Record Harvest',
    'vineyard.total_yield': 'Total Yield',
    'vineyard.harvests_count': 'Harvest Records',
    'vineyard.avg_brix': 'Average Brix',
    'vineyard.avg_quality': 'Average Quality',
    'vineyard.harvest_records': 'Harvest Records',
    'vineyard.harvest_records_description': 'View all recorded harvests with quality analysis',
    'vineyard.no_harvests': 'No harvest records yet',
    'vineyard.pests': 'Pest & Disease Management',
    'vineyard.pests_description': 'Track pest and disease occurrences and treatments',
    'vineyard.log_pest': 'Log Issue',
    'vineyard.total_incidents': 'Incidents',
    'vineyard.active_issues': 'Active Issues',
    'vineyard.treatment_cost': 'Treatment Cost',
    'vineyard.critical': 'Critical',
    'vineyard.pest_records': 'Pest & Disease Records',
    'vineyard.pest_records_description': 'View all recorded pests and treatments',
    'vineyard.no_pest_records': 'No pest records yet',
    'vineyard.soil': 'Soil Management',
    'vineyard.soil_description': 'Track soil amendments and nutrient management',
    'vineyard.add_amendment': 'Add Amendment',
    'vineyard.amendments': 'Amendments',
    'vineyard.total_amount': 'Total Amount',
    'vineyard.amendment_cost': 'Cost',
    'vineyard.nitrogen': 'Nitrogen Added',
    'vineyard.amendments_log': 'Soil Amendments',
    'vineyard.amendments_log_description': 'View all soil amendments and nutrient applications',
    'vineyard.no_amendments': 'No soil amendments recorded yet',
    'vineyard.equipment': 'Equipment Management',
    'vineyard.equipment_description': 'Track vineyard equipment, maintenance schedules, and storage',
    'vineyard.add_equipment': 'Add Equipment',
    'vineyard.total_equipment': 'Total Equipment',
    'vineyard.equipment_list': 'Equipment',
    'vineyard.equipment_list_description': 'All vineyard equipment and maintenance tracking',
    'vineyard.no_equipment': 'No equipment recorded yet',
    'vineyard.analytics': 'Vineyard Analytics',
    'vineyard.analytics_description': 'Comprehensive analytics for yield, quality, and vineyard performance',
    'vineyard.total_production': 'Total Production',
    'vineyard.production_metrics': 'Production Metrics',
    'vineyard.analytics_dashboard': 'Analytics Dashboard',
    'vineyard.analytics_description_long': 'View detailed analytics and performance metrics',
    
    // Advanced
    'nav.advanced': 'Advanced',
    'nav.advanced_desc': 'System tools',
    'nav.facility_requests': 'Requests',
    'nav.facility_requests_tip': 'Facility requests',
    'nav.ai_ops': 'AI Ops',
    'nav.ai_ops_tip': 'AI operations',
    'nav.admin': 'Admin',
    'nav.admin_tip': 'System administration',
  },
  es: {
    // Core Operations
    'nav.core_operations': 'Operaciones Principales',
    'nav.core_operations_desc': 'Gestionar reservas y negocios',
    'nav.dashboard': 'Panel',
    'nav.dashboard_tip': 'Ver panel principal',
    'nav.bookings': 'Reservas',
    'nav.bookings_tip': 'Gestionar reservas de propiedades',
    'nav.invoices': 'Facturas',
    'nav.invoices_tip': 'Gestionar facturas',
    'nav.tasks': 'Tareas',
    'nav.tasks_tip': 'Rastrear tareas y actividades',
    
    // Sovereignty
    'nav.sovereignty': 'Soberanía',
    'nav.sovereignty_desc': 'Desarrollo personal',
    'nav.sovereignty_dashboard': 'Soberanía',
    'nav.sovereignty_dashboard_tip': 'Panel de coaching personal',
    'nav.coach': 'Entrenador',
    'nav.coach_tip': 'Entrenador de desarrollo personal',
    'nav.layers': 'Capas',
    'nav.layers_tip': 'Capas de desarrollo',
    
    // Cattle Operations
    'nav.cattle_operations': 'Operaciones Ganaderas',
    'nav.cattle_operations_desc': 'Gestión de ganado',
    'nav.cattle_health': 'Salud',
    'nav.cattle_health_tip': 'Monitorear salud del ganado',
    'nav.expert_coach': 'Entrenador Experto',
    'nav.expert_coach_tip': 'Orientación experta con IA',
    'nav.business_plan': 'Plan de Negocio',
    'nav.business_plan_tip': 'Herramientas de planificación',
    'nav.pricing_costs': 'Costos',
    'nav.pricing_costs_tip': 'Análisis de precios y costos',
    
    // Property Management
    'nav.property_management': 'Gestión de Propiedades',
    'nav.property_management_desc': 'Activos e inventario',
    'nav.assets': 'Activos',
    'nav.assets_tip': 'Gestionar activos de propiedades',
    'nav.inventory': 'Inventario',
    'nav.inventory_tip': 'Rastrear inventario',
    'nav.all_assets': 'Todos los Activos',
    'nav.by_category': 'Por Categoría',
    'nav.by_cost_center': 'Por Centro de Costos',
    'nav.categories': 'Categorías',
    'nav.cost_centers': 'Centros de Costos',
    'nav.audit_logs': 'Registros de Auditoría',
    'nav.operations': 'Operaciones',
    'nav.operations_tip': 'Gestión de operaciones',
    'nav.fuel_consumption': 'Combustible',
    'nav.fuel_consumption_tip': 'Rastrear consumo de combustible',
    'nav.maintenance': 'Mantenimiento',
    'nav.maintenance_tip': 'Rastrear mantenimiento',
    'nav.gis_map': 'Mapa GIS',
    'nav.gis_map_tip': 'Información geográfica',
    'nav.kmz_viewer': 'Visor KMZ',
    'nav.kmz_viewer_tip': 'Ver archivos KMZ',
    
    // Off-Grid Energy
    'nav.off_grid_energy': 'Energía Fuera de Red',
    'nav.off_grid_energy_desc': 'Gestión de energía',
    'nav.management': 'Gestión',
    'nav.management_tip': 'Gestión de energía',
    'nav.energy_dashboard': 'Panel',
    'nav.energy_dashboard_tip': 'Analítica de energía',
    'nav.reports': 'Reportes',
    'nav.reports_tip': 'Reportes de energía',
    'nav.victron_setup': 'Configuración Victron',
    'nav.victron_setup_tip': 'Configuración del sistema Victron',
    'nav.integration_docs': 'Integración',
    'nav.integration_docs_tip': 'Documentación de integración',
    
    // Orchard Farm
    'nav.orchard_farm': 'Huerto',
    'nav.orchard_farm_desc': 'Producción de frutas',
    'nav.orchard_dashboard': 'Huerto',
    'nav.orchard_dashboard_tip': 'Resumen del huerto',
    'nav.orchard_crops': 'Cultivos',
    'nav.orchard_crops_tip': 'Gestionar cultivos del huerto',
    'nav.orchard_care': 'Cuidado',
    'nav.orchard_care_tip': 'Actividades de cuidado',
    'nav.orchard_harvest': 'Cosecha',
    'nav.orchard_harvest_tip': 'Rastreo de cosecha',
    'nav.orchard_pests': 'Plagas',
    'nav.orchard_pests_tip': 'Gestión de plagas',
    'nav.orchard_soil': 'Suelo',
    'nav.orchard_soil_tip': 'Gestión del suelo',
    'nav.orchard_equipment': 'Equipos',
    'nav.orchard_equipment_tip': 'Rastreo de equipos',
    'nav.orchard_analytics': 'Analítica',
    'nav.orchard_analytics_tip': 'Analítica de producción',
    
    // Vineyard
    'nav.vineyard': 'Viña',
    'nav.vineyard_desc': 'Producción de uvas y vino',
    'nav.vineyard_dashboard': 'Viña',
    'nav.vineyard_dashboard_tip': 'Resumen de la viña',
    'nav.vineyard_vines': 'Vides',
    'nav.vineyard_vines_tip': 'Gestionar vides del viñedo',
    'nav.vineyard_care': 'Cuidado',
    'nav.vineyard_care_tip': 'Actividades de cuidado de vides',
    'nav.vineyard_harvest': 'Vendimia',
    'nav.vineyard_harvest_tip': 'Rastreo de vendimia',
    'nav.vineyard_pests': 'Enfermedades',
    'nav.vineyard_pests_tip': 'Gestión de enfermedades',
    'nav.vineyard_soil': 'Suelo',
    'nav.vineyard_soil_tip': 'Enmiendas del suelo',
    'nav.vineyard_equipment': 'Equipos',
    'nav.vineyard_equipment_tip': 'Rastreo de equipos',
    'nav.vineyard_analytics': 'Analítica',
    'nav.vineyard_analytics_tip': 'Analítica de rendimiento y calidad',
    
    // Supply Chain
    'nav.supply_chain': 'Cadena de Suministro',
    'nav.supply_chain_desc': 'Adquisiciones',
    'nav.procurement': 'Adquisiciones',
    'nav.procurement_tip': 'Gestión de adquisiciones',
    'nav.suppliers': 'Proveedores',
    'nav.suppliers_tip': 'Gestión de proveedores',
    'nav.analytics': 'Analítica',
    'nav.analytics_tip': 'Analítica de adquisiciones',
    
    // People Operations
    'nav.people_operations': 'Operaciones de Personal',
    'nav.people_operations_desc': 'Gestión de equipo',
    'nav.employees': 'Empleados',
    'nav.employees_tip': 'Gestionar empleados',
    'nav.volunteers': 'Voluntarios',
    'nav.volunteers_tip': 'Gestión de voluntarios',
    'nav.activities': 'Actividades',
    'nav.activities_tip': 'Calendario de actividades',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Servicios de concierge',
    'nav.guest_requests': 'Solicitudes de Huéspedes',
    'nav.guest_requests_tip': 'Atender solicitudes de huéspedes',
    'nav.kitchen': 'Cocina',
    'nav.kitchen_tip': 'Gestión de cocina',
    'nav.checklists': 'Listas de Verificación',
    'nav.checklists_tip': 'Listas de verificación de tareas',
    
    // Vineyard Pages
    'vineyard.loading': 'Cargando...',
    'vineyard.title': 'Gestión del Viñedo',
    'vineyard.description': 'Gestiona tus parcelas de viñedo, vides y registros de cosecha',
    'vineyard.care_logs': 'Registros de Cuidado',
    'vineyard.add_plot': 'Añadir Parcela',
    'vineyard.total_plots': 'Parcelas Totales',
    'vineyard.total_area': 'Área Total',
    'vineyard.active_plots': 'Activas',
    'vineyard.avg_density': 'Densidad Promedio',
    'vineyard.plots': 'Parcelas del Viñedo',
    'vineyard.plots_description': 'Ver y gestionar todas las secciones del viñedo',
    'vineyard.no_plots': 'Sin parcelas de viñedo aún',
    'vineyard.vines': 'Gestión de Vides',
    'vineyard.vines_description': 'Rastrear y gestionar vides individuales y su salud',
    'vineyard.add_vine': 'Añadir Vid',
    'vineyard.total_vines': 'Vides Totales',
    'vineyard.search': 'Buscar vides...',
    'vineyard.care': 'Cuidado del Viñedo',
    'vineyard.care_description': 'Rastrear actividades de poda, fertilización e irrigación',
    'vineyard.log_activity': 'Registrar Actividad',
    'vineyard.total_activities': 'Actividades',
    'vineyard.total_cost': 'Costo Total',
    'vineyard.labor_hours': 'Horas de Trabajo',
    'vineyard.fertilizer': 'Fertilizante',
    'vineyard.care_activities': 'Actividades de Cuidado',
    'vineyard.care_activities_description': 'Todos los registros de poda, fertilización y mantenimiento',
    'vineyard.no_care_logs': 'Sin actividades de cuidado registradas aún',
    'vineyard.harvest': 'Gestión de Vendimia',
    'vineyard.harvest_description': 'Registra y rastrea la cosecha de uva con métricas de calidad',
    'vineyard.record_harvest': 'Registrar Vendimia',
    'vineyard.total_yield': 'Rendimiento Total',
    'vineyard.harvests_count': 'Registros de Vendimia',
    'vineyard.avg_brix': 'Brix Promedio',
    'vineyard.avg_quality': 'Calidad Promedio',
    'vineyard.harvest_records': 'Registros de Vendimia',
    'vineyard.harvest_records_description': 'Ver todas las vendimias registradas con análisis de calidad',
    'vineyard.no_harvests': 'Sin registros de vendimia aún',
    'vineyard.pests': 'Gestión de Plagas y Enfermedades',
    'vineyard.pests_description': 'Rastrear ocurrencias de plagas y enfermedades y tratamientos',
    'vineyard.log_pest': 'Registrar Problema',
    'vineyard.total_incidents': 'Incidentes',
    'vineyard.active_issues': 'Problemas Activos',
    'vineyard.treatment_cost': 'Costo de Tratamiento',
    'vineyard.critical': 'Crítico',
    'vineyard.pest_records': 'Registros de Plagas y Enfermedades',
    'vineyard.pest_records_description': 'Ver todos los registros de plagas y tratamientos',
    'vineyard.no_pest_records': 'Sin registros de plagas aún',
    'vineyard.soil': 'Gestión del Suelo',
    'vineyard.soil_description': 'Rastrear enmiendas del suelo y gestión de nutrientes',
    'vineyard.add_amendment': 'Añadir Enmienda',
    'vineyard.amendments': 'Enmiendas',
    'vineyard.total_amount': 'Cantidad Total',
    'vineyard.amendment_cost': 'Costo',
    'vineyard.nitrogen': 'Nitrógeno Añadido',
    'vineyard.amendments_log': 'Enmiendas del Suelo',
    'vineyard.amendments_log_description': 'Ver todas las enmiendas del suelo y aplicaciones de nutrientes',
    'vineyard.no_amendments': 'Sin enmiendas del suelo registradas aún',
    'vineyard.equipment': 'Gestión de Equipos',
    'vineyard.equipment_description': 'Rastrear equipos del viñedo, horarios de mantenimiento y almacenamiento',
    'vineyard.add_equipment': 'Añadir Equipo',
    'vineyard.total_equipment': 'Equipos Totales',
    'vineyard.equipment_list': 'Equipos',
    'vineyard.equipment_list_description': 'Todos los equipos del viñedo y rastreo de mantenimiento',
    'vineyard.no_equipment': 'Sin equipos registrados aún',
    'vineyard.analytics': 'Analítica del Viñedo',
    'vineyard.analytics_description': 'Analítica completa para rendimiento, calidad y desempeño del viñedo',
    'vineyard.total_production': 'Producción Total',
    'vineyard.production_metrics': 'Métricas de Producción',
    'vineyard.analytics_dashboard': 'Panel de Analítica',
    'vineyard.analytics_description_long': 'Ver analítica detallada y métricas de desempeño',
    
    // Advanced
    'nav.advanced': 'Avanzado',
    'nav.advanced_desc': 'Herramientas del sistema',
    'nav.facility_requests': 'Solicitudes',
    'nav.facility_requests_tip': 'Solicitudes de instalaciones',
    'nav.ai_ops': 'Operaciones de IA',
    'nav.ai_ops_tip': 'Operaciones de IA',
    'nav.admin': 'Administrador',
    'nav.admin_tip': 'Administración del sistema',
  },
}
