'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    'common.language': 'Language',
    'common.english': 'English',
    'common.spanish': 'Español',
    'nav.core_operations': 'Core Operations',
    'nav.core_operations_desc': 'Manage your property bookings and reservations',
    'nav.dashboard': 'Dashboard',
    'nav.dashboard_tip': 'Overview of your property',
    'nav.bookings': 'Bookings',
    'nav.bookings_tip': 'Manage reservations and availability',
    'nav.invoices': 'Invoices',
    'nav.invoices_tip': 'Manage invoices and payments',
    'nav.tasks': 'Tasks',
    'nav.tasks_tip': 'Daily management tasks',
    'nav.sovereignty': 'Sovereignty',
    'nav.sovereignty_desc': 'Track facility independence and self-sufficiency',
    'nav.sovereignty_dashboard': 'Dashboard',
    'nav.sovereignty_dashboard_tip': 'Track facility autonomy and independence',
    'nav.coach': 'Coach',
    'nav.coach_tip': 'AI advisor for achieving independence',
    'nav.layers': 'Layers',
    'nav.layers_tip': 'View 5-layer sovereignty pyramid',
    'dashboard.title': 'Blackswan Facility Core System',
    'dashboard.description': 'Professional facility management and booking system for your luxury vacation rental. Manage reservations, track availability, and optimize occupancy rates.',
    'dashboard.total_rooms': 'Total Rooms',
    'dashboard.total_rooms_desc': 'Registered properties',
    'dashboard.total_beds': 'Total Beds',
    'dashboard.total_beds_desc': 'Available inventory',
    'dashboard.occupancy_rate': 'Occupancy Rate',
    'dashboard.occupancy_rate_desc': 'Current utilization',
    'dashboard.active_reservations': 'Active Reservations',
    'dashboard.active_reservations_desc': 'Current bookings',
    'dashboard.quick_actions': 'Quick Actions',
    'facilities.title': 'Property Locations',
    'facilities.description': 'Manage all rental property locations',
    'facilities.add_location': 'Add Location',
    'facilities.locations': 'Locations',
    'facilities.no_locations': 'No locations found',
    'guests.title': 'Guests Management',
    'guests.description': 'Manage guest profiles and information',
    'guests.add_guest': 'Add Guest',
    'guests.search': 'Search Guests',
    'guests.search_placeholder': 'Search by name, email, or phone...',
    'guests.name': 'Name',
    'guests.email': 'Email',
    'guests.phone': 'Phone',
    'guests.company': 'Company',
    'guests.vip_status': 'VIP Status',
    'guests.bookings': 'Bookings',
    'guests.delete_confirmation': 'Are you sure you want to delete this guest?',
    'guests.loading': 'Loading guests...',
    'guests.no_guests': 'No guests found',
    'rooms.title': 'Room & Bed Management',
    'rooms.description': 'Manage rental units and bed inventory',
    'rooms.add_room': 'Add Room',
    'rooms.add_bed': 'Add Bed',
    'rooms.room_number': 'Room Number',
    'rooms.room_type': 'Room Type',
    'rooms.capacity': 'Capacity',
    'rooms.rate_per_night': 'Rate per Night',
    'rooms.beds': 'Beds',
    'rooms.delete_confirmation': 'Are you sure you want to delete this room?',
    'rooms.loading': 'Loading rooms...',
    'rooms.no_rooms': 'No rooms found',
    'rooms.up_to_guests': 'Up to {count} guests',
    'rooms.available': 'Available',
    'rooms.occupied': 'Occupied',
    'reports.title': 'Reports',
    'reports.description': 'View booking analytics and reports',
    'reports.occupancy': 'Occupancy Report',
    'reports.revenue': 'Revenue Report',
    'reports.bookings': 'Bookings Report',
    'reports.guests': 'Guests Report',
    'reports.current_month': 'Current Month',
    'reports.last_month': 'Last Month',
    'reports.last_3_months': 'Last 3 Months',
    'reports.last_6_months': 'Last 6 Months',
    'reports.all_locations': 'All Locations',
    'reports.export': 'Export',
    'reports.total_revenue': 'Total Revenue',
    'reports.total_bookings': 'Total Bookings',
    'reports.occupancy_rate': 'Occupancy Rate',
    'reports.average_rate': 'Average Rate',
    'reports.total_guests': 'Total Guests',
    'reports.repeat_guests': 'Repeat Guests',
    'reports.vip_guests': 'VIP Guests',
    'reports.new_guests': 'New Guests',
    'reports.location_performance': 'Location Performance',
    'reports.top_performing_rooms': 'Top Performing Rooms',
    'reports.payment_methods': 'Payment Methods',
    'reports.room': 'Room',
    'reports.location': 'Location',
    'reports.bookings_count': 'Bookings',
    'reports.from_previous_period': 'from previous period',
    'reports.room_utilization': 'Room utilization',
    'reports.per_booking': 'Per booking',
    'reports.registered_guests': 'Registered guests',
    'reports.returning_visitors': 'Returning visitors',
    'reports.premium_members': 'Premium members',
    'reports.first_time_bookings': 'First time bookings',
    'reports.loading': 'Loading reports...',
    'reports.comprehensive_revenue': 'Comprehensive revenue, occupancy, and performance insights',
    'sovereignty.title': 'Sovereignty Dashboard',
    'sovereignty.description': 'Track your facility independence and self-sufficiency across all domains',
    'sovereignty.self_sufficiency': 'Self-Sufficiency',
    'sovereignty.energy': 'Energy',
    'sovereignty.food': 'Food',
    'sovereignty.water': 'Water',
    'sovereignty.people': 'People',
    'sovereignty.software': 'Software',
    'sovereignty.assets': 'Assets',
    'sovereignty.current_value': 'Current Value',
    'sovereignty.target_value': 'Target Value',
    'sovereignty.trending': 'Trending',
    'sovereignty.last_updated': 'Last Updated',
    'sovereignty.notes': 'Notes',
    'sovereignty.on_track': 'On Track',
    'sovereignty.at_risk': 'At Risk',
    'sovereignty.dependencies': 'Dependencies',
    'sovereignty.dependency_name': 'Dependency',
    'sovereignty.status': 'Status',
    'sovereignty.risk_level': 'Risk Level',
    'sovereignty.criticality': 'Criticality',
    'sovereignty.critical': 'Critical',
    'sovereignty.high': 'High',
    'sovereignty.medium': 'Medium',
    'sovereignty.low': 'Low',
    'sovereignty.timeline': 'Timeline & Milestones',
    'sovereignty.event_type': 'Event Type',
    'sovereignty.before': 'Before',
    'sovereignty.after': 'After',
    'sovereignty.impact_area': 'Impact Area',
    'sovereignty.coach_title': 'Sovereignty Coach',
    'sovereignty.coach_description': 'AI-powered advisor for facility independence',
    'sovereignty.coach_subtitle': 'Get personalized recommendations on energy, food, water, people, software, and asset sovereignty.',
    'sovereignty.coach_header': 'AI Sovereignty Coach',
    'sovereignty.coach_guidance': 'Personalized guidance for achieving facility independence',
    'sovereignty.coach_prompt': 'Ask me anything about improving your facility\'s sovereignty across energy, food, water, people, software, and assets. I\'ll analyze your current metrics and provide actionable recommendations.',
    'sovereignty.coach_placeholder': 'Ask about improving facility independence...',
    'sovereignty.coach_send': 'Send',
    'sovereignty.quick_questions': 'Quick Questions',
    'sovereignty.layers_title': 'Sovereignty Layers Architecture',
    'sovereignty.layers_description': 'A 5-layer pyramid of facility independence. Build from foundation up - each layer strengthens the ones above.',
    'sovereignty.layer_foundation': 'Foundation',
    'sovereignty.layer_infrastructure': 'Infrastructure',
    'sovereignty.layer_services': 'Services',
    'sovereignty.layer_operations': 'Operations',
    'sovereignty.layer_excellence': 'Excellence',
    'sovereignty.layer_objective': 'Objectives',
    'sovereignty.completion': 'Completion',
    'sovereignty.priority_critical': 'Critical',
    'sovereignty.priority_high': 'High',
    'sovereignty.priority_medium': 'Medium',
    'sovereignty.priority_low': 'Low',
    'sovereignty.status_completed': 'Completed',
    'sovereignty.status_in_progress': 'In Progress',
    'sovereignty.status_planned': 'Planned',
    'sovereignty.modules': 'Modules',
    'sovereignty.quick_wins': 'Quick Wins',
    'sovereignty.action_items': 'Action Items',
    'sovereignty.target_milestones': 'Target Milestones',
    'sovereignty.no_timeline_events': 'No timeline events yet. Start documenting your sovereignty journey.',
    'sovereignty.improve_sovereignty': 'Improve Sovereignty',
    'sovereignty.energy_independence': 'Energy Independence',
    'sovereignty.build_team_skills': 'Build Team Skills',
    'sovereignty.manage_assets': 'Manage Assets',
    'sovereignty.view_reports': 'View Reports',
    'sovereignty.achievement_roadmap': 'Achievement Roadmap',
    'sovereignty.guidance_higher_levels': 'Guidance for achieving higher sovereignty levels',
    'sovereignty.step1_title': 'Step 1: Identify Key Metrics',
    'sovereignty.step1_desc': 'Understand the metrics that define sovereignty in each category.',
    'sovereignty.step2_title': 'Step 2: Set Target Values',
    'sovereignty.step2_desc': 'Establish realistic target values for each metric to strive towards.',
    'sovereignty.step3_title': 'Step 3: Monitor Progress',
    'sovereignty.step3_desc': 'Regularly track and update your progress towards these targets.',
    'sovereignty.step4_title': 'Step 4: Address Dependencies',
    'sovereignty.step4_desc': 'Identify and mitigate high-risk dependencies to enhance sovereignty.',
    'sovereignty.step5_title': 'Step 5: Optimize Resources',
    'sovereignty.step5_desc': 'Allocate resources efficiently to improve self-sufficiency in weaker areas.',
    'sovereignty.step6_title': 'Step 6: Continuous Improvement',
    'sovereignty.step6_desc': 'Continuously refine strategies and adapt to new challenges for sustained sovereignty.',
    'sovereignty.categories_tracked': 'Categories Tracked',
    'sovereignty.by_category': 'by Category',
    'sovereignty.compare_systems': 'Compare sovereignty levels across all facility systems',
    'sovereignty.metrics': 'Sovereignty Metrics',
    'sovereignty.all_categories': 'All Categories',
    'sovereignty.critical_dependencies': 'Critical Dependencies Requiring Action',
    'sovereignty.high_risk_external': 'High-risk external dependencies affecting sovereignty',
    'sovereignty.timeline_description': 'Historical improvements and impact on independence',
    'sovereignty.related_modules': 'Related Modules',
    'sovereignty.key_objectives': 'Key Objectives',
    'sovereignty.target': 'Target',
    'sovereignty.no_objectives': 'No objectives defined yet',
    'sovereignty.overall_progress': 'Overall Sovereignty Progress',
    'sovereignty.layer': 'Layer',
    'sovereignty.dependencies_to_eliminate': 'Dependencies to Eliminate',
  },
  es: {
    'common.language': 'Idioma',
    'common.english': 'English',
    'common.spanish': 'Español',
    'nav.core_operations': 'Operaciones Principales',
    'nav.core_operations_desc': 'Gestiona tus reservas y reservaciones de propiedades',
    'nav.dashboard': 'Panel de Control',
    'nav.dashboard_tip': 'Descripción general de tu propiedad',
    'nav.bookings': 'Reservas',
    'nav.bookings_tip': 'Gestiona reservaciones y disponibilidad',
    'nav.invoices': 'Facturas',
    'nav.invoices_tip': 'Gestiona facturas y pagos',
    'nav.tasks': 'Tareas',
    'nav.tasks_tip': 'Tareas de gestión diaria',
    'nav.sovereignty': 'Soberanía',
    'nav.sovereignty_desc': 'Rastrear la independencia de la instalación y autosuficiencia',
    'nav.sovereignty_dashboard': 'Panel de Control',
    'nav.sovereignty_dashboard_tip': 'Rastrear la autonomía e independencia de la instalación',
    'nav.coach': 'Entrenador',
    'nav.coach_tip': 'Asesor de IA para lograr la independencia',
    'nav.layers': 'Capas',
    'nav.layers_tip': 'Ver pirámide de soberanía de 5 capas',
    'dashboard.title': 'Sistema Central de Instalaciones Blackswan',
    'dashboard.description': 'Sistema profesional de gestión de instalaciones y reservas para tu alquiler vacacional de lujo. Gestiona reservas, rastrear disponibilidad y optimizar tasas de ocupación.',
    'dashboard.total_rooms': 'Habitaciones Totales',
    'dashboard.total_rooms_desc': 'Propiedades registradas',
    'dashboard.total_beds': 'Camas Totales',
    'dashboard.total_beds_desc': 'Inventario disponible',
    'dashboard.occupancy_rate': 'Tasa de Ocupación',
    'dashboard.occupancy_rate_desc': 'Utilización actual',
    'dashboard.active_reservations': 'Reservas Activas',
    'dashboard.active_reservations_desc': 'Reservas actuales',
    'dashboard.quick_actions': 'Acciones Rápidas',
    'facilities.title': 'Ubicaciones de Propiedades',
    'facilities.description': 'Gestiona todas las ubicaciones de propiedades de alquiler',
    'facilities.add_location': 'Agregar Ubicación',
    'facilities.locations': 'Ubicaciones',
    'facilities.no_locations': 'No se encontraron ubicaciones',
    'guests.title': 'Gestión de Huéspedes',
    'guests.description': 'Gestiona perfiles e información de huéspedes',
    'guests.add_guest': 'Agregar Huésped',
    'guests.search': 'Buscar Huéspedes',
    'guests.search_placeholder': 'Buscar por nombre, email o teléfono...',
    'guests.name': 'Nombre',
    'guests.email': 'Email',
    'guests.phone': 'Teléfono',
    'guests.company': 'Empresa',
    'guests.vip_status': 'Estado VIP',
    'guests.bookings': 'Reservas',
    'guests.delete_confirmation': '¿Estás seguro de que quieres eliminar este huésped?',
    'guests.loading': 'Cargando huéspedes...',
    'guests.no_guests': 'No hay huéspedes encontrados',
    'rooms.title': 'Gestión de Habitaciones y Camas',
    'rooms.description': 'Gestiona unidades de alquiler e inventario de camas',
    'rooms.add_room': 'Agregar Habitación',
    'rooms.add_bed': 'Agregar Cama',
    'rooms.room_number': 'Número de Habitación',
    'rooms.room_type': 'Tipo de Habitación',
    'rooms.capacity': 'Capacidad',
    'rooms.rate_per_night': 'Tarifa por Noche',
    'rooms.beds': 'Camas',
    'rooms.delete_confirmation': '¿Estás seguro de que quieres eliminar esta habitación?',
    'rooms.loading': 'Cargando habitaciones...',
    'rooms.no_rooms': 'No hay habitaciones encontradas',
    'rooms.up_to_guests': 'Hasta {count} huéspedes',
    'rooms.available': 'Disponible',
    'rooms.occupied': 'Ocupado',
    'reports.title': 'Reportes',
    'reports.description': 'Ver análisis y reportes de reservas',
    'reports.occupancy': 'Reporte de Ocupación',
    'reports.revenue': 'Reporte de Ingresos',
    'reports.bookings': 'Reporte de Reservas',
    'reports.guests': 'Reporte de Huéspedes',
    'reports.current_month': 'Mes Actual',
    'reports.last_month': 'Mes Pasado',
    'reports.last_3_months': 'Últimos 3 Meses',
    'reports.last_6_months': 'Últimos 6 Meses',
    'reports.all_locations': 'Todas las Ubicaciones',
    'reports.export': 'Exportar',
    'reports.total_revenue': 'Ingresos Totales',
    'reports.total_bookings': 'Reservas Totales',
    'reports.occupancy_rate': 'Tasa de Ocupación',
    'reports.average_rate': 'Tarifa Promedio',
    'reports.total_guests': 'Huéspedes Totales',
    'reports.repeat_guests': 'Huéspedes Frecuentes',
    'reports.vip_guests': 'Huéspedes VIP',
    'reports.new_guests': 'Nuevos Huéspedes',
    'reports.location_performance': 'Rendimiento de Ubicación',
    'reports.top_performing_rooms': 'Habitaciones con Mejor Desempeño',
    'reports.payment_methods': 'Métodos de Pago',
    'reports.room': 'Habitación',
    'reports.location': 'Ubicación',
    'reports.bookings_count': 'Reservas',
    'reports.from_previous_period': 'del período anterior',
    'reports.room_utilization': 'Utilización de habitaciones',
    'reports.per_booking': 'Por reserva',
    'reports.registered_guests': 'Huéspedes registrados',
    'reports.returning_visitors': 'Visitantes que regresan',
    'reports.premium_members': 'Miembros premium',
    'reports.first_time_bookings': 'Primeras reservas',
    'reports.loading': 'Cargando reportes...',
    'reports.comprehensive_revenue': 'Información completa de ingresos, ocupación y desempeño',
    'sovereignty.title': 'Panel de Soberanía',
    'sovereignty.description': 'Rastrear la independencia de tu instalación y autosuficiencia en todos los dominios',
    'sovereignty.self_sufficiency': 'Autosuficiencia',
    'sovereignty.energy': 'Energía',
    'sovereignty.food': 'Alimentos',
    'sovereignty.water': 'Agua',
    'sovereignty.people': 'Personas',
    'sovereignty.software': 'Software',
    'sovereignty.assets': 'Activos',
    'sovereignty.current_value': 'Valor Actual',
    'sovereignty.target_value': 'Valor Objetivo',
    'sovereignty.trending': 'Tendencia',
    'sovereignty.last_updated': 'Última Actualización',
    'sovereignty.notes': 'Notas',
    'sovereignty.on_track': 'En Camino',
    'sovereignty.at_risk': 'En Riesgo',
    'sovereignty.dependencies': 'Dependencias',
    'sovereignty.dependency_name': 'Dependencia',
    'sovereignty.status': 'Estado',
    'sovereignty.risk_level': 'Nivel de Riesgo',
    'sovereignty.criticality': 'Criticidad',
    'sovereignty.critical': 'Crítico',
    'sovereignty.high': 'Alto',
    'sovereignty.medium': 'Medio',
    'sovereignty.low': 'Bajo',
    'sovereignty.timeline': 'Línea de Tiempo e Hitos',
    'sovereignty.event_type': 'Tipo de Evento',
    'sovereignty.before': 'Antes',
    'sovereignty.after': 'Después',
    'sovereignty.impact_area': 'Área de Impacto',
    'sovereignty.coach_title': 'Entrenador de Soberanía',
    'sovereignty.coach_description': 'Asesor impulsado por IA para la independencia de la instalación',
    'sovereignty.coach_subtitle': 'Obtén recomendaciones personalizadas sobre soberanía de energía, alimentos, agua, personas, software y activos.',
    'sovereignty.coach_header': 'Entrenador de Soberanía de IA',
    'sovereignty.coach_guidance': 'Orientación personalizada para lograr la independencia de la instalación',
    'sovereignty.coach_prompt': 'Pregúntame cualquier cosa sobre cómo mejorar la soberanía de tu instalación en energía, alimentos, agua, personas, software y activos. Analizaré tus métricas actuales y proporcionaré recomendaciones accionables.',
    'sovereignty.coach_placeholder': 'Pregunta sobre cómo mejorar la independencia de la instalación...',
    'sovereignty.coach_send': 'Enviar',
    'sovereignty.quick_questions': 'Preguntas Rápidas',
    'sovereignty.layers_title': 'Arquitectura de Capas de Soberanía',
    'sovereignty.layers_description': 'Una pirámide de 5 capas de independencia de la instalación. Construye desde la base hacia arriba - cada capa fortalece las de arriba.',
    'sovereignty.layer_foundation': 'Fundación',
    'sovereignty.layer_infrastructure': 'Infraestructura',
    'sovereignty.layer_services': 'Servicios',
    'sovereignty.layer_operations': 'Operaciones',
    'sovereignty.layer_excellence': 'Excelencia',
    'sovereignty.layer_objective': 'Objetivos',
    'sovereignty.completion': 'Finalización',
    'sovereignty.priority_critical': 'Crítico',
    'sovereignty.priority_high': 'Alto',
    'sovereignty.priority_medium': 'Medio',
    'sovereignty.priority_low': 'Bajo',
    'sovereignty.status_completed': 'Completado',
    'sovereignty.status_in_progress': 'En Progreso',
    'sovereignty.status_planned': 'Planeado',
    'sovereignty.modules': 'Módulos',
    'sovereignty.quick_wins': 'Ganancias Rápidas',
    'sovereignty.action_items': 'Elementos de Acción',
    'sovereignty.target_milestones': 'Hitos Objetivo',
    'sovereignty.no_timeline_events': 'Sin eventos de cronología aún. Comienza a documentar tu viaje de soberanía.',
    'sovereignty.improve_sovereignty': 'Mejorar Soberanía',
    'sovereignty.energy_independence': 'Independencia Energética',
    'sovereignty.build_team_skills': 'Construir Habilidades del Equipo',
    'sovereignty.manage_assets': 'Gestionar Activos',
    'sovereignty.view_reports': 'Ver Reportes',
    'sovereignty.achievement_roadmap': 'Mapa de Ruta de Logros',
    'sovereignty.guidance_higher_levels': 'Orientación para lograr niveles más altos de soberanía',
    'sovereignty.step1_title': 'Paso 1: Identificar Métricas Clave',
    'sovereignty.step1_desc': 'Comprende las métricas que definen la soberanía en cada categoría.',
    'sovereignty.step2_title': 'Paso 2: Establecer Valores Objetivo',
    'sovereignty.step2_desc': 'Establece valores objetivo realistas para cada métrica a los que aspirar.',
    'sovereignty.step3_title': 'Paso 3: Monitorear Progreso',
    'sovereignty.step3_desc': 'Rastrear y actualizar regularmente tu progreso hacia estos objetivos.',
    'sovereignty.step4_title': 'Paso 4: Abordar Dependencias',
    'sovereignty.step4_desc': 'Identifica y mitiga dependencias de alto riesgo para mejorar la soberanía.',
    'sovereignty.step5_title': 'Paso 5: Optimizar Recursos',
    'sovereignty.step5_desc': 'Asigna recursos de manera eficiente para mejorar la autosuficiencia en áreas débiles.',
    'sovereignty.step6_title': 'Paso 6: Mejora Continua',
    'sovereignty.step6_desc': 'Refina continuamente las estrategias y adapta a nuevos desafíos para la soberanía sostenible.',
    'sovereignty.categories_tracked': 'Categorías Rastreadas',
    'sovereignty.by_category': 'por Categoría',
    'sovereignty.compare_systems': 'Compara niveles de soberanía en todos los sistemas de la instalación',
    'sovereignty.metrics': 'Métricas de Soberanía',
    'sovereignty.all_categories': 'Todas las Categorías',
    'sovereignty.critical_dependencies': 'Dependencias Críticas Que Requieren Acción',
    'sovereignty.high_risk_external': 'Dependencias externas de alto riesgo que afectan la soberanía',
    'sovereignty.timeline_description': 'Mejoras históricas e impacto en la independencia',
    'sovereignty.related_modules': 'Módulos Relacionados',
    'sovereignty.key_objectives': 'Objetivos Clave',
    'sovereignty.target': 'Objetivo',
    'sovereignty.no_objectives': 'No hay objetivos definidos aún',
    'sovereignty.overall_progress': 'Progreso General de Soberanía',
    'sovereignty.layer': 'Capa',
    'sovereignty.dependencies_to_eliminate': 'Dependencias a Eliminar',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')
  const [isMounted, setIsMounted] = useState(false)

  useEffect(() => {
    setIsMounted(true)
    const saved = localStorage.getItem('language') as Language | null
    if (saved) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
