'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    'common.language': 'Language',
    'common.english': 'English',
    'common.spanish': 'Español',
    'nav.core_operations': 'Core Operations',
    'nav.core_operations_desc': 'Manage your property bookings and reservations',
    'nav.dashboard': 'Dashboard',
    'nav.dashboard_tip': 'Overview of your property',
    'nav.bookings': 'Bookings',
    'nav.bookings_tip': 'Manage reservations and availability',
    'nav.invoices': 'Invoices',
    'nav.invoices_tip': 'Manage invoices and payments',
    'nav.tasks': 'Tasks',
    'nav.tasks_tip': 'Daily management tasks',
    'nav.sovereignty': 'Sovereignty',
    'nav.sovereignty_desc': 'Track facility independence and self-sufficiency',
    'nav.sovereignty_dashboard': 'Dashboard',
    'nav.sovereignty_dashboard_tip': 'Track facility autonomy and independence',
    'nav.coach': 'Coach',
    'nav.coach_tip': 'AI advisor for achieving independence',
    'nav.layers': 'Layers',
    'nav.layers_tip': 'View 5-layer sovereignty pyramid',
    'nav.cattle_operations': 'Cattle Operations',
    'nav.cattle_operations_desc': 'Livestock management and breeding operations',
    'nav.cattle_health': 'Health Monitoring',
    'nav.cattle_health_tip': 'Biometric analysis, alerts, and veterinary tracking',
    'nav.expert_coach': 'Expert Coach',
    'nav.expert_coach_tip': 'AI advisor for cattle business',
    'nav.business_plan': 'Business Plan',
    'nav.business_plan_tip': 'Financial projections',
    'nav.pricing_costs': 'Pricing & Costs',
    'nav.pricing_costs_tip': 'Cost analysis and pricing',
    'nav.property_management': 'Property Management',
    'nav.property_management_desc': 'Configure and maintain your facility',
    'nav.assets': 'Assets',
    'nav.assets_tip': 'Inventory and equipment',
    'nav.inventory': 'Inventory',
    'nav.inventory_tip': 'Multimedia inventory tracking and QR codes',
    'nav.all_assets': 'All Assets',
    'nav.by_category': 'By Category',
    'nav.by_cost_center': 'By Cost Center',
    'nav.categories': 'Categories',
    'nav.cost_centers': 'Cost Centers',
    'nav.audit_logs': 'Audit Logs',
    'nav.operations': 'Operations',
    'nav.operations_tip': 'Monthly operations and vehicle trips with KMZ tracking',
    'nav.fuel_consumption': 'Fuel Consumption',
    'nav.fuel_consumption_tip': 'Track field fuel consumption and costs',
    'nav.maintenance': 'Maintenance',
    'nav.maintenance_tip': 'Schedule and track repairs',
    'nav.gis_map': 'GIS Map',
    'nav.gis_map_tip': 'Property location and layout',
    'nav.kmz_viewer': 'KMZ Viewer',
    'nav.kmz_viewer_tip': 'Upload and view KMZ overlays',
    'nav.off_grid_energy': 'Off Grid Energy',
    'nav.off_grid_energy_desc': 'Solar panels, batteries, and Victron monitoring',
    'nav.management': 'Management',
    'nav.management_tip': 'Solar panels and electricity consumption',
    'nav.energy_dashboard': 'Dashboard',
    'nav.energy_dashboard_tip': 'Real-time energy monitoring',
    'nav.reports': 'Reports',
    'nav.reports_tip': 'Historical reports and analytics',
    'nav.victron_setup': 'Victron Setup',
    'nav.victron_setup_tip': 'Victron integration guide',
    'nav.integration_docs': 'Integration Docs',
    'nav.integration_docs_tip': 'MQTT, Node-RED, and VRM API documentation',
    'nav.supply_chain': 'Supply Chain',
    'nav.supply_chain_desc': 'Procurement, suppliers, and acquisitions',
    'nav.procurement': 'Procurement',
    'nav.procurement_tip': 'Purchase orders and acquisitions',
    'nav.suppliers': 'Suppliers',
    'nav.suppliers_tip': 'Manage supplier contacts and relationships',
    'nav.analytics': 'Analytics',
    'nav.people_operations': 'People & Operations',
    'nav.people_operations_desc': 'Staff management and guest services',
    'nav.employees': 'Employees',
    'nav.employees_tip': 'Team management',
    'nav.volunteers': 'Volunteers',
    'nav.volunteers_tip': 'Volunteer coordination and tracking',
    'nav.activities': 'Activities Calendar',
    'nav.activities_tip': 'Plan and manage facility activities, events, and entertainment',
    'nav.concierge': 'Concierge',
    'nav.concierge_tip': 'Guest communication',
    'nav.guest_requests': 'Guest Requests',
    'nav.guest_requests_tip': 'Tablet interface for hospitality requests',
    'nav.kitchen': 'Kitchen',
    'nav.kitchen_tip': 'Kitchen and food preparation facilities',
    'nav.checklists': 'Checklists',
    'nav.checklists_tip': 'Operational checklists',
    'nav.advanced': 'Advanced',
    'nav.advanced_desc': 'Analytics and system settings',
    'nav.facility_requests': 'Facility Requests',
    'nav.facility_requests_tip': 'Track facility requests and service tickets',
    'nav.ai_ops': 'AI Operations',
    'nav.ai_ops_tip': 'AI-powered insights',
    'nav.admin': 'Admin',
    'nav.admin_tip': 'System configuration',
    'nav.need_help': 'Need Help?',
    'nav.press_cmd': 'Press ⌘K to search',
    'nav.version': 'BFCS v1.0',
    // Core Operations - Dashboard
    'dashboard.title': 'Blackswan Facility Core System',
    'dashboard.description': 'Professional facility management and booking system for your luxury vacation rental. Manage reservations, track availability, and optimize occupancy rates.',
    'dashboard.total_rooms': 'Total Rooms',
    'dashboard.total_rooms_desc': 'Registered properties',
    'dashboard.total_beds': 'Total Beds',
    'dashboard.total_beds_desc': 'Available inventory',
    'dashboard.occupancy_rate': 'Occupancy Rate',
    'dashboard.occupancy_rate_desc': 'Current utilization',
    'dashboard.active_reservations': 'Active Reservations',
    'dashboard.active_reservations_desc': 'Current bookings',
    'dashboard.todays_checkins': 'Today\'s Check-ins',
    'dashboard.todays_checkins_desc': 'Guests arriving today',
    'dashboard.todays_checkouts': 'Today\'s Check-outs',
    'dashboard.todays_checkouts_desc': 'Guests departing today',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.booking_calendar': 'Booking Calendar',
    'dashboard.booking_calendar_desc': 'View and manage all reservations',
    'dashboard.property_management': 'Property Management',
    'dashboard.property_management_desc': 'Configure rooms and amenities',
    'dashboard.maintenance': 'Maintenance',
    'dashboard.maintenance_desc': 'Schedule and track maintenance',
    'dashboard.analytics': 'Analytics',
    'dashboard.analytics_desc': 'View booking trends and insights',
    // Core Operations - Bookings
    'bookings.title': 'Bookings',
    'bookings.add_reservation': 'Add Reservation',
    'bookings.facilities': 'Facilities',
    'bookings.guests': 'Guests',
    'bookings.rooms': 'Rooms',
    'bookings.invoices': 'Invoices',
    'bookings.reports': 'Reports',
    'bookings.calendar': 'Calendar',
    // Core Operations - Tasks
    'tasks.title': 'Tasks',
    'tasks.add_task': 'Add Task',
    'tasks.low': 'Low',
    'tasks.medium': 'Medium',
    'tasks.high': 'High',
    'tasks.urgent': 'Urgent',
    'tasks.new': 'New',
    'tasks.in_progress': 'In Progress',
    'tasks.completed': 'Completed',
    'tasks.cancelled': 'Cancelled',
    // Bookings Management
    'bookings.management': 'Booking Management',
    'bookings.manage_reservations': 'Manage reservations across all properties',
    'bookings.single_property': 'Single Property',
    'bookings.all_properties': 'All Properties',
    'bookings.properties': 'Properties',
    'bookings.total_beds': 'Total Beds',
    'bookings.active_bookings': 'Active Bookings',
    'bookings.occupancy': 'Occupancy',
    'bookings.revenue': 'Revenue (Est.)',
    'bookings.new_reservation': 'New Reservation',
    'bookings.previous': 'Previous',
    'bookings.next': 'Next',
    'bookings.today': 'Today',
    'bookings.confirmed': 'Confirmed',
    'bookings.checked_in': 'Checked-in',
    'bookings.pending': 'Pending',
    'bookings.cancelled': 'Cancelled',
    'bookings.guest_name': 'Guest Name',
    'bookings.check_in': 'Check-in',
    'bookings.check_out': 'Check-out',
    'bookings.status': 'Status',
    'bookings.amount': 'Amount',
    'bookings.no_reservation': 'Click to create a new reservation',
    'bookings.loading': 'Loading bookings...',
    'bookings.no_properties': 'No properties found. Add locations first.',
    // Invoices
    'invoices.management': 'Invoices Management',
    'invoices.create_edit_manage': 'Create, edit, and manage all invoices',
    'invoices.new_invoice': 'New Invoice',
    'invoices.search_invoices': 'Search Invoices',
    'invoices.search_placeholder': 'Search by invoice number or customer name...',
    'invoices.all_invoices': 'All Invoices',
    'invoices.invoice_number': 'Invoice Number',
    'invoices.customer': 'Customer',
    'invoices.date': 'Date',
    'invoices.total': 'Total',
    'invoices.payment_status': 'Payment Status',
    'invoices.paid': 'Paid',
    'invoices.pending': 'Pending',
    'invoices.overdue': 'Overdue',
    'invoices.draft': 'Draft',
    'invoices.loading': 'Loading invoices...',
    'invoices.no_invoices': 'No invoices found',
    'invoices.delete_confirmation': 'Are you sure you want to delete this invoice?',
    // Facilities
    'facilities.title': 'Property Locations',
    'facilities.description': 'Manage all rental property locations',
    'facilities.add_location': 'Add Location',
    'facilities.locations': 'Locations',
    'facilities.no_locations': 'No locations found',
    'facilities.name': 'Name',
    'facilities.description_field': 'Description',
    'facilities.latitude': 'Latitude',
    'facilities.longitude': 'Longitude',
    'facilities.add': 'Add',
    'facilities.edit': 'Edit',
    'facilities.delete': 'Delete',
    'facilities.manage_rooms_beds': 'Manage Rooms & Beds',
    'facilities.deactivate': 'Deactivate',
    'facilities.activate': 'Activate',
    'facilities.active': 'Active',
    'facilities.search_placeholder': 'Search locations...',
    'facilities.add_new_location': 'Add New Location',
    'facilities.add_new_location_desc': 'Add a new rental property location to your facility',
    'facilities.location_name': 'Location Name',
    'facilities.location_name_placeholder': 'e.g., Bamboo House, Cesar Palace',
    'facilities.description_label': 'Description',
    'facilities.description_placeholder': 'Brief description of the property',
    'facilities.latitude_label': 'Latitude',
    'facilities.latitude_placeholder': '9.12345',
    'facilities.longitude_label': 'Longitude',
    'facilities.longitude_placeholder': '-83.12345',
    'facilities.cancel': 'Cancel',
    'facilities.add_location_btn': 'Add Location',
    'facilities.edit_location': 'Edit Location',
    'facilities.edit_location_desc': 'Update the location details',
    'facilities.save_changes': 'Save Changes',
    'common.cancel': 'Cancel',
    // Guests
    'guests.title': 'Guests',
    'guests.add_guest': 'Add Guest',
    'guests.search': 'Search Guests',
    'guests.search_placeholder': 'Search by name, email, or phone...',
    'guests.name': 'Name',
    'guests.email': 'Email',
    'guests.phone': 'Phone',
    'guests.company': 'Company',
    'guests.vip_status': 'VIP Status',
    'guests.bookings': 'Bookings',
    'guests.delete_confirmation': 'Are you sure you want to delete this guest?',
    'guests.loading': 'Loading guests...',
    'guests.no_guests': 'No guests found',
    // Rooms
    'rooms.title': 'Room & Bed Management',
    'rooms.description': 'Manage rental units and bed inventory',
    'rooms.add_room': 'Add Room',
    'rooms.add_bed': 'Add Bed',
    'rooms.room_number': 'Room Number',
    'rooms.room_type': 'Room Type',
    'rooms.capacity': 'Capacity',
    'rooms.rate_per_night': 'Rate per Night',
    'rooms.beds': 'Beds',
    'rooms.delete_confirmation': 'Are you sure you want to delete this room?',
    'rooms.loading': 'Loading rooms...',
    'rooms.no_rooms': 'No rooms found',
    'rooms.up_to_guests': 'Up to {count} guests',
    'rooms.available': 'Available',
    'rooms.occupied': 'Occupied',
    // Guests
    'guests.title': 'Guests Management',
    'guests.description': 'Manage guest profiles and information',
    'guests.add_guest': 'Add Guest',
    'guests.search': 'Search Guests',
    'guests.search_placeholder': 'Search by name, email, or phone...',
    'guests.name': 'Name',
    'guests.email': 'Email',
    'guests.phone': 'Phone',
    'guests.company': 'Company',
    'guests.vip_status': 'VIP Status',
    'guests.bookings': 'Bookings',
    'guests.delete_confirmation': 'Are you sure you want to delete this guest?',
    'guests.loading': 'Loading guests...',
    'guests.no_guests': 'No guests found',
    // Reports
    'reports.title': 'Reports',
    'reports.description': 'View booking analytics and reports',
    'reports.occupancy': 'Occupancy Report',
    'reports.revenue': 'Revenue Report',
    'reports.bookings': 'Bookings Report',
    'reports.guests': 'Guests Report',
    'reports.current_month': 'Current Month',
    'reports.last_month': 'Last Month',
    'reports.last_3_months': 'Last 3 Months',
    'reports.last_6_months': 'Last 6 Months',
    'reports.all_locations': 'All Locations',
    'reports.export': 'Export',
    'reports.total_revenue': 'Total Revenue',
    'reports.total_bookings': 'Total Bookings',
    'reports.occupancy_rate': 'Occupancy Rate',
    'reports.average_rate': 'Average Rate',
    'reports.total_guests': 'Total Guests',
    'reports.repeat_guests': 'Repeat Guests',
    'reports.vip_guests': 'VIP Guests',
    'reports.new_guests': 'New Guests',
    'reports.location_performance': 'Location Performance',
    'reports.top_performing_rooms': 'Top Performing Rooms',
    'reports.payment_methods': 'Payment Methods',
    'reports.room': 'Room',
    'reports.location': 'Location',
    'reports.bookings_count': 'Bookings',
    'reports.from_previous_period': 'from previous period',
    'reports.room_utilization': 'Room utilization',
    'reports.per_booking': 'Per booking',
    'reports.registered_guests': 'Registered guests',
    'reports.returning_visitors': 'Returning visitors',
    'reports.premium_members': 'Premium members',
    'reports.first_time_bookings': 'First time bookings',
    'reports.loading': 'Loading reports...',
    'reports.comprehensive_revenue': 'Comprehensive revenue, occupancy, and performance insights',
    // Sovereignty - Main Dashboard
    'sovereignty.title': 'Sovereignty Dashboard',
    'sovereignty.description': 'Track your facility independence and self-sufficiency across all domains',
    'sovereignty.self_sufficiency': 'Self-Sufficiency',
    'sovereignty.energy': 'Energy',
    'sovereignty.food': 'Food',
    'sovereignty.water': 'Water',
    'sovereignty.people': 'People',
    'sovereignty.software': 'Software',
    'sovereignty.assets': 'Assets',
    'sovereignty.current_value': 'Current Value',
    'sovereignty.target_value': 'Target Value',
    'sovereignty.trending': 'Trending',
    'sovereignty.last_updated': 'Last Updated',
    'sovereignty.notes': 'Notes',
    'sovereignty.on_track': 'On Track',
    'sovereignty.at_risk': 'At Risk',
    'sovereignty.dependencies': 'Dependencies',
    'sovereignty.dependency_name': 'Dependency',
    'sovereignty.status': 'Status',
    'sovereignty.risk_level': 'Risk Level',
    'sovereignty.criticality': 'Criticality',
    'sovereignty.critical': 'Critical',
    'sovereignty.high': 'High',
    'sovereignty.medium': 'Medium',
    'sovereignty.low': 'Low',
    'sovereignty.timeline': 'Timeline & Milestones',
    'sovereignty.event_type': 'Event Type',
    'sovereignty.before': 'Before',
    'sovereignty.after': 'After',
    'sovereignty.impact_area': 'Impact Area',
    // Sovereignty - Coach
    'sovereignty.coach_title': 'Sovereignty Coach',
    'sovereignty.coach_description': 'AI-powered advisor for facility independence',
    'sovereignty.coach_subtitle': 'Get personalized recommendations on energy, food, water, people, software, and asset sovereignty.',
    'sovereignty.coach_header': 'AI Sovereignty Coach',
    'sovereignty.coach_guidance': 'Personalized guidance for achieving facility independence',
    'sovereignty.coach_prompt': 'Ask me anything about improving your facility\'s sovereignty across energy, food, water, people, software, and assets. I\'ll analyze your current metrics and provide actionable recommendations.',
    'sovereignty.coach_placeholder': 'Ask about improving facility independence...',
    'sovereignty.coach_send': 'Send',
    'sovereignty.quick_questions': 'Quick Questions',
    // Sovereignty - Layers
    'sovereignty.layers_title': 'Sovereignty Layers',
    'sovereignty.layers_description': 'View the 5-layer sovereignty pyramid',
    'sovereignty.layer_foundation': 'Foundation',
    'sovereignty.layer_infrastructure': 'Infrastructure',
    'sovereignty.layer_services': 'Services',
    'sovereignty.layer_operations': 'Operations',
    'sovereignty.layer_excellence': 'Excellence',
    'sovereignty.layer_objective': 'Objectives',
    'sovereignty.completion': 'Completion',
    'sovereignty.priority_critical': 'Critical',
    'sovereignty.priority_high': 'High',
    'sovereignty.priority_medium': 'Medium',
    'sovereignty.priority_low': 'Low',
    'sovereignty.status_completed': 'Completed',
    'sovereignty.status_in_progress': 'In Progress',
    'sovereignty.status_planned': 'Planned',
    'sovereignty.modules': 'Modules',
    'sovereignty.quick_wins': 'Quick Wins',
    'sovereignty.action_items': 'Action Items',
    'sovereignty.target_milestones': 'Target Milestones',
    // Sovereignty - Additional pages and specific texts
    'sovereignty.no_timeline_events': 'No timeline events yet. Start documenting your sovereignty journey.',
    'sovereignty.improve_sovereignty': 'Improve Sovereignty',
    'sovereignty.energy_independence': 'Energy Independence',
    'sovereignty.build_team_skills': 'Build Team Skills',
    'sovereignty.manage_assets': 'Manage Assets',
    'sovereignty.view_reports': 'View Reports',
    'sovereignty.achievement_roadmap': 'Achievement Roadmap',
    'sovereignty.guidance_higher_levels': 'Guidance for achieving higher sovereignty levels',
    'sovereignty.step1_title': 'Step 1: Identify Key Metrics',
    'sovereignty.step1_desc': 'Understand the metrics that define sovereignty in each category.',
    'sovereignty.step2_title': 'Step 2: Set Target Values',
    'sovereignty.step2_desc': 'Establish realistic target values for each metric to strive towards.',
    'sovereignty.step3_title': 'Step 3: Monitor Progress',
    'sovereignty.step3_desc': 'Regularly track and update your progress towards these targets.',
    'sovereignty.step4_title': 'Step 4: Address Dependencies',
    'sovereignty.step4_desc': 'Identify and mitigate high-risk dependencies to enhance sovereignty.',
    'sovereignty.step5_title': 'Step 5: Optimize Resources',
    'sovereignty.step5_desc': 'Allocate resources efficiently to improve self-sufficiency in weaker areas.',
    'sovereignty.step6_title': 'Step 6: Continuous Improvement',
    'sovereignty.step6_desc': 'Continuously refine strategies and adapt to new challenges for sustained sovereignty.',
    'sovereignty.categories_tracked': 'Categories Tracked',
    'sovereignty.by_category': 'by Category',
    'sovereignty.compare_systems': 'Compare sovereignty levels across all facility systems',
    'sovereignty.metrics': 'Sovereignty Metrics',
    'sovereignty.all_categories': 'All Categories',
    'sovereignty.critical_dependencies': 'Critical Dependencies Requiring Action',
    'sovereignty.high_risk_external': 'High-risk external dependencies affecting sovereignty',
    'sovereignty.timeline_description': 'Historical improvements and impact on independence',
  },
  es: {
    'common.language': 'Idioma',
    'common.english': 'English',
    'common.spanish': 'Español',
    'nav.core_operations': 'Operaciones Principales',
    'nav.core_operations_desc': 'Administra tus reservas de propiedades',
    'nav.dashboard': 'Panel de Control',
    'nav.dashboard_tip': 'Resumen de tu propiedad',
    'nav.bookings': 'Reservas',
    'nav.bookings_tip': 'Gestiona reservas y disponibilidad',
    'nav.invoices': 'Facturas',
    'nav.invoices_tip': 'Administra facturas y pagos',
    'nav.tasks': 'Tareas',
    'nav.tasks_tip': 'Tareas de gestión diaria',
    'nav.sovereignty': 'Soberanía',
    'nav.sovereignty_desc': 'Rastrear la independencia y autosuficiencia de la instalación',
    'nav.sovereignty_dashboard': 'Panel de Control',
    'nav.sovereignty_dashboard_tip': 'Rastrear autonomía e independencia',
    'nav.coach': 'Entrenador',
    'nav.coach_tip': 'Asesor de IA para lograr independencia',
    'nav.layers': 'Capas',
    'nav.layers_tip': 'Ver pirámide de soberanía de 5 capas',
    'nav.cattle_operations': 'Operaciones de Ganado',
    'nav.cattle_operations_desc': 'Gestión de ganado y operaciones de reproducción',
    'nav.cattle_health': 'Monitoreo de Salud',
    'nav.cattle_health_tip': 'Análisis biométrico, alertas y seguimiento veterinario',
    'nav.expert_coach': 'Entrenador Experto',
    'nav.expert_coach_tip': 'Asesor de IA para negocios ganaderos',
    'nav.business_plan': 'Plan de Negocios',
    'nav.business_plan_tip': 'Proyecciones financieras',
    'nav.pricing_costs': 'Precios y Costos',
    'nav.pricing_costs_tip': 'Análisis de costos y precios',
    'nav.property_management': 'Gestión de Propiedades',
    'nav.property_management_desc': 'Configura y mantén tu instalación',
    'nav.assets': 'Activos',
    'nav.assets_tip': 'Inventario y equipo',
    'nav.inventory': 'Inventario',
    'nav.inventory_tip': 'Seguimiento de inventario multimedia y códigos QR',
    'nav.all_assets': 'Todos los Activos',
    'nav.by_category': 'Por Categoría',
    'nav.by_cost_center': 'Por Centro de Costos',
    'nav.categories': 'Categorías',
    'nav.cost_centers': 'Centros de Costos',
    'nav.audit_logs': 'Registros de Auditoría',
    'nav.operations': 'Operaciones',
    'nav.operations_tip': 'Operaciones mensuales y viajes en vehículos con seguimiento KMZ',
    'nav.fuel_consumption': 'Consumo de Combustible',
    'nav.fuel_consumption_tip': 'Rastrear el consumo de combustible del campo y costos',
    'nav.maintenance': 'Mantenimiento',
    'nav.maintenance_tip': 'Programar y rastrear reparaciones',
    'nav.gis_map': 'Mapa GIS',
    'nav.gis_map_tip': 'Ubicación y diseño de la propiedad',
    'nav.kmz_viewer': 'Visor KMZ',
    'nav.kmz_viewer_tip': 'Carga y visualiza superposiciones KMZ',
    'nav.off_grid_energy': 'Energía Fuera de Red',
    'nav.off_grid_energy_desc': 'Paneles solares, baterías y monitoreo Victron',
    'nav.management': 'Gestión',
    'nav.management_tip': 'Paneles solares y consumo de electricidad',
    'nav.energy_dashboard': 'Panel de Control',
    'nav.energy_dashboard_tip': 'Monitoreo de energía en tiempo real',
    'nav.reports': 'Reportes',
    'nav.reports_tip': 'Reportes históricos y análisis',
    'nav.victron_setup': 'Configuración Victron',
    'nav.victron_setup_tip': 'Guía de integración Victron',
    'nav.integration_docs': 'Documentos de Integración',
    'nav.integration_docs_tip': 'Documentación MQTT, Node-RED y API VRM',
    'nav.supply_chain': 'Cadena de Suministro',
    'nav.supply_chain_desc': 'Compras, proveedores y adquisiciones',
    'nav.procurement': 'Compras',
    'nav.procurement_tip': 'Órdenes de compra y adquisiciones',
    'nav.suppliers': 'Proveedores',
    'nav.suppliers_tip': 'Gestiona contactos y relaciones con proveedores',
    'nav.analytics': 'Análisis',
    'nav.people_operations': 'Personas y Operaciones',
    'nav.people_operations_desc': 'Gestión del personal y servicios para huéspedes',
    'nav.employees': 'Empleados',
    'nav.employees_tip': 'Gestión del equipo',
    'nav.volunteers': 'Voluntarios',
    'nav.volunteers_tip': 'Coordinación y seguimiento de voluntarios',
    'nav.activities': 'Calendario de Actividades',
    'nav.activities_tip': 'Planifica y gestiona actividades, eventos y entretenimiento de la instalación',
    'nav.concierge': 'Conserje',
    'nav.concierge_tip': 'Comunicación con huéspedes',
    'nav.guest_requests': 'Solicitudes de Huéspedes',
    'nav.guest_requests_tip': 'Interfaz de tableta para solicitudes de hospitalidad',
    'nav.kitchen': 'Cocina',
    'nav.kitchen_tip': 'Instalaciones de cocina y preparación de alimentos',
    'nav.checklists': 'Listas de Verificación',
    'nav.checklists_tip': 'Listas de verificación operativas',
    'nav.advanced': 'Avanzado',
    'nav.advanced_desc': 'Análisis y configuración del sistema',
    'nav.facility_requests': 'Solicitudes de Instalación',
    'nav.facility_requests_tip': 'Rastrear solicitudes de instalación y boletos de servicio',
    'nav.ai_ops': 'Operaciones de IA',
    'nav.ai_ops_tip': 'Información impulsada por IA',
    'nav.admin': 'Admin',
    'nav.admin_tip': 'Configuración del sistema',
    'nav.need_help': '¿Necesitas Ayuda?',
    'nav.press_cmd': 'Presiona ⌘K para buscar',
    'nav.version': 'BFCS v1.0',
    // Core Operations - Dashboard
    'dashboard.title': 'Sistema Central de Instalaciones Blackswan',
    'dashboard.description': 'Sistema profesional de gestión de instalaciones y reservas para tu alquiler vacacional de lujo. Administra reservas, monitorea disponibilidad y optimiza tasas de ocupación.',
    'dashboard.total_rooms': 'Habitaciones Totales',
    'dashboard.total_rooms_desc': 'Propiedades registradas',
    'dashboard.total_beds': 'Camas Totales',
    'dashboard.total_beds_desc': 'Inventario disponible',
    'dashboard.occupancy_rate': 'Tasa de Ocupación',
    'dashboard.occupancy_rate_desc': 'Utilización actual',
    'dashboard.active_reservations': 'Reservas Activas',
    'dashboard.active_reservations_desc': 'Reservas actuales',
    'dashboard.todays_checkins': 'Check-ins de Hoy',
    'dashboard.todays_checkins_desc': 'Huéspedes llegando hoy',
    'dashboard.todays_checkouts': 'Check-outs de Hoy',
    'dashboard.todays_checkouts_desc': 'Huéspedes partiendo hoy',
    'dashboard.quick_actions': 'Acciones Rápidas',
    'dashboard.booking_calendar': 'Calendario de Reservas',
    'dashboard.booking_calendar_desc': 'Ver y gestionar todas las reservas',
    'dashboard.property_management': 'Gestión de Propiedades',
    'dashboard.property_management_desc': 'Configura habitaciones y servicios',
    'dashboard.maintenance': 'Mantenimiento',
    'dashboard.maintenance_desc': 'Programa y monitorea mantenimiento',
    'dashboard.analytics': 'Análisis',
    'dashboard.analytics_desc': 'Ver tendencias e información de reservas',
    // Core Operations - Bookings
    'bookings.title': 'Reservas',
    'bookings.add_reservation': 'Agregar Reserva',
    'bookings.facilities': 'Instalaciones',
    'bookings.guests': 'Huéspedes',
    'bookings.rooms': 'Habitaciones',
    'bookings.invoices': 'Facturas',
    'bookings.reports': 'Reportes',
    'bookings.calendar': 'Calendario',
    // Core Operations - Tasks
    'tasks.title': 'Tareas',
    'tasks.add_task': 'Agregar Tarea',
    'tasks.low': 'Baja',
    'tasks.medium': 'Media',
    'tasks.high': 'Alta',
    'tasks.urgent': 'Urgente',
    'tasks.new': 'Nueva',
    'tasks.in_progress': 'En Progreso',
    'tasks.completed': 'Completada',
    'tasks.cancelled': 'Cancelada',
    // Bookings Management
    'bookings.management': 'Gestión de Reservas',
    'bookings.manage_reservations': 'Gestiona reservas en todas las propiedades',
    'bookings.single_property': 'Una Propiedad',
    'bookings.all_properties': 'Todas las Propiedades',
    'bookings.properties': 'Propiedades',
    'bookings.total_beds': 'Total de Camas',
    'bookings.active_bookings': 'Reservas Activas',
    'bookings.occupancy': 'Ocupación',
    'bookings.revenue': 'Ingresos (Est.)',
    'bookings.new_reservation': 'Nueva Reserva',
    'bookings.previous': 'Anterior',
    'bookings.next': 'Siguiente',
    'bookings.today': 'Hoy',
    'bookings.confirmed': 'Confirmada',
    'bookings.checked_in': 'Hospedado',
    'bookings.pending': 'Pendiente',
    'bookings.cancelled': 'Cancelada',
    'bookings.guest_name': 'Nombre del Huésped',
    'bookings.check_in': 'Entrada',
    'bookings.check_out': 'Salida',
    'bookings.status': 'Estado',
    'bookings.amount': 'Cantidad',
    'bookings.no_reservation': 'Haz clic para crear una nueva reserva',
    'bookings.loading': 'Cargando reservas...',
    'bookings.no_properties': 'No hay propiedades encontradas. Agrega ubicaciones primero.',
    // Invoices
    'invoices.management': 'Gestión de Facturas',
    'invoices.create_edit_manage': 'Crea, edita y gestiona todas las facturas',
    'invoices.new_invoice': 'Nueva Factura',
    'invoices.search_invoices': 'Buscar Facturas',
    'invoices.search_placeholder': 'Buscar por número de factura o nombre del cliente...',
    'invoices.all_invoices': 'Todas las Facturas',
    'invoices.invoice_number': 'Número de Factura',
    'invoices.customer': 'Cliente',
    'invoices.date': 'Fecha',
    'invoices.total': 'Total',
    'invoices.payment_status': 'Estado de Pago',
    'invoices.paid': 'Pagada',
    'invoices.pending': 'Pendiente',
    'invoices.overdue': 'Vencida',
    'invoices.draft': 'Borrador',
    'invoices.loading': 'Cargando facturas...',
    'invoices.no_invoices': 'No hay facturas encontradas',
    'invoices.delete_confirmation': '¿Estás seguro de que quieres eliminar esta factura?',
    // Facilities
    'facilities.title': 'Ubicaciones de Propiedades',
    'facilities.description': 'Gestiona todas las ubicaciones de propiedades en alquiler',
    'facilities.add_location': 'Agregar Ubicación',
    'facilities.locations': 'Ubicaciones',
    'facilities.no_locations': 'No hay ubicaciones encontradas',
    'facilities.name': 'Nombre',
    'facilities.description_field': 'Descripción',
    'facilities.latitude': 'Latitud',
    'facilities.longitude': 'Longitud',
    'facilities.add': 'Agregar',
    'facilities.edit': 'Editar',
    'facilities.delete': 'Eliminar',
    'facilities.manage_rooms_beds': 'Gestionar Habitaciones y Camas',
    'facilities.deactivate': 'Desactivar',
    'facilities.activate': 'Activar',
    'facilities.active': 'Activa',
    'facilities.search_placeholder': 'Buscar ubicaciones...',
    'facilities.add_new_location': 'Agregar Nueva Ubicación',
    'facilities.add_new_location_desc': 'Agrega una nueva ubicación de propiedad de alquiler a tu instalación',
    'facilities.location_name': 'Nombre de Ubicación',
    'facilities.location_name_placeholder': 'p.ej., Casa de Bambú, Palacio César',
    'facilities.description_label': 'Descripción',
    'facilities.description_placeholder': 'Breve descripción de la propiedad',
    'facilities.latitude_label': 'Latitud',
    'facilities.latitude_placeholder': '9.12345',
    'facilities.longitude_label': 'Longitud',
    'facilities.longitude_placeholder': '-83.12345',
    'facilities.cancel': 'Cancelar',
    'facilities.add_location_btn': 'Agregar Ubicación',
    'facilities.edit_location': 'Editar Ubicación',
    'facilities.edit_location_desc': 'Actualiza los detalles de la ubicación',
    'facilities.save_changes': 'Guardar Cambios',
    'common.cancel': 'Cancelar',
    // Rooms
    'rooms.title': 'Gestión de Habitaciones y Camas',
    'rooms.description': 'Gestiona unidades de alquiler e inventario de camas',
    'rooms.add_room': 'Agregar Habitación',
    'rooms.add_bed': 'Agregar Cama',
    'rooms.room_number': 'Número de Habitación',
    'rooms.room_type': 'Tipo de Habitación',
    'rooms.capacity': 'Capacidad',
    'rooms.rate_per_night': 'Tarifa por Noche',
    'rooms.beds': 'Camas',
    'rooms.delete_confirmation': '¿Estás seguro de que quieres eliminar esta habitación?',
    'rooms.loading': 'Cargando habitaciones...',
    'rooms.no_rooms': 'No hay habitaciones encontradas',
    'rooms.up_to_guests': 'Hasta {count} huéspedes',
    'rooms.available': 'Disponible',
    'rooms.occupied': 'Ocupado',
    // Guests
    'guests.title': 'Gestión de Huéspedes',
    'guests.description': 'Gestiona perfiles e información de huéspedes',
    'guests.add_guest': 'Agregar Huésped',
    'guests.search': 'Buscar Huéspedes',
    'guests.search_placeholder': 'Buscar por nombre, email o teléfono...',
    'guests.name': 'Nombre',
    'guests.email': 'Email',
    'guests.phone': 'Teléfono',
    'guests.company': 'Empresa',
    'guests.vip_status': 'Estado VIP',
    'guests.bookings': 'Reservas',
    'guests.delete_confirmation': '¿Estás seguro de que quieres eliminar este huésped?',
    'guests.loading': 'Cargando huéspedes...',
    'guests.no_guests': 'No hay huéspedes encontrados',
    // Reports
    'reports.title': 'Reportes',
    'reports.description': 'Ver análisis y reportes de reservas',
    'reports.occupancy': 'Reporte de Ocupación',
    'reports.revenue': 'Reporte de Ingresos',
    'reports.bookings': 'Reporte de Reservas',
    'reports.guests': 'Reporte de Huéspedes',
    'reports.current_month': 'Mes Actual',
    'reports.last_month': 'Mes Pasado',
    'reports.last_3_months': 'Últimos 3 Meses',
    'reports.last_6_months': 'Últimos 6 Meses',
    'reports.all_locations': 'Todas las Ubicaciones',
    'reports.export': 'Exportar',
    'reports.total_revenue': 'Ingresos Totales',
    'reports.total_bookings': 'Reservas Totales',
    'reports.occupancy_rate': 'Tasa de Ocupación',
    'reports.average_rate': 'Tarifa Promedio',
    'reports.total_guests': 'Huéspedes Totales',
    'reports.repeat_guests': 'Huéspedes Frecuentes',
    'reports.vip_guests': 'Huéspedes VIP',
    'reports.new_guests': 'Nuevos Huéspedes',
    'reports.location_performance': 'Rendimiento de Ubicación',
    'reports.top_performing_rooms': 'Habitaciones con Mejor Desempeño',
    'reports.payment_methods': 'Métodos de Pago',
    'reports.room': 'Habitación',
    'reports.location': 'Ubicación',
    'reports.bookings_count': 'Reservas',
    'reports.from_previous_period': 'del período anterior',
    'reports.room_utilization': 'Utilización de habitaciones',
    'reports.per_booking': 'Por reserva',
    'reports.registered_guests': 'Huéspedes registrados',
    'reports.returning_visitors': 'Visitantes que regresan',
    'reports.premium_members': 'Miembros premium',
    'reports.first_time_bookings': 'Primeras reservas',
    'reports.loading': 'Cargando reportes...',
    'reports.comprehensive_revenue': 'Información completa de ingresos, ocupación y desempeño',
    // Sovereignty - Main Dashboard
    'sovereignty.title': 'Panel de Control de Soberanía',
    'sovereignty.description': 'Rastrear la independencia de tu instalación y autosuficiencia en todos los dominios',
    'sovereignty.self_sufficiency': 'Autosuficiencia',
    'sovereignty.energy': 'Energía',
    'sovereignty.food': 'Comida',
    'sovereignty.water': 'Agua',
    'sovereignty.people': 'Personas',
    'sovereignty.software': 'Software',
    'sovereignty.assets': 'Activos',
    'sovereignty.current_value': 'Valor Actual',
    'sovereignty.target_value': 'Valor Objetivo',
    'sovereignty.trending': 'Tendencia',
    'sovereignty.last_updated': 'Última Actualización',
    'sovereignty.notes': 'Notas',
    'sovereignty.on_track': 'En Camino',
    'sovereignty.at_risk': 'En Riesgo',
    'sovereignty.dependencies': 'Dependencias',
    'sovereignty.dependency_name': 'Dependencia',
    'sovereignty.status': 'Estado',
    'sovereignty.risk_level': 'Nivel de Riesgo',
    'sovereignty.criticality': 'Criticidad',
    'sovereignty.critical': 'Crítico',
    'sovereignty.high': 'Alto',
    'sovereignty.medium': 'Medio',
    'sovereignty.low': 'Bajo',
    'sovereignty.timeline': 'Línea de Tiempo e Hitos',
    'sovereignty.event_type': 'Tipo de Evento',
    'sovereignty.before': 'Antes',
    'sovereignty.after': 'Después',
    'sovereignty.impact_area': 'Área de Impacto',
    // Sovereignty - Coach
    'sovereignty.coach_title': 'Entrenador de Soberanía',
    'sovereignty.coach_description': 'Asesor impulsado por IA para independencia de instalaciones',
    'sovereignty.coach_subtitle': 'Obtén recomendaciones personalizadas sobre energía, alimentos, agua, personas, software y soberanía de activos.',
    'sovereignty.coach_header': 'Entrenador de Soberanía IA',
    'sovereignty.coach_guidance': 'Orientación personalizada para lograr la independencia de la instalación',
    'sovereignty.coach_prompt': 'Pregúntame cualquier cosa sobre mejorar la soberanía de tu instalación en energía, alimentos, agua, personas, software y activos. Analizaré tus métricas actuales y proporcionaré recomendaciones accionables.',
    'sovereignty.coach_placeholder': 'Pregunta sobre mejorar la independencia de la instalación...',
    'sovereignty.coach_send': 'Enviar',
    'sovereignty.quick_questions': 'Preguntas Rápidas',
    // Sovereignty - Layers
    'sovereignty.layers_title': 'Capas de Soberanía',
    'sovereignty.layers_description': 'Ver la pirámide de soberanía de 5 capas',
    'sovereignty.layer_foundation': 'Fundación',
    'sovereignty.layer_infrastructure': 'Infraestructura',
    'sovereignty.layer_services': 'Servicios',
    'sovereignty.layer_operations': 'Operaciones',
    'sovereignty.layer_excellence': 'Excelencia',
    'sovereignty.layer_objective': 'Objetivos',
    'sovereignty.completion': 'Finalización',
    'sovereignty.priority_critical': 'Crítico',
    'sovereignty.priority_high': 'Alto',
    'sovereignty.priority_medium': 'Medio',
    'sovereignty.priority_low': 'Bajo',
    'sovereignty.status_completed': 'Completado',
    'sovereignty.status_in_progress': 'En Progreso',
    'sovereignty.status_planned': 'Planificado',
    'sovereignty.modules': 'Módulos',
    'sovereignty.quick_wins': 'Ganancias Rápidas',
    'sovereignty.action_items': 'Elementos de Acción',
    'sovereignty.target_milestones': 'Hitos Objetivo',
    // Sovereignty - Additional pages and specific texts
    'sovereignty.no_timeline_events': 'Sin eventos de cronología aún. Comienza a documentar tu viaje de soberanía.',
    'sovereignty.improve_sovereignty': 'Mejorar Soberanía',
    'sovereignty.energy_independence': 'Independencia Energética',
    'sovereignty.build_team_skills': 'Construir Habilidades del Equipo',
    'sovereignty.manage_assets': 'Gestionar Activos',
    'sovereignty.view_reports': 'Ver Reportes',
    'sovereignty.achievement_roadmap': 'Mapa de Ruta de Logros',
    'sovereignty.guidance_higher_levels': 'Orientación para lograr niveles más altos de soberanía',
    'sovereignty.step1_title': 'Paso 1: Identificar Métricas Clave',
    'sovereignty.step1_desc': 'Comprende las métricas que definen la soberanía en cada categoría.',
    'sovereignty.step2_title': 'Paso 2: Establecer Valores Objetivo',
    'sovereignty.step2_desc': 'Establece valores objetivo realistas para cada métrica a los que aspirar.',
    'sovereignty.step3_title': 'Paso 3: Monitorear Progreso',
    'sovereignty.step3_desc': 'Rastrear y actualizar regularmente tu progreso hacia estos objetivos.',
    'sovereignty.step4_title': 'Paso 4: Abordar Dependencias',
    'sovereignty.step4_desc': 'Identifica y mitiga dependencias de alto riesgo para mejorar la soberanía.',
    'sovereignty.step5_title': 'Paso 5: Optimizar Recursos',
    'sovereignty.step5_desc': 'Asigna recursos de manera eficiente para mejorar la autosuficiencia en áreas débiles.',
    'sovereignty.step6_title': 'Paso 6: Mejora Continua',
    'sovereignty.step6_desc': 'Refina continuamente las estrategias y adapta a nuevos desafíos para la soberanía sostenible.',
    'sovereignty.categories_tracked': 'Categorías Rastreadas',
    'sovereignty.by_category': 'por Categoría',
    'sovereignty.compare_systems': 'Compara niveles de soberanía en todos los sistemas de la instalación',
    'sovereignty.metrics': 'Métricas de Soberanía',
    'sovereignty.all_categories': 'Todas las Categorías',
    'sovereignty.critical_dependencies': 'Dependencias Críticas Que Requieren Acción',
    'sovereignty.high_risk_external': 'Dependencias externas de alto riesgo que afectan la soberanía',
    'sovereignty.timeline_description': 'Mejoras históricas e impacto en la independencia',
    'sovereignty.related_modules': 'Módulos Relacionados',
    'sovereignty.key_objectives': 'Objetivos Clave',
    'sovereignty.target': 'Objetivo',
    'sovereignty.no_objectives': 'No hay objetivos definidos aún',
    'sovereignty.overall_progress': 'Progreso General de Soberanía',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')
  const [isMounted, setIsMounted] = useState(false)

  useEffect(() => {
    setIsMounted(true)
    const saved = localStorage.getItem('language') as Language | null
    if (saved) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
