export type OperationalArea =
  | "ganaderia"
  | "hospitalidad"
  | "housekeeping"
  | "cocina"
  | "mantenimiento"
  | "huerto_vinedo"
  | "infraestructura"
  | "logistica"
  | "seguridad"
  | "administracion"

export type OperationalTaskTemplate = {
  id: string
  area: OperationalArea
  category: string
  title: string
  description: string
  estimatedMinutes: number
  priority: "baja" | "media" | "alta" | "urgente"
  animalHandling?: boolean
  safetyNotes?: string
  suitableForVolunteers?: boolean
}

export const operationalAreaLabels: Record<OperationalArea, string> = {
  ganaderia: "Ganadería y animales",
  hospitalidad: "Hospitalidad y huéspedes",
  housekeeping: "Housekeeping y habitaciones",
  cocina: "Cocina y servicio",
  mantenimiento: "Mantenimiento",
  huerto_vinedo: "Huerto y viñedo",
  infraestructura: "Infraestructura y exteriores",
  logistica: "Logística y abastecimiento",
  seguridad: "Seguridad y prevención",
  administracion: "Administración y apoyo",
}

export const operationalTaskTemplates: OperationalTaskTemplate[] = [
  { id: "ganado-ronda", area: "ganaderia", category: "Observación animal", title: "Ronda de observación del ganado", description: "Revisar comportamiento, movilidad, consumo de agua y señales visibles de lesión o enfermedad. Informar anomalías sin realizar tratamientos no autorizados.", estimatedMinutes: 45, priority: "alta", animalHandling: true, safetyNotes: "No ingresar solo a corrales con animales reactivos. Mantener vía de salida despejada.", suitableForVolunteers: false },
  { id: "ganado-agua", area: "ganaderia", category: "Agua y alimentación", title: "Revisar bebederos y suministro de agua", description: "Comprobar nivel, limpieza, flujo, filtraciones y acceso seguro de los animales. Registrar fallas para mantenimiento.", estimatedMinutes: 40, priority: "alta", animalHandling: true, safetyNotes: "Cortar energía antes de intervenir bombas o cableado. No trabajar entre animales en movimiento.", suitableForVolunteers: true },
  { id: "ganado-alimento", area: "ganaderia", category: "Agua y alimentación", title: "Preparar y distribuir alimentación animal", description: "Distribuir la ración definida para cada grupo, revisar comederos y reportar rechazo de alimento o consumo irregular.", estimatedMinutes: 60, priority: "alta", animalHandling: true, safetyNotes: "Usar solo raciones e indicaciones autorizadas. No modificar dosis ni suplementos.", suitableForVolunteers: true },
  { id: "ganado-cercos", area: "ganaderia", category: "Potreros y cercos", title: "Inspeccionar cercos, portones y pasos de ganado", description: "Recorrer el sector asignado, detectar alambres sueltos, postes dañados, portones abiertos y riesgos de escape.", estimatedMinutes: 90, priority: "alta", animalHandling: true, safetyNotes: "No reparar cercos eléctricos energizados. Señalizar el sector antes de intervenir.", suitableForVolunteers: true },
  { id: "ganado-corrales", area: "ganaderia", category: "Corrales", title: "Limpiar y ordenar corrales", description: "Retirar residuos, limpiar zonas de tránsito y mantener accesos, mangas y áreas de manejo despejadas.", estimatedMinutes: 90, priority: "media", animalHandling: true, safetyNotes: "Realizar con el corral despejado o bajo supervisión del responsable de animales.", suitableForVolunteers: true },
  { id: "ganado-registro", area: "ganaderia", category: "Registros", title: "Actualizar registro diario de animales", description: "Registrar observaciones, movimientos, alimentación, alertas de salud y novedades informadas por el encargado.", estimatedMinutes: 30, priority: "media", animalHandling: false, suitableForVolunteers: true },

  { id: "hosp-checkin", area: "hospitalidad", category: "Llegadas", title: "Preparar llegada de huéspedes", description: "Confirmar habitación, accesos, calefacción, iluminación, agua, información de bienvenida y solicitudes registradas.", estimatedMinutes: 45, priority: "alta", suitableForVolunteers: true },
  { id: "hosp-request", area: "hospitalidad", category: "Solicitudes", title: "Atender solicitud de huésped", description: "Revisar la solicitud asignada, coordinar la solución y registrar resultado o escalamiento.", estimatedMinutes: 30, priority: "alta", suitableForVolunteers: false },
  { id: "hosp-common", area: "hospitalidad", category: "Áreas comunes", title: "Revisar áreas comunes para huéspedes", description: "Verificar orden, limpieza, temperatura, iluminación, mobiliario y disponibilidad de insumos en espacios compartidos.", estimatedMinutes: 45, priority: "media", suitableForVolunteers: true },
  { id: "hosp-experience", area: "hospitalidad", category: "Experiencia", title: "Preparar actividad o experiencia para huéspedes", description: "Confirmar lugar, materiales, condiciones climáticas, seguridad, horario y responsable de la actividad.", estimatedMinutes: 60, priority: "media", suitableForVolunteers: true },
  { id: "hosp-arrivals-review", area: "hospitalidad", category: "Llegadas", title: "Revisar llegadas del día", description: "Confirmar huéspedes que llegan hoy, horario estimado, habitación, número de personas, solicitudes especiales y pendientes antes de recibirlos.", estimatedMinutes: 20, priority: "alta", suitableForVolunteers: false },
  { id: "hosp-welcome", area: "hospitalidad", category: "Llegadas", title: "Preparar bienvenida del huésped", description: "Dejar lista la información de acceso, indicaciones principales, contacto operativo y elementos de bienvenida definidos para la estadía.", estimatedMinutes: 25, priority: "alta", suitableForVolunteers: true },
  { id: "hosp-checkout", area: "hospitalidad", category: "Salidas", title: "Coordinar salida de huéspedes", description: "Confirmar horario de salida, equipaje, llaves o accesos, consumos pendientes, transporte informado y coordinación con housekeeping.", estimatedMinutes: 25, priority: "alta", suitableForVolunteers: false },
  { id: "hosp-departures-review", area: "hospitalidad", category: "Salidas", title: "Revisar salidas del día", description: "Revisar huéspedes que salen hoy, horarios, solicitudes pendientes y habitaciones que deben liberarse para coordinar operación.", estimatedMinutes: 20, priority: "alta", suitableForVolunteers: false },
  { id: "hosp-guest-followup", area: "hospitalidad", category: "Experiencia", title: "Revisar experiencia de huéspedes alojados", description: "Contactar o revisar discretamente si existe alguna necesidad operativa pendiente durante la estadía y registrar sólo acciones necesarias.", estimatedMinutes: 20, priority: "media", suitableForVolunteers: false },
  { id: "hosp-transfer", area: "hospitalidad", category: "Traslados", title: "Confirmar traslado de huésped", description: "Confirmar hora, punto de encuentro, número de pasajeros, equipaje, responsable y cualquier instrucción registrada para el traslado.", estimatedMinutes: 15, priority: "alta", suitableForVolunteers: false },
  { id: "hosp-shift-handover", area: "hospitalidad", category: "Turno", title: "Entregar pendientes del turno de hospitalidad", description: "Registrar llegadas, salidas, solicitudes abiertas, incidencias y compromisos que el siguiente turno debe continuar.", estimatedMinutes: 15, priority: "alta", suitableForVolunteers: false },

  { id: "hk-checkout", area: "housekeeping", category: "Habitaciones", title: "Limpieza completa posterior a salida", description: "Ventilar, retirar ropa usada, limpiar baño y superficies, reponer textiles e insumos y reportar daños u objetos olvidados.", estimatedMinutes: 75, priority: "alta", suitableForVolunteers: false },
  { id: "hk-refresh", area: "housekeeping", category: "Habitaciones", title: "Repaso diario de habitación ocupada", description: "Ordenar, retirar residuos, reponer insumos autorizados y reportar necesidades de mantenimiento sin mover pertenencias personales.", estimatedMinutes: 30, priority: "media", suitableForVolunteers: false },
  { id: "hk-laundry", area: "housekeeping", category: "Lavandería", title: "Clasificar y procesar ropa de cama", description: "Separar textiles, revisar manchas o daños, lavar según tipo, secar, doblar y registrar bajas necesarias.", estimatedMinutes: 90, priority: "media", suitableForVolunteers: true },
  { id: "hk-inventory", area: "housekeeping", category: "Insumos", title: "Revisar stock de housekeeping", description: "Contar ropa de cama, toallas, artículos de aseo y consumibles; informar faltantes o diferencias.", estimatedMinutes: 45, priority: "media", suitableForVolunteers: true },
  { id: "hk-common", area: "housekeeping", category: "Áreas comunes", title: "Limpiar y ordenar áreas comunes", description: "Limpiar superficies, retirar residuos, ordenar mobiliario y reponer insumos básicos en espacios comunes de uso de huéspedes y equipo.", estimatedMinutes: 60, priority: "media", suitableForVolunteers: true },
  { id: "hk-prearrival-inspection", area: "housekeeping", category: "Inspección", title: "Inspeccionar habitación antes de llegada", description: "Verificar cama, baño, limpieza, textiles, amenities, temperatura, iluminación, olor y detalles visibles antes de liberar la habitación.", estimatedMinutes: 20, priority: "alta", suitableForVolunteers: false },
  { id: "hk-bathroom", area: "housekeeping", category: "Habitaciones", title: "Sanitizar y reponer baño de huésped", description: "Limpiar y sanitizar superficies, revisar ducha y desagüe, reponer toallas, papel y amenities definidos.", estimatedMinutes: 25, priority: "alta", suitableForVolunteers: false },
  { id: "hk-amenities", area: "housekeeping", category: "Insumos", title: "Reponer amenities de habitaciones", description: "Revisar las habitaciones asignadas y reponer únicamente los amenities e insumos definidos para cada tipo de estadía.", estimatedMinutes: 30, priority: "media", suitableForVolunteers: true },
  { id: "hk-linen-restock", area: "housekeeping", category: "Lavandería", title: "Reponer ropa blanca en puntos de operación", description: "Distribuir sábanas, fundas, toallas y textiles limpios en los puntos definidos, registrando faltantes o daños visibles.", estimatedMinutes: 35, priority: "media", suitableForVolunteers: true },
  { id: "hk-lost-found", area: "housekeeping", category: "Objetos encontrados", title: "Registrar objeto encontrado en habitación", description: "No manipular más de lo necesario. Registrar habitación, fecha, descripción objetiva y entregar el objeto al responsable definido.", estimatedMinutes: 10, priority: "alta", suitableForVolunteers: false },
  { id: "hk-room-release", area: "housekeeping", category: "Inspección", title: "Liberar habitación para check-in", description: "Confirmar que limpieza e inspección están completas y que no quedan pendientes visibles antes de marcar la habitación disponible.", estimatedMinutes: 10, priority: "alta", suitableForVolunteers: false },

  { id: "kitchen-breakfast", area: "cocina", category: "Servicio", title: "Preparar desayuno", description: "Preparar mise en place, alimentos, vajilla y estación de servicio según número de huéspedes y requerimientos informados.", estimatedMinutes: 90, priority: "alta", suitableForVolunteers: false },
  { id: "kitchen-lunch", area: "cocina", category: "Servicio", title: "Preparar almuerzo", description: "Preparar y servir almuerzo según planificación del día, restricciones alimentarias registradas y número de comensales.", estimatedMinutes: 120, priority: "alta", suitableForVolunteers: false },
  { id: "kitchen-dinner", area: "cocina", category: "Servicio", title: "Preparar cena", description: "Preparar y servir cena, dejando cocina y superficies de trabajo sanitizadas al cierre.", estimatedMinutes: 120, priority: "alta", suitableForVolunteers: false },
  { id: "kitchen-mise", area: "cocina", category: "Preparación", title: "Mise en place del día", description: "Revisar menú, porcionar ingredientes, preparar bases y dejar estaciones listas para los servicios programados.", estimatedMinutes: 60, priority: "media", suitableForVolunteers: false },
  { id: "kitchen-hygiene", area: "cocina", category: "Higiene", title: "Limpieza y cierre de cocina", description: "Lavar y guardar utensilios, sanitizar superficies, retirar residuos, revisar equipos apagados y dejar la cocina lista para el siguiente turno.", estimatedMinutes: 60, priority: "alta", suitableForVolunteers: true },
  { id: "kitchen-stock", area: "cocina", category: "Abastecimiento", title: "Revisar stock y vencimientos de cocina", description: "Revisar insumos críticos, cadena de frío, fechas de vencimiento y faltantes; registrar necesidades de compra sin ajustar inventario histórico.", estimatedMinutes: 45, priority: "media", suitableForVolunteers: true },
  { id: "kitchen-dietary", area: "cocina", category: "Huéspedes", title: "Revisar restricciones alimentarias", description: "Confirmar alergias, restricciones y preferencias registradas para huéspedes antes de preparar el próximo servicio.", estimatedMinutes: 20, priority: "alta", suitableForVolunteers: false },
  { id: "kitchen-coffee", area: "cocina", category: "Servicio", title: "Preparar estación de café y bebidas calientes", description: "Revisar agua, café, té, leche, vajilla y limpieza de la estación antes del servicio programado.", estimatedMinutes: 20, priority: "media", suitableForVolunteers: true },
  { id: "kitchen-service-reset", area: "cocina", category: "Servicio", title: "Restablecer comedor después del servicio", description: "Retirar vajilla, limpiar mesas y superficies, reponer elementos básicos y dejar el comedor preparado para el siguiente uso.", estimatedMinutes: 35, priority: "media", suitableForVolunteers: true },
  { id: "kitchen-cold-chain", area: "cocina", category: "Higiene", title: "Revisar cadena de frío y equipos", description: "Verificar temperaturas visibles, puertas cerradas, orden y condiciones de refrigeradores y congeladores. Escalar cualquier desviación.", estimatedMinutes: 15, priority: "alta", suitableForVolunteers: false },
  { id: "kitchen-breakfast-close", area: "cocina", category: "Servicio", title: "Cerrar servicio de desayuno", description: "Retirar alimentos expuestos, almacenar lo permitido, sanitizar estación, lavar vajilla y registrar faltantes para el siguiente servicio.", estimatedMinutes: 40, priority: "media", suitableForVolunteers: true },

  { id: "mant-water", area: "mantenimiento", category: "Agua", title: "Inspeccionar sistema de agua del sector", description: "Revisar bombas, estanques, caudal, filtraciones, ruidos anormales y presión visible. Registrar evidencia de fallas.", estimatedMinutes: 60, priority: "alta", safetyNotes: "No intervenir tableros eléctricos ni equipos presurizados sin autorización.", suitableForVolunteers: false },
  { id: "mant-heating", area: "mantenimiento", category: "Calefacción", title: "Revisar calefacción y agua caliente", description: "Comprobar funcionamiento, temperatura, combustible o energía disponible y señales de fuga o combustión anormal.", estimatedMinutes: 45, priority: "alta", safetyNotes: "Suspender uso y escalar ante olor a gas, humo o sobrecalentamiento.", suitableForVolunteers: false },
  { id: "mant-tools", area: "mantenimiento", category: "Herramientas", title: "Ordenar y revisar herramientas", description: "Limpiar, ordenar, comprobar estado y registrar herramientas faltantes, dañadas o inseguras.", estimatedMinutes: 60, priority: "media", suitableForVolunteers: true },
  { id: "mant-waste", area: "mantenimiento", category: "Residuos", title: "Retirar y clasificar residuos operativos", description: "Retirar residuos de puntos asignados, separar reciclables y trasladar materiales al área definida.", estimatedMinutes: 60, priority: "media", safetyNotes: "No manipular químicos, vidrio roto o residuos peligrosos sin equipo y responsable autorizado.", suitableForVolunteers: true },
  { id: "mant-room-quickcheck", area: "mantenimiento", category: "Habitaciones", title: "Revisar falla reportada en habitación", description: "Inspeccionar la falla reportada, registrar condición visible, resolver sólo si corresponde a una intervención simple autorizada o escalar.", estimatedMinutes: 30, priority: "alta", safetyNotes: "No intervenir electricidad, gas, presión o equipos críticos sin autorización.", suitableForVolunteers: false },
  { id: "mant-lighting", area: "mantenimiento", category: "Iluminación", title: "Revisar iluminación de áreas de huéspedes", description: "Comprobar luces y luminarias en accesos, pasillos y áreas comunes; registrar fallas y riesgos visibles.", estimatedMinutes: 30, priority: "media", suitableForVolunteers: true },
  { id: "mant-backup", area: "mantenimiento", category: "Continuidad operativa", title: "Revisar respaldo eléctrico operativo", description: "Comprobar visualmente disponibilidad y estado operativo informado del sistema de respaldo. Escalar cualquier alerta o falta de disponibilidad.", estimatedMinutes: 20, priority: "alta", safetyNotes: "No abrir tableros ni intervenir conexiones eléctricas.", suitableForVolunteers: false },

  { id: "huerto-riego", area: "huerto_vinedo", category: "Riego", title: "Revisar y ejecutar riego programado", description: "Comprobar humedad, líneas de riego, goteros, válvulas y fugas. Aplicar únicamente el programa indicado.", estimatedMinutes: 75, priority: "alta", suitableForVolunteers: true },
  { id: "huerto-maleza", area: "huerto_vinedo", category: "Manejo vegetal", title: "Control manual de malezas", description: "Retirar malezas en el sector asignado evitando daño a cultivos, raíces, tutores y líneas de riego.", estimatedMinutes: 120, priority: "media", suitableForVolunteers: true },
  { id: "huerto-cosecha", area: "huerto_vinedo", category: "Cosecha", title: "Cosechar y clasificar producción", description: "Cosechar según madurez indicada, separar producto dañado y trasladar en contenedores limpios.", estimatedMinutes: 120, priority: "media", suitableForVolunteers: true },
  { id: "vinedo-inspection", area: "huerto_vinedo", category: "Viñedo", title: "Inspeccionar hileras del viñedo", description: "Revisar tutores, alambres, brotes, riego, daño de fauna y signos visibles de enfermedad para informar al responsable.", estimatedMinutes: 90, priority: "media", suitableForVolunteers: true },

  { id: "infra-trails", area: "infraestructura", category: "Senderos", title: "Inspeccionar y despejar senderos", description: "Retirar ramas y obstáculos menores, revisar drenajes, señalética y riesgos de caída. Escalar árboles o daños mayores.", estimatedMinutes: 120, priority: "media", safetyNotes: "No usar motosierra ni intervenir árboles tensionados sin personal calificado.", suitableForVolunteers: true },
  { id: "infra-drainage", area: "infraestructura", category: "Drenajes", title: "Limpiar canaletas y drenajes superficiales", description: "Retirar hojas y sedimentos, verificar flujo y reportar erosión, obstrucciones profundas o daños estructurales.", estimatedMinutes: 90, priority: "alta", suitableForVolunteers: true },
  { id: "infra-signage", area: "infraestructura", category: "Señalética", title: "Revisar señalética y demarcaciones", description: "Comprobar visibilidad, fijaciones, contenido y ubicación de señalética operativa, de seguridad y para huéspedes.", estimatedMinutes: 60, priority: "baja", suitableForVolunteers: true },

  { id: "log-receiving", area: "logistica", category: "Recepción", title: "Recibir y verificar abastecimiento", description: "Comparar productos y cantidades con la orden, revisar estado, registrar diferencias y almacenar según corresponda.", estimatedMinutes: 45, priority: "media", suitableForVolunteers: false },
  { id: "log-inventory", area: "logistica", category: "Inventario", title: "Conteo de inventario del sector", description: "Contar existencias físicas, identificar faltantes, vencimientos o daños y registrar diferencias sin ajustar datos históricos.", estimatedMinutes: 90, priority: "media", suitableForVolunteers: true },
  { id: "log-vehicle", area: "logistica", category: "Vehículos", title: "Revisión visual previa de vehículo", description: "Revisar neumáticos, luces, niveles visibles, daños, limpieza y elementos de seguridad antes de uso.", estimatedMinutes: 20, priority: "alta", safetyNotes: "No conducir ni intervenir mecánica sin autorización y licencia correspondiente.", suitableForVolunteers: false },
  { id: "log-guest-supplies", area: "logistica", category: "Abastecimiento", title: "Preparar insumos para próximas llegadas", description: "Reunir y distribuir los insumos definidos para próximas llegadas según ocupación prevista, sin alterar inventario histórico.", estimatedMinutes: 30, priority: "media", suitableForVolunteers: true },
  { id: "log-linen-transfer", area: "logistica", category: "Distribución interna", title: "Mover ropa blanca entre lavandería y habitaciones", description: "Trasladar textiles limpios y usados en contenedores separados hacia los puntos definidos para operación.", estimatedMinutes: 30, priority: "media", suitableForVolunteers: true },

  { id: "safe-round", area: "seguridad", category: "Prevención", title: "Ronda preventiva del sector", description: "Revisar accesos, iluminación, obstáculos, extintores visibles, salidas y condiciones inseguras. Registrar y escalar hallazgos.", estimatedMinutes: 45, priority: "alta", suitableForVolunteers: false },
  { id: "safe-weather", area: "seguridad", category: "Clima", title: "Preparar sector ante lluvia o viento fuerte", description: "Asegurar objetos sueltos, despejar drenajes accesibles, revisar cierres y comunicar riesgos operativos.", estimatedMinutes: 60, priority: "alta", safetyNotes: "No trabajar en altura ni cerca de árboles inestables durante viento fuerte.", suitableForVolunteers: true },

  { id: "admin-records", area: "administracion", category: "Registros", title: "Actualizar registros operativos del día", description: "Consolidar tareas, novedades, consumos, incidencias y pendientes informados por los responsables de cada área.", estimatedMinutes: 45, priority: "media", suitableForVolunteers: true },
  { id: "admin-photos", area: "administracion", category: "Evidencia", title: "Ordenar evidencia fotográfica operativa", description: "Clasificar fotografías por fecha, sector y actividad, evitando incluir datos personales innecesarios.", estimatedMinutes: 60, priority: "baja", suitableForVolunteers: true },
  { id: "admin-shift-handover", area: "administracion", category: "Turno", title: "Consolidar entrega de turno", description: "Resumir pendientes críticos, responsables, huéspedes afectados, incidencias y acciones que deben continuar en el siguiente turno.", estimatedMinutes: 20, priority: "alta", suitableForVolunteers: false },
]
