"use client"

import { FormEvent, useEffect, useMemo, useState } from "react"
import { Save, ShieldCheck } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale = "en" | "es" | "de"
type Settings = {
  id:string; farm_key:string; farm_name:string; country_code:string; currency:string; farm_address:string|null; farm_city:string|null; farm_state:string|null; postal_code:string|null;
  latitude:number|null; longitude:number|null; measurement_system:"metric"|"imperial"; temperature_unit:"celsius"|"fahrenheit"; planting_amount_unit:"bed"|"bed_meter";
  standard_bed_width_cm:number|string; standard_bed_length_m:number|string; standard_path_width_cm:number|string;
  last_hard_frost_md:string|null; last_light_frost_md:string|null; first_light_frost_md:string|null; first_hard_frost_md:string|null; frost_source:string|null;
  weather_timezone:string|null; weather_provider:string|null; weather_enabled:boolean|null; first_weekday:string|null; updated_at:string
}
type Plan = { id:string; name:string; season:string|null; start_date:string|null; end_date:string|null; status:string }
type Account = { email:string; name:string; id:string }
type Tab = "farm" | "account" | "subscription" | "references"

const copy = {
  en:{title:"Settings",farmTab:"Farm Info",accountTab:"Account",subscriptionTab:"Subscription",referencesTab:"References",farmDetails:"Farm Details",farmName:"Farm Name",fullAddress:"Full Address",city:"City",state:"State",zip:"Zip",country:"Country",timezone:"Timezone",measurement:"Measurement System",imperial:"Imperial",metric:"Metric",seasonCalendar:"Season & Calendar",startSeason:"Start of Season",temperature:"Temperature",plantingAmount:"Planting Amount",firstWeekday:"First Weekday",bed:"Bed",bedMeter:"Bed Meter",notSet:"Not set",sunday:"Sunday",monday:"Monday",tuesday:"Tuesday",wednesday:"Wednesday",thursday:"Thursday",friday:"Friday",saturday:"Saturday",frost:"Frost Date Presets",lastHard:"Last Hard Frost",lastLight:"Last Light Frost",firstLight:"First Light Frost",firstHard:"First Hard Frost",override:"Override Frost Dates",save:"Save",saving:"Saving…",saved:"Settings saved",error:"Could not save farm settings.",loading:"Loading settings…",account:"Account",accountHelp:"Authenticated account currently operating Black Swan Orchard.",name:"Name",email:"Email",userId:"User ID",subscription:"Subscription",subscriptionHelp:"No canonical subscription or billing source is connected to Black Swan Orchard. Nothing is inferred here.",subscriptionState:"Subscription data",notConnected:"Not connected",references:"References",referencesHelp:"Canonical sources used by Orchard preferences and planning.",farmSettingsSource:"Farm preferences, location, units and frost presets",gamePlanSource:"Season boundaries and active planning scope",cropLibrarySource:"Crop and cultivar agronomic parameters",rls:"Protected by Orchard RLS",canonical:"Canonical source"},
  es:{title:"Configuración",farmTab:"Información de la granja",accountTab:"Cuenta",subscriptionTab:"Suscripción",referencesTab:"Referencias",farmDetails:"Datos de la granja",farmName:"Nombre de la granja",fullAddress:"Dirección completa",city:"Ciudad",state:"Región",zip:"Código postal",country:"País",timezone:"Zona horaria",measurement:"Sistema de medición",imperial:"Imperial",metric:"Métrico",seasonCalendar:"Temporada y calendario",startSeason:"Inicio de temporada",temperature:"Temperatura",plantingAmount:"Cantidad de plantación",firstWeekday:"Primer día de la semana",bed:"Cama",bedMeter:"Metro de cama",notSet:"Sin configurar",sunday:"Domingo",monday:"Lunes",tuesday:"Martes",wednesday:"Miércoles",thursday:"Jueves",friday:"Viernes",saturday:"Sábado",frost:"Fechas de heladas",lastHard:"Última helada fuerte",lastLight:"Última helada ligera",firstLight:"Primera helada ligera",firstHard:"Primera helada fuerte",override:"Editar fechas de heladas",save:"Guardar",saving:"Guardando…",saved:"Configuración guardada",error:"No fue posible guardar la configuración.",loading:"Cargando configuración…",account:"Cuenta",accountHelp:"Cuenta autenticada que opera actualmente Black Swan Orchard.",name:"Nombre",email:"Correo",userId:"ID de usuario",subscription:"Suscripción",subscriptionHelp:"Black Swan Orchard no tiene una fuente canónica de suscripción o facturación conectada. No se infiere información.",subscriptionState:"Datos de suscripción",notConnected:"No conectado",references:"Referencias",referencesHelp:"Fuentes canónicas utilizadas por las preferencias y planificación de Orchard.",farmSettingsSource:"Preferencias, ubicación, unidades y heladas de la granja",gamePlanSource:"Límites de temporada y alcance activo de planificación",cropLibrarySource:"Parámetros agronómicos de cultivos y cultivares",rls:"Protegido por RLS de Orchard",canonical:"Fuente canónica"},
  de:{title:"Einstellungen",farmTab:"Hofdaten",accountTab:"Konto",subscriptionTab:"Abonnement",referencesTab:"Referenzen",farmDetails:"Hofdetails",farmName:"Hofname",fullAddress:"Vollständige Adresse",city:"Stadt",state:"Region",zip:"Postleitzahl",country:"Land",timezone:"Zeitzone",measurement:"Maßsystem",imperial:"Imperial",metric:"Metrisch",seasonCalendar:"Saison & Kalender",startSeason:"Saisonbeginn",temperature:"Temperatur",plantingAmount:"Pflanzmenge",firstWeekday:"Erster Wochentag",bed:"Beet",bedMeter:"Beetmeter",notSet:"Nicht festgelegt",sunday:"Sonntag",monday:"Montag",tuesday:"Dienstag",wednesday:"Mittwoch",thursday:"Donnerstag",friday:"Freitag",saturday:"Samstag",frost:"Frosttermine",lastHard:"Letzter harter Frost",lastLight:"Letzter leichter Frost",firstLight:"Erster leichter Frost",firstHard:"Erster harter Frost",override:"Frosttermine bearbeiten",save:"Speichern",saving:"Speichern…",saved:"Einstellungen gespeichert",error:"Hofeinstellungen konnten nicht gespeichert werden.",loading:"Einstellungen werden geladen…",account:"Konto",accountHelp:"Authentifiziertes Konto, das Black Swan Orchard derzeit betreibt.",name:"Name",email:"E-Mail",userId:"Benutzer-ID",subscription:"Abonnement",subscriptionHelp:"Für Black Swan Orchard ist keine kanonische Abonnement- oder Abrechnungsquelle verbunden. Es werden keine Daten abgeleitet.",subscriptionState:"Abonnementdaten",notConnected:"Nicht verbunden",references:"Referenzen",referencesHelp:"Kanonische Quellen für Orchard-Einstellungen und Planung.",farmSettingsSource:"Hofpräferenzen, Standort, Einheiten und Frosttermine",gamePlanSource:"Saisongrenzen und aktiver Planungsumfang",cropLibrarySource:"Agronomische Parameter für Kulturen und Sorten",rls:"Durch Orchard-RLS geschützt",canonical:"Kanonische Quelle"}
} as const

const blank:Settings = {id:"",farm_key:"black_swan_orchard",farm_name:"Black Swan Orchard",country_code:"CL",currency:"CLP",farm_address:"",farm_city:"",farm_state:"",postal_code:"",latitude:null,longitude:null,measurement_system:"metric",temperature_unit:"celsius",planting_amount_unit:"bed_meter",standard_bed_width_cm:76,standard_bed_length_m:10,standard_path_width_cm:40,last_hard_frost_md:null,last_light_frost_md:null,first_light_frost_md:null,first_hard_frost_md:null,frost_source:null,weather_timezone:null,weather_provider:null,weather_enabled:null,first_weekday:null,updated_at:""}

function mdFromDate(value:string|null){if(!value)return "—";const [,m,d]=value.split("-");return m&&d?`${m}/${d}`:"—"}

export default function OrchardSettingsPage(){
  const {language}=useLanguage(); const lang:Locale=language; const text=copy[lang]; const supabase=useMemo(()=>createBrowserClient(),[])
  const [settings,setSettings]=useState<Settings>(blank); const [plans,setPlans]=useState<Plan[]>([]); const [account,setAccount]=useState<Account>({email:"",name:"",id:""});
  const [tab,setTab]=useState<Tab>("farm"); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null)

  useEffect(()=>{if(typeof window==="undefined")return;const raw=new URLSearchParams(window.location.search).get("tab");if(raw==="account"||raw==="subscription"||raw==="references")setTab(raw)},[])
  useEffect(()=>{let live=true;void Promise.all([
    supabase.from("orchard_farm_settings").select("*").eq("farm_key","black_swan_orchard").single(),
    supabase.from("orchard_game_plans").select("id,name,season,start_date,end_date,status").order("start_date",{ascending:false}),
    supabase.auth.getUser(),
  ]).then(([s,p,u])=>{if(!live)return;if(s.error)setError(s.error.message);else setSettings({...blank,...(s.data as Settings)});setPlans((p.data??[]) as Plan[]);const user=u.data.user;if(user)setAccount({email:user.email??"",name:String(user.user_metadata?.full_name??user.email?.split("@")[0]??""),id:user.id});setLoading(false)});return()=>{live=false}},[supabase])

  const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null
  const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
  const update=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(current=>({...current,[key]:value}))
  const switchTab=(next:Tab)=>{setTab(next);if(typeof window!=="undefined"){const url=new URL(window.location.href);next==="farm"?url.searchParams.delete("tab"):url.searchParams.set("tab",next);window.history.replaceState(null,"",url.toString())}}
  const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setMessage(null);setError(null);const payload={farm_name:settings.farm_name,country_code:settings.country_code,currency:settings.currency,farm_address:settings.farm_address||null,farm_city:settings.farm_city||null,farm_state:settings.farm_state||null,postal_code:settings.postal_code||null,latitude:settings.latitude==null?null:Number(settings.latitude),longitude:settings.longitude==null?null:Number(settings.longitude),measurement_system:settings.measurement_system,temperature_unit:settings.temperature_unit,planting_amount_unit:settings.planting_amount_unit,standard_bed_width_cm:Number(settings.standard_bed_width_cm),standard_bed_length_m:Number(settings.standard_bed_length_m),standard_path_width_cm:Number(settings.standard_path_width_cm),last_hard_frost_md:settings.last_hard_frost_md||null,last_light_frost_md:settings.last_light_frost_md||null,first_light_frost_md:settings.first_light_frost_md||null,first_hard_frost_md:settings.first_hard_frost_md||null,weather_timezone:settings.weather_timezone||null,first_weekday:settings.first_weekday||null};const result=await supabase.from("orchard_farm_settings").update(payload).eq("id",settings.id).select("*").single();if(result.error)setError(text.error);else{setSettings({...blank,...(result.data as Settings)});setMessage(text.saved)}setSaving(false)}

  if(loading)return <AppLayout><OrchardNavigation/><main className="p-8 text-sm text-muted-foreground">{text.loading}</main></AppLayout>
  const tabs:[Tab,string][]=[["farm",text.farmTab],["account",text.accountTab],["subscription",text.subscriptionTab],["references",text.referencesTab]]
  return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1180px] px-5 pb-20 pt-6 lg:px-8">
    <div className="flex items-center justify-between gap-4"><h1 className="text-[30px] font-normal tracking-[-.03em]">{text.title}</h1>{tab==="farm"?<button type="submit" form="orchard-farm-settings" disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md bg-[#176f55] px-4 text-sm font-medium text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?text.saving:text.save}</button>:null}</div>
    <div className="mt-5 flex gap-8 border-b border-[var(--orchard-line)]">{tabs.map(([key,label])=><button key={key} type="button" onClick={()=>switchTab(key)} className={`border-b-2 px-0 pb-3 text-sm ${tab===key?"border-[var(--orchard-green)] text-[var(--orchard-green)]":"border-transparent text-muted-foreground hover:text-foreground"}`}>{label}</button>)}</div>

    {tab==="farm"?<form id="orchard-farm-settings" onSubmit={save} className="mt-7">
      <div className="grid gap-12 lg:grid-cols-[1fr_1.1fr]">
        <section><h2 className="mb-5 text-[21px] font-normal">{text.farmDetails}</h2><div className="space-y-4">
          <Field label={text.farmName}><input value={settings.farm_name} onChange={e=>update("farm_name",e.target.value)} className="field"/></Field>
          <Field label={text.fullAddress}><input value={settings.farm_address??""} onChange={e=>update("farm_address",e.target.value)} className="field"/></Field>
          <Field label={text.city}><input value={settings.farm_city??""} onChange={e=>update("farm_city",e.target.value)} className="field"/></Field>
          <Field label={text.state}><input value={settings.farm_state??""} onChange={e=>update("farm_state",e.target.value)} className="field"/></Field>
          <Field label={text.zip}><input value={settings.postal_code??""} onChange={e=>update("postal_code",e.target.value)} className="field"/></Field>
          <Field label={text.country}><input value={settings.country_code} onChange={e=>update("country_code",e.target.value.toUpperCase())} maxLength={2} className="field"/></Field>
          <Field label={text.timezone}><input value={settings.weather_timezone??""} onChange={e=>update("weather_timezone",e.target.value)} placeholder="America/Santiago" className="field"/></Field>
        </div></section>

        <div className="space-y-9">
          <section><h2 className="mb-4 text-[21px] font-normal">{text.measurement}</h2><div className="grid grid-cols-2 gap-3"><Choice active={settings.measurement_system==="imperial"} onClick={()=>update("measurement_system","imperial")} label={text.imperial}/><Choice active={settings.measurement_system==="metric"} onClick={()=>update("measurement_system","metric")} label={text.metric}/></div></section>
          <section><h2 className="mb-4 text-[21px] font-normal">{text.seasonCalendar}</h2><div className="grid gap-x-5 gap-y-4 sm:grid-cols-2">
            <ReadField label={text.startSeason} value={mdFromDate(plan?.start_date??null)}/>
            <Field label={text.temperature}><select value={settings.temperature_unit} onChange={e=>update("temperature_unit",e.target.value as Settings["temperature_unit"])} className="field"><option value="celsius">°C</option><option value="fahrenheit">°F</option></select></Field>
            <Field label={text.plantingAmount}><select value={settings.planting_amount_unit} onChange={e=>update("planting_amount_unit",e.target.value as Settings["planting_amount_unit"])} className="field"><option value="bed">{text.bed}</option><option value="bed_meter">{text.bedMeter}</option></select></Field>
            <Field label={text.firstWeekday}><select value={settings.first_weekday??""} onChange={e=>update("first_weekday",e.target.value||null)} className="field"><option value="">{text.notSet}</option><option value="sunday">{text.sunday}</option><option value="monday">{text.monday}</option><option value="tuesday">{text.tuesday}</option><option value="wednesday">{text.wednesday}</option><option value="thursday">{text.thursday}</option><option value="friday">{text.friday}</option><option value="saturday">{text.saturday}</option></select></Field>
          </div></section>
          <section><div className="mb-4 flex items-center justify-between gap-4"><h2 className="text-[21px] font-normal">{text.frost}</h2><span className="text-xs text-muted-foreground">{settings.frost_source??text.canonical}</span></div><div className="grid gap-x-5 gap-y-4 sm:grid-cols-2">
            <Field label={text.lastHard}><input value={settings.last_hard_frost_md??""} onChange={e=>update("last_hard_frost_md",e.target.value||null)} placeholder="MM/DD" className="field"/></Field>
            <Field label={text.lastLight}><input value={settings.last_light_frost_md??""} onChange={e=>update("last_light_frost_md",e.target.value||null)} placeholder="MM/DD" className="field"/></Field>
            <Field label={text.firstLight}><input value={settings.first_light_frost_md??""} onChange={e=>update("first_light_frost_md",e.target.value||null)} placeholder="MM/DD" className="field"/></Field>
            <Field label={text.firstHard}><input value={settings.first_hard_frost_md??""} onChange={e=>update("first_hard_frost_md",e.target.value||null)} placeholder="MM/DD" className="field"/></Field>
          </div><p className="mt-3 text-xs text-[var(--orchard-green)]">{text.override}</p></section>
        </div>
      </div>
      <div className="mt-8 flex min-h-6 items-center border-t border-[var(--orchard-line)] pt-4 text-sm">{error?<span className="text-red-300">{error}</span>:message?<span className="text-[var(--orchard-green)]">{message}</span>:null}</div>
    </form>:null}

    {tab==="account"?<section className="mt-8 max-w-2xl"><h2 className="text-2xl font-normal">{text.account}</h2><p className="mt-2 text-sm text-muted-foreground">{text.accountHelp}</p><div className="mt-6 divide-y divide-[var(--orchard-line)] border-y border-[var(--orchard-line)]"><Info label={text.name} value={account.name||text.notSet}/><Info label={text.email} value={account.email||text.notSet}/><Info label={text.userId} value={account.id||text.notSet}/></div></section>:null}
    {tab==="subscription"?<section className="mt-8 max-w-2xl"><h2 className="text-2xl font-normal">{text.subscription}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text.subscriptionHelp}</p><div className="mt-6 border-y border-[var(--orchard-line)]"><Info label={text.subscriptionState} value={text.notConnected}/></div></section>:null}
    {tab==="references"?<section className="mt-8 max-w-3xl"><h2 className="text-2xl font-normal">{text.references}</h2><p className="mt-2 text-sm text-muted-foreground">{text.referencesHelp}</p><div className="mt-6 divide-y divide-[var(--orchard-line)] border-y border-[var(--orchard-line)]"><Reference name="orchard_farm_settings" description={text.farmSettingsSource}/><Reference name="orchard_game_plans" description={text.gamePlanSource}/><Reference name="orchard_crop_library · orchard_cultivar_library" description={text.cropLibrarySource}/></div><div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4"/>{text.rls}</div></section>:null}
    <style jsx>{`.field{width:100%;height:39px;border:1px solid rgba(231,225,216,.16);border-radius:4px;background:#171614;padding:0 11px;color:inherit;outline:none}.field:focus{border-color:var(--orchard-green)}`}</style>
  </main></AppLayout>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[12px] text-[#d2ccc3]">{label}</span>{children}</label>}
function ReadField({label,value}:{label:string;value:string}){return <div><span className="mb-1.5 block text-[12px] text-[#d2ccc3]">{label}</span><div className="flex h-[39px] items-center rounded border border-[var(--orchard-line)] bg-[#171614] px-3 text-sm text-[#b9b0a4]">{value}</div></div>}
function Choice({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button type="button" onClick={onClick} className={`flex h-10 items-center gap-3 rounded border px-3 text-left text-sm ${active?"border-[var(--orchard-green)] bg-[var(--orchard-green-soft)]":"border-[var(--orchard-line)] bg-[#171614]"}`}><span className={`h-4 w-4 rounded-full border ${active?"border-[var(--orchard-green)] bg-[var(--orchard-green)] shadow-[inset_0_0_0_3px_#171614]":"border-[#6e675e]"}`}/>{label}</button>}
function Info({label,value}:{label:string;value:string}){return <div className="grid grid-cols-[180px_1fr] gap-4 py-4 text-sm"><span className="text-muted-foreground">{label}</span><span className="break-all">{value}</span></div>}
function Reference({name,description}:{name:string;description:string}){return <div className="py-4"><p className="font-mono text-sm text-[var(--orchard-green)]">{name}</p><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>}
