"use client"

import { FormEvent, useEffect, useMemo, useState } from "react"
import { Save, ShieldCheck } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Settings={
 id:string; farm_key:string; farm_name:string; country_code:string; currency:string; farm_address:string|null; latitude:number|null; longitude:number|null;
 measurement_system:"metric"|"imperial"; temperature_unit:"celsius"|"fahrenheit"; planting_amount_unit:"bed"|"bed_meter";
 standard_bed_width_cm:number|string; standard_bed_length_m:number|string; standard_path_width_cm:number|string;
 last_hard_frost_md:string|null; last_light_frost_md:string|null; first_light_frost_md:string|null; first_hard_frost_md:string|null; frost_source:string|null; updated_at:string
}
type Plan={id:string;name:string;season:string|null;start_date:string|null;end_date:string|null;status:string}

const copy={
 en:{eyebrow:"Orchard · Settings",title:"Farm settings",description:"Canonical operating defaults for Black Swan Orchard. These settings guide new planning and map objects; they never rewrite existing beds, allocations or observed field records.",farm:"Farm info",farmName:"Farm name",country:"Country",currency:"Currency",address:"Farm address",latitude:"Latitude",longitude:"Longitude",season:"Season",seasonNote:"Season dates come from the selected Game Plan and are read-only here.",measurement:"Measurement system",metric:"Metric",imperial:"Imperial",temperature:"Temperature unit",celsius:"Celsius",fahrenheit:"Fahrenheit",planting:"Planting amount",bed:"Bed",bedMeter:"Bed meter",dimensions:"Standard bed dimensions",bedWidth:"Bed width",bedLength:"Bed length",pathWidth:"Path width",dimensionsNote:"Current Black Swan physical map uses 10 m beds × 76 cm width with 40 cm paths. Changing these defaults affects newly created blocks only.",frost:"Frost dates",lastHard:"Last hard frost",lastLight:"Last light frost",firstLight:"First light frost",firstHard:"First hard frost",frostNote:"29/08 and 24/09 are retained as account-reference values observed in the authenticated Heirloom setup. Future frost dates remain blank until Black Swan has its own canonical weather source.",save:"Save settings",saved:"Settings saved",error:"Could not save farm settings.",loading:"Loading farm settings…",source:"Canonical source",sourceText:"orchard_farm_settings under Orchard RLS"},
 es:{eyebrow:"Huerto · Configuración",title:"Configuración de la granja",description:"Valores operativos canónicos de Black Swan Orchard. Estas preferencias guían nueva planificación y nuevos objetos del mapa; nunca reescriben camas, asignaciones ni evidencia de terreno existentes.",farm:"Información de la granja",farmName:"Nombre de la granja",country:"País",currency:"Moneda",address:"Dirección",latitude:"Latitud",longitude:"Longitud",season:"Temporada",seasonNote:"Las fechas de temporada vienen del Game Plan seleccionado y son de sólo lectura aquí.",measurement:"Sistema de medición",metric:"Métrico",imperial:"Imperial",temperature:"Unidad de temperatura",celsius:"Celsius",fahrenheit:"Fahrenheit",planting:"Cantidad de plantación",bed:"Cama",bedMeter:"Metro de cama",dimensions:"Dimensiones estándar de cama",bedWidth:"Ancho de cama",bedLength:"Largo de cama",pathWidth:"Ancho de pasillo",dimensionsNote:"El mapa físico actual de Black Swan usa camas de 10 m × 76 cm con pasillos de 40 cm. Cambiar estos valores afecta sólo bloques nuevos.",frost:"Fechas de heladas",lastHard:"Última helada fuerte",lastLight:"Última helada ligera",firstLight:"Primera helada ligera",firstHard:"Primera helada fuerte",frostNote:"29/08 y 24/09 se conservan como valores de referencia observados en la cuenta autenticada de Heirloom. Las fechas futuras quedan vacías hasta tener una fuente meteorológica canónica propia de Black Swan.",save:"Guardar configuración",saved:"Configuración guardada",error:"No fue posible guardar la configuración.",loading:"Cargando configuración…",source:"Fuente canónica",sourceText:"orchard_farm_settings bajo RLS de Huerto"},
 de:{eyebrow:"Orchard · Einstellungen",title:"Hofeinstellungen",description:"Kanonische Betriebsstandards für Black Swan Orchard. Sie gelten für neue Planung und neue Kartenobjekte und überschreiben keine bestehenden Beete, Belegungen oder Felddaten.",farm:"Hofdaten",farmName:"Hofname",country:"Land",currency:"Währung",address:"Hofadresse",latitude:"Breitengrad",longitude:"Längengrad",season:"Saison",seasonNote:"Saisondaten stammen aus dem gewählten Game Plan und sind hier schreibgeschützt.",measurement:"Maßsystem",metric:"Metrisch",imperial:"Imperial",temperature:"Temperatureinheit",celsius:"Celsius",fahrenheit:"Fahrenheit",planting:"Pflanzmenge",bed:"Beet",bedMeter:"Beetmeter",dimensions:"Standard-Beetmaße",bedWidth:"Beetbreite",bedLength:"Beetlänge",pathWidth:"Wegbreite",dimensionsNote:"Die aktuelle physische Black-Swan-Karte nutzt 10-m-Beete × 76 cm mit 40-cm-Wegen. Änderungen gelten nur für neue Blöcke.",frost:"Frostdaten",lastHard:"Letzter harter Frost",lastLight:"Letzter leichter Frost",firstLight:"Erster leichter Frost",firstHard:"Erster harter Frost",frostNote:"29/08 und 24/09 bleiben als beobachtete Referenzwerte aus dem authentifizierten Heirloom-Konto erhalten. Zukünftige Frostdaten bleiben leer, bis Black Swan eine eigene kanonische Wetterquelle hat.",save:"Einstellungen speichern",saved:"Einstellungen gespeichert",error:"Hofeinstellungen konnten nicht gespeichert werden.",loading:"Hofeinstellungen werden geladen…",source:"Kanonische Quelle",sourceText:"orchard_farm_settings unter Orchard-RLS"}
} as const

const blank:Settings={id:"",farm_key:"black_swan_orchard",farm_name:"Black Swan Orchard",country_code:"CL",currency:"CLP",farm_address:"",latitude:null,longitude:null,measurement_system:"metric",temperature_unit:"celsius",planting_amount_unit:"bed_meter",standard_bed_width_cm:76,standard_bed_length_m:10,standard_path_width_cm:40,last_hard_frost_md:null,last_light_frost_md:null,first_light_frost_md:null,first_hard_frost_md:null,frost_source:null,updated_at:""}

export default function OrchardSettingsPage(){
 const {language}=useLanguage();const lang:Locale=language;const text=copy[lang];const supabase=useMemo(()=>createBrowserClient(),[])
 const [settings,setSettings]=useState<Settings>(blank);const [plans,setPlans]=useState<Plan[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let live=true;void Promise.all([
  supabase.from("orchard_farm_settings").select("*").eq("farm_key","black_swan_orchard").single(),
  supabase.from("orchard_game_plans").select("id,name,season,start_date,end_date,status").order("start_date",{ascending:false})
 ]).then(([s,p])=>{if(!live)return;if(s.error){setError(s.error.message)}else setSettings(s.data as Settings);setPlans((p.data??[]) as Plan[]);setLoading(false)});return()=>{live=false}},[supabase])
 const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null
 const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const update=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(current=>({...current,[key]:value}))
 const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setMessage(null);setError(null);const payload={farm_name:settings.farm_name,country_code:settings.country_code,currency:settings.currency,farm_address:settings.farm_address||null,latitude:settings.latitude==null?null:Number(settings.latitude),longitude:settings.longitude==null?null:Number(settings.longitude),measurement_system:settings.measurement_system,temperature_unit:settings.temperature_unit,planting_amount_unit:settings.planting_amount_unit,standard_bed_width_cm:Number(settings.standard_bed_width_cm),standard_bed_length_m:Number(settings.standard_bed_length_m),standard_path_width_cm:Number(settings.standard_path_width_cm),last_hard_frost_md:settings.last_hard_frost_md||null,last_light_frost_md:settings.last_light_frost_md||null,first_light_frost_md:settings.first_light_frost_md||null,first_hard_frost_md:settings.first_hard_frost_md||null};const result=await supabase.from("orchard_farm_settings").update(payload).eq("id",settings.id).select("*").single();if(result.error)setError(text.error);else{setSettings(result.data as Settings);setMessage(text.saved)}setSaving(false)}
 if(loading)return <AppLayout><OrchardNavigation/><main className="p-8 text-sm text-muted-foreground">{text.loading}</main></AppLayout>
 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1180px] px-4 pb-20 pt-7 sm:px-6 lg:px-8">
  <header className="mb-7 border-b border-[var(--orchard-line)] pb-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--orchard-green)]">{text.eyebrow}</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-4xl font-normal sm:text-5xl">{text.title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">{text.description}</p></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4"/><span>{text.source}: {text.sourceText}</span></div></div></header>
  <form onSubmit={save} className="space-y-8">
   <section><h2 className="mb-4 text-2xl font-normal">{text.farm}</h2><div className="grid gap-4 border-y border-[var(--bs-divider-subtle)] py-5 md:grid-cols-2"><Field label={text.farmName}><input value={settings.farm_name} onChange={e=>update("farm_name",e.target.value)} className="input"/></Field><Field label={text.country}><input value={settings.country_code} onChange={e=>update("country_code",e.target.value.toUpperCase())} maxLength={2} className="input"/></Field><Field label={text.currency}><input value={settings.currency} onChange={e=>update("currency",e.target.value.toUpperCase())} maxLength={3} className="input"/></Field><Field label={text.address}><input value={settings.farm_address??""} onChange={e=>update("farm_address",e.target.value)} className="input"/></Field><Field label={text.latitude}><input type="number" step="any" value={settings.latitude??""} onChange={e=>update("latitude",e.target.value===""?null:Number(e.target.value))} className="input"/></Field><Field label={text.longitude}><input type="number" step="any" value={settings.longitude??""} onChange={e=>update("longitude",e.target.value===""?null:Number(e.target.value))} className="input"/></Field></div></section>
   <section><h2 className="mb-4 text-2xl font-normal">{text.season}</h2><div className="border-y border-[var(--bs-divider-subtle)] py-5"><div className="grid gap-4 sm:grid-cols-3"><Read label="Game Plan" value={plan?.name??"—"}/><Read label={text.season} value={plan?.season??"—"}/><Read label="Dates" value={plan?.start_date&&plan?.end_date?`${plan.start_date} → ${plan.end_date}`:"—"}/></div><p className="mt-4 text-xs leading-5 text-muted-foreground">{text.seasonNote}</p></div></section>
   <section className="grid gap-8 lg:grid-cols-3"><Choice title={text.measurement} value={settings.measurement_system} options={[["metric",text.metric],["imperial",text.imperial]]} onChange={value=>update("measurement_system",value as Settings["measurement_system"])}/><Choice title={text.temperature} value={settings.temperature_unit} options={[["celsius",text.celsius],["fahrenheit",text.fahrenheit]]} onChange={value=>update("temperature_unit",value as Settings["temperature_unit"])}/><Choice title={text.planting} value={settings.planting_amount_unit} options={[["bed",text.bed],["bed_meter",text.bedMeter]]} onChange={value=>update("planting_amount_unit",value as Settings["planting_amount_unit"])}/></section>
   <section><h2 className="mb-4 text-2xl font-normal">{text.dimensions}</h2><div className="grid gap-4 border-y border-[var(--bs-divider-subtle)] py-5 sm:grid-cols-3"><Field label={`${text.bedWidth} (cm)`}><input type="number" min="1" step="0.1" value={settings.standard_bed_width_cm} onChange={e=>update("standard_bed_width_cm",e.target.value)} className="input"/></Field><Field label={`${text.bedLength} (m)`}><input type="number" min="1" step="0.1" value={settings.standard_bed_length_m} onChange={e=>update("standard_bed_length_m",e.target.value)} className="input"/></Field><Field label={`${text.pathWidth} (cm)`}><input type="number" min="0" step="0.1" value={settings.standard_path_width_cm} onChange={e=>update("standard_path_width_cm",e.target.value)} className="input"/></Field><p className="sm:col-span-3 text-xs leading-5 text-muted-foreground">{text.dimensionsNote}</p></div></section>
   <section><h2 className="mb-4 text-2xl font-normal">{text.frost}</h2><div className="grid gap-4 border-y border-[var(--bs-divider-subtle)] py-5 sm:grid-cols-2 lg:grid-cols-4"><Field label={text.lastHard}><input placeholder="DD/MM" value={settings.last_hard_frost_md??""} onChange={e=>update("last_hard_frost_md",e.target.value||null)} className="input"/></Field><Field label={text.lastLight}><input placeholder="DD/MM" value={settings.last_light_frost_md??""} onChange={e=>update("last_light_frost_md",e.target.value||null)} className="input"/></Field><Field label={text.firstLight}><input placeholder="DD/MM" value={settings.first_light_frost_md??""} onChange={e=>update("first_light_frost_md",e.target.value||null)} className="input"/></Field><Field label={text.firstHard}><input placeholder="DD/MM" value={settings.first_hard_frost_md??""} onChange={e=>update("first_hard_frost_md",e.target.value||null)} className="input"/></Field><p className="sm:col-span-2 lg:col-span-4 text-xs leading-5 text-muted-foreground">{text.frostNote}</p></div></section>
   <div className="flex items-center justify-between gap-4 border-t border-[var(--orchard-line)] pt-5"><div className="text-sm">{error?<span className="text-red-300">{error}</span>:message?<span className="text-[var(--orchard-green)]">{message}</span>:null}</div><button type="submit" disabled={saving} className="inline-flex min-h-11 items-center gap-2 bg-[var(--orchard-green)] px-5 text-sm font-medium text-[#10130f] disabled:opacity-50"><Save className="h-4 w-4"/>{saving?"…":text.save}</button></div>
  </form>
  <style jsx>{`.input{width:100%;height:44px;border:1px solid var(--bs-divider-subtle);background:var(--bs-surface-primary);padding:0 12px;color:inherit;outline:none}.input:focus{border-color:var(--orchard-green)}`}</style>
 </main></AppLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs uppercase tracking-[.12em] text-muted-foreground">{label}</span>{children}</label>}
function Read({label,value}:{label:string;value:string}){return <div><p className="text-xs uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-2 text-sm">{value}</p></div>}
function Choice({title,value,options,onChange}:{title:string;value:string;options:[string,string][];onChange:(value:string)=>void}){return <section><h2 className="mb-3 text-lg font-normal">{title}</h2><div className="border-y border-[var(--bs-divider-subtle)] py-3">{options.map(([key,label])=><label key={key} className="flex min-h-11 cursor-pointer items-center gap-3"><input type="radio" checked={value===key} onChange={()=>onChange(key)}/><span className="text-sm">{label}</span></label>)}</div></section>}
