"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { Activity, BadgeDollarSign, BookOpenText, Leaf, RefreshCw, ShieldAlert, Sprout } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Succession={id:string;crop_cycle_id:string;planned_sow_date:string;planned_first_harvest_date:string|null;planned_last_harvest_date:string|null;status:string}
type Cycle={id:string;crop_name:string;variety:string|null}
type Crop={id:string;crop_succession_id:string|null;crop_name:string;variety:string|null;status:string;actual_yield:number|null;estimated_yield:number|null;yield_unit:string|null}
type Harvest={crop_succession_id:string|null;crop_id:string;harvest_date:string;quantity_harvested:number|null;harvest_unit:string|null;total_market_value:number|null;market_value_per_unit:number|null}
type Health={id:string;crop_id:string;severity_level:string|null;treatment_effectiveness:string|null;observation_date:string}
type Note={id:string;note_type:string;observed_at:string}
type Care={id:string;activity_date:string;hours_spent:number|null}
type Commitment={id:string;status:string;quantity:number;price_per_unit:number|null;currency:string}

const money=(value:number,currency="CLP")=>new Intl.NumberFormat("es-CL",{style:"currency",currency,maximumFractionDigits:0}).format(value)
const cropPhoto=(name:string)=>{const n=name.toLowerCase();if(n.includes("tomat"))return "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=1800&q=92";if(n.includes("lettuce")||n.includes("lechuga"))return "https://images.unsplash.com/photo-1622205313162-be1d5712a43f?auto=format&fit=crop&w=1800&q=92";if(n.includes("pepper")||n.includes("piment"))return "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=1800&q=92";if(n.includes("carrot")||n.includes("zanah"))return "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=1800&q=92";return "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1800&q=92"}

export default function OrchardSeasonSummaryPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const es=language==="es"
 const [successions,setSuccessions]=useState<Succession[]>([]);const [cycles,setCycles]=useState<Cycle[]>([]);const [crops,setCrops]=useState<Crop[]>([]);const [harvests,setHarvests]=useState<Harvest[]>([]);const [health,setHealth]=useState<Health[]>([]);const [notes,setNotes]=useState<Note[]>([]);const [care,setCare]=useState<Care[]>([]);const [commitments,setCommitments]=useState<Commitment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);const [s,cy,c,h,he,n,ca,cm]=await Promise.all([supabase.from("orchard_crop_successions").select("id,crop_cycle_id,planned_sow_date,planned_first_harvest_date,planned_last_harvest_date,status"),supabase.from("orchard_crop_cycles").select("id,crop_name,variety"),supabase.from("orchard_crops").select("id,crop_succession_id,crop_name,variety,status,actual_yield,estimated_yield,yield_unit"),supabase.from("orchard_harvest_records").select("crop_succession_id,crop_id,harvest_date,quantity_harvested,harvest_unit,total_market_value,market_value_per_unit"),supabase.from("orchard_pest_logs").select("id,crop_id,severity_level,treatment_effectiveness,observation_date"),supabase.from("orchard_notes").select("id,note_type,observed_at"),supabase.from("orchard_care_logs").select("id,activity_date,hours_spent"),supabase.from("orchard_sales_commitments").select("id,status,quantity,price_per_unit,currency")]);const e=s.error??cy.error??c.error??h.error??he.error??n.error??ca.error??cm.error;if(e)setError(e.message);else{setSuccessions((s.data??[]) as Succession[]);setCycles((cy.data??[]) as Cycle[]);setCrops((c.data??[]) as Crop[]);setHarvests((h.data??[]) as Harvest[]);setHealth((he.data??[]) as Health[]);setNotes((n.data??[]) as Note[]);setCare((ca.data??[]) as Care[]);setCommitments((cm.data??[]) as Commitment[])}setLoading(false)},[supabase]);useEffect(()=>{void load()},[load])
 const cycleById=useMemo(()=>new Map(cycles.map(c=>[c.id,c])),[cycles]);const cropById=useMemo(()=>new Map(crops.map(c=>[c.id,c])),[crops]);
 const started=successions.filter(s=>s.status!=="planned"&&s.status!=="cancelled").length;const completed=successions.filter(s=>s.status==="completed").length;const harvestValue=harvests.reduce((sum,h)=>sum+Number(h.total_market_value??((h.quantity_harvested??0)*(h.market_value_per_unit??0))),0);const careHours=care.reduce((sum,c)=>sum+Number(c.hours_spent??0),0);const seriousHealth=health.filter(h=>["high","critical"].includes((h.severity_level??"").toLowerCase())&&!['effective','very_effective'].includes((h.treatment_effectiveness??"").toLowerCase())).length;const committedValue=commitments.filter(c=>c.status!=="cancelled").reduce((sum,c)=>sum+Number(c.quantity||0)*Number(c.price_per_unit??0),0)
 const dates=[...successions.map(s=>s.planned_sow_date),...harvests.map(h=>h.harvest_date)].filter(Boolean).sort();const seasonStart=dates[0]??null;const seasonEnd=dates.at(-1)??null
 const cropRollup=useMemo(()=>{const map=new Map<string,{crop:string;variety:string|null;successions:number;harvest:number;units:Set<string>;value:number;health:number}>();cycles.forEach(c=>map.set(c.id,{crop:c.crop_name,variety:c.variety,successions:0,harvest:0,units:new Set(),value:0,health:0}));successions.forEach(s=>{const r=map.get(s.crop_cycle_id);if(r)r.successions+=1});harvests.forEach(h=>{let cycleId:string|undefined;if(h.crop_succession_id)cycleId=successions.find(s=>s.id===h.crop_succession_id)?.crop_cycle_id;if(!cycleId){const crop=cropById.get(h.crop_id);cycleId=crop?.crop_succession_id?successions.find(s=>s.id===crop.crop_succession_id)?.crop_cycle_id:undefined}const r=cycleId?map.get(cycleId):undefined;if(r){r.harvest+=Number(h.quantity_harvested??0);if(h.harvest_unit)r.units.add(h.harvest_unit);r.value+=Number(h.total_market_value??((h.quantity_harvested??0)*(h.market_value_per_unit??0)))}});health.forEach(he=>{const crop=cropById.get(he.crop_id);const cycleId=crop?.crop_succession_id?successions.find(s=>s.id===crop.crop_succession_id)?.crop_cycle_id:undefined;const r=cycleId?map.get(cycleId):undefined;if(r&&["high","critical"].includes((he.severity_level??"").toLowerCase()))r.health+=1});return [...map.values()].filter(r=>r.successions>0||r.harvest>0).sort((a,b)=>b.value-a.value||b.harvest-a.harvest)},[cycles,successions,harvests,health,cropById])
 return <AppLayout><PageHeader title={es?"Resumen de Temporada":"Season Summary"} description={es?"Una lectura ejecutiva de planificación, ejecución, cosecha, valor, incidentes y aprendizaje usando los registros canónicos de Orchard.":"An executive read of planning, execution, harvest, value, incidents and learning from canonical Orchard records."} actions={<Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>{es?"Actualizar":"Refresh"}</Button>}/><OrchardNavigation/><div className="space-y-6 p-4 pb-24 sm:p-8">{error&&<Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
 <section className="relative min-h-[320px] overflow-hidden border border-white/10 bg-[#111711] p-6 md:p-8"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,12,9,.96)_0%,rgba(8,12,9,.82)_48%,rgba(8,12,9,.2)_100%),url('https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=92')] bg-cover bg-center [filter:none] [opacity:1]"/><div className="relative z-10 max-w-3xl"><p className="text-xs uppercase tracking-[.2em] text-emerald-200/70">{es?"Cierre operacional":"Operational close"}</p><h2 className="mt-3 text-3xl md:text-5xl">{seasonStart&&seasonEnd?`${seasonStart} → ${seasonEnd}`:(es?"Temporada en curso":"Season in progress")}</h2><p className="mt-4 max-w-2xl text-sm text-white/70">{es?"Plan, terreno, cosecha y aprendizaje reunidos en una sola lectura. Sin scores inventados: cada señal proviene de registros existentes.":"Plan, field execution, harvest and learning in one view. No invented scores: every signal comes from existing records."}</p><div className="mt-6 grid max-w-2xl grid-cols-2 gap-3 md:grid-cols-4"><HeroMetric label={es?"Iniciadas":"Started"} value={`${started}/${successions.length}`}/><HeroMetric label={es?"Completadas":"Completed"} value={String(completed)}/><HeroMetric label={es?"Valor cosecha":"Harvest value"} value={money(harvestValue)}/><HeroMetric label={es?"Horas cuidado":"Care hours"} value={careHours.toFixed(1)}/></div></div></section>
 <div className="grid gap-4 md:grid-cols-4"><Metric icon={BadgeDollarSign} label={es?"Demanda comprometida":"Committed demand"} value={money(committedValue)}/><Metric icon={ShieldAlert} label={es?"Incidentes serios abiertos":"Serious health follow-up"} value={String(seriousHealth)}/><Metric icon={BookOpenText} label={es?"Notas capturadas":"Notes captured"} value={String(notes.length)}/><Metric icon={Leaf} label={es?"Pases de cosecha":"Harvest passes"} value={String(harvests.length)}/></div>
 <Card><CardHeader><CardTitle>{es?"Historia de la temporada por cultivo":"Season story by crop"}</CardTitle><CardDescription>{es?"Cobertura de sucesiones, volumen cosechado, valor registrado e incidentes sanitarios altos/críticos.":"Succession coverage, harvested volume, recorded value and high/critical health incidents."}</CardDescription></CardHeader><CardContent>{cropRollup.length===0?<p className="text-sm text-muted-foreground">{es?"Aún no hay datos suficientes.":"Not enough season data yet."}</p>:<div className="grid gap-4 lg:grid-cols-2">{cropRollup.map((r,index)=><div key={`${r.crop}-${r.variety??""}-${index}`} className="overflow-hidden border border-white/10 bg-[var(--bs-surface-secondary)]"><div className="relative h-40"><img src={cropPhoto(r.crop)} alt="" className="h-full w-full object-cover [filter:none] [opacity:1]"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(8,12,9,.08),rgba(8,12,9,.88))]"/><div className="absolute inset-x-0 bottom-0 p-4"><p className="text-xl font-semibold text-white">{r.crop}{r.variety?` · ${r.variety}`:""}</p><p className="text-xs text-white/60">{r.successions} {es?"sucesiones":"successions"}</p></div></div><div className="grid grid-cols-3 gap-3 p-4 text-sm"><Datum label={es?"Cosecha":"Harvest"} value={r.units.size===1?`${Number(r.harvest.toFixed(2))} ${[...r.units][0]}`:r.harvest?`${Number(r.harvest.toFixed(2))} · ${es?"unidades mixtas":"mixed units"}`:"—"}/><Datum label={es?"Valor":"Value"} value={money(r.value)}/><Datum label={es?"Incidentes":"Incidents"} value={String(r.health)}/></div></div>)}</div>}</CardContent></Card>
 <div className="grid gap-4 md:grid-cols-3"><Action href={`/${language}/orchard/traceability`} icon={Sprout} title={es?"Trazabilidad completa":"Full traceability"} text={es?"Seguir semilla/sucesión → cultivo → cuidado → salud → cosecha.":"Follow succession → crop → care → health → harvest."}/><Action href={`/${language}/orchard/reports`} icon={BookOpenText} title={es?"Paquete ejecutivo":"Executive reports"} text={es?"Entrar al hub de reportes y vistas de cierre.":"Open the reporting and closeout hub."}/><Action href={`/${language}/orchard/decisions`} icon={Activity} title={es?"Decisiones abiertas":"Open decisions"} text={es?"Resolver excepciones antes de cerrar la temporada.":"Resolve operational exceptions before closeout."}/></div>
 </div></AppLayout>}
function HeroMetric({label,value}:{label:string;value:string}){return <div className="border border-white/15 bg-black/20 p-3"><p className="text-[10px] uppercase tracking-wider text-white/50">{label}</p><p className="mt-1 text-lg font-semibold text-white">{value}</p></div>}
function Metric({icon:Icon,label,value}:{icon:typeof Leaf;label:string;value:string}){return <Card><CardContent className="flex items-center gap-3 p-4"><div className="bg-muted p-2"><Icon className="h-4 w-4"/></div><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div></CardContent></Card>}
function Datum({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
function Action({href,icon:Icon,title,text}:{href:string;icon:typeof Leaf;title:string;text:string}){return <Link href={href} className="block border border-white/10 bg-[var(--bs-surface-secondary)] p-5 transition hover:bg-[var(--bs-surface-elevated)]"><Icon className="h-5 w-5"/><p className="mt-4 font-semibold">{title}</p><p className="mt-1 text-sm text-muted-foreground">{text}</p></Link>}
