"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { Activity, BadgeDollarSign, BookOpenText, Leaf, RefreshCw, ShieldAlert, Sprout } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"
import { ALL_GAME_PLANS, gamePlanScopeLabel, resolveRequestedGamePlanId, resolveSelectedGamePlan, scopeBySuccessionId, scopeGamePlanGraph, syncGamePlanQuery, withGamePlanQuery } from "@/lib/orchard/game-plan-scope"

type GamePlan={id:string;name:string;season:string|null;start_date:string;end_date:string;status:string}
type Succession={id:string;crop_cycle_id:string;planned_sow_date:string;planned_first_harvest_date:string|null;planned_last_harvest_date:string|null;status:string}
type Cycle={id:string;game_plan_id:string;crop_name:string;variety:string|null}
type Crop={id:string;crop_succession_id:string|null;crop_name:string;variety:string|null;status:string;actual_yield:number|null;estimated_yield:number|null;yield_unit:string|null}
type Harvest={crop_succession_id:string|null;crop_id:string;harvest_date:string;quantity_harvested:number|null;harvest_unit:string|null;total_market_value:number|null;market_value_per_unit:number|null}
type Health={id:string;crop_id:string;severity_level:string|null;treatment_effectiveness:string|null;observation_date:string}
type Note={id:string;crop_id:string|null;crop_succession_id:string|null;note_type:string;observed_at:string}
type Care={id:string;crop_id:string;activity_date:string;hours_spent:number|null}
type Commitment={id:string;crop_succession_id:string|null;status:string;quantity:number;price_per_unit:number|null;currency:string}

const locales={en:"en-US",es:"es-CL",de:"de-DE"} as const
const copy={
 en:{title:"Season Summary",all:"All records",refresh:"Refresh",globalDescription:"Global record view. Select a Game Plan to turn it into a bounded, traceable season closeout.",scopedDescription:(scope:string)=>`Closeout bounded to Game Plan ${scope}, propagated through cycles, successions, crops and related operational records.`,closeout:"Game Plan closeout",coverage:"Operational coverage",noRange:"No record range",scopedHero:(scope:string)=>`Scope: ${scope}. Only plan cycles, their successions, linked crops and dependent records are included. Harvest value remains currencyless because the harvest schema does not store currency.`,globalHero:"This range is derived from all loaded records and does not represent a formal season until a Game Plan is selected.",started:"Started",completed:"Completed",harvestValue:"Recorded harvest value",careHours:"Care hours",demand:"Demand by currency",highCritical:"High/critical observations",notes:"Notes captured",harvestPasses:"Harvest passes",seasonStory:"Season story by crop",globalStory:"Crop story across loaded records",storyHelp:"Succession coverage, harvested volume, recorded numeric value and high/critical health observations. Value has no currency symbol because harvest records do not store currency.",empty:"Not enough data for this scope yet.",successions:"successions",harvest:"Harvest",mixedUnits:"mixed units",recordedValue:"Recorded value",traceability:"Full traceability",traceabilityHelp:"Follow succession → crop → care → health → harvest.",reports:"Executive reports",reportsHelp:"Open reports with the same Game Plan scope.",review:"Operational review",reviewHelp:"Review factual operational exceptions before closeout.",currencyUnspecified:"currency unspecified"},
 es:{title:"Resumen de Temporada",all:"Todos los registros",refresh:"Actualizar",globalDescription:"Vista global de registros. Selecciona un Game Plan para convertirla en un cierre de temporada acotado y trazable.",scopedDescription:(scope:string)=>`Cierre acotado al Game Plan ${scope}, propagado por ciclos, sucesiones, cultivos y registros operacionales relacionados.`,closeout:"Cierre por Game Plan",coverage:"Cobertura operacional",noRange:"Sin rango de registros",scopedHero:(scope:string)=>`Alcance: ${scope}. Solo se incluyen ciclos del plan, sus sucesiones, cultivos enlazados y registros dependientes. El valor de cosecha se mantiene sin moneda porque el esquema de cosecha no almacena moneda.`,globalHero:"Este rango se deriva de todos los registros cargados y no representa una temporada formal hasta seleccionar un Game Plan.",started:"Iniciadas",completed:"Completadas",harvestValue:"Valor cosecha registrado",careHours:"Horas de cuidado",demand:"Demanda por moneda",highCritical:"Observaciones altas/críticas",notes:"Notas capturadas",harvestPasses:"Pases de cosecha",seasonStory:"Historia de la temporada por cultivo",globalStory:"Historia por cultivo en los registros cargados",storyHelp:"Cobertura de sucesiones, volumen cosechado, valor numérico registrado y observaciones sanitarias altas/críticas. El valor no lleva símbolo monetario porque cosecha no guarda moneda.",empty:"Aún no hay datos suficientes para este alcance.",successions:"sucesiones",harvest:"Cosecha",mixedUnits:"unidades mixtas",recordedValue:"Valor registrado",traceability:"Trazabilidad completa",traceabilityHelp:"Seguir sucesión → cultivo → cuidado → salud → cosecha.",reports:"Paquete ejecutivo",reportsHelp:"Abrir reportes con el mismo alcance de Game Plan.",review:"Revisión operativa",reviewHelp:"Revisar excepciones factuales antes del cierre.",currencyUnspecified:"sin moneda"},
 de:{title:"Saisonübersicht",all:"Alle Datensätze",refresh:"Aktualisieren",globalDescription:"Globale Datensatzansicht. Wähle einen Game Plan, um daraus einen abgegrenzten, rückverfolgbaren Saisonabschluss zu machen.",scopedDescription:(scope:string)=>`Saisonabschluss für den Game Plan ${scope}, über Zyklen, Folgen, Kulturen und zugehörige Betriebsdaten hinweg.`,closeout:"Game-Plan-Abschluss",coverage:"Betriebliche Abdeckung",noRange:"Kein Datumsbereich",scopedHero:(scope:string)=>`Umfang: ${scope}. Enthalten sind nur Zyklen des Plans, deren Folgen, verknüpfte Kulturen und abhängige Datensätze. Der Erntewert bleibt ohne Währung, da das Ernteschema keine Währung speichert.`,globalHero:"Dieser Zeitraum wird aus allen geladenen Datensätzen abgeleitet und stellt erst nach Auswahl eines Game Plans eine formale Saison dar.",started:"Gestartet",completed:"Abgeschlossen",harvestValue:"Erfasster Erntewert",careHours:"Pflegestunden",demand:"Nachfrage nach Währung",highCritical:"Hohe/kritische Beobachtungen",notes:"Erfasste Notizen",harvestPasses:"Erntedurchgänge",seasonStory:"Saisonverlauf nach Kultur",globalStory:"Kulturverlauf in den geladenen Datensätzen",storyHelp:"Abdeckung der Folgen, Erntemenge, erfasster numerischer Wert und hohe/kritische Gesundheitsbeobachtungen. Der Wert hat kein Währungssymbol, da Erntedatensätze keine Währung speichern.",empty:"Für diesen Umfang liegen noch nicht genügend Daten vor.",successions:"Folgen",harvest:"Ernte",mixedUnits:"gemischte Einheiten",recordedValue:"Erfasster Wert",traceability:"Vollständige Rückverfolgbarkeit",traceabilityHelp:"Folge → Kultur → Pflege → Gesundheit → Ernte nachvollziehen.",reports:"Managementberichte",reportsHelp:"Berichte mit demselben Game-Plan-Umfang öffnen.",review:"Betriebliche Prüfung",reviewHelp:"Faktische betriebliche Ausnahmen vor dem Abschluss prüfen.",currencyUnspecified:"Währung nicht angegeben"},
} as const

const cropPhoto=(name:string)=>{const n=name.toLowerCase();if(n.includes("tomat"))return "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=1800&q=92";if(n.includes("lettuce")||n.includes("lechuga"))return "https://images.unsplash.com/photo-1622205313162-be1d5712a43f?auto=format&fit=crop&w=1800&q=92";if(n.includes("pepper")||n.includes("piment"))return "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=1800&q=92";if(n.includes("carrot")||n.includes("zanah"))return "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=1800&q=92";return "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1800&q=92"}

export default function OrchardSeasonSummaryPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const text=copy[language];const locale=locales[language]
 const number=useCallback((value:number)=>new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(value),[locale])
 const money=useCallback((value:number,currency:string)=>{try{return new Intl.NumberFormat(locale,{style:"currency",currency:currency||"CLP",maximumFractionDigits:0}).format(value)}catch{return `${currency||"?"} ${number(value)}`}},[locale,number])
 const [plans,setPlans]=useState<GamePlan[]>([]);const [selectedPlanId,setSelectedPlanId]=useState<string>(ALL_GAME_PLANS);const [successions,setSuccessions]=useState<Succession[]>([]);const [cycles,setCycles]=useState<Cycle[]>([]);const [crops,setCrops]=useState<Crop[]>([]);const [harvests,setHarvests]=useState<Harvest[]>([]);const [health,setHealth]=useState<Health[]>([]);const [notes,setNotes]=useState<Note[]>([]);const [care,setCare]=useState<Care[]>([]);const [commitments,setCommitments]=useState<Commitment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);const [gp,s,cy,c,h,he,n,ca,cm]=await Promise.all([supabase.from("orchard_game_plans").select("id,name,season,start_date,end_date,status").order("start_date",{ascending:false}),supabase.from("orchard_crop_successions").select("id,crop_cycle_id,planned_sow_date,planned_first_harvest_date,planned_last_harvest_date,status"),supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name,variety"),supabase.from("orchard_crops").select("id,crop_succession_id,crop_name,variety,status,actual_yield,estimated_yield,yield_unit"),supabase.from("orchard_harvest_records").select("crop_succession_id,crop_id,harvest_date,quantity_harvested,harvest_unit,total_market_value,market_value_per_unit"),supabase.from("orchard_pest_logs").select("id,crop_id,severity_level,treatment_effectiveness,observation_date"),supabase.from("orchard_notes").select("id,crop_id,crop_succession_id,note_type,observed_at"),supabase.from("orchard_care_logs").select("id,crop_id,activity_date,hours_spent"),supabase.from("orchard_sales_commitments").select("id,crop_succession_id,status,quantity,price_per_unit,currency")]);const e=gp.error??s.error??cy.error??c.error??h.error??he.error??n.error??ca.error??cm.error;if(e)setError(e.message);else{const planRows=(gp.data??[]) as GamePlan[];setPlans(planRows);setSuccessions((s.data??[]) as Succession[]);setCycles((cy.data??[]) as Cycle[]);setCrops((c.data??[]) as Crop[]);setHarvests((h.data??[]) as Harvest[]);setHealth((he.data??[]) as Health[]);setNotes((n.data??[]) as Note[]);setCare((ca.data??[]) as Care[]);setCommitments((cm.data??[]) as Commitment[]);if(typeof window!=="undefined")setSelectedPlanId(resolveRequestedGamePlanId(planRows,window.location.search))}setLoading(false)},[supabase]);useEffect(()=>{void load()},[load])
 const selectedPlan=resolveSelectedGamePlan(plans,selectedPlanId);const {scopedCycles,scopedSuccessions,successionIds}=useMemo(()=>scopeGamePlanGraph(cycles,successions,selectedPlanId),[cycles,successions,selectedPlanId])
 const scopedCrops=useMemo(()=>scopeBySuccessionId(crops,successionIds,selectedPlanId,c=>c.crop_succession_id),[crops,successionIds,selectedPlanId]);const cropIds=useMemo(()=>new Set(scopedCrops.map(c=>c.id)),[scopedCrops])
 const scopedHarvests=useMemo(()=>selectedPlanId===ALL_GAME_PLANS?harvests:harvests.filter(h=>(h.crop_succession_id&&successionIds.has(h.crop_succession_id))||cropIds.has(h.crop_id)),[harvests,successionIds,cropIds,selectedPlanId])
 const scopedHealth=useMemo(()=>selectedPlanId===ALL_GAME_PLANS?health:health.filter(h=>cropIds.has(h.crop_id)),[health,cropIds,selectedPlanId]);const scopedCare=useMemo(()=>selectedPlanId===ALL_GAME_PLANS?care:care.filter(c=>cropIds.has(c.crop_id)),[care,cropIds,selectedPlanId]);const scopedNotes=useMemo(()=>selectedPlanId===ALL_GAME_PLANS?notes:notes.filter(n=>(n.crop_id&&cropIds.has(n.crop_id))||(n.crop_succession_id&&successionIds.has(n.crop_succession_id))),[notes,cropIds,successionIds,selectedPlanId]);const scopedCommitments=useMemo(()=>scopeBySuccessionId(commitments,successionIds,selectedPlanId,c=>c.crop_succession_id),[commitments,successionIds,selectedPlanId])
 const cropById=useMemo(()=>new Map(scopedCrops.map(c=>[c.id,c])),[scopedCrops]);const successionById=useMemo(()=>new Map(scopedSuccessions.map(s=>[s.id,s])),[scopedSuccessions])
 const started=scopedSuccessions.filter(s=>s.status!=="planned"&&s.status!=="cancelled").length;const completed=scopedSuccessions.filter(s=>s.status==="completed").length;const harvestValue=scopedHarvests.reduce((sum,h)=>sum+Number(h.total_market_value??((h.quantity_harvested??0)*(h.market_value_per_unit??0))),0);const careHours=scopedCare.reduce((sum,c)=>sum+Number(c.hours_spent??0),0);const highCriticalHealth=scopedHealth.filter(h=>["high","critical"].includes((h.severity_level??"").toLowerCase())).length
 const committedByCurrency=useMemo(()=>{const map=new Map<string,number>();scopedCommitments.filter(c=>c.status!=="cancelled").forEach(c=>{const currency=(c.currency||"UNSPECIFIED").toUpperCase();map.set(currency,(map.get(currency)??0)+Number(c.quantity||0)*Number(c.price_per_unit??0))});return [...map.entries()].sort(([a],[b])=>a.localeCompare(b))},[scopedCommitments]);const committedLabel=committedByCurrency.length?committedByCurrency.map(([currency,value])=>currency==="UNSPECIFIED"?`${number(value)} ${text.currencyUnspecified}`:money(value,currency)).join(" · "):"—"
 const recordDates=[...scopedSuccessions.map(s=>s.planned_sow_date),...scopedHarvests.map(h=>h.harvest_date),...scopedHealth.map(h=>h.observation_date),...scopedCare.map(c=>c.activity_date)].filter(Boolean).sort();const coverageStart=selectedPlan?.start_date??recordDates[0]??null;const coverageEnd=selectedPlan?.end_date??recordDates.at(-1)??null
 const cropRollup=useMemo(()=>{const map=new Map<string,{crop:string;variety:string|null;successions:number;harvest:number;units:Set<string>;value:number;health:number}>();scopedCycles.forEach(c=>map.set(c.id,{crop:c.crop_name,variety:c.variety,successions:0,harvest:0,units:new Set(),value:0,health:0}));scopedSuccessions.forEach(s=>{const r=map.get(s.crop_cycle_id);if(r)r.successions+=1});scopedHarvests.forEach(h=>{let cycleId:string|undefined;if(h.crop_succession_id)cycleId=successionById.get(h.crop_succession_id)?.crop_cycle_id;if(!cycleId){const crop=cropById.get(h.crop_id);cycleId=crop?.crop_succession_id?successionById.get(crop.crop_succession_id)?.crop_cycle_id:undefined}const r=cycleId?map.get(cycleId):undefined;if(r){r.harvest+=Number(h.quantity_harvested??0);if(h.harvest_unit)r.units.add(h.harvest_unit);r.value+=Number(h.total_market_value??((h.quantity_harvested??0)*(h.market_value_per_unit??0)))}});scopedHealth.forEach(he=>{const crop=cropById.get(he.crop_id);const cycleId=crop?.crop_succession_id?successionById.get(crop.crop_succession_id)?.crop_cycle_id:undefined;const r=cycleId?map.get(cycleId):undefined;if(r&&["high","critical"].includes((he.severity_level??"").toLowerCase()))r.health+=1});return [...map.values()].filter(r=>r.successions>0||r.harvest>0).sort((a,b)=>b.harvest-a.harvest||a.crop.localeCompare(b.crop))},[scopedCycles,scopedSuccessions,scopedHarvests,scopedHealth,cropById,successionById])
 const scopeLabel=gamePlanScopeLabel(selectedPlan,text.all);const changePlan=(id:string)=>{setSelectedPlanId(id);syncGamePlanQuery(id)}
 return <AppLayout><PageHeader title={text.title} description={selectedPlan?text.scopedDescription(scopeLabel):text.globalDescription} actions={<div className="flex flex-wrap items-center gap-2"><Select value={selectedPlanId} onValueChange={changePlan}><SelectTrigger className="w-[250px]" aria-label="Game Plan"><SelectValue/></SelectTrigger><SelectContent><SelectItem value={ALL_GAME_PLANS}>{text.all}</SelectItem>{plans.map(plan=><SelectItem key={plan.id} value={plan.id}>{plan.name}{plan.season?` · ${plan.season}`:""}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>{text.refresh}</Button></div>}/><OrchardNavigation/><div className="space-y-6 p-4 pb-24 sm:p-8">{error&&<Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
 <section className="relative min-h-[320px] overflow-hidden border border-white/10 bg-[#111711] p-6 md:p-8"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,12,9,.96)_0%,rgba(8,12,9,.82)_48%,rgba(8,12,9,.2)_100%),url('https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=92')] bg-cover bg-center [filter:none] [opacity:1]"/><div className="relative z-10 max-w-3xl"><p className="text-xs uppercase tracking-[.2em] text-emerald-200/70">{selectedPlan?text.closeout:text.coverage}</p><h2 className="mt-3 text-3xl md:text-5xl">{coverageStart&&coverageEnd?`${coverageStart} → ${coverageEnd}`:text.noRange}</h2><p className="mt-4 max-w-2xl text-sm text-white/70">{selectedPlan?text.scopedHero(scopeLabel):text.globalHero}</p><div className="mt-6 grid max-w-2xl grid-cols-2 gap-3 md:grid-cols-4"><HeroMetric label={text.started} value={`${started}/${scopedSuccessions.length}`}/><HeroMetric label={text.completed} value={String(completed)}/><HeroMetric label={text.harvestValue} value={number(harvestValue)}/><HeroMetric label={text.careHours} value={careHours.toFixed(1)}/></div></div></section>
 <div className="grid gap-4 md:grid-cols-4"><Metric icon={BadgeDollarSign} label={text.demand} value={committedLabel}/><Metric icon={ShieldAlert} label={text.highCritical} value={String(highCriticalHealth)}/><Metric icon={BookOpenText} label={text.notes} value={String(scopedNotes.length)}/><Metric icon={Leaf} label={text.harvestPasses} value={String(scopedHarvests.length)}/></div>
 <Card><CardHeader><CardTitle>{selectedPlan?text.seasonStory:text.globalStory}</CardTitle><CardDescription>{text.storyHelp}</CardDescription></CardHeader><CardContent>{cropRollup.length===0?<p className="text-sm text-muted-foreground">{text.empty}</p>:<div className="grid gap-4 lg:grid-cols-2">{cropRollup.map((r,index)=><div key={`${r.crop}-${r.variety??""}-${index}`} className="overflow-hidden border border-white/10 bg-[var(--bs-surface-secondary)]"><div className="relative h-40"><img src={cropPhoto(r.crop)} alt="" className="h-full w-full object-cover [filter:none] [opacity:1]"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(8,12,9,.08),rgba(8,12,9,.88))]"/><div className="absolute inset-x-0 bottom-0 p-4"><p className="text-xl font-semibold text-white">{r.crop}{r.variety?` · ${r.variety}`:""}</p><p className="text-xs text-white/60">{r.successions} {text.successions}</p></div></div><div className="grid grid-cols-3 gap-3 p-4 text-sm"><Datum label={text.harvest} value={r.units.size===1?`${Number(r.harvest.toFixed(2))} ${[...r.units][0]}`:r.harvest?`${Number(r.harvest.toFixed(2))} · ${text.mixedUnits}`:"—"}/><Datum label={text.recordedValue} value={number(r.value)}/><Datum label={text.highCritical} value={String(r.health)}/></div></div>)}</div>}</CardContent></Card>
 <div className="grid gap-4 md:grid-cols-3"><Action href={withGamePlanQuery(`/${language}/orchard/traceability`,selectedPlanId)} icon={Sprout} title={text.traceability} text={text.traceabilityHelp}/><Action href={withGamePlanQuery(`/${language}/orchard/reports`,selectedPlanId)} icon={BookOpenText} title={text.reports} text={text.reportsHelp}/><Action href={`/${language}/orchard/decisions`} icon={Activity} title={text.review} text={text.reviewHelp}/></div>
 </div></AppLayout>}

function HeroMetric({label,value}:{label:string;value:string}){return <div className="border border-white/15 bg-black/20 p-3"><p className="text-[10px] uppercase tracking-wider text-white/50">{label}</p><p className="mt-1 text-lg font-semibold text-white">{value}</p></div>}
function Metric({icon:Icon,label,value}:{icon:typeof Leaf;label:string;value:string}){return <Card><CardContent className="flex items-center gap-3 p-4"><div className="bg-muted p-2"><Icon className="h-4 w-4"/></div><div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-lg font-semibold">{value}</p></div></CardContent></Card>}
function Datum({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
function Action({href,icon:Icon,title,text}:{href:string;icon:typeof Leaf;title:string;text:string}){return <Link href={href} className="block border border-white/10 bg-[var(--bs-surface-secondary)] p-5 transition hover:bg-[var(--bs-surface-elevated)]"><Icon className="h-5 w-5"/><p className="mt-4 font-semibold">{title}</p><p className="mt-1 text-sm text-muted-foreground">{text}</p></Link>}
