"use client"

import type { FormEvent, ReactNode } from "react"
import { useCallback, useEffect, useMemo, useState } from "react"
import { CalendarDays, CheckCircle2, Copy, Gauge, Plus, RefreshCw, Sparkles, Sprout, Target, Trash2 } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type GamePlan = { id: string; name: string; season: string | null; start_date: string; end_date: string; status: "draft" | "active" | "completed" | "archived"; objective: string | null; notes: string | null }
type CropCycle = { id: string; game_plan_id: string; crop_name: string; variety: string | null; cycle_type: "direct_sow" | "transplant" | "perennial" | "cover_crop"; planned_start_date: string; target_harvest_date: string | null; status: "planned" | "nursery" | "planted" | "growing" | "harvest_ready" | "completed" | "cancelled"; planned_area_sqm: number | null; target_quantity: number | null; target_unit: string | null; notes: string | null }
type Succession = { id: string; crop_cycle_id: string; sequence_no: number; planned_sow_date: string; planned_transplant_date: string | null; planned_first_harvest_date: string | null; planned_last_harvest_date: string | null; days_to_maturity: number | null; planned_plants: number | null; planned_area_sqm: number | null; plant_spacing_cm: number | null; row_spacing_cm: number | null; germination_rate_pct: number | null; seeds_per_plant: number | null; status: "planned" | "sown" | "transplanted" | "harvesting" | "completed" | "cancelled"; notes: string | null }
type Crop = { id: string; crop_succession_id: string | null; planting_date: string; expected_harvest_date: string | null; actual_harvest_date: string | null; status: string; estimated_yield: number | null; actual_yield: number | null; yield_unit: string | null }

const copy = {
  en: { title: "Game Plan", description: "Build the season, repeat successions fast, and compare the plan with live execution.", refresh: "Refresh", plans: "Game plans", newPlan: "New game plan", planName: "Plan name", season: "Season", start: "Start date", end: "End date", objective: "Objective", notes: "Notes", createPlan: "Create game plan", noPlans: "No game plans yet.", addCycle: "Add crop cycle", crop: "Crop", variety: "Variety", cycleType: "Cycle type", targetHarvest: "Target harvest", area: "Planned area (m²)", quantity: "Target quantity", unit: "Unit", createCycle: "Create crop cycle", successions: "Successions", addSuccession: "Add succession", sowDate: "Sow date", transplantDate: "Transplant date", firstHarvest: "First harvest", lastHarvest: "Last harvest", maturity: "Days to maturity", plants: "Planned plants", germination: "Germination (%)", seedsPerPlant: "Seeds / plant", createSuccession: "Create succession", timeline: "Season runway", timelineHelp: "Every succession positioned inside the selected operating window.", execution: "Plan vs actual", executionHelp: "Live crops linked to planned successions.", linked: "Linked successions", onTime: "On-time starts", actualHarvests: "Actual harvests", repeat: "Repeat", repeatCount: "Copies", repeatEvery: "Every (days)", repeatAction: "Create repeats", estimatedSeeds: "Estimated seeds", plannedPlants: "Planned plants", harvestWindows: "Harvest windows", plannedArea: "Planned area", noCycles: "No crop cycles in this plan yet.", noSuccessions: "No successions yet.", loadError: "Could not load planning data", saveError: "Could not save changes", deletePlan: "Delete this game plan and all related planning records?", deleteCycle: "Delete this crop cycle and all successions?", deleteSuccession: "Delete this succession?", planProgress: "Execution coverage", live: "Live", planned: "Planned", actual: "Actual", daysVariance: "Start variance", noExecution: "No live crops linked to this plan yet.", command: "Season command center", commandHelp: "One operating picture for capacity, propagation demand, harvest windows and execution drift.", activeCycles: "Active crop cycles", liveCrops: "Live crops", objectiveLabel: "Operating objective", seasonSignal: "Season signal", build: "Build the plan", buildHelp: "Create crop cycles only after the operating window and objective are clear.", cadence: "Succession cadence", cadenceHelp: "Repeat proven succession timing without rebuilding dates manually." },
  es: { title: "Plan de Cultivo", description: "Construye la temporada, repite sucesiones rápido y compara el plan con la ejecución real.", refresh: "Actualizar", plans: "Planes", newPlan: "Nuevo plan", planName: "Nombre del plan", season: "Temporada", start: "Fecha de inicio", end: "Fecha de término", objective: "Objetivo", notes: "Notas", createPlan: "Crear plan", noPlans: "Aún no hay planes.", addCycle: "Agregar ciclo", crop: "Cultivo", variety: "Variedad", cycleType: "Tipo de ciclo", targetHarvest: "Cosecha objetivo", area: "Área planificada (m²)", quantity: "Cantidad objetivo", unit: "Unidad", createCycle: "Crear ciclo", successions: "Sucesiones", addSuccession: "Agregar sucesión", sowDate: "Fecha de siembra", transplantDate: "Fecha de trasplante", firstHarvest: "Primera cosecha", lastHarvest: "Última cosecha", maturity: "Días a madurez", plants: "Plantas planificadas", germination: "Germinación (%)", seedsPerPlant: "Semillas / planta", createSuccession: "Crear sucesión", timeline: "Pista de temporada", timelineHelp: "Cada sucesión posicionada dentro de la ventana operativa seleccionada.", execution: "Plan vs real", executionHelp: "Cultivos vivos conectados a sucesiones planificadas.", linked: "Sucesiones conectadas", onTime: "Inicios a tiempo", actualHarvests: "Cosechas reales", repeat: "Repetir", repeatCount: "Copias", repeatEvery: "Cada (días)", repeatAction: "Crear repeticiones", estimatedSeeds: "Semillas estimadas", plannedPlants: "Plantas planificadas", harvestWindows: "Ventanas de cosecha", plannedArea: "Área planificada", noCycles: "Aún no hay ciclos en este plan.", noSuccessions: "Aún no hay sucesiones.", loadError: "No fue posible cargar la planificación", saveError: "No fue posible guardar cambios", deletePlan: "¿Eliminar este plan y todos sus registros de planificación?", deleteCycle: "¿Eliminar este ciclo y sus sucesiones?", deleteSuccession: "¿Eliminar esta sucesión?", planProgress: "Cobertura de ejecución", live: "Activo", planned: "Plan", actual: "Real", daysVariance: "Desviación inicio", noExecution: "Aún no hay cultivos vivos conectados a este plan.", command: "Centro de mando de temporada", commandHelp: "Una sola vista operativa para capacidad, demanda de propagación, ventanas de cosecha y desviaciones de ejecución.", activeCycles: "Ciclos activos", liveCrops: "Cultivos vivos", objectiveLabel: "Objetivo operativo", seasonSignal: "Señal de temporada", build: "Construir el plan", buildHelp: "Crea ciclos de cultivo cuando la ventana operativa y el objetivo estén claros.", cadence: "Cadencia de sucesiones", cadenceHelp: "Repite una cadencia probada sin reconstruir fechas manualmente." },
} as const

const cycleTypes: CropCycle["cycle_type"][] = ["direct_sow", "transplant", "perennial", "cover_crop"]
const planStatuses: GamePlan["status"][] = ["draft", "active", "completed", "archived"]
const cycleStatuses: CropCycle["status"][] = ["planned", "nursery", "planted", "growing", "harvest_ready", "completed", "cancelled"]
const titleize = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase())
const dateLabel = (value: string | null, locale: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString(locale, { month: "short", day: "numeric", year: "numeric" }) : "—"
const addDays = (value: string, days: number) => { const d = new Date(`${value}T12:00:00`); d.setDate(d.getDate() + days); return d.toISOString().slice(0, 10) }
const dayDiff = (a: string, b: string) => Math.round((new Date(`${a}T12:00:00`).getTime() - new Date(`${b}T12:00:00`).getTime()) / 86400000)
const seedsFor = (s: Succession) => s.planned_plants && s.germination_rate_pct && s.seeds_per_plant ? Math.ceil((s.planned_plants * s.seeds_per_plant) / (s.germination_rate_pct / 100)) : 0
const photo = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1800&q=92`
const cropPhoto = (name: string) => {
  const key = name.toLowerCase()
  if (key.includes("tomato")) return photo("photo-1592924357228-91a4daadcfea")
  if (key.includes("lettuce")) return photo("photo-1622206151226-18ca2c9ab4a1")
  if (key.includes("radish")) return photo("photo-1582284540020-8acbe03f4924")
  if (key.includes("onion")) return photo("photo-1508747703725-719777637510")
  if (key.includes("carrot")) return photo("photo-1447175008436-054170c2e979")
  if (key.includes("arugula") || key.includes("rocket")) return photo("photo-1501004318641-b39e6451bec6")
  if (key.includes("spinach")) return photo("photo-1576045057995-568f588f82fb")
  if (key.includes("basil")) return photo("photo-1618375569909-3c8616cf7733")
  return photo("photo-1416879595882-3373a0480b5b")
}

export default function OrchardGamePlanPage() {
  const supabase = useMemo(() => createBrowserClient(), [])
  const { language } = useLanguage(); const lang = language === "es" ? "es" : "en"; const text = copy[lang]; const locale = lang === "es" ? "es-CL" : "en-US"
  const [plans, setPlans] = useState<GamePlan[]>([]); const [cycles, setCycles] = useState<CropCycle[]>([]); const [successions, setSuccessions] = useState<Succession[]>([]); const [crops, setCrops] = useState<Crop[]>([])
  const [selectedPlanId, setSelectedPlanId] = useState<string | null>(null); const [openCycleId, setOpenCycleId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const [planForm, setPlanForm] = useState({ name: "", season: "", start_date: "", end_date: "", objective: "", notes: "" })
  const [cycleForm, setCycleForm] = useState({ crop_name: "", variety: "", cycle_type: "direct_sow" as CropCycle["cycle_type"], planned_start_date: "", target_harvest_date: "", planned_area_sqm: "", target_quantity: "", target_unit: "kg", notes: "" })
  const emptySuccession = { planned_sow_date: "", planned_transplant_date: "", planned_first_harvest_date: "", planned_last_harvest_date: "", days_to_maturity: "", planned_plants: "", planned_area_sqm: "", plant_spacing_cm: "", row_spacing_cm: "", germination_rate_pct: "85", seeds_per_plant: "1", notes: "" }
  const [successionForm, setSuccessionForm] = useState(emptySuccession); const [repeatForm, setRepeatForm] = useState({ count: "3", every_days: "14" })

  const load = useCallback(async () => {
    setLoading(true); setError(null)
    const [p, c, s, live] = await Promise.all([
      supabase.from("orchard_game_plans").select("id,name,season,start_date,end_date,status,objective,notes").order("start_date", { ascending: false }),
      supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name,variety,cycle_type,planned_start_date,target_harvest_date,status,planned_area_sqm,target_quantity,target_unit,notes").order("planned_start_date"),
      supabase.from("orchard_crop_successions").select("id,crop_cycle_id,sequence_no,planned_sow_date,planned_transplant_date,planned_first_harvest_date,planned_last_harvest_date,days_to_maturity,planned_plants,planned_area_sqm,plant_spacing_cm,row_spacing_cm,germination_rate_pct,seeds_per_plant,status,notes").order("planned_sow_date"),
      supabase.from("orchard_crops").select("id,crop_succession_id,planting_date,expected_harvest_date,actual_harvest_date,status,estimated_yield,actual_yield,yield_unit").not("crop_succession_id", "is", null),
    ])
    const e = p.error ?? c.error ?? s.error ?? live.error
    if (e) setError(`${text.loadError}: ${e.message}`)
    else { const nextPlans = (p.data ?? []) as GamePlan[]; setPlans(nextPlans); setCycles((c.data ?? []) as CropCycle[]); setSuccessions((s.data ?? []) as Succession[]); setCrops((live.data ?? []) as Crop[]); setSelectedPlanId((current) => current && nextPlans.some((x) => x.id === current) ? current : nextPlans[0]?.id ?? null) }
    setLoading(false)
  }, [supabase, text.loadError])
  useEffect(() => { void load() }, [load])

  const selectedPlan = plans.find((p) => p.id === selectedPlanId) ?? null
  const selectedCycles = cycles.filter((c) => c.game_plan_id === selectedPlanId)
  const selectedCycleIds = useMemo(() => new Set(selectedCycles.map((c) => c.id)), [selectedCycles])
  const selectedSuccessions = successions.filter((s) => selectedCycleIds.has(s.crop_cycle_id))
  const selectedSuccessionIds = useMemo(() => new Set(selectedSuccessions.map((s) => s.id)), [selectedSuccessions])
  const liveCrops = crops.filter((c) => c.crop_succession_id && selectedSuccessionIds.has(c.crop_succession_id))
  const linkedIds = new Set(liveCrops.map((c) => c.crop_succession_id).filter(Boolean)); const coverage = selectedSuccessions.length ? Math.round((linkedIds.size / selectedSuccessions.length) * 100) : 0
  const onTime = liveCrops.filter((crop) => { const s = selectedSuccessions.find((x) => x.id === crop.crop_succession_id); if (!s) return false; return Math.abs(dayDiff(crop.planting_date, s.planned_transplant_date ?? s.planned_sow_date)) <= 3 }).length
  const totalArea = selectedSuccessions.reduce((sum, s) => sum + (s.planned_area_sqm ?? 0), 0); const totalPlants = selectedSuccessions.reduce((sum, s) => sum + (s.planned_plants ?? 0), 0); const totalSeeds = selectedSuccessions.reduce((sum, s) => sum + seedsFor(s), 0); const harvestWindows = selectedSuccessions.filter((s) => s.planned_first_harvest_date).length
  const activeCycles = selectedCycles.filter((cycle) => !["completed", "cancelled"].includes(cycle.status)).length

  async function createPlan(e: FormEvent) { e.preventDefault(); if (!planForm.name || !planForm.start_date || !planForm.end_date) return; setSaving(true); const r = await supabase.from("orchard_game_plans").insert({ ...planForm, season: planForm.season || null, objective: planForm.objective || null, notes: planForm.notes || null }).select("id").single(); if (r.error) setError(`${text.saveError}: ${r.error.message}`); else { setPlanForm({ name: "", season: "", start_date: "", end_date: "", objective: "", notes: "" }); await load(); setSelectedPlanId(r.data.id) } setSaving(false) }
  async function createCycle(e: FormEvent) { e.preventDefault(); if (!selectedPlanId || !cycleForm.crop_name || !cycleForm.planned_start_date) return; setSaving(true); const r = await supabase.from("orchard_crop_cycles").insert({ game_plan_id: selectedPlanId, crop_name: cycleForm.crop_name.trim(), variety: cycleForm.variety.trim() || null, cycle_type: cycleForm.cycle_type, planned_start_date: cycleForm.planned_start_date, target_harvest_date: cycleForm.target_harvest_date || null, planned_area_sqm: cycleForm.planned_area_sqm ? Number(cycleForm.planned_area_sqm) : null, target_quantity: cycleForm.target_quantity ? Number(cycleForm.target_quantity) : null, target_unit: cycleForm.target_unit || null, notes: cycleForm.notes || null }); if (r.error) setError(`${text.saveError}: ${r.error.message}`); else { setCycleForm({ crop_name: "", variety: "", cycle_type: "direct_sow", planned_start_date: "", target_harvest_date: "", planned_area_sqm: "", target_quantity: "", target_unit: "kg", notes: "" }); await load() } setSaving(false) }
  async function createSuccession(e: FormEvent) { e.preventDefault(); if (!openCycleId || !successionForm.planned_sow_date) return; const existing = successions.filter((s) => s.crop_cycle_id === openCycleId); setSaving(true); const r = await supabase.from("orchard_crop_successions").insert({ crop_cycle_id: openCycleId, sequence_no: existing.length + 1, planned_sow_date: successionForm.planned_sow_date, planned_transplant_date: successionForm.planned_transplant_date || null, planned_first_harvest_date: successionForm.planned_first_harvest_date || null, planned_last_harvest_date: successionForm.planned_last_harvest_date || null, days_to_maturity: successionForm.days_to_maturity ? Number(successionForm.days_to_maturity) : null, planned_plants: successionForm.planned_plants ? Number(successionForm.planned_plants) : null, planned_area_sqm: successionForm.planned_area_sqm ? Number(successionForm.planned_area_sqm) : null, plant_spacing_cm: successionForm.plant_spacing_cm ? Number(successionForm.plant_spacing_cm) : null, row_spacing_cm: successionForm.row_spacing_cm ? Number(successionForm.row_spacing_cm) : null, germination_rate_pct: successionForm.germination_rate_pct ? Number(successionForm.germination_rate_pct) : null, seeds_per_plant: successionForm.seeds_per_plant ? Number(successionForm.seeds_per_plant) : null, notes: successionForm.notes || null }); if (r.error) setError(`${text.saveError}: ${r.error.message}`); else { setSuccessionForm(emptySuccession); await load() } setSaving(false) }
  async function repeatSuccession(source: Succession) { const count = Math.max(1, Number(repeatForm.count) || 1); const every = Math.max(1, Number(repeatForm.every_days) || 14); const existing = successions.filter((s) => s.crop_cycle_id === source.crop_cycle_id); const rows = Array.from({ length: count }, (_, i) => { const offset = every * (i + 1); return { crop_cycle_id: source.crop_cycle_id, sequence_no: existing.length + i + 1, planned_sow_date: addDays(source.planned_sow_date, offset), planned_transplant_date: source.planned_transplant_date ? addDays(source.planned_transplant_date, offset) : null, planned_first_harvest_date: source.planned_first_harvest_date ? addDays(source.planned_first_harvest_date, offset) : null, planned_last_harvest_date: source.planned_last_harvest_date ? addDays(source.planned_last_harvest_date, offset) : null, days_to_maturity: source.days_to_maturity, planned_plants: source.planned_plants, planned_area_sqm: source.planned_area_sqm, plant_spacing_cm: source.plant_spacing_cm, row_spacing_cm: source.row_spacing_cm, germination_rate_pct: source.germination_rate_pct, seeds_per_plant: source.seeds_per_plant, notes: source.notes } }); setSaving(true); const r = await supabase.from("orchard_crop_successions").insert(rows); if (r.error) setError(`${text.saveError}: ${r.error.message}`); else await load(); setSaving(false) }
  async function updateStatus(table: string, id: string, status: string) { setSaving(true); const r = await supabase.from(table).update({ status }).eq("id", id); if (r.error) setError(`${text.saveError}: ${r.error.message}`); else await load(); setSaving(false) }
  async function remove(table: string, id: string, message: string) { if (!window.confirm(message)) return; setSaving(true); const r = await supabase.from(table).delete().eq("id", id); if (r.error) setError(`${text.saveError}: ${r.error.message}`); else await load(); setSaving(false) }

  return <AppLayout><PageHeader title={text.title} description={text.description} actions={<Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />{text.refresh}</Button>} /><OrchardNavigation /><div className="space-y-6 p-4 sm:p-8">{error && <Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}

    {selectedPlan && <section className="relative overflow-hidden rounded-3xl border border-white/10 bg-[#0b0f0d] text-white shadow-2xl"><img src={photo("photo-1523348837708-15d4a09cfac2")} alt="Season planning" className="absolute inset-0 h-full w-full object-cover opacity-100 [filter:none]" /><div className="absolute inset-0" style={{background:"linear-gradient(90deg,rgba(5,8,7,.96) 0%,rgba(5,8,7,.88) 42%,rgba(5,8,7,.48) 72%,rgba(5,8,7,.22) 100%),linear-gradient(0deg,rgba(5,8,7,.82) 0%,rgba(5,8,7,.08) 64%)"}}/><div className="relative grid gap-8 p-6 md:p-8 xl:grid-cols-[1.1fr_.9fr]"><div className="max-w-3xl"><div className="flex flex-wrap items-center gap-2"><Badge className="border-white/15 bg-white/10 text-white hover:bg-white/10">{selectedPlan.status}</Badge><Badge variant="outline" className="border-white/20 bg-black/25 text-white">{selectedPlan.season ?? text.seasonSignal}</Badge></div><p className="mt-6 text-xs font-semibold uppercase tracking-[.22em] text-emerald-200">{text.command}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em] md:text-5xl">{selectedPlan.name}</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-white/70">{selectedPlan.objective || text.commandHelp}</p><div className="mt-6 flex flex-wrap gap-3 text-sm"><span className="rounded-full border border-white/15 bg-black/25 px-3 py-1.5">{dateLabel(selectedPlan.start_date, locale)} → {dateLabel(selectedPlan.end_date, locale)}</span><span className="rounded-full border border-white/15 bg-black/25 px-3 py-1.5">{selectedCycles.length} {text.activeCycles.toLowerCase()}</span><span className="rounded-full border border-white/15 bg-black/25 px-3 py-1.5">{liveCrops.length} {text.liveCrops.toLowerCase()}</span></div></div><div className="grid grid-cols-2 gap-3 self-end"><HeroMetric icon={<Gauge className="h-4 w-4"/>} label={text.planProgress} value={`${coverage}%`} /><HeroMetric icon={<Target className="h-4 w-4"/>} label={text.plannedArea} value={`${totalArea.toFixed(1)} m²`} /><HeroMetric icon={<Sprout className="h-4 w-4"/>} label={text.plannedPlants} value={totalPlants.toLocaleString(locale)} /><HeroMetric icon={<CalendarDays className="h-4 w-4"/>} label={text.harvestWindows} value={String(harvestWindows)} /></div></div></section>}

    <div className="grid gap-6 xl:grid-cols-[300px_1fr]">
      <div className="space-y-6"><Card className="overflow-hidden"><CardHeader><CardTitle>{text.plans}</CardTitle><CardDescription>{text.commandHelp}</CardDescription></CardHeader><CardContent className="space-y-3">{plans.length === 0 ? <p className="text-sm text-muted-foreground">{text.noPlans}</p> : plans.map((p) => <button key={p.id} className={`group w-full overflow-hidden rounded-2xl border text-left transition ${selectedPlanId === p.id ? "border-emerald-500/40 ring-1 ring-emerald-500/20" : "hover:border-foreground/20"}`} onClick={() => setSelectedPlanId(p.id)}><div className="relative h-24 overflow-hidden"><img src={photo("photo-1471193945509-9ad0617afabf")} alt="Growing season" className="h-full w-full object-cover opacity-100 transition-transform duration-500 [filter:none] group-hover:scale-[1.02]"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(5,8,7,.9),rgba(5,8,7,.12))]"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between gap-2 p-3 text-white"><span className="font-medium">{p.name}</span><Badge className="border-white/15 bg-black/30 text-white">{p.status}</Badge></div></div><div className="p-3 text-xs text-muted-foreground">{dateLabel(p.start_date, locale)} → {dateLabel(p.end_date, locale)}</div></button>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>{text.newPlan}</CardTitle><CardDescription>{text.buildHelp}</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={createPlan}><Field label={text.planName}><Input value={planForm.name} onChange={(e) => setPlanForm((v) => ({ ...v, name: e.target.value }))} required /></Field><Field label={text.season}><Input value={planForm.season} onChange={(e) => setPlanForm((v) => ({ ...v, season: e.target.value }))} /></Field><div className="grid grid-cols-2 gap-2"><Field label={text.start}><Input type="date" value={planForm.start_date} onChange={(e) => setPlanForm((v) => ({ ...v, start_date: e.target.value }))} required /></Field><Field label={text.end}><Input type="date" value={planForm.end_date} onChange={(e) => setPlanForm((v) => ({ ...v, end_date: e.target.value }))} required /></Field></div><Field label={text.objective}><Textarea value={planForm.objective} onChange={(e) => setPlanForm((v) => ({ ...v, objective: e.target.value }))} /></Field><Button type="submit" className="w-full" disabled={saving}><Plus className="mr-2 h-4 w-4" />{text.createPlan}</Button></form></CardContent></Card></div>

      <div className="space-y-6">{selectedPlan && <>
        <Card><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">{text.objectiveLabel}</p><p className="mt-2 max-w-3xl text-sm leading-6">{selectedPlan.objective || "—"}</p></div><div className="flex items-center gap-2"><Status value={selectedPlan.status} values={planStatuses} disabled={saving} onChange={(value) => void updateStatus("orchard_game_plans", selectedPlan.id, value)} /><Button size="icon" variant="ghost" onClick={() => void remove("orchard_game_plans", selectedPlan.id, text.deletePlan)}><Trash2 className="h-4 w-4" /></Button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label={text.plannedArea} value={`${totalArea.toFixed(1)} m²`} /><Metric label={text.plannedPlants} value={String(totalPlants)} /><Metric label={text.estimatedSeeds} value={String(totalSeeds)} /><Metric label={text.harvestWindows} value={String(harvestWindows)} /><Metric label={text.activeCycles} value={`${activeCycles}/${selectedCycles.length}`} /></div></CardContent></Card>

        <Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5"/>{text.timeline}</CardTitle><CardDescription>{text.timelineHelp}</CardDescription></CardHeader><CardContent className="space-y-5">{selectedCycles.length === 0 ? <p className="text-sm text-muted-foreground">{text.noCycles}</p> : selectedCycles.map((cycle) => { const cycleSuccessions = selectedSuccessions.filter((s) => s.crop_cycle_id === cycle.id); const span = Math.max(1, dayDiff(selectedPlan.end_date, selectedPlan.start_date)); const liveForCycle = cycleSuccessions.filter((s) => crops.some((c) => c.crop_succession_id === s.id)).length; return <div key={cycle.id} className="overflow-hidden rounded-2xl border"><div className="relative min-h-36 overflow-hidden p-5 text-white"><img src={cropPhoto(cycle.crop_name)} alt={cycle.crop_name} className="absolute inset-0 h-full w-full object-cover opacity-100 [filter:none]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(6,9,8,.93),rgba(6,9,8,.62)_58%,rgba(6,9,8,.2))]"/><div className="relative flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-emerald-200">{titleize(cycle.cycle_type)}</p><h3 className="mt-1 text-2xl font-semibold">{cycle.crop_name}{cycle.variety ? ` · ${cycle.variety}` : ""}</h3><div className="mt-3 flex flex-wrap gap-2 text-xs text-white/70"><span>{cycleSuccessions.length} {text.successions.toLowerCase()}</span><span>·</span><span>{liveForCycle} {text.live.toLowerCase()}</span>{cycle.planned_area_sqm != null && <><span>·</span><span>{cycle.planned_area_sqm} m²</span></>}</div></div><div className="flex items-center gap-2"><Status value={cycle.status} values={cycleStatuses} disabled={saving} onChange={(value) => void updateStatus("orchard_crop_cycles", cycle.id, value)} /><Button size="icon" variant="ghost" className="text-white hover:bg-white/10 hover:text-white" onClick={() => void remove("orchard_crop_cycles", cycle.id, text.deleteCycle)}><Trash2 className="h-4 w-4" /></Button></div></div></div>
        <div className="p-4"><div className="space-y-4">{cycleSuccessions.length === 0 ? <p className="text-xs text-muted-foreground">{text.noSuccessions}</p> : cycleSuccessions.map((s) => { const startDate = s.planned_transplant_date ?? s.planned_sow_date; const endDate = s.planned_last_harvest_date ?? s.planned_first_harvest_date ?? startDate; const left = Math.max(0, Math.min(100, (dayDiff(startDate, selectedPlan.start_date) / span) * 100)); const width = Math.max(2, Math.min(100 - left, (Math.max(1, dayDiff(endDate, startDate)) / span) * 100)); const live = crops.find((c) => c.crop_succession_id === s.id); return <div key={s.id} className="rounded-xl border bg-muted/10 p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">#{s.sequence_no} · {dateLabel(s.planned_sow_date, locale)}</p><p className="mt-1 text-xs text-muted-foreground">{s.planned_plants ?? 0} {text.plannedPlants.toLowerCase()} · {s.planned_area_sqm ?? 0} m² · {seedsFor(s)} {text.estimatedSeeds.toLowerCase()}</p></div><div className="flex items-center gap-1"><Badge variant={live ? "default" : "outline"}>{live ? text.live : s.status}</Badge><Button size="sm" variant="ghost" onClick={() => void repeatSuccession(s)}><Copy className="mr-1 h-3.5 w-3.5" />{text.repeat}</Button><Button size="icon" variant="ghost" onClick={() => void remove("orchard_crop_successions", s.id, text.deleteSuccession)}><Trash2 className="h-3.5 w-3.5" /></Button></div></div><div className="relative mt-3 h-9 overflow-hidden rounded-lg bg-muted"><div className="absolute inset-y-1 rounded-md bg-foreground/85 shadow-sm" style={{ left: `${left}%`, width: `${width}%` }} /><div className="absolute inset-0 flex items-center justify-between px-2 text-[10px] text-muted-foreground"><span>{dateLabel(startDate, locale)}</span><span>{dateLabel(endDate, locale)}</span></div></div></div> })}</div>
        <div className="mt-4 rounded-xl border bg-muted/10 p-4"><div className="mb-3"><p className="font-medium">{text.cadence}</p><p className="text-xs text-muted-foreground">{text.cadenceHelp}</p></div><div className="grid gap-2 sm:grid-cols-3"><Field label={text.repeatCount}><Input type="number" min="1" max="12" value={repeatForm.count} onChange={(e) => setRepeatForm((v) => ({ ...v, count: e.target.value }))} /></Field><Field label={text.repeatEvery}><Input type="number" min="1" value={repeatForm.every_days} onChange={(e) => setRepeatForm((v) => ({ ...v, every_days: e.target.value }))} /></Field><div className="flex items-end"><Button variant="outline" className="w-full" disabled={cycleSuccessions.length === 0 || saving} onClick={() => cycleSuccessions.length && void repeatSuccession(cycleSuccessions[cycleSuccessions.length - 1])}>{text.repeatAction}</Button></div></div></div>
        <div className="mt-4"><Button variant="secondary" onClick={() => { setOpenCycleId(openCycleId === cycle.id ? null : cycle.id); setSuccessionForm(emptySuccession) }}><Plus className="mr-2 h-4 w-4" />{text.addSuccession}</Button></div>{openCycleId === cycle.id && <form className="mt-4 grid gap-3 rounded-xl border bg-background p-4 md:grid-cols-2 xl:grid-cols-4" onSubmit={createSuccession}><Field label={text.sowDate}><Input type="date" value={successionForm.planned_sow_date} onChange={(e) => setSuccessionForm((v) => ({ ...v, planned_sow_date: e.target.value }))} required /></Field><Field label={text.transplantDate}><Input type="date" value={successionForm.planned_transplant_date} onChange={(e) => setSuccessionForm((v) => ({ ...v, planned_transplant_date: e.target.value }))} /></Field><Field label={text.firstHarvest}><Input type="date" value={successionForm.planned_first_harvest_date} onChange={(e) => setSuccessionForm((v) => ({ ...v, planned_first_harvest_date: e.target.value }))} /></Field><Field label={text.lastHarvest}><Input type="date" value={successionForm.planned_last_harvest_date} onChange={(e) => setSuccessionForm((v) => ({ ...v, planned_last_harvest_date: e.target.value }))} /></Field><Field label={text.maturity}><Input type="number" min="1" value={successionForm.days_to_maturity} onChange={(e) => setSuccessionForm((v) => ({ ...v, days_to_maturity: e.target.value }))} /></Field><Field label={text.plants}><Input type="number" min="0" value={successionForm.planned_plants} onChange={(e) => setSuccessionForm((v) => ({ ...v, planned_plants: e.target.value }))} /></Field><Field label={text.area}><Input type="number" min="0" step="0.1" value={successionForm.planned_area_sqm} onChange={(e) => setSuccessionForm((v) => ({ ...v, planned_area_sqm: e.target.value }))} /></Field><Field label={text.germination}><Input type="number" min="1" max="100" value={successionForm.germination_rate_pct} onChange={(e) => setSuccessionForm((v) => ({ ...v, germination_rate_pct: e.target.value }))} /></Field><Field label={text.seedsPerPlant}><Input type="number" min="0.1" step="0.1" value={successionForm.seeds_per_plant} onChange={(e) => setSuccessionForm((v) => ({ ...v, seeds_per_plant: e.target.value }))} /></Field><div className="md:col-span-2 xl:col-span-4"><Field label={text.notes}><Textarea value={successionForm.notes} onChange={(e) => setSuccessionForm((v) => ({ ...v, notes: e.target.value }))} /></Field></div><div className="md:col-span-2 xl:col-span-4"><Button type="submit" disabled={saving}><Plus className="mr-2 h-4 w-4" />{text.createSuccession}</Button></div></form>}</div></div> })}</CardContent></Card>

        <Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5"/>{text.execution}</CardTitle><CardDescription>{text.executionHelp}</CardDescription></CardHeader><CardContent><div className="mb-4 grid gap-3 sm:grid-cols-3"><Metric label={text.linked} value={`${linkedIds.size}/${selectedSuccessions.length}`} /><Metric label={text.onTime} value={`${onTime}/${liveCrops.length}`} /><Metric label={text.actualHarvests} value={String(liveCrops.filter((c) => c.actual_harvest_date).length)} /></div>{liveCrops.length === 0 ? <p className="text-sm text-muted-foreground">{text.noExecution}</p> : <div className="grid gap-3 md:grid-cols-2">{liveCrops.map((crop) => { const s = selectedSuccessions.find((x) => x.id === crop.crop_succession_id); const cycle = s ? selectedCycles.find((x) => x.id === s.crop_cycle_id) : null; const plannedStart = s ? (s.planned_transplant_date ?? s.planned_sow_date) : crop.planting_date; const variance = dayDiff(crop.planting_date, plannedStart); return <div key={crop.id} className="overflow-hidden rounded-xl border"><div className="relative h-24"><img src={cropPhoto(cycle?.crop_name ?? "crop")} alt={cycle?.crop_name ?? "Crop"} className="h-full w-full object-cover opacity-100 [filter:none]"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(6,9,8,.88),rgba(6,9,8,.08))]"/><div className="absolute inset-x-0 bottom-0 p-3 text-white"><p className="font-medium">{cycle?.crop_name ?? "Crop"}{cycle?.variety ? ` · ${cycle.variety}` : ""} {s ? `#${s.sequence_no}` : ""}</p></div></div><div className="flex flex-wrap items-center justify-between gap-2 p-3"><div className="text-xs text-muted-foreground">{text.planned}: {dateLabel(plannedStart, locale)}<br/>{text.actual}: {dateLabel(crop.planting_date, locale)}</div><div className="flex gap-2"><Badge variant={Math.abs(variance) <= 3 ? "default" : "outline"}>{variance > 0 ? `+${variance}` : variance}d</Badge><Badge variant="secondary">{crop.status}</Badge></div></div></div> })}</div>}</CardContent></Card>

        <Card><CardHeader><CardTitle>{text.build}</CardTitle><CardDescription>{text.buildHelp}</CardDescription></CardHeader><CardContent><form className="grid gap-3 md:grid-cols-2" onSubmit={createCycle}><Field label={text.crop}><Input value={cycleForm.crop_name} onChange={(e) => setCycleForm((v) => ({ ...v, crop_name: e.target.value }))} required /></Field><Field label={text.variety}><Input value={cycleForm.variety} onChange={(e) => setCycleForm((v) => ({ ...v, variety: e.target.value }))} /></Field><Field label={text.cycleType}><Select value={cycleForm.cycle_type} onValueChange={(value) => setCycleForm((v) => ({ ...v, cycle_type: value as CropCycle["cycle_type"] }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{cycleTypes.map((type) => <SelectItem key={type} value={type}>{titleize(type)}</SelectItem>)}</SelectContent></Select></Field><Field label={text.start}><Input type="date" value={cycleForm.planned_start_date} onChange={(e) => setCycleForm((v) => ({ ...v, planned_start_date: e.target.value }))} required /></Field><Field label={text.targetHarvest}><Input type="date" value={cycleForm.target_harvest_date} onChange={(e) => setCycleForm((v) => ({ ...v, target_harvest_date: e.target.value }))} /></Field><Field label={text.area}><Input type="number" min="0" step="0.1" value={cycleForm.planned_area_sqm} onChange={(e) => setCycleForm((v) => ({ ...v, planned_area_sqm: e.target.value }))} /></Field><Field label={text.quantity}><Input type="number" min="0" step="0.1" value={cycleForm.target_quantity} onChange={(e) => setCycleForm((v) => ({ ...v, target_quantity: e.target.value }))} /></Field><Field label={text.unit}><Input value={cycleForm.target_unit} onChange={(e) => setCycleForm((v) => ({ ...v, target_unit: e.target.value }))} /></Field><div className="md:col-span-2"><Field label={text.notes}><Textarea value={cycleForm.notes} onChange={(e) => setCycleForm((v) => ({ ...v, notes: e.target.value }))} /></Field></div><div className="md:col-span-2"><Button type="submit" disabled={saving}><Sprout className="mr-2 h-4 w-4" />{text.createCycle}</Button></div></form></CardContent></Card>
      </>}</div>
    </div>
  </div></AppLayout>
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-muted/10 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div> }
function HeroMetric({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-black/30 p-4 backdrop-blur-sm"><div className="flex items-center gap-2 text-xs uppercase tracking-[.16em] text-white/55">{icon}{label}</div><p className="mt-2 text-2xl font-semibold text-white">{value}</p></div> }
function Status<T extends string>({ value, values, disabled, onChange }: { value: T; values: readonly T[]; disabled: boolean; onChange: (value: T) => void }) { return <Select value={value} onValueChange={(next) => onChange(next as T)} disabled={disabled}><SelectTrigger className="w-[150px]"><SelectValue /></SelectTrigger><SelectContent>{values.map((item) => <SelectItem key={item} value={item}>{titleize(item)}</SelectItem>)}</SelectContent></Select> }
