"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowRight, CheckCircle2 } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Plan={id:string;name:string;season:string|null;status:string}
type Cycle={id:string;game_plan_id:string}
type Succession={id:string;crop_cycle_id:string;planned_bed_m:number|string|null}
type Allocation={crop_succession_id:string}
type RevenueTarget={crop_succession_id:string}
type TaskRef={source_id:string|null;source_type:string|null}
type Snapshot={plans:Plan[];cycles:Cycle[];successions:Succession[];allocations:Allocation[];revenueTargets:RevenueTarget[];tasks:TaskRef[];farmObjects:number;charts:number;seeds:number}
const initial:Snapshot={plans:[],cycles:[],successions:[],allocations:[],revenueTargets:[],tasks:[],farmObjects:0,charts:0,seeds:0}
const statusLabels:Record<Locale,Record<string,string>>={en:{draft:"Draft",active:"Active",completed:"Completed",archived:"Archived"},es:{draft:"Borrador",active:"Activo",completed:"Completado",archived:"Archivado"},de:{draft:"Entwurf",active:"Aktiv",completed:"Abgeschlossen",archived:"Archiviert"}}
const statusLabel=(status:string,locale:Locale)=>statusLabels[locale][status]??status.replaceAll("_"," ")
const copy={
 en:{eyebrow:"Orchard · Getting Started",title:"Finish setup",description:"Only the actions that still need real operating evidence stay in front of you.",loading:"Loading Orchard state…",error:"Could not load onboarding state.",plan:"Game Plan",actions:"Actions left",allDone:"Setup complete",allDoneHelp:"The selected Game Plan has the operating setup needed to run Orchard.",completed:"Completed setup",open:"Continue",cropGap:(n:number)=>`${n} planned planting${n===1?"":"s"} still need a physical bed allocation.`,seedGap:"No physical seed lots are recorded yet. Add the stock you actually have on hand; do not estimate it.",steps:[["Map your farm","Physical farm locations are configured."],["Choose your crops","Season crops and cultivars are configured."],["Create your Game Plan","Season successions are planned."],["Finish Crop Map","Allocate every planned planting to a physical bed."],["Financial forecast","Revenue targets exist for the reconciled plan."],["Data charts","Intelligence Studio has saved operational views."],["Consolidate seed stock","Record the first physical seed lot or receipt."],["Workload","Operational tasks are available for the plan."]]},
 es:{eyebrow:"Huerto · Primeros pasos",title:"Terminar configuración",description:"Sólo quedan al frente las acciones que todavía requieren evidencia operacional real.",loading:"Cargando estado de Orchard…",error:"No fue posible cargar el onboarding.",plan:"Plan de cultivo",actions:"Acciones pendientes",allDone:"Configuración completa",allDoneHelp:"El plan seleccionado ya tiene la configuración operativa necesaria para trabajar en Orchard.",completed:"Configuración completada",open:"Continuar",cropGap:(n:number)=>`${n} plantación${n===1?"":"es"} planificada${n===1?"":"s"} aún necesita${n===1?"":"n"} una cama física.`,seedGap:"Todavía no hay lotes físicos de semillas. Registra el stock que realmente tienes disponible; no lo estimes.",steps:[["Mapea tu granja","Las ubicaciones físicas ya están configuradas."],["Elige tus cultivos","Los cultivos y cultivares de temporada ya están configurados."],["Crea tu plan de cultivo","Las sucesiones de temporada ya están planificadas."],["Termina el Mapa de cultivos","Asigna cada plantación planificada a una cama física."],["Proyección financiera","Ya existen objetivos de ingreso para el plan reconciliado."],["Gráficos de datos","Intelligence Studio ya tiene vistas operativas guardadas."],["Consolida el stock de semillas","Registra el primer lote físico o recepción de semillas."],["Carga de trabajo","El plan ya tiene tareas operativas disponibles."]]},
 de:{eyebrow:"Orchard · Erste Schritte",title:"Einrichtung abschließen",description:"Nur Schritte mit noch fehlendem realem Betriebsnachweis bleiben im Vordergrund.",loading:"Orchard-Status wird geladen…",error:"Onboarding konnte nicht geladen werden.",plan:"Anbauplan",actions:"Offene Aktionen",allDone:"Einrichtung abgeschlossen",allDoneHelp:"Der gewählte Game Plan besitzt die notwendige operative Einrichtung.",completed:"Abgeschlossene Einrichtung",open:"Weiter",cropGap:(n:number)=>`${n} geplante Pflanzung${n===1?"":"en"} benötigen noch eine physische Beetzuordnung.`,seedGap:"Noch keine physischen Saatgutpartien erfasst. Nur tatsächlich vorhandenen Bestand eintragen; nicht schätzen.",steps:[["Farm kartieren","Physische Farmbereiche sind eingerichtet."],["Kulturen auswählen","Saisonkulturen und Sorten sind eingerichtet."],["Anbauplan erstellen","Saisonfolgen sind geplant."],["Anbaukarte abschließen","Jede geplante Pflanzung einem physischen Beet zuordnen."],["Finanzprognose","Umsatzziele für den abgeglichenen Plan sind vorhanden."],["Datendiagramme","Intelligence Studio besitzt gespeicherte Betriebsansichten."],["Saatgutbestand konsolidieren","Erste physische Saatgutpartie oder Wareneingang erfassen."],["Arbeitslast","Operative Aufgaben für den Plan sind vorhanden."]]}
} as const

export default function OrchardGettingStartedPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const locale:Locale=language;const text=copy[locale]
 const [snapshot,setSnapshot]=useState<Snapshot>(initial),[selectedPlanId,setSelectedPlanId]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 useEffect(()=>{let live=true;void Promise.all([
  supabase.from("orchard_game_plans").select("id,name,season,status").order("created_at",{ascending:false}),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id,planned_bed_m").neq("status","cancelled"),
  supabase.from("orchard_bed_allocations").select("crop_succession_id"),
  supabase.from("orchard_revenue_targets").select("crop_succession_id"),
  supabase.from("tasks").select("source_id,source_type").in("operational_area",["orchard","huerto_vinedo"]),
  supabase.from("orchard_farm_map_objects").select("id",{count:"exact",head:true}).in("object_type",["field_block","greenhouse","tunnel","farm_area"]),
  supabase.from("orchard_chart_definitions").select("id",{count:"exact",head:true}),
  supabase.from("orchard_seed_lots").select("id",{count:"exact",head:true})
 ]).then(results=>{if(!live)return;const first=results.find(result=>result.error)?.error;if(first){setError(`${text.error} ${first.message}`);setLoading(false);return}const plans=(results[0].data??[]) as Plan[];setSnapshot({plans,cycles:(results[1].data??[]) as Cycle[],successions:(results[2].data??[]) as Succession[],allocations:(results[3].data??[]) as Allocation[],revenueTargets:(results[4].data??[]) as RevenueTarget[],tasks:(results[5].data??[]) as TaskRef[],farmObjects:results[6].count??0,charts:results[7].count??0,seeds:results[8].count??0});const requested=new URLSearchParams(window.location.search).get("game_plan");setSelectedPlanId(plans.find(plan=>plan.id===requested)?.id??plans.find(plan=>plan.season==="2026/27")?.id??plans.find(plan=>plan.status==="active")?.id??plans.find(plan=>plan.status==="draft")?.id??plans[0]?.id??"");setLoading(false)});return()=>{live=false}},[supabase,text.error])
 const cycles=snapshot.cycles.filter(c=>c.game_plan_id===selectedPlanId);const cycleIds=new Set(cycles.map(c=>c.id));const successions=snapshot.successions.filter(s=>cycleIds.has(s.crop_cycle_id)&&Number(s.planned_bed_m)>0);const successionIds=new Set(successions.map(s=>s.id));const allocated=new Set(snapshot.allocations.filter(a=>successionIds.has(a.crop_succession_id)).map(a=>a.crop_succession_id));const scopedRevenueTargets=snapshot.revenueTargets.filter(target=>successionIds.has(target.crop_succession_id));const scopedTasks=snapshot.tasks.filter(task=>Boolean(task.source_id&&successionIds.has(task.source_id)))
 const completion=[snapshot.farmObjects>0,cycles.length>0,successions.length>0,successions.length>0&&allocated.size===successions.length,scopedRevenueTargets.length>0,snapshot.charts>0,snapshot.seeds>0,scopedTasks.length>0];const completed=completion.filter(Boolean).length;const unallocated=Math.max(0,successions.length-allocated.size)
 const routes=["/orchard/farm-map","/orchard/crops/catalog","/orchard/game-plan/season","/orchard/crop-map/overview","/orchard/game-plan/forecast","/orchard/charts","/orchard/nursery/advanced","/orchard/work/week-board"]
 const href=(route:string)=>`/${language}${route}${selectedPlanId?`?game_plan=${encodeURIComponent(selectedPlanId)}`:""}`;const pending=completion.map((done,index)=>({done,index})).filter(item=>!item.done);const doneItems=completion.map((done,index)=>({done,index})).filter(item=>item.done)
 const detail=(index:number)=>index===3?text.cropGap(unallocated):index===6?text.seedGap:text.steps[index][1]
 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1040px] px-4 py-7 sm:px-6 lg:px-8">
  <header className="grid gap-5 border-b border-[var(--orchard-line)] pb-5 lg:grid-cols-[1fr_260px] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--orchard-green)]">{text.eyebrow}</p><h1 className="mt-2 text-3xl font-normal sm:text-4xl">{text.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{text.description}</p></div><label className="text-xs text-muted-foreground">{text.plan}<select value={selectedPlanId} onChange={e=>setSelectedPlanId(e.target.value)} className="mt-2 h-10 w-full border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] px-3 text-sm text-foreground outline-none">{snapshot.plans.map(plan=><option key={plan.id} value={plan.id}>{plan.season??plan.name} · {statusLabel(plan.status,locale)}</option>)}</select></label></header>
  {loading?<div className="py-16 text-sm text-muted-foreground">{text.loading}</div>:error?<div className="my-8 border-y border-red-400/30 py-4 text-sm text-red-300">{error}</div>:<>
   <section className="my-6 flex items-center justify-between gap-6 border-y border-[var(--orchard-line)] py-4"><div><p className="text-xs uppercase tracking-[.15em] text-muted-foreground">{pending.length?text.actions:text.allDone}</p><p className="mt-1 text-3xl font-light tabular-nums">{pending.length}</p></div><div className="min-w-[180px] flex-1"><div className="flex justify-between text-xs text-muted-foreground"><span>{completed}/8</span><span>{Math.round(completed/8*100)}%</span></div><div className="mt-2 h-1 overflow-hidden bg-[var(--bs-surface-tertiary)]"><div className="h-full bg-[var(--orchard-green)]" style={{width:`${completed/8*100}%`}}/></div></div></section>
   {pending.length===0?<section className="border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] p-6"><CheckCircle2 className="h-6 w-6 text-[var(--orchard-green)]"/><h2 className="mt-4 text-2xl font-normal">{text.allDone}</h2><p className="mt-2 text-sm text-muted-foreground">{text.allDoneHelp}</p></section>:<section className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[.15em] text-muted-foreground">{text.actions}</p>{pending.map(({index})=><Link key={index} href={href(routes[index])} className="group grid gap-4 border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] p-5 transition hover:bg-[var(--bs-surface-secondary)] sm:grid-cols-[44px_1fr_auto] sm:items-center"><span className="text-sm tabular-nums text-[var(--orchard-green)]">0{index+1}</span><span><strong className="block text-xl font-normal">{text.steps[index][0]}</strong><span className="mt-1 block text-sm leading-6 text-muted-foreground">{detail(index)}</span></span><span className="inline-flex items-center gap-2 text-sm font-medium text-[var(--orchard-green)]">{text.open}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></Link>)}</section>}
   <details className="mt-8 border-y border-[var(--orchard-line)] py-4"><summary className="cursor-pointer text-sm font-medium">{text.completed} · {doneItems.length}</summary><div className="mt-4 grid gap-x-6 md:grid-cols-2">{doneItems.map(({index})=><Link key={index} href={href(routes[index])} className="flex items-center justify-between border-t border-[var(--bs-divider-subtle)] py-3 text-sm"><span className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-[var(--orchard-green)]"/><span>{text.steps[index][0]}</span></span><ArrowRight className="h-3.5 w-3.5 text-muted-foreground"/></Link>)}</div></details>
  </>}
 </main></AppLayout>
}
