"use client"

import Link from "next/link"
import { FormEvent, useEffect, useMemo, useState } from "react"
import { ArrowRight, CheckCircle2, Sprout } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Plan={id:string;name:string;season:string|null;status:string;start_date:string;end_date:string}
type Cycle={id:string;game_plan_id:string}
type Succession={id:string;crop_cycle_id:string;planned_bed_m:number|string|null}
type Allocation={crop_succession_id:string}
type RevenueTarget={crop_succession_id:string}
type TaskRef={source_id:string|null;source_type:string|null}
type CropProfile={id:string;crop_name:string;default_cycle_type:string|null;days_to_maturity:number|null;germination_rate_pct:number|null;seeds_per_plant:number|null}
type Snapshot={plans:Plan[];cycles:Cycle[];successions:Succession[];allocations:Allocation[];revenueTargets:RevenueTarget[];tasks:TaskRef[];profiles:CropProfile[];farmObjects:number;charts:number;seeds:number}
type QuickForm={cropId:string;variety:string;cycleType:"direct_sow"|"transplant"|"perennial"|"cover_crop";sowDate:string;transplantDate:string;bedMeters:string}

const initial:Snapshot={plans:[],cycles:[],successions:[],allocations:[],revenueTargets:[],tasks:[],profiles:[],farmObjects:0,charts:0,seeds:0}
const emptyQuick:QuickForm={cropId:"",variety:"",cycleType:"direct_sow",sowDate:"",transplantDate:"",bedMeters:""}
const statusLabels:Record<Locale,Record<string,string>>={en:{draft:"Draft",active:"Active",completed:"Completed",archived:"Archived"},es:{draft:"Borrador",active:"Activo",completed:"Completado",archived:"Archivado"},de:{draft:"Entwurf",active:"Aktiv",completed:"Abgeschlossen",archived:"Archiviert"}}
const statusLabel=(status:string,locale:Locale)=>statusLabels[locale][status]??status.replaceAll("_"," ")
const copy={
 en:{eyebrow:"Orchard · Getting Started",title:"Start growing",description:"Create one real planting first. Orchard will guide you through the rest only when it becomes necessary.",loading:"Loading Orchard state…",error:"Could not load onboarding state.",plan:"Game Plan",actions:"Actions left",allDone:"Setup complete",allDoneHelp:"The selected Game Plan has the operating setup needed to run Orchard.",completed:"Completed setup",open:"Continue",cropGap:(n:number)=>`${n} planned planting${n===1?"":"s"} still need a physical bed allocation.`,seedGap:"No physical seed lots are recorded yet. Add only stock you actually have on hand.",steps:[["Map your farm","Physical farm locations are configured."],["Create your first planting","Add one crop to the season in the fast setup."],["Build the season","Season successions are planned."],["Place crops in beds","Allocate every planned planting to a physical bed."],["Financial forecast","Revenue targets exist for the reconciled plan."],["Data charts","Intelligence Studio has saved operational views."],["Consolidate seed stock","Record the first physical seed lot or receipt."],["Workload","Operational tasks are available for the plan."]],quickTitle:"Create your first planting",quickHelp:"Five fields. Orchard creates the crop cycle and first succession for you.",crop:"Crop",chooseCrop:"Choose a crop",variety:"Variety (optional)",method:"How will it start?",direct:"Direct sow",transplant:"Nursery / transplant",perennial:"Perennial",cover:"Cover crop",sowDate:"Sow / start date",transplantDate:"Field transplant date",bedMeters:"Bed metres needed",create:"Create planting",creating:"Creating…",quickError:"Could not create the planting.",missingPlan:"Create a Game Plan first, then come back here.",createPlan:"Create Game Plan",nextHelp:"After saving, you will go straight to Crop Map to place this planting in a physical bed.",why:"You can refine harvest dates, plant counts, spacing and propagation later. The first goal is to get one real planting into the system."},
 es:{eyebrow:"Huerto · Primeros pasos",title:"Empieza a cultivar",description:"Crea primero una plantación real. Orchard te irá pidiendo el resto sólo cuando sea necesario.",loading:"Cargando estado de Orchard…",error:"No fue posible cargar el onboarding.",plan:"Plan de cultivo",actions:"Acciones pendientes",allDone:"Configuración completa",allDoneHelp:"El plan seleccionado ya tiene la configuración operativa necesaria para trabajar en Orchard.",completed:"Configuración completada",open:"Continuar",cropGap:(n:number)=>`${n} plantación${n===1?"":"es"} planificada${n===1?"":"s"} aún necesita${n===1?"":"n"} una cama física.`,seedGap:"Todavía no hay lotes físicos de semillas. Registra sólo el stock que realmente tienes.",steps:[["Mapea tu granja","Las ubicaciones físicas ya están configuradas."],["Crea tu primera plantación","Agrega un cultivo a la temporada con la configuración rápida."],["Construye la temporada","Las sucesiones de temporada ya están planificadas."],["Ubica los cultivos en camas","Asigna cada plantación planificada a una cama física."],["Proyección financiera","Ya existen objetivos de ingreso para el plan reconciliado."],["Gráficos de datos","Intelligence Studio ya tiene vistas operativas guardadas."],["Consolida el stock de semillas","Registra el primer lote físico o recepción de semillas."],["Carga de trabajo","El plan ya tiene tareas operativas disponibles."]],quickTitle:"Crea tu primera plantación",quickHelp:"Cinco datos. Orchard crea por detrás el ciclo de cultivo y su primera sucesión.",crop:"Cultivo",chooseCrop:"Elige un cultivo",variety:"Variedad (opcional)",method:"¿Cómo comenzará?",direct:"Siembra directa",transplant:"Almácigo / trasplante",perennial:"Perenne",cover:"Cobertura",sowDate:"Fecha de siembra / inicio",transplantDate:"Fecha de trasplante a campo",bedMeters:"Metros de cama necesarios",create:"Crear plantación",creating:"Creando…",quickError:"No fue posible crear la plantación.",missingPlan:"Primero crea un Plan de Cultivo y vuelve aquí.",createPlan:"Crear Plan de Cultivo",nextHelp:"Al guardar, irás directo al Mapa de cultivos para ubicar esta plantación en una cama física.",why:"Puedes completar cosecha, cantidad de plantas, espaciamiento y propagación después. El primer objetivo es dejar una plantación real dentro del sistema."},
 de:{eyebrow:"Orchard · Erste Schritte",title:"Mit dem Anbau starten",description:"Zuerst eine reale Pflanzung anlegen. Orchard fragt weitere Details erst ab, wenn sie wirklich gebraucht werden.",loading:"Orchard-Status wird geladen…",error:"Onboarding konnte nicht geladen werden.",plan:"Anbauplan",actions:"Offene Aktionen",allDone:"Einrichtung abgeschlossen",allDoneHelp:"Der gewählte Game Plan besitzt die notwendige operative Einrichtung.",completed:"Abgeschlossene Einrichtung",open:"Weiter",cropGap:(n:number)=>`${n} geplante Pflanzung${n===1?"":"en"} benötigen noch eine physische Beetzuordnung.`,seedGap:"Noch keine physischen Saatgutpartien erfasst. Nur tatsächlich vorhandenen Bestand eintragen.",steps:[["Farm kartieren","Physische Farmbereiche sind eingerichtet."],["Erste Pflanzung anlegen","Eine Kultur mit dem Schnellstart zur Saison hinzufügen."],["Saison aufbauen","Saisonfolgen sind geplant."],["Kulturen Beeten zuordnen","Jede geplante Pflanzung einem physischen Beet zuordnen."],["Finanzprognose","Umsatzziele für den abgeglichenen Plan sind vorhanden."],["Datendiagramme","Intelligence Studio besitzt gespeicherte Betriebsansichten."],["Saatgutbestand konsolidieren","Erste physische Saatgutpartie oder Wareneingang erfassen."],["Arbeitslast","Operative Aufgaben für den Plan sind vorhanden."]],quickTitle:"Erste Pflanzung anlegen",quickHelp:"Fünf Angaben. Orchard erstellt Kulturzyklus und erste Folge im Hintergrund.",crop:"Kultur",chooseCrop:"Kultur wählen",variety:"Sorte (optional)",method:"Wie startet die Kultur?",direct:"Direktsaat",transplant:"Anzucht / Verpflanzung",perennial:"Mehrjährig",cover:"Zwischenfrucht",sowDate:"Aussaat / Startdatum",transplantDate:"Feldpflanzdatum",bedMeters:"Benötigte Beetmeter",create:"Pflanzung erstellen",creating:"Wird erstellt…",quickError:"Pflanzung konnte nicht erstellt werden.",missingPlan:"Zuerst einen Game Plan anlegen und dann hierher zurückkehren.",createPlan:"Game Plan erstellen",nextHelp:"Nach dem Speichern geht es direkt zur Anbaukarte, um die Pflanzung einem physischen Beet zuzuordnen.",why:"Erntefenster, Pflanzenzahl, Abstände und Vermehrung können später ergänzt werden. Zuerst soll eine reale Pflanzung im System stehen."}
} as const

export default function OrchardGettingStartedPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const locale:Locale=language;const text=copy[locale]
 const [snapshot,setSnapshot]=useState<Snapshot>(initial),[selectedPlanId,setSelectedPlanId]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 const [quick,setQuick]=useState<QuickForm>(emptyQuick),[saving,setSaving]=useState(false),[quickError,setQuickError]=useState<string|null>(null)

 useEffect(()=>{let live=true;void Promise.all([
  supabase.from("orchard_game_plans").select("id,name,season,status,start_date,end_date").order("created_at",{ascending:false}),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id,planned_bed_m").neq("status","cancelled"),
  supabase.from("orchard_bed_allocations").select("crop_succession_id"),
  supabase.from("orchard_revenue_targets").select("crop_succession_id"),
  supabase.from("tasks").select("source_id,source_type").in("operational_area",["orchard","huerto_vinedo"]),
  supabase.from("orchard_farm_map_objects").select("id",{count:"exact",head:true}).in("object_type",["field_block","greenhouse","tunnel","farm_area"]),
  supabase.from("orchard_chart_definitions").select("id",{count:"exact",head:true}),
  supabase.from("orchard_seed_lots").select("id",{count:"exact",head:true}),
  supabase.from("orchard_crop_library").select("id,crop_name,default_cycle_type,days_to_maturity,germination_rate_pct,seeds_per_plant").eq("is_active",true).eq("classification_scheme","black_swan_canonical").eq("classification_code","fundo_corcovado").order("crop_name")
 ]).then(results=>{if(!live)return;const first=results.find(result=>result.error)?.error;if(first){setError(`${text.error} ${first.message}`);setLoading(false);return}const plans=(results[0].data??[]) as Plan[];const profiles=(results[9].data??[]) as CropProfile[];setSnapshot({plans,cycles:(results[1].data??[]) as Cycle[],successions:(results[2].data??[]) as Succession[],allocations:(results[3].data??[]) as Allocation[],revenueTargets:(results[4].data??[]) as RevenueTarget[],tasks:(results[5].data??[]) as TaskRef[],farmObjects:results[6].count??0,charts:results[7].count??0,seeds:results[8].count??0,profiles});const requested=new URLSearchParams(window.location.search).get("game_plan");const selected=plans.find(plan=>plan.id===requested)??plans.find(plan=>plan.season==="2026/27")??plans.find(plan=>plan.status==="active")??plans.find(plan=>plan.status==="draft")??plans[0]??null;setSelectedPlanId(selected?.id??"");if(profiles.length)setQuick(current=>current.cropId?current:{...current,cropId:profiles[0].id,cycleType:(profiles[0].default_cycle_type as QuickForm["cycleType"])||"direct_sow",sowDate:selected?.start_date??""});setLoading(false)});return()=>{live=false}},[supabase,text.error])

 const selectedPlan=snapshot.plans.find(plan=>plan.id===selectedPlanId)??null
 const cycles=snapshot.cycles.filter(c=>c.game_plan_id===selectedPlanId);const cycleIds=new Set(cycles.map(c=>c.id));const allSuccessions=snapshot.successions.filter(s=>cycleIds.has(s.crop_cycle_id));const reconciledSuccessions=allSuccessions.filter(s=>Number(s.planned_bed_m)>0);const reconciledIds=new Set(reconciledSuccessions.map(s=>s.id));const allocated=new Set(snapshot.allocations.filter(a=>reconciledIds.has(a.crop_succession_id)).map(a=>a.crop_succession_id));const scopedRevenueTargets=snapshot.revenueTargets.filter(target=>reconciledIds.has(target.crop_succession_id));const scopedTasks=snapshot.tasks.filter(task=>Boolean(task.source_id&&reconciledIds.has(task.source_id)))
 const completion=[snapshot.farmObjects>0,cycles.length>0,allSuccessions.length>0,reconciledSuccessions.length>0&&allocated.size===reconciledSuccessions.length,scopedRevenueTargets.length>0,snapshot.charts>0,snapshot.seeds>0,scopedTasks.length>0];const completed=completion.filter(Boolean).length;const unallocated=Math.max(0,reconciledSuccessions.length-allocated.size)
 const routes=["/orchard/farm-map","/orchard/getting-started","/orchard/game-plan/season","/orchard/crop-map/overview","/orchard/game-plan/forecast","/orchard/charts","/orchard/nursery/quick-stock","/orchard/work/week-board"]
 const href=(route:string)=>`/${language}${route}${selectedPlanId?`?game_plan=${encodeURIComponent(selectedPlanId)}`:""}`;const pending=completion.map((done,index)=>({done,index})).filter(item=>!item.done);const doneItems=completion.map((done,index)=>({done,index})).filter(item=>item.done)
 const detail=(index:number)=>index===3?text.cropGap(unallocated):index===6?text.seedGap:text.steps[index][1]
 const profile=snapshot.profiles.find(item=>item.id===quick.cropId)??null

 function selectCrop(id:string){const next=snapshot.profiles.find(item=>item.id===id);setQuick(current=>({...current,cropId:id,cycleType:(next?.default_cycle_type as QuickForm["cycleType"])||current.cycleType}))}
 async function createFirstPlanting(event:FormEvent){
  event.preventDefault();setQuickError(null);if(!selectedPlan||!profile||!quick.sowDate||!quick.bedMeters)return
  const bedMeters=Number(quick.bedMeters);if(!Number.isFinite(bedMeters)||bedMeters<=0)return
  if(quick.cycleType==="transplant"&&!quick.transplantDate)return
  setSaving(true)
  const cycle=await supabase.from("orchard_crop_cycles").insert({game_plan_id:selectedPlan.id,crop_name:profile.crop_name,variety:quick.variety.trim()||null,cycle_type:quick.cycleType,planned_start_date:quick.sowDate,target_harvest_date:null,status:"planned",planned_area_sqm:null,target_quantity:null,target_unit:null,notes:null}).select("id").single()
  if(cycle.error){setQuickError(`${text.quickError} ${cycle.error.message}`);setSaving(false);return}
  const succession=await supabase.from("orchard_crop_successions").insert({crop_cycle_id:cycle.data.id,sequence_no:1,planned_sow_date:quick.sowDate,planned_transplant_date:quick.cycleType==="transplant"?quick.transplantDate:null,planned_first_harvest_date:null,planned_last_harvest_date:null,days_to_maturity:profile.days_to_maturity,planned_plants:null,planned_area_sqm:null,plant_spacing_cm:null,row_spacing_cm:null,germination_rate_pct:profile.germination_rate_pct,seeds_per_plant:profile.seeds_per_plant,status:"planned",notes:null,crop_library_id:profile.id,planned_bed_m:bedMeters}).select("id").single()
  if(succession.error){await supabase.from("orchard_crop_cycles").delete().eq("id",cycle.data.id);setQuickError(`${text.quickError} ${succession.error.message}`);setSaving(false);return}
  window.location.assign(`/${language}/orchard/crop-map/overview?game_plan=${encodeURIComponent(selectedPlan.id)}&new_succession=${encodeURIComponent(succession.data.id)}`)
 }

 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1040px] px-4 py-7 sm:px-6 lg:px-8">
  <header className="grid gap-5 border-b border-[var(--orchard-line)] pb-5 lg:grid-cols-[1fr_260px] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--orchard-green)]">{text.eyebrow}</p><h1 className="mt-2 text-3xl font-normal sm:text-4xl">{text.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{text.description}</p></div><label className="text-xs text-muted-foreground">{text.plan}<select value={selectedPlanId} onChange={e=>setSelectedPlanId(e.target.value)} className="mt-2 h-10 w-full border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] px-3 text-sm text-foreground outline-none">{snapshot.plans.map(plan=><option key={plan.id} value={plan.id}>{plan.season??plan.name} · {statusLabel(plan.status,locale)}</option>)}</select></label></header>
  {loading?<div className="py-16 text-sm text-muted-foreground">{text.loading}</div>:error?<div className="my-8 border-y border-red-400/30 py-4 text-sm text-red-300">{error}</div>:<>
   <section className="my-6 border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] p-5 sm:p-6">
    <div className="flex items-start gap-3"><span className="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[var(--orchard-green-soft)] text-[var(--orchard-green)]"><Sprout className="h-5 w-5"/></span><div><h2 className="text-2xl font-normal">{text.quickTitle}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{text.quickHelp}</p></div></div>
    {!selectedPlan?<div className="mt-5 border-t border-[var(--orchard-line)] pt-5"><p className="text-sm text-muted-foreground">{text.missingPlan}</p><Link href={`/${language}/orchard/game-plan`} className="mt-3 inline-flex min-h-10 items-center gap-2 bg-[var(--orchard-green)] px-4 text-sm font-medium text-black">{text.createPlan}<ArrowRight className="h-4 w-4"/></Link></div>:<form onSubmit={createFirstPlanting} className="mt-5 grid gap-4 border-t border-[var(--orchard-line)] pt-5 md:grid-cols-2">
     <label className="text-xs text-muted-foreground">{text.crop}<select required value={quick.cropId} onChange={e=>selectCrop(e.target.value)} className="mt-2 h-11 w-full border border-[var(--orchard-line)] bg-[var(--bs-bg-primary)] px-3 text-sm text-foreground"><option value="">{text.chooseCrop}</option>{snapshot.profiles.map(item=><option key={item.id} value={item.id}>{item.crop_name}</option>)}</select></label>
     <label className="text-xs text-muted-foreground">{text.variety}<input value={quick.variety} onChange={e=>setQuick(v=>({...v,variety:e.target.value}))} className="mt-2 h-11 w-full border border-[var(--orchard-line)] bg-[var(--bs-bg-primary)] px-3 text-sm"/></label>
     <label className="text-xs text-muted-foreground">{text.method}<select value={quick.cycleType} onChange={e=>setQuick(v=>({...v,cycleType:e.target.value as QuickForm["cycleType"]}))} className="mt-2 h-11 w-full border border-[var(--orchard-line)] bg-[var(--bs-bg-primary)] px-3 text-sm text-foreground"><option value="direct_sow">{text.direct}</option><option value="transplant">{text.transplant}</option><option value="perennial">{text.perennial}</option><option value="cover_crop">{text.cover}</option></select></label>
     <label className="text-xs text-muted-foreground">{text.sowDate}<input required type="date" min={selectedPlan.start_date} max={selectedPlan.end_date} value={quick.sowDate} onChange={e=>setQuick(v=>({...v,sowDate:e.target.value}))} className="mt-2 h-11 w-full border border-[var(--orchard-line)] bg-[var(--bs-bg-primary)] px-3 text-sm"/></label>
     {quick.cycleType==="transplant"?<label className="text-xs text-muted-foreground">{text.transplantDate}<input required type="date" min={quick.sowDate||selectedPlan.start_date} max={selectedPlan.end_date} value={quick.transplantDate} onChange={e=>setQuick(v=>({...v,transplantDate:e.target.value}))} className="mt-2 h-11 w-full border border-[var(--orchard-line)] bg-[var(--bs-bg-primary)] px-3 text-sm"/></label>:null}
     <label className="text-xs text-muted-foreground">{text.bedMeters}<input required type="number" min="0.1" step="0.1" value={quick.bedMeters} onChange={e=>setQuick(v=>({...v,bedMeters:e.target.value}))} className="mt-2 h-11 w-full border border-[var(--orchard-line)] bg-[var(--bs-bg-primary)] px-3 text-sm"/></label>
     <div className="md:col-span-2"><p className="text-xs leading-5 text-muted-foreground">{text.why}</p><p className="mt-1 text-xs leading-5 text-[var(--orchard-green)]">{text.nextHelp}</p>{quickError?<p className="mt-3 text-sm text-red-300">{quickError}</p>:null}<button type="submit" disabled={saving||!profile} className="mt-4 inline-flex min-h-11 items-center gap-2 bg-[var(--orchard-green)] px-5 text-sm font-medium text-black disabled:opacity-50"><Sprout className="h-4 w-4"/>{saving?text.creating:text.create}</button></div>
    </form>}
   </section>
   <section className="my-6 flex items-center justify-between gap-6 border-y border-[var(--orchard-line)] bg-[var(--orchard-canvas)] py-4 text-foreground"><div><p className="text-xs uppercase tracking-[.15em] text-muted-foreground">{pending.length?text.actions:text.allDone}</p><p className="mt-1 text-3xl font-light tabular-nums text-[var(--orchard-green)]">{pending.length}</p></div><div className="min-w-[180px] flex-1"><div className="flex justify-between text-xs text-muted-foreground"><span>{completed}/8</span><span>{Math.round(completed/8*100)}%</span></div><div className="mt-2 h-1 overflow-hidden bg-[var(--bs-surface-tertiary)]"><div className="h-full bg-[var(--orchard-green)]" style={{width:`${completed/8*100}%`}}/></div></div></section>
   {pending.length===0?<section className="border-y border-[var(--orchard-line)] bg-transparent py-6"><CheckCircle2 className="h-6 w-6 text-[var(--orchard-green)]"/><h2 className="mt-4 text-2xl font-normal">{text.allDone}</h2><p className="mt-2 text-sm text-muted-foreground">{text.allDoneHelp}</p></section>:<section className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[.15em] text-muted-foreground">{text.actions}</p>{pending.map(({index})=><Link key={index} href={href(routes[index])} className="group grid gap-4 border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] p-5 transition hover:bg-[var(--bs-surface-secondary)] sm:grid-cols-[44px_1fr_auto] sm:items-center"><span className="text-sm tabular-nums text-[var(--orchard-green)]">0{index+1}</span><span><strong className="block text-xl font-normal">{text.steps[index][0]}</strong><span className="mt-1 block text-sm leading-6 text-muted-foreground">{detail(index)}</span></span><span className="inline-flex items-center gap-2 text-sm font-medium text-[var(--orchard-green)]">{text.open}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></Link>)}</section>}
   <details className="mt-8 border-y border-[var(--orchard-line)] py-4"><summary className="cursor-pointer text-sm font-medium">{text.completed} · {doneItems.length}</summary><div className="mt-4 grid gap-x-6 md:grid-cols-2">{doneItems.map(({index})=><Link key={index} href={href(routes[index])} className="flex items-center justify-between border-t border-[var(--bs-divider-subtle)] py-3 text-sm"><span className="flex items-center gap-3"><CheckCircle2 className="h-4 w-4 text-[var(--orchard-green)]"/><span>{text.steps[index][0]}</span></span><ArrowRight className="h-3.5 w-3.5 text-muted-foreground"/></Link>)}</div></details>
  </>}
 </main></AppLayout>
}
