"use client"

import { useEffect, useMemo, useState } from "react"
import { AlertCircle, DollarSign, Package, TrendingUp } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { useLanguage } from "@/lib/hooks/use-language"
import { createBrowserClient } from "@/lib/supabase/client"

interface ProcurementItem { id:string; item_name:string; category:string; total_cost:number; status:string; supplier_id:string; quantity:number }
interface CategoryStats { category:string; count:number; total:number }

const LOCALES={en:"en-US",es:"es-CL",de:"de-DE"} as const
const COPY={
 en:{title:"Procurement analytics",description:"Budget and procurement performance indicators",spent:"Total spent",orders:"Total orders",avg:"Average order value",pendingOrders:"Pending orders",byCategory:"Spending by category",byCategoryDetail:"Budget allocation across procurement categories",loading:"Loading analytics…",items:"items",empty:"No spending data available",statusSummary:"Order status summary",pending:"Pending",delivered:"Delivered",transit:"In transit",top:"Top categories"},
 es:{title:"Analítica de compras",description:"Seguimiento de presupuesto e indicadores de compras",spent:"Gasto total",orders:"Órdenes totales",avg:"Valor promedio por orden",pendingOrders:"Órdenes pendientes",byCategory:"Gasto por categoría",byCategoryDetail:"Distribución presupuestaria entre categorías de compras",loading:"Cargando analítica…",items:"ítems",empty:"No hay datos de gasto disponibles",statusSummary:"Resumen de estados de órdenes",pending:"Pendientes",delivered:"Entregadas",transit:"En tránsito",top:"Principales categorías"},
 de:{title:"Procurement-Analyse",description:"Budget- und Beschaffungskennzahlen",spent:"Gesamtausgaben",orders:"Bestellungen gesamt",avg:"Durchschnittlicher Bestellwert",pendingOrders:"Offene Bestellungen",byCategory:"Ausgaben nach Kategorie",byCategoryDetail:"Budgetverteilung über Beschaffungskategorien",loading:"Analyse wird geladen…",items:"Artikel",empty:"Keine Ausgabendaten verfügbar",statusSummary:"Bestellstatus",pending:"Ausstehend",delivered:"Geliefert",transit:"Unterwegs",top:"Top-Kategorien"}
} as const

export default function ProcurementAnalyticsPage(){
 const {language}=useLanguage();const copy=COPY[language];const locale=LOCALES[language]
 const money=useMemo(()=>new Intl.NumberFormat(locale,{style:"currency",currency:"CLP",maximumFractionDigits:0}),[locale]);const number=useMemo(()=>new Intl.NumberFormat(locale),[locale]);const percent=useMemo(()=>new Intl.NumberFormat(locale,{style:"percent",maximumFractionDigits:1}),[locale])
 const [items,setItems]=useState<ProcurementItem[]>([]);const [loading,setLoading]=useState(true);const [categoryStats,setCategoryStats]=useState<CategoryStats[]>([])
 useEffect(()=>{let cancelled=false;async function loadData(){const supabase=createBrowserClient();const {data,error}=await supabase.from("procurement_items").select("*");if(error){console.error("[procurement-analytics] load failed",error)}else if(data&&!cancelled){setItems(data);const stats:Record<string,{count:number;total:number}>={};data.forEach(item=>{if(!stats[item.category])stats[item.category]={count:0,total:0};stats[item.category].count+=1;stats[item.category].total+=item.total_cost||0});setCategoryStats(Object.entries(stats).map(([category,{count,total}])=>({category,count,total})))}if(!cancelled)setLoading(false)}void loadData();return()=>{cancelled=true}},[])
 const totalSpent=items.reduce((sum,item)=>sum+(item.total_cost||0),0);const totalOrders=items.length;const pendingOrders=items.filter(item=>item.status==="pending").length;const deliveredOrders=items.filter(item=>item.status==="delivered").length;const ordered=items.filter(item=>item.status==="ordered").length;const avgOrderValue=totalOrders>0?totalSpent/totalOrders:0
 return <AppLayout><PageHeader title={copy.title} description={copy.description}/><div className="space-y-6 p-8">
  <div className="grid gap-4 md:grid-cols-4"><Kpi title={copy.spent} value={money.format(totalSpent)} icon={<DollarSign className="h-4 w-4 text-primary"/>}/><Kpi title={copy.orders} value={number.format(totalOrders)} icon={<Package className="h-4 w-4 text-primary"/>}/><Kpi title={copy.avg} value={money.format(avgOrderValue)} icon={<TrendingUp className="h-4 w-4 text-primary"/>}/><Kpi title={copy.pendingOrders} value={number.format(pendingOrders)} icon={<AlertCircle className="h-4 w-4 text-yellow-500"/>}/></div>
  <Card><CardHeader><CardTitle>{copy.byCategory}</CardTitle><CardDescription>{copy.byCategoryDetail}</CardDescription></CardHeader><CardContent><div className="space-y-4">{loading?<div className="py-8 text-center text-muted-foreground">{copy.loading}</div>:categoryStats.length>0?categoryStats.map(stat=>{const ratio=totalSpent>0?stat.total/totalSpent:0;return <div key={stat.category} className="space-y-2"><div className="flex items-center justify-between"><div><p className="font-medium text-accent">{stat.category}</p><p className="text-sm text-muted-foreground">{number.format(stat.count)} {copy.items}</p></div><div className="text-right"><p className="font-semibold text-accent">{money.format(stat.total)}</p><p className="text-sm text-muted-foreground">{percent.format(ratio)}</p></div></div><div className="h-2 w-full rounded-full bg-secondary"><div className="h-2 rounded-full bg-primary transition-all duration-300" style={{width:`${Math.min(100,ratio*100)}%`}}/></div></div>}):<div className="py-8 text-center text-muted-foreground">{copy.empty}</div>}</div></CardContent></Card>
  <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>{copy.statusSummary}</CardTitle></CardHeader><CardContent className="space-y-3"><StatusRow label={copy.pending} value={number.format(pendingOrders)} className="text-yellow-500"/><StatusRow label={copy.delivered} value={number.format(deliveredOrders)} className="text-green-500"/><StatusRow label={copy.transit} value={number.format(ordered)} className="text-blue-500"/></CardContent></Card><Card><CardHeader><CardTitle>{copy.top}</CardTitle></CardHeader><CardContent><div className="space-y-3">{[...categoryStats].sort((a,b)=>b.total-a.total).slice(0,3).map((stat,idx)=><div key={stat.category} className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="h-3 w-3 rounded-full bg-primary" style={{opacity:1-idx*0.2}}/><span className="text-sm text-muted-foreground">{stat.category}</span></div><span className="font-semibold text-accent">{money.format(stat.total)}</span></div>)}</div></CardContent></Card></div>
 </div></AppLayout>
}
function Kpi({title,value,icon}:{title:string;value:string;icon:React.ReactNode}){return <Card><CardHeader className="pb-2"><div className="flex items-center justify-between"><CardTitle className="text-sm font-medium text-muted-foreground">{title}</CardTitle>{icon}</div></CardHeader><CardContent><div className="text-3xl font-bold text-accent">{value}</div></CardContent></Card>}
function StatusRow({label,value,className}:{label:string;value:string;className:string}){return <div className="flex items-center justify-between"><span className="text-muted-foreground">{label}</span><span className={`text-lg font-semibold ${className}`}>{value}</span></div>}
