"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowRight, ArrowUpDown, CalendarRange, Eye, Plus, Search, SlidersHorizontal, Sprout } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Plan={id:string;name:string;season:string|null;start_date:string;end_date:string;status:string;objective:string|null}
type Cycle={id:string;game_plan_id:string;crop_name:string;variety:string|null;cycle_type:string;planned_start_date:string;target_harvest_date:string|null;status:string;planned_area_sqm:number|null;target_quantity:number|null;target_unit:string|null}
type Succession={id:string;crop_cycle_id:string;sequence_no:number;planned_sow_date:string;planned_transplant_date:string|null;planned_first_harvest_date:string|null;planned_last_harvest_date:string|null;planned_area_sqm:number|null;status:string}

const copy={
 en:{eyebrow:"Dietrich · Season Plan",title:"The Codified Game Plan, without the editor",description:"One row per crop cycle with its succession rhythm. Use this to read the season; open the advanced editor only when the plan itself must change.",crops:"Crop cycles",successions:"Successions",direct:"Direct sow",transplant:"Transplant",crop:"Crop",type:"Propagation",cadence:"Successions",start:"First sow",field:"First field date",harvest:"Harvest window",area:"Planned area",target:"Target",status:"Status",objective:"Operating objective",advanced:"Edit Game Plan",source:"Canonical plan structure from orchard_game_plans, orchard_crop_cycles and orchard_crop_successions."},
 es:{eyebrow:"Dietrich · Plan de Temporada",title:"El Codified Game Plan, sin el editor",description:"Una fila por ciclo de cultivo con su ritmo de sucesiones. Esta vista sirve para leer la temporada; el editor avanzado se abre sólo cuando hay que cambiar el plan.",crops:"Ciclos de cultivo",successions:"Sucesiones",direct:"Siembra directa",transplant:"Trasplante",crop:"Cultivo",type:"Propagación",cadence:"Sucesiones",start:"Primera siembra",field:"Primera entrada a campo",harvest:"Ventana cosecha",area:"Área planificada",target:"Objetivo",status:"Estado",objective:"Objetivo operativo",advanced:"Editar Game Plan",source:"Estructura canónica desde orchard_game_plans, orchard_crop_cycles y orchard_crop_successions."},
 de:{eyebrow:"Dietrich · Saisonplan",title:"Der Codified Game Plan ohne Editor",description:"Eine Zeile je Kulturzyklus mit dem Rhythmus seiner Folgen. Zum Lesen der Saison; der erweiterte Editor wird nur geöffnet, wenn der Plan geändert werden muss.",crops:"Kulturzyklen",successions:"Folgen",direct:"Direktsaat",transplant:"Verpflanzung",crop:"Kultur",type:"Vermehrung",cadence:"Folgen",start:"Erste Aussaat",field:"Erster Feldtermin",harvest:"Erntefenster",area:"Geplante Fläche",target:"Ziel",status:"Status",objective:"Betriebsziel",advanced:"Game Plan bearbeiten",source:"Kanonische Planstruktur aus orchard_game_plans, orchard_crop_cycles und orchard_crop_successions."},
} as const
const localeMap:Record<Locale,string>={en:"en-US",es:"es-CL",de:"de-DE"}
const dateLabel=(v:string|null,locale:string)=>v?new Date(`${v}T12:00:00-04:00`).toLocaleDateString(locale,{day:"2-digit",month:"short",year:"numeric",timeZone:"America/Santiago"}):"—"
const typeLabel=(value:string,lang:Locale)=>value==="direct_sow"?({en:"Direct sow",es:"Siembra directa",de:"Direktsaat"}[lang]):value==="transplant"?({en:"Transplant",es:"Trasplante",de:"Verpflanzung"}[lang]):value.replaceAll("_"," ")
const monthKeys=(start:string,end:string)=>{const months:string[]=[];const cursor=new Date(`${start.slice(0,7)}-01T12:00:00`);const stop=new Date(`${end.slice(0,7)}-01T12:00:00`);while(cursor<=stop){months.push(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}`);cursor.setMonth(cursor.getMonth()+1)}return months}
const timelinePosition=(value:string,start:string,end:string)=>{const first=new Date(`${start}T12:00:00`).getTime();const last=new Date(`${end}T12:00:00`).getTime();const current=new Date(`${value}T12:00:00`).getTime();return Math.max(0,Math.min(100,((current-first)/(last-first))*100))}

export default function DietrichSeasonPlanPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const lang:Locale=language;const text=copy[lang];const locale=localeMap[lang]
 const [plans,setPlans]=useState<Plan[]>([]),[cycles,setCycles]=useState<Cycle[]>([]),[successions,setSuccessions]=useState<Succession[]>([]),[loading,setLoading]=useState(true)
 const [query,setQuery]=useState("")
 useEffect(()=>{let live=true;void Promise.all([
  supabase.from("orchard_game_plans").select("id,name,season,start_date,end_date,status,objective").order("start_date",{ascending:false}),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name,variety,cycle_type,planned_start_date,target_harvest_date,status,planned_area_sqm,target_quantity,target_unit").order("crop_name"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id,sequence_no,planned_sow_date,planned_transplant_date,planned_first_harvest_date,planned_last_harvest_date,planned_area_sqm,status").order("sequence_no"),
 ]).then(([p,c,s])=>{if(!live)return;setPlans((p.data??[]) as Plan[]);setCycles((c.data??[]) as Cycle[]);setSuccessions((s.data??[]) as Succession[]);setLoading(false)});return()=>{live=false}},[supabase])
 const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null;const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const scoped=plan?cycles.filter(c=>c.game_plan_id===plan.id):[];const rows=scoped.map(c=>{const ss=successions.filter(s=>s.crop_cycle_id===c.id).sort((a,b)=>a.sequence_no-b.sequence_no);return{c,ss,first:ss[0],last:ss[ss.length-1]}});const visibleRows=rows.filter(({c})=>`${c.crop_name} ${c.variety??""}`.toLowerCase().includes(query.trim().toLowerCase()))
 const direct=rows.filter(r=>r.c.cycle_type==="direct_sow").length;const transplant=rows.filter(r=>r.c.cycle_type==="transplant").length;const successionCount=rows.reduce((n,r)=>n+r.ss.length,0);const advancedHref=`/${language}/orchard/game-plan${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`
 const months=plan?monthKeys(plan.start_date,plan.end_date):[]
 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1560px] px-4 py-8 sm:px-6 lg:px-8">
  <header className="mb-8 max-w-4xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">{text.eyebrow}</p><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-normal sm:text-4xl">{text.title}</h1>{plan?.season?<Badge variant="secondary">{plan.season}</Badge>:null}</div><p className="mt-3 text-sm leading-6 text-muted-foreground sm:text-base">{text.description}</p>{plan?.objective?<p className="mt-4 border-l-2 border-[var(--bs-divider-subtle)] pl-4 text-sm leading-6 text-muted-foreground"><strong className="font-medium text-foreground">{text.objective}:</strong> {plan.objective}</p>:null}</header>
  {loading?<div className="py-12 text-sm text-muted-foreground">…</div>:<>
   <section className="mb-6 grid gap-px bg-[var(--bs-divider-subtle)] sm:grid-cols-4"><div className="bg-[var(--bs-surface-primary)] p-5"><CalendarRange className="h-4 w-4 text-muted-foreground"/><p className="mt-4 text-xs uppercase tracking-wide text-muted-foreground">{text.crops}</p><p className="mt-2 text-3xl tabular-nums">{rows.length}</p></div><div className="bg-[var(--bs-surface-primary)] p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{text.successions}</p><p className="mt-2 text-3xl tabular-nums">{successionCount}</p></div><div className="bg-[var(--bs-surface-primary)] p-5"><Sprout className="h-4 w-4 text-muted-foreground"/><p className="mt-4 text-xs uppercase tracking-wide text-muted-foreground">{text.direct}</p><p className="mt-2 text-3xl tabular-nums">{direct}</p></div><div className="bg-[var(--bs-surface-primary)] p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{text.transplant}</p><p className="mt-2 text-3xl tabular-nums">{transplant}</p></div></section>
   <section className="overflow-hidden rounded-xl border border-[var(--orchard-line)] bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-[var(--orchard-line)] p-3 lg:flex-row lg:items-center"><label className="flex min-h-11 flex-1 items-center gap-2 rounded-lg border border-[var(--orchard-line)] bg-white px-3 lg:max-w-sm"><Search className="h-4 w-4 text-muted-foreground"/><span className="sr-only">Search crops</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search crops…" className="h-9 w-full border-0 bg-transparent text-sm outline-none"/></label><div className="flex flex-wrap gap-2"><button type="button" className="inline-flex min-h-10 items-center gap-2 rounded-lg px-3 text-sm text-muted-foreground hover:bg-[var(--orchard-green-soft)]"><Eye className="h-4 w-4"/>{text.crops}</button><button type="button" className="inline-flex min-h-10 items-center gap-2 rounded-lg px-3 text-sm text-muted-foreground hover:bg-[var(--orchard-green-soft)]"><SlidersHorizontal className="h-4 w-4"/>Filters</button><button type="button" className="inline-flex min-h-10 items-center gap-2 rounded-lg px-3 text-sm text-muted-foreground hover:bg-[var(--orchard-green-soft)]"><ArrowUpDown className="h-4 w-4"/>{text.cadence}</button></div><Link href={advancedHref} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-[var(--orchard-green)] px-4 text-sm font-medium text-white"><Plus className="h-4 w-4"/>{text.advanced}</Link></div>
    <div className="overflow-x-auto"><div className="min-w-[1120px]"><div className="grid border-b border-[var(--orchard-line)] bg-[#f5f7f4]" style={{gridTemplateColumns:`230px repeat(${Math.max(months.length,1)},minmax(82px,1fr))`}}><div className="border-r border-[var(--orchard-line)] px-4 py-4 text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">{text.crop}</div>{months.map(month=><div key={month} className="border-r border-[var(--orchard-line)] px-2 py-4 text-center text-sm font-medium last:border-r-0">{new Date(`${month}-01T12:00:00`).toLocaleDateString(locale,{month:"long"})}</div>)}</div>
     <div>{visibleRows.map(({c,ss})=><div key={c.id} className="grid min-h-24 border-b border-[var(--orchard-line)] last:border-b-0" style={{gridTemplateColumns:`230px minmax(0,1fr)`}}><div className="border-r border-[var(--orchard-line)] p-4"><p className="font-medium">{c.crop_name}</p><p className="mt-1 text-xs text-muted-foreground">{c.variety??typeLabel(c.cycle_type,lang)} · {ss.length} {text.cadence.toLowerCase()}</p></div><div className="relative bg-[repeating-linear-gradient(90deg,transparent_0,transparent_calc(100%/12_-_1px),#eef1ed_calc(100%/12_-_1px),#eef1ed_calc(100%/12))]">{ss.map(s=>{const start=s.planned_sow_date;const end=s.planned_last_harvest_date??s.planned_first_harvest_date??s.planned_transplant_date??start;const left=plan?timelinePosition(start,plan.start_date,plan.end_date):0;const right=plan?timelinePosition(end,plan.start_date,plan.end_date):left;return <div key={s.id} className="absolute flex h-5 min-w-3 items-center rounded-full bg-[var(--orchard-green)] px-2 text-[10px] font-medium text-white shadow-sm" style={{left:`${left}%`,width:`${Math.max(1.5,right-left)}%`,top:`${13+(s.sequence_no-1)%3*24}px`}} title={`${c.crop_name} · ${dateLabel(start,locale)} — ${dateLabel(end,locale)}`}><span className="truncate">{s.sequence_no}</span></div>})}</div></div>)}</div>
    </div></div>
   </section>
   <div className="mt-5 flex flex-col gap-3 border-t border-[var(--bs-divider-subtle)] pt-5 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span>{text.source}</span><Link href={advancedHref} className="inline-flex items-center gap-2 text-sm text-foreground">{text.advanced}<ArrowRight className="h-4 w-4"/></Link></div>
  </>}
 </main></AppLayout>
}
