"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { Download, ExternalLink, Smartphone, Wifi, WifiOff } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { useLanguage } from "@/lib/hooks/use-language"

type InstallPromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> }

export default function OrchardMobilePage(){
 const {language}=useLanguage();const es=language==="es";const [online,setOnline]=useState(true);const [installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null);const [standalone,setStandalone]=useState(false);const [registered,setRegistered]=useState(false)
 useEffect(()=>{setOnline(navigator.onLine);setStandalone(window.matchMedia("(display-mode: standalone)").matches);const onOnline=()=>setOnline(true);const onOffline=()=>setOnline(false);const before=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent)};window.addEventListener("online",onOnline);window.addEventListener("offline",onOffline);window.addEventListener("beforeinstallprompt",before);if("serviceWorker" in navigator){navigator.serviceWorker.register("/orchard-sw.js",{scope:"/orchard/"}).then(()=>setRegistered(true)).catch(()=>setRegistered(false))}return()=>{window.removeEventListener("online",onOnline);window.removeEventListener("offline",onOffline);window.removeEventListener("beforeinstallprompt",before)}},[])
 async function install(){if(!installPrompt)return;await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==="accepted")setStandalone(true);setInstallPrompt(null)}
 return <AppLayout><PageHeader title={es?"Orchard Mobile":"Orchard Mobile"} description={es?"Instala el modo terreno como aplicación y valida conectividad antes de registrar operaciones.":"Install Field Mode as an app and verify connectivity before recording operational changes."}/><OrchardNavigation/><div className="space-y-6 p-3 pb-24 sm:p-8">
 <div className="grid gap-4 sm:grid-cols-3"><State label={es?"Conectividad":"Connectivity"} value={online?(es?"En línea":"Online"):(es?"Sin conexión":"Offline")} icon={online?<Wifi className="h-5 w-5"/>:<WifiOff className="h-5 w-5"/>}/><State label={es?"Instalación":"Installation"} value={standalone?(es?"Instalada":"Installed"):(es?"Navegador":"Browser")} icon={<Smartphone className="h-5 w-5"/>}/><State label="Service worker" value={registered?(es?"Activo":"Active"):(es?"No registrado":"Not registered")} icon={<Download className="h-5 w-5"/>}/></div>
 <Card><CardHeader><CardTitle>{es?"Aplicación de terreno":"Field application"}</CardTitle><CardDescription>{es?"La app usa un shell offline seguro, pero las mutaciones operacionales siguen requiriendo conexión para evitar replays silenciosos o conflictos de datos.":"The app uses an offline-safe shell, but operational mutations still require connectivity to avoid silent replay and data conflicts."}</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3">{installPrompt&&<Button onClick={()=>void install()}><Download className="mr-2 h-4 w-4"/>{es?"Instalar BSFC":"Install BSFC"}</Button>}<Button asChild variant="outline"><Link href={`/${language}/orchard/field`}><Smartphone className="mr-2 h-4 w-4"/>{es?"Abrir Field Mode":"Open Field Mode"}</Link></Button>{!installPrompt&&!standalone&&<Badge variant="outline">{es?"Usa “Agregar a pantalla de inicio” si tu navegador no muestra el botón de instalación.":"Use Add to Home Screen if your browser does not expose the install prompt."}</Badge>}</CardContent></Card>
 <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>{es?"Ya preparado para móvil":"Already mobile-ready"}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-muted-foreground"><p>• {es?"Field Mode para tareas, vivero, salud y cosecha":"Field Mode for tasks, nursery, health and harvest"}</p><p>• {es?"Captura de cámara para evidencia privada":"Camera capture for private evidence"}</p><p>• {es?"Controles táctiles y entrada rápida":"Touch-sized controls and quick entry"}</p><p>• {es?"Shell instalable y fallback offline":"Installable shell and offline fallback"}</p></CardContent></Card><Card><CardHeader><CardTitle>{es?"Límite deliberado":"Deliberate limit"}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><p>{es?"No almacenamos cosechas, tratamientos o tareas pendientes para sincronizarlas silenciosamente después. Esas acciones tienen implicancias de inventario, trazabilidad y concurrencia.":"We do not queue harvests, treatments or tasks for silent later synchronization. Those actions affect inventory, traceability and concurrency."}</p><Button asChild variant="link" className="h-auto p-0"><Link href={`/${language}/orchard/field`}>{es?"Ir al flujo operacional":"Go to operational flow"}<ExternalLink className="ml-1 h-3 w-3"/></Link></Button></CardContent></Card></div>
 </div></AppLayout>
}
function State({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <Card><CardContent className="flex items-center gap-3 p-4"><div className="rounded-lg bg-muted p-2">{icon}</div><div><p className="font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>}
