"use client"

import type { ReactNode } from "react"
import { useEffect, useState } from "react"
import Link from "next/link"
import { Database, Download, ExternalLink, PackageCheck, Share2, Smartphone, Wifi, WifiOff } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { useLanguage, type Language } from "@/lib/hooks/use-language"
import { ALL_GAME_PLANS, withGamePlanQuery } from "@/lib/orchard/game-plan-scope"

type InstallPromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> }

const copy:Record<Language,Record<string,string>>={
 en:{description:"Installable field PWA plus a native-ready iOS/Android packaging workspace without silently queueing mutations.",preserved:"Game Plan context preserved",preservedHelp:"All quick links and the shared Field Mode URL preserve the game_plan parameter. Destination modules validate the ID against authorized Game Plans before applying scope.",connectivity:"Connectivity",online:"Online",offline:"Offline",pwa:"PWA install",installed:"Installed",browser:"Browser",active:"Active",notRegistered:"Not registered",storage:"Storage persistence",persistent:"Persistent",evictable:"Evictable",unknown:"Unknown",nativePackage:"Native package",buildReady:"Build-ready",fieldApp:"Field application",fieldAppHelp:"The PWA adds shortcuts to Field, Harvest, Nursery, Care and Health. Static resources can persist; authenticated data and writes remain network-first to protect traceability, inventory and concurrency.",install:"Install BSFC",openField:"Open Field Mode",protectCache:"Protect local cache",share:"Share shortcut",installHint:"Use Add to Home Screen if your browser does not expose the install prompt.",harvest:"Harvest",nursery:"Nursery",care:"Care",health:"Health",nativeWorkspace:"Native packaging workspace",nativeWorkspaceHelp:"Blackswan Facility Core now has an isolated Capacitor 8.5.0 shell for iOS and Android, using bundle id app.blackswn.facilitycore and the HTTPS production origin.",origin:"Origin",distribution:"Distribution",unsigned:"Unsigned / not published",nativeGate:"The final gate remains real: generate native projects, configure signing/privacy, test physical devices, and distribute through the approved channel. App Store/Google Play is not shown as complete until that actually happens.",appLike:"App-like field experience",shortcutBullet:"Installed-app shortcuts for frequent field flows",cameraBullet:"Camera capture for private evidence",touchBullet:"Touch-sized controls and quick entry",cacheBullet:"Persistent static cache when the device grants it",shareBullet:"Native share sheet for Field Mode links",offlineBoundary:"Deliberate offline boundary",offlineHelp:"We do not queue harvests, treatments, inventory or tasks for silent later synchronization. The native shell keeps the same rule until an explicit transactional queue with conflict resolution exists.",goOperational:"Go to operational flow",shareText:"Open Orchard Field Mode"},
 es:{description:"PWA instalable para terreno y workspace nativo listo para empaquetar iOS/Android sin poner mutaciones en una cola invisible.",preserved:"Contexto de Game Plan preservado",preservedHelp:"Todos los accesos rápidos y el enlace compartido conservan el parámetro game_plan. Los módulos destino validan el ID contra los Game Plans autorizados antes de aplicar scope.",connectivity:"Conectividad",online:"En línea",offline:"Sin conexión",pwa:"Instalación PWA",installed:"Instalada",browser:"Navegador",active:"Activo",notRegistered:"No registrado",storage:"Persistencia local",persistent:"Persistente",evictable:"Evictable",unknown:"Desconocida",nativePackage:"Paquete nativo",buildReady:"Listo para build",fieldApp:"Aplicación de terreno",fieldAppHelp:"La PWA agrega accesos rápidos a Field, Harvest, Nursery, Care y Health. Los recursos estáticos sí se conservan; datos autenticados y escrituras siguen network-first para proteger trazabilidad, inventario y concurrencia.",install:"Instalar BSFC",openField:"Abrir Field Mode",protectCache:"Proteger cache local",share:"Compartir acceso",installHint:"Usa “Agregar a pantalla de inicio” si tu navegador no muestra el botón de instalación.",harvest:"Cosecha",nursery:"Vivero",care:"Cuidados",health:"Sanidad",nativeWorkspace:"Workspace nativo",nativeWorkspaceHelp:"Blackswan Facility Core ya tiene un shell Capacitor 8.5.0 aislado para iOS y Android, con bundle id app.blackswn.facilitycore y origen HTTPS de producción.",origin:"Origen",distribution:"Distribución",unsigned:"No firmada / no publicada",nativeGate:"El gate final sigue siendo real: generar proyectos nativos, configurar firma y privacidad, probar en dispositivos físicos y distribuir por el canal aprobado. No mostramos App Store/Google Play como completo hasta que eso ocurra.",appLike:"Experiencia tipo app",shortcutBullet:"Accesos rápidos desde el icono instalado",cameraBullet:"Captura de cámara para evidencia privada",touchBullet:"Controles táctiles y entrada rápida",cacheBullet:"Cache estático persistente cuando el dispositivo lo autoriza",shareBullet:"Compartir Field Mode usando el share sheet nativo",offlineBoundary:"Límite deliberado",offlineHelp:"No almacenamos cosechas, tratamientos, inventario o tareas pendientes para sincronizarlos silenciosamente después. El shell nativo mantiene la misma regla hasta que exista una cola transaccional explícita con resolución de conflictos.",goOperational:"Ir al flujo operacional",shareText:"Abrir Orchard Field Mode"},
 de:{description:"Installierbare Feld-PWA plus nativer iOS/Android-Packaging-Arbeitsbereich, ohne Änderungen unsichtbar in eine Warteschlange zu stellen.",preserved:"Game-Plan-Kontext beibehalten",preservedHelp:"Alle Schnellzugriffe und der geteilte Field-Mode-Link behalten den Parameter game_plan bei. Zielmodule validieren die ID gegen autorisierte Game Plans, bevor der Bereich angewendet wird.",connectivity:"Verbindung",online:"Online",offline:"Offline",pwa:"PWA-Installation",installed:"Installiert",browser:"Browser",active:"Aktiv",notRegistered:"Nicht registriert",storage:"Lokale Persistenz",persistent:"Persistent",evictable:"Löschbar",unknown:"Unbekannt",nativePackage:"Native App",buildReady:"Build-bereit",fieldApp:"Feldanwendung",fieldAppHelp:"Die PWA bietet Schnellzugriffe auf Field, Harvest, Nursery, Care und Health. Statische Ressourcen können lokal bleiben; authentifizierte Daten und Schreibvorgänge bleiben network-first, um Rückverfolgbarkeit, Inventar und Parallelität zu schützen.",install:"BSFC installieren",openField:"Field Mode öffnen",protectCache:"Lokalen Cache schützen",share:"Zugriff teilen",installHint:"Verwende „Zum Startbildschirm hinzufügen“, wenn dein Browser keine Installationsschaltfläche anbietet.",harvest:"Ernte",nursery:"Jungpflanzen",care:"Pflege",health:"Pflanzengesundheit",nativeWorkspace:"Nativer Packaging-Arbeitsbereich",nativeWorkspaceHelp:"Blackswan Facility Core besitzt bereits eine isolierte Capacitor-8.5.0-Shell für iOS und Android mit Bundle-ID app.blackswn.facilitycore und der HTTPS-Produktionsadresse.",origin:"Quelle",distribution:"Verteilung",unsigned:"Nicht signiert / nicht veröffentlicht",nativeGate:"Das letzte Gate bleibt real: native Projekte erzeugen, Signierung und Datenschutz konfigurieren, auf physischen Geräten testen und über den genehmigten Kanal verteilen. App Store/Google Play wird erst als abgeschlossen angezeigt, wenn das tatsächlich erfolgt ist.",appLike:"App-ähnliche Felderfahrung",shortcutBullet:"Schnellzugriffe der installierten App für häufige Feldabläufe",cameraBullet:"Kameraerfassung für private Nachweise",touchBullet:"Touchgerechte Bedienelemente und schnelle Eingabe",cacheBullet:"Persistenter statischer Cache, wenn das Gerät ihn erlaubt",shareBullet:"Nativer Share-Sheet für Field-Mode-Links",offlineBoundary:"Bewusste Offline-Grenze",offlineHelp:"Ernten, Behandlungen, Inventar oder Aufgaben werden nicht für eine stille spätere Synchronisierung vorgemerkt. Die native Shell behält dieselbe Regel bei, bis eine explizite transaktionale Warteschlange mit Konfliktauflösung existiert.",goOperational:"Zum operativen Ablauf",shareText:"Orchard Field Mode öffnen"},
}

export default function OrchardMobilePage(){
 const {language}=useLanguage();const text=copy[language];const [online,setOnline]=useState(true);const [installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null);const [standalone,setStandalone]=useState(false);const [registered,setRegistered]=useState(false);const [persistent,setPersistent]=useState<boolean|null>(null);const [shareable,setShareable]=useState(false);const [gamePlanId,setGamePlanId]=useState<string>(ALL_GAME_PLANS)
 useEffect(()=>{setOnline(navigator.onLine);setStandalone(window.matchMedia("(display-mode: standalone)").matches);setShareable(typeof navigator.share==="function");setGamePlanId(new URLSearchParams(window.location.search).get("game_plan")||ALL_GAME_PLANS);void navigator.storage?.persisted().then(setPersistent).catch(()=>setPersistent(null));const onOnline=()=>setOnline(true);const onOffline=()=>setOnline(false);const before=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent)};window.addEventListener("online",onOnline);window.addEventListener("offline",onOffline);window.addEventListener("beforeinstallprompt",before);if("serviceWorker" in navigator){navigator.serviceWorker.register("/orchard-sw.js",{scope:"/orchard/"}).then(()=>setRegistered(true)).catch(()=>setRegistered(false))}return()=>{window.removeEventListener("online",onOnline);window.removeEventListener("offline",onOffline);window.removeEventListener("beforeinstallprompt",before)}},[])
 const scopedHref=(path:string)=>withGamePlanQuery(`/${language}${path}`,gamePlanId)
 async function install(){if(!installPrompt)return;await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==="accepted")setStandalone(true);setInstallPrompt(null)}
 async function persistStorage(){if(!navigator.storage?.persist)return;const value=await navigator.storage.persist();setPersistent(value)}
 async function share(){if(!navigator.share)return;await navigator.share({title:"Blackswan Facility Core · Orchard",text:text.shareText,url:`${window.location.origin}${scopedHref("/orchard/field")}`})}
 return <AppLayout><OrchardNavigation/><PageHeader title="Orchard Mobile" description={text.description}/><div className="space-y-6 p-3 pb-24 sm:p-8">
 {gamePlanId!==ALL_GAME_PLANS&&<Card><CardContent className="p-4"><p className="text-sm font-medium">{text.preserved}</p><p className="mt-1 text-xs text-muted-foreground">{text.preservedHelp}</p></CardContent></Card>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><State label={text.connectivity} value={online?text.online:text.offline} icon={online?<Wifi className="h-5 w-5"/>:<WifiOff className="h-5 w-5"/>}/><State label={text.pwa} value={standalone?text.installed:text.browser} icon={<Smartphone className="h-5 w-5"/>}/><State label="Service worker" value={registered?text.active:text.notRegistered} icon={<Download className="h-5 w-5"/>}/><State label={text.storage} value={persistent===true?text.persistent:persistent===false?text.evictable:text.unknown} icon={<Database className="h-5 w-5"/>}/><State label={text.nativePackage} value={text.buildReady} icon={<PackageCheck className="h-5 w-5"/>}/></div>
 <Card><CardHeader><CardTitle>{text.fieldApp}</CardTitle><CardDescription>{text.fieldAppHelp}</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3">{installPrompt&&<Button onClick={()=>void install()}><Download className="mr-2 h-4 w-4"/>{text.install}</Button>}<Button asChild variant="outline"><Link href={scopedHref("/orchard/field")}><Smartphone className="mr-2 h-4 w-4"/>{text.openField}</Link></Button>{persistent===false&&<Button variant="outline" onClick={()=>void persistStorage()}><Database className="mr-2 h-4 w-4"/>{text.protectCache}</Button>}{shareable&&<Button variant="outline" onClick={()=>void share()}><Share2 className="mr-2 h-4 w-4"/>{text.share}</Button>}{!installPrompt&&!standalone&&<Badge variant="outline">{text.installHint}</Badge>}</CardContent></Card>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Quick href={scopedHref("/orchard/field")} label="Field"/><Quick href={scopedHref("/orchard/field/harvest")} label={text.harvest}/><Quick href={scopedHref("/orchard/field/nursery")} label={text.nursery}/><Quick href={scopedHref("/orchard/care")} label={text.care}/><Quick href={scopedHref("/orchard/pests")} label={text.health}/></div>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><PackageCheck className="h-5 w-5"/>{text.nativeWorkspace}</CardTitle><CardDescription>{text.nativeWorkspaceHelp}</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm md:grid-cols-3"><Datum label={text.origin} value="https://blackswn.app"/><Datum label="Bundle ID" value="app.blackswn.facilitycore"/><Datum label={text.distribution} value={text.unsigned}/><p className="md:col-span-3 text-muted-foreground">{text.nativeGate}</p></CardContent></Card>
 <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>{text.appLike}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-muted-foreground"><p>• {text.shortcutBullet}</p><p>• {text.cameraBullet}</p><p>• {text.touchBullet}</p><p>• {text.cacheBullet}</p><p>• {text.shareBullet}</p></CardContent></Card><Card><CardHeader><CardTitle>{text.offlineBoundary}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><p>{text.offlineHelp}</p><Button asChild variant="link" className="h-auto p-0"><Link href={scopedHref("/orchard/field")}>{text.goOperational}<ExternalLink className="ml-1 h-3 w-3"/></Link></Button></CardContent></Card></div>
 </div></AppLayout>
}
function State({label,value,icon}:{label:string;value:string;icon:ReactNode}){return <Card><CardContent className="flex items-center gap-3 p-4"><div className="rounded-lg bg-muted p-2">{icon}</div><div><p className="font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>}
function Quick({href,label}:{href:string;label:string}){return <Card><CardContent className="p-3"><Button asChild variant="ghost" className="w-full justify-start"><Link href={href}><Smartphone className="mr-2 h-4 w-4"/>{label}</Link></Button></CardContent></Card>}
function Datum({label,value}:{label:string;value:string}){return <div className="rounded-lg border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
