"use client"

import type { ReactNode } from "react"
import { useEffect, useState } from "react"
import Link from "next/link"
import { Database, Download, ExternalLink, PackageCheck, Share2, Smartphone, Wifi, WifiOff } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { useLanguage } from "@/lib/hooks/use-language"

type InstallPromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> }

export default function OrchardMobilePage(){
 const {language}=useLanguage();const es=language==="es";const [online,setOnline]=useState(true);const [installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null);const [standalone,setStandalone]=useState(false);const [registered,setRegistered]=useState(false);const [persistent,setPersistent]=useState<boolean|null>(null);const [shareable,setShareable]=useState(false)
 useEffect(()=>{setOnline(navigator.onLine);setStandalone(window.matchMedia("(display-mode: standalone)").matches);setShareable(typeof navigator.share==="function");void navigator.storage?.persisted().then(setPersistent).catch(()=>setPersistent(null));const onOnline=()=>setOnline(true);const onOffline=()=>setOnline(false);const before=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent)};window.addEventListener("online",onOnline);window.addEventListener("offline",onOffline);window.addEventListener("beforeinstallprompt",before);if("serviceWorker" in navigator){navigator.serviceWorker.register("/orchard-sw.js",{scope:"/orchard/"}).then(()=>setRegistered(true)).catch(()=>setRegistered(false))}return()=>{window.removeEventListener("online",onOnline);window.removeEventListener("offline",onOffline);window.removeEventListener("beforeinstallprompt",before)}},[])
 async function install(){if(!installPrompt)return;await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==="accepted")setStandalone(true);setInstallPrompt(null)}
 async function persistStorage(){if(!navigator.storage?.persist)return;const value=await navigator.storage.persist();setPersistent(value)}
 async function share(){if(!navigator.share)return;await navigator.share({title:"Blackswan Facility Core · Orchard",text:es?"Abrir Orchard Field Mode":"Open Orchard Field Mode",url:`${window.location.origin}/${language}/orchard/field`})}
 return <AppLayout><PageHeader title="Orchard Mobile" description={es?"PWA instalable para terreno y workspace nativo listo para empaquetar iOS/Android sin poner mutaciones en una cola invisible.":"Installable field PWA plus a native-ready iOS/Android packaging workspace without silently queueing mutations."}/><OrchardNavigation/><div className="space-y-6 p-3 pb-24 sm:p-8">
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><State label={es?"Conectividad":"Connectivity"} value={online?(es?"En línea":"Online"):(es?"Sin conexión":"Offline")} icon={online?<Wifi className="h-5 w-5"/>:<WifiOff className="h-5 w-5"/>}/><State label={es?"Instalación PWA":"PWA install"} value={standalone?(es?"Instalada":"Installed"):(es?"Navegador":"Browser")} icon={<Smartphone className="h-5 w-5"/>}/><State label="Service worker" value={registered?(es?"Activo":"Active"):(es?"No registrado":"Not registered")} icon={<Download className="h-5 w-5"/>}/><State label={es?"Persistencia local":"Storage persistence"} value={persistent===true?(es?"Persistente":"Persistent"):persistent===false?(es?"Evictable":"Evictable"):(es?"Desconocida":"Unknown")} icon={<Database className="h-5 w-5"/>}/><State label={es?"Paquete nativo":"Native package"} value={es?"Listo para build":"Build-ready"} icon={<PackageCheck className="h-5 w-5"/>}/></div>
 <Card><CardHeader><CardTitle>{es?"Aplicación de terreno":"Field application"}</CardTitle><CardDescription>{es?"La PWA agrega accesos rápidos a Field, Harvest, Nursery, Care y Health. Los recursos estáticos sí se conservan; datos autenticados y escrituras siguen network-first para proteger trazabilidad, inventario y concurrencia.":"The PWA adds shortcuts to Field, Harvest, Nursery, Care and Health. Static resources can persist; authenticated data and writes remain network-first to protect traceability, inventory and concurrency."}</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3">{installPrompt&&<Button onClick={()=>void install()}><Download className="mr-2 h-4 w-4"/>{es?"Instalar BSFC":"Install BSFC"}</Button>}<Button asChild variant="outline"><Link href={`/${language}/orchard/field`}><Smartphone className="mr-2 h-4 w-4"/>{es?"Abrir Field Mode":"Open Field Mode"}</Link></Button>{persistent===false&&<Button variant="outline" onClick={()=>void persistStorage()}><Database className="mr-2 h-4 w-4"/>{es?"Proteger cache local":"Protect local cache"}</Button>}{shareable&&<Button variant="outline" onClick={()=>void share()}><Share2 className="mr-2 h-4 w-4"/>{es?"Compartir acceso":"Share shortcut"}</Button>}{!installPrompt&&!standalone&&<Badge variant="outline">{es?"Usa “Agregar a pantalla de inicio” si tu navegador no muestra el botón de instalación.":"Use Add to Home Screen if your browser does not expose the install prompt."}</Badge>}</CardContent></Card>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Quick href={`/${language}/orchard/field`} label="Field"/><Quick href={`/${language}/orchard/field/harvest`} label={es?"Cosecha":"Harvest"}/><Quick href={`/${language}/orchard/field/nursery`} label={es?"Vivero":"Nursery"}/><Quick href={`/${language}/orchard/care`} label={es?"Cuidados":"Care"}/><Quick href={`/${language}/orchard/pests`} label={es?"Sanidad":"Health"}/></div>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><PackageCheck className="h-5 w-5"/>{es?"Workspace nativo":"Native packaging workspace"}</CardTitle><CardDescription>{es?"Blackswan Facility Core ya tiene un shell Capacitor 8.5.0 aislado para iOS y Android, con bundle id app.blackswn.facilitycore y origen HTTPS de producción.":"Blackswan Facility Core now has an isolated Capacitor 8.5.0 shell for iOS and Android, using bundle id app.blackswn.facilitycore and the HTTPS production origin."}</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm md:grid-cols-3"><Datum label={es?"Origen":"Origin"} value="https://blackswn.app"/><Datum label="Bundle ID" value="app.blackswn.facilitycore"/><Datum label={es?"Distribución":"Distribution"} value={es?"No firmada / no publicada":"Unsigned / not published"}/><p className="md:col-span-3 text-muted-foreground">{es?"El gate final sigue siendo real: generar proyectos nativos, configurar firma y privacidad, probar en dispositivos físicos y distribuir por el canal aprobado. No mostramos App Store/Google Play como completo hasta que eso ocurra.":"The final gate remains real: generate native projects, configure signing/privacy, test physical devices, and distribute through the approved channel. App Store/Google Play is not shown as complete until that actually happens."}</p></CardContent></Card>
 <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>{es?"Experiencia tipo app":"App-like field experience"}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-muted-foreground"><p>• {es?"Accesos rápidos desde el icono instalado":"Installed-app shortcuts for frequent field flows"}</p><p>• {es?"Captura de cámara para evidencia privada":"Camera capture for private evidence"}</p><p>• {es?"Controles táctiles y entrada rápida":"Touch-sized controls and quick entry"}</p><p>• {es?"Cache estático persistente cuando el dispositivo lo autoriza":"Persistent static cache when the device grants it"}</p><p>• {es?"Compartir Field Mode usando el share sheet nativo":"Native share sheet for Field Mode links"}</p></CardContent></Card><Card><CardHeader><CardTitle>{es?"Límite deliberado":"Deliberate offline boundary"}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><p>{es?"No almacenamos cosechas, tratamientos, inventario o tareas pendientes para sincronizarlos silenciosamente después. El shell nativo mantiene la misma regla hasta que exista una cola transaccional explícita con resolución de conflictos.":"We do not queue harvests, treatments, inventory or tasks for silent later synchronization. The native shell keeps the same rule until an explicit transactional queue with conflict resolution exists."}</p><Button asChild variant="link" className="h-auto p-0"><Link href={`/${language}/orchard/field`}>{es?"Ir al flujo operacional":"Go to operational flow"}<ExternalLink className="ml-1 h-3 w-3"/></Link></Button></CardContent></Card></div>
 </div></AppLayout>
}
function State({label,value,icon}:{label:string;value:string;icon:ReactNode}){return <Card><CardContent className="flex items-center gap-3 p-4"><div className="rounded-lg bg-muted p-2">{icon}</div><div><p className="font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>}
function Quick({href,label}:{href:string;label:string}){return <Card><CardContent className="p-3"><Button asChild variant="ghost" className="w-full justify-start"><Link href={href}><Smartphone className="mr-2 h-4 w-4"/>{label}</Link></Button></CardContent></Card>}
function Datum({label,value}:{label:string;value:string}){return <div className="rounded-lg border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
