"use client"

import type { FormEvent } from "react"
import { useCallback, useEffect, useMemo, useState } from "react"
import { BadgeDollarSign, Plus, RefreshCw, Store } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Channel={id:string;name:string;channel_type:string;status:string;default_price_per_unit:number|null;default_unit:string|null;currency:string;notes:string|null}
type Target={id:string;crop_succession_id:string;sales_channel_id:string|null;planned_quantity:number;unit:string;target_price_per_unit:number;planned_revenue:number;notes:string|null}
type Succession={id:string;crop_cycle_id:string;sequence_no:number}
type Cycle={id:string;crop_name:string;variety:string|null}
type Harvest={crop_succession_id:string|null;sales_channel_id:string|null;quantity_harvested:number|null;harvest_unit:string|null;total_market_value:number|null;market_value_per_unit:number|null}
const money=(v:number,currency="CLP")=>new Intl.NumberFormat("es-CL",{style:"currency",currency,maximumFractionDigits:0}).format(v)

export default function OrchardCommercialPage(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const es=language==="es"
 const [channels,setChannels]=useState<Channel[]>([]);const [targets,setTargets]=useState<Target[]>([]);const [successions,setSuccessions]=useState<Succession[]>([]);const [cycles,setCycles]=useState<Cycle[]>([]);const [harvests,setHarvests]=useState<Harvest[]>([]);const [error,setError]=useState<string|null>(null);const [saving,setSaving]=useState(false)
 const [channelForm,setChannelForm]=useState({name:"",channel_type:"restaurant",default_price_per_unit:"",default_unit:"kg",currency:"CLP",notes:""});const [targetForm,setTargetForm]=useState({crop_succession_id:"",sales_channel_id:"none",planned_quantity:"",unit:"kg",target_price_per_unit:"",notes:""})
 const load=useCallback(async()=>{const [ch,t,s,c,h]=await Promise.all([supabase.from("orchard_sales_channels").select("*").order("name"),supabase.from("orchard_revenue_targets").select("*").order("created_at",{ascending:false}),supabase.from("orchard_crop_successions").select("id,crop_cycle_id,sequence_no").neq("status","cancelled"),supabase.from("orchard_crop_cycles").select("id,crop_name,variety"),supabase.from("orchard_harvest_records").select("crop_succession_id,sales_channel_id,quantity_harvested,harvest_unit,total_market_value,market_value_per_unit")]);const e=ch.error??t.error??s.error??c.error??h.error;if(e)setError(e.message);else{setChannels((ch.data??[]) as Channel[]);setTargets((t.data??[]) as Target[]);setSuccessions((s.data??[]) as Succession[]);setCycles((c.data??[]) as Cycle[]);setHarvests((h.data??[]) as Harvest[])}},[supabase]);useEffect(()=>{void load()},[load])
 const cycleById=useMemo(()=>new Map(cycles.map(c=>[c.id,c])),[cycles]);const channelById=useMemo(()=>new Map(channels.map(c=>[c.id,c])),[channels]);const successionLabel=(id:string)=>{const s=successions.find(x=>x.id===id);const c=s?cycleById.get(s.crop_cycle_id):null;return s?`${c?.crop_name??"Crop"}${c?.variety?` · ${c.variety}`:""} #${s.sequence_no}`:"—"}
 const planned=targets.reduce((sum,t)=>sum+Number(t.planned_revenue||0),0);const actual=harvests.reduce((sum,h)=>sum+Number(h.total_market_value??((h.quantity_harvested??0)*(h.market_value_per_unit??0))),0);const gap=actual-planned
 async function addChannel(e:FormEvent){e.preventDefault();if(!channelForm.name.trim())return;setSaving(true);setError(null);const r=await supabase.from("orchard_sales_channels").insert({name:channelForm.name.trim(),channel_type:channelForm.channel_type,default_price_per_unit:channelForm.default_price_per_unit?Number(channelForm.default_price_per_unit):null,default_unit:channelForm.default_unit.trim()||null,currency:channelForm.currency.trim()||"CLP",notes:channelForm.notes.trim()||null});if(r.error)setError(r.error.message);else{setChannelForm({name:"",channel_type:"restaurant",default_price_per_unit:"",default_unit:"kg",currency:"CLP",notes:""});await load()}setSaving(false)}
 async function addTarget(e:FormEvent){e.preventDefault();if(!targetForm.crop_succession_id||!targetForm.planned_quantity||!targetForm.target_price_per_unit)return;setSaving(true);setError(null);const r=await supabase.from("orchard_revenue_targets").insert({crop_succession_id:targetForm.crop_succession_id,sales_channel_id:targetForm.sales_channel_id==="none"?null:targetForm.sales_channel_id,planned_quantity:Number(targetForm.planned_quantity),unit:targetForm.unit.trim(),target_price_per_unit:Number(targetForm.target_price_per_unit),notes:targetForm.notes.trim()||null});if(r.error)setError(r.error.message);else{setTargetForm({crop_succession_id:"",sales_channel_id:"none",planned_quantity:"",unit:"kg",target_price_per_unit:"",notes:""});await load()}setSaving(false)}
 const rows=targets.map(t=>{const hs=harvests.filter(h=>h.crop_succession_id===t.crop_succession_id&&(!t.sales_channel_id||h.sales_channel_id===t.sales_channel_id));const actualRevenue=hs.reduce((sum,h)=>sum+Number(h.total_market_value??((h.quantity_harvested??0)*(h.market_value_per_unit??0))),0);const qty=hs.filter(h=>!h.harvest_unit||h.harvest_unit===t.unit).reduce((sum,h)=>sum+Number(h.quantity_harvested??0),0);return {...t,actualRevenue,actualQty:qty}})
 return <AppLayout><PageHeader title={es?"Plan Comercial":"Commercial Plan"} description={es?"Conecta producción planificada con canales, precio objetivo y valor real de cosecha.":"Connect planned production to channels, target price and realized harvest value."} actions={<Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>{es?"Actualizar":"Refresh"}</Button>}/><OrchardNavigation/><div className="space-y-6 p-3 pb-24 sm:p-8">
 {error&&<Card className="border-destructive/60"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>}
 <div className="grid gap-4 sm:grid-cols-3"><Metric label={es?"Ingreso planificado":"Planned revenue"} value={money(planned)}/><Metric label={es?"Valor cosechado":"Harvest value"} value={money(actual)}/><Metric label={es?"Desviación":"Variance"} value={money(gap)}/></div>
 <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Store className="h-5 w-5"/>{es?"Nuevo canal":"New sales channel"}</CardTitle><CardDescription>{es?"Mercado, restaurante, mayorista, suscripción, consumo interno u otro.":"Market, restaurant, wholesale, subscription, internal use or other."}</CardDescription></CardHeader><CardContent><form onSubmit={addChannel} className="grid gap-3 md:grid-cols-2"><Field label={es?"Nombre":"Name"}><Input value={channelForm.name} onChange={e=>setChannelForm(f=>({...f,name:e.target.value}))} required/></Field><Field label={es?"Tipo":"Type"}><Select value={channelForm.channel_type} onValueChange={v=>setChannelForm(f=>({...f,channel_type:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["farm_gate","restaurant","wholesale","market","subscription","internal","other"].map(v=><SelectItem key={v} value={v}>{v.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select></Field><Field label={es?"Precio por defecto":"Default price"}><Input type="number" min="0" value={channelForm.default_price_per_unit} onChange={e=>setChannelForm(f=>({...f,default_price_per_unit:e.target.value}))}/></Field><Field label={es?"Unidad":"Unit"}><Input value={channelForm.default_unit} onChange={e=>setChannelForm(f=>({...f,default_unit:e.target.value}))}/></Field><Field label={es?"Moneda":"Currency"}><Input value={channelForm.currency} onChange={e=>setChannelForm(f=>({...f,currency:e.target.value}))}/></Field><Field label={es?"Notas":"Notes"}><Input value={channelForm.notes} onChange={e=>setChannelForm(f=>({...f,notes:e.target.value}))}/></Field><Button className="md:col-span-2" disabled={saving}><Plus className="mr-2 h-4 w-4"/>{es?"Crear canal":"Create channel"}</Button></form></CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><BadgeDollarSign className="h-5 w-5"/>{es?"Objetivo de venta":"Revenue target"}</CardTitle><CardDescription>{es?"Planifica cantidad × precio por sucesión y canal; el valor real viene de cosecha.":"Plan quantity × price per succession/channel; actual value comes from harvest."}</CardDescription></CardHeader><CardContent><form onSubmit={addTarget} className="grid gap-3 md:grid-cols-2"><Field label={es?"Sucesión":"Succession"}><Select value={targetForm.crop_succession_id} onValueChange={v=>setTargetForm(f=>({...f,crop_succession_id:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{successions.map(s=><SelectItem key={s.id} value={s.id}>{successionLabel(s.id)}</SelectItem>)}</SelectContent></Select></Field><Field label={es?"Canal":"Channel"}><Select value={targetForm.sales_channel_id} onValueChange={v=>{const c=channelById.get(v);setTargetForm(f=>({...f,sales_channel_id:v,unit:c?.default_unit??f.unit,target_price_per_unit:c?.default_price_per_unit!=null?String(c.default_price_per_unit):f.target_price_per_unit}))}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{es?"Sin canal":"Unassigned"}</SelectItem>{channels.filter(c=>c.status==="active").map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></Field><Field label={es?"Cantidad planificada":"Planned quantity"}><Input type="number" min="0" step="0.1" value={targetForm.planned_quantity} onChange={e=>setTargetForm(f=>({...f,planned_quantity:e.target.value}))}/></Field><Field label={es?"Unidad":"Unit"}><Input value={targetForm.unit} onChange={e=>setTargetForm(f=>({...f,unit:e.target.value}))}/></Field><Field label={es?"Precio objetivo":"Target price"}><Input type="number" min="0" step="0.01" value={targetForm.target_price_per_unit} onChange={e=>setTargetForm(f=>({...f,target_price_per_unit:e.target.value}))}/></Field><Field label={es?"Notas":"Notes"}><Input value={targetForm.notes} onChange={e=>setTargetForm(f=>({...f,notes:e.target.value}))}/></Field><Button className="md:col-span-2" disabled={saving}><Plus className="mr-2 h-4 w-4"/>{es?"Agregar objetivo":"Add target"}</Button></form></CardContent></Card></div>
 <Card><CardHeader><CardTitle>{es?"Plan vs valor real":"Plan vs realized value"}</CardTitle><CardDescription>{es?"La cantidad real solo se compara cuando la unidad coincide; el valor usa los importes canónicos de cosecha.":"Actual quantity is compared only when units match; revenue uses canonical harvest values."}</CardDescription></CardHeader><CardContent>{rows.length===0?<p className="text-sm text-muted-foreground">{es?"Aún no hay objetivos comerciales.":"No commercial targets yet."}</p>:<div className="space-y-3">{rows.map(r=><div key={r.id} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><p className="font-semibold">{successionLabel(r.crop_succession_id)}</p><p className="text-xs text-muted-foreground">{r.sales_channel_id?channelById.get(r.sales_channel_id)?.name:(es?"Sin canal":"Unassigned")}</p></div><Datum label={es?"Plan cantidad":"Planned qty"} value={`${r.planned_quantity} ${r.unit}`}/><Datum label={es?"Real cantidad":"Actual qty"} value={`${r.actualQty} ${r.unit}`}/><div><Datum label={es?"Ingreso":"Revenue"} value={`${money(r.actualRevenue)} / ${money(Number(r.planned_revenue))}`}/><Badge variant={r.actualRevenue>=Number(r.planned_revenue)?"default":"outline"}>{r.actualRevenue>=Number(r.planned_revenue)?(es?"Meta alcanzada":"On target"):(es?"Bajo meta":"Below target")}</Badge></div></div>)}</div>}</CardContent></Card>
 </div></AppLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Metric({label,value}:{label:string;value:string}){return <Card><CardContent className="p-4"><p className="text-xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>}
function Datum({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="font-medium">{value}</p></div>}
