"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowDownAZ, ArrowRight, ArrowUpAZ, CalendarPlus, Filter, Plus, Search, Sprout, Star, X } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { cropColor, cropChipStyle } from "@/lib/orchard/crop-identity"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Plan={id:string;name:string;season:string|null;status:string}
type CropProfile={id:string;crop_name:string;scientific_name:string|null;crop_family:string|null;default_cycle_type:string|null;days_to_maturity:number|null;observed_count:number;provenance_type:string}
type Photo={crop_name:string;photo_url:string|null;storage_public_url:string|null;verification_status:string}
type Cycle={id:string;game_plan_id:string;crop_name:string}
type Succession={id:string;crop_cycle_id:string}
type CycleLabels={direct:string;transplant:string;perennial:string;cover:string}
type SortDirection="asc"|"desc"

const copy={
 en:{title:"Crops",description:"Canonical Corcovado crop catalog. Search, filter, sort, favorite crops and create a crop without leaving the operating season.",search:"Search crops...",filters:"Filters",sort:"Sort",sortName:"Name",asc:"ASC",desc:"DESC",create:"Create crop",all:"All crops",inPlan:"In this plan",favorites:"Favorites",favoritesOnly:"Favorites only",showCatalog:"All crops",backToPlan:"In this plan",field:"In field",library:"Advanced library",plantings:"plantings",planting:"planting",add:"Create planting",openPlan:"Open plan",empty:"No crops match this view.",season:"Season",direct:"Direct sow",transplant:"Transplant",perennial:"Perennial",cover:"Cover crop",days:"days",canonical:"Corcovado canonical",noVerifiedPhoto:"No verified photo",favorite:"Add to favorites",unfavorite:"Remove from favorites",createTitle:"Create crop",cropName:"Crop name",family:"Family",scientific:"Scientific name",propagation:"Propagation",save:"Create",cancel:"Cancel",required:"Crop name is required.",duplicate:"That crop already exists in the canonical catalog.",createError:"Could not create crop.",filterPlan:"Only crops in this plan",filterFavorites:"Only favorite crops"},
 es:{title:"Cultivos",description:"Catálogo canónico Corcovado. Busca, filtra, ordena, marca favoritos y crea un cultivo sin salir de la temporada operativa.",search:"Buscar cultivos...",filters:"Filtros",sort:"Orden",sortName:"Nombre",asc:"ASC",desc:"DESC",create:"Crear cultivo",all:"Todos los cultivos",inPlan:"En este plan",favorites:"Favoritos",favoritesOnly:"Sólo favoritos",showCatalog:"Todos los cultivos",backToPlan:"En este plan",field:"En terreno",library:"Biblioteca avanzada",plantings:"plantaciones",planting:"plantación",add:"Crear plantación",openPlan:"Abrir plan",empty:"No hay cultivos para esta vista.",season:"Temporada",direct:"Siembra directa",transplant:"Trasplante",perennial:"Perenne",cover:"Cobertura",days:"días",canonical:"Canónico Corcovado",noVerifiedPhoto:"Sin foto verificada",favorite:"Agregar a favoritos",unfavorite:"Quitar de favoritos",createTitle:"Crear cultivo",cropName:"Nombre del cultivo",family:"Familia",scientific:"Nombre científico",propagation:"Propagación",save:"Crear",cancel:"Cancelar",required:"El nombre del cultivo es obligatorio.",duplicate:"Ese cultivo ya existe en el catálogo canónico.",createError:"No fue posible crear el cultivo.",filterPlan:"Sólo cultivos de este plan",filterFavorites:"Sólo cultivos favoritos"},
 de:{title:"Kulturen",description:"Kanonischer Corcovado-Kulturkatalog. Suchen, filtern, sortieren, Favoriten markieren und Kulturen innerhalb der Saison anlegen.",search:"Kulturen suchen...",filters:"Filter",sort:"Sortierung",sortName:"Name",asc:"ASC",desc:"DESC",create:"Kultur erstellen",all:"Alle Kulturen",inPlan:"In diesem Plan",favorites:"Favoriten",favoritesOnly:"Nur Favoriten",showCatalog:"Alle Kulturen",backToPlan:"In diesem Plan",field:"Im Feld",library:"Erweiterte Bibliothek",plantings:"Pflanzungen",planting:"Pflanzung",add:"Pflanzung erstellen",openPlan:"Plan öffnen",empty:"Keine Kulturen entsprechen dieser Ansicht.",season:"Saison",direct:"Direktsaat",transplant:"Verpflanzung",perennial:"Mehrjährig",cover:"Zwischenfrucht",days:"Tage",canonical:"Corcovado kanonisch",noVerifiedPhoto:"Kein verifiziertes Foto",favorite:"Zu Favoriten",unfavorite:"Aus Favoriten entfernen",createTitle:"Kultur erstellen",cropName:"Kulturname",family:"Familie",scientific:"Wissenschaftlicher Name",propagation:"Vermehrung",save:"Erstellen",cancel:"Abbrechen",required:"Kulturname ist erforderlich.",duplicate:"Diese Kultur existiert bereits im kanonischen Katalog.",createError:"Kultur konnte nicht erstellt werden.",filterPlan:"Nur Kulturen in diesem Plan",filterFavorites:"Nur Favoriten"},
} as const

function normalized(value:string){return value.trim().toLowerCase()}
function cycleLabel(value:string|null,text:CycleLabels){if(value==="direct_sow")return text.direct;if(value==="transplant")return text.transplant;if(value==="perennial")return text.perennial;if(value==="cover_crop")return text.cover;return "—"}

export default function OrchardCropCatalogPage(){
 const supabase=useMemo(()=>createBrowserClient(),[])
 const {language}=useLanguage();const lang:Locale=language;const text=copy[lang]
 const [plans,setPlans]=useState<Plan[]>([]),[profiles,setProfiles]=useState<CropProfile[]>([]),[photos,setPhotos]=useState<Photo[]>([]),[cycles,setCycles]=useState<Cycle[]>([]),[successions,setSuccessions]=useState<Succession[]>([])
 const [userId,setUserId]=useState<string|null>(null),[favoriteIds,setFavoriteIds]=useState<Set<string>>(new Set())
 const [query,setQuery]=useState(""),[planOnly,setPlanOnly]=useState(false),[favoritesOnly,setFavoritesOnly]=useState(false),[sortDirection,setSortDirection]=useState<SortDirection>("asc"),[filtersOpen,setFiltersOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 const [createOpen,setCreateOpen]=useState(false),[saving,setSaving]=useState(false),[formError,setFormError]=useState<string|null>(null)
 const [cropName,setCropName]=useState(""),[family,setFamily]=useState(""),[scientific,setScientific]=useState(""),[cycleType,setCycleType]=useState("transplant")

 useEffect(()=>{let live=true;setLoading(true);setError(null);void Promise.all([
  supabase.auth.getUser(),
  supabase.from("orchard_game_plans").select("id,name,season,status").order("start_date",{ascending:false}),
  supabase.from("orchard_crop_library").select("id,crop_name,scientific_name,crop_family,default_cycle_type,days_to_maturity,observed_count,provenance_type").eq("is_active",true).eq("classification_scheme","black_swan_canonical").eq("classification_code","fundo_corcovado").order("crop_name"),
  supabase.from("orchard_crop_photo_registry").select("crop_name,photo_url,storage_public_url,verification_status").in("verification_status",["verified","approved"]),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id").neq("status","cancelled"),
 ]).then(async([auth,p,l,ph,c,s])=>{if(!live)return;const first=p.error??l.error??ph.error??c.error??s.error;if(first){setError(first.message);setLoading(false);return}const uid=auth.data.user?.id??null;setUserId(uid);setPlans((p.data??[]) as Plan[]);setProfiles((l.data??[]) as CropProfile[]);setPhotos((ph.data??[]) as Photo[]);setCycles((c.data??[]) as Cycle[]);setSuccessions((s.data??[]) as Succession[]);if(uid){const fav=await supabase.from("orchard_crop_favorites").select("crop_library_id").eq("user_id",uid);if(live&&!fav.error)setFavoriteIds(new Set((fav.data??[]).map(row=>row.crop_library_id as string)))}setLoading(false)});return()=>{live=false}},[supabase])

 const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null
 const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const planCycles=cycles.filter(c=>c.game_plan_id===plan?.id)
 const successionCountByCycle=new Map<string,number>();for(const s of successions)successionCountByCycle.set(s.crop_cycle_id,(successionCountByCycle.get(s.crop_cycle_id)??0)+1)
 const countByCrop=new Map<string,number>();for(const cycle of planCycles){const key=normalized(cycle.crop_name);countByCrop.set(key,(countByCrop.get(key)??0)+(successionCountByCycle.get(cycle.id)??0))}
 const photoByCrop=new Map<string,string>();for(const photo of photos){const url=photo.storage_public_url??photo.photo_url;if(url&&!photoByCrop.has(normalized(photo.crop_name)))photoByCrop.set(normalized(photo.crop_name),url)}
 const filtered=profiles.filter(profile=>{const key=normalized(profile.crop_name);const matches=!query.trim()||`${profile.crop_name} ${profile.scientific_name??""} ${profile.crop_family??""}`.toLowerCase().includes(query.trim().toLowerCase());if(!matches)return false;if(planOnly&&(countByCrop.get(key)??0)===0)return false;if(favoritesOnly&&!favoriteIds.has(profile.id))return false;return true}).sort((a,b)=>sortDirection==="asc"?a.crop_name.localeCompare(b.crop_name):b.crop_name.localeCompare(a.crop_name))
 const planHref=`/${language}/orchard/game-plan${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`
 const calendarHref=`/${language}/orchard/game-plan/season${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`
 const fieldHref=`/${language}/orchard/crops${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`
 const libraryHref=`/${language}/orchard/library${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`

 async function toggleFavorite(profileId:string){if(!userId)return;const active=favoriteIds.has(profileId);const result=active?await supabase.from("orchard_crop_favorites").delete().eq("user_id",userId).eq("crop_library_id",profileId):await supabase.from("orchard_crop_favorites").insert({user_id:userId,crop_library_id:profileId});if(result.error){setError(result.error.message);return}setFavoriteIds(current=>{const next=new Set(current);active?next.delete(profileId):next.add(profileId);return next})}
 async function createCrop(){setFormError(null);const name=cropName.trim();if(!name){setFormError(text.required);return}if(profiles.some(profile=>normalized(profile.crop_name)===normalized(name))){setFormError(text.duplicate);return}setSaving(true);const result=await supabase.from("orchard_crop_library").insert({crop_name:name,scientific_name:scientific.trim()||null,crop_family:family.trim()||null,default_cycle_type:cycleType,source_name:"Black Swan operator",source_verified_at:new Date().toISOString(),provenance_type:"manual",classification_scheme:"black_swan_canonical",classification_code:"fundo_corcovado",is_active:true}).select("id,crop_name,scientific_name,crop_family,default_cycle_type,days_to_maturity,observed_count,provenance_type").single();setSaving(false);if(result.error){setFormError(result.error.code==="23505"?text.duplicate:`${text.createError} ${result.error.message}`);return}setProfiles(current=>[...(current as CropProfile[]),result.data as CropProfile]);setCropName("");setFamily("");setScientific("");setCycleType("transplant");setCreateOpen(false)}

 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1580px] px-4 pb-16 pt-6 sm:px-6 lg:px-8">
  <header className="mb-4 flex flex-col gap-4 border-b border-[var(--orchard-line)] pb-4 lg:flex-row lg:items-end lg:justify-between">
   <div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--orchard-green)]">{text.canonical}</p><h1 className="mt-1 text-3xl font-medium">{text.title}</h1><p className="mt-2 max-w-3xl text-sm leading-5 text-muted-foreground">{text.description}</p></div>
   <div className="flex flex-wrap items-center gap-2"><Link href={fieldHref} className="inline-flex min-h-10 items-center border border-[var(--orchard-line)] px-3 text-sm hover:bg-muted">{text.field}</Link><Link href={libraryHref} className="inline-flex min-h-10 items-center border border-[var(--orchard-line)] px-3 text-sm hover:bg-muted">{text.library}</Link></div>
  </header>
  <section className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
   <label className="flex min-h-10 w-full max-w-md items-center gap-2 border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] px-3"><Search className="h-4 w-4 text-muted-foreground"/><span className="sr-only">{text.search}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={text.search} className="h-8 w-full border-0 bg-transparent text-sm outline-none"/></label>
   <div className="flex flex-wrap items-center gap-2">
    <button type="button" onClick={()=>setFiltersOpen(value=>!value)} aria-expanded={filtersOpen} className="inline-flex min-h-10 items-center gap-2 border border-[var(--orchard-line)] px-3 text-sm hover:bg-muted"><Filter className="h-4 w-4"/>{text.filters}</button>
    <button type="button" onClick={()=>setSortDirection(value=>value==="asc"?"desc":"asc")} className="inline-flex min-h-10 items-center gap-2 border border-[var(--orchard-line)] px-3 text-sm hover:bg-muted">{sortDirection==="asc"?<ArrowDownAZ className="h-4 w-4"/>:<ArrowUpAZ className="h-4 w-4"/>}{text.sort}: {text.sortName} ({sortDirection==="asc"?text.asc:text.desc})</button>
    <button type="button" onClick={()=>setCreateOpen(true)} className="inline-flex min-h-10 items-center gap-2 bg-[var(--orchard-green)] px-3 text-sm font-medium text-black"><Plus className="h-4 w-4"/>{text.create}</button>
   </div>
  </section>
  {filtersOpen?<section className="mb-4 flex flex-wrap items-center gap-5 border-y border-[var(--orchard-line)] py-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={planOnly} onChange={event=>setPlanOnly(event.target.checked)}/>{text.filterPlan}</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={favoritesOnly} onChange={event=>setFavoritesOnly(event.target.checked)}/>{text.filterFavorites}</label><div className="ml-auto text-xs text-muted-foreground">{text.season}: <strong className="font-medium text-foreground">{plan?.season??"—"}</strong></div></section>:null}
  <div className="mb-4 flex items-center gap-3 text-xs text-muted-foreground"><span>{planOnly?text.inPlan:text.all} · <strong className="font-medium text-foreground">{filtered.length}</strong></span>{favoriteIds.size?<span>{text.favorites} · <strong className="font-medium text-foreground">{favoriteIds.size}</strong></span>:null}</div>

  {loading?<div className="py-12 text-sm text-muted-foreground">…</div>:error?<div className="border-y border-red-400/30 py-4 text-sm text-red-300">{error}</div>:filtered.length===0?<div className="border-y border-[var(--orchard-line)] py-10 text-sm text-muted-foreground">{text.empty}</div>:<section className="grid grid-cols-2 gap-px bg-[var(--orchard-line)] md:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">
   {filtered.map(profile=>{const key=normalized(profile.crop_name);const count=countByCrop.get(key)??0;const image=photoByCrop.get(key);const identity=cropChipStyle(profile.crop_name,profile.crop_family);const color=cropColor(profile.crop_name,profile.crop_family);const favorite=favoriteIds.has(profile.id);return <article key={profile.id} className="overflow-hidden bg-[var(--bs-surface-primary)]" style={{boxShadow:`inset 3px 0 0 ${color}`}}>
    <div className="relative h-28 overflow-hidden" style={{backgroundColor:color}}>{image?<img src={image} alt={profile.crop_name} className="h-full w-full object-cover" loading="lazy"/>:<div className="flex h-full flex-col items-center justify-center gap-2"><Sprout className="h-10 w-10 text-white/70"/><span className="text-[10px] uppercase tracking-[.12em] text-white/65">{text.noVerifiedPhoto}</span></div>}<button type="button" aria-label={favorite?text.unfavorite:text.favorite} onClick={()=>void toggleFavorite(profile.id)} disabled={!userId} className="absolute left-2 top-2 flex h-8 w-8 items-center justify-center bg-black/60 text-white disabled:opacity-50"><Star className={`h-4 w-4 ${favorite?"fill-current":""}`}/></button><span className="absolute right-2 top-2 bg-black/55 px-2 py-1 text-[10px] text-white">{cycleLabel(profile.default_cycle_type,text)}</span></div>
    <div className="p-3"><h2 className="line-clamp-2 min-h-[2.6em] text-base font-medium leading-[1.3]" title={profile.crop_name}>{profile.crop_name}</h2><p className="mt-1 min-h-5 line-clamp-1 text-xs italic text-muted-foreground">{profile.crop_family??profile.scientific_name??(profile.days_to_maturity?`${profile.days_to_maturity} ${text.days}`:"Corcovado")}</p>
     <div className="mt-3 flex items-center justify-between gap-2 border-t border-[var(--orchard-line-soft)] pt-3">{count>0?<Link href={calendarHref} className="inline-flex min-h-9 items-center gap-1.5 text-xs font-medium" style={{color:identity.color}}><ArrowRight className="h-3.5 w-3.5"/>{count} {count===1?text.planting:text.plantings}</Link>:<span className="text-xs text-muted-foreground">0 {text.plantings}</span>}<Link href={planHref} className="inline-flex min-h-9 items-center gap-1.5 px-2.5 text-xs font-medium text-white" style={{backgroundColor:color}}><CalendarPlus className="h-3.5 w-3.5"/>{count?text.openPlan:text.add}</Link></div>
    </div>
   </article>})}
  </section>}

  {createOpen?<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-label={text.createTitle}><section className="w-full max-w-lg border border-[var(--orchard-line)] bg-[var(--bs-bg-primary)]"><header className="flex items-center justify-between border-b border-[var(--orchard-line)] px-5 py-4"><h2 className="text-xl font-medium">{text.createTitle}</h2><button type="button" onClick={()=>setCreateOpen(false)} aria-label={text.cancel}><X className="h-5 w-5"/></button></header><div className="space-y-4 p-5"><Field label={text.cropName} value={cropName} onChange={setCropName} required/><Field label={text.family} value={family} onChange={setFamily}/><Field label={text.scientific} value={scientific} onChange={setScientific}/><label className="block"><span className="mb-1.5 block text-xs text-muted-foreground">{text.propagation}</span><select value={cycleType} onChange={event=>setCycleType(event.target.value)} className="h-10 w-full border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] px-3 text-sm"><option value="transplant">{text.transplant}</option><option value="direct_sow">{text.direct}</option><option value="perennial">{text.perennial}</option><option value="cover_crop">{text.cover}</option></select></label>{formError?<p className="text-sm text-red-300">{formError}</p>:null}</div><footer className="flex justify-end gap-2 border-t border-[var(--orchard-line)] p-4"><button type="button" onClick={()=>setCreateOpen(false)} className="min-h-10 border border-[var(--orchard-line)] px-4 text-sm">{text.cancel}</button><button type="button" onClick={()=>void createCrop()} disabled={saving} className="min-h-10 bg-[var(--orchard-green)] px-4 text-sm font-medium text-black disabled:opacity-50">{saving?"…":text.save}</button></footer></section></div>:null}
 </main></AppLayout>
}

function Field({label,value,onChange,required=false}:{label:string;value:string;onChange:(value:string)=>void;required?:boolean}){return <label className="block"><span className="mb-1.5 block text-xs text-muted-foreground">{label}{required?" *":""}</span><input value={value} required={required} onChange={event=>onChange(event.target.value)} className="h-10 w-full border border-[var(--orchard-line)] bg-[var(--bs-surface-primary)] px-3 text-sm outline-none focus:border-[var(--orchard-green)]"/></label>}
