"use client"

import type { FormEvent, ReactNode } from "react"
import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { CalendarRange, Plus, RefreshCw, Sprout, Target, Users, Wheat } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { PageHeader } from "@/components/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale = "en" | "es" | "de"
type Scenario = { id:string; name:string; start_date:string; end_date:string; status:"draft"|"active"|"archived"; resident_people:number; staff_people:number; manual_people:number; include_bookings:boolean; self_sufficiency_target_pct:number; waste_pct:number; notes:string|null }
type CropTarget = { id:string; scenario_id:string; crop_name:string; consumption_kg_per_person_week:number; target_share_pct:number; notes:string|null }
type Reservation = { check_in:string; check_out:string; num_guests:number|null; status:string|null }
type CropCycle = { crop_name:string; target_harvest_date:string|null; target_quantity:number|null; target_unit:string|null; status:string|null }
type Crop = { id:string; crop_name:string; expected_harvest_date:string|null; estimated_yield:number|null; actual_yield:number|null; yield_unit:string|null; status:string|null }
type Harvest = { crop_id:string; harvest_date:string; quantity_harvested:number; harvest_unit:string }

type DemandRow = { crop:string; demand:number; planned:number; forecast:number; harvested:number; supply:number; gap:number; coverage:number }

const copy = {
  en:{title:"Food Demand & Self-Sufficiency",description:"Turn people-to-feed into crop demand, production targets and a visible path toward zero imported food.",refresh:"Refresh",scenario:"Scenario",newScenario:"New demand scenario",scenarioName:"Scenario name",start:"Start",end:"End",residents:"Residents",staff:"Staff",manual:"Manual / events",bookings:"Include bookings",target:"Self-sufficiency target %",waste:"Waste buffer %",notes:"Notes",create:"Create scenario",people:"People to feed",foodDemand:"Food demand",plannedSupply:"Planned supply",selfSufficiency:"Self-sufficiency",bookingPeople:"avg. from bookings",noBookings:"No future booking demand in this window",cropMix:"Crop demand mix",cropMixHelp:"Set weekly consumption per person. Demand is calculated for the scenario horizon and adjusted for waste and target share.",crop:"Crop",kgPersonWeek:"kg / person / week",share:"Target share %",addTarget:"Add crop target",demand:"Demand kg",planned:"Planned kg",forecast:"Forecast kg",harvested:"Harvested kg",importGap:"Import gap",coverage:"Coverage",action:"Action",addPlan:"Add to Game Plan",noTargets:"Add crop targets to start calculating demand.",assumption:"Demand uses average people over the scenario window. Booking occupancy is derived from overlapping reservation guest-days; residents, staff and manual/event headcount are added as constant demand.",draft:"Draft",active:"Active",archived:"Archived",weeks:"weeks",saveError:"Could not save demand planning data",loadError:"Could not load demand planning data",targetSaved:"Crop demand target saved."},
  es:{title:"Demanda de Alimentos y Autosuficiencia",description:"Convierte personas a alimentar en demanda por cultivo, objetivos de producción y una ruta visible hacia cero alimentos importados.",refresh:"Actualizar",scenario:"Escenario",newScenario:"Nuevo escenario de demanda",scenarioName:"Nombre del escenario",start:"Inicio",end:"Término",residents:"Residentes",staff:"Equipo",manual:"Manual / eventos",bookings:"Incluir reservas",target:"Meta de autosuficiencia %",waste:"Buffer de merma %",notes:"Notas",create:"Crear escenario",people:"Personas a alimentar",foodDemand:"Demanda alimentaria",plannedSupply:"Producción planificada",selfSufficiency:"Autosuficiencia",bookingPeople:"prom. desde reservas",noBookings:"No hay demanda futura de reservas en esta ventana",cropMix:"Mix de demanda por cultivo",cropMixHelp:"Define consumo semanal por persona. La demanda se calcula para el horizonte del escenario y se ajusta por merma y participación objetivo.",crop:"Cultivo",kgPersonWeek:"kg / persona / semana",share:"Participación objetivo %",addTarget:"Agregar objetivo",demand:"Demanda kg",planned:"Plan kg",forecast:"Forecast kg",harvested:"Cosechado kg",importGap:"Brecha de importación",coverage:"Cobertura",action:"Acción",addPlan:"Agregar al Game Plan",noTargets:"Agrega objetivos por cultivo para comenzar a calcular demanda.",assumption:"La demanda usa personas promedio durante la ventana. La ocupación de reservas se deriva de guest-days superpuestos; residentes, equipo y carga manual/eventos se agregan como demanda constante.",draft:"Borrador",active:"Activo",archived:"Archivado",weeks:"semanas",saveError:"No fue posible guardar la planificación de demanda",loadError:"No fue posible cargar la planificación de demanda",targetSaved:"Objetivo de demanda guardado."},
  de:{title:"Lebensmittelbedarf & Selbstversorgung",description:"Übersetze zu versorgende Personen in Kulturbedarf, Produktionsziele und einen sichtbaren Weg zu null Lebensmittelimporten.",refresh:"Aktualisieren",scenario:"Szenario",newScenario:"Neues Bedarfsszenario",scenarioName:"Szenarioname",start:"Start",end:"Ende",residents:"Bewohner",staff:"Team",manual:"Manuell / Events",bookings:"Buchungen einbeziehen",target:"Selbstversorgungsziel %",waste:"Verlustpuffer %",notes:"Notizen",create:"Szenario erstellen",people:"Zu versorgende Personen",foodDemand:"Lebensmittelbedarf",plannedSupply:"Geplante Produktion",selfSufficiency:"Selbstversorgung",bookingPeople:"Ø aus Buchungen",noBookings:"Keine zukünftige Buchungsnachfrage in diesem Zeitraum",cropMix:"Bedarfsmix nach Kultur",cropMixHelp:"Lege den Wochenverbrauch pro Person fest. Der Bedarf wird für den Szenariozeitraum berechnet und um Verluste und Zielanteil angepasst.",crop:"Kultur",kgPersonWeek:"kg / Person / Woche",share:"Zielanteil %",addTarget:"Kulturziel hinzufügen",demand:"Bedarf kg",planned:"Plan kg",forecast:"Prognose kg",harvested:"Geerntet kg",importGap:"Importlücke",coverage:"Abdeckung",action:"Aktion",addPlan:"Zum Game Plan",noTargets:"Füge Kulturziele hinzu, um die Bedarfsrechnung zu starten.",assumption:"Der Bedarf nutzt die durchschnittliche Personenzahl im Zeitraum. Buchungsbelegung wird aus überlappenden Gasttagen berechnet; Bewohner, Team und manuelle/Event-Personen werden als konstante Nachfrage addiert.",draft:"Entwurf",active:"Aktiv",archived:"Archiviert",weeks:"Wochen",saveError:"Bedarfsplanung konnte nicht gespeichert werden",loadError:"Bedarfsplanung konnte nicht geladen werden",targetSaved:"Kulturbedarfsziel gespeichert."},
} as const

const localeMap:Record<Locale,string>={en:"en-US",es:"es-CL",de:"de-DE"}
const today=()=>new Date().toISOString().slice(0,10)
const plusMonths=(months:number)=>{const d=new Date();d.setMonth(d.getMonth()+months);return d.toISOString().slice(0,10)}
const daysBetween=(a:string,b:string)=>Math.max(1,Math.ceil((new Date(`${b}T12:00:00`).getTime()-new Date(`${a}T12:00:00`).getTime())/86400000))
const overlaps=(aStart:string,aEnd:string,bStart:string,bEnd:string)=>aStart<bEnd&&aEnd>bStart
const overlapDays=(aStart:string,aEnd:string,bStart:string,bEnd:string)=>{const s=Math.max(new Date(`${aStart}T12:00:00`).getTime(),new Date(`${bStart}T12:00:00`).getTime());const e=Math.min(new Date(`${aEnd}T12:00:00`).getTime(),new Date(`${bEnd}T12:00:00`).getTime());return Math.max(0,Math.ceil((e-s)/86400000))}
const kg=(value:number)=>Number.isFinite(value)?value:0
const isKg=(unit:string|null|undefined)=>!unit||unit.toLowerCase().startsWith("kg")

export default function OrchardDemandPage(){
  const supabase=useMemo(()=>createBrowserClient(),[])
  const {language}=useLanguage();const lang:Locale=language;const text=copy[lang];const numberLocale=localeMap[lang]
  const [scenarios,setScenarios]=useState<Scenario[]>([]);const [selectedId,setSelectedId]=useState("");const [targets,setTargets]=useState<CropTarget[]>([])
  const [reservations,setReservations]=useState<Reservation[]>([]);const [cycles,setCycles]=useState<CropCycle[]>([]);const [crops,setCrops]=useState<Crop[]>([]);const [harvests,setHarvests]=useState<Harvest[]>([])
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null)
  const [scenarioForm,setScenarioForm]=useState({name:"Food independence",start_date:today(),end_date:plusMonths(6),resident_people:"0",staff_people:"0",manual_people:"0",self_sufficiency_target_pct:"100",waste_pct:"10",notes:""})
  const [targetForm,setTargetForm]=useState({crop_name:"",consumption:"0.25",share:"100"})
  const selected=useMemo(()=>scenarios.find(s=>s.id===selectedId)??scenarios[0]??null,[scenarios,selectedId])

  const load=useCallback(async()=>{
    setLoading(true);setError(null)
    const [s,t,r,c,live,h]=await Promise.all([
      supabase.from("orchard_demand_scenarios").select("*").order("created_at",{ascending:false}),
      supabase.from("orchard_demand_crop_targets").select("*").order("crop_name"),
      supabase.from("reservations").select("check_in,check_out,num_guests,status"),
      supabase.from("orchard_crop_cycles").select("crop_name,target_harvest_date,target_quantity,target_unit,status"),
      supabase.from("orchard_crops").select("id,crop_name,expected_harvest_date,estimated_yield,actual_yield,yield_unit,status"),
      supabase.from("orchard_harvest_records").select("crop_id,harvest_date,quantity_harvested,harvest_unit"),
    ])
    const firstError=[s.error,t.error,r.error,c.error,live.error,h.error].find(Boolean)
    if(firstError)setError(firstError.message||text.loadError)
    setScenarios((s.data??[]) as Scenario[]);setTargets((t.data??[]) as CropTarget[]);setReservations((r.data??[]) as Reservation[]);setCycles((c.data??[]) as CropCycle[]);setCrops((live.data??[]) as Crop[]);setHarvests((h.data??[]) as Harvest[])
    const first=(s.data?.[0] as Scenario|undefined);setSelectedId(id=>id||(first?.id??""));setLoading(false)
  },[supabase,text.loadError])
  useEffect(()=>{void load()},[load])

  async function createScenario(e:FormEvent){e.preventDefault();setSaving(true);setError(null);setNotice(null)
    const payload={name:scenarioForm.name.trim(),start_date:scenarioForm.start_date,end_date:scenarioForm.end_date,resident_people:Number(scenarioForm.resident_people)||0,staff_people:Number(scenarioForm.staff_people)||0,manual_people:Number(scenarioForm.manual_people)||0,self_sufficiency_target_pct:Number(scenarioForm.self_sufficiency_target_pct)||100,waste_pct:Number(scenarioForm.waste_pct)||0,include_bookings:true,notes:scenarioForm.notes.trim()||null}
    const r=await supabase.from("orchard_demand_scenarios").insert(payload).select("*").single();if(r.error)setError(r.error.message||text.saveError);else{setSelectedId(r.data.id);await load()}setSaving(false)
  }
  async function addTarget(e:FormEvent){e.preventDefault();if(!selected||!targetForm.crop_name.trim())return;setSaving(true);setError(null);setNotice(null)
    const r=await supabase.from("orchard_demand_crop_targets").upsert({scenario_id:selected.id,crop_name:targetForm.crop_name.trim(),consumption_kg_per_person_week:Number(targetForm.consumption)||0,target_share_pct:Number(targetForm.share)||100},{onConflict:"scenario_id,crop_name"});if(r.error)setError(r.error.message||text.saveError);else{setTargetForm({crop_name:"",consumption:"0.25",share:"100"});setNotice(text.targetSaved);await load()}setSaving(false)
  }

  const metrics=useMemo(()=>{
    if(!selected)return {days:0,weeks:0,bookingAvg:0,people:0,totalDemand:0,planned:0,self:0,rows:[] as DemandRow[]}
    const days=daysBetween(selected.start_date,selected.end_date);const weeks=days/7
    const bookingGuestDays=selected.include_bookings?reservations.reduce((sum,r)=>{if(!r.check_in||!r.check_out||!overlaps(r.check_in,r.check_out,selected.start_date,selected.end_date))return sum;const status=(r.status??"").toLowerCase();if(["cancelled","canceled","no_show"].includes(status))return sum;return sum+overlapDays(r.check_in,r.check_out,selected.start_date,selected.end_date)*Math.max(0,r.num_guests??0)},0):0
    const bookingAvg=bookingGuestDays/days;const people=selected.resident_people+selected.staff_people+selected.manual_people+bookingAvg
    const scenarioTargets=targets.filter(t=>t.scenario_id===selected.id)
    const cropById=new Map(crops.map(c=>[c.id,c.crop_name]))
    const rows=scenarioTargets.map<DemandRow>(t=>{
      const demand=people*weeks*t.consumption_kg_per_person_week*(t.target_share_pct/100)*(1+selected.waste_pct/100)
      const planned=cycles.filter(c=>c.crop_name.toLowerCase()===t.crop_name.toLowerCase()&&c.target_harvest_date&&c.target_harvest_date>=selected.start_date&&c.target_harvest_date<=selected.end_date&&isKg(c.target_unit)&&c.status!=="cancelled").reduce((sum,c)=>sum+kg(Number(c.target_quantity??0)),0)
      const forecast=crops.filter(c=>c.crop_name.toLowerCase()===t.crop_name.toLowerCase()&&c.expected_harvest_date&&c.expected_harvest_date>=selected.start_date&&c.expected_harvest_date<=selected.end_date&&isKg(c.yield_unit)&&c.status!=="cancelled").reduce((sum,c)=>sum+kg(Number(c.estimated_yield??0)),0)
      const harvested=harvests.filter(h=>(cropById.get(h.crop_id)??"").toLowerCase()===t.crop_name.toLowerCase()&&h.harvest_date>=selected.start_date&&h.harvest_date<=selected.end_date&&isKg(h.harvest_unit)).reduce((sum,h)=>sum+kg(Number(h.quantity_harvested??0)),0)
      const supply=Math.max(planned,forecast,harvested);const gap=Math.max(0,demand-supply);const coverage=demand>0?Math.min(100,(supply/demand)*100):100
      return {crop:t.crop_name,demand,planned,forecast,harvested,supply,gap,coverage}
    }).sort((a,b)=>b.gap-a.gap)
    const totalDemand=rows.reduce((s,r)=>s+r.demand,0);const planned=rows.reduce((s,r)=>s+r.supply,0);const self=totalDemand>0?Math.min(100,(planned/totalDemand)*100):0
    return {days,weeks,bookingAvg,people,totalDemand,planned,self,rows}
  },[selected,reservations,targets,cycles,crops,harvests])

  return <AppLayout><PageHeader title={text.title} description={text.description} actions={<Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>{text.refresh}</Button>}/><OrchardNavigation/><div className="space-y-6 p-3 pb-24 sm:p-8">
    {error?<Card className="border-destructive/40"><CardContent className="p-4 text-sm text-destructive">{error}</CardContent></Card>:null}{notice?<Card><CardContent className="p-4 text-sm">{notice}</CardContent></Card>:null}
    <div className="grid gap-3 lg:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Target className="h-5 w-5"/>{text.scenario}</CardTitle></CardHeader><CardContent className="space-y-4"><Select value={selected?.id??""} onValueChange={setSelectedId}><SelectTrigger><SelectValue placeholder={text.scenario}/></SelectTrigger><SelectContent>{scenarios.map(s=><SelectItem key={s.id} value={s.id}>{s.name} · {s.start_date} → {s.end_date}</SelectItem>)}</SelectContent></Select>{selected?<div className="flex flex-wrap gap-2"><Badge variant="outline">{text[selected.status]}</Badge><Badge variant="outline">{metrics.weeks.toFixed(1)} {text.weeks}</Badge><Badge variant="outline">{selected.self_sufficiency_target_pct}% {text.target.toLowerCase()}</Badge></div>:null}</CardContent></Card>
      <Card><CardHeader><CardTitle>{text.newScenario}</CardTitle></CardHeader><CardContent><form onSubmit={createScenario} className="grid gap-3 sm:grid-cols-2"><Field label={text.scenarioName}><Input value={scenarioForm.name} onChange={e=>setScenarioForm(f=>({...f,name:e.target.value}))} required/></Field><Field label={text.start}><Input type="date" value={scenarioForm.start_date} onChange={e=>setScenarioForm(f=>({...f,start_date:e.target.value}))} required/></Field><Field label={text.end}><Input type="date" value={scenarioForm.end_date} onChange={e=>setScenarioForm(f=>({...f,end_date:e.target.value}))} required/></Field><Field label={text.residents}><Input type="number" min="0" value={scenarioForm.resident_people} onChange={e=>setScenarioForm(f=>({...f,resident_people:e.target.value}))}/></Field><Field label={text.staff}><Input type="number" min="0" value={scenarioForm.staff_people} onChange={e=>setScenarioForm(f=>({...f,staff_people:e.target.value}))}/></Field><Field label={text.manual}><Input type="number" min="0" value={scenarioForm.manual_people} onChange={e=>setScenarioForm(f=>({...f,manual_people:e.target.value}))}/></Field><Field label={text.target}><Input type="number" min="0" max="100" value={scenarioForm.self_sufficiency_target_pct} onChange={e=>setScenarioForm(f=>({...f,self_sufficiency_target_pct:e.target.value}))}/></Field><Field label={text.waste}><Input type="number" min="0" max="100" value={scenarioForm.waste_pct} onChange={e=>setScenarioForm(f=>({...f,waste_pct:e.target.value}))}/></Field><div className="sm:col-span-2"><Field label={text.notes}><Textarea value={scenarioForm.notes} onChange={e=>setScenarioForm(f=>({...f,notes:e.target.value}))}/></Field></div><div className="sm:col-span-2"><Button disabled={saving}><Plus className="mr-2 h-4 w-4"/>{text.create}</Button></div></form></CardContent></Card></div>
    {selected?<><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users className="h-5 w-5"/>} label={text.people} value={metrics.people.toLocaleString(numberLocale,{maximumFractionDigits:1})} detail={metrics.bookingAvg>0?`${metrics.bookingAvg.toLocaleString(numberLocale,{maximumFractionDigits:1})} ${text.bookingPeople}`:text.noBookings}/><Metric icon={<Wheat className="h-5 w-5"/>} label={text.foodDemand} value={`${metrics.totalDemand.toLocaleString(numberLocale,{maximumFractionDigits:0})} kg`}/><Metric icon={<Sprout className="h-5 w-5"/>} label={text.plannedSupply} value={`${metrics.planned.toLocaleString(numberLocale,{maximumFractionDigits:0})} kg`}/><Metric icon={<Target className="h-5 w-5"/>} label={text.selfSufficiency} value={`${metrics.self.toLocaleString(numberLocale,{maximumFractionDigits:1})}%`} detail={`${text.target}: ${selected.self_sufficiency_target_pct}%`}/></section>
      <Card><CardHeader><CardTitle>{text.cropMix}</CardTitle><CardDescription>{text.cropMixHelp}</CardDescription></CardHeader><CardContent><form onSubmit={addTarget} className="grid gap-3 md:grid-cols-[1.5fr_1fr_1fr_auto]"><Field label={text.crop}><Input value={targetForm.crop_name} onChange={e=>setTargetForm(f=>({...f,crop_name:e.target.value}))} required/></Field><Field label={text.kgPersonWeek}><Input type="number" min="0" step="0.01" value={targetForm.consumption} onChange={e=>setTargetForm(f=>({...f,consumption:e.target.value}))}/></Field><Field label={text.share}><Input type="number" min="0" max="100" value={targetForm.share} onChange={e=>setTargetForm(f=>({...f,share:e.target.value}))}/></Field><div className="flex items-end"><Button className="w-full" disabled={saving}><Plus className="mr-2 h-4 w-4"/>{text.addTarget}</Button></div></form></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarRange className="h-5 w-5"/>{text.cropMix}</CardTitle><CardDescription>{text.assumption}</CardDescription></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[980px] text-sm"><thead><tr>{[text.crop,text.demand,text.planned,text.forecast,text.harvested,text.importGap,text.coverage,text.action].map(h=><th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{metrics.rows.map(r=><tr key={r.crop} className="border-t border-border"><td className="px-4 py-3 font-medium">{r.crop}</td><td className="px-4 py-3">{r.demand.toLocaleString(numberLocale,{maximumFractionDigits:1})}</td><td className="px-4 py-3">{r.planned.toLocaleString(numberLocale,{maximumFractionDigits:1})}</td><td className="px-4 py-3">{r.forecast.toLocaleString(numberLocale,{maximumFractionDigits:1})}</td><td className="px-4 py-3">{r.harvested.toLocaleString(numberLocale,{maximumFractionDigits:1})}</td><td className="px-4 py-3 font-semibold">{r.gap.toLocaleString(numberLocale,{maximumFractionDigits:1})}</td><td className="px-4 py-3"><Badge variant={r.coverage>=90?"default":"outline"}>{r.coverage.toLocaleString(numberLocale,{maximumFractionDigits:0})}%</Badge></td><td className="px-4 py-3"><Button asChild size="sm" variant="outline"><Link href={`/${lang}/orchard/game-plan?demand_crop=${encodeURIComponent(r.crop)}&demand_gap_kg=${Math.ceil(r.gap)}`}>{text.addPlan}</Link></Button></td></tr>)}{metrics.rows.length===0?<tr><td colSpan={8} className="px-4 py-10 text-center text-muted-foreground">{text.noTargets}</td></tr>:null}</tbody></table></CardContent></Card></>:null}
  </div></AppLayout>
}

function Field({label,children}:{label:string;children:ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Metric({icon,label,value,detail}:{icon:ReactNode;label:string;value:string;detail?:string}){return <Card><CardContent className="flex min-h-[132px] flex-col justify-between p-5"><div className="flex items-center justify-between text-muted-foreground"><span className="text-xs font-medium uppercase tracking-[.14em]">{label}</span>{icon}</div><div><div className="text-3xl font-semibold tracking-tight">{value}</div>{detail?<p className="mt-1 text-xs text-muted-foreground">{detail}</p>:null}</div></CardContent></Card>}
