"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowRight, CalendarRange, Leaf } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { Badge } from "@/components/ui/badge"
import { cropChipStyle, cropColor, cropPhaseStyle } from "@/lib/orchard/crop-identity"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Plan={id:string;season:string|null;status:string}
type Cycle={id:string;game_plan_id:string;crop_name:string}
type Succession={id:string;crop_cycle_id:string;sequence_no:number;planned_first_harvest_date:string|null;planned_last_harvest_date:string|null}
type Allocation={crop_succession_id:string}
type Harvest={id:string;crop_succession_id:string|null;harvest_date:string;quantity_harvested:number|null;harvest_unit:string|null;harvest_lot_code:string|null}
type CropProfile={crop_name:string;crop_family:string|null}
type ActualSummary={passes:number;byUnit:Map<string,number>}
type WindowRow={s:Succession;cycle:Cycle}
type CropRow={crop:string;windows:WindowRow[];successionIds:Set<string>}

const copy={
 en:{eyebrow:"Orchard · Harvest",title:"Weekly harvest availability",description:"The reconciled field plan is read as a crop-by-week availability matrix. Crop identity keeps the same canonical family color used across Calendar, Crop Map and Nursery.",planned:"Reconciled harvest windows",recorded:"Current-plan harvest passes",active:"Open now",next:"Next / active harvest",none:"No harvest window",noActual:"No harvest has been recorded for the reconciled 2026/27 field plantings yet.",crop:"Crop",actual:"Actual recorded",advanced:"Record / manage harvest",source:"Planned availability comes from exact succession harvest windows. Actual quantities come only from orchard_harvest_records with matching crop_succession_id; incompatible units are never summed.",passes:"passes",mixed:"mixed units",loadError:"Could not load harvest desk.",matrix:"Season availability",matrixHelp:"Each weekly cell counts how many reconciled successions for that crop have an open harvest window during the week. Color identifies the crop; intensity means harvest availability.",week:"W",weeks:"weeks",successions:"successions"},
 es:{eyebrow:"Huerto · Cosecha",title:"Disponibilidad semanal de cosecha",description:"El plan de campo reconciliado se lee como una matriz cultivo×semana. La identidad del cultivo conserva el mismo color canónico de familia usado en Calendario, Crop Map y Vivero.",planned:"Ventanas reconciliadas",recorded:"Pasadas reales del plan",active:"Abiertas hoy",next:"Próxima / activa",none:"Sin ventana de cosecha",noActual:"Todavía no hay cosechas registradas para las plantaciones de campo reconciliadas 2026/27.",crop:"Cultivo",actual:"Real registrado",advanced:"Registrar / gestionar cosecha",source:"La disponibilidad planificada viene de las ventanas exactas de cada sucesión. Las cantidades reales vienen sólo de orchard_harvest_records con crop_succession_id coincidente; nunca se suman unidades incompatibles.",passes:"pasadas",mixed:"unidades mixtas",loadError:"No fue posible cargar la mesa de cosecha.",matrix:"Disponibilidad de temporada",matrixHelp:"Cada celda semanal cuenta cuántas sucesiones reconciliadas tienen una ventana de cosecha abierta. El color identifica el cultivo; la intensidad representa disponibilidad de cosecha.",week:"S",weeks:"semanas",successions:"sucesiones"},
 de:{eyebrow:"Orchard · Ernte",title:"Wöchentliche Ernteverfügbarkeit",description:"Der abgeglichene Feldplan wird als Kultur×Woche-Matrix gelesen. Kulturidentität verwendet dieselbe kanonische Familienfarbe wie Kalender, Crop Map und Anzucht.",planned:"Abgeglichene Erntefenster",recorded:"Ist-Ernten im Plan",active:"Heute offen",next:"Nächste / aktive Ernte",none:"Kein Erntefenster",noActual:"Für die abgeglichenen Feldpflanzungen 2026/27 wurde noch keine Ernte erfasst.",crop:"Kultur",actual:"Erfasstes Ist",advanced:"Ernte erfassen / verwalten",source:"Geplante Verfügbarkeit stammt aus den exakten Erntefenstern der Folgen. Ist-Mengen stammen nur aus orchard_harvest_records mit passender crop_succession_id; inkompatible Einheiten werden nie summiert.",passes:"Durchgänge",mixed:"gemischte Einheiten",loadError:"Erntetisch konnte nicht geladen werden.",matrix:"Saisonverfügbarkeit",matrixHelp:"Jede Wochenzelle zählt offene Erntefenster. Farbe identifiziert die Kultur; Intensität zeigt Ernteverfügbarkeit.",week:"W",weeks:"Wochen",successions:"Folgen"},
} as const

const localeMap:Record<Locale,string>={en:"en-US",es:"es-CL",de:"de-DE"}
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())
const dateLabel=(v:string,locale:string)=>new Date(`${v}T12:00:00`).toLocaleDateString(locale,{day:"2-digit",month:"short",year:"numeric"})
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`
const mondayOf=(value:string)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()-((d.getDay()+6)%7));return dateKey(d)}
const addDays=(value:string,days:number)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()+days);return dateKey(d)}
const weekKeys=(start:string,end:string)=>{const out:string[]=[];let key=mondayOf(start);while(key<=end&&out.length<60){out.push(key);key=addDays(key,7)}return out}
const isoWeek=(value:string)=>{const d=new Date(`${value}T12:00:00Z`);const day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day+3);const firstThursday=new Date(Date.UTC(d.getUTCFullYear(),0,4));return 1+Math.round((d.getTime()-firstThursday.getTime())/604800000)}
const normalize=(value:string)=>value.trim().toLowerCase()

export default function DietrichHarvestDesk(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const lang:Locale=language;const text=copy[lang];const locale=localeMap[lang]
 const [plans,setPlans]=useState<Plan[]>([]),[cycles,setCycles]=useState<Cycle[]>([]),[successions,setSuccessions]=useState<Succession[]>([]),[allocations,setAllocations]=useState<Allocation[]>([]),[harvests,setHarvests]=useState<Harvest[]>([]),[profiles,setProfiles]=useState<CropProfile[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 useEffect(()=>{let live=true;setLoading(true);setError(null);void Promise.all([
  supabase.from("orchard_game_plans").select("id,season,status").order("start_date",{ascending:false}),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id,sequence_no,planned_first_harvest_date,planned_last_harvest_date").neq("status","cancelled"),
  supabase.from("orchard_bed_allocations").select("crop_succession_id"),
  supabase.from("orchard_harvest_records").select("id,crop_succession_id,harvest_date,quantity_harvested,harvest_unit,harvest_lot_code").order("harvest_date",{ascending:false}),
  supabase.from("orchard_crop_library").select("crop_name,crop_family").eq("is_active",true).eq("classification_scheme","black_swan_canonical").eq("classification_code","fundo_corcovado"),
 ]).then(([p,c,s,a,h,f])=>{if(!live)return;const first=p.error??c.error??s.error??a.error??h.error??f.error;if(first){setError(`${text.loadError} ${first.message}`);setLoading(false);return}setPlans((p.data??[]) as Plan[]);setCycles((c.data??[]) as Cycle[]);setSuccessions((s.data??[]) as Succession[]);setAllocations((a.data??[]) as Allocation[]);setHarvests((h.data??[]) as Harvest[]);setProfiles((f.data??[]) as CropProfile[]);setLoading(false)});return()=>{live=false}},[supabase,text.loadError])

 const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null
 const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const familyByCrop=new Map(profiles.map(profile=>[normalize(profile.crop_name),profile.crop_family]));const familyFor=(crop:string)=>familyByCrop.get(normalize(crop))??null
 const scopedCycles=plan?cycles.filter(c=>c.game_plan_id===plan.id):[];const cycleById=new Map(scopedCycles.map(c=>[c.id,c]));const allocatedIds=new Set(allocations.map(a=>a.crop_succession_id));const scopedSuccessions=successions.filter(s=>cycleById.has(s.crop_cycle_id)&&allocatedIds.has(s.id));const successionById=new Map(scopedSuccessions.map(s=>[s.id,s]));const scopedHarvests=harvests.filter(h=>h.crop_succession_id&&successionById.has(h.crop_succession_id))
 const windows:WindowRow[]=scopedSuccessions.filter(s=>s.planned_first_harvest_date&&s.planned_last_harvest_date).map(s=>({s,cycle:cycleById.get(s.crop_cycle_id)!})).sort((a,b)=>a.s.planned_first_harvest_date!.localeCompare(b.s.planned_first_harvest_date!))
 const todayKey=today();const openNow=windows.filter(w=>w.s.planned_first_harvest_date!<=todayKey&&w.s.planned_last_harvest_date!>=todayKey);const next=openNow[0]??windows.find(w=>w.s.planned_first_harvest_date!>todayKey)??null
 const actualBySuccession=new Map<string,ActualSummary>();for(const h of scopedHarvests){if(!h.crop_succession_id)continue;const current=actualBySuccession.get(h.crop_succession_id)??{passes:0,byUnit:new Map<string,number>()};current.passes+=1;if(h.quantity_harvested!=null&&h.harvest_unit){current.byUnit.set(h.harvest_unit,(current.byUnit.get(h.harvest_unit)??0)+Number(h.quantity_harvested))}actualBySuccession.set(h.crop_succession_id,current)}
 const cropRows:CropRow[]=[];for(const row of windows){let crop=cropRows.find(c=>c.crop===row.cycle.crop_name);if(!crop){crop={crop:row.cycle.crop_name,windows:[],successionIds:new Set<string>()};cropRows.push(crop)}crop.windows.push(row);crop.successionIds.add(row.s.id)}cropRows.sort((a,b)=>a.crop.localeCompare(b.crop))
 const actualLabel=(ids:Set<string>)=>{const summaries=[...ids].map(id=>actualBySuccession.get(id)).filter((v):v is ActualSummary=>Boolean(v));if(!summaries.length)return "—";const units=new Map<string,number>();let passes=0;for(const summary of summaries){passes+=summary.passes;for(const [unit,value] of summary.byUnit)units.set(unit,(units.get(unit)??0)+value)}const entries=[...units.entries()];if(entries.length===1)return `${entries[0][1].toLocaleString(locale,{maximumFractionDigits:2})} ${entries[0][0]} · ${passes} ${text.passes}`;if(entries.length>1)return `${passes} ${text.passes} · ${text.mixed}`;return `${passes} ${text.passes}`}
 const minHarvest=windows.map(w=>w.s.planned_first_harvest_date!).sort()[0]??todayKey;const maxHarvest=windows.map(w=>w.s.planned_last_harvest_date!).sort().at(-1)??todayKey;const weeks=weekKeys(minHarvest,maxHarvest)
 const activeInWeek=(row:WindowRow,weekStart:string)=>{const weekEnd=addDays(weekStart,6);return row.s.planned_first_harvest_date!<=weekEnd&&row.s.planned_last_harvest_date!>=weekStart}
 const advancedHref=`/${language}/orchard/harvest${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`

 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1700px] px-4 pb-16 pt-6 sm:px-6 lg:px-8">
  <header className="mb-4 max-w-5xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--orchard-green)]">{text.eyebrow}</p><div className="mt-1.5 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-normal sm:text-4xl">{text.title}</h1>{plan?.season?<Badge variant="secondary">{plan.season}</Badge>:null}</div><p className="mt-2 max-w-4xl text-sm leading-5 text-muted-foreground">{text.description}</p></header>
  {loading?<div className="py-12 text-sm text-muted-foreground">…</div>:error?<div className="border-y border-red-400/30 py-4 text-sm text-red-300">{error}</div>:<>
   <section className="mb-4 grid border-y border-[var(--bs-divider-subtle)] sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CalendarRange} label={text.planned} value={windows.length}/><Metric icon={Leaf} label={text.recorded} value={scopedHarvests.length}/><Metric label={text.active} value={openNow.length}/><div className="border-r border-[var(--bs-divider-subtle)] px-3 py-3 last:border-r-0"><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{text.next}</p>{next?(()=>{const family=familyFor(next.cycle.crop_name);const chip=cropChipStyle(next.cycle.crop_name,family);return <><p className="mt-1.5 inline-flex items-center gap-2 text-sm font-medium"><i className="h-2 w-2 rounded-full" style={{backgroundColor:cropColor(next.cycle.crop_name,family)}}/>{next.cycle.crop_name} · #{next.s.sequence_no}</p><p className="mt-0.5 text-[10px]" style={{color:chip.color}}>{dateLabel(next.s.planned_first_harvest_date!,locale)} — {dateLabel(next.s.planned_last_harvest_date!,locale)}</p></>})():<p className="mt-1.5 text-sm font-medium">{text.none}</p>}</div></section>

   <section className="mb-6"><div className="mb-2"><p className="text-xs uppercase tracking-[.16em] text-muted-foreground">{text.matrix}</p><h2 className="mt-1 text-2xl font-normal">{cropRows.length} {text.crop.toLowerCase()} · {weeks.length} {text.weeks}</h2><p className="mt-1 max-w-4xl text-xs leading-5 text-muted-foreground">{text.matrixHelp}</p></div><div className="overflow-x-auto border-y border-[var(--bs-divider-subtle)]"><div style={{minWidth:`${260+weeks.length*54+190}px`}}><div className="flex border-b border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-secondary)] text-[10px] uppercase tracking-[.08em] text-muted-foreground"><div className="sticky left-0 z-20 w-[260px] shrink-0 border-r border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-secondary)] px-3 py-2">{text.crop}</div>{weeks.map(week=><div key={week} className="w-[54px] shrink-0 border-r border-[var(--bs-divider-subtle)] px-1 py-2 text-center"><span className="block">{text.week}{isoWeek(week)}</span><span className="mt-0.5 block normal-case tracking-normal">{new Date(`${week}T12:00:00`).toLocaleDateString(locale,{day:"2-digit",month:"short"})}</span></div>)}<div className="sticky right-0 z-20 w-[190px] shrink-0 bg-[var(--bs-surface-secondary)] px-3 py-2">{text.actual}</div></div>
   {cropRows.map(row=>{const family=familyFor(row.crop);const color=cropColor(row.crop,family);const chip=cropChipStyle(row.crop,family);const harvestStyle=cropPhaseStyle(row.crop,family,"harvest");return <div key={row.crop} className="flex min-h-[48px] border-b border-[var(--bs-divider-subtle)] last:border-b-0"><div className="sticky left-0 z-10 w-[260px] shrink-0 border-r border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)] px-3 py-2.5" style={{boxShadow:`inset 2px 0 0 ${color}`}}><strong className="inline-flex items-center gap-2 text-sm font-medium"><i className="h-2 w-2 rounded-full" style={{backgroundColor:color}}/>{row.crop}</strong><p className="mt-0.5 text-[10px]" style={{color:chip.color}}>{row.successionIds.size} {text.successions}{family?` · ${family}`:""}</p></div>{weeks.map(week=>{const active=row.windows.filter(w=>activeInWeek(w,week)).length;const currentWeek=todayKey>=week&&todayKey<=addDays(week,6);return <div key={week} className="flex w-[54px] shrink-0 items-center justify-center border-r border-[var(--orchard-line-soft)] text-xs tabular-nums" style={{backgroundColor:active?harvestStyle.backgroundColor:"transparent",color:active?color:undefined,fontWeight:active?600:400,outline:currentWeek?`1px solid ${color}`:undefined,outlineOffset:currentWeek?"-1px":undefined}}>{active||""}</div>})}<div className="sticky right-0 z-10 flex w-[190px] shrink-0 items-center bg-[var(--bs-surface-primary)] px-3 py-2 text-xs">{actualLabel(row.successionIds)}</div></div>})}</div></div></section>

   {scopedHarvests.length===0?<p className="mb-5 text-sm text-muted-foreground">{text.noActual}</p>:null}
   <footer className="flex justify-end border-t border-[var(--bs-divider-subtle)] pt-4"><Link href={advancedHref} className="inline-flex items-center gap-2 text-sm text-foreground">{text.advanced}<ArrowRight className="h-4 w-4"/></Link></footer>
  </>}
 </main></AppLayout>
}

function Metric({icon:Icon,label,value}:{icon?:typeof CalendarRange;label:string;value:number}){return <div className="border-r border-[var(--bs-divider-subtle)] px-3 py-3 last:border-r-0">{Icon?<Icon className="h-3.5 w-3.5 text-muted-foreground"/>:null}<p className={`${Icon?"mt-2":""} text-[10px] uppercase tracking-wide text-muted-foreground`}>{label}</p><p className="mt-1 text-2xl tabular-nums">{value}</p></div>}
