begin;

with seed(code, title, domain, owner_role, description, risk_level, review_frequency_days) as (
  values
    ('SOP-HSP-001','Gestión integral de reservas y estadías','Hospitalidad','Coordinación de hospitalidad','Flujo maestro para crear, confirmar, modificar, ejecutar y cerrar reservas y estadías.','medium',180),
    ('SOP-HSK-001','Preparación y limpieza de alojamientos','Housekeeping','Housekeeping','Preparación, limpieza, reposición, inspección y liberación de alojamientos.','medium',180),
    ('SOP-LOG-001','Traslados y logística de huéspedes','Logística','Coordinación logística','Planificación y ejecución de llegadas, salidas, vehículos, conductores, equipaje e incidencias.','medium',180),
    ('SOP-ACT-001','Gestión de actividades y experiencias','Actividades','Coordinación de actividades','Programación, preparación, ejecución, cierre, cancelación y reprogramación de actividades.','medium',180),
    ('SOP-MNT-001','Mantenimiento e incidencias','Mantenimiento','Mantenimiento','Registro, evaluación, asignación, ejecución, evidencia y cierre de incidencias y mantenimiento.','high',120),
    ('SOP-INV-001','Inventario, activos y abastecimiento','Inventario','Inventario y activos','Entradas, salidas, conteos, ajustes, faltantes, reposición y activos fuera de servicio.','medium',180),
    ('SOP-PRC-001','Compras y proveedores','Compras','Compras y administración','Solicitud, revisión, aprobación, orden de compra, recepción y cierre de adquisiciones.','medium',180),
    ('SOP-OPS-001','Tareas, personal y turnos','Operaciones','Coordinación operacional','Asignación, priorización, cambio de responsable, bloqueos, evidencia y cierre de tareas.','medium',180),
    ('SOP-FIN-001','Facturación interna y pagos','Finanzas','Administración y finanzas','Generación correlativa, revisión, emisión, pagos, saldos, anulaciones y cierre financiero interno.','high',120),
    ('SOP-PROP-001','Propiedades e infraestructura','Propiedades','Administración de propiedades','Inspección, disponibilidad, apertura, cierre temporal, bloqueos y condición operacional de propiedades.','medium',180)
)
insert into public.sop_procedures(code,title,domain,owner_role,status,review_frequency_days,next_review_date,risk_level,ppe_requirements,description)
select code,title,domain,owner_role,'draft',review_frequency_days,current_date + review_frequency_days,risk_level,'{}'::text[],description
from seed
on conflict (code) do update set title=excluded.title,domain=excluded.domain,owner_role=excluded.owner_role,description=excluded.description,risk_level=excluded.risk_level,review_frequency_days=excluded.review_frequency_days,updated_at=now();

with version_seed(code, objective, scope, prerequisites, required_materials, acceptance_criteria, exception_instructions, estimated_minutes) as (
  values
    ('SOP-HSP-001','Coordinar una reserva completa desde su creación hasta su cierre.','Reservas, estadías, modificaciones, cancelaciones, check-in y check-out.','Documento operacional creado y datos esenciales disponibles.','{}'::text[],'La reserva queda trazable, sin conflictos abiertos y con tareas críticas cerradas.','Registrar la excepción, asignar responsable y escalar cuando afecte seguridad, huésped o continuidad.',45),
    ('SOP-HSK-001','Entregar alojamientos limpios, abastecidos y operativamente disponibles.','Preparación previa, limpieza durante estadía, salida e inspección.','Alojamiento identificado y ventana de trabajo confirmada.','{}'::text[],'El alojamiento cumple checklist, evidencia requerida y queda liberado o bloqueado con motivo.','Bloquear el alojamiento y notificar cuando exista daño, riesgo o falta crítica.',60),
    ('SOP-LOG-001','Ejecutar traslados seguros, puntuales y coordinados.','Llegadas, salidas y movimientos asociados a huéspedes.','Horario, pasajeros, punto de encuentro y recurso confirmados.','{}'::text[],'Traslado completado, pasajeros confirmados e incidencias registradas.','Reprogramar y escalar ante retraso, falla de vehículo, ausencia o riesgo de ruta.',30),
    ('SOP-ACT-001','Preparar y ejecutar actividades con recursos y responsables confirmados.','Actividades y experiencias asociadas a documentos operacionales.','Participantes, horario, capacidad y recursos revisados.','{}'::text[],'Actividad cerrada con participantes, recursos, resultado e incidencias registrados.','Suspender o reprogramar ante condiciones inseguras, falta de recurso o capacidad excedida.',45),
    ('SOP-MNT-001','Resolver incidencias y trabajos de mantenimiento con trazabilidad.','Mantenimiento correctivo, preventivo e incidencias.','Incidencia registrada, ubicación y prioridad definidas.','{}'::text[],'Trabajo probado, evidencia registrada, recurso liberado y cierre aprobado cuando corresponda.','Aislar el área o recurso y escalar inmediatamente ante riesgo para personas o continuidad.',60),
    ('SOP-INV-001','Mantener cantidades y condición de activos e inventario confiables.','Movimientos, conteos, ajustes, faltantes y recursos fuera de servicio.','Ítem o activo identificado y motivo del movimiento registrado.','{}'::text[],'Movimiento trazable, saldo actualizado y diferencias justificadas.','Bloquear movimientos dudosos y solicitar revisión cuando exista pérdida, daño o diferencia relevante.',30),
    ('SOP-PRC-001','Comprar de forma trazable y proporcional a la necesidad operacional.','Solicitud, aprobación, compra, recepción y devolución.','Necesidad, solicitante, cantidad y centro operacional identificados.','{}'::text[],'Compra aprobada, recibida, conciliada y cerrada con documentación suficiente.','Detener el flujo ante proveedor no validado, diferencia de precio o recepción no conforme.',45),
    ('SOP-OPS-001','Asignar y cerrar tareas operacionales con responsabilidad clara.','Tareas, responsables, turnos, bloqueos y evidencias.','Tarea definida con fecha, prioridad y resultado esperado.','{}'::text[],'Tarea cerrada con resultado verificable o bloqueo formalmente registrado.','Reasignar o escalar cuando no exista capacidad, acceso, recurso o competencia suficiente.',20),
    ('SOP-FIN-001','Emitir y cerrar facturación interna manteniendo correlativos y trazabilidad.','Facturas internas, líneas, pagos, saldos y anulaciones.','Documento operacional y líneas facturables revisados.','{}'::text[],'Factura correlativa reproducible, pagos conciliados y saldo o anulación correctamente registrado.','No emitir ante diferencias; conservar correlativo y registrar razón en caso de anulación.',30),
    ('SOP-PROP-001','Mantener propiedades y espacios con estado operacional explícito.','Inspecciones, apertura, cierre, disponibilidad y bloqueos.','Propiedad o espacio identificado y alcance de inspección definido.','{}'::text[],'Estado actualizado, restricciones visibles y acciones pendientes asignadas.','Bloquear disponibilidad y crear incidencia ante condición insegura o no conforme.',45)
)
insert into public.sop_versions(sop_procedure_id,version_number,status,objective,scope,prerequisites,required_materials,acceptance_criteria,exception_instructions,estimated_minutes)
select p.id,1,'draft',v.objective,v.scope,v.prerequisites,v.required_materials,v.acceptance_criteria,v.exception_instructions,v.estimated_minutes
from version_seed v join public.sop_procedures p on p.code=v.code
where not exists (select 1 from public.sop_versions sv where sv.sop_procedure_id=p.id and sv.version_number=1);

with step_seed(code, step_number, title, instruction, requires_evidence, evidence_type, requires_approval, expected_minutes) as (
  values
    ('SOP-HSP-001',1,'Revisar solicitud','Validar fechas, participantes, datos de contacto, servicios y observaciones esenciales.',false,null,false,5),('SOP-HSP-001',2,'Confirmar disponibilidad','Comprobar alojamiento, actividades, traslados y recursos antes de confirmar.',true,'registro',false,10),('SOP-HSP-001',3,'Coordinar ejecución','Crear o revisar tareas de preparación, llegada, estadía y salida.',false,null,false,15),('SOP-HSP-001',4,'Ejecutar llegada y estadía','Registrar check-in, cambios, solicitudes e incidencias relevantes.',true,'registro',false,10),('SOP-HSP-001',5,'Cerrar operación','Completar check-out, extras, tareas pendientes y estado financiero.',true,'registro',true,5),
    ('SOP-HSK-001',1,'Revisar programación','Confirmar alojamiento, tipo de servicio y hora límite.',false,null,false,5),('SOP-HSK-001',2,'Preparar recursos','Reunir insumos y verificar faltantes antes de ingresar.',false,null,false,5),('SOP-HSK-001',3,'Limpiar y reponer','Ejecutar limpieza, lavandería, amenities y reposición definida.',false,null,false,35),('SOP-HSK-001',4,'Inspeccionar','Revisar limpieza, funcionamiento básico, daños y presentación.',true,'fotografia',false,10),('SOP-HSK-001',5,'Liberar o bloquear','Marcar disponible o bloquear con motivo y acción correctiva.',true,'registro',true,5),
    ('SOP-LOG-001',1,'Confirmar traslado','Validar pasajeros, horario, origen, destino y equipaje.',false,null,false,5),('SOP-LOG-001',2,'Asignar recursos','Confirmar vehículo, conductor y capacidad.',true,'registro',false,5),('SOP-LOG-001',3,'Realizar control previo','Revisar condición básica, combustible, comunicaciones y ruta.',false,null,false,10),('SOP-LOG-001',4,'Ejecutar traslado','Confirmar inicio, pasajeros y llegada.',true,'registro',false,5),('SOP-LOG-001',5,'Cerrar o registrar incidencia','Cerrar el servicio o documentar desviación y acción siguiente.',true,'registro',false,5),
    ('SOP-ACT-001',1,'Validar actividad','Revisar participantes, capacidad, horario y condiciones.',false,null,false,5),('SOP-ACT-001',2,'Asignar recursos','Confirmar responsable, espacio, equipo y transporte si aplica.',true,'registro',false,10),('SOP-ACT-001',3,'Preparar actividad','Completar revisión previa y comunicar instrucciones necesarias.',false,null,false,15),('SOP-ACT-001',4,'Ejecutar y supervisar','Registrar inicio, participantes y cualquier desviación.',true,'registro',false,10),('SOP-ACT-001',5,'Cerrar o reprogramar','Registrar resultado, recursos devueltos y acciones pendientes.',true,'registro',false,5),
    ('SOP-MNT-001',1,'Registrar y clasificar','Identificar ubicación, activo, síntoma, impacto y prioridad.',true,'fotografia',false,10),('SOP-MNT-001',2,'Asegurar el área','Bloquear o señalizar cuando exista riesgo.',true,'fotografia',false,5),('SOP-MNT-001',3,'Diagnosticar y asignar','Definir alcance, responsable, recursos y plazo.',false,null,false,15),('SOP-MNT-001',4,'Ejecutar trabajo','Realizar intervención y registrar materiales o acciones.',true,'fotografia',false,25),('SOP-MNT-001',5,'Probar y cerrar','Verificar funcionamiento, liberar recurso y aprobar cierre.',true,'registro',true,5),
    ('SOP-INV-001',1,'Identificar movimiento','Definir ítem, cantidad, origen, destino y motivo.',false,null,false,5),('SOP-INV-001',2,'Verificar condición y saldo','Revisar disponibilidad, estado físico y restricciones.',true,'registro',false,5),('SOP-INV-001',3,'Registrar movimiento','Procesar entrada, salida, ajuste, conteo o bloqueo.',true,'registro',false,10),('SOP-INV-001',4,'Resolver diferencias','Documentar faltantes, daños o discrepancias.',true,'fotografia',false,5),('SOP-INV-001',5,'Confirmar cierre','Validar saldo y generar reposición o incidencia si corresponde.',false,null,false,5),
    ('SOP-PRC-001',1,'Registrar necesidad','Definir producto o servicio, cantidad, justificación y fecha requerida.',false,null,false,5),('SOP-PRC-001',2,'Revisar y aprobar','Validar necesidad, presupuesto, autorización y proveedor.',true,'registro',true,10),('SOP-PRC-001',3,'Emitir orden','Generar orden correlativa con condiciones y entrega.',true,'documento',false,10),('SOP-PRC-001',4,'Recibir y verificar','Comparar cantidad, condición, precio y documentos.',true,'fotografia',false,15),('SOP-PRC-001',5,'Conciliar y cerrar','Registrar recepción, diferencias, devolución o cierre.',true,'registro',true,5),
    ('SOP-OPS-001',1,'Definir tarea','Establecer resultado, prioridad, fecha y dependencia.',false,null,false,5),('SOP-OPS-001',2,'Asignar responsable','Confirmar persona, turno y capacidad.',true,'registro',false,5),('SOP-OPS-001',3,'Ejecutar o bloquear','Realizar trabajo o registrar motivo de bloqueo y acción requerida.',false,null,false,5),('SOP-OPS-001',4,'Adjuntar evidencia','Incorporar evidencia proporcional al riesgo y resultado.',true,'registro',false,3),('SOP-OPS-001',5,'Verificar y cerrar','Comprobar resultado, pendientes y cierre.',true,'registro',false,2),
    ('SOP-FIN-001',1,'Revisar documento origen','Validar cliente, moneda, líneas, cantidades y precios.',false,null,false,5),('SOP-FIN-001',2,'Generar correlativo','Emitir la factura interna mediante el generador transaccional.',true,'documento',false,5),('SOP-FIN-001',3,'Revisar y emitir','Verificar totales, descuentos, impuestos, vencimiento y estado.',true,'documento',true,10),('SOP-FIN-001',4,'Registrar pagos','Conciliar monto, fecha, medio y saldo.',true,'registro',false,5),('SOP-FIN-001',5,'Cerrar o anular','Cerrar saldo o conservar correlativo y registrar motivo de anulación.',true,'registro',true,5),
    ('SOP-PROP-001',1,'Identificar propiedad','Definir ubicación, espacio y motivo de revisión.',false,null,false,5),('SOP-PROP-001',2,'Inspeccionar condición','Revisar disponibilidad, seguridad, servicios y restricciones.',true,'fotografia',false,20),('SOP-PROP-001',3,'Actualizar estado','Marcar operativa, restringida, bloqueada o fuera de servicio.',true,'registro',false,5),('SOP-PROP-001',4,'Asignar acciones','Crear mantenimiento, limpieza, compra u otra tarea necesaria.',false,null,false,10),('SOP-PROP-001',5,'Verificar apertura o cierre','Confirmar estado final y comunicar disponibilidad.',true,'registro',true,5)
)
insert into public.sop_steps(sop_version_id,step_number,title,instruction,is_required,requires_evidence,evidence_type,requires_approval,expected_minutes,checklist_items,safety_notes)
select sv.id,s.step_number,s.title,s.instruction,true,s.requires_evidence,s.evidence_type,s.requires_approval,s.expected_minutes,'[]'::jsonb,null
from step_seed s join public.sop_procedures p on p.code=s.code join public.sop_versions sv on sv.sop_procedure_id=p.id and sv.version_number=1
where not exists (select 1 from public.sop_steps x where x.sop_version_id=sv.id and x.step_number=s.step_number);

commit;
