-- Persist FAO-aligned Orchard crop photography for the remaining P-Y index.
-- Crop identity comes from the FAO WCA 2020 crop master; imagery is mapped per crop,
-- avoiding generic category substitutions.

with photos(crop_name, photo_url) as (values
('Palm palmyra','https://commons.wikimedia.org/wiki/Special:FilePath/Borassus_flabellifer_fruit_on_tree.jpg'),
('Palm, kernel oil','https://commons.wikimedia.org/wiki/Special:FilePath/Elaeis_guineensis_-_noix_de_palme_-_oil_palm_-_raw_fruit_detail_showing_oil.jpg'),
('Palm, oil','https://commons.wikimedia.org/wiki/Special:FilePath/Elaeis_guineensis_oil_palm_fruit_Portoviejo_Ecuador.jpg'),
('Palm, sago','https://commons.wikimedia.org/wiki/Special:FilePath/Metroxylon_sagu%2C_the_Sago_Palm.jpg'),
('Papaya (pawpaw)','https://commons.wikimedia.org/wiki/Special:FilePath/Carica_Papaya_or_papaya_tree.jpg'),
('Parsley','https://images.unsplash.com/photo-1720354390554-84df8f2a7199?auto=format&fit=crop&w=1400&q=92'),
('Parsnip','https://commons.wikimedia.org/wiki/Special:FilePath/Pastinaca_sativa_SCA-120614-07.jpg'),
('Pea, edible dry, for grain','https://commons.wikimedia.org/wiki/Special:FilePath/Dried_Green_Peas.jpg'),
('Pea, harvested green','https://images.unsplash.com/photo-1751828374210-76f0be8c0078?auto=format&fit=crop&w=1400&q=92'),
('Peach','https://commons.wikimedia.org/wiki/Special:FilePath/Peaches_on_the_tree_at_Dehibolo_2023.jpg'),
('Peanut (groundnut)','https://commons.wikimedia.org/wiki/Special:FilePath/Peanut_plants.jpg'),
('Pear','https://commons.wikimedia.org/wiki/Special:FilePath/Pear_(Pyrus_communis)_(19691456728).jpg'),
('Pecan nut','https://commons.wikimedia.org/wiki/Special:FilePath/Pecan_tree_full_of_fruit.jpg'),
('Pepper, black','https://commons.wikimedia.org/wiki/Special:FilePath/Black_Pepper_(Piper_nigrum)_fruits.jpg'),
('Pepper, dry','https://commons.wikimedia.org/wiki/Special:FilePath/Dried_Capsicum_annuum-Red_Chilli_Pepper_on_Nanglo.jpg'),
('Persimmon','https://commons.wikimedia.org/wiki/Special:FilePath/Diospyros_kaki.jpg'),
('Pigeon pea','https://commons.wikimedia.org/wiki/Special:FilePath/Pigeon_peas.jpg'),
('Pineapple','https://commons.wikimedia.org/wiki/Special:FilePath/Ananas_comosus_fruit.jpg'),
('Pistachio nut','https://commons.wikimedia.org/wiki/Special:FilePath/Pistacia_vera_(Pistachio)_tree_in_RDA%2C_Bogra_03.jpg'),
('Plantain','https://commons.wikimedia.org/wiki/Special:FilePath/Musa_paradisiaca_(2914713852).jpg'),
('Plum','https://commons.wikimedia.org/wiki/Special:FilePath/Prunus_domestica_fruit.jpg'),
('Pomegranate','https://commons.wikimedia.org/wiki/Special:FilePath/Pomegranate_fruit_-_Punica_granatum.jpg'),
('Pomelo','https://commons.wikimedia.org/wiki/Special:FilePath/Pomelo_fruit.jpg'),
('Poppy seed','https://commons.wikimedia.org/wiki/Special:FilePath/Opium_poppy_seed_capsule.jpg'),
('Poppy straw','https://commons.wikimedia.org/wiki/Special:FilePath/Papaver_somniferum_-_Capsule_-_GBA_Viote.jpg'),
('Potato','https://commons.wikimedia.org/wiki/Special:FilePath/Potato_plant_.jpg'),
('Potato, sweet','https://commons.wikimedia.org/wiki/Special:FilePath/Ipomoea_batatas_-_Tubers.jpg'),
('Prune','https://commons.wikimedia.org/wiki/Special:FilePath/Fruits_Prunus_domestica.jpg'),
('Pumpkin, edible','https://commons.wikimedia.org/wiki/Special:FilePath/Pumpkin_vegetable.jpg'),
('Pumpkin, for fodder','https://commons.wikimedia.org/wiki/Special:FilePath/Pumpkin_vegetable.jpg'),
('Pyrethrum','https://commons.wikimedia.org/wiki/Special:FilePath/Tanacetum_cinerariifolium_(DITSL).JPG'),
('Queensland nut','https://commons.wikimedia.org/wiki/Special:FilePath/Macadamia_nuts.jpg'),
('Quince','https://commons.wikimedia.org/wiki/Special:FilePath/Cydonia_oblonga_fruit.jpg'),
('Quinine','https://commons.wikimedia.org/wiki/Special:FilePath/Samples_of_cinchona_bark%2C_Quinquina_Route_Equateur%2C_prepared_Wellcome_L0058850.jpg'),
('Quinoa','https://commons.wikimedia.org/wiki/Special:FilePath/Peru_Chenopodium_quinoa.jpg'),
('Radish','https://images.unsplash.com/photo-1589753014594-0676c69bbcbe?auto=format&fit=crop&w=1400&q=92'),
('Ramie','https://commons.wikimedia.org/wiki/Special:FilePath/Boehmeria_nivea.jpg'),
('Rapeseed (colza)','https://commons.wikimedia.org/wiki/Special:FilePath/Raps_Rapeseed_field_Brassica_napus_01.jpg'),
('Raspberry (all varieties)','https://commons.wikimedia.org/wiki/Special:FilePath/Rubus_idaeus_-_fruit.jpg'),
('Red beet','https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?auto=format&fit=crop&w=1400&q=92'),
('Redtop','https://commons.wikimedia.org/wiki/Special:FilePath/Agrostis_gigantea.jpg'),
('Rhea','https://commons.wikimedia.org/wiki/Special:FilePath/Boehmeria_nivea.jpg'),
('Rhubarb','https://commons.wikimedia.org/wiki/Special:FilePath/Rhubarb_(Rabarbra)_(Rheum_rhabarbarum)_-_And%C3%B8y%2C_Norway_2023-07-12.jpg'),
('Rice','https://commons.wikimedia.org/wiki/Special:FilePath/Rice_Field%2A.jpg'),
('Rose','https://commons.wikimedia.org/wiki/Special:FilePath/Rosa_Red_Chateau01.jpg'),
('Rubber','https://commons.wikimedia.org/wiki/Special:FilePath/Rubber_tree_tapping.jpg'),
('Rutabaga (swede)','https://commons.wikimedia.org/wiki/Special:FilePath/Rutabaga%2C_variety_nadmorska.JPG'),
('Rye','https://commons.wikimedia.org/wiki/Special:FilePath/Secale_cereale.jpg'),
('Ryegrass seed','https://commons.wikimedia.org/wiki/Special:FilePath/Lolium_perenne_-_perennial_ryegrass.jpg'),
('Safflower','https://commons.wikimedia.org/wiki/Special:FilePath/Carthamus_tinctorius.jpg'),
('Saffron','https://commons.wikimedia.org/wiki/Special:FilePath/Crocus_sativus%2C_saffron.jpg'),
('Sainfoin','https://commons.wikimedia.org/wiki/Special:FilePath/Onobrychis_viciifolia_-_img_25621.jpg'),
('Salsify','https://commons.wikimedia.org/wiki/Special:FilePath/SalsifyMeasured.JPG'),
('Sapodilla','https://commons.wikimedia.org/wiki/Special:FilePath/Manilkara_zapota_fruit.jpg'),
('Satsuma (mandarin/tangerine)','https://commons.wikimedia.org/wiki/Special:FilePath/Starr-171115-1105-Citrus_unshiu-Owari_satsuma_fruit-Hawea_Pl_Olinda-Maui_(38767544822).jpg'),
('Scorzonera (black salsify)','https://commons.wikimedia.org/wiki/Special:FilePath/Scorzonera_hispanica_sl165.jpg'),
('Sesame','https://commons.wikimedia.org/wiki/Special:FilePath/Sesamum_indicum.jpg'),
('Shea tree (shea butter or karite nut)','https://commons.wikimedia.org/wiki/Special:FilePath/Vitellaria_paradoxa_fruit.jpg'),
('Sisal','https://commons.wikimedia.org/wiki/Special:FilePath/Sisal_Plantation_in_Kenya.jpg'),
('Sorghum','https://commons.wikimedia.org/wiki/Special:FilePath/SorghumBicolorField.jpg'),
('Sorghum, broom','https://commons.wikimedia.org/wiki/Special:FilePath/Sorghum_bicolor.JPG'),
('Sorghum, durra','https://commons.wikimedia.org/wiki/Special:FilePath/Sorghum_bicolor.JPG'),
('Sorghum, Guinea corn','https://commons.wikimedia.org/wiki/Special:FilePath/SorghumBicolorField.jpg'),
('Sorghum, jowar','https://commons.wikimedia.org/wiki/Special:FilePath/SorghumBicolorField.jpg'),
('Sorghum, sweet','https://commons.wikimedia.org/wiki/Special:FilePath/SorghumBicolorField.jpg'),
('Sour cherry','https://commons.wikimedia.org/wiki/Special:FilePath/Prunus_cerasus_fruit.jpg'),
('Soybean','https://commons.wikimedia.org/wiki/Special:FilePath/Soybean.USDA.jpg'),
('Soybean hay','https://commons.wikimedia.org/wiki/Special:FilePath/Soybean.USDA.jpg'),
('Spelt wheat','https://commons.wikimedia.org/wiki/Special:FilePath/Triticum_spelta%2C_spelt.jpg'),
('Spinach','https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=1400&q=92'),
('Squash','https://commons.wikimedia.org/wiki/Special:FilePath/Cucurbita_pepo_fruit.jpg'),
('Strawberry','https://commons.wikimedia.org/wiki/Special:FilePath/Starr-090518-7951-Fragaria_x_ananassa-crop_and_worker_in_field-Omaopio-Maui_(24328636823).jpg'),
('Sugar beet','https://commons.wikimedia.org/wiki/Special:FilePath/SugarBeet.jpg'),
('Sugar beet for fodder','https://commons.wikimedia.org/wiki/Special:FilePath/SugarBeet.jpg'),
('Sugar beet for seed','https://commons.wikimedia.org/wiki/Special:FilePath/SugarBeet.jpg'),
('Sugar cane for fodder','https://commons.wikimedia.org/wiki/Special:FilePath/Sugar_Cane_(Saccharum_officinarum)_1.jpg'),
('Sugar cane for sugar or alcohol','https://commons.wikimedia.org/wiki/Special:FilePath/Starr-160324-0641-Saccharum_officinarum-view_Mokulele_Hwy_and_bike_path_Cane_Haul_Rd-Puunene-Maui_(26922240176).jpg'),
('Sugar cane for thatching','https://commons.wikimedia.org/wiki/Special:FilePath/Saccharum_officinarum.JPG'),
('Sunflower for fodder','https://commons.wikimedia.org/wiki/Special:FilePath/Helianthus_annuus_-_Field_of_Sunflower.jpg'),
('Sunflower for oil seed','https://commons.wikimedia.org/wiki/Special:FilePath/Helianthus_annuus_field.jpg'),
('Sunhemp','https://commons.wikimedia.org/wiki/Special:FilePath/Crotalaria_juncea.jpg'),
('Swede','https://commons.wikimedia.org/wiki/Special:FilePath/Rutabaga%2C_variety_nadmorska.JPG'),
('Swede for fodder','https://commons.wikimedia.org/wiki/Special:FilePath/Rutabaga%2C_variety_nadmorska.JPG'),
('Sweet corn','https://commons.wikimedia.org/wiki/Special:FilePath/Corn_on_the_cob_(sweet_corn).jpg'),
('Sweet lime','https://commons.wikimedia.org/wiki/Special:FilePath/Sweet_lime.jpg'),
('Sweet pepper','https://commons.wikimedia.org/wiki/Special:FilePath/Red_chilli_plant_bearing_ripe_fruits.jpg'),
('Sweet potato','https://commons.wikimedia.org/wiki/Special:FilePath/Ipomoea_batatas_-_Tubers.jpg'),
('Sweet sorghum','https://commons.wikimedia.org/wiki/Special:FilePath/SorghumBicolorField.jpg'),
('Tallow tree','https://commons.wikimedia.org/wiki/Special:FilePath/TriadicaSebifera12.jpg'),
('Tangerine','https://commons.wikimedia.org/wiki/Special:FilePath/Tangerines_fruit_citrus_reticulata.jpg'),
('Tannia','https://commons.wikimedia.org/wiki/Special:FilePath/Xanthosoma_sagittifolium.jpg'),
('Tapioca (cassava)','https://commons.wikimedia.org/wiki/Special:FilePath/Cassava_(Manihot_esculenta).jpg'),
('Taro','https://commons.wikimedia.org/wiki/Special:FilePath/Taro_(Colocasia_esculenta).jpg'),
('Tea','https://commons.wikimedia.org/wiki/Special:FilePath/Tea_plantation_(Camellia_sinensis)_-_Sh%C5%8Dsei-en_-_Kyoto%2C_Japan_-_DSC06919.jpg'),
('Teff','https://commons.wikimedia.org/wiki/Special:FilePath/Eragrostis_tef_(Teff).jpg'),
('Thymus','https://commons.wikimedia.org/wiki/Special:FilePath/Thymus_vulgaris.jpg'),
('Timothy','https://commons.wikimedia.org/wiki/Special:FilePath/Phleum_pratense_-_timothy.jpg'),
('Tobacco','https://commons.wikimedia.org/wiki/Special:FilePath/Patch_of_Tobacco_(Nicotiana_tabacum_)_in_a_field_in_Intercourse%2C_Pennsylvania..jpg'),
('Tomato','https://commons.wikimedia.org/wiki/Special:FilePath/Ripe_tomato_on_tomato_plant_in_home_garden.jpg'),
('Trefoil','https://commons.wikimedia.org/wiki/Special:FilePath/Lotus_corniculatus_RF.jpg'),
('Triticale','https://commons.wikimedia.org/wiki/Special:FilePath/Triticale_field_Larvik_Norway.jpg'),
('Tung tree','https://commons.wikimedia.org/wiki/Special:FilePath/Tung_Tree_Leaf_and_Berries.jpg'),
('Turmeric','https://commons.wikimedia.org/wiki/Special:FilePath/Turmeric_plants_images.jpg'),
('Turnip, edible','https://commons.wikimedia.org/wiki/Special:FilePath/Turnip_2622027.jpg'),
('Turnip, for fodder','https://commons.wikimedia.org/wiki/Special:FilePath/Turnip_2622027.jpg'),
('Urena (Congo jute)','https://commons.wikimedia.org/wiki/Special:FilePath/Urena_lobata.jpg'),
('Vanilla','https://commons.wikimedia.org/wiki/Special:FilePath/Vanilla_planifolia_cluster_of_green_pods.JPG'),
('Vetches','https://commons.wikimedia.org/wiki/Special:FilePath/Common_Vetch_(Ve%C3%A7a)_(Vicia_sativa)_-_Parc_Natural_de_s%27Albufera%2C_Spain_2022-04-18.jpg'),
('Walnut','https://commons.wikimedia.org/wiki/Special:FilePath/Juglans_regia_Echte_Walnussfrucht_3.jpg'),
('Watermelon','https://commons.wikimedia.org/wiki/Special:FilePath/Watermelon_(Citrullus_lanatus.var._lanatus)_grown_in_Gran_Canaria%2C_Canary_Islands%2C_Spain.jpg'),
('Wheat','https://commons.wikimedia.org/wiki/Special:FilePath/Triticum_aestivum_field%2C_gewone_tarwe_veld.jpg'),
('Yam','https://commons.wikimedia.org/wiki/Special:FilePath/Dioscorea_alata_334682164.jpg'),
('Yautia','https://commons.wikimedia.org/wiki/Special:FilePath/Xanthosoma_sagittifolium_7zz.jpg'),
('Yerba mate','https://commons.wikimedia.org/wiki/Special:FilePath/Misiones_1994_12.jpg')
)
insert into public.orchard_crop_photo_registry
  (crop_name, photo_url, source_page, verification_status, verified_at, notes, updated_at)
select
  crop_name,
  photo_url,
  case
    when photo_url like 'https://commons.wikimedia.org/wiki/Special:FilePath/%'
      then replace(photo_url, 'https://commons.wikimedia.org/wiki/Special:FilePath/', 'https://commons.wikimedia.org/wiki/File:')
    when photo_url like '%unsplash.com%' then 'https://unsplash.com'
    else null
  end,
  'verified',
  now(),
  'FAO WCA crop identity aligned; crop-specific reference photography.',
  now()
from photos
on conflict (crop_name) do update set
  photo_url = excluded.photo_url,
  source_page = excluded.source_page,
  verification_status = excluded.verification_status,
  verified_at = excluded.verified_at,
  notes = excluded.notes,
  updated_at = excluded.updated_at;
