"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { ArrowRight, BookOpen, BookOpenText, CalendarDays, CalendarRange, ChartNoAxesCombined, CheckCircle2, Leaf, Map as MapIcon, Sprout, Target } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { OrchardNavigation } from "@/components/orchard/orchard-navigation"
import { SeasonPulseChart } from "@/components/orchard/orchard-season-graphics"
import { Badge } from "@/components/ui/badge"
import { createBrowserClient } from "@/lib/supabase/client"
import { useLanguage } from "@/lib/hooks/use-language"

type Locale="en"|"es"|"de"
type Plan={id:string;name:string;season:string|null;status:string;start_date:string;end_date:string}
type Cycle={id:string;game_plan_id:string;crop_name:string}
type Succession={id:string;crop_cycle_id:string;planned_sow_date:string;planned_transplant_date:string|null;planned_first_harvest_date:string|null}
type Allocation={crop_succession_id:string}
type Section={href:string;icon:typeof Target;title:Record<Locale,string>;description:Record<Locale,string>;kind:"operate"|"reference"}

const sections:Section[]=[
 {href:"/orchard/game-plan/propagation",icon:Sprout,kind:"operate",title:{en:"Sowing & nursery",es:"Siembra y almácigo",de:"Aussaat & Anzucht"},description:{en:"Direct sow methods, nursery propagation and germination evidence.",es:"Métodos de siembra directa, almácigo y evidencia de germinación.",de:"Direktsaat, Anzucht und Keimungsnachweise."}},
 {href:"/orchard/game-plan/tasks",icon:CalendarDays,kind:"operate",title:{en:"Planned work",es:"Labores planificadas",de:"Geplante Arbeit"},description:{en:"Crop Chart follow-ups converted to accountable tasks only on confirmation.",es:"Labores de Crop Chart que sólo se convierten en tareas responsables al confirmar.",de:"Crop-Chart-Folgearbeiten werden erst nach Bestätigung zu Aufgaben."}},
 {href:"/orchard/game-plan/capacity",icon:MapIcon,kind:"operate",title:{en:"Beds & capacity",es:"Camas y capacidad",de:"Beete & Kapazität"},description:{en:"Verified 8-block physical capacity and simultaneous bed-meter occupancy.",es:"Capacidad física verificada de 8 bloques y ocupación simultánea en bed-m.",de:"Verifizierte 8-Block-Kapazität und gleichzeitige Beetmeterbelegung."}},
 {href:"/orchard/game-plan/forecast",icon:ChartNoAxesCombined,kind:"operate",title:{en:"Production forecast",es:"Forecast de producción",de:"Produktionsprognose"},description:{en:"Harvest-window availability from the physically reconciled plan.",es:"Disponibilidad por ventanas de cosecha del plan físicamente reconciliado.",de:"Erntefenster-Verfügbarkeit aus dem physisch abgeglichenen Plan."}},
 {href:"/orchard/harvest/desk",icon:Leaf,kind:"operate",title:{en:"Harvest desk",es:"Mesa de cosecha",de:"Erntezentrale"},description:{en:"Planned windows and actual output tied to exact succession lineage.",es:"Ventanas planificadas y producción real ligada a la sucesión exacta.",de:"Planfenster und reale Produktion mit exakter Folgen-Lineage."}},
 {href:"/orchard/game-plan/objectives",icon:Target,kind:"reference",title:{en:"Objectives",es:"Objetivos",de:"Ziele"},description:{en:"Mission and annual objectives preserved from Dietrich's planning system.",es:"Misión y objetivos anuales preservados desde el sistema de Dietrich.",de:"Mission und Jahresziele aus Dietrichs Planungssystem."}},
 {href:"/orchard/game-plan/written-plan",icon:BookOpenText,kind:"reference",title:{en:"Written Game Plan",es:"Written Game Plan",de:"Written Game Plan"},description:{en:"Original operating narrative and crop-specific written notes.",es:"Marco operativo original y notas escritas por cultivo.",de:"Originaler Betriebsrahmen und kulturspezifische Notizen."}},
 {href:"/orchard/game-plan/crop-chart",icon:BookOpen,kind:"reference",title:{en:"Crop Chart",es:"Crop Chart",de:"Crop Chart"},description:{en:"Corcovado agronomic standards with bounded Heirloom comparison.",es:"Estándares agronómicos Corcovado con comparación Heirloom acotada.",de:"Corcovado-Anbaustandards mit begrenztem Heirloom-Vergleich."}},
]
const copy={
 en:{eyebrow:"Fundo Corcovado · Game Plan",title:"The season starts with the planting calendar",description:"The operating plan and the reference plan are deliberately separated. Use the physical field plan for execution; keep the full written and agronomic plan available as source context.",season:"Season",fieldCrops:"Field crops",fieldPlantings:"Field plantings",fullCycles:"Full crop cycles",fullSuccessions:"Full successions",primary:"Primary operating view",calendar:"Open planting calendar",calendarHelp:"32 physically reconciled plantings on one continuous timeline.",operate:"Operate the season",reference:"Reference & intent",source:"Canonical execution from Supabase; written and agronomic reference from Dietrich's immutable Black Swan workbooks.",loading:"Loading Game Plan…",empty:"No Game Plan is registered.",reconciled:"Physically reconciled",pulse:"Season pulse",pulseHelp:"Monthly planting activity from the 32 physically reconciled successions. Bars count dated sowing, transplant and first-harvest milestones; they are planning events, not completed work."},
 es:{eyebrow:"Fundo Corcovado · Game Plan",title:"La temporada parte en el calendario de plantación",description:"El plan operativo y el plan de referencia quedan separados a propósito. Para ejecutar usamos el plan físico de campo; el plan completo escrito y agronómico se conserva como contexto fuente.",season:"Temporada",fieldCrops:"Cultivos en campo",fieldPlantings:"Plantaciones en campo",fullCycles:"Ciclos plan completo",fullSuccessions:"Sucesiones plan completo",primary:"Vista operacional principal",calendar:"Abrir calendario de plantación",calendarHelp:"32 plantaciones físicamente reconciliadas en una sola línea temporal.",operate:"Operar la temporada",reference:"Referencia e intención",source:"Ejecución canónica desde Supabase; referencia escrita y agronómica desde los workbooks inmutables de Dietrich.",loading:"Cargando Game Plan…",empty:"No hay Game Plan registrado.",reconciled:"Físicamente reconciliado",pulse:"Pulso de temporada",pulseHelp:"Actividad mensual de las 32 sucesiones físicamente reconciliadas. Las barras cuentan hitos fechados de siembra, trasplante y primera cosecha; son eventos de planificación, no trabajo ejecutado."},
 de:{eyebrow:"Fundo Corcovado · Game Plan",title:"Die Saison beginnt im Pflanzkalender",description:"Betriebsplan und Referenzplan werden bewusst getrennt. Für die Ausführung gilt der physische Feldplan; der vollständige schriftliche und agronomische Plan bleibt als Quellkontext erhalten.",season:"Saison",fieldCrops:"Feldkulturen",fieldPlantings:"Feldpflanzungen",fullCycles:"Vollständige Kulturzyklen",fullSuccessions:"Vollständige Folgen",primary:"Primäre Betriebsansicht",calendar:"Pflanzkalender öffnen",calendarHelp:"32 physisch abgeglichene Pflanzungen auf einer Zeitachse.",operate:"Saison betreiben",reference:"Referenz & Absicht",source:"Kanonische Ausführung aus Supabase; schriftliche und agronomische Referenz aus Dietrichs unveränderlichen Workbooks.",loading:"Game Plan wird geladen…",empty:"Kein Game Plan erfasst.",reconciled:"Physisch abgeglichen",pulse:"Saisonpuls",pulseHelp:"Monatliche Aktivität der 32 physisch abgeglichenen Folgen. Die Balken zählen datierte Aussaat-, Verpflanzungs- und erste Ernteereignisse; sie sind Planungsereignisse, keine ausgeführte Arbeit."},
} as const

function monthKey(value:string){return value.slice(0,7)}
function monthKeys(start:string,end:string){const out:string[]=[];const d=new Date(`${start.slice(0,7)}-01T12:00:00`);const last=new Date(`${end.slice(0,7)}-01T12:00:00`);while(d<=last&&out.length<18){out.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`);d.setMonth(d.getMonth()+1)}return out}

export default function DietrichGamePlanOverview(){
 const supabase=useMemo(()=>createBrowserClient(),[]);const {language}=useLanguage();const lang:Locale=language;const text=copy[lang]
 const [plans,setPlans]=useState<Plan[]>([]),[cycles,setCycles]=useState<Cycle[]>([]),[successions,setSuccessions]=useState<Succession[]>([]),[allocations,setAllocations]=useState<Allocation[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 useEffect(()=>{let live=true;setLoading(true);setError(null);void Promise.all([
  supabase.from("orchard_game_plans").select("id,name,season,status,start_date,end_date").order("start_date",{ascending:false}),
  supabase.from("orchard_crop_cycles").select("id,game_plan_id,crop_name"),
  supabase.from("orchard_crop_successions").select("id,crop_cycle_id,planned_sow_date,planned_transplant_date,planned_first_harvest_date"),
  supabase.from("orchard_bed_allocations").select("crop_succession_id"),
 ]).then(([p,c,s,a])=>{if(!live)return;const first=p.error??c.error??s.error??a.error;if(first){setError(first.message);setLoading(false);return}setPlans((p.data??[]) as Plan[]);setCycles((c.data??[]) as Cycle[]);setSuccessions((s.data??[]) as Succession[]);setAllocations((a.data??[]) as Allocation[]);setLoading(false)});return()=>{live=false}},[supabase])
 const requested=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("game_plan"):null
 const plan=plans.find(p=>p.id===requested)??plans.find(p=>p.status==="active")??plans.find(p=>p.status==="draft")??plans[0]??null
 const scopedCycles=plan?cycles.filter(c=>c.game_plan_id===plan.id):[];const cycleById=new globalThis.Map(scopedCycles.map(c=>[c.id,c]));const scopedSuccessions=successions.filter(s=>cycleById.has(s.crop_cycle_id));const allocatedIds=new Set(allocations.map(a=>a.crop_succession_id));const fieldSuccessions=scopedSuccessions.filter(s=>allocatedIds.has(s.id));const fieldCycleIds=new Set(fieldSuccessions.map(s=>s.crop_cycle_id));const fieldCropNames=new Set([...fieldCycleIds].map(id=>cycleById.get(id)?.crop_name).filter(Boolean))
 const href=(path:string)=>`/${language}${path}${plan?`?game_plan=${encodeURIComponent(plan.id)}`:""}`
 const operational=sections.filter(s=>s.kind==="operate"),reference=sections.filter(s=>s.kind==="reference")
 const locale=lang==="es"?"es-CL":lang==="de"?"de-DE":"en-US"
 const pulseData=plan?monthKeys(plan.start_date,plan.end_date).map(key=>({label:new Date(`${key}-01T12:00:00`).toLocaleDateString(locale,{month:"short"}),sow:fieldSuccessions.filter(s=>monthKey(s.planned_sow_date)===key).length,transplant:fieldSuccessions.filter(s=>s.planned_transplant_date&&monthKey(s.planned_transplant_date)===key).length,harvest:fieldSuccessions.filter(s=>s.planned_first_harvest_date&&monthKey(s.planned_first_harvest_date)===key).length})):[]
 return <AppLayout><OrchardNavigation/><main className="mx-auto w-full max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8">
  <header className="mb-7 max-w-4xl"><p className="mb-3 text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">{text.eyebrow}</p><h1 className="text-3xl font-normal sm:text-4xl">{text.title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground sm:text-base">{text.description}</p></header>
  {loading?<div className="py-12 text-sm text-muted-foreground">{text.loading}</div>:error?<div className="border border-red-300 bg-red-50 p-4 text-sm text-red-800">{error}</div>:!plan?<div className="py-12 text-sm text-muted-foreground">{text.empty}</div>:<>
   <section className="mb-6 grid gap-px bg-[var(--bs-divider-subtle)] sm:grid-cols-2 xl:grid-cols-5"><Metric label={text.season} value={plan.season??plan.name}/><Metric label={text.fieldCrops} value={String(fieldCropNames.size)}/><Metric label={text.fieldPlantings} value={String(fieldSuccessions.length)}/><Metric label={text.fullCycles} value={String(scopedCycles.length)}/><Metric label={text.fullSuccessions} value={String(scopedSuccessions.length)}/></section>
   <section className="mb-6 border border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)] p-5 sm:p-6"><div className="mb-2"><h2 className="text-xl font-normal">{text.pulse}</h2><p className="mt-1 max-w-4xl text-xs leading-5 text-muted-foreground">{text.pulseHelp}</p></div><SeasonPulseChart data={pulseData} language={lang}/></section>
   <Link href={href("/orchard/game-plan/season")} className="group mb-8 grid min-h-40 border border-[var(--orchard-green)] bg-[var(--orchard-green-soft)] p-6 md:grid-cols-[1fr_auto] md:items-end"><div><div className="flex items-center gap-2 text-xs font-medium uppercase tracking-[.14em] text-[var(--orchard-green)]"><CheckCircle2 className="h-4 w-4"/>{text.primary} · {text.reconciled}</div><h2 className="mt-4 text-3xl font-normal">{text.calendar}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{text.calendarHelp}</p></div><ArrowRight className="mt-5 h-5 w-5 text-[var(--orchard-green)] transition-transform group-hover:translate-x-1 md:mt-0"/></Link>
   <section className="grid gap-8 lg:grid-cols-2"><SectionList title={text.operate} sections={operational} lang={lang} href={href}/><SectionList title={text.reference} sections={reference} lang={lang} href={href}/></section>
   <p className="mt-7 border-t border-[var(--bs-divider-subtle)] pt-5 text-xs leading-5 text-muted-foreground">{text.source}</p>
  </>}
 </main></AppLayout>
}
function Metric({label,value}:{label:string;value:string}){return <div className="bg-[var(--bs-surface-primary)] p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl tabular-nums">{value}</p></div>}
function SectionList({title,sections,lang,href}:{title:string;sections:Section[];lang:Locale;href:(path:string)=>string}){return <div><h2 className="mb-3 text-xl font-normal">{title}</h2><div className="border border-[var(--bs-divider-subtle)] bg-[var(--bs-surface-primary)]">{sections.map(section=>{const Icon=section.icon;return <Link key={section.href} href={href(section.href)} className="group grid grid-cols-[32px_1fr_24px] gap-3 border-b border-[var(--bs-divider-subtle)] p-4 last:border-b-0 hover:bg-[var(--bs-surface-secondary)]"><Icon className="mt-0.5 h-4 w-4 text-muted-foreground"/><div><strong className="font-medium">{section.title[lang]}</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">{section.description[lang]}</p></div><ArrowRight className="mt-1 h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1"/></Link>})}</div></div>}
