"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { AlertTriangle, RefreshCw } from "lucide-react"
import { AppLayout } from "@/components/app-layout"
import { PageHeader } from "@/components/page-header"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { createBrowserClient } from "@/lib/supabase/client"
import { BusinessPlanUpload } from "@/components/cattle/business-plan-upload"
import { useLanguage } from "@/lib/hooks/use-language"

type PricingData={id:string;animal_type:string;price_pesos:number;unit:string;category:string;description:string|null;quantity_standard:number|null}
type CostData={id:string;cost_type:string;amount_pesos:number;unit:string;description:string|null;business_unit:string;is_fixed:boolean}
type BusinessPlanRecord={id:string;year:number;month:string;inventory_count:number;purchase_amount:number;sales_amount:number;operational_cost:number;profit_loss:number;business_unit:string}
const COPY={
 en:{title:"Cattle · costs and scenarios",description:"Price assumptions, operating costs and projections loaded for Fundo Corcovado's cattle unit.",warningTitle:"Financial scenario, not executed accounting",warning:"Records in this section are assumptions and projections. They must not be interpreted as purchases, sales, costs or profit actually realized.",questionable:(n:number)=>`${n} prices use “per animal” with a value below CLP 10,000.`,questionableDesc:"Some may correspond to price per kilogram or another inherited unit. They remain unchanged until administrative validation.",loadError:"The information could not be loaded.",retry:"Retry",period:"Projected period",noData:"No data",loaded:"records loaded",purchases:"Projected purchases",sales:"Projected sales",costs:"Projected costs",result:"Projected result",resultDetail:"Sum of the profit_loss field",breeding:"Breeding prices",fattening:"Fattening prices",operating:"Recorded operating costs",operatingDesc:"Reference amounts; frequency and unit are shown exactly as stored.",concept:"Concept",unitBusiness:"Cattle unit",type:"Type",unit:"Unit",value:"Recorded value",loadingCosts:"Loading costs…",noCosts:"No costs recorded.",general:"General",fixed:"Fixed",variable:"Variable",scenario:"Loaded scenario detail",scenarioDesc:"First 20 records ordered by year and month. Amounts are expressed as CLP under the current schema.",periodCol:"Period",inventory:"Inventory",loadingScenario:"Loading scenario…",noScenario:"No projections loaded.",animalType:"Type",price:"Recorded price",noPrices:"No prices recorded.",unitLabels:{unit:"per animal",kg:"per kilogram",year:"per year","one-time":"one-time",percent:"percentage"}},
 es:{title:"Ganadería · costos y escenarios",description:"Supuestos de precios, costos operacionales y proyecciones cargadas para la unidad ganadera de Fundo Corcovado.",warningTitle:"Escenario financiero, no contabilidad ejecutada",warning:"Los registros de esta sección son supuestos y proyecciones. No deben interpretarse como compras, ventas, costos o utilidades efectivamente realizadas.",questionable:(n:number)=>`Hay ${n} precios con unidad “por animal” y valor inferior a CLP 10.000.`,questionableDesc:"Es probable que algunos correspondan a precio por kilogramo o a otra unidad heredada. Se mantienen sin modificación hasta validación administrativa.",loadError:"No fue posible cargar la información.",retry:"Reintentar",period:"Período proyectado",noData:"Sin datos",loaded:"registros cargados",purchases:"Compras proyectadas",sales:"Ventas proyectadas",costs:"Costos proyectados",result:"Resultado proyectado",resultDetail:"Suma del campo profit_loss",breeding:"Precios de crianza",fattening:"Precios de engorda",operating:"Costos operacionales registrados",operatingDesc:"Montos de referencia; la periodicidad y unidad se muestran exactamente según el registro.",concept:"Concepto",unitBusiness:"Unidad ganadera",type:"Tipo",unit:"Unidad",value:"Valor registrado",loadingCosts:"Cargando costos…",noCosts:"No hay costos registrados.",general:"General",fixed:"Fijo",variable:"Variable",scenario:"Detalle del escenario cargado",scenarioDesc:"Primeros 20 registros ordenados por año y mes. Los montos están expresados como CLP según el esquema actual.",periodCol:"Período",inventory:"Inventario",loadingScenario:"Cargando escenario…",noScenario:"No hay proyecciones cargadas.",animalType:"Tipo",price:"Precio registrado",noPrices:"Sin precios registrados.",unitLabels:{unit:"por animal",kg:"por kilogramo",year:"por año","one-time":"pago único",percent:"porcentaje"}},
 de:{title:"Rinderhaltung · Kosten und Szenarien",description:"Preisannahmen, Betriebskosten und geladene Projektionen für die Rindereinheit von Fundo Corcovado.",warningTitle:"Finanzszenario, keine ausgeführte Buchhaltung",warning:"Die Datensätze in diesem Bereich sind Annahmen und Projektionen. Sie dürfen nicht als tatsächlich realisierte Käufe, Verkäufe, Kosten oder Gewinne interpretiert werden.",questionable:(n:number)=>`${n} Preise verwenden „pro Tier“ mit einem Wert unter CLP 10.000.`,questionableDesc:"Einige könnten Preise pro Kilogramm oder eine andere übernommene Einheit darstellen. Sie bleiben bis zur administrativen Validierung unverändert.",loadError:"Die Informationen konnten nicht geladen werden.",retry:"Erneut versuchen",period:"Projizierter Zeitraum",noData:"Keine Daten",loaded:"Datensätze geladen",purchases:"Projizierte Käufe",sales:"Projizierte Verkäufe",costs:"Projizierte Kosten",result:"Projiziertes Ergebnis",resultDetail:"Summe des Feldes profit_loss",breeding:"Zuchtpreise",fattening:"Mastpreise",operating:"Erfasste Betriebskosten",operatingDesc:"Referenzbeträge; Periodizität und Einheit werden genau wie gespeichert angezeigt.",concept:"Posten",unitBusiness:"Rindereinheit",type:"Typ",unit:"Einheit",value:"Erfasster Wert",loadingCosts:"Kosten werden geladen…",noCosts:"Keine Kosten erfasst.",general:"Allgemein",fixed:"Fix",variable:"Variabel",scenario:"Detail des geladenen Szenarios",scenarioDesc:"Erste 20 Datensätze nach Jahr und Monat. Beträge sind im aktuellen Schema in CLP angegeben.",periodCol:"Zeitraum",inventory:"Bestand",loadingScenario:"Szenario wird geladen…",noScenario:"Keine Projektionen geladen.",animalType:"Typ",price:"Erfasster Preis",noPrices:"Keine Preise erfasst.",unitLabels:{unit:"pro Tier",kg:"pro Kilogramm",year:"pro Jahr","one-time":"einmalig",percent:"Prozent"}},
} as const

export default function PricingCostsPage(){
 const{language}=useLanguage();const lang=(language in COPY?language:"en") as keyof typeof COPY;const c=COPY[lang];const locale=lang==="es"?"es-CL":lang==="de"?"de-DE":"en-US";const clp=useMemo(()=>new Intl.NumberFormat(locale,{style:"currency",currency:"CLP",maximumFractionDigits:0}),[locale]);const number=useMemo(()=>new Intl.NumberFormat(locale,{maximumFractionDigits:2}),[locale]);const supabase=useMemo(()=>createBrowserClient(),[]);const[pricing,setPricing]=useState<PricingData[]>([]);const[costs,setCosts]=useState<CostData[]>([]);const[plan,setPlan]=useState<BusinessPlanRecord[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState(false)
 const fetchData=useCallback(async()=>{setLoading(true);setError(false);const[pricingRes,costsRes,planRes]=await Promise.all([supabase.from("cattle_pricing").select("id, animal_type, price_pesos, unit, category, description, quantity_standard").eq("is_active",true).order("category").order("animal_type"),supabase.from("cattle_operational_costs").select("id, cost_type, amount_pesos, unit, description, business_unit, is_fixed").order("business_unit").order("cost_type"),supabase.from("cattle_business_plan").select("id, year, month, inventory_count, purchase_amount, sales_amount, operational_cost, profit_loss, business_unit").order("year").order("month")]);const loadError=pricingRes.error||costsRes.error||planRes.error;if(loadError){console.error("CATTLE_PRICING_LOAD_FAILED",loadError);setError(true);setPricing([]);setCosts([]);setPlan([])}else{setPricing((pricingRes.data??[]) as PricingData[]);setCosts((costsRes.data??[]) as CostData[]);setPlan((planRes.data??[]) as BusinessPlanRecord[])}setLoading(false)},[supabase]);useEffect(()=>{void fetchData()},[fetchData])
 const summary=useMemo(()=>({firstYear:plan.length?Math.min(...plan.map(i=>i.year)):null,lastYear:plan.length?Math.max(...plan.map(i=>i.year)):null,purchases:plan.reduce((s,i)=>s+Number(i.purchase_amount??0),0),sales:plan.reduce((s,i)=>s+Number(i.sales_amount??0),0),costs:plan.reduce((s,i)=>s+Number(i.operational_cost??0),0),result:plan.reduce((s,i)=>s+Number(i.profit_loss??0),0)}),[plan]);const questionablePrices=pricing.filter(i=>i.unit==="unit"&&Number(i.price_pesos)<10000).length;const breeding=pricing.filter(i=>i.category==="Breeding");const fattening=pricing.filter(i=>i.category==="Fattening");const unitLabel=(u:string)=>(c.unitLabels as Record<string,string>)[u]??u
 return <AppLayout><PageHeader title={c.title} description={c.description}/><div className="space-y-6 p-4 sm:p-8"><Card className="border-amber-300"><CardContent className="flex gap-3 p-5"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600"/><div><p className="font-medium">{c.warningTitle}</p><p className="mt-1 text-sm text-muted-foreground">{c.warning}</p></div></CardContent></Card>
 {questionablePrices>0&&<Card className="border-amber-300"><CardContent className="p-5 text-sm"><p className="font-medium">{c.questionable(questionablePrices)}</p><p className="mt-1 text-muted-foreground">{c.questionableDesc}</p></CardContent></Card>}{error&&<Card className="border-destructive/60"><CardContent className="flex items-center justify-between gap-4 p-5"><p className="text-sm text-destructive">{c.loadError}</p><Button variant="outline" size="sm" onClick={()=>void fetchData()}><RefreshCw className="mr-2 h-4 w-4"/>{c.retry}</Button></CardContent></Card>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric title={c.period} value={summary.firstYear&&summary.lastYear?`${summary.firstYear}–${summary.lastYear}`:c.noData} detail={`${plan.length} ${c.loaded}`}/><Metric title={c.purchases} value={clp.format(summary.purchases)}/><Metric title={c.sales} value={clp.format(summary.sales)}/><Metric title={c.costs} value={clp.format(summary.costs)}/><Metric title={c.result} value={clp.format(summary.result)} detail={c.resultDetail}/></div>
 <BusinessPlanUpload onDataLoaded={()=>void fetchData()}/><div className="grid gap-6 xl:grid-cols-2"><PricingTable title={c.breeding} records={breeding} c={c} clp={clp} unitLabel={unitLabel}/><PricingTable title={c.fattening} records={fattening} c={c} clp={clp} unitLabel={unitLabel}/></div>
 <Card><CardHeader><CardTitle>{c.operating}</CardTitle><CardDescription>{c.operatingDesc}</CardDescription></CardHeader><CardContent><div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>{c.concept}</TableHead><TableHead>{c.unitBusiness}</TableHead><TableHead>{c.type}</TableHead><TableHead>{c.unit}</TableHead><TableHead className="text-right">{c.value}</TableHead></TableRow></TableHeader><TableBody>{loading?<TableRow><TableCell colSpan={5} className="py-8 text-center text-muted-foreground">{c.loadingCosts}</TableCell></TableRow>:costs.length===0?<TableRow><TableCell colSpan={5} className="py-8 text-center text-muted-foreground">{c.noCosts}</TableCell></TableRow>:costs.map(item=><TableRow key={item.id}><TableCell><p className="font-medium">{item.cost_type}</p>{item.description&&<p className="mt-1 text-xs text-muted-foreground">{item.description}</p>}</TableCell><TableCell>{item.business_unit||c.general}</TableCell><TableCell><Badge variant="outline">{item.is_fixed?c.fixed:c.variable}</Badge></TableCell><TableCell>{unitLabel(item.unit)}</TableCell><TableCell className="text-right font-medium">{item.unit==="percent"?`${number.format(item.amount_pesos)}%`:clp.format(item.amount_pesos)}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
 <Card><CardHeader><CardTitle>{c.scenario}</CardTitle><CardDescription>{c.scenarioDesc}</CardDescription></CardHeader><CardContent><div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>{c.unitBusiness}</TableHead><TableHead>{c.periodCol}</TableHead><TableHead className="text-right">{c.inventory}</TableHead><TableHead className="text-right">{c.purchases}</TableHead><TableHead className="text-right">{c.sales}</TableHead><TableHead className="text-right">{c.costs}</TableHead><TableHead className="text-right">{c.result}</TableHead></TableRow></TableHeader><TableBody>{loading?<TableRow><TableCell colSpan={7} className="py-8 text-center text-muted-foreground">{c.loadingScenario}</TableCell></TableRow>:plan.length===0?<TableRow><TableCell colSpan={7} className="py-8 text-center text-muted-foreground">{c.noScenario}</TableCell></TableRow>:plan.slice(0,20).map(item=><TableRow key={item.id}><TableCell><Badge variant="outline">{item.business_unit}</Badge></TableCell><TableCell>{item.year}-{item.month}</TableCell><TableCell className="text-right">{number.format(item.inventory_count??0)}</TableCell><TableCell className="text-right">{clp.format(item.purchase_amount??0)}</TableCell><TableCell className="text-right">{clp.format(item.sales_amount??0)}</TableCell><TableCell className="text-right">{clp.format(item.operational_cost??0)}</TableCell><TableCell className="text-right font-medium">{clp.format(item.profit_loss??0)}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card></div></AppLayout>
}
function PricingTable({title,records,c,clp,unitLabel}:{title:string;records:PricingData[];c:any;clp:Intl.NumberFormat;unitLabel:(v:string)=>string}){return <Card><CardHeader><CardTitle className="flex items-center justify-between text-base"><span>{title}</span><Badge variant="outline">{records.length}</Badge></CardTitle></CardHeader><CardContent><div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>{c.animalType}</TableHead><TableHead>{c.unit}</TableHead><TableHead className="text-right">{c.price}</TableHead></TableRow></TableHeader><TableBody>{records.length===0?<TableRow><TableCell colSpan={3} className="py-8 text-center text-muted-foreground">{c.noPrices}</TableCell></TableRow>:records.map(item=><TableRow key={item.id}><TableCell><p className="font-medium">{item.animal_type}</p>{item.description&&<p className="mt-1 text-xs text-muted-foreground">{item.description}</p>}</TableCell><TableCell>{unitLabel(item.unit)}</TableCell><TableCell className="text-right font-medium">{clp.format(item.price_pesos)}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>}
function Metric({title,value,detail}:{title:string;value:string;detail?:string}){return <Card><CardHeader className="pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">{title}</CardTitle></CardHeader><CardContent><div className="text-2xl font-semibold tracking-tight">{value}</div>{detail&&<p className="mt-1 text-xs text-muted-foreground">{detail}</p>}</CardContent></Card>}
