'use client'

import React, { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Droplet, Heart, Plus, Zap } from 'lucide-react'
import { AppLayout } from '@/components/app-layout'
import { HealthInsightsPanel } from '@/components/cattle/health-insights-panel'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { createBrowserClient } from '@/lib/supabase/client'
import { useLanguage } from '@/lib/hooks/use-language'

type BiometricRecord={id:string;animal_id:string;test_date:string;bhb:number|null;total_protein:number|null;magnesium:number|null;calcium:number|null;glucose:number|null}
type CattleAnimal={id:string;animal_id:string;name:string;breed:string;status:string}
const COPY={
 en:{title:"Cattle health monitoring",description:"Biometric records and internal risk indicators for animal welfare. Indicators are not diagnoses and require veterinary interpretation.",register:"Record analysis",animals:"Animals",recent:"Recent analyses",withAlerts:"With indicators",critical:"Critical indicators",criticalMessage:(n:number)=>`${n} critical indicators require prompt veterinary review. Review the records below.`,all:"All animals",latest:"Latest biochemical analyses",latestDesc:"Health parameters and internal risk indicators",empty:"No biochemical analysis records",emptyHelp:"Record the first analysis to start building the history.",first:"Record first analysis",date:"Date",protein:"Protein",magnesium:"Magnesium",glucose:"Glucose",criticalLabel:"critical",high:"high",medium:"medium",ketosis:"Elevated BHB / fat-mobilization indicator",lowProtein:"Low total-protein indicator",lowMagnesium:"Low magnesium indicator",abnormalGlucose:"Glucose outside configured range",guidance:"Operational mitigation guidance",guidanceDesc:"Reference guidance for Valdivia conditions; validate with the responsible veterinarian before applying changes.",guides:["Winter feed quality: review forage availability and supplementation before the highest-demand period.","Mineralization: verify magnesium and mineral supplementation against the veterinary plan.","Early monitoring: schedule periodic blood sampling according to the veterinary protocol.","Seasonal planning: align forage reserves and supplementation with pasture availability.","Infection prevention: maintain nutrition, housing, ventilation and isolation protocols for symptomatic animals."],dialog:"Record biochemical analysis",dialogDesc:"Enter parameters from the veterinary analysis.",animal:"Animal",noAnimals:"No animals are registered. Create animals in the cattle module first.",select:"Select an animal",unnamed:"Unnamed",testDate:"Analysis date",totalProtein:"Total protein (g/L)",calcium:"Calcium (mmol/L)",notes:"Notes",notesPlaceholder:"Additional observations…",cancel:"Cancel",saving:"Saving…",save:"Save analysis",selectError:"Select an animal.",saveError:"The analysis could not be saved."},
 es:{title:"Monitoreo de salud ganadera",description:"Registros biométricos e indicadores internos de riesgo para bienestar animal. Los indicadores no son diagnósticos y requieren interpretación veterinaria.",register:"Registrar análisis",animals:"Animales",recent:"Análisis recientes",withAlerts:"Con indicadores",critical:"Indicadores críticos",criticalMessage:(n:number)=>`Hay ${n} indicadores críticos que requieren revisión veterinaria oportuna. Revisa los registros abajo.`,all:"Todos los animales",latest:"Últimos análisis bioquímicos",latestDesc:"Parámetros de salud e indicadores internos de riesgo",empty:"Sin registros de análisis bioquímicos",emptyHelp:"Registra el primer análisis para comenzar a construir el historial.",first:"Registrar primer análisis",date:"Fecha",protein:"Proteína",magnesium:"Magnesio",glucose:"Glucosa",criticalLabel:"crítico",high:"alto",medium:"medio",ketosis:"BHB elevado / indicador de movilización de grasa",lowProtein:"Indicador de proteína total baja",lowMagnesium:"Indicador de magnesio bajo",abnormalGlucose:"Glucosa fuera del rango configurado",guidance:"Guía operativa de mitigación",guidanceDesc:"Guía de referencia para condiciones de Valdivia; valida con el veterinario responsable antes de aplicar cambios.",guides:["Alimentación invernal: revisar disponibilidad de forraje y suplementación antes del período de mayor demanda.","Mineralización: verificar suplementación de magnesio y minerales contra el plan veterinario.","Monitoreo temprano: programar muestreos de sangre periódicos según protocolo veterinario.","Planificación estacional: alinear reservas de forraje y suplementación con disponibilidad de pradera.","Prevención de infecciones: mantener protocolos de nutrición, alojamiento, ventilación y aislamiento de animales sintomáticos."],dialog:"Registrar análisis bioquímico",dialogDesc:"Ingresa los parámetros informados por el análisis veterinario.",animal:"Animal",noAnimals:"No hay animales registrados. Crea animales en el módulo de ganado primero.",select:"Selecciona un animal",unnamed:"Sin nombre",testDate:"Fecha del análisis",totalProtein:"Proteína total (g/L)",calcium:"Calcio (mmol/L)",notes:"Notas",notesPlaceholder:"Observaciones adicionales…",cancel:"Cancelar",saving:"Guardando…",save:"Guardar análisis",selectError:"Selecciona un animal.",saveError:"No fue posible guardar el análisis."},
 de:{title:"Gesundheitsmonitoring Rinder",description:"Biometrische Datensätze und interne Risikoindikatoren für das Tierwohl. Die Indikatoren sind keine Diagnosen und benötigen tierärztliche Interpretation.",register:"Analyse erfassen",animals:"Tiere",recent:"Aktuelle Analysen",withAlerts:"Mit Indikatoren",critical:"Kritische Indikatoren",criticalMessage:(n:number)=>`${n} kritische Indikatoren erfordern eine zeitnahe tierärztliche Prüfung. Prüfe die Datensätze unten.`,all:"Alle Tiere",latest:"Letzte biochemische Analysen",latestDesc:"Gesundheitsparameter und interne Risikoindikatoren",empty:"Keine biochemischen Analysen erfasst",emptyHelp:"Erfasse die erste Analyse, um den Verlauf aufzubauen.",first:"Erste Analyse erfassen",date:"Datum",protein:"Protein",magnesium:"Magnesium",glucose:"Glukose",criticalLabel:"kritisch",high:"hoch",medium:"mittel",ketosis:"Erhöhter BHB / Indikator für Fettmobilisierung",lowProtein:"Indikator für niedriges Gesamtprotein",lowMagnesium:"Indikator für niedriges Magnesium",abnormalGlucose:"Glukose außerhalb des konfigurierten Bereichs",guidance:"Operative Minderungsleitlinie",guidanceDesc:"Referenzleitlinie für Bedingungen in Valdivia; Änderungen vor Umsetzung mit dem verantwortlichen Tierarzt validieren.",guides:["Winterfütterung: Futterverfügbarkeit und Ergänzung vor der höchsten Bedarfsphase prüfen.","Mineralversorgung: Magnesium- und Mineralergänzung mit dem tierärztlichen Plan abgleichen.","Frühes Monitoring: regelmäßige Blutproben gemäß tierärztlichem Protokoll planen.","Saisonplanung: Futterreserven und Ergänzung an die Weideverfügbarkeit anpassen.","Infektionsprävention: Protokolle für Ernährung, Haltung, Lüftung und Isolation symptomatischer Tiere einhalten."],dialog:"Biochemische Analyse erfassen",dialogDesc:"Parameter aus der tierärztlichen Analyse eingeben.",animal:"Tier",noAnimals:"Keine Tiere erfasst. Lege zuerst Tiere im Rindermodul an.",select:"Tier auswählen",unnamed:"Ohne Namen",testDate:"Analysedatum",totalProtein:"Gesamtprotein (g/L)",calcium:"Kalzium (mmol/L)",notes:"Notizen",notesPlaceholder:"Zusätzliche Beobachtungen…",cancel:"Abbrechen",saving:"Speichern…",save:"Analyse speichern",selectError:"Wähle ein Tier aus.",saveError:"Die Analyse konnte nicht gespeichert werden."},
} as const

export default function CattleHealthPage(){
 const{language}=useLanguage();const lang=(language in COPY?language:"en") as keyof typeof COPY;const c=COPY[lang];const locale=lang==="es"?"es-CL":lang==="de"?"de-DE":"en-US";const number=useMemo(()=>new Intl.NumberFormat(locale,{maximumFractionDigits:2}),[locale]);const dateFmt=useMemo(()=>new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeZone:"America/Santiago"}),[locale]);const supabase=useMemo(()=>createBrowserClient(),[]);const[animals,setAnimals]=useState<CattleAnimal[]>([]);const[records,setRecords]=useState<BiometricRecord[]>([]);const[loading,setLoading]=useState(true);const[selectedAnimal,setSelectedAnimal]=useState('all');const[showDialog,setShowDialog]=useState(false);const[formLoading,setFormLoading]=useState(false);const[formError,setFormError]=useState('');const[formData,setFormData]=useState({animal_id:'',test_date:new Date().toISOString().split('T')[0],bhb:'',total_protein:'',magnesium:'',calcium:'',glucose:'',notes:''})
 const loadData=async()=>{setLoading(true);try{const[animalsRes,recordsRes]=await Promise.all([supabase.from('cattle_animals').select('id, animal_id, name, breed, status').order('animal_id',{ascending:true}),supabase.from('cattle_biometric_records').select('*').order('test_date',{ascending:false}).limit(100)]);if(animalsRes.error||recordsRes.error)throw animalsRes.error||recordsRes.error;setAnimals((animalsRes.data??[]) as CattleAnimal[]);setRecords((recordsRes.data??[]) as BiometricRecord[])}catch(error){console.error('CATTLE_HEALTH_LOAD_FAILED',error);setAnimals([]);setRecords([])}finally{setLoading(false)}};useEffect(()=>{void loadData()},[])
 const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setFormError('');setFormLoading(true);try{if(!formData.animal_id){setFormError(c.selectError);return}const{error}=await supabase.from('cattle_biometric_records').insert({animal_id:formData.animal_id,test_date:formData.test_date,bhb:formData.bhb?parseFloat(formData.bhb):null,total_protein:formData.total_protein?parseFloat(formData.total_protein):null,magnesium:formData.magnesium?parseFloat(formData.magnesium):null,calcium:formData.calcium?parseFloat(formData.calcium):null,glucose:formData.glucose?parseFloat(formData.glucose):null,notes:formData.notes||null});if(error)throw error;setFormData({animal_id:'',test_date:new Date().toISOString().split('T')[0],bhb:'',total_protein:'',magnesium:'',calcium:'',glucose:'',notes:''});setShowDialog(false);await loadData()}catch(err){console.error('CATTLE_HEALTH_SAVE_FAILED',err);setFormError(c.saveError)}finally{setFormLoading(false)}}
 const filtered=selectedAnimal==='all'?records:records.filter(r=>animals.find(a=>a.id===r.animal_id)?.animal_id===selectedAnimal)
 const detectAlerts=(record:BiometricRecord)=>{const alerts:Array<{type:string;severity:'critical'|'high'|'medium';value:string}>=[];if(record.bhb&&record.bhb>0.6)alerts.push({type:c.ketosis,severity:record.bhb>1?'critical':'high',value:number.format(record.bhb)});if(record.total_protein&&record.total_protein<65)alerts.push({type:c.lowProtein,severity:record.total_protein<55?'critical':'high',value:number.format(record.total_protein)});if(record.magnesium&&record.magnesium<0.8)alerts.push({type:c.lowMagnesium,severity:record.magnesium<0.5?'critical':'medium',value:number.format(record.magnesium)});if(record.glucose&&(record.glucose<40||record.glucose>100))alerts.push({type:c.abnormalGlucose,severity:record.glucose<30?'critical':'medium',value:number.format(record.glucose)});return alerts}
 const stats={totalAnimals:animals.length,recentRecords:records.length,animalsWithAlerts:records.filter(r=>detectAlerts(r).length>0).length,criticalAlerts:records.reduce((sum,r)=>sum+detectAlerts(r).filter(a=>a.severity==='critical').length,0)}
 if(loading)return <AppLayout><div className="space-y-4"><div className="h-10 animate-pulse rounded bg-muted"/><div className="h-20 animate-pulse rounded bg-muted"/></div></AppLayout>
 return <AppLayout><div className="space-y-6"><div className="flex items-center justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight text-foreground">{c.title}</h1><p className="mt-1 text-muted-foreground">{c.description}</p></div><Button size="lg" className="gap-2" onClick={()=>setShowDialog(true)}><Plus className="h-4 w-4"/>{c.register}</Button></div>
 <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<Heart className="h-4 w-4"/>} label={c.animals} value={stats.totalAnimals}/><Stat icon={<Droplet className="h-4 w-4"/>} label={c.recent} value={stats.recentRecords}/><Stat icon={<AlertTriangle className="h-4 w-4"/>} label={c.withAlerts} value={stats.animalsWithAlerts}/><Stat icon={<Zap className="h-4 w-4"/>} label={c.critical} value={stats.criticalAlerts}/></div>
 {stats.criticalAlerts>0&&<Alert><AlertTriangle className="h-4 w-4"/><AlertDescription>{c.criticalMessage(stats.criticalAlerts)}</AlertDescription></Alert>}
 <HealthInsightsPanel/><div className="flex gap-2"><select value={selectedAnimal} onChange={e=>setSelectedAnimal(e.target.value)} className="rounded-md border border-border bg-input px-3 py-2 text-sm"><option value="all">{c.all}</option>{animals.map(a=><option key={a.id} value={a.animal_id}>{a.name||a.animal_id} ({a.breed})</option>)}</select></div>
 <Card><CardHeader><CardTitle>{c.latest}</CardTitle><CardDescription>{c.latestDesc}</CardDescription></CardHeader><CardContent>{filtered.length===0?<div className="py-12 text-center"><p className="mb-4 text-muted-foreground">{c.empty}</p><p className="mb-4 text-sm text-muted-foreground">{c.emptyHelp}</p><Button size="sm" onClick={()=>setShowDialog(true)}>{c.first}</Button></div>:<div className="space-y-4">{filtered.slice(0,20).map(record=>{const animal=animals.find(a=>a.id===record.animal_id);const alerts=detectAlerts(record);return <div key={record.id} className="space-y-3 rounded-lg border p-4 transition-colors hover:bg-accent/5"><div className="flex items-start justify-between"><div><p className="font-semibold text-foreground">{animal?.name||animal?.animal_id||record.animal_id}</p><p className="text-sm text-muted-foreground">{c.date}: {dateFmt.format(new Date(`${record.test_date}T12:00:00-04:00`))}</p></div>{alerts.length>0&&<div className="flex gap-1">{alerts.map((a,i)=><Badge key={i} variant={a.severity==='critical'?'destructive':'outline'}>{a.severity==='critical'?c.criticalLabel:a.severity==='high'?c.high:c.medium}</Badge>)}</div>}</div><div className="grid grid-cols-2 gap-2 text-sm sm:grid-cols-4">{record.bhb!==null&&<Param label="BHB" value={`${number.format(record.bhb)} mmol/L`}/>} {record.total_protein!==null&&<Param label={c.protein} value={`${number.format(record.total_protein)} g/L`}/>} {record.magnesium!==null&&<Param label={c.magnesium} value={`${number.format(record.magnesium)} mmol/L`}/>} {record.glucose!==null&&<Param label={c.glucose} value={`${number.format(record.glucose)} mg/dL`}/>}</div>{alerts.length>0&&<div className="space-y-1 rounded border p-2">{alerts.map((alert,i)=><p key={i} className="text-sm">{alert.type}: {alert.value}</p>)}</div>}</div>})}</div>}</CardContent></Card>
 <Card><CardHeader><CardTitle>{c.guidance}</CardTitle><CardDescription>{c.guidanceDesc}</CardDescription></CardHeader><CardContent className="space-y-3">{c.guides.map((guide,i)=><div key={guide} className="border-l-2 pl-4 py-1"><p className="text-sm"><strong>{i+1}.</strong> {guide}</p></div>)}</CardContent></Card></div>
 <Dialog open={showDialog} onOpenChange={setShowDialog}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{c.dialog}</DialogTitle><DialogDescription>{c.dialogDesc}</DialogDescription></DialogHeader><form onSubmit={handleSubmit} className="space-y-4">{formError&&<div className="rounded-md bg-destructive/20 p-3 text-sm text-destructive">{formError}</div>}<div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label={`${c.animal} *`}>{animals.length===0?<div className="rounded-md border p-3 text-sm">{c.noAnimals}</div>:<select value={formData.animal_id} onChange={e=>setFormData({...formData,animal_id:e.target.value})} className="w-full rounded-md border border-border bg-input px-3 py-2 text-sm" required><option value="">{c.select}</option>{animals.map(a=><option key={a.id} value={a.id}>{a.animal_id} - {a.name||c.unnamed}</option>)}</select>}</Field><Field label={`${c.testDate} *`}><input type="date" value={formData.test_date} onChange={e=>setFormData({...formData,test_date:e.target.value})} className="w-full rounded-md border border-border bg-input px-3 py-2 text-sm" required/></Field><NumberField label="BHB (mmol/L)" value={formData.bhb} step="0.01" onChange={v=>setFormData({...formData,bhb:v})}/><NumberField label={c.totalProtein} value={formData.total_protein} step="0.1" onChange={v=>setFormData({...formData,total_protein:v})}/><NumberField label={`${c.magnesium} (mmol/L)`} value={formData.magnesium} step="0.01" onChange={v=>setFormData({...formData,magnesium:v})}/><NumberField label={c.calcium} value={formData.calcium} step="0.01" onChange={v=>setFormData({...formData,calcium:v})}/><NumberField label={`${c.glucose} (mg/dL)`} value={formData.glucose} step="0.1" onChange={v=>setFormData({...formData,glucose:v})}/></div><Field label={c.notes}><textarea placeholder={c.notesPlaceholder} value={formData.notes} onChange={e=>setFormData({...formData,notes:e.target.value})} className="w-full resize-none rounded-md border border-border bg-input px-3 py-2 text-sm" rows={3}/></Field><div className="flex justify-end gap-2 pt-4"><Button type="button" variant="outline" onClick={()=>setShowDialog(false)}>{c.cancel}</Button><Button type="submit" disabled={formLoading}>{formLoading?c.saving:c.save}</Button></div></form></DialogContent></Dialog></AppLayout>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm font-medium text-muted-foreground">{icon}{label}</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{value}</div></CardContent></Card>}
function Param({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{value}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><label className="text-sm font-medium">{label}</label>{children}</div>}
function NumberField({label,value,step,onChange}:{label:string;value:string;step:string;onChange:(v:string)=>void}){return <Field label={label}><input type="number" step={step} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-md border border-border bg-input px-3 py-2 text-sm"/></Field>}
